.eslintrc

Now that these rules are working, we don't need to explicitly enable them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1785)

Bug 1289138 - Remove explicit enabling of rules that are enabled by default

---

tests/etl/test_job_loader.py
tests/sample_data/pulse_consumer/transformed_job_data.json
treeherder/etl/job_loader.py

errorsummary logs containing failure lines are, for historical reasons,
not supplied as normal logs, but are in the jobInfo property of TC
submissions. Therefore in order to be processed as for buildbot we need
to extract this data from there and add it to the other log data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1777)

Bug 1294149 - Process errorsummary logs from TaskCluster submissions.

---

treeherder/config/settings.py

ActiveData's scraping of Treeherder's API has caused responsiveness and performance issues for other users of Treeherder on several occasions, so is being blocked until we can decide upon a less detrimental way for ActiveData to obtain this data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1798)

Bug 1289830 - Block ActiveData's user agent due to excessive requests

---

.travis.yml
puppet/manifests/classes/elasticsearch.pp
puppet/manifests/classes/init.pp

* Travis: Updates Elasticsearch to 2.3.5 (for consistency with Vagrant, since it was pulling latest from the repo) and cleans up the install steps.
* Vagrant: Switches from `openjdk-7-jre` to the smaller `openjdk-7-jre-headless`, since Elasticsearch doesn't need the additional 144 dependencies of the former.
* Vagrant: Switches to downloading the Elasticsearch .deb archive manually and installing with dpkg (rather than using apt-get) - to reduce complexity & make more consistent with Travis.
For further details see the individual commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1795)

Bug 1296267 - Use the same version of Elasticsearch on Travis/Vagrant

---

ui/js/controllers/bugfiler.js

Breaking this out so it can land independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1771)

Bug 1278746 - Skip over versions that are is_active: false

---

treeherder/model/fixtures/repository.json

I'm currently working on setting up a repository that is intended for providing examples, best practices, testing examples and other templates that are useful for general add-on development especially for test pilot and system add-ons.
One of the pieces I'm adding is taskcluster integration. I will hopefully land that on master later today once github-taskcluster is working again.
In the meantime, I'd like to get treeherder set up ready for the repository so that I can demonstrate the integration available, and also use it to test out the current integration and work out if there's any missing bits or bugs that we need to get fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Bug 1297671 - Add the example-addon-repo repository

---

Gruntfile.js
npm-shrinkwrap.json
package.json
ui/js/models/resultsets_store.js

* Use babel to make transpile ES6 code to ES5
* Add a trivial use of the => function to make sure this actually works
in production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1807)

Bug 1297722 - Fix ES6 use in production

---

ui/plugins/auto_classification/main.html

So, this PR as-is:
1) Disables the "ignore others" button and changes the title for the button when not signed in.
2) Changes the titles for the line-specific "save" buttons and a select dropdown, and attempts to disable both when not signed in.
But those attempts to disable them don't appear to work, and I don't know why, since "loggedIn()" is working just above the ng-disabled's as part of the titles... @jgraham ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1784)

Bug 1294746 - Disable more autoclassify buttons when not logged in

---

tests/conftest.py
tests/etl/test_perf_data_adapters.py
tests/ui/mock/job_group_list.json
tests/ui/mock/job_type_list.json
tests/webapp/api/test_performance_data_api.py
treeherder/client/thclient/client.py
treeherder/model/management/commands/import_reference_data.py
treeherder/model/migrations/0037_remove_refdata_activestatus.py
treeherder/model/models.py
treeherder/webapp/admin.py

The field is never updated or used in anything but repository, so let's just
take them out for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1809)

Bug 1178395 - Remove active status from most reference data tables

---

ui/js/controllers/logviewer.js

When searching for the right step to jump to previously, we used
an algorithm that assumed we would have more than one step, which
isn't guaranteed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1812)

Bug 1298464 - Handle errors in jobs with only one step

---

treeherder/etl/buildapi.py

They were only supposed to be used for debugging, but we haven't even
been using them for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1827)

Bug 1299861 - Stop storing buildapi_running artifacts

---

ui/js/filters.js
ui/plugins/auto_classification/main.html

This option just stops checking if we're in a tag. Nothing appears to be worse off for this, and it highlights more things that should be highlighted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1818)

Bug 1269416 - Just stop checking if we're in a tag

---

requirements.txt
treeherder/config/settings.py

Since it clobbers the settings we need to use on Heroku for making memcached connections via stunnel. In addition, it made the cache configuration very opaque, and doesn't use the latest best practices suggested on:
https://www.memcachier.com/documentation#django
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1824)

Bug 1291307 - Stop using django-heroku-memcacheify

---

Gruntfile.js
bin/post_compile

Previously `<site-root>/revision.txt` would 404 if `SERVE_MINIFIED_UI` was unset on Heroku, which would then cause the next deploy to fail.
It's now made available in both the `ui/` and `dist/` directories, so it can be found regardless of the value of `SERVE_MINIFIED_UI`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1832)

Bug 1299443 - Fix revision.txt on Heroku when SERVE_MINIFIED_UI is unset

---

ui/js/controllers/jobs.js
ui/partials/main/jobs.html

When you select a single job and then press the cancel all jobs button,
the behavior of the cancel all jobs button so it cancels just the selected
job.
Prior to this patch, the selected job can be canceled no matter which
cancel all jobs button is clicked, even if the selected job is from a
different push. 
This patch only activates the selected job behavior when
the selected job is from the push where the cancel all jobs button was
pressed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1814)

Bug 1298539 - Make sure canceling a single job only works from the same push

---

treeherder/webapp/api/runnable_jobs.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1834)

Bug 1330795 - Skip taskcluster jobs without treeherder metadata in runnable jobs

---

tests/log_parser/test_error_parser.py
treeherder/log_parser/parsers.py

Upcoming changes in bug 1295380 will change log output for many tests
in TaskCluster resulting in lines being prefixed with a timestamp and
the task step name. Unless these line prefixes are handled, it
confuses the error parser.
This commit detects logs as coming from TaskCluster and strips their
line prefix accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1836)

Bug 1297184 - Strip TaskCluster log prefix when parsing logs

---

treeherder/model/fixtures/repository.json

Some of these were outdated, or not quite a match to what we get from pulse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1839)

Bug 1301739 - Fix Github repo urls so pulse data ingestion will work

---

treeherder/autoclassify/tasks.py
treeherder/config/settings.py

Since it occasionally causes queue backlogs and needs tweaking to be useful for the sheriffs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1838)

Bug 1301434 - Disable the detect-intermittents task by default

---

tests/ui/unit/filtersSpec.js
ui/js/filters.js

The filter as it was written returned already returned a valid string, but apparently somewhere between angular getting the filtered string back from the filter and it getting injected into the page as HTML, the quotes were breaking the element, causing it to be rendered incorrectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1843)

Bug 1301906 - Make sure linkifyClassifications filter gives usable results

---

bin/run_celery_worker_buildapi
treeherder/etl/resultset_loader.py
treeherder/etl/tasks/pulse_tasks.py

Also make the pulse tasks retryable_tasks as well as
add a field to logging for pulse resultsets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1847)

Bug 1302529 - Add store_pulse_resultsets to bin script

---

docs/conf.py

This fixes Bugzilla bug [1302754](https://bugzilla.mozilla.org/show_bug.cgi?id=1302754).
Our footer copyright appeared to be out of date. I dug around to see if there's a way to have it update on the fly but with Sphinx it appears to be a manual process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1852)

Bug 1302754 - Update the docs copyright to 2016

---

ui/logviewer.html

We need to update the template value on angular digest cycles, because
we can't count on the "raw log url" being available when we first render the
template (the job may still be loading).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1850)

Bug 1302224 - Make sure raw log link in logviewer works

---

Procfile
bin/run_celery_worker_log_parser

This should increase throughput, especially in cases where we are backlogged
due to network latency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1857)

Bug 1303055 - Double the number of log processing workers

---

treeherder/etl/common.py
treeherder/model/derived/jobs.py

The only one that was actually used was JobDataError, which doesn't have any
advantage over the more generic ValueError.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1858)

Bug 1185039 - Remove JobData* classes

---

treeherder/model/management/commands/run_sql.py

This prevents changes from being discarded if the DB connection timed out between the `.execute()` call being made, and it completing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1859)

Bug 1303102 - Use autocommit for the run_sql command

---

ui/js/controllers/jobs.js

The /jobdetail/ endpoint doesn't currently support filtering by job id,
we need to pass the guid instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1861)

Bug 1303433 - Fix cancelling a single job from the UI

---

ui/plugins/pinboard.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1849)

Bug 1302545 - Remove the Ctrl-Enter bypass for not fully classifying failures

---

ui/plugins/controller.js

Since after bug 1280039, retriggers error with:
"Unable to send retrigger: Must also filter on repository if filtering on job id".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1868)

Bug 1304253 - Pass the repository name to the API when retriggering

---

treeherder/webapp/api/jobs.py

In the /jobs/XXXX/ endpoint, we were just keying off the job id when
trying to figure out which log information to return. This could result
in additional (incorrect) data being returned for the case that
there were jobs with the same project specific id value in multiple
repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1864)

Bug 1304091 - For job information, don't return incorrect job log links

---

ui/js/controllers/main.js
ui/partials/main/thWatchedRepoNavPanel.html

This disables the checkbox for the final selected tier so that you can't unselect all tiers, avoiding the "bug" where tiers 1 and 2 get automatically reselected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1841)

Bug 1240211 - Disable the checkbox for the single remaining selected tier

---

ui/js/values.js

This PR creates a space for 32 bit Windows builds shown by _build_ platform rather than _test_ platform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1867)

Bug 1304354 - add a row for 32 bit Win 2012 builds

---

ui/js/controllers/main.js
ui/partials/main/jobs.html
ui/partials/main/thActionButton.html
ui/partials/main/thPinboardPanel.html
ui/plugins/pinboard.js

This work hopefully fixes Bugzilla bug [1301081](https://bugzilla.mozilla.org/show_bug.cgi?id=1301081).
This disables pinboard save menus when appropriate, and alters: **Save** (button), **Save classification only** (menu), **Save bugs only** (menu), **Retrigger all** (menu). 
The use cases are a bit complex, and span combinations of:
* try vs. non-try repos
* logged in vs. logged out
* related bugs only
* classifications only
* default classification vs. non-default (eg. intermittent vs. others)
Before:
Proposed (Logged out with default settings they are dimmed - unless you are on Try):
Everything seems generally ok, but there may be things I've missed since I've not been doing daily development. I've added a `$scope.user.loggedin` test to `canSaveClassifications()` as I'm not sure why …

Bug 1301081 - Disable various menus when appropriate

---

ui/css/treeherder-resultsets.css
ui/js/controllers/jobs.js
ui/partials/main/jobs.html

This also reverts the previous behaviour where we'd cancel a single job
if one was selected. This new approach hopefully makes it harder to
accidentally delete all jobs when only intending to cancel one, while
still being intuitive if that's really what you want to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1874)

Bug 1293264 - Show distinctive banner when user tries to cancel all jobs

---

requirements/common.txt

To pick up the security fix:
https://www.djangoproject.com/weblog/2016/sep/26/security-releases/
https://docs.djangoproject.com/en/stable/releases/1.8.15/
https://github.com/django/django/compare/1.8.14...1.8.15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1878)

Bug 1302689 - Update Django from 1.8.14 to 1.8.15

---

docs/common_tasks.rst

This fixes Bugzilla bug [1306369](https://bugzilla.mozilla.org/show_bug.cgi?id=1306369).
This updates the docs log parser example to a test which currently exists in the repo. I chose the most recently touched test, which in this case is test_tasks.py.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1881)

Bug 1306369 -  Update common tasks log parser doc example

---

ui/js/directives/treeherder/persona.js
ui/js/models/error.js
ui/js/services/pinboard.js

**1) Make ThModelErrors use HTTP status code if no API message**
Previously if the server response wasn't valid json with a `detail` attribute, only the generic message from the `ThModelErrors.format()` call (eg "Unable to cancel job") would be displayed.
Now, `format()` will fall back to including the HTTP status code (and corresponding text description of that code) too.
We intentionally don't display the server response if it's not valid json, since in this case it's likely several hundreds lines of HTML from the load balancer. (And users can always inspect the response manually.)
**2) Use ThModelErrors for classification and persona errors**
There are still other API error cases that aren't yet using `ThModelErrors`, however these two cases are the most important for now, since …

Bug 1290082 - Fix the display of server/API error messages in the UI

---

ui/js/reactselect.js

Adds a keyboard shortcut to make ctrl+a select all items in reactlist
components like the exclusion lists in the admin view. This is default
behavior in chrome/ium, but not FF or IE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1887)

Bug 1066724 - Make ctrl+a select all in focused exclusion lists

---

ui/partials/main/thMultiSelect.html

In the exceptions page of the admin section, the items can now be moved from the left list to the right list (or from included to excluded and viceversa) by double clicking on them.
Refers to: https://bugzilla.mozilla.org/show_bug.cgi?id=1066722

Bug 1066722 - Support double click for moving an item from a list to the other in the exceptions page

---

ui/plugins/failure_summary/main.html

This makes the button appear for anyone that is logged in and either in
the is_staff group or has '&bugfiler' in the URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1891)

Bug 1306859 - Enable the bug filer for is_staff users

---

ui/js/controllers/bugfiler.js

For whatever reasons, xperf failures are logged as "TEST-UNEXPECTED-FAIL :
xperf :" instead of "TEST-UNEXPECTED-FAIL | xperf |", which caused issues
with the bugfiler trying to split the failure line on |s. This patches
over the problem by not letting the summary array be reduced if there's
only one item left in the array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1890)

Bug 1306889 - Help ensure bugfiler doesn't choke on xperf failures

---

ui/css/treeherder-info-panel.css

The menus in the app header navbar get a subtle grey background on hover.
For some reason, the same is not applying to the retrigger/backfill menu.
This patch just forces the same style change to occur for this menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1893)

Bug 1205747 - Ensure the retrigger/backfill menu gets styled

---

Procfile

This works around the apparent pre-existing memory leak until we're able to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1899)

Bug 1307785 - Lower gunicorn --max-requests on Heroku to match SCL3

---

requirements/common.txt
tests/autoclassify/test_classify_failures.py
tests/autoclassify/test_detect_intermittents.py
tests/autoclassify/utils.py
tests/conftest.py
tests/e2e/test_client_job_ingestion.py
tests/log_parser/test_crossreference_error_lines.py
tests/log_parser/test_tasks.py
tests/model/derived/test_artifacts_model.py
tests/model/derived/test_jobs_model.py
tests/webapp/api/test_artifact_api.py
tests/webapp/api/test_classified_failure.py
tests/webapp/api/test_failureline.py
tests/webapp/api/test_text_log_summary_lines.py
treeherder/autoclassify/management/commands/autoclassify.py
treeherder/config/settings.py
treeherder/model/derived/artifacts.py
treeherder/model/derived/jobs.py
treeherder/model/error_summary.py
treeherder/model/models.py
treeherder/webapp/api/failureline.py
treeherder/webapp/api/jobs.py
treeherder/webapp/api/text_log_summary_line.py
ui/index.html
ui/js/models/bug_suggestions.js
ui/plugins/failure_summary/controller.js

Instead, generate the data when required. We will store the return value
of this in memcache for a day to ensure things are responsive for the sheriffs
when classifying recent failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1871)

Bug 1281820 - Stop using bug suggestions artifacts

---

ui/js/directives/treeherder/clonejobs.js
ui/partials/main/jobs.html

Here's my attempt - the `.ready` class is added to a new, hidden `span` once the first resultset has loaded its jobs and appended them to their containing element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1904)

Bug 1263236 - Indicate jobs are ready in the DOM

---

tests/etl/test_bugzilla.py
tests/model/test_bugscache.py
tests/sample_data/bug_list.json
treeherder/model/models.py

It appears that the intent of this code is to to a phrase match of the
search string against the bug summary for relevance matching. However
the code incorrectly tried to quote the string and as a result failed
to handle special characters in the AGAINST clause (e.g. + - ~ >
etc.). This change simply removes any existing quote characters from
the string and places the entire thing in quotes. Per the MySQL
documentations:
> A phrase that is enclosed within double quote (") characters
matches only rows that contain the phrase literally, as it was
typed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1914)

Bug 1283859 - Fix quoting of MATCH ... AGAINST in bugscache search

---

tests/sample_data/logs/mozilla-esr17_xp_test_pgo-mochitest-browser-chrome-bm74-tests1-windows-build12.jobartifact.json
tests/sample_data/logs/ux_ubuntu32_vm_test-jetpack-bm67-tests1-linux-build16.jobartifact.json
treeherder/log_parser/parsers.py
ui/plugins/job_details/main.html

This hopefully fixes Bugzilla bug [1294525](https://bugzilla.mozilla.org/show_bug.cgi?id=1294525), or is an inspiration for similar fix :) This splits long TinderboxPrint lines like:
`TinderboxPrint:<a href=https://hg.mozilla.org/mozilla-central/rev/1a5b53a831e5 title='Built from mozilla-central revision 1a5b53a831e5'>moz:1a5b53a831e5</a>`
into manageable chunks and reduces the chance it bumps up against the 125 character string limit, which we'd like to keep.
Bug, note the "moz" line:
Proposed, back to it's prior appearance:
Nightly **51.0a1 (2016-09-12) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1848)

Bug 1294525 - Break out Tinderbox fields in log parser

---

.travis.yml
puppet/files/treeherder/env.sh
treeherder/config/settings.py
treeherder/model/models.py

**1) Bug 1288369 - Use TLS when connecting to RDS from Vagrant**
Previously if someone set `DATABASE_URL` in their Vagrant environment to a remote RDS instance, TLS wouldn't have been used. Now, using TLS depends not on the `IS_HEROKU` environment variable (which we should stop using anyway, since it goes against the 12-factor methodology), but the DB hostname itself.
The CA bundle path has been made relative, to allow it to work inside Vagrant as well as on Heroku.
I've bundled this change in here, since the refactor helps with the below.
**2) Bug 1310016 - Remove read_only DB config**
Since we no longer have a master-slave setup, and in all environments DATABASE_URL is identical to DATABASE_RO_URL.
**3) Bug 1310016 - Persist DB connections for 5 mins to improve performance**
By default …

Bug 1310016 - Persist DB connections for 5 mins to improve performance

---

tests/log_parser/test_job_artifact_builder.py

This makes the job_artifact builder consistent with the log_view_artifact builder, in the sense it will facilitate exporting test files now for both.
I re-ordered `exp` so it presents in the same order as in log_view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1920)

Bug 1306878 - Add job artifact test data generation

---

bin/vendor-libmysqlclient.sh

The packages have been moved under the archives path, since there are newer releases now available. The official download link has remained unchanged, however it's a 302 redirect to a non-HTTPS version of these links, so we intentionally deep-link, even if it means the URLs will occasionally need updating.
Fixes the 404 whilst Vagrant provisioning, and failures that would occur with a clean cache on Heroku/Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1931)

Bug 1310727 - Switch to new download URLs for libmysqlclient

---

ui/js/models/resultsets_store.js

Instead, just calculate on the fly with the job information we have.
This makes the display of the first job data about 3 seconds faster in
my preliminary testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1912)

Bug 1308782 - Don't download job and group data on load

---

tests/autoclassify/test_classify_failures.py
tests/autoclassify/test_detect_intermittents.py
tests/log_parser/test_crossreference_error_lines.py
tests/log_parser/test_store_failure_lines.py
treeherder/autoclassify/autoclassify.py
treeherder/autoclassify/detect_intermittents.py
treeherder/autoclassify/management/commands/autoclassify.py
treeherder/autoclassify/management/commands/detect_intermittents.py
treeherder/autoclassify/matchers.py
treeherder/autoclassify/tasks.py
treeherder/log_parser/crossreference.py
treeherder/log_parser/failureline.py
treeherder/log_parser/management/commands/crossreference_error_lines.py
treeherder/log_parser/tasks.py
treeherder/log_parser/utils.py
treeherder/model/derived/jobs.py
treeherder/model/models.py

Now that log information is in the main treeherder database use the id
information there as the input to the log parsing and autoclassification
tasks.
As part of the same change there is a mild refactor of the
autoclassification related tasks to not go through the call_command
infrastructure as this is just unnecessary overhead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1932)

Bug 1310972 - Use job id as input to log parsing tasks

---

ui/plugins/controller.js

Adding &autoclassify to the url still allows it to be enabled.
This will allow the feature to be refactored rather than spending
lots of time investigating sub-issues in the current implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1948)

Bug 1312459 - Disable autoclassify panel by default

---

Vagrantfile

Vagrant wants to use Virtualbox by default on Windows. Unfortunately, Virtualbox doesn't work when Hyper-V - the VM provider built into Windows itself - is running.
This commit modifies the Vagrantfile to support Hyper-V.
The obvious change is the addition of a new provider block for Hyper-V. It overrides the default box to use one that is compatible with Hyper-V.
The non-obvious change is the refactor of the provisioner logic.
The Hyper-V box doesn't have Puppet installed. So we need to install Puppet in a provisioner before the Puppet provisioner runs. But due to the way Vagrantfiles are evaluated, we can't just insert the provisioner in the hyperv provider block. So, this commit relies on the fact that Vagrantfiles are really Ruby scripts that return a data structure. The code for …

Bug 1312544 - Support for Hyper-V

---

tests/etl/test_classification_mirroring.py
treeherder/etl/classification_mirroring.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1952)

Bug 1301729 - Use job's ref_data_name for buildname w/ classification mirroring

---

ui/plugins/auto_classification/main.html

This fixes Bugzilla bug [1313074](https://bugzilla.mozilla.org/show_bug.cgi?id=1313074).
This removes what appears to be an unused class `best-classification-star` from the auto classification panel markup. As far as I can tell, it isn't referenced in the repo.
I had removed it as part of bug [1305565](https://bugzilla.mozilla.org/show_bug.cgi?id=1305565) but that won't likely land with the component based panel work under way. So removing it here in case it's forgotten about.
Adding @jgraham for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1956)

Bug 1313074 - Remove unused class from autoclassification panel

---

treeherder/log_parser/crossreference.py
treeherder/log_parser/tasks.py

In the short term this change is a small negative as it will slow down
autoclassification tasks. However it's a necessary step to future
changes that will put the autoclassification results on the text log
error table and allow autoclassification of non-structured lines.
As part of this, we remove the use of callback tasks and just schedule
the crossreference task to run after the parser tasks. This is simpler
and reflects the fact that we only schedule one parser task at a time
now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1955)

Bug 1310974 - Perform autoclassification after crossreferencing error lines

---

ui/js/controllers/main.js
ui/js/providers.js
ui/partials/main/thShortcutTable.html
ui/plugins/controller.js

This work fixes Bugzilla bug [1310825](https://bugzilla.mozilla.org/show_bug.cgi?id=1310825).
This adds a keyboard shortcut **_t_** which cycles through the visible tabs for a selected job. I'd like to spend some more time with local integration testing; but everything seems to be working well. Perf jobs which have 5 tabs cycles properly, other jobs with 4 tabs cycle properly, cycling with other UI like the pinboard open seems fine, etc.
I didn't test the Auto Classification tab yet, but I don't think it would have issues. I find it very pleasant to use in conjunction with n,p,j,k during job navigation.
Nightly **52.0a1 (2016-10-09) (64-bit)**
Chrome Latest Release **53.0.2785.143 (64-bit)**
Adding @KWierso and @camd for feedback or review.
---
This change is [<img …

Bug 1310825 - Add a tab navigation shortcut

---

puppet/files/mysql/my.cnf

Stage/prod use the RDS parameter group defined here:
https://github.com/mozilla-platform-ops/devservices-aws/blob/master/treeherder/rds.tf
The slow query log changes aren't really useful for Vagrant/Travis, but it seemed less confusing than saying the files should be kept in sync minus a bunch of exceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1958)

Bug 1313236 - Sync Vagrant/Travis MySQL config with that on production

---

ui/js/controllers/bugfiler.js

This just makes sure that when the selected failing job is a wpt test, the
Testing :: web-platform-tests product/component pair is offerred as a
suggestion.
This also helps make sure we don't try to use "TEST-UNEXPECTED-foo" as a
potential path root for the initial product searches, because that makes
the feature fail to find anything if the "TEST-UNEXPECTED-foo" isn't
omitted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1909)

Bug 1308669 - BugFiler product selection improvements

---

treeherder/model/fixtures/repository.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1963)

Bug 1313698 - Disable perf alerts for fx-team as it is read-only

---

treeherder/model/fixtures/repository.json

This branch will be used for the Quantum Render work, and we want it displayed on TreeHerder as there will be CI jobs running on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1966)

Bug 1314079 - Reactivate the projects/graphics branch

---

Vagrantfile
docs/common_tasks.rst
docs/installation.rst
docs/rest_api.rst
puppet/files/varnish/default.vcl
puppet/manifests/vagrant.pp
treeherder/config/settings.py

I think I should also address ``security.W005`` in the  ``SILENCED_SYSTEM_CHECKS`` of ``settings.py``.  Though it seems the tests need it.  Ed: would you advise the right thing to do here?  :)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1974)

Bug 1315818 - Vagrant: Use localhost instead of local.treeherder.m.o

---

requirements/common.txt
treeherder/config/settings.py

1) Use the domain from `SITE_URL` to set `ALLOWED_HOSTS`:
One of the Django 1.8.16 security changes means that `ALLOWED_HOSTS` is now used even when `DEBUG` mode is enabled. As such, we must now set it in the Vagrant environment.
2) Update Django from 1.8.15 to 1.8.16:
https://www.djangoproject.com/weblog/2016/nov/01/security-releases/
https://docs.djangoproject.com/en/stable/releases/1.8.16/

Bug 1317682 - Update Django from 1.8.15 to 1.8.16

---

ui/css/treeherder-global.css
ui/css/treeherder-info-panel.css
ui/partials/main/thJobDetailsRetriggerMenu.html
ui/plugins/pluginpanel.html

This work fixes Bugzilla bug [1207460](https://bugzilla.mozilla.org/show_bug.cgi?id=1207460).
This splits the retrigger/backfill menu back out into separate buttons. I managed to consume only 2px more in width for the job-details-panel than what we had before, since it appears the reftest and cancel icon never coexist - we achieved 1 icon of economy, while adding the backfill icon.
Current:
Proposed:
My screen grab above is a bit misleading in the sense I'm showing the disabled tooltip, with the enabled appearance, just to illustrate the color in the PR.
I provided a selection of other possible svg icons other than `fa-arrow-down` in the bug [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1207460#c9). @jgraham favored it as a start point.
The `cyan` color was a bit arbitrary, other …

Bug 1207460 - Split retrigger menu into separate btns

---

ui/css/treeherder-job-buttons.css
ui/index.html

Do this by making the job groups a clickable button, which is incidentally
also better behaviour for screen readers (since it gives a hint that the
element is clickable)

Bug 1318893 - Fix click behaviour for job groups

---

ui/partials/main/jobs.html

They were defined as spans which meant:
1. They weren't a proper click target for screen readers
2. They were still selectable even if disabled (e.g. try to click on cancel as not logged-in user on try).
Fixing this is simple, so let's just do it.

Bug 1319146 - Render resultset buttons as actual buttons, not spans

---

Procfile
bin/run_celery_worker
bin/run_celery_worker_buildapi
bin/run_celery_worker_hp
bin/run_celery_worker_log_parser
bin/run_celery_worker_pushlog
bin/run_celerybeat
bin/run_gunicorn
docs/troubleshooting.rst
puppet/files/treeherder/.profile
puppet/manifests/classes/treeherder.pp
treeherder/config/settings_local.example.py

Outputting to the console rather than a log file:
* is more user-friendly during development
* is more consistent with Heroku
* means the Vagrant-specific Django LOGGING config is now closer to the one in settings.py, and so more easily combined with it
Both gunicorn and celery default to outputting to stdout/stderr, so the `logfile` options can be omitted entirely.

Bug 1318021 - (Part 1) Vagrant: Stop using log files for gunicorn/celery output

---

treeherder/etl/common.py
treeherder/log_parser/artifactbuildercollection.py

Cloud mirror cases periodic spikes in response time (bug 1305768), so we now use the new `x-taskcluster-skip-cache` header to skip it when downloading eg logs/taskgraphs/...:
https://docs.taskcluster.net/reference/platform/queue/references/api#getArtifact
Since the urllib2 usage is going to be replaced with the common requests code, and since this is hopefully a short-term workaround, hardcoding this at point of usage should be fine.

Bug 1319441 - Skip cloud mirror when downloading logs from Taskcluster

---

.coveragerc
.gitignore
docs/pulseload.rst
puppet/manifests/vagrant.pp
treeherder/config/settings.py
treeherder/config/settings_local.example.py

It has been the source of Vagrant-environment confusion multiple times in the past, and in an environment-variable-centric world really isn't the best way to achieve local custom configuration.
Specifically:
* It doesn't show up in `git status` (by design) so people don't even realise they are running custom settings, that cause later breakage (bug 1291038 and bug 1320479 are just two examples).
* It exists on the host, and not in the VM, so persists even after a `vagrant destroy`, thwarting people's attempts to reset back to defaults.
* The only real use-case for it is IMO actually an anti-feature, in that it encourages people to squirrel away development environment tips & tricks, rather than landing them on master where everyone could benefit. For one-off local changes people should …

Bug 1318011 - Remove support for settings_local.py

---

ui/css/treeherder-global.css
ui/css/treeherder-info-panel.css
ui/css/treeherder-pinboard.css
ui/js/providers.js
ui/js/services/pinboard.js
ui/plugins/controller.js
ui/plugins/pinboard.js
ui/plugins/pluginpanel.html

This work fixes Bugzilla bug [1319300](https://bugzilla.mozilla.org/show_bug.cgi?id=1319300).
This moves the pin counter from the "Pin this job" button to the Pinboard collapse/expand button, as we had a user recently who interpreted its current location to mean job details actionbar buttons operate on all pinned jobs, which they do not.
The 'superscript' counter offset position below is intentional, to cue the user there is more "in" that button, particularly when closed.
I changed the closed Pinboard button to the native pinboard color, which seemed to make sense again for new users, to highlight its workflow importance.
Here's a static screen grab, showing the Pinboard closed, with 2 pinned jobs.
The counter pulses when a job is pinned. This lets the user know the pin occurred, …

Bug 1319300 - Move the pin counter to the pinboard btn

---

ui/css/treeherder-navbar-panels.css
ui/index.html
ui/js/controllers/main.js
ui/partials/main/thTreeherderUpdateBar.html
ui/partials/main/thWatchedRepoNavPanel.html

This lets the user know if the server's version has changed since loading the page. 
On the initial page load, a request is made to load revision.txt. If it can load revision.txt (doesn't appear to be present if I'm running with vagrant via bin/run_gunicorn or manage.py, though for testing purposes, I manually created the file and it seems to work), it stores the revision as $rootScope.serverRev. 
Responses from the resultset api now include the current revision used on the server side.
The two values are compared on the UI side, and if they differ, a notification is shown to the user.
I'd be open to better ideas on how to get the server-side revision rather than adding gitpython, allowing raw git commands to be run on the server.
---
This change is [<img …

Bug 1088204 - Notify the user when the server's revision has changed from when the page was loaded

---

ui/css/treeherder-info-panel.css

This is a supplemental tweak omitted from PR https://github.com/mozilla/treeherder/pull/1992.
We add a suitable btn line so we get dark buttons in the action bar for both retrigger and backfill. Illustrating the logged out, non-hover appearance, below.
Current:
Proposed:
Nightly **53.0a1 (2016-11-29) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2010)

Bug 1207460 - Add actionbar button color

---

tests/conftest.py
tests/model/test_job_notes.py
tests/webapp/api/test_note_api.py
tests/webapp/conftest.py
treeherder/model/derived/jobs.py

We were always resetting the failure classification to an invalid value
when the last job note was deleted for a job, but we didn't notice it
before because we didn't have foreign key validation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2008)

Bug 1318474 - Fix job note deletion

---

treeherder/model/migrations/0043_bugscache_cleanup.py
treeherder/model/models.py

* Switches `id` from an auto_increment to an unsigned int.
* Stops allowing null/blank values for status/modified.
* Drops unused fulltext indexes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2004)

Bug 1304047 - Clean up the Bugscache schema

---

treeherder/model/derived/jobs.py

We still need to pass in old-style job id's for this, until the supporting
code is rewritten.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2016)

Bug 1321895 - Fix exception when cancelling a job

---

ui/plugins/controller.js

This tweak hopefully fixes Bugzilla bug [1321910](https://bugzilla.mozilla.org/show_bug.cgi?id=1321910).
I believe `backfillButtonTitle()` asks for the `$scope.currentRepo` object in the markup before it's defined during page load. So we'll declare them first in the function, and let Treeherder reset it again during the rest of the load process.
I think this will quiet down the console errors which were occurring. Perhaps there is a better or more economical way to do it. I'll dig around but leave this up for a review in the meantime.
Nightly **53.0a1 (2016-12-02) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2018)

Bug 1321910 - Fix backfill title console error on page load

---

ui/js/controllers/main.js

I think this should remove the spam when running locally. Unsure if I even need this, we could probably do nothing in the failure case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2019)

Bug 1321920 - Switch the revision checker failure case from log() to debug()

---

.travis.yml

**1) Switch to the newer sudo-enabled image**
The image has received several updates, including now defaulting to mysql-server 5.6:
https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/
...which means we can skip the 20-25s install of mysql-server-5.6.
The issue with Java on the newer image has now been fixed, so we no longer need to remain on the older (`group: deprecated`) release.
**2) Switch the container builds to the new Trusty beta**
Travis have just announced a beta for container-based Ubuntu Trusty builds:
https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/
This means the linter runs can now run on the same version of Ubuntu used by the other tests and production. This also reduces runtime since Travis can skip the glibc patching step required on …

Bug 1323559 - Travis: Switch to the newer Ubuntu Trusty images

---

treeherder/model/migrations/0044_add_similar_job_indexes.py
treeherder/model/models.py
treeherder/webapp/api/jobs.py

* Instead of ordering by push time (which is a foreign key), order by job
start time.
* Add composite indexes to speed up the query
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2015)

Bug 1246196 - Speed up loading similar jobs

---

tests/webapp/api/test_jobs_api.py
treeherder/model/migrations/0046_remove_flat_exclusion_column.py
treeherder/model/models.py
treeherder/webapp/api/serializers.py

The way we had written things, a "flat exclusion" information (which
is essentially just a cache) had to be rewritten for *every* repository
on submission of a new job, even though the new job would apply to
only one repository. Let's fix this by just calculating this information
on demand (most of the time this should be very fast, as we already
store the final data in memcache)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2009)

Bug 1320805 - Create per-project exclusion lists on-demand

---

ui/js/directives/treeherder/clonejobs.js

By default, ngReact watches component props using an expensive deep
$watch. This made the revision list react components noticeably slow
down the UI when clicking a job button. This commit changes the watch
depth for the revision list components to lighten the load.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2041)

Bug 1242905 - Fix watch depth in react revisions

---

ui/js/values.js

I noticed most recent Sync intermittents ended up in "Core :: Web Services". Most of the code in `services/` is Sync and FxA, so let's suggest those for intermittent failures instead. We'll triage bugs in those components weekly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2051)

Bug 1326314 - Improve Bugzilla component suggestions for services

---

requirements/common.txt
treeherder/config/settings.py
treeherder/config/urls.py
treeherder/webapp/api/serializers.py

**1) Add an explicit `fields` option to all ModelSerializers**
Since in django-rest-framework 3.5.0+ each `ModelSerializer` must include either a `fields` option or an `exclude` option:
http://www.django-rest-framework.org/topics/3.4-announcement/#use-fields-or-exclude-on-serializer-classes
@wlach / @camd - whilst this change is a no-op compared to current behaviour, do any of these look like they should actually exclude some fields rather than returning all of them?
**2) Update djangorestframework from 3.3.3 to 3.5.3**
http://www.django-rest-framework.org/topics/3.4-announcement/
http://www.django-rest-framework.org/topics/3.5-announcement/
http://www.django-rest-framework.org/topics/release-notes/#35x-series
https://github.com/tomchristie/django-rest-framework/compare/3.3.3...3.5.3
**3) …

Bug 1324707 - Update django-rest-framework and friends for Django 1.10 compatibility

---

treeherder/config/settings.py

Since the old `TEMPLATE_*` settings have been removed in Django 1.10:
https://docs.djangoproject.com/en/1.10/ref/templates/upgrading/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2054)

Bug 1328270 - Switch to new style Django TEMPLATE settings dict

---

requirements/common.txt

Since it's required by Django and also by our ETL layer and not just by legacy versions of django-rest-swagger, contrary to the previous comment in common.txt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2059)

Bug 1324707 - Re-add PyYAML dependency to requirements/common.txt

---

ui/css/treeherder-info-panel.css
ui/plugins/controller.js
ui/plugins/pluginpanel.html

Create an per-job "extras" job button in Treeherder and put "backfill"
and the current set of taskcluster options (one click loaner, inspect task)
in there, if they exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2052)

Bug 1285007 - Make Taskcluster options more discoverable

---

treeherder/webapp/api/jobs.py

The fields listed must be relational fields - `select_related()` does not control which fields are returned, just which tables are joined.
Under Django <=1.9 any non-relational fields are ignored, however under Django 1.10 these cause errors of form:
"FieldError: Non-relational field given in select_related: 'name'. Choices are: repository_group"
This change is a no-op in terms of generated SQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2061)

Bug 1328294 - Correct select_related() usage inJobDetailViewSet

---

treeherder/embed/templates/embed/resultset_status.html

I also cleaned up some whitespace to make it consistent between the head and body elements (and to get rid of hard tabstops).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2066)

Bug 1329049 - Actually put these styles in a style element.

---

ui/js/components/logviewer/logviewer.js
ui/js/controllers/logviewer.js

Fixes:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://taskcluster.github.io') does not match the recipient window's origin ('https://treeherder.mozilla.org').
We can't use the Treeherder base URL for the target origin, since otherwise once the iframe loads the target will change again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2063)

Bug 1328908 - Fix postMessage error on log viewer pageload

---

requirements/common.txt
tests/test_setup.py

Now that the Django 1.10 compatibility changes have landed via the [deps of bug 1311967](https://bugzilla.mozilla.org/showdependencytree.cgi?id=1311967&maxdepth=1&hide_resolved=0), we're ready to proceed.
**1) Mark test_no_missing_migrations as requiring DB access**
In Django 1.10 the makemigrations command now requires the database (see https://code.djangoproject.com/ticket/25850), so this test must now have the `django_db` annotation.
**2) Update Django from 1.9.12 to 1.10.5**
https://docs.djangoproject.com/en/1.10/releases/1.10/
https://docs.djangoproject.com/en/1.10/releases/1.10.1/
https://docs.djangoproject.com/en/1.10/releases/1.10.2/
https://docs.djangoproject.com/en/1.10/releases/1.10.3/
https://docs.djangoproject.com/en/1.10/releases/1.10.4/ …

Bug 1311967 - Update to Django 1.10

---

ui/css/treeherder-info-panel.css
ui/plugins/pluginpanel.html

This fixes Bugzilla bug [1329040](https://bugzilla.mozilla.org/show_bug.cgi?id=1329040).
This change
* removes some dead Retrigger css
* adds a unique selector id for the new Actionbar menu button for automated testing
* adds a tooltip for it so new users might be more comfortable clicking on the button
Nightly **53.0a1 (2017-01-05) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2065)

Bug 1329040 - Remove dead Retrigger dropdown css

---

tests/test_setup.py

Django 1.10 added a new check changes mode to the `makemigrations` command, which we can use to avoid the hack of checking that the exit code is 1 in the passing case:
https://docs.djangoproject.com/en/1.10/ref/django-admin/#cmdoption-makemigrations-check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2070)

Bug 1328173 - Switch test_no_missing_migrations to using check_changes

---

npm-shrinkwrap.json
package.json
tests/ui/config/karma.conf.js
tests/ui/unit/react/jobSpec.js
tests/ui/unit/react/revisionSpec.js
ui/css/treeherder-resultsets.css
ui/index.html
ui/js/directives/treeherder/clonejobs.js
ui/js/reactjobs.js
ui/js/services/main.js

Two changes:
1. Installs [`ng-react-test-utils`](https://github.com/jrwebdev/ngreact-test-utils) to provide a reusable compile() function for ngreact tests. Previously I just wrote a one-off `compile()` in the revision list test file, but reusing it presented a problem. Setting up browserify for the react tests only seemed like the path of least resistance - if this seems like overkill, I'll see if I can figure something else out.
2. Adds a simple platform name component to start the migration of the job list table to react.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2055)

Bug 1242905 - React component for job list platform names

---

tests/webapp/api/test_runnable_jobs_api.py
treeherder/etl/runnable_jobs.py

We need to set state/result of runnable jobs to "runnable" for this to work,
and that got broken accidentally. Add a unit test so that this doesn't happen
again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2076)

Bug 1330015 - Make "add additional jobs" option work again

---

.travis.yml
bin/pre_deploy
runtests.sh

Django 1.10 added a new `--fail-level` option that allows overriding the default of only exiting 1 for ERROR and above, avoiding the need to rely on awk hacks:
https://docs.djangoproject.com/en/1.10/ref/django-admin/#check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2069)

Bug 1326207 - Replace Django system check hack with --fail-level

---

treeherder/etl/runnable_jobs.py

Runnable jobs from taskcluster were missing their ``job_coalesced_to_guid`` value.  In the UI, if this field is not present AND set to null, it defaults to coalesced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2077)

Bug 1330157 - Ensure runnable jobs always have a null coalesced value

---

treeherder/model/models.py

The way we were using Django's "annotate" function with values_list
resulted in non-deterministic output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2079)

Bug 1329992 - Fix resultset status endpoint

---

treeherder/model/migrations/0001_initial.py
treeherder/model/migrations/0015_auto_20160402_1345.py
treeherder/model/migrations/0018_merge_duplicate_classifications.py
treeherder/model/migrations/0022_add_index_failureline_signature.py
treeherder/model/migrations/0027_failure_line_idx_signature_test.py
treeherder/model/migrations/0028_test_match_created_index.py
treeherder/model/migrations/0035_job_detail_field_lengths_decrease.py
treeherder/model/migrations/0036_job_details_unique_together.py
treeherder/model/migrations/0043_bugscache_cleanup.py
treeherder/model/models.py

Django's `squashmigrations` command cannot optimise past `RunSQL` or `RunPython` migration operations, since it cannot guarantee that the order of migration operations isn't important. However as of Django 1.10 these commands can be marked as `elidable`, if they are not required in the final migration (eg if they only manipulate legacy data and have already run in all necessary environments), which solves this problem.
This PR makes use of the new `elidable` feature along with a few other changes, to reduce the number of RunSQL operations that will block the optimisation of migrations when we use `squashmigrations` in a later PR.
A dump of the resultant schema before/after this PR shows no surprises (generated using `mysqldump -u root --no-data …

Bug 1320136 - Clean up RunSQL and RunPython operations

---

ui/js/components/logviewer/logviewer.js
ui/js/controllers/logviewer.js

Currently if you click on a failure, the viewer would put the red failure line on the very top of the log area, which is less optimal since some log above the failure line could usually be useful. This
PR adds an offset to a line number so that users can see the log above a failure line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2087)

Bug 1245389 - Add offset to log line number

---

ui/js/controllers/logviewer.js

This bug required changes in both [taskcluster/unified-logviewer/pull/29](https://github.com/taskcluster/unified-logviewer/pull/29) and Treeherder repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2078)

Bug 1329735 - New logviewer puts many entries in browsing history

---

treeherder/model/management/commands/load_initial_data.py

Since it increases the runtime of `load_initial_data` from 2 seconds to 2 minutes 30 seconds, which delays both Vagrant provisions and prod deploys.
This was added recently in bug 1328618, however another solution will have to be found to improve the local development workflow instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2098)

Bug 1329685 - Stop calling update_runnable_jobs during load_initial_data

---

ui/js/controllers/main.js

We have some code which tries to get the size of a non-existent "top navbar"
to adjust the size of the resultset/jobs view. I think this dates way back
to 2014, before I added flexbox-- the code is harmless (since it does
nothing), but causes a confusing console error ("Empty string passed to
getElementById"). Let's remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2099)

Bug 1333422 - Remove useless resize-watching code from ui

---

ui/admin.html
ui/failureviewer.html
ui/js/components/auth.js
ui/logviewer.html
ui/partials/main/thGlobalTopNavPanel.html
ui/partials/main/thWatchedRepoNavPanel.html
ui/perf.html

It turns out that adding a data-target property of '#' to a dropdown
is unnecessary and confuses bootstrap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2100)

Bug 1333427 - Fix remaining "Empty string passed to getElementById()" warnings

---

ui/js/controllers/logviewer.js

Copy-pasting from the logviewer introduces empty lines in between. This is because we are using `<p>` tags to wrap a line in the viewer. Switching `<p>` to `<div>` fixes the problem. Since the logviewer within Treeherder is styling based on tags, we will need to do this change in 3 steps in order to avoid downtime. This PR does the **second** step.
Steps:
1. **logviewer-pr**: Change `<p>` to `<p class="line...>`
2. **th-pr**: Change Treeherder logviewer styling to use `.line` instead of `p`
3. **logviewer-pr**: Change `<p class="line...>` to `<div class="line...>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2109)

Bug 1294354 - Modify log style to use "line" class

---

treeherder/config/settings.py

Since we don't use either of them:
https://docs.djangoproject.com/en/1.10/ref/contrib/sites/
https://docs.djangoproject.com/en/1.10/ref/contrib/messages/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2118)

Bug 1335238 - Disable Django sites and messages frameworks

---

ui/partials/main/thActionButton.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2121)

Bug 1335506 - Hide the trigger missing jobs button until it behaves

---

docs/admin.rst

Also removes `task_set_meta` from the exclusion list, since that table no longer exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2117)

Bug 1335151 - Docs: Update read-only replica GRANTs for new SETA table

---

treeherder/model/migrations/0001_squashed_0053_add_job_platform_option_push_index.py
treeherder/model/models.py

Since it overlaps with the composite index, and the additional length isn't required (50 characters vs 25).
The RunSQL operation is being removed from the existing migrations file (rather than adding a new RunSQL operation that reverts it), since the index is missing on prod, so any attempts to remove it would error. This means that existing Vagrant environments will have an extra index until the environment is recreated, however it's unlike to have an impact on reproducibility of prod issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2125)

Bug 1304062 - Remove prefix index on failure_line.signature

---

ui/plugins/pluginpanel.html

I think the order of these two filters should be reversed, so that URLs get linkified before attempting to linkify SHA-like classification comments. Otherwise, SHAs get linkified, then the linkified SHAs get further linkified, causing the problem described in the bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2122)

Bug 1315941 - Change the order of filters being applied to fix linkified classification comments

---

treeherder/config/settings.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2130)

Bug 1336476 - Set treeherder logging level to warning

---

requirements/common.txt

Notably this means long-lived static assets will be served with a `Cache-Control` header that now contains the new `immutable` directive, for improved browser caching behaviour. See:
https://bitsup.blogspot.co.uk/2016/05/cache-control-immutable.html
https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/
Changes:
http://whitenoise.evans.io/en/stable/changelog.html#v3-3-0
https://github.com/evansd/whitenoise/compare/v3.2.3...v3.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2131)

Bug 1336504 - Update whitenoise from 3.2.3 to 3.3.0

---

treeherder/config/whitenoise_custom.py

The UI build switched from grunt-cache-busting to grunt-cache-bust in bug 1315933, however the regex for the hashed filenames was not updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2129)

Bug 1320963 - Fix regex used to determine long max-age static assets

---

treeherder/credentials/templates/credentials/base.html

In order to use the `static` statement later in the file, the static tag first has to be loaded:
https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#std:templatetag-static
This was previously achieved via `load staticfiles` (deprecated form), but that was accidentally removed in bug 1273034 (https://github.com/mozilla/treeherder/commit/ba8165c23934f65df3bbd809f75af94e77a2a258#diff-305591ed7394d1ff36503ffa74c7b32cL1), resulting in HTTP 500s when the credentials self-serve pages were accessed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2127)

Bug 1336270 - Add missing 'load static' to credentials self-serve pages

---

treeherder/config/whitenoise_custom.py

The previous change adjusted the hash length, however the filenames also no longer use a hyphen as a separator, eg:
index.min.fe5b2cd9a306c9d1.css
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2134)

Bug 1320963 - Really fix regex for long max-age static assets

---

ui/index.html

This removes what appears to be an unused `ng-class` from the markup. The info panel and pinboard appear to behave fine without it.
Nightly **54.0a1 (2017-02-03) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2132)

Bug 1336575 - Remove unused pinboard class

---

ui/js/controllers/jobs.js
ui/js/models/resultset.js
ui/js/services/taskcluster.js
ui/plugins/controller.js

This contains a good number of changes from #2057 but adds some refactoring for re-use of certain components for the add-talos support. As I understand it, what we want to do for add-all-talos is to still send a pulse message for pulse_actions to act on in order to add buildbot talos jobs, and then submit an action task to tc for the tc based ones. This PR is dependent on https://reviewboard.mozilla.org/r/103910/ getting merged first before it can work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2092)

Bug 1289824 - Add add-all-talos support for tc

---

tests/auth/test_backends.py
tests/webapp/api/test_auth.py
treeherder/auth/backends.py
treeherder/webapp/api/auth.py

This allows users to use the Taskcluster Auth "Sign-in with Email" option.  If an email isn't found in the user's scope of "mozilla-user" then it will attempt to find an email in the ``clientId`` value of the result.  If it can't be found there, then deny login as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2011)

Bug 1319246 - Allow login with plain email from Auth0

---

treeherder/auth/backends.py

Since it's recommended over direct creation, by the Django docs:
https://docs.djangoproject.com/en/1.10/topics/auth/default/#topics-auth-creating-users
Specifically, the helper:
* normalises username/email
* sets an unusable password rather than a blank one (subtle security implications that are unlikely to affect us, but better to be safe)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2152)

Bug 1338206 - Create new users via the create_user() helper

---

setup.cfg

This demands a weird style when using
```
if (something and
something_else):
```
which is not really helpful to code readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2149)

Bug 1337726 - Disable E129 pyflakes lint.

---

treeherder/config/settings.py
treeherder/etl/tasks/buildapi_tasks.py
treeherder/etl/tasks/classification_mirroring_tasks.py
treeherder/etl/tasks/tasks.py
treeherder/seta/tasks.py

**1) Switch Celery per-task time_limits to soft_time_limits**
Since the hard time limits prevent the New Relic Python agent from reporting the timeout exception:
http://docs.celeryproject.org/en/3.1/userguide/workers.html#time-limits
**2) Set default Celery soft and hard time limits**
Since otherwise if either is not set on an individual task, it can run forever (or at least until the dyno is restarted, every 24 hours):
http://docs.celeryproject.org/en/3.1/configuration.html#celeryd-task-time-limit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2155)

Bug 1308549 - Switch to soft Celery time limits to allow reporting to New Relic

---

ui/css/treeherder-info-panel.css
ui/plugins/controller.js

This hopefully fixes Bugzilla bug [1322158](https://bugzilla.mozilla.org/show_bug.cgi?id=1322158).
This improves the UX of the info panel during initial job selection, by sliding onscreen, rather than it just popping onscreen as it currently does. Doing so:
* reduces the current jarring UX where it just appears
* provides more clarity it sits atop the job tables
* provides an additional visual cue it's movable and can be adjusted
Everything seems fine in local testing so far: `esc` to clear the selection, re-selection, page re-load with a job selected, pinboard open and closed, info panel resized and reopened. We still preserve the current 35% height for the panel.
Nightly **53.0a1 (2016-12-02) (64-bit)**
Chrome Release **54.0.2840.98 (64-bit)**
---
This change …

Bug 1322158 - Slide info panel onscreen during initial job selection

---

ui/js/models/error.js

This was the wrong error code and resulted in a confusing error message of `Taskcluster: ext.certificate.expiry < now`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2161)

Bug 1339041 - Fix check on error code for Taskcluster expired creds

---

Procfile
treeherder/config/settings.py

CloudAMQP recommend disabling events/heartbeats/gossip/mingle messages, in order to reduce unnecessary load on the rabbitmq server:
https://www.cloudamqp.com/docs/celery.html
For settings reference, see:
http://docs.celeryproject.org/en/3.1/configuration.html
http://docs.celeryproject.org/en/3.1/whatsnew-3.1.html#gossip-worker-worker-communication
http://docs.celeryproject.org/en/3.1/reference/celery.bin.worker.html#cmdoption-celery-worker--without-gossip
The Procfile is now becoming exceptionally verbose, however that's a problem to consider solving in another bug, perhaps via a runner script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2165)

Bug 1215102 - Adjust Celery settings to match CloudAMQP recommendations

---

docs/conf.py

I noticed the Read The Docs copyright is out of date, so let's update it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2163)

Bug 1339157 - Remove the RTD copyright year

---

puppet/files/mysql/my.cnf

Since Django recommends it over REPEATABLE-READ:
https://docs.djangoproject.com/en/1.10/ref/models/querysets/#get-or-create
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_tx_isolation
This will update Travis/Vagrant, a separate PR will be opened against the prod RDS Terraform configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2173)

Bug 1330324 - Use MySQL READ-COMMITTED transaction isolation level

---

newrelic.ini

The name of suitable (finite duration) management commands have to be defined in the New Relic config file, since Django management commands are not annotated by default:
https://docs.newrelic.com/docs/agents/python-agent/supported-features/python-background-tasks#django
We'll likely want to expand this list in the future, particularly if we switch from celery beat schedules and towards the Heroku scheduler in  bug 1176492 (since it will run management commands directly, outside of Celery).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2180)

Bug 1340203 - Make some Django management commands report to New Relic

---

Procfile
bin/run_gunicorn

Since hopefully now we're no longer using datasource, the leaks should have gone. The gunicorn processes will now only be restarted at the daily Heroku dyno restart, rather than multiple times per minute, improving performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2177)

Bug 1340123 - Stop using --max-requests with gunicorn

---

tests/webapp/api/test_resultset_api.py
treeherder/webapp/api/resultset.py

Resolved the bug to handle the case gracefully and throw HTTP 400. Also added test case for the same.
Bugzilla link - https://bugzilla.mozilla.org/show_bug.cgi?id=1311974.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2176)

Bug 1311974 - ResultSetViewSet.list "ValueError: invalid literal for int() with base 10: ..."

---

ui/css/treeherder-pinboard.css

This removes unused `-webkit` properties from the pinboard, stemming from webkit browser evolution (eg. Chrome) which appears to now support their non -webkit equivalents.
Everything seems consistent in the branch vs current production in basic pinboard functionality testing: pinning, unpinning, bug numbers, classifications, pinning many jobs, resizing the pinboard, changing the browser width, etc.
Nightly **54.0a1 (2017-02-13) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2182)

Bug 1340232 - Remove unused -webkit css in the pinboard

---

ui/js/reactrevisions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2148)

Bug 1337970 - Unescape commit message tooltips

---

ui/css/treeherder-info-panel.css

This removes unused -webkit properties from the info-panel, stemming from webkit browser evolution (eg. Chrome) which appears to now support their non -webkit equivalents.
Everything seems consistent in this branch vs current production in basic info-panel functionality testing: scroll, job details, tab functionality, annotation, similar jobs, performance, resizing the info panel, changing the browser width, pinboard integration.
Nightly **54.0a1 (2017-02-16) (64-bit)**
Chrome Release **Version 56.0.2924.87 (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2189)

Bug 1340232 - Remove unused -webkit css from info-panel

---

treeherder/log_parser/parsers.py

This is pretty simple, though I don't know if there are reasons why this wouldn't work (such as running gtests with expected failures).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2185)

Bug 1340329 - Recognize gtest failure lines as errors

---

ui/js/directives/treeherder/top_nav_bar.js
ui/js/models/repository.js
ui/partials/main/thWatchedRepo.html
ui/partials/main/thWatchedRepoNavPanel.html

Addresses @camd's comment here:  https://bugzilla.mozilla.org/show_bug.cgi?id=1081074#c9
The only item needing addressing is sort order; navbar items are output by `thWatchedRepoNavPanel.html`, via:
```
<th-watched-repo ng-repeat="(name, repoData) in repoModel.watchedRepos"></th-watched-repo>
```
I'll need to add something to reverse that object key order to put the most recently watched repos first (before a page refresh).  Working on that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2105)

Bug 1081074 - Store and display watched repos in the nav panel

---

tests/etl/test_buildbot.py
treeherder/etl/buildbot.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2194)

Bug 1341776 - Change the buildbot symbol for mochitest a11y to match taskcluster's symbol

---

treeherder/log_parser/failureline.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2200)

Bug 1342377 - Only store failure_line data from known errorsummary keys

---

ui/css/treeherder-global.css
ui/css/treeherder-navbar-panels.css
ui/css/treeherder-navbar.css
ui/css/treeherder-resultsets.css

This removes unused `-webkit` properties from the main page, resultsets, and navbar, stemming from webkit browser evolution (eg. Chrome) which appears to now support their non -webkit equivalents.
Everything seems consistent in the branch vs current production in basic functionality at all browser sizes for the navbar menus, filter panel, resultsets, dropdowns, counters, info panel and pinboard integration testing.
Nightly **54.0a1 (2017-02-19) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2197)

Bug 1340232 - Remove unused -webkit css from main page

---

ui/partials/main/thShortcutTable.html

This fixes the recent layout break of the shortcut table. I also re-ordered the next/previous shortcuts where 'next' is read first in the list; which seems to make sense since by default this is the likely direction the user navigates.
Before:
Fixed:
Nightly **54.0a1 (2017-02-19) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2198)

Bug 1342269 - Fix shortcut table

---

tests/webapp/api/test_bug_job_map_api.py
treeherder/webapp/api/bug.py

The value error is now handled gracefully with HTTP 400.
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1311980
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2142)

Bug 1311980 - Gracefully handle invalid job_id in BugJobMapViewSet.list

---

ui/css/treeherder-global.css

As part of PR https://github.com/mozilla/treeherder/pull/2197 we removed this flex property since its antecedent bugs were fixed. But it turns out we still need it for small pushes containing small numbers of jobs, so the info-panel doesn't consume more than its usual vertical space.
Nightly **54.0a1 (2017-02-23) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2205)

Bug 1340232 - Return flex property for small push reflows

---

ui/partials/main/thPinboardPanel.html
ui/plugins/controller.js
ui/plugins/pinboard.js

While annotating jobs for classification type "fixed by commit", a dropdown suggesting recent revisions added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2095)

Bug 1333396 - Add a dropdown list showing recent revisions while annotating jobs when using "fixed by commit" 

---

ui/js/controllers/jobs.js
ui/js/models/resultset.js

This makes add-new-jobs go direct to the taskcluster queue as well. I think this should be the last thing that pulse_actions handles for taskcluster, so we can remove scopes for tc from pulse_actions after that.
pulse_actions still handles bb-specific stuff though, so this logic passes on bb jobs to it the same as before.
I've tested this locally to the best of my ability on some of my own try pushes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2208)

Bug 1343002 - Make add-jobs go direct to tc for tc jobs

---

treeherder/config/settings.py

This allows non-BMP unicode values to be sent by the client to MySQL server, to allow insertion into tables that have been converted to utf8mb4 (currently only the `commit` table).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2212)

Bug 1115608 - Set Django DB connection charset to utf8mb4

---

tests/webapp/api/test_job_details_api.py
treeherder/webapp/api/jobs.py

This will allow the test-centric UI prototype to more easily fetch all "artifact uploaded" URLs associated with a single push.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2211)

Bug 1343329 - Add push_id filtering support to the /jobdetail/ API

---

Vagrantfile

Since with the MySQL, Elasticsearch, rabbitmq-server and memcached services running there is only 640MB free, which is insufficient for building the UI using Webpack/Neutrino or when mass ingesting data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2230)

Bug 1344983 - Vagrant: Increase VM memory allocation from 2GB to 3GB

---

ui/js/controllers/perf/compare.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2224)

Bug 1174777 - Hitting 'back' on a Compare result should preserve project/revision values

---

.travis.yml
npm-shrinkwrap.json
package.json

The npm shrinkwrap was also updated since new nodejs versions come with new npm, and the format for the shrinkwrap sometimes changes:
https://treeherder.readthedocs.io/common_tasks.html#updating-packages-in-package-json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2233)

Bug 1343932 - Update nodejs used on Heroku/Travis from 6.2.0 to 7.7.1

---

docs/admin.rst

These were added by bug 1312575 and bug 1323110.
The table exclusion list has also been updated to remove the corsheader entry, since as of v2.0.0 it no longer creates any tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2234)

Bug 1345220 - Docs: Update read-only replica GRANTs for new tables

---

ui/css/perf.css

This removes unused -webkit properties from Perf, stemming from webkit browser evolution (eg. Chrome) which appears to now support their non -webkit equivalents.
Everything seems consistent in the branch vs current production, with the blink behavior during test data load, and the tooltip radius on both browsers.
Nightly **54.0a1 (2017-03-03) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2235)

Bug 1340232 - Remove unused -webkit css from perf

---

puppet/manifests/classes/init.pp
puppet/manifests/classes/nodejs.pp
puppet/manifests/vagrant.pp

Since once we switch to Neutrino/webpack all UI and full-stack
development will require building the UI using nodejs.
Uses the steps here:
https://github.com/nodesource/distributions#manual-installation
https://yarnpkg.com/en/docs/install#linux-tab
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2239)

Bug 1343624 - Vagrant: Install nodejs and yarn during provision

---

ui/js/controllers/perf/graphs.js

It's not recommended, but also not unusual for people to have graphs with 6+ series in them. Let's try to handle this case a little better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2214)

Bug 1343586 - Increase # of available colors for perf graphs

---

ui/plugins/controller.js

As it stands, backfilling will not work in stage. This should fix that as soon as https://reviewboard.mozilla.org/r/107310/ lands. I'll assign this review to someone as soon as that gets try results back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2108)

Bug 1333604 - Allow specific treeherder instance to be used in backfill

---

.travis.yml
package.json

Vagrant uses the latest 7.x.x release, which is now 7.7.2. To reduce
differences between environments whilst the Neutrino/webpack work is
stabilised, it makes sense to update Heroku/Travis again too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2241)

Bug 1343932 - Update nodejs used on Heroku/Travis from 7.7.1 to 7.7.2

---

treeherder/model/management/commands/cycle_data.py

Since previously the select was evaluated independently of the delete, causing timeouts when attempting to returning 2.6 million machine ids from the jobs table.
Now the select queryset isn't evaluated on it's own, and instead is only used to generate the subquery in eg:
```sql
SELECT `machine`.`id`, `machine`.`name` FROM `machine` WHERE NOT
(`machine`.`id` IN (SELECT DISTINCT U0.`machine_id` FROM `job` U0));
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2244)

Bug 1346567 - Rewrite inefficient queries in cycle_non_job_data()

---

ui/js/controllers/main.js
ui/partials/main/thShortcutTable.html

The autoclassify UI rewrite accidentially swapped the meaning of the
j and k keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2255)

Bug 1347454 - Make prev/next keybindings match vi again.

---

ui/css/logviewer.css

This removes unused css from the Logviewer.
Everything seems consistent in the branch vs current production. It would be good for someone else to try it out on another platform for sanity. Where possible some -moz -webkit and -ms prefixed properties were removed, others needed to remain.
Nightly **55.0a1 (2017-03-14) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2247)

Bug 1345512 - Remove unused css from Logviewer

---

requirements/common.txt

Notably this fixes the reporting of exceptions that occur outside of a view handler (which previously did not show up in APM at all).
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-282062
https://github.com/edmorley/newrelic-python-agent/compare/v2.78.0.57...v2.82.0.62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2261)

Bug 1336276 - Update newrelic from 2.78.0.57 to 2.82.0.62

---

ui/js/controllers/logviewer.js
ui/logviewer.html

This fixes Bugzilla bug [1347278](https://bugzilla.mozilla.org/show_bug.cgi?id=1347278).
This adds a conditional title, and disables the cursor on the 'show successful steps' checkbox for any TaskCluster job, since step parsing isn't yet supported from TaskCluster.
Proposed (cursor not shown here):
I also experimented with hiding the container entirely for TaskCluster jobs, but it seemed to make a lot more sense to tell the user why it's not available, rather than have them think it's missing. There was also a lot of angular template bouncing around when hiding, which would have been undesirable.
Nightly **55.0a1 (2017-03-14) (64-bit)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Bug 1347278 - Disable Successful Step checkbox for TaskCluster jobs

---

treeherder/seta/update_job_priority.py

These were hidden by the use of `# flake8: noqa`, which wasn't actually required on the line in question since line length checks are disabled, and in fact disabled flake8 for the entire file rather than just the one line.
```
treeherder/seta/update_job_priority.py:12:1: F401 'copy' imported but unused
treeherder/seta/update_job_priority.py:14:1: F401 'json' imported but unused
treeherder/seta/update_job_priority.py:16:1: F401 'os' imported but unused
treeherder/seta/update_job_priority.py:17:1: F401 'time' imported but unused
treeherder/seta/update_job_priority.py:54:1: E302 expected 2 blank lines, found 1
treeherder/seta/update_job_priority.py:104:1: E302 expected 2 blank lines, found 1
treeherder/seta/update_job_priority.py:126:1: E302 expected 2 blank lines, found 1 …
```

Bug 1348360 - Remove 'flake8: noqa' and fix linter errors in update_job_priority.py

---

treeherder/etl/tasks/__init__.py

Since it turns out Celery uses them during task auto-discovery.
This partially reverts commit 63372232164bf09ae4378e07e196c407a0b29229.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2276)

Bug 1348375 - Re-add wildcard imports in treeherder.etl.tasks

---

ui/js/directives/treeherder/main.js

Elements like toolbar buttons can be clicked and then become
disabled. In this case they will eat keyboard shortcuts leading to
bugs. A simplisitic fix is just to ensure that those elements give up
focus after they are activated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2262)

Bug 1347726 - Prevent prevent-default-on-left-click elements retaining focus

---

treeherder/model/fixtures/repository.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1313221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2280)

Bug 1313221 - Disable the unused gaia and gaia-master repositories

---

ui/plugins/auto_classification/controller.js

Emit the event that causes the job status to update after saving and
ending up with 0 pending lines, as well as after save all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2277)

Bug 1349283 - Update job status after saving final line in autoclassify panel

---

tests/perfalert/test_analyze.py
tests/perfalert/test_create_alerts.py
treeherder/perf/alerts.py
treeherder/perfalert/perfalert/__init__.py

Retriggering performance jobs to generate better performance numbers
is becoming increasingly common, but our old regression detection
code didn't really account for that case -- in particular, it
had a bug that would allow for a regression to be generated *inside*
the data for a particular revision (if there were enough).
This commit fixes that bug and also changes the behaviour of the
linear weighting function so that retriggers on a particular revision
will be weighted the same (rather than declining in importance)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2284)

Bug 1344358 - Make perf regression detection work better w/ retriggers

---

ui/plugins/auto_classification/controller.js
ui/plugins/auto_classification/panel.html

Before a job is complete we should show a message indicating that
rather than one claiming that the logs are not fully parsed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2286)

Bug 1348013 - Don't show a logs parsing message when the job is incomplete

---

tests/model/test_error_summary.py
treeherder/model/error_summary.py

Process output lines start with a prefix like GECKO(1234) or PID 1234
and then a pipe. This is an extra pipe symbol compared to other lines,
so our code that splits on | and assumes specific data in specific
positions is broken. Try to detect the process output case and discard
the first token so that we have the same fields as other
pipe-delimited data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2289)

Bug 1349617 - Handle process output lines in the log parser.

---

ui/plugins/auto_classification/controller.js
ui/plugins/auto_classification/panel.html

When moving between jobs it was possible to see significant lag in the
UI, with the spinner disappearing, but the panel showing stale
data. Try to show the spinner earlier and hide it later so that it is
displayed until the latest data is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2287)

Bug 1349932 - Be more conservative showing Failure Classification lines.

---

ui/css/treeherder-info-panel.css
ui/js/services/pinboard.js
ui/plugins/auto_classification/controller.js
ui/plugins/auto_classification/errorLine.html
ui/plugins/auto_classification/option.html
ui/plugins/auto_classification/panel.html
ui/plugins/auto_classification/staticOption.html
ui/plugins/auto_classification/toolbar.html

Currently non-sheriffs cannot classify through the Failure
Classification panel. It turns out that there are a few peoeple who
want to do that. The simplest approach is to add the pinboard icons
analogous to the old UI so that they can mark jobs as classified but
not affect the autoclassification data. For sheriffs the pinboard is
also important for non-intermittents, so add a bustage button to the
toolbar and show the pinboard icons when the job is pinned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2288)

Bug 1347946 - Add pinboard integration to the Failure Classification panel

---

ui/plugins/auto_classification/panel.html

This was displaying on fully verified jobs as well as jobs with no
error lines becase we used pendingLines rather than errorLines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2291)

Fixup message for no error lines.

---

bin/post_compile

Since it avoids including 4500 unused files (28MB) in the slug, now that
we're using the yarn support added to newer versions of the nodejs
buildpack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2278)

Bug 1349405 - Delete .heroku/yarn/ during post_compile

---

ui/js/treeherder_app.js

`useXDomain` never actually did anything since the PR that proposed it was never merged:
https://github.com/angular/angular.js/issues/2956#issuecomment-19493940
And deleting the 'X-Requested-With' header isn't required as of Angular >1.1.x :
https://github.com/angular/angular.js/issues/11008
https://github.com/angular/angular.js/commit/3a75b1124d062f64093a90b26630938558909e8d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2279)

Bug 1343108 - Clean up obsolete $httpProvider defaults

---

ui/js/controllers/main.js
ui/partials/main/thActionButton.html

This links to our prototype running on Heroku.  I know it's hard-coded to the domain for now, which isn't ideal.  But that will be ripped out anyway once we merge this into Treeherder proper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2296)

Bug 1351092 - Add link to the test-centric UI from resultsets

---

tests/autoclassify/utils.py
tests/log_parser/test_crossreference_error_lines.py
treeherder/log_parser/crossreference.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2299)

Bug 1351408 - Skip unmatchable failure_line entries when trying to crossreference lines

---

treeherder/model/fixtures/repository.json

This adds the various repositories with automated tests currently being run in our Jenkins instance, in preparation for publishing test results to Treeherder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2301)

Bug 1351644 - Add repositories for Firefox Test Engineering automated tests

---

ui/js/controllers/main.js
ui/js/services/main.js
ui/plugins/auto_classification/controller.js
ui/plugins/auto_classification/errorLine.html

Also make the "l" shortcut open the log viewer on the first selected
line, if any.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2290)

Bug 1350353 - Link error lines to the corresponding line in the logs.

---

treeherder/webapp/graphql/schema.py

Only Jobs and BuildPlatform had the right ORM query matching their
Graph.  The rest were all BuildPlatform, which gave an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2305)

Bug 1352244 - Fix queries for broken GraphQL objects

---

ui/js/controllers/main.js

For some reason, the commit that updated lint messed this up:
https://github.com/mozilla/treeherder/commit/11ca87fb3444f87981a3c751bd195758183222b4#diff-84c67dfb34465e36f91640c8c95657c9L593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2311)

Bug 1336556 - followup to fix active-filters-bar

---

ui/js/controllers/bugfiler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2315)

Bug 1353203 - Generalize the reftest failure path stripping to hopefully catch all variations

---

neutrino-custom/lint.js
ui/js/models/resultset.js
ui/js/services/main.js
ui/plugins/controller.js

I believe this is all that needed done to get jsyaml in the places we needed it afterall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2314)

Bug 1353066 - Move jsyaml to being loaded correctly

---

tests/ui/unit/controllers/bugfiler.tests.js
ui/js/controllers/bugfiler.js

The changes to the actual bugfiler controller are to let the function actually be reachable to the tests.
A lot of the boilerplate stuff is things I was adding to try to test the findProducts function, but I never got far enough to get it working. Don't want to lose the work I put into it, though, so here it is...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2322)

Bug 1353951 - Add tests for bug filer's parseSummary and findProduct functions

---

requirements/common.txt
requirements/dev.txt

**1) Update pytest-\* packages**
Since the new pytest-html version now depends on pytest-metadata, and pyup doesn't yet handle adding new sub-dependencies as part of package updates (pyupio/pyup#209), so we have to do so manually. The other packages have to be updated at the same time, since pytest-html made breaking changes in a minor version.
https://github.com/pytest-dev/pytest-html/blob/master/CHANGES.rst
https://github.com/pytest-dev/pytest-html/compare/v1.13.0...v1.14.2
https://github.com/pytest-dev/pytest-variables/blob/master/CHANGES.rst
https://github.com/pytest-dev/pytest-variables/compare/v1.4...v1.5.1
https://github.com/pytest-dev/pytest-base-url/blob/master/CHANGES.rst
https://github.com/pytest-dev/pytest-base-url/compare/v1.2.0...v1.3.0 …

Bug 1345131 - Preparation for using pyup.io to manage Python dependencies

---

tests/settings.py
treeherder/config/settings.py
treeherder/webapp/api/bugzilla.py

BZ_API_URL currently is used for both the bug filer and fetching bug suggestions through the rest of Treeherder. At the moment, both of them point to production bmo's API. Bug suggestions coming from the bugzilla instance that actually has most of the intermittent bugs filed makes sense. Filing bugs from staging Treeherder's bug filer into production bmo makes less sense, so this patch lets you specify a different API URL.
If the new environmental variable isn't present, the bug filer will still default to production bmo, so this should be deployable without any configuration changes, and everything should still just work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder …

Bug 1354438 - Give the Bug Filer control of its own API URL

---

treeherder/model/migrations/0008_push_job_child_references.py

Django bug https://code.djangoproject.com/ticket/28065 causes the
addition of ``related_name`` to create a migration that will drop and
re-add the foreign key.  However, this is a ``meta`` only change, so
no DB changes should be made and this ForeignKey drop and re-add
is super expensive.  I didn't notice this problem before I merged
commit d85b8f74d2bd63a7bd1de420aa15f422b360dbc8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2334)

Bug 1353093 - Make migration 0008 a no-op

---

ui/js/filters.js
ui/partials/perf/comparetable.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2333)

Bug 1352207 - Compare view should show a tooltip on bars saying whether the result was better or worse

---

treeherder/config/urls.py

This is necessary to allow the TestGroup UI to access these GraphQL endpoints from a separate domain.  The client library we are using is Apollo, which uses a POST, even for read-only requests.  It is easier to ease the CSRF protections here than to get Apollo to support GET requests at this time.  We'll likely move to GET requests at a later time.
Disabling CSRF protections on these endpoints is safe because they are all read-only.  If we create "mutations" for these endpoints which allow writes, we'll need to re-visit the use of this exemption.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2340)

Bug 1356047 - Allow csrf_exempt on graphql endpoints

---

ui/js/controllers/bugfiler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2308)

Bug 1351036 - Strip 'xpcshell-unpack.ini:' from failure paths in the bug filer

---

ui/plugins/failure_summary/controller.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2341)

Bug 1356483 - Only take the crash signature from the currently selected failure line

---

requirements/common.txt

Now that the initial PR is out of the way, subsequent PRs will be one
package per PR, which is what we want for the more risky common.txt
updates (mass updating the dev dependencies was safe and so not worth
the additional spam of one PR per package).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2368)

Bug 1345131 - Enable pyup.io for requirements/common.txt

---

tests/etl/test_job_loader.py
treeherder/etl/jobs.py

Since it's no longer true that they won't have artifacts.

Bug 1354135 - Don't skip the ingestion of artifacts for pending jobs

---

.travis.yml
vagrant/setup.sh

For parity with that already running on Heroku prototype.

Bug 1357491 - Update Vagrant/Travis Elasticsearch from 2.3.5 to 2.4.4

---

bin/vendor-libmysqlclient.sh

Also switches to the official URLs (that 302 redirect) rather than direct-linking, since the official URLs are now HTTPS. Avoids potential breakage in the future as the CDN internal URLs change.
Changelog (most of the changes only affect mysql-server):
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-15.html
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-16.html
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-17.html
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-18.html

Bug 1357595 - Update libmysqlclient from 5.7.14 to 5.7.18

---

tests/model/test_cycle_data.py
treeherder/model/management/commands/es_import_failure_lines.py

The count `search_type` was deprecated in Elasticsearch 2.0.0 and has been removed entirely in version 5+:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html
This switches to the `.count()` API instead:
https://elasticsearch-dsl.readthedocs.io/en/latest/api.html#elasticsearch_dsl.Search.count
This can be landed prior to the ES 5.x upgrade, since it's supported by the ES 2.x API too.

Bug 1340554 - Switch away from deprecated Elasticsearch count API

---

tests/log_parser/test_error_parser.py
treeherder/log_parser/parsers.py

This assumes that any line involving the words REFTEST ERROR is always
a failure. It is possible that we will need restrict this if there are
passing tests that produce that in their output.

Bug 1354694 - Add REFTEST ERROR to the list of error strings

---

.travis.yml
requirements/common.txt
vagrant/setup.sh

* ES 5.x now requires JDK 8, and Ubuntu 14.04 only ships with openjdk 7, so a third party PPA must be used in Vagrant:
https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa
* ES 5.x changed the way it manages the heap size, such that:
- The variables for controlling it have changed (now set via eg `ES_JAVA_OPTS="-Xms1g -Xmx1g"` or in the jvm.options file). See:
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/heap-size.html
- The default heap size has increased from ~(min:256MB, max:1GB) to (min: 2GB, max: 2GB) which causes OOM in the VM, unless either lowered back down or the VM RAM increased.
* The Python ES clients must be updated to the latest releases:
https://elasticsearch-py.readthedocs.io/en/master/#compatibility
* The previous test failures were fixed in #2403.
* The …

Bug 1340554 - Update from Elasticsearch 2.x to 5.x

---

treeherder/model/fixtures/repository.json

enable holly branch for testing
Turn off buildbot macosx64 opt builds scheduling 
https://bugzilla.mozilla.org/show_bug.cgi?id=1353376

bug 1353376 - enable holly branch for macosx on tc scheduling testing

---

tests/ui/unit/controllers/bugfiler.tests.js
ui/js/controllers/bugfiler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2343)

Bug 1356719 - Strip out 'REFTEST ' from unexpected reftest passes

---

tests/ui/unit/controllers/bugfiler.tests.js
ui/js/controllers/bugfiler.js

Tired of manually adding these every single time I find a new prefix. This should stop them all, assuming they match the `xpcshell-FOO-BAR.ini:" format.

Bug 1359626 - Strip out more xpcshell prefixes from the path

---

docs/common_tasks.rst
docs/ui/installation.rst
neutrino-custom/lint.js
neutrino-custom/production.js
tests/ui/unit/init.js
ui/js/config/index.js
ui/js/config/sample.local.conf.js
ui/js/providers.js

Previously a forgotten-about `local.conf.js` (which is git-ignored) would override the URL passed by the `SERVICE_URL` environment variable.
With webpack and environment variables, there is no need to use a local config file to control the API URL, so we can now remove this footgun.

Bug 1168117 - Remove support for defining the API URL via local.conf.js

---

treeherder/seta/preseed.py

This PR is another option for already opened PR #2203 .
Here, load_preseed does nothing if JobPriority table is empty, so the load_preseed will just wait until analyze_failure has eventually run. 
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1330391

Bug 1330391 - SETA-Make load_preseed do nothing if JobPriority table empty

---

tests/etl/test_resultset_loader.py
tests/sample_data/pulse_consumer/hg_push.json
tests/sample_data/pulse_consumer/hg_push_commits.json
tests/sample_data/pulse_consumer/transformed_hg_push.json
tests/sampledata.py
treeherder/config/settings.py
treeherder/etl/resultset_loader.py

This uses the same mechanism we use for ingesting GitHub pushes.  This adds an additional Transformer for HG pushes, and requires adding the Pulse exchange of ``exchange/hgpushes/v1`` to the existing PULSE_RESULTSET_SOURCES environment variable.

Bug 1065567 - Add ability to ingest Mercurial Pushes via Pulse

---

treeherder/webapp/api/performance_data.py
ui/js/controllers/perf/graphs.js
ui/partials/perf/graphsctrl.html

We don't have job information for data > 4 months old (per Treeherder's job
expiry policy), but we can at least let the user hover over it as they
expect.

Bug 1360305 - Make hovering over very old performance data work as expected

---

treeherder/webapp/graphql/schema.py

This allows you to query for the FailureLine entries for jobs.  So it doesn't need a direct accessor.  This just allows them to be fields of ``Job`` queries.

Bug 1361424 - Add GraphQL support for failure lines

---

Procfile
bin/run_celery_worker
bin/run_celery_worker_buildapi
bin/run_celery_worker_hp
bin/run_celery_worker_pushlog

Now we're no longer using datasource, the memory leaks previously seen have gone. As such there is no need to make the celery worker processes restart so frequently (they will now only be restarted at the daily Heroku dyno restart), which will improve performance.
In addition, this will reduce the number of transactions that don't get reported to New Relic (when the maxtasksperchild threshold is reached, the worker is forcibly killed before it can submit the New Relic payload).
The log parser tasks have been left unchanged for now, since they appear to still be leaking.

Bug 1340132 - Reduce usage of --maxtasksperchild with celery

---

ui/js/providers.js

These aren't in the "reftest" job group but do have "reftest" in the
job title. This change is required to ensure that they get the reftest
analyzer links.

Bug 1362812 - Consider wpt reftests to be reftests.

---

Vagrantfile

NFS isn't available on Windows, so the additional virtual network adapter is unnecessary.

Bug 1320693 - Vagrant: Only enable DCHP networking on NFS platforms

---

Vagrantfile
bin/vendor-libmysqlclient.sh
vagrant/.profile
vagrant/setup.sh

At some point soon we'll want to switch Heroku stage/production to their new Heroku-16 (Ubuntu 16.04) stack, so it makes sense to trial it locally first. Their Heroku-16 docker image will make switching to docker simpler too.
Notable changes to the provision steps:
* We're using the Bento boxes rather than the 'official' Canonical ones, at the recommendation of Vagrant:
https://www.vagrantup.com/docs/boxes.html#official-boxes
* openjdk-8-jre-headless is now available from the ubuntu.com repository, so doesn't require a PPA.
* There isn't an official mysql-server-5.6 package (only 5.7+), so we have to start using a PPA.
* Services must now be managed using systemd rather than SysV init.
* The `eth0` network interface has changed name: …

Bug 1363444 - Vagrant: Update to Ubuntu 16.04

---

.travis.yml

Since as of travis-ci/travis-build#989 the latest yarn is already installed even when the default `install` step is overridden.

Bug 1364020 - Travis: Remove the now redundant yarn install step

---

package.json
yarn.lock

The only change is the move of `karma` from angular-toarrayfilter's `dependencies` to `devDependencies`, which stops us unnecessarily pulling in an ancient version of karma, and the resultant security warnings.

Bug 1364010 - Update angular-toarrayfilter from 1.0.1 to 1.0.2

---

treeherder/webapp/graphql/schema.py

This allows GraphQL queries to avoid downloading Tier-3 jobs.

Bug 1363467 - Allow 'less than' filtering on the Tier field in GraphQL

---

treeherder/perf/fixtures/performance_bug_templates.yaml
ui/js/controllers/perf/alerts.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2337)

Bug 1352398 - use raw link to revisions instead of a revision number in the talos regression template

---

.travis.yml
setup.cfg
tests/jenkins/Jenkinsfile
tests/jenkins/expected.py
tests/jenkins/pages/base.py
tests/jenkins/pages/perfherder.py
tests/jenkins/pages/run.sh
tests/jenkins/pages/treeherder.py
tests/jenkins/requirements.txt
tests/jenkins/tests/conftest.py
tests/jenkins/tests/test_expanding_group_count.py
tests/jenkins/tests/test_filter_job_by_email.py
tests/jenkins/tests/test_filter_job_by_keywords.py
tests/jenkins/tests/test_filter_jobs.py
tests/jenkins/tests/test_filter_panel.py
tests/jenkins/tests/test_get_next_results.py
tests/jenkins/tests/test_keyboard_shortcuts.py
tests/jenkins/tests/test_keyword.py
tests/jenkins/tests/test_load_page_results.py
tests/jenkins/tests/test_pin_job.py
tests/jenkins/tests/test_range.py
tests/jenkins/tests/test_status_results.py
tests/jenkins/tests/test_switch_repo.py
tests/jenkins/tests/test_treeherder_menu.py
tests/jenkins/tests/test_unclassified_job.py
tests/jenkins/tests/test_view_single_result.py
tests/jenkins/tox.ini

Moving the contents of the Treeherder-Tests repo into the /selenium folder. Tests will not run automatically, as Travis will need to be set up. This is just to get the content into the primary repo going forward so that the Treeherder-Tests repo can be decommissioned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2302)

Bug 1286686 - Initial move of Treeherder-Tests into /selenium folder

---

ui/js/models/resultset.js

Line 242 is just a bugfix for something I noticed while looking into this. The rest is a method for mapping bbb jobs back to the tc tasks they started with so that we can add them properly.

Bug 1364421 - Allow add-new-jobs to work for bbb

---

ui/partials/main/thPinboardPanel.html
ui/plugins/pinboard.js

Something is eating the event fired when ctrl-enter is pressed to save classifications if the manual bug number field is focused, making the user press ctrl-enter twice to save the classification.  This patch adds a keypress listener to the bug entry field which forces the save() function to get called when ctrl-enter is pressed.

Bug 1366345 - Force the save() event to be emitted when ctrl-enter is used while manually entering bug numbers

---

tests/jenkins/Jenkinsfile

We can safely revert the workaround, and remove the comment for https://issues.jenkins-ci.org/browse/JENKINS-42771, now that it's been fixed.
@davehunt @edmorley r?

Remove workaround for Jenkins Issue 42771

---

tests/conftest.py
tests/etl/test_job_loader.py

Since otherwise tests that ingest jobs that have structured error summary logs will hit the network, causing non-deterministic test failures, such as the failures in `test_ingest_pulse_jobs` currently being seen on Travis (since the log in question no longer exists on S3).

Bug 1370229 - Make mock_log_parser mock store_failure_lines too

---

ui/css/treeherder-global.css
ui/css/treeherder-resultsets.css
ui/js/filters.js

This hopefully improves at-a-glance recognition of what the user labels are, in the revision list.
The computed difference between the old initial text and the new one is essentially unchanged (9px to 8px). I intentionally used superscript with the initials to differentiate them visually and to place them beside the 'head' of the user icon.
Current:
Proposed:
Tested on OSX 10.12:
Nightly **55.0a1 (2017-05-01) (64-bit)**
Chrome Release **58.0.3029.110 (64-bit)**

Bug 1367867 - Improve recognition of user Initial Labels

---

treeherder/log_parser/tasks.py

Having ids in the custom parameter names doesn't play too well with new
relic insights.

Make log parser custom parameters less variable.

---

treeherder/log_parser/management/commands/crossreference_missing.py
treeherder/log_parser/tasks.py

This is a temporary script designed to fill in missing data. It looks for jobs that have `text_log_error` and `failure_line` but no `text_log_error_metadata` and reruns the crossreferencing command on them.

Add script for backfilling missing links between failure_line and text_log_error

---

treeherder/log_parser/artifactbuildercollection.py

This will help determine what maximum size threshold is appropriate to allow the common log sizes, but still prevent the extreme offenders. The Content-Encoding is also recorded, to check if there are any other logs being served without gzip.

Bug 1295997 - Record the size of the unstructured log download

---

treeherder/log_parser/artifactbuildercollection.py

New Relic Insights doesn't coerce strings to integers, so doesn't allow the graphing of custom attributes sent as strings. HTTP headers are always exposed as strings, even for fields that are expected to represent numbers, so we must explicitly cast `Content-Length`.

Bug 1295997 - Send the unstructured log size to New Relic as ints

---

treeherder/autoclassify/tasks.py
treeherder/etl/tasks/classification_mirroring_tasks.py
treeherder/log_parser/tasks.py
treeherder/model/tasks.py
treeherder/perf/tasks.py

Since if they are left as integers New Relic treats them as fields that can be graphed.

Bug 1373245 - Send database ID annotations to New Relic as strings

---

neutrino-custom/base.js
package.json
yarn.lock

The webpack-md5-hash plugin attempts to make the generated hashes less susceptible to churn when chunks haven't actually changed. However it requires careful use and clearly wasn't set up correctly, since the manifest file hashes were always the same regardless of content, causing stale files and runtime errors in production.
Once Neutrino v6 is released, we can use its new in-built support for caching to save having to implement this ourselves.

Bug 1373376 - Remove broken webpack-md5-hash configuration

---

treeherder/etl/buildbot.py

Thunderbird's mozmill builder was split into chunks in https://bugzilla.mozilla.org/show_bug.cgi?id=1342828 which leads to treeherder not being able to properly identify them. This teaches treeherder how to detect them again.

Bug 1342828 - Detect mozmill builders that are split into chunks.

---

tests/ui/unit/filters.tests.js

Updates the test since after bug 1361835, an infinity result returns the infinity symbol rather than the string `Infinity`.

Bug 1364031 - Fix failing displayNumber test

---

package.json
yarn.lock

To pick up the fix for failing JS tests not making the Travis run fail (mozilla-neutrino/neutrino-dev#268).

Bug 1364030 - Update to neutrino-preset-karma 4.2.1

---

tests/jenkins/pages/treeherder.py

The locators were updated on the page for setting items to top or bottom of the range.

Jenkins/tests: fix locators for test_range.py

---

package.json
ui/js/components/logviewer/logviewer.js
ui/js/controllers/main.js
ui/js/controllers/perf/graphs.js
ui/js/directives/treeherder/main.js
yarn.lock

There were only two tiny issues that affected us:
* $.bind has been deprecated, so it is a switch to $.on
* Found a function that was dead code, so removed it

Bug 1364882 - Upgrade from JQuery 2.x to 3.x

---

treeherder/model/fixtures/repository.json

Hopefully this addresses both bug 1376166 as well as https://github.com/mozilla/snippets-tests/pull/115#issuecomment-310631998
/cc @davehunt @glogiotatidis

Bug 1376166 - Add/change Snippets Service repo and GitHub account in Treeherder

---

ui/js/reactrevisions.jsx

This hopefully fixes Bugzilla bug [1372372](https://bugzilla.mozilla.org/show_bug.cgi?id=1372372).
This capitalizes all revision initials, so in scenarios like Sotaro Ikeda where they have just registered their name as 'sotaro' - at least we have a properly capitalized, more visible initial.
Before (note tiny lowercase 's' superscript to the user icon):
Proposed (capitalized):
The change only alters the first letter, so intercap cases like 'VanderMeulen' will be preserved :)
Tested on OSX 10.11.5
Nightly **55.0a1 (2017-06-12) (64-bit)**

Bug 1372372 - Capitalize all user initials in revision list

---

treeherder/webapp/graphql/schema.py
treeherder/webapp/graphql/types.py

This GraphQL Schema addition is a little different in that we are enabling the return of an object that is not represented by a Django Model.  The Bug Suggestions is fetched from the cache and returned as an object.  So I've introduced a new ``ObjectScalar`` to represent a simple ``Object`` type to be returned.

Bug 1375712 - Return bug suggestions from graphql queries

---

ui/js/controllers/jobs.js

I believe this is the only place where taskcluster errors are not sticky currently.

Bug 1376517 - Make add-new-jobs errors sticky

---

.travis.yml
bin/post_compile
docs/common_tasks.rst
docs/deployment.rst
docs/installation.rst
docs/ui/installation.rst

Docs: `yarn run foo` -> `yarn foo`

---

tests/ui/unit/controllers/pinboard.tests.js
ui/partials/main/thPinboardPanel.html
ui/plugins/pinboard.js

If a 12 or 40 char string consisting only of a-f,0-9 is pasted into the classification textbox, or if the pasted string contains 'hg.mozilla.org', automatically select the 'fixed by commit' classification type, to reduce the number of clicks needed to properly classify this failure.

Bug 1371820 - Automatically select 'fixed by commit' classification type in certain circumstances

---

tests/jenkins/Jenkinsfile
tests/jenkins/requirements.txt
tests/jenkins/tox.ini
treeherder/model/fixtures/repository.json

This renames the repository within the "qa automation tests" group in Treeherder from the original 'treeherder-tests' to simply 'treeherder'. This reflects the functional UI tests moving to the main repository. It also enabled submitting the results of these tests running in Jenkins to Treeherder, and updates the test dependencies to take advantage of the latest features from these packages.
Note that ultimately the tests in the 'jenkins' folder will be migrated into the 'selenium' folder, and will be executed in Travis CI. We may continue to run the tests in Jenkins and report results to ActiveData/Treeherder as a form of monitoring, much like we do today.
I ran an adhoc build from this branch, which can be seen here: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/treeherder.adhoc/ …

Bug 1377138 - Add Treeherder repository to Treeherder

---

setup.cfg

This stops the broken mozlog plugin being loaded, which was preventing us updating to newer pytest. Other unused plugins have also been disabled, to avoid future issues and improve pytest load times.

Bug 1378118 - Disable unused auto-loaded pytest plugins

---

tests/webapp/api/test_performance_data_api.py

Previously it was dependant on the order of results returned by the API, when the backing DB query doesn't use an ORDER BY. This means that changes in the optimiser (eg upgrading to a different MySQL version) could cause the test to fail.
Also removes the typoed (and redundant) `format` parameter from the `APIClient` call.

Bug 1378950 - Fix test_summary_performance_data non-determinism

---

.travis.yml
vagrant/env.sh
vagrant/setup.sh

**1) Update to MySQL 5.7 in Vagrant/Travis**
The Vagrant environment is running Ubuntu 16.04, which has a native mysql-server-5.7 package available, so doesn't need a custom APT repository to be set.
Travis is still on Ubuntu 14.04 (since they don't offer an Ubuntu 16.04 image yet), so has to use the upstream mysql.com repository instead.
In the future I'll be switching both Travis and local development to use the same Docker images to avoid these kind of differences.
After this lands, we'll want to open a PR against the Terraform configs to switch the treeherder-dev RDS instance to MySQL 5.7, before doing the same for stage/prod.
**2) Stop vendoring libmysqlclient in Vagrant/Travis**
Now that we're using MySQL 5.7 server, there is no longer a conflict between our desired choice of client …

Bug 1378433 - Update to MySQL 5.7 in Vagrant/Travis

---

ui/entry-index.js
ui/js/controllers/tcjobactions.js

This used to be vendored, but vendored in such a way that it defined a
global named `jsonSchemaDefaults`.  Just requiring it in the entrypoint
does not have the same effect. So, require it where it's used like a
normal JS module.

Actually require jsonSchemaDefaults where it's used

---

ui/js/services/tcactions.js

JSON-e defines `{$json: ..}`, and that's what the actions documentation
says, but Treeherder has been expecting `$dumps`, and the current
`action.json` files use `$dumps`.  So this is the first step toward
migrating to the JSON-e standard: make TH accept both.  Once this is
deployed, we can switch the in-tree code to generate `$json`.  A little
while later, we can switch TH to use JSON-e instead.
Custom actions have been broken for a few months now (from March 1 until #2619 is deployed) so I am not much more worried than that about breaking things.

Bug 1335920 - support both $dumps and $json

---

.travis.yml
vagrant/setup.sh

This updates the version used in Vagrant and on Travis to the latest
release. The Heroku addon version will be updated separately to match.
Changes between the two versions:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.3.2.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.3.3.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.4.0.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.4.1.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.4.2.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.4.3.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.5.0.html

Bug 1378361 - Update Elasticsearch from 5.3.1 to 5.5.0

---

bin/pre_compile

Since the Python buildpack now restores the cache prior to the `bin/pre_compile` script being run, which makes the workaround unnecessary and in fact breaks clean installs.

Bug 1381242 - Heroku: Remove workaround for buildpack caching bug

---

package.json
ui/js/services/tcactions.js
yarn.lock

This replaces the old, "fake" JSON-e with the real JSON-e library.
The library is packaged as a service since the action spec will
eventually specify additional context values, and we want to apply those
values universally.

Bug 1335920 - Use JSON-e directly to parameterize action tasks

---

tests/test_setup.py

Since unlike for Vagrant/Heroku, on Travis we have to upgrade from MySQL 5.6 to 5.7 and so there are still enough MySQL 5.6 remnants behind that cause the test to fail (eg libmysqlclient18, old libmysqlclient-dev header files etc). Multiple attempts have been made to clean them up to no avail, and since this will go away soon when we switch Travis to using Docker images (since they won't have an existing older MySQL version installed), it's not worth spending any more time on it.
We still have the custom Django system check that ensures that the libmysqlclient against which mysqlclient-python was built against is from MySQL >5.7.11.

Bug 1378433 - Skip test_mysqlclient_tls_enforced() on Travis

---

bin/pre_compile

Since the OS package present in the Heroku-16 image is now new enough (v5.7.x) that it's not affected by [the MITM issue](https://github.com/heroku/stack-images/pull/38). See:
https://devcenter.heroku.com/articles/stack-packages

Bug 1365567 - Heroku: Don't vendor libmysqlclient on Heroku-16

---

tests/sample_data/pulse_consumer/github_push_commits.json
tests/sample_data/pulse_consumer/transformed_gh_push.json
treeherder/etl/resultset_loader.py

We use python .format() to concatenate the commit author’s name and
email address.  But if it has extended characters, it can’t go into a String.
So this makes sure to put those fields into a Unicode field to preserve them.
The original error should have been raised (or not caught) but instead I was allowing the code to continue until it threw the ``AttributeError`` later due to calling ``.get()`` on a null object.

Bug 1372581 - Handle latin characters in commit author names

---

package.json
ui/entry-perf.js
yarn.lock

metrics-graphics is built over d3. So there is no need to add its pacakage separately.
Direct include of metrics-graphics is redundant with the angular fixture.

Bug 1350384 - [Follow Up] Remove redundant dependencies

---

ui/entry-perf.js

Since numeral is being included using an angular fixture it is not required to add
it in entry-perf.js

Bug 1164891 - [Follow Up] Remove directly included numeral library

---

ui/js/controllers/bugfiler.js

In the case where no usable filename is found, getting bug summaries to be suggested depends on matching the entirety of anything listed in search_terms. When we drop the omittedLeads from the summary, that causes the matching to fail. So lets not drop omittedLeads in those cases.

Bug 1351141 - Don't omit usually unneeded leads if omitting them causes no match with search_terms

---

treeherder/config/settings.py

Now that we are also ingesting HG pushes via Pulse, this celery beat
fetch interval is just a failsafe.  So we can decrease the interval from
every minute to every 5 minutes.

Bug 1065567 - Decrease pushlog interval to 5 minutes

---

neutrino-custom/lint.js
ui/js/controllers/perf/graphs.js

http://eslint.org/docs/rules/no-unneeded-ternary

Bug 1385432 - Add  'no-unneeded-ternary' eslint rule

---

.travis.yml
runtests.sh

Verifies installed packages have compatible dependencies, to help prevent issues like bug 1324707.
This will also reduce the time taken to review pyup bot PRs.
Example output if errors found:
```
Running pip check
celery 3.1.25 has requirement kombu<3.1,>=3.0.37, but you have kombu 4.1.0.
```

Bug 1317275 - Run pip check on Travis

---

vagrant/setup.sh

Since the archives have now been updated to no long include the unwanted additional packages:
https://github.com/heroku/heroku-buildpack-python/issues/379#issuecomment-319223312

Bug 1387266 - Vagrant: Remove Python archive workaround

---

tests/jenkins/tests/conftest.py

@davehunt thoughts?
Ad-hoc run is here: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/treeherder.adhoc/37/
Raw output: https://gist.github.com/stephendonner/ee5d4ee702c23d6ab56c3415f4834379
Some notes of my own:
1) you'll probably want us to remove the selenium.window.maximize() code, right?  If not here, then in a follow-up patch
2) re: docs - I was surprised to re-discover that we didn't move any of the README content over, when this was migrated from the treeherder-tests repo in https://github.com/mozilla/treeherder/commit/1d1f651ce4103d82b4e7f839cffd815c349b8935; so, should we put in something a la https://github.com/mozilla-services/socorro/blob/ea37047733100340ff775a8346c48c105a576399/e2e-tests/README.md albeit less verbose?

Switch to using Marionette/geckodriver

---

Procfile
bin/run_gunicorn

To ensure that:
* the Heroku router's 30 second timeout doesn't beat gunicorn to it, given that routing time is included in Heroku's timing
* the app is more likely to remain responsive, when receiving many badly filtered API calls

Bug 1387487 - Reduce gunicorn maximum request time to 20 seconds

---

treeherder/auth/backends.py

Replace all instances of `scope_match` with `scopeMatch` as the former is deprecated according to a warning outputed after testing in Vagrant. Only instances were found in `treeherder/auth/backends.py`.

Bug 1378935 - Replace deprecated scope_match with scopeMatch

---

treeherder/webapp/api/jobs.py

This is a huge table and the unbounded query (no job ids) takes too long
and is useless anyway.

Bug 1387147 - Prevent unbounded /jobdetail query

---

treeherder/client/thclient/client.py

**1) Remove deprecated features**
Since they've been deprecated for months in existing releases, and we're bumping the major version shortly.
**2)  Bump version to 4.0.0**
Changes:
* Removal of `TreeherderArtifact`, `TreeherderArtifactCollection` and `get_artifacts()` since the REST API no longer supports submitting artifacts independently of the job data submission.
* Removal of `TreeherderRevision`, `TreeherderResultSet` and `TreeherderResultSetCollection` since pushes can now only be submitted via Pulse.
* Removal of the previously deprecated `add_revision_hash()` since revision hashes are no longer required, and instead the revision should be added to a job directly, using `add_revision()`.
* Removal of the previously deprecated `protocol` and `host` parameters to `TreeherderClient`. …

Bug 1387711 - Prepare for treeherder-client v4.0.0 release

---

tests/etl/test_perf_data_adapters.py
treeherder/etl/perf.py

For subtest performance alerts, repository-wide setting should trump
configured one

Bug 1387562 - Fix erroneously-generated subtest performance alerts

---

.travis.yml

As of a few days ago, the `latest` alias now maps to Firefox 55 rather than Firefox 54.0.1. However the JS tests for some reason frequently time out with Firefox 55, so until that's resolved we must explicitly use the older version.

Bug 1388513 - Travis: Downgrade to Firefox 54.0.1 to avoid timeouts

---

docs/seta.rst
treeherder/seta/management/commands/initialize_seta.py

This populates the job priority table with data locally.
It puts all jobs into the table without considerations of analyzing failures.
That can follow up in the future.
Update docs accordingly.

Bug 1388862 - Management command to initialize SETA locally

---

README.md

* Switches the requires.io to pyup.io
* Uses the new form david-dm badge URL to fix deep linking
* Uses HTTPS for the read the docs badge

Bug 1389756 - README: Update/fix badges

---

vagrant/setup.sh

**1) Move the cleanup step earlier in provision**
To reduce the risk that one of the commands we run is broken by things that need cleaning up (eg pyc files). An unnecessary `|| true` has also been removed from the moved `rm -f` command.
**2) Remove .pyc files during provision**
To prevent confusing pytest `ImportMismatchError` exceptions if the paths hardcoded in pyc files (which are git-ignored) leftover from the past, don't match the paths used now.

Bug 1390573 - Clean up stale pyc files during Vagrant provision

---

tests/jenkins/pages/treeherder.py

Many of the current Jenkins test failures are due to a "list index out of range" error caused by the browser closing prior to loading the data. This change should fix that.

Fix test failure list index out of range

---

ui/js/controllers/tcjobactions.js
ui/partials/main/tcjobactions.html

When an action has no schema, this hides the JSON payload field and
doesn't try to JSON.parse it.
Note that this still fails for schema = {}, since json-schema-defaults
returns `undefined` for that value.

Bug 1383085 - handle actions with no schema

---

.travis.yml

Previously the Travis run took anywhere from 8 to 15 minutes (wall time) to complete, which both holds up merging of PRs and also Heroku deployments (since the latter isn't triggered until the additional Travis run on master completes).
The long pole (and also the cause of the large variance) was the Javascript UI tests job, which was being run on the slower Travis container infrastructure. For longer running jobs, the boot time penalty of the fully virtualised GCE infrastructure is far outweighed by the faster CPU/more RAM.
After these changes, the Travis end-to-end time is now consistently in the 4m40s-5m50s range.
For more details see the individual commit messages.

Bug 1390517 - Speed up the Travis run

---

treeherder/webapp/api/jobs.py

If an invalid param value, such as ``job_id__id=‘’`` is passed in, we
will return a 400 response instead of a 500.

Bug 1387147 - Return a 400 for JobDetail bad params instead of 500

---

ui/plugins/pluginpanel.html

This hopefully fixes Bug [1384955](https://bugzilla.mozilla.org/show_bug.cgi?id=1384955).
I've named it Create Task. Since that is the page you land on, in TaskCluster. In my opinion, if the menu name gets changed, it should also change on the TaskCluster page so they are the same.
Proposed:
Nightly **57.0a1 (2017-08-03) (64-bit)**
Chrome Release **59.0.3071.115 (Official Build) (64-bit)**

Bug 1384955 - Add Create Task to job action menu

---

.travis.yml
package.json
vagrant/setup.sh

This speeds up yarn build by 22% and yarn test by 14%, which helps with Heroku deploy times.
Changelog:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.10.1
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.4.0

Bug 1390598 - Upgrade to nodejs 8

---

tests/auth/test_backends.py
tests/conftest.py
tests/webapp/api/test_auth.py
treeherder/auth/backends.py

```
def test_existing_email_create_user(test_user, monkeypatch, result,
exp_username, email, exp_create_user): 
```
in [tests/auth/test_backends.py](https://github.com/mozilla/treeherder/blob/master/tests/auth/test_backends.py#L106) failing for exp_create_user = False

Bug 1337987 - Remove login backend auth code that finds a user by email, rather than username

---

tests/autoclassify/test_classify_failures.py
tests/e2e/test_jobs_loaded.py
tests/log_parser/test_store_failure_lines.py
tests/model/test_cycle_data.py
tests/webapp/api/test_failureline.py
tests/webapp/api/test_text_log_error.py

Bugzilla Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1223883

Bug 1223883 - Fix pytest warnings("cannot collect test class 'TestFailureDetector' / 'TestApp' because it has a __init__ constructor")

---

.travis.yml
vagrant/mysql.cnf

Using a ramdisk on Travis halves the duration of the pytest command, which even when the Travis setup time is included still reduces Travis end to end time by 30%.
The use of `innodb_flush_log_at_trx_commit=0` in Vagrant reduces pytest time by 30%.

Bug 1392546 - Speed up MySQL I/O in Vagrant/Travis

---

ui/js/controllers/perf/compare.js

* Replicate link should be "replicates" (not "replicate")
* Title for graphs should not be lowercase except for first word

Minor capitalization fixes for perfherder replicate views/links

---

.travis.yml

Since after bug 1390517 the timeouts are gone.

Bug 1388513 - Travis: Switch back to latest Firefox release

---

tests/conftest.py

Just clear the cache instead. Much simpler.

Bug 1393762 - Stop incrementing cache key prefix in unit tests

---

package.json
ui/entry-logviewer.js
ui/entry-perf.js
ui/js/controllers/jobs.js
ui/js/controllers/tcjobactions.js
ui/js/models/resultset.js
ui/js/services/tcactions.js
ui/plugins/controller.js
yarn.lock

This makes it so that if a push has an `actions.json` set of tasks, it will use that over `actions.yml` or pulse-actions when possible. This should prove to be more reliable and have the side benefit of being more secure with our new `authorizedScopes` usage.
*This PR will be easiest to review by going one commit at a time, each bit should be self-contained!*
I'm going to bug @djmitche first so we can make sure this makes sense from a tc perspective and then when we're happy, I'll assign a treeherder reviewer.

Bug 1391321 - Use taskcluster actions.json for all actions

---

treeherder/webapp/api/classifiedfailure.py
treeherder/webapp/api/jobs.py
treeherder/webapp/api/performance_data.py

The deprecation warnings don't show up now. :)

Bug 1389538 - Fix django-rest-framework deprecation warnings about 'rest_framework.filters'

---

tests/auth/test_backends.py
treeherder/auth/backends.py
treeherder/config/urls.py
treeherder/webapp/api/auth.py

Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1389536

Bug 1389536 - Fix Django 1.11 deprecation warnings for url and authenticate()

---

tests/webapp/graphql/test_helper.py
tests/webapp/graphql/test_schema.py
treeherder/webapp/graphql/schema.py

Ironically, my change to job_group broke the GraphQL query optimizations due to the ``select_related`` change required.  I didn't have a test for this workflow, so I added one.

Bug 1215587 - Fix graphql query with job_group change

---

bin/post_compile
treeherder/config/settings.py

**1) Use 'DYNO' to check if running on Heroku**
On Heroku, the environment variable `DYNO` is always set in the environment. As such, we can just use that to determine whether code is being run on Heroku, rather than having to add our own environment variable.
**2) Use .profile instead of set-env**
`set-env` was renamed in the buildpack to `set_env`, breaking this script. Rather than just renaming our usage, it makes more sense to stop using what is really an internal buildpack API and instead use `.profile`:
https://devcenter.heroku.com/articles/dynos#the-profile-file

Bug 1394593 - Fix Heroku deployments with latest Python buildpack

---

Procfile
bin/run_celery_worker
treeherder/config/settings.py
treeherder/etl/runnable_jobs.py
treeherder/etl/tasks/buildapi_tasks.py

Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1330773
For the fetch_allthethings task: In treeherder/Procfile and /treeherder/bin/run_celery_worker, I wasn't really sure of what it does, so I didn't rename it for now.
Could you explain me the purpose of these files and hence, if it has to be renamed as well?

Bug 1330773 - Rename the fetch-allthethings and AllthethingsTransformerMixin task to something that mentions RunnableJobs

---

bin/pre_deploy

This allows deploys to succeed even if the live version of revision.txt is not currently accessible, such as when maintenance mode is enabled.

Bug 1394128 - Heroku: Fail gracefully if revision.txt inaccessible

---

docs/seta.rst

The maintenance section was not addressing that data can take a while before the different scheduled processes bring the data into the right tables.
This addresses documenting how to:
* Update the runnable jobs table
* Update the job priority table

Improve SETA maintenance documentation

---

.travis.yml
package.json
vagrant/setup.sh

**1) Update nodejs from 8.4.0 to 8.5.0**
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.5.0
**2) Vagrant: Use --ignore-engines with yarn install**
To prevent errors when Vagrant provisioning after a new nodejs version is released, due to version mismatch between package.json (used by Heroku) and the APT package used by Vagrant. The other option is pinning the version in Vagrant too, however we might as well wait until the Docker based development environment where state management/invalidation is simpler.

Bug 1399281 - Update nodejs from 8.4.0 to 8.5.0 and use --ignore-engines with yarn install

---

treeherder/etl/job_loader.py

Since previously it was virtually impossible to track down the source of jobs that are still using `revision_hash`.

Bug 1257602 - Include more metadata in revision_hash usage event

---

ui/js/controllers/tcjobactions.js
ui/js/services/tcactions.js
ui/plugins/controller.js

I think I forgot this the original time around. This should make backfilling work again with bbb jobs and with tc. It would be nice if this could land in production without a long wait in stage, but is not 🔥*the-world-is-ending*🔥 urgent!
I've tried this out as much as I can from my development install. Unfortunately backfilling is hard to try out for real.

Bug 1394779 - Fix backfilling with actions.json tasks

---

tests/jenkins/Jenkinsfile

@edmorley this is largely just to keep parity with web-automation suites' shared-library versions.
Full build output; intermittent, currently-known failures: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/treeherder.adhoc/49/console
https://gist.github.com/stephendonner/05664f681ff6768d5b83cac839d09376

Bump shared-library version to 1.9

---

treeherder/credentials/models.py
treeherder/model/models.py
treeherder/perf/models.py

The default value for on_delete is `CASCADE`, so this change is a no-op aside from fixing hundreds of deprecation warnings of form:
```
RemovedInDjango20Warning: on_delete will be a required arg for
ForeignKey in Django 2.0. Set it to models.CASCADE on models and in
existing migrations if you want to maintain the current default
behavior.
```
(Plus the same for `OneToOneField`)
See:
https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.on_delete

Bug 1400222 - Always pass an explicit ForeignKey on_delete value

---

ui/partials/main/thWatchedRepoNavPanel.html

This fixes Bugzilla bug [1400576](https://bugzilla.mozilla.org/show_bug.cgi?id=1400576).
This economizes the markup a bit, and ensures the tooltip will appear when hovering over the entire region of the expand/collapse job group button, not just hovering over the small area where the +/- text exists.
A couple of minor 'Sentence case' tweaks were included in nearby tooltips given we seem to use that style everywhere. I defer to you guys if they make sense.
Nightly **57.0a1 (2017-09-05) (64-bit)**
Chrome Release **60.0.3112.113 (Official Build) (64-bit)**

Bug 1400576 - Improve the expand/collapse job group markup

---

ui/css/treeherder-navbar.css
ui/partials/main/thGlobalTopNavPanel.html

This hopefully fixes Bugzilla bug [1401233](https://bugzilla.mozilla.org/show_bug.cgi?id=1401233).
This prevents typical notifications from being unreadable because they overflow the fixed width property on the dropdown.
Current:
Proposed:
Nightly **57.0a1 (2017-09-16) (64-bit)**
Chrome Release **61.0.3163.91 (Official Build) (64-bit)**

Bug 1401233 - Improve the notification dropdown with a few tweaks

---

ui/js/controllers/perf/compare.js

The default value for showOnlyImportant is 0, but currently showOnlyImportant=1
is stripped from the URL, because it's assumed to be the default, while
showOnlyImportant=0 is occasionally added.

Bug 1400416 - Don't strip showOnlyImportant=1 from perfherder URLs.

---

ui/index.html
ui/userguide.html

The `class='kbd'` usages were missed from the changes in bug 1339508. 
The mismatched tags have been present since the original landing in bug 1139421.
**Before:**
...plus validation errors.
**After:**
...with no validation errors.
Also removes a stray space from index.html.

Bug 1403195 - Fix styling and mismatched tags in userguide.html

---

tests/jenkins/Jenkinsfile

@edmorley @davehunt r?
This was suggested to us a while back by a core Jenkins project member, and nearly all other web-automation projects have it; just bringing this up to parity.
Full build output: https://gist.github.com/stephendonner/0ee5ee9ce654b9f7ad76c7c3df1b68d9 (usual intermittent failures)

Move fxtest-library include into pipeline block

---

ui/partials/main/jobs.html
ui/partials/main/thActionButton.html

This addresses [Bug 1404076](https://bugzilla.mozilla.org/show_bug.cgi?id=1404076)
Moves the link to the Test-based UI show on the Push status bar rather than in the action menu.  Text styling matches "Add new jobs".

Bug 1404076 - Make link to test-based ui more prominent

---

ui/js/services/jobfilters.js

This fixes if you set ``fromchange`` for two different pushes.  It makes sure to replace the value, rather than setting it to multiple values.

Bug 1045609 - Fix replacing filter values on non-field filters

---

ui/css/treeherder-navbar-panels.css
ui/partials/main/thActiveFiltersBar.html
yarn.lock

This hopefully fixes Bugzilla bug [1407775](https://bugzilla.mozilla.org/show_bug.cgi?id=1407775).
This improves a few layout things in the job filters bar:
- pass the full filter.value into a tooltip for long filters
- vertically align the title with adjacent spans, it was slightly out
- delete only on the font awesome icon, not the whole span
- align the contents with the related push block below it
- apply alternate bold/plain styling for each field/value pair for readability
- supporting tweaks as needed
Current:
Proposed:
Nightly **58.0a1 (2017-10-10) (64-bit)**

Bug 1407775 - Improve the layout and info in the job filters bar

---

tests/jenkins/tests/test_filter_panel.py

Keyboard shortcuts are ignored when a checkbox is focused. By closing the filter panel, we shift the focus, and allow the keyboard shortcuts to work.

Bug 1405666 - Close panel after filtering results to avoid keyboard shortcuts from being ignored

---

ui/js/directives/treeherder/clonejobs.js

**Fix for Treeherder Bug 1062463**
https://bugzilla.mozilla.org/show_bug.cgi?id=1062463
Bug summary: User can end up with multiple jobs selected using Ctrl/Cmd - click to pin. When a user pins a new job using cmd-click(mac) or ctrl-click(pc), that job will now be also selected/highlights and the previously selected/highlighted job will be deselected.
Please see link above for screenshots and more information.

Bug 1062463 - Correctly highlight/select jobs when adding to pinboard

---

docs/ui/installation.rst

Fix for Treeherder Bug 1407367
https://bugzilla.mozilla.org/show_bug.cgi?id=1407367
Documentation update summary: Currently running yarn test from within a Vagrant VM fails.  The documentation is updated to explicitly direct users to run yarn test outside of their Vagrant VM.
Please see link above for more information.

Bug 1407367 - Update doc that ui unit tests are not to be run within a VM

---

ui/partials/main/thActiveFiltersBar.html

This hopefully fixes Bugzilla bug [1407807](https://bugzilla.mozilla.org/show_bug.cgi?id=1407807)
This suppresses the Tier field as a choice in the job filter field dropdown list. It's a one off, so the more generalized solution of adding a new display field to all 11 of the `FIELD_CHOICES` object elements in jobFilters.js may not be needed, at least for now.
Proposed (excluding Tier):
Nightly **58.0a1 (2017-10-13) (64-bit)**

Bug 1407807 - Remove Tier as a choice from the job filter field dropdown

---

ui/partials/main/thActiveFiltersBar.html

This hopefully fixes Bugzilla bug [1408496](https://bugzilla.mozilla.org/show_bug.cgi?id=1408496)
This prevents double **author:** entries in the job filter bar. I also economized a bit while I was there so we only have one title property and one field label in the markup.
Current:
Proposed:
Nightly **58.0a1 (2017-10-13) (64-bit)**

Bug 1408496 - Fix duplicate push Author filter bar values

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_filter_jobs.py

This improves test_filter_jobs, which fails when the first result set doesn't include builds with windows or linux platforms. This happens when the gecko decision task is running, and before the additional builds are added. This patch changes the test to select the first result set with the required platforms. It also makes sure that only displayed builds are returned from the page object.
@rbillings r?

Improve test_filter_jobs

---

bin/post_compile

Previously New Relic displayed the hostname for each dyno as "Dynamic Hostname", due to the randomly generated Heroku hostnames. As such, we had to set a manual display name to identify the dyno type reported for each transaction. This was only partly useful, since New Relic doesn't use it in all places of their UI.
However the New Relic Python agent 2.96.0.80 release has now added official support for Heroku dyno names, making this workaround unnecessary:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-252040
https://github.com/edmorley/newrelic-python-agent/commit/d2c4aa097e18da56f6d2d21879796f7ef796f05a#diff-a57cabe85e94b1050fb4ff1749effcf5R335

Bug 1176412 - Heroku: Remove New Relic host display name workaround

---

vagrant/setup.sh

Since in most cases people will use it from the host anyway, and if they don't it can lead to committing changes under the author `vagrant <vagrant@vagrant.vm>`.

Bug 1408683 - Vagrant: Don't install Git

---

.travis.yml
package.json

For parity with Vagrant and to save the hassle of constantly updating.
Heroku uses the version from `package.json`.

Bug 1408954 - Use latest yarn on Heroku/Travis

---

ui/css/treeherder-job-buttons.css

**Fix for Treeherder Bug 1376506**
https://bugzilla.mozilla.org/show_bug.cgi?id=1376506
Bug Summary: the jobs section text was not left aligned. 
Please see link above for screenshots and more information.

Bug 1376506 - Make job row contents flush left like they used to be

---

ui/js/controllers/main.js
ui/partials/main/thActiveFiltersBar.html
ui/partials/main/thWatchedRepoNavPanel.html

This hopefully fixes Bugzilla bug [1407906](https://bugzilla.mozilla.org/show_bug.cgi?id=1407906)
This turns the Filter by a job field button, from an open-only behavior, to a toggle. Everything seems to work fine. I left the Cancel button in for now, so the user has that additional way of closing the input group.
Toggle Input Group Open:
Toggle Input Group Closed:
Nightly **58.0a1 (2017-10-10) (64-bit)**

Bug 1407906 - Make the filter by job field icon a toggle

---

ui/js/services/main.js

Now it is checking for ``undefined`` when the last param
was omitted and assigns it an empty object value.

Bug 1409381 - Fix thNotify when last param is omitted

---

docs/testcases.rst

This fixes Bugzilla bug [1410230](https://bugzilla.mozilla.org/show_bug.cgi?id=1410230).
This updates the wording to match the behaviour of the pinboard limits.

Bug 1410230 - Tweak the pinboard testcase wording

---

ui/js/cache-templates.js

Since:
(a) the reason for it / where the implementation comes from was unclear
(b) it turns out we're including partials in every page's bundle which we really should fix as part of bug 1384255

Bug 1384255 - Improve the documentation of cache-template.js

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_keyboard_shortcuts.py

The filters panel has been changed to a drop down, which is hidden once a job is selected. I've fixed the test by so that it only checks that the job details panel is closed when the keyboard shortcut is triggered.
@rbillings r?

Fix test_close_open_panels

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_get_next_results.py
tests/jenkins/tests/test_load_page_results.py

This improves the two tests that get next results by waiting for the number of results to increase by the specified value. I have also removed some duplication, and parameterised one test to improve overall runtime when distributing tests across multiple processes. Currently, test_load_next_results is failing because it's waiting for the wrong number of results.

Improve tests that get the next results

---

package.json

Typically the `package.json` commands call scripts that exist in the top-level `node_modules/.bin/` directory, which are (a) already on `PATH` when invoked by yarn, and (b) on Windows have `.cmd` script shims that work around Windows' lack of shebang support.
However due to symlinks being problematic inside Virtualbox, we have to use `--no-bin-links` with `yarn install`, which means the top-level `.bin/` directory doesn't exist. As such, the `<package>/bin/` scripts have to be used directly, which require prefixing with `node` to work around lack of shebang support on Windows.
See:
https://shapeshed.com/writing-cross-platform-node/#scripts-in-package-json
Note that even with these changes, the `start:stage` command will not work due to the environment variable prefix. This will be solved …

Bug 1351907 - Improve yarn script compatibility with Windows

---

tests/jenkins/tests/test_expanding_group_count.py

I noticed a failure due to the first result set not having a job group to expand. This changes the test to target the first collapsed job group across all displayed result sets.
@rbillings r?

Improve test_expanding_group_count

---

treeherder/log_parser/parsers.py

Previously schema violations would result in:
`TypeError: not enough arguments for format string`
See [bug 1326250 comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1326250#c1) for why this didn't cause the test to fail. Other than parsing all test stdout/stderr, I'm not sure there is an easy way to make a test for it.
The exception `message` property is used instead of the `str` representation, since the latter results in pages of log output rather than just the human readable message:
https://github.com/Julian/jsonschema/blob/v2.6.0/jsonschema/exceptions.py#L59-L88
https://python-jsonschema.readthedocs.io/en/v2.6.0/errors/#jsonschema.exceptions.ValidationError.message

Bug 1326250 - Fix TypeError in PerformanceParser error logging

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_filter_panel.py

This test is failing because of the recent filter panel changes. There's no longer a checkbox to hide all failures, so I've switched to using the navigation filters. I've also added checks to ensure that there are jobs of the specified type (switched to in progress as they are more abundant), and that there are none when they're hidden by the filter.
@rbillings r?

Fix test_filter_panel_reset_button

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_filter_jobs.py

I noticed we still had failures for this test, which *appear* to be related to the result sets refreshing on the page. This improvement looks across all builds and platforms rather than focusing on the first result set with the necessary platforms, and should be more stable.
@rbillings r?

Further improvements to test_filter_jobs

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_pin_job.py

This improves the pin job tests by using a random job instead of assuming a suitable job exists in the first result set.
@rbillings r?

Improve pin job tests

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_range.py

This improves the tests by working around bug 1411264 and picking result sets relative to the end of the list instead of assuming the number of result sets that exist.
@rbillings r?

Improve range tests

---

tests/jenkins/pages/treeherder.py

This improves the tests that filter using email by working around bug 1411264. Instead of relying on Marionette to wait for the page load after the click, we first wait for the body element to become stale, and then wait for the page to be loaded.

Improve tests that filter by email by working around bug 1411264

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_view_single_result.py

This works around bug 1411264, but also now picks a random result set instead of the first one every time.
@rbillings r?

Improve test_open_single_result by working around bug 1411264

---

tests/jenkins/pages/treeherder.py
tests/jenkins/tests/test_filter_jobs.py
tests/jenkins/tests/test_filter_panel.py
tests/jenkins/tests/test_status_results.py

If a test exceeds ~60 seconds then Treeherder polls for new results and elements become stale. These optimisations aim to reduce the total duration of the tests, whilst also improving coverage.
@rbillings r?

Optimise a few tests that are taking too long in Sauce Labs

---

tests/jenkins/pages/base.py

Looking at the recent UI test failures, it appears that the initial page load often takes more than 10 seconds to display jobs. There are three options to resolve this:
1. Increase the timeout (this patch)
2. Improve the performance of the application
3. Automatically rerun the test
As we're planning to move these tests to run on Travis, where we will have control over the number of results and jobs, and performance/latency will be less of a concern, I have opted for increasing the timeout.
@rbillings, @edmorley r?

Increase timeout to 20 seconds for UI tests

---

ui/partials/logviewer/logviewer.html

Trying to contribute to a FOSS project at Mozilla for the first time, and it seems this one is just about adding a sandbox attribute, so I thought I would try it out.
It appears that the only permissions needed in order for the iframe to show is allow-scripts and allow-same-origin.

Bug 1328710 - Set the sandbox attribute for the iframe used in the log viewer to improve security

---

tests/jenkins/pages/treeherder.py

Another case were we click and the page load detection in Firefox is not kicking in.

Improve test_switch_repo by working around bug 1411264

---

tests/jenkins/pages/treeherder.py

I've seen a couple of failures that are related to the tests trying to interact with the info panel before it's finished loading. This waits for the loading overlay to be removed before continuing after showing job details.
@rbillings r?

Improve wait after showing job details

---

tests/jenkins/tests/test_view_single_result.py

After clicking a result set, we wait for there to be at least one job displayed so that we are confident that the page has loaded enough to continue with the tests. This change ensures we only attempt to view a result set that has at least one job associated.
@rbillings r?

Fix test_open_single_result by avoiding result sets with no jobs

---

.travis.yml
bin/travis-setup.sh

This:
* reduces duplication
* opens the door to sharing functionality with `vagrant/setup.sh`
* will make it easier to visualise the Travis bootstrap process when moving both Travis and Vagrant to a unified Docker environment.
Plus some other cleanup.

Bug 1414094 - Travis: Move setup steps to a reusable script

---

bin/travis-setup.sh

Now that Firefox supports being run in headless mode, we no longer need to use the xvfb workaround on Travis.

Bug 1414247 - Travis: Use Firefox headless mode instead of xvfb

---

ui/js/models/perf/alerts.js

It used toLocaleFormat, which was never standard and seems to no longer be defined
in recent Firefox versions. Use toUTCString instead, which seems to be available
everywhere.

Bug 1414312 - Fix perfherder textual alert summary copy function on recent Firefoxen

---

bin/travis-setup.sh

Since it reduces the intermittent failure rate in bug 1401048 and is also likely more representative of what people are using to access Treeherder in production (whilst still being more stable than Nightly).

Bug 1414667 - Travis: Test using Firefox beta instead of stable

---

vagrant/.profile

Since the `.profile` script is sourced in the login shell, so using strict mode can cause the shell to exit and so `vagrant ssh` to not work. Instead we fix the SC2164 using the method here:
https://github.com/koalaman/shellcheck/wiki/SC2164

Bug 1414255 - Vagrant: Use alternative fix for shellcheck SC2164

---

ui/js/models/resultsets_store.js

It [looks](https://github.com/mozilla/treeherder/pull/2057/files#diff-9da180a71af78c18a9d5089198b6099fL356) like it was meant to be temporary.

Get runnable jobs from current decision task on every project.

---

tests/jenkins/tests/test_status_results.py

It may be coincidence but since https://github.com/mozilla/treeherder/commit/51dc3cc938234c441c6b95a9715ac0daf5f03f9c I've seen an increase in failures for the tests exercising the status filters. It seems that every so often the filter takes a little longer than expected to apply. I have fixed this in the tests by introducing a wait instead of relying on the timing of the test when it immediately checks the results after applying the filter.

Wait for the status filters to be applied during tests

---

tests/webapp/api/test_performance_data_api.py
treeherder/webapp/api/performance_data.py
treeherder/webapp/api/performance_serializers.py
ui/js/controllers/perf/dashboard.js
ui/js/controllers/perf/graphs.js
ui/js/models/perf/alerts.js
ui/js/services/perf/compare.js

* Make the performance data api accept signature id as input
* Rewrite most of the frontend to use that API in preference to passing
in signature hashes
* Correspondingly increase the chunks of comparison data we fetch
at once

Bug 1265709 - Reference perf signatures by id instead of hash where possible

---

neutrino-custom/base.js
package.json
tests/ui/unit/init.js
tests/ui/unit/react/revisions.tests.jsx
ui/entry-index.js
ui/js/reactrevisions.jsx
yarn.lock

This fixes [Bug 1364891](https://bugzilla.mozilla.org/show_bug.cgi?id=1364891)
Most notable change here is that React.PropTypes is now
moved to a separate package and referenced just by
PropTypes.  So this needed some import and linting changes.

Bug 1364891 - Update from React 15.3 to 15.6

---

ui/js/components/perf/compare.js
ui/js/controllers/perf/alerts.js
ui/js/controllers/perf/dashboard.js
ui/js/controllers/perf/e10s-trend.js
ui/js/controllers/perf/graphs.js
ui/js/filters.js
ui/js/models/job.js
ui/js/models/perf/alerts.js
ui/js/models/repository.js
ui/js/models/resultsets_store.js
ui/js/services/jsonpushes.js

Just wanted to see if this is the type of refactor you were looking for.
I kept it to _.filter; do you want a new PR for each function replacement?
I am also slightly concerned about any lodash-specific "iterables". I assumed these
iterables were only arrays. I didn't run into any errors while testing and running
the unit tests. 
"""
Remove existing lodash filter function and replace with
es6's array.filter(). Some whitespace changes were
made for clarity or because the linter got upset.
"""

Bug 1413156 - refactor _.filter to es6 array.filter

---

vagrant/.profile

The bento image has renamed the network interface from `enp0s3` back to `eth0`, effectively reverting the upstream Ubuntu 16.04 "predictable network interface names" feature. We now have to calculate the name dynamically, since we don't know which version of the bento image will be installed locally when people use the Treeherder Vagrant environment.
Tested by performing a `vagrant destroy -f && vagrant up && vagrant ssh`, then `./manage.py runserver` in the VM and confirming 127.0.0.1:8000 connects successfully from the host.

Bug 1417099 - Vagrant: Fix networking when using latest Bento images

---

ui/js/services/jobfilters.js
ui/partials/main/thActiveFiltersBar.html

This hopefully fixes Bugzilla bug [1408671](https://bugzilla.mozilla.org/show_bug.cgi?id=1408671).
This maps the 'id' of the failure_classification_type in the UI to its human readable string. Previously you'd just get the number passed from the filter value in the URL.
Before:
Proposed:
I still have a bit more testing to do, so marking as DNM for now. I'll update and assign this for review when I'm satisfied all my test cases and workflows are fine.
Nightly **58.0a1 (2017-11-07) (64-bit)**

Bug 1408671 - Display job field filter classification by name not id

---

ui/js/components/perf/compare.js
ui/js/controllers/perf/compare.js
ui/js/perfapp.js
ui/js/services/perf/compare.js
ui/partials/perf/comparectrl.html
ui/partials/perf/comparesubtestctrl.html
ui/partials/perf/comparetable.html

this works for summary and subtest, probably has a lot of potential wins and logic to improve upon- for now I want to get a first attempt rolled out for easier comparison of new platforms.

Bug 1416347 - Implement a solution for generating a noise metric when viewing perfherder compare

---

ui/js/services/jobfilters.js
ui/partials/main/thActiveFiltersBar.html

Still some issues with reload, so I've opened a PR for @camd or @edmorley to revert my change, in case that helps save them a minute or two.
This reverts commit 94739118f9f746ee7fd2c47af22896539d71cf17.

Revert "Bug 1408671 - Display job field filter classification by name not id (#2922)"

---

ui/js/models/repository.js

Some new linter rules added after 4ca94fca62f2564729ff4db88d821b5fd556a3b1
was merged failed a line of code that had an implicit return value
of `undefined`.
I don't have any linter errors on my end of things (branching off master). This is a shorter way of writing that function that will never have an implicit return value. I'm not quite sure why `return repo` was used since the predicate function passed to both `Array.filter()` and `_.filter()` expects a bool return value.

Bug 1413156 - fix linter "array-callback-return" error

---

.yarnrc
bin/travis-setup.sh
docs/common_tasks.rst
docs/deployment.rst
docs/installation.rst
docs/seta.rst
docs/ui/installation.rst
vagrant/setup.sh

**1) Docs: Remove unnecessary `yarn install` steps**
The vagrant provision runs `yarn install`, so it isn't necessary to do so again before running `yarn start`.
**2) Docs: Clarify which node/yarn version should be used**
Since for people installing node/yarn on their own (outside the Vagrant environment) it can be confusing to work out which version is appropriate, given node always has both an LTS and current release.
**3) Disable yarn strict engines mode using .yarnrc**
As of yarn 1.0+ if the version of node or yarn doesn't match that specified in `package.json`, yarn commands will fail to run and complain about incompatible versions. Unfortunately the error message doesn't really make it clear that the user has the wrong version installed, and instead gives the impression something is …

Bug 1416257 - Make it easier for contributors to set up a node environment

---

docs/installation.rst

Since recent Vagrant now bundles its own SSH client.

Bug 1419167 - Vagrant: Remove unnecessary MSYS SSH pre-requisite

---

ui/js/controllers/jobs.js
ui/js/controllers/main.js
ui/js/controllers/perf/alerts.js
ui/js/controllers/perf/dashboard.js
ui/js/controllers/perf/e10s-trend.js
ui/js/controllers/perf/graphs.js
ui/js/directives/treeherder/clonejobs.js
ui/js/models/perf/alerts.js
ui/js/models/resultset.js
ui/js/models/resultsets_store.js
ui/js/services/classifications.js
ui/js/services/pinboard.js
ui/plugins/controller.js

I looked around for usages of _.forEach and found several places where it could be replaced trivially. Unfortunately I could not remove it entirely because it is used on both arrays and objects.

Bug 1413156 - Remove lodash forEach usage for arrays

---

ui/js/services/jobfilters.js
ui/partials/main/thActiveFiltersBar.html

This hopefully fixes Bugzilla bug [1417666](https://bugzilla.mozilla.org/show_bug.cgi?id=1417666).
This tweak adds the ability to clear all field filters in one click by hooking to the existing unused function `removeAllFieldFilters()`, and to clear field filters sequentially without having to mouse to arbitrary points on screen by placing the close icons at the front of each filter.
Current:
Proposed:
Nightly **59.0a1 (2017-11-15) (64-bit)**

Bug 1417666 - Improve field filter clearing workflows

---

ui/css/treeherder-info-panel.css

Windows can show double-bolding with "font-weight: bolder".  But our
logic for highlighting common terms sometimes adds nested ``<strong>``
elements due to substrings.  This makes them all just "bold" regardless
of how much they're nested.

Bug 1418286 - Fix bolding of common terms in bug suggestions on Windows

---

ui/partials/main/thShortcutTable.html

This fixes Bugzilla bug [1419923](https://bugzilla.mozilla.org/show_bug.cgi?id=1419923).
This removes the unimplemented `F1` key placeholder in the shortcut table, since there are no future plans for inline UI help at this time as originally discussed in the Description of bug [1141569](https://bugzilla.mozilla.org/show_bug.cgi?id=1141569).
Nightly **59.0a1 (2017-11-22) (64-bit)**

Bug 1419923 - Pull unimplemented F1 key from shortcut table

---

ui/js/controllers/userguide.js
ui/userguide.html

This hopefully fixes Bugzilla bug [1419966](https://bugzilla.mozilla.org/show_bug.cgi?id=1419966).
This provides a dynamic date example for the `&startdate` and `&enddate` query filters, so they never fall out of date or otherwise result in the users browser freezing trying to load a year's worth of pushes from a static start/end date example.
Visually the examples are unchanged, except I think they may print as D or M for single integer days, but in testing I think Treeherder handles those. I also added a YYYY-MM-DD cue in the description.
Proposed:
Nightly **59.0a1 (2017-11-22) (64-bit)**

Bug 1419966 - Angularize start/end query examples in the User Guide

---

bin/travis-setup.sh

**1) Don't install custom yarn**
Since I've adjusted the Travis images to always use the latest yarn at the time the images are created, so it's not worth installing the latest version at every runtime.
**2) Skip Elasticsearch install if version matches**
Since I've updated the Travis images so that the pre-installed version of Elasticsearch matches the one we're looking for, meaning the download/install can be skipped, saving time.

Bug 1389572 - Travis: Speed up yarn and Elasticsearch setup

---

.travis.yml
package.json

Since the node minor/patch versions are reliable enough that it's not worth the hassle of pinning to an exact version. This only affects Heroku/Travis, since Vagrant was already always using the latest 8 series release via the APT repo.
This effectively upgrades node on Heroku/Travis from 8.9.0 to 8.9.1, since it's the latest release at the moment:
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.1
The yarn version specifier has been adjusted to use the `.x` format, which gives the same end result as the caret range, given Heroku doesn't cache binaries from one build to the next (only `node_modules`).

Bug 1419987 - Always use latest minor version of node.js

---

ui/js/controllers/perf/compare.js
ui/js/models/perf/alerts.js
ui/js/models/perf/series.js
ui/js/services/perf/compare.js

This means we no longer display tests as being a "summary" in the
test chooser (you can generally figure that out by noticing that there
is no subtest specified).

Bug 1416870 - Always use abbreviated mode for calculating performance test name

---

ui/js/values.js

This changes the times shown in the UI to be padded with a leading zero if the hour is only a single digit (ie between midnight and 10am). This fixes the test failure in `test_open_single_result()`, since that expects the hour to use padding.

Bug 1421111 - Use double digit hours in UI datetimes

---

.coveragerc

Since it's not currently used, and at whatever point we add Python test coverage tracking, we'll likely need to overhaul it anyway.

Remove .coveragerc

---

.gitattributes
docs/troubleshooting.rst

This prevents `$'\r': command not found` bash errors caused by CRLFs when Windows hosts have suboptimal global Git configurations, meaning one less thing that can go wrong / that needs documenting.
See:
https://help.github.com/articles/dealing-with-line-endings/
https://git-scm.com/docs/gitattributes
https://github.com/alexkaratarakis/gitattributes/blob/master/Web.gitattributes

Bug 1419168 - Add a .gitattributes file to force Linux line endings

---

ui/css/treeherder-info-panel.css

This hopefully fixes Bugzilla bug [1419994](https://bugzilla.mozilla.org/show_bug.cgi?id=1419994).
This returns the pin icon in the Failure Summary tab to its former approximate width, and also so it matches the same dimensions as its sibling in the Failure Classification tab.
We still need the `failure-summary-bug` tags in the markup for other formatting, but it appears we can pull this css target without affecting anything else (that I can find).
Current:
Proposed:
Nightly **59.0a1 (2017-11-27) (64-bit)**

Bug 1419994 - Fix failure Summary pin icon width

---

tests/jenkins/requirements.txt

Not sure if you want this, @edmorley - same failures as on master, but it seems there's some extra debug spew on failures, since pytest 3.3.0.
At least it doesn't seem affected by https://github.com/pytest-dev/pytest/issues/2956
Full console log: https://pastebin.com/eWEU8qk5
/cc @davehunt

Update pytest to 3.3.0

---

vagrant/.profile

On platforms that are not Windows, the Vagrantfile enables a second virtual network adapter to allow NFS to work. However this breaks the fix in bug 1417099, since it only expected one interface to be returned by the grepped `ip` output. We could have adjusted that fix to instead iterate through the results, however it's easier to just use a wildcard with `iptables` instead, since we know all ethernet adapters start with the letter `e`.

Bug 1421073 - Vagrant: Fix networking on non-Windows platforms

---

tests/etl/test_runnable_jobs.py
treeherder/config/settings.py
treeherder/etl/common.py
treeherder/etl/runnable_jobs.py

The runnable jobs API now fetches runnable-jobs.json if available and fallsback to
full-task-graph.json.
The new file is less than a tenth of the original file and contains the minimum
amount of data required for the endpoint.
You can test this locally with:
http://localhost:8000/api/project/try/runnable_jobs/?format=json&decision_task_id=DAKx7zD0RkWwa4dFs03kgA
You can check the new file in here:
https://public-artifacts.taskcluster.net/DAKx7zD0RkWwa4dFs03kgA/0/public/runnable-jobs.json
How can I run the tests for this? I would like to add a new test case.

Bug 1288028 - Reduce latency of runnable jobs API

---

tests/model/test_cycle_data.py
treeherder/model/management/commands/cycle_data.py

Since it's timing out due to missing indexes, preventing the rest of the jobs data cycling from taking place (resulting in disk space usage alerts).

Bug 1346567 - Temporarily disable perfherder data cycling

---

tests/jenkins/Jenkinsfile

@edmorley r? 
Suggested temp fix/workaround from Sauce Labs, for a working Firefox 57 instance; I'll definitely circle back and fix to "57.0" once their permanent fix is live.
Ad-hoc build results here, comparable with master: https://gist.github.com/stephendonner/e79e12e778b90977ddb08fbd0e598b62

Update to Firefox 57

---

ui/css/treeherder-info-panel.css
ui/plugins/pluginpanel.html

This hopefully fixes Bugzilla bug [1421107](https://bugzilla.mozilla.org/show_bug.cgi?id=1421107).
This returns functionality lost in Treeherder which prevents the performance tab from wrapping at smaller browser widths if a Perf job is selected.
Current (tab incorrectly wrapping):
Proposed:
I applied the `min-width` to the `ul` which was the most direct element, rather than multiple parents higher in `job-tabs-panel` which was done in the original implementation in https://github.com/mozilla/treeherder/pull/1002.
Everything seems fine in local testing on OSX selecting both Perf and non-Perf jobs.
Nightly **59.0a1 (2017-12-02) (64-bit)**

Bug 1421107 - Stop perf tab wrapping at narrower widths

---

.travis.yml

By design, Travis runs all commands in `scripts` even if earlier ones fail. However in the case of the selenium tests, they are expected to fail if `yarn build` failed, so running them regardless only makes the log output harder to follow. Moving `yarn build` to `before_script` means the job will instead be aborted prior to running the tests.

Bug 1423376 - Travis: Skip selenium tests if yarn build failed

---

vagrant/setup.sh

Passes locally even given the newly added checks:
https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md#v047---2017-12-08

Vagrant: Update shellcheck from 0.4.6 to 0.4.7

---

ui/css/treeherder-navbar.css
ui/partials/main/thWatchedRepo.html
ui/partials/main/thWatchedRepoInfoDropDown.html

This hopefully fixes Bugzilla bug [1422208](https://bugzilla.mozilla.org/show_bug.cgi?id=1422208).
This prevents the watched repo dropdown menu from clipping off screen when the first listed repo name is short (eg. 'Ash').
Current (clipped):
Proposed:
Other menus:
It seemed to be the least invasive way to fix the issue. For repos 'two' and 'three' in the row per above, the drop down now lies flush left with its parent repo container. Which seems to make the most sense.
I also tightened up the spacing between the info button and its repo name, so they look paired with each other. And I capitalized 'Unwatch repo'.
Nightly **59.0a1 (2017-12-12) (64-bit)**

Bug 1422208 - Stop the watched repo dropdown clipping off screen

---

vagrant/env.sh

* `ENABLE_LOCAL_SETTINGS_FILE` is no longer references anywhere.
* `GRAPHQL` now defaults to `True`, so doesn't need to be overridden.

Vagrant: Remove redundant environment variables

---

renovate.json

Now that the group package PR title and commit messages have been adjusted upstream, our config no longer needs to override them. See:
https://github.com/renovateapp/renovate/commit/1e4bebe627d8fe55328b4ac9546cf92e295b7b90
[skip ci]

Bug 1409778 - Simplify Renovate configuration

---

treeherder/model/migrations/0020_remove_project_specific_id.py

To fix deployment, since it's currently failing with:
```
django.db.utils.OperationalError: (1091, "Can't DROP 'job_repository_id_project_specific_id_7883a5e8_uniq'; check that column/key exists")
```
We'll just drop the index by hand on dev/stage/prod instead.

Bug 1328985 - Make 0020_remove_project_specific_id a no-op

---

requirements/common.txt

To keep pyup.io quiet for now, since the upgrade will need to be performed manually.

Bug 1412792 - Add pyup ignore markers for graphene-django v2

---

requirements/common.txt

Since 1.4.2 has too strict requirements, so we can't use it either.
(See #3060)

Bug 1412792 - Update pyup ignore marker for graphene

---

package.json
ui/js/components/auth.js
yarn.lock

This reverts commit b37ef957a2282bcc7dd5d0d884df4b3c05718992.
There appears to be a bug with the webpack module resolution, such that Treeherder's upgraded Hawk 7 is being used by taskcluster-client, even though that has a separate dependency on Hawk 6, and so should be using its own copy of Hawk.
For now, let's roll back to Hawk 7 for Treeherder's direct dependency (used by the login flow), to work around this.

Bug 1426741 - Revert "Update hawk from v6.0.2 to v7.0.5 (#3049)"

---

requirements/common.txt

Since both packages need updating at once, along with upgrading Elasticsearch server and fixing the failures due to breaking changes.

Bug 1427598 - Add pyup ignore markers for elasticsearch(-dsl) 6

---

.yarnrc

Since otherwise it defaults to the tilde version ranges (eg `^1.2.3`), whereas we choose to use exact version numbers instead. This saves having to remember to pass `--exact` each time `yarn add` is used.

Make yarn default to saving non-tilde versions in package.json

---

neutrino-custom/production.js
package.json
tests/ui/unit/init.js
yarn.lock

https://reactjs.org/blog/2017/09/26/react-v16.0.html
https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html
Replaces #3048/#3068/#3069, since additional changes were required.
Also adjusts the Babili minification settings to work around a bug in the minification of ``react-dom (that will hopefully be fixed in newer versions of `babel-plugin-minify-mangle-names`, that we'll get as part of Neutrino upgrade):
https://github.com/babel/minify/tree/babel-preset-babili@0.0.11/packages/babel-preset-babili#options

Bug 1426902 - Upgrade to React 16

---

ui/js/controllers/jobs.js
ui/js/controllers/perf/dashboard.js
ui/js/directives/treeherder/clonejobs.js
ui/js/models/resultset.js
ui/js/services/buildapi.js

In my travels I noticed at least two unused dependencies in various controllers, so I thought I'd open a PR to remove them. I don't know if this is best practice or not or they should be left in for future hypothetical use. I defer to you guys.
I ran the unit tests locally and all 45 tests passed with these changes.

Remove unused dependencies thServiceDomain, thResultStatusObject

---

package.json
ui/js/controllers/perf/compare.js
ui/js/failureviewer.js
ui/js/logviewer.js
ui/js/models/repository.js
ui/js/models/resultsets_store.js
ui/js/perfapp.js
ui/js/services/buildapi.js
ui/js/services/classifications.js
ui/js/services/pinboard.js
ui/js/treeherder_app.js
yarn.lock

**1) Stop using deprecated $http callback methods**
Angular v1.4.4 deprecated `$http`'s `.success()` and `.error()` callbacks in favour of `.then()` and `.catch()`. The deprecated forms are finally removed in Angular 1.6, so we need to stop using them:
https://docs.angularjs.org/guide/migration#-http-
**2) Update from AngularJS 1.5 to 1.6**
...and fix the only other breaking change that affects us - the `hashPrefix` change - which we revert by manually setting it back to the empty string, so that existing URLs still work:
https://docs.angularjs.org/guide/migration#commit-aa077e8
For more details, see:
https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#160-rainbow-tsunami-2016-12-08
Closes #3044.

Bug 1364888 - Upgrade to AngularJS 1.6

---

ui/partials/main/jobs.html
ui/test-view/redux/configureStore.js
ui/test-view/redux/modules/groups.js
ui/test-view/ui/Test.js

Since the performance issue with GraphQL is limited to the bug suggestions, we don't need to disable the entire app.  The real fix, of course is to get all the queries to fall within our performance thresholds.
However, in the mean-time we can re-enable the main app and make the fetch of bug suggestions be on-demand.  When the user clicks a test, then it makes the call(s) for only that test.
If this approach isn't agree-able, we could entirely disable the calls to bug suggestions, but still let the users see the tests themselves.
This is the on-demand approach.

Bug 1409679 - On-demand bug suggestion fetch in test-view

---

ui/js/components/perf/compare.js
ui/js/perfapp.js

AngularJS 1.6 made bindings no longer be pre-assigned by default, which breaks Perfherder's compare view, since the controller relies on the bindings being present at initialisation. Until it is adjusted to use the new `$onInit()` method, the legacy mode has been re-enabled:
https://docs.angularjs.org/guide/migration#commit-bcd0d4

Bug 1428958 - Enable pre-assigning bindings mode for Perfherder

---

vagrant/.profile

The `tabname` and `thlogsdelete` functions were removed in #1995.

Remove references to previously removed .profile helper aliases

---

vagrant/setup.sh

Since Brotli now ships as a wheel, so doesn't need g++ to build.

Vagrant: Remove no longer needed g++ package

---

tests/selenium/test_select_unclassified_job.py

I was able to reproduce intermittent failures in these tests. This additional wait appear to make them solid. /cc @rbillings

Improve the stability of the test_select_unclassified_job tests

---

bin/travis-setup.sh
requirements/common.txt
tests/test_setup.py
treeherder/config/settings.py
treeherder/config/utils.py
treeherder/config/wsgi.py
vagrant/env.sh
vagrant/setup.sh

Since:
* Redis has additional features we need (eg for [bug 1409679](https://bugzilla.mozilla.org/show_bug.cgi?id=1409679))
* the Redis server, python client and Django backend are more actively maintained (so have persistent connections/pooling that actually works, which gives a big perf win)
* we can use Heroku's own Redis addon rather than relying on a third-party's (to hopefully prevent a repeat of the certificate expiration downtime)
Initial testing shows a 4x performance win (mostly from persistent connections now working):
Before this is merged, Heroku Redis instances will need to be created for stage/production (already done for prototype) - likely on plan `premium-3`:
https://elements.heroku.com/addons/heroku-redis
We'll also need to pick an eviction policy: …

Bug 1384518 - Switch from Memcached to Redis

---

ui/js/services/main.js
ui/plugins/controller.js
ui/plugins/job_details_pane.jsx
ui/plugins/pluginpanel.html

Presently, when the build system type of a job is buildbot, there is a hyperlink 
on the machine name that takes a user to the slave health
dashboard. When a job runs outside of buildbot, there is a worker
explorer. A worker explorer shows information like most recent task IDs
claimed. Also, a user can perform actions on the machine if they own the
required scopes (e.g., quarantine & terminate instance).
This pull-request provides a shortcut to the worker explorer when the build system
type is not buildbot.

Bug 1429230 - Add ability to terminate instances from treeherder

---

ui/plugins/pluginpanel.html

This hopefully fixes Bugzilla bug [1429922](https://bugzilla.mozilla.org/show_bug.cgi?id=1429922).
This returns the missing backfill menu tooltip to the dropdown menu entry. I think I have the presentation logic correct, based on past functionality.
Proposed (logged out):
Proposed (logged in):
I intentionally left the cursor as arrow rather than disabled, since that style blocks the view of the menu. I did the same in an unrelated PR https://github.com/mozilla/treeherder/pull/3077.
Release **57.0.4 (64-bit)**

Bug 1429922 - Return tooltip to backfill menu

---

ui/js/controllers/main.js

This is a trivial little check to avoid throwing an exception when you click the "filter" button on the toolbar.  It has no effect, but should be quieted.  Didn't seem worth a bug.  :)

Fix benign JS exception when filtering

---

ui/plugins/controller.js
ui/plugins/pinboard.js

Similar to the work in PR https://github.com/mozilla/treeherder/pull/3077, I knew there were some similar inline functions lying around, so let's ES6 them while we're at it.
Everything seems fine in the Pinboard and Backfill UI in local testing after the change.
Nightly **60.0a1 (2018-01-24) (64-bit)**

Update similar inline functions to bug 1401518 to es6

---

ui/js/directives/treeherder/clonejobs.js

Prior to #3154 the conditional used:
`_.includes(failResults, resultStatus)`
...so should now be using `!== -1` rather than `=== 1`.

Bug 1413156 - Fix inverted conditional in renderGroupJobsAndCounts

---

docs/admin.rst

Generated using the approach documented at the end of the page:
https://treeherder.readthedocs.io/admin.html#direct-database-access
The changes are required since bug 1373008 added the `group` and `group_failure_lines` tables and #2532 removed `text_log_summary` and `text_log_summary_line`.
Now that we're using MySQL 5.7, we can specify `REQUIRE SSL` on the `CREATE USER` statement, rather than having to do so on the individual GRANTs. Compare:
https://dev.mysql.com/doc/refman/5.6/en/create-user.html
https://dev.mysql.com/doc/refman/5.7/en/create-user.html
Prevents:
```
1 warning(s): 1287 Using GRANT statement to modify existing user's
properties other than privileges is deprecated and will be removed
in future release. Use ALTER USER statement for this operation.
```

Bug 1434307 - Docs: Update read-only replica GRANTs

---

ui/js/controllers/jobs.js
ui/partials/main/thActionButton.html

This hopefully fixes Buzilla bug [1401518](https://bugzilla.mozilla.org/show_bug.cgi?id=1401518).
I tried fixing this a better way, per my later thread comment:
> Thinking about this further, I think it would be even better if we disable the menu, change the menu tooltip to "No decision task available" and prevent the user from selecting the menu to begin with.
Case 1: Logged in, decision task available (the 'all is well' scenario):
Case 2: Not logged in, no decision task available
Case 3: Logged in, no decision task available (I believe @whimboo's test case)
Case 4: Not logged in, decision task available
Everything seems fine in local testing, but I defer to the expert users to try it out locally. I left the original sticky `thNotify` encountered in the bug in the code, in case it gets …

Bug 1401518 - Make Add new jobs menu require a decision task

---

tests/auth/test_backends.py
treeherder/auth/backends.py

Presently, when you login with google you are prompted with a screen
that tells you to login using a different provider. However, if you try to
login with google using a "@mozilla.com", then there is a
blank page saying Unrecognized identity.
This commit will allow a user to login with Google when he tries to login with a `mozilla.com` email.

Bug 1436943 - Login fails with "Unrecognized identity" when using Google authentication

---

Vagrantfile
vagrant/setup.sh

To pick up the newer kernel/security updates. Only takes effect when people destroy/recreate their VM, so also adds a `dist-upgrade` to upgrade existing boxes. (The older Bento box had a broken kernel config so `dist-upgrade` can't upgrade the kernel, but it's better than nothing.)
Also switches the Hyper-V provider to the Bento images for parity, since Bento now create Hyper-V variants too.
For available box versions, see:
https://app.vagrantup.com/bento/boxes/ubuntu-16.04
The `box` name cannot be factored out of the provider blocks due to:
https://github.com/hashicorp/vagrant/issues/9452

Bug 1428919 - Vagrant: Update to latest Bento image

---

ui/css/treeherder-global.css
ui/partials/main/thShortcutTable.html

This hopefully fixes Bugzilla bug [1434456](https://bugzilla.mozilla.org/show_bug.cgi?id=1434456).
This removes the unwanted scrollbar in the User Guide introduced by PR https://github.com/mozilla/treeherder/pull/3129 in bug [1430171](https://bugzilla.mozilla.org/show_bug.cgi?id=1430171).
User Guide before and after:
In this change we only target the parent `onscreen-shortcuts` id and traverse across the ng-include into the shortcut partial, targeting the same div element the prior change did. But this way, the User Guide, or any other use of the of the shortcut component will always be clean. Only the onscreen instance of it will have a scroll bar.
Release **58.0.1 (64-bit)**

Bug 1434456 - Remove scrollbar from shortcut table in userguide

---

ui/partials/main/thPinboardPanel.html
ui/plugins/pinboard.js

This hopefully fixes Bugzilla bug [1371843](https://bugzilla.mozilla.org/show_bug.cgi?id=1371843).
This changes the classification save drop down, such that when the user enters a bug number, or enters classification text, or modifies the classification drop down, the Save drop down is exposed, allowing the user to "Clear all" (effectively resetting the UI inputs).
Proposed:
Mildly tested on OSX 10.12.6:
Release **58.0.1 (64-bit)**

Bug 1371843 - Expose Clear all when the pinboard is dirty

---

treeherder/config/settings.py
treeherder/middleware.py

The old API (`MIDDLEWARE_CLASSES`) has been deprecated in favour of the `MIDDLEWARE` pref. The new API is faster (since it short-circuits) and has more sensible error handling characteristics:
https://github.com/django/deps/blob/master/final/0005-improved-middleware.rst
https://docs.djangoproject.com/en/1.11/topics/http/middleware/#upgrading-middleware
To make the switch a couple of other changes are required:
* adapting any middleware not already compatible with the new API
* adjusting the order of middleware, to take into account that short-circuiting (returning early) now works properly

Bug 1412797 - Switch to the Django 1.10+ new style middleware API

---

docs/pulseload.rst
treeherder/config/settings.py

This hopefully fixes Bugzilla bug [1429988](https://bugzilla.mozilla.org/show_bug.cgi?id=1429988).
This makes some minor updates, such that local pulse ingestion works out of the box, and the instructions and examples are a bit more clear.
I've tested the actual config changes this evening in the process of working on bug [1401518](https://bugzilla.mozilla.org/show_bug.cgi?id=1401518) and in collaboration with @camd on IRC.
Release **57.0.4 (64-bit)**

Bug 1429988 - Minor updates for local pulse ingestion

---

tests/webapp/api/test_jobs_api.py

Since bug 1177519 has long since landed. 
The test needed one small tweak to take into account bug 1233164.

Bug 1437317 - Don't skip test_jobs_api.py's test_job_error_lines

---

treeherder/model/models.py
treeherder/webapp/api/jobs.py

The remaining REST API job submitters are using `JobsViewSet.create` to transition jobs from one state to the next instead.
This makes the various `*STATES` constants unused. (I'd thought they were used for validation during ingestion, but I guess not. We at least have the jsonschema validation for pulse - i think that's enough for now?)

Bug 1437938 - Remove unused /jobs/update_state/ API

---

treeherder/webapp/api/refdata.py
treeherder/webapp/api/serializers.py
treeherder/webapp/api/urls.py

New Relic says zero requests to these in the last 7 days:
* BuildPlatformViewSet
* MachineViewSet
* ProductViewSet
...and these have only been accessed <= 2 times:
* JobGroupViewSet
* JobTypeViewSet
* MachinePlatformViewSet

Bug 1437968 - Remove unused refdata APIs

---

ui/js/auth/AuthService.js

I suspect multiple tabs are trying to renew at the same time, where one tab will throw an error hence logging users out.

Bug 1437824 - Stop logging out users if renewal fails

---

tests/ui/mock/resultset_list.json
tests/ui/unit/react/revisions.tests.jsx
tests/webapp/api/test_push_api.py
treeherder/webapp/api/push.py
treeherder/webapp/api/serializers.py

Since revision details are included in the response from the `/push/` API, so there's never any need to fetch them separately.
(And if anyone wants more than the first 20 commits, they should be using hg.mozilla.org's API instead.)

Bug 1438060 - Remove unused /push/revisions/ API

---

tests/selenium/pages/treeherder.py

There appears to be a moment between clicking the job and the result/details being populated. This fix means we don't return from the wait for the info panel to be displayed until the job result is populated.
I ran the tests/selenium/test_filter_jobs_by_failure_result.py::test_filter_jobs_by_failure_result[testfailed] 100 times without failure with this patch applied.

Bug 1438469 - Improve InfoPanel.is_open to include check for job result

---

docs/rest_api.rst
requirements/common.txt
treeherder/config/settings.py
treeherder/config/urls.py

Now that django-rest-framework supports interactive docs natively, we no longer need to use the additional django-rest-swagger package:
http://www.django-rest-framework.org/topics/3.6-announcement/#interactive-api-documentation
http://www.django-rest-framework.org/topics/documenting-your-api/
This significantly reduces the number of static files that have to be processed, reducing the time taken for `collectstatic` (which is run on every deployment and takes a while due to Brotli compression) by 70%.

Bug 1357476 - Replace django-rest-swagger with native d-r-f docs

---

tests/autoclassify/test_classify_failures.py
tests/webapp/api/test_bug_job_map_api.py
treeherder/model/migrations/0022_modify_bugscache_and_bugjobmap.py
treeherder/model/models.py
treeherder/webapp/api/serializers.py

Since unfortunately the migration failed on stage due to:
```
IntegrityError: (1452, 'Cannot add or update a child row: a foreign
key constraint fails (`treeherder`.`#sql-1c26_1936a5`, CONSTRAINT
`bug_job_map_bug_id_013db14b_fk_bugscache_id` FOREIGN KEY (`bug_id`)
REFERENCES `bugscache` (`id`))')
```
I believe this is due to the fact that bug numbers are sometimes manually entered when classifying failures (eg for infra failures), meaning that not every bug ID in `BugJobMap` is for an intermittent bug, and so doesn't exist in `Bugscache` (which is currently only populated with bugs that have the keyword `intermittent-failure`).
This wasn't caught on prototype, since whilst that has some failure classifications saved, none of them where hand-entered and so all existed in `Bugscache`, …

Revert BugJobMap foreign key part of 4db1aa4 (bug 1367362)

---

ui/js/constants.js

Once https://bugzilla.mozilla.org/show_bug.cgi?id=1439365 lands it will look like this: https://treeherder.mozilla.org/#/jobs?repo=try&revision=b1e1956ee2daa787cc623f09f7675e89c86987fc
It'd be nice to have a nice platform mapping for MinGW.

Add the Windows MinGW Platform to the Platform Mapping

---

ui/js/auth/LoginCallback.jsx

STR:
1. Navigate to `localhost:8000/login.html`
2. Login
Expected: User is redirected to `localhost:8000`
Actual: The spinner is shown
Reason: The user did not click the login button in the main page of treeherder. They navigated to the login route directly.

Redirect user to origin if user navigates to the login route directly

---

ui/job-view/JobButton.jsx
ui/job-view/JobGroup.jsx
ui/job-view/JobsAndGroups.jsx
ui/job-view/Platform.jsx
ui/job-view/PushJobs.jsx
ui/job-view/PushList.jsx

The problem here was that when a job was classified in "unclassified only" mode, then it disappeared.  When we had ``clonejobs.js`` it still existed, but was hidden.  In React, it's actually gone.  So we had no idea how to find the right NEXT job, and it just started at the beginning.  This change will keep a job visible in unclassified only mode as long as its selected.  As soon as you nav off the job, it disappears.
This had to pass a reference of each job's ``Platform`` as well as a callback function for filtering platforms so that when a job is set to no longer selected, we can check if it then disappears and the group or entire platform should be "disappeared."  Since this partially hinges off of whether the job is or WAS selected, we have to pass the ``selectedJobId`` around a bit …

Bug 1438555 - Fix Classifying a failure in the middle of the page breaks n/p navigation

---

ui/job-view/PushActionMenu.jsx

The links for set top and bottom of range weren't working
as links and the BuildAPI link was totally broken.
The ``data-ignore-job-clear-on-click`` directive from angular actually doesn't work here.  Luckily, it's also not needed.  So removing it.
The range changes used to be handled with an ``onClick`` but they should have just been links.  That way they work both in the same tab, and when you want to open a new tab that doesn't disturb the existing one.

Bug 1440516 - Fix Push action menu links

---

tests/ui/unit/init.js
ui/entry-index.js
ui/js/controllers/perf/compare.js
ui/js/controllers/tcjobactions.js
ui/js/filters.js
ui/js/models/resultset.js
ui/js/services/main.js
ui/js/services/tcactions.js
ui/plugins/controller.js

Since it's the cleaner way to declare dependencies and is another small step towards migrating away from AngularJS.

Bug 1440774 - Convert AngularJS dependency factories to ES6 imports

---

ui/job-view/PushHeader.jsx
ui/job-view/PushList.jsx
ui/js/models/resultsets_store.js
ui/js/providers.js

This fixes two bugs related to the ``PushHeader`` not updating.  The progress counter was only updating sometimes, and the link for the push that should have been getting the filters was never updating.  This fixes both.

Bug 1440473 - Fix push header progress and link live updating

---

docs/admin.rst

Bug 1428032 introduced the `issue_tracker` table, but production database users cannot view it. I updated the docs with the SQL config script used for granting the rights.

Bug 1428032 - Grant visibility for new issue_tracker table

---

ui/job-view/PushList.jsx

We should only try to set selected job from url (and thereby loading the details panel) on a page first load.  Otherwise, it reloads every time we fetch new jobs.

Bug 1441215 - Fix unwanted reload of detail panel

---

ui/js/services/pinboard.js
ui/plugins/failure_summary_panel.jsx

This was using an angular $timeout in the thPinboard service addBug
function.  That caused the value to not be persisted.  Moved the $timeout
to the ReactJS failure_summary_panel since that's where it's needed.

Bug 1438410 - Fix filing with bugfiler from Failure Summary tab

---

docs/submitting_data.rst
tests/ui/unit/filters.tests.js
ui/job-view/PushActionMenu.jsx
ui/job-view/PushHeader.jsx
ui/job-view/PushLoadErrors.jsx
ui/job-view/RevisionList.jsx
ui/js/components/auth.js
ui/js/filters.js
ui/logviewer.html
ui/partials/main/intermittent.html
ui/partials/main/thGlobalTopNavPanel.html
ui/partials/main/thHelpMenu.html
ui/partials/main/thInfraMenu.html
ui/partials/main/thRelatedBugQueued.html
ui/partials/main/thWatchedRepoInfoDropDown.html
ui/partials/perf/alertsctrl.html
ui/partials/perf/graphsctrl.html
ui/partials/perf/helpMenu.html
ui/plugins/annotations_panel.jsx
ui/plugins/auto_classification/errorLine.html
ui/plugins/auto_classification/option.html
ui/plugins/auto_classification/staticOption.html
ui/plugins/failure_summary_panel.jsx
ui/plugins/job_details/main.html
ui/plugins/job_details_pane.jsx
ui/plugins/perf_details/main.html
ui/plugins/pluginpanel.html
ui/plugins/similar_jobs/main.html
ui/test-view/ui/LogViewer.jsx
ui/test-view/ui/Test.jsx

This helps prevent:
https://www.owasp.org/index.php/Reverse_Tabnabbing
We're not also using `noreferrer`, since most browsers now support `noopener` (https://caniuse.com/#search=noopener) and the link targets are all Mozilla properties where the referrer may be useful.
The auth.js `window.open()` has not been changed, since the login callback makes use of `window.opener`.

Bug 1441493 - Use rel="noopener" for all target != null links

---

ui/job-view/PushActionMenu.jsx
ui/job-view/PushHeader.jsx
ui/plugins/controller.js

The third argument was changed from a bool to an options object in bug 1402062 - so these instances would fail with:
`Error: Must pass an object as last argument to thNotify.send!`

Bug 1441851 - Fix thNotify calls using old-style sticky argument

---

ui/plugins/failure_summary_panel.jsx

The failure classification pin button was broken for bug suggestions that fell under the "all others" category, since the `BugListItem` for them weren't passed the `$timeout` prop, unlike for the "open recent" `BugListItem` instance.

Bug 1443023 - Pass missing $timeout prop to BugListItem

---

ui/job-view/JobButton.jsx
ui/job-view/JobGroup.jsx
ui/job-view/JobsAndGroups.jsx
ui/job-view/Platform.jsx
ui/job-view/PushJobs.jsx
ui/js/constants.js

These refs were not actually used, so can be removed.  It does appear to
improve rendering speed, especially when changin filtering.  I had noticed
that the JobGroup was re-rendering more times than it should, and this
change stops that.  I believe more work is to be done here, but this is one
step.
This also includes a couple other small tweaks that may help speed.

Bug 1442556 - Improve rendering speed in treeherder by removing refs

---

ui/js/treeherder_app.js

So we remember to remove them once unused.

Annotate third-party module usage in the treeherder.app module

---

ui/js/components/perf/compare.js
ui/js/controllers/perf/compare.js
ui/js/controllers/perf/dashboard.js
ui/js/perfapp.js
ui/partials/perf/comparetable.html

Basically I searched for 'showOnlyConfident' and cargo-culted that code everywhere.  I ran it with `yarn start` and it seems to work fine for me.

Bug 1443331 - Add a checkbox to hide results that don't have data for both the old and new revisions

---

ui/js/logviewer.js
ui/js/perfapp.js
ui/js/treeherder_app.js
ui/js/userguide.js

Since we don't use them, and disabling improves compile performance:
https://docs.angularjs.org/guide/production#disable-comment-and-css-class-directives

Bug 1443832 - Disable compilation of class and comment directives

---

tests/ui/mock/mappedGroup.json
tests/ui/mock/mappedGroupDups.json
ui/job-view/JobGroup.jsx
ui/job-view/JobsAndGroups.jsx
ui/js/models/resultsets_store.js

I went ahead and optimized the deconstruction, too.  Since this function is called a lot, every bit helps for speed.  :)

Bug 1443667 - Fix 'tier' not yet assigned when getJobGroupInfo() creates map

---

neutrino-custom/lint.js
ui/details-panel/AnnotationsTab.jsx
ui/job-view/RevisionList.jsx
ui/plugins/failure_summary_panel.jsx
ui/test-view/redux/modules/groups.js
ui/test-view/ui/Groups.jsx
ui/test-view/ui/Test.jsx

In some of these cases there wasn't an ``id`` I could use, so I had to use a field that WILL be unique.  Sometimes that's the revision hash, or sometimes it's just the text that's displayed.

Bug 1437818 - Enable ESLint rule react/no-array-index-key

---

ui/js/models/repository.js
ui/js/services/treestatus.js

TreeStatus has long since moved to:
https://mozilla-releng.net/treestatus

Bug 1353753 - Update legacy Treestatus URLs

---

neutrino-custom/base.js
package.json
ui/entry-index.js
ui/entry-logviewer.js
ui/entry-perf.js
ui/entry-userguide.js
yarn.lock

Notably:
* the `popper.js` `DefinePlugin` entry is no longer required
* the JS/CSS imports have been adjusted to match the install docs:
https://getbootstrap.com/docs/4.0/getting-started/webpack/
...which shaves 23KB off the bundle size of most pages (due to the use of the minified CSS).
Release announcements:
https://blog.getbootstrap.com/2017/12/28/bootstrap-4-beta-3/
https://blog.getbootstrap.com/2018/01/18/bootstrap-4/
Release notes:
https://github.com/twbs/bootstrap/releases/tag/v4.0.0-beta.3
https://github.com/twbs/bootstrap/releases/tag/v4.0.0
Changelog:
https://github.com/twbs/bootstrap/compare/v4.0.0-beta.3...v4.0.0
Closes #3079.

Bug 1444644 - Update Bootstrap from v4.0.0-beta.2 to v4.0.0

---

tests/jenkins/requirements.txt

Full ad-hoc log here (with 5 failures, while the next ad-hoc from master, had 6, so this should be fine): https://gist.github.com/stephendonner/d9adb8a0c9fd8c4b8466f482bc330fc9
@edmorley r?

Bump pytest to latest, 3.4.2

---

ui/job-view/Revision.jsx

The escaping is not necessary because the attribute gets safely with JavaScript.

Bug 1444931 - Fix escaped characters in commit message tooltips

---

tests/auth/test_backends.py
tests/webapp/api/test_auth.py
treeherder/config/settings.py

The cache-based engine stores session data in our Redis cache rather
than in the `django_sessions` table in the MySQL database.
This has several advantages:
* faster access (session lookups occur for virtually all API requests)
* expired sessions are automatically cleaned up (the database engine
requires that the `clearsessions` command be run periodically)
* fewer secrets being stored in the database and its backups
See:
https://docs.djangoproject.com/en/1.11/topics/http/sessions/#configuring-sessions
https://docs.djangoproject.com/en/1.11/ref/settings/#session-engine
We're not concerned about very occasional session loss, so don't need
the persistence guarantees of the related `cached_db` engine.
The `INSTALLED_APPS` entry is being removed since it's only purpose
is to load the session …

Bug 1310241 - Switch to the cache-based Django session engine

---

ui/job-view/PushList.jsx
ui/js/controllers/main.js
ui/js/models/repository.js
ui/js/models/resultsets_store.js
ui/js/services/jobfilters.js
ui/plugins/pinboard.js

Bug1413156 - lodash to ES6: replace _.without _.values _.last usage

Bug1413156 - lodash to ES6: replace _.without _.values _.last usage

---

.travis.yml
lints/queuelint.py
tests/etl/test_perf_schema.py
tests/etl/test_text.py
tests/log_parser/test_tasks.py
tests/model/test_bugscache.py
tests/model/test_error_summary.py
tests/webapp/api/test_bugzilla.py
tests/webapp/api/test_job_details_api.py
treeherder/etl/artifact.py
treeherder/etl/jobs.py
treeherder/etl/perf.py
treeherder/etl/text.py
treeherder/perf/management/commands/test_analyze_perf.py
treeherder/perfalert/perfalert/__init__.py

Fixes all flake8 errors when running under Python 3[.6.4].
I added tests and pulled apart the lambda in `astra_filter` so I could ensure any changes I made to the regex wouldn't break things.

Bug 1428045 - Fix flake8 errors on Python 3

---

ui/helpers/urlHelper.js
ui/intermittent-failures/BugDetailsView.jsx

change jobsUrl to include job_id for revision link in bug details view table

Bug 1445295 - intermittent failures fix

---

requirements/common.txt

The PyPI API now returns package download URLs in a different order than before, causing errors in cases where not all hashes were listed and there were multiple matching candidates (such as both `.zip` and `.tar.gz` versions of the sdist archives).
See:
https://github.com/pypa/pypi-legacy/issues/790
This adds the hashes for the alternate package variants to fix the errors when pip installing from a clean environment.

Bug 1450971 - Fix package hash errors after PyPI API change

---

ui/css/treeherder-navbar-panels.css
ui/entry-index.js
ui/js/controllers/main.js
ui/js/controllers/settings.js
ui/partials/main/thGlobalTopNavPanel.html
ui/partials/main/thSettingsPanel.html

Since it's hidden and has never been used.
The `thSettingsPanel.html` partial is a leftover from when this feature was first added in 3e625f3 / 6b0c56e.

Bug 1451428 - Remove unused settings panel

---

ui/plugins/failure_summary/main.html

This has to do with my usage of ``ng-react``.  It didn't notice the job had changed in scope in angular, so it left the failure summary tab the same, which would pin the previous job.  This watches the "reference" of the job which will re-render when the job changes in ``scope``.

Bug 1450972 - Fix pin wrong job from failure summary tab

---

ui/partials/main/login.html
ui/plugins/auto_classification/errorActions.html

The `login.html` partial is a leftover from the switch to Auth0 in bug 1395356, and `errorActions.html` appears to have never been used since it landed in 8e56de8 (bug 1321798).

Bug 1451457 - Removed unused partials

---

ui/js/services/jobfilters.js

I found two uses of _.forEach which could be replaced by ES6 features.

Bug 1413156 - Remove lodash .forEach() usage for objects

---

treeherder/perf/management/commands/import_perf_data.py

Since `.format()` doesn't support `%s`. 
Found by the eslint `too-many-format-args` rule.

Bug 1452220 - Fix import_perf_data exception string formatting

---

treeherder/etl/runnable_jobs.py

Previously all created/updated `RunnableJobs` entries were using the `job_group` default of `2`, rather than the actual job group ID.
Not bothering to add a test since `RunnableJobs` will be going away once buildbot supported is removed.

Bug 1452213 - Correctly set RunnableJobs group

---

.travis.yml

This merges the three separate non-selenium Python test jobs into one, reducing the overall job count from 7 to 5. This helps avoid hitting Travis concurrency limits, that delay starting the selenium job (which is the long pole for the end to end time).
Before:
https://travis-ci.org/mozilla/treeherder/builds/364253318
After:
https://travis-ci.org/mozilla/treeherder/builds/364554939

Bug 1452904 - Rebalance the Travis test chunks

---

ui/js/controllers/main.js
ui/partials/main/thShortcutTable.html
ui/plugins/auto_classification/controller.js

This wasn't super urgent, but it was also scratching my own itch, so I went ahead and did it.  :)
The ``i`` shortcut was getting overridden by the same key for the autoclassify panel because it was listed twice.  This makes the autoclassify one need a ``ctrl``.
This also tries to clean up the keyboard shortcuts and alphabetize them so we don't introduce conflicts.  
An additional small thing to allow multi-select on mac in the autoclassify panel (already worked on windows) is so I can do A/B testing easier against the ReactJS version.

Bug 1352862 - Restore the 'i' keyboard shortcut to toggle in-progress jobs

---

treeherder/perf/management/commands/test_analyze_perf.py

Prevents the `ImportError` after the rename in #2284.

Bug 1452306 - Fix test_analyze_perf command

---

setup.cfg
tests/selenium/pages/perfherder.py
tests/selenium/pages/treeherder.py

Fixes:
`pypom/view.py:21: DeprecationWarning: use driver instead`

Bug 1389517 - Remove usages of deprecated pypom .selenium property

---

.travis.yml
bin/travis-setup.sh
setup.cfg
tests/webapp/api/test_bug_job_map_api.py

This enables `DeprecationWarnings` for things that Python 2 knows are not compatible with Python 3. The `error` entry in the pytest `filterwarnings` setting ensures these will be surfaced as exceptions and so result in test failures.
See:
https://docs.python.org/2/using/cmdline.html#cmdoption-3
The removal of `sorted()` from `test_bug_job_map_api.py` is to fix:
`DeprecationWarning: dict inequality comparisons not supported in 3.x`

Bug 1453850 - Enable Python 2's `-3` mode on Travis

---

ui/css/treeherder-navbar.css
ui/js/components/auth.js
ui/partials/main/thGlobalTopNavPanel.html
ui/perf.html

This hopefully fixes Bugzilla bug [1454075](https://bugzilla.mozilla.org/show_bug.cgi?id=1454075).
A tiny nit that nobody really sees except developers. This improves the Login button a little when the user is running the standalone yarn server and not vagrant. The old login text was oversized and the button had no padding. I stared at it for months and eventually did something about it.
Current:
Proposed:
At the same time, there's a `btn-right-navbar` class that was apparently made redundant during the React work. So let's remove that at the same time.
Nightly **61.0a1 (2018-04-12) (64-bit)**

Bug 1454075 - Clean up login button and remove dead class

---

ui/partials/main/thGlobalTopNavPanel.html
ui/partials/main/thRepoMenuItem.html

This may fix Bugzilla bug [1405666](https://bugzilla.mozilla.org/show_bug.cgi?id=1405666).
A bit of a speculative PR based on the description and workflow in the bug, but this enables the ability to issue mousetrap shortcuts when any main navbar checkbox input has focus.
Proposed (checkbox focus, navigated via `>` key to "next job"):
It seems to work as expected on Nightly and Chrome.
Nightly **61.0a1 (2018-04-13) (64-bit)**
Chrome Release **65.0.3325.181 (64-bit)**

Bug 1405666 - Enable mousetrap shortcuts inside checkboxes

---

tests/selenium/pages/perfherder.py
tests/selenium/pages/treeherder.py

This allows any PyPOM plugins that implement the `pypom_after_wait_for_page_to_load` hook. See http://pypom.readthedocs.io/en/latest/plugins.html for more details.

Use loaded property in pages instead of overriding wait_for_page_to_load

---

treeherder/config/settings.py

This removes the DEBUG conditional for our `LOGGING` setting and merges the two definitions.

Bug 1318021 - Merge debug logging config into main LOGGING setting

---

Vagrantfile
bin/travis-setup.sh
requirements/common.txt
treeherder/autoclassify/matchers.py
treeherder/services/elasticsearch/mapping.py
vagrant/setup.sh

This upgrades Elasticsearch to 6.2.4, fixing the index mapping and search query to work with the later version.

Bug 1427598 - Upgrade Elasticsearch to 6.2.4

---

schemas/pulse-job.yml

Hi guys,
The motivation for this minor `title` cleanup is to aid [downstream code generation](https://godoc.org/github.com/taskcluster/taskcluster-client-go/tctreeherderevents).
There are no structural changes, just updates to titles to improve the type names that get generated, and perhaps improve clarity in the schema.
Thanks!

Cleaned up titles in pulse-job.yml to aid downstream client generation

---

treeherder/model/management/commands/es_import_failure_lines.py

This got missed when I switched us from `pyelasticsearch` to `elasticsearch`.

Fix Elasticsearch Index Existence Check

---

requirements/common.txt
treeherder/config/settings.py
treeherder/config/utils.py

[Furl](https://github.com/gruns/furl) is a great little library for handling URL manipulation.  I find it greatly simplifies urlparse code into a much more pythonic structure.
This PR is a precursor to some Elasticsearch work that I'd like to use furl for too.

Convert Redis URL to stunnel variant with furl

---

ui/js/controllers/logviewer.js
ui/logviewer.html

Reverts the accidental change to the raw log URL from here:
https://github.com/mozilla/treeherder/commit/5d237353598a531337fc91c6e09a32a03d9b457a#diff-4f14c25b423d5c12f4983b7229fedeb1L165
And updates the reftest URL handling to take into account:
https://github.com/mozilla/treeherder/commit/5d237353598a531337fc91c6e09a32a03d9b457a#diff-189002a90173e09fe81da88161e6e80dL63

Bug 1457917 - Fix the display of logs in the log viewer

---

treeherder/autoclassify/management/commands/es_benchmark.py
treeherder/autoclassify/matchers.py

Currently we do that after every search and after looking at the data in NR it seems we _rarely_ get a single result back, so the graph produced is actually tracking "the search did not error" giving us this graph:
([Live view](https://insights.newrelic.com/accounts/677903/explorer/events?eventType=es_matches&duration=1800000))
Instead we should start with tracking searches that return at least one result so we can effectively see changes when changing the search params.
This sets events to only be sent (to logs and NR) when we get results from Elasticsearch.

Only Send Events When ES Returns 1+ Results

---

treeherder/model/fixtures/repository.json

This disables:
* autopush
* bmo-development
* bmo-master
* bmo-upstream-merge
* bugzilla-4_4
* bugzilla-5_0
* bugzilla-master
* cedar
* comm-aurora
* cypress
* example-addon
* graphics

Bug 1458184 - Disable unused repositories

---

tests/seta/conftest.py
treeherder/config/settings.py
treeherder/seta/update_job_priority.py

I don't quite understand where this is used, so I'm not sure when this should land.
The old indexes still work, and will stick around for some time for backwards compatibility. The corresponding m-c changes have landed on all trunk and release branches, but haven't actively merged them to any project branches.

[RFC] Bug 1455448: Update treeherder to use new index for decision tasks.

---

ui/details-panel/autoclassify/StaticLineOption.jsx
ui/plugins/auto_classification/main.html
ui/plugins/perf_details/main.html

The ``onClick`` function was getting executed because it was a command rather than  a function which would initiate the command.
I also added more complete disabling for this and the perf tab in the case that it's not being used.  This prevents their code getting executed in the background when they are irrelevant.

Bug 1458633 - Fix bug wrongly added to list of bugs for classification

---

ui/js/models/resultsets_store.js

This should ONLY have applied to tier-2 groups that didn't have a group symbol.  So just had to add the other check.

Bug 1458922 - Fix tier 2 tasks not displaying group symbols

---

ui/job-view/PushActionMenu.jsx

These urls were only updated on page-load or state-change.  But we weren't watching for the changes, so never updated them.

Bug 1454182 - Fix preserving filters when setting 'set as bottom of range

---

requirements/common.txt
tests/autoclassify/test_matchers.py
tests/utils/test_queryset.py
treeherder/autoclassify/matchers.py
treeherder/utils/queryset.py

This replaces the `id_window` decorator with some composable functions and aims to extract the core functionality from id_window making them reusable.
Along the way I also documented everything in `matchers.py`, using the `pep257` tool to see what it was like (pretty good!) and added another QuerySet chunking function that works in the opposite direction.

Remove id_window Decorator

---

.travis.yml
package.json
vagrant/setup.sh

Node.js 10 is the new LTS:
https://github.com/nodejs/Release#release-schedule
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.1.0
This updates Vagrant, Travis and Heroku (the latter uses the version from `package.json`) from Node 8.
`yarn build` times on Travis are now 15% faster (189s -> 161s, using best of 3 runs of each).

Bug 1460218 - Update to Node 10

---

treeherder/model/models.py

This adds a custom NewRelic event to track when a user classified a failure that we had already picked up via auto-classification.
I added the change to `create_autoclassify_job_note` as I thought it would need to be further changed for this to pass in a matcher name/instance.  It turned out to not be necessary but the change is a nice simplification either way.

Add Classification Efficacy Metrics

---

docs/installation.rst
docs/troubleshooting.rst
vagrant/setup.sh

The `--provision` flag is unnecessary for new instances, since Vagrant runs `provision` as part of the initial `up` regardless. However by including `--provision` in the suggested command, it will mean returning contributors will re-run provision when they re-use the same steps.
An alternative approach would be to mark the provision block in `Vagrantfile` as `run: "always"`, however that would slow down the `vagrant up` of core developers too (by 40s), with no way to opt-out.

Bug 1420941 - Docs: Encourage users to run Vagrant provision

---

treeherder/log_parser/parsers.py

I'd like to make tsan tier1, but the current Failure Summary for them is kind of bad. One thing that would help is recognizing the SUMMARY: line as with {Address,Leak}Sanitizer.

Bug 1291954 - Highlight tsan errors

---

package.json
yarn.lock

Since `enzyme-adapter-react-16` now has it as a dependency rather than a peer dependency:
http://airbnb.io/enzyme/docs/installation/#working-with-react-16

Bug 1462267 - Remove unnecessary react-test-renderer dependency

---

tests/model/test_classified_failure.py
treeherder/autoclassify/autoclassify.py
treeherder/model/models.py

This simplifies how we save matched failures to the DB.  It specifically tries to improve the readability of `update_db` which was doing a few things before.
I took a stab at this once I realised I was really struggling to pick apart what the variables held at various places.

Simplify Auto-Classification Saving

---

ui/plugins/controller.js

This was changed from `_.findIndex()` to `Array.prototype.findIndex()` in #3537, however was using the former's `_.matches()` shorthand style, which isn't supported by the ES6 equivalent.
https://lodash.com/docs#findIndex
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

Bug 1462625 - Fix TypeError when selecting buildbot jobs

---

ui/js/components/perf/compare.js
ui/js/perfapp.js

AngularJS 1.6 changed the way controller bindings were initialised, but allowed users to revert to the previous behaviour by setting `preAssignBindingsEnabled(true)`.
As part of our upgrade from AngularJS 1.5 to 1.6, we set that pref in Perfherder, to fix the bug 1428958 regression.
However AngularJS 1.7 has now removed the pref, so we need to actually fix the root cause - by moving any controller logic that is dependant on the bindings into the `.$onInit()` method, which is only called after all of the bindings are guaranteed to exist.
See:
https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$compile
Testing this locally shows the regression in bug 1428958 no longer occurs, and as far as I can tell all other functionality in Perfherder works fine (and there are no new …

Bug 1463079 - Remove the preAssignBindingsEnabled workaround

---

package.json
ui/plugins/controller.js
yarn.lock

Changelog:
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#170-nonexistent-physiology-2018-05-11
`PluginCtrl` has been updated to correctly cancel the `$http` requests made by `selectJob`, since previously they were silently failing to be cancelled, whereas under AngularJS 1.7 an exception is raised if `$timeout` is used incorrectly:
https://code.angularjs.org/snapshot/docs/guide/migration#-timeout-
The usage of `$timeout` has been removed in favour of this pattern:
https://odetocode.com/blogs/scott/archive/2014/04/24/canceling-http-requests-in-angularjs.aspx
Closes #3542.

Bug 1463079 - Update to AngularJS 1.7

---

treeherder/model/models.py

This removes the check for already auto-classified notes since we've not had metrics come through to the insights panel at all yet which makes me think the check is too restrictive.

Record metrics when a user verifies

---

ui/partials/perf/graphsctrl.html

Apparently angular wasn't so happy about the event being bound to
"ng-click", but "ng-change" (which is what's recommended by the
angular documentation) works fine.

Bug 1463079 - Fix hiding series in perfherder graphs view

---

neutrino-custom/base.js
package.json
yarn.lock

Neutrino 4 removes the webpack default module resolution of looking in a relative `node_modules` directory (and then the parent of that directory, and so on), in favour of hardcoding the repo root's `node_modules` and those of the Neutrino preset directories.
This is both unnecessary and causes incorrect module resolution, which has bitten us multiple times.
In addition to fixing the failures being seen during Heroku builds, this change means we can also remove the not-directly-used dependency on `hawk`, which we'd had to leave in to work around:
https://github.com/mozilla/treeherder/pull/3144#discussion_r164726521

Bug 1465041 - Restore default webpack module resolution config

---

treeherder/autoclassify/matchers.py

This is a pretty simple change!  I'm hoping to try and start gathering some more specific metrics on how the matchers are working in production in preparation of improving verification of their results.  This change probably isn't strictly necessary for that goal but I want to have some idea of the efficiency of each matcher as we tweak them to avoid potential perf regressions.

Trace Matcher Execution Time

---

treeherder/perf/fixtures/performance_framework.json

These are two new performance frameworks currently under development.
For now these tasks will be unsheriffed until they are more stable,
though we still want to get a feel for the data they produce.

Bug 1464840 - Add 'raptor' and 'js-bench' to perfherder_frameworks.json

---

ui/js/controllers/filters.js

Somehow the add/remove filter got reversed, so this fixes that part.
There is one edge-case where if you uncheck both classified and unclassified, it defaults back to BOTH being shown.  This was intentional as it's useless to hide both unclassified and classified.  Then no jobs whatsoever will show.
However, when you uncheck both, then it SHOULD pop back to checking both.  But due to a quirk in angular with the click event, it will set the filters to show both, but the last checkbox will show unclicked.  I could work-around this with some conditional usage of ``preventDefault``, but I don't think it's worth it.  When this converts to React, that problem will be moot, since it's use of ``state`` will manage that better.

Bug 1464273 - Fix classified/unclassified in Filters menu

---

tests/autoclassify/test_classify_failures.py
tests/conftest.py
tests/model/test_classified_failure.py
tests/webapp/api/test_failureline.py
tests/webapp/api/test_jobs_api.py
tests/webapp/api/test_text_log_error.py
treeherder/model/models.py
treeherder/webapp/api/failureline.py
treeherder/webapp/api/jobs.py
treeherder/webapp/api/serializers.py

This consolidates the `FailureMatch` and `TextLogErrorMatch` models, giving us one source of truth for matches.  It also simplifies the creation of matches and setting classifications, removing a nice chunk of essentially duplicate code!

Consolidate *Match Models

---

tests/autoclassify/test_classify_failures.py
tests/autoclassify/test_matchers.py
treeherder/autoclassify/autoclassify.py
treeherder/autoclassify/matchers.py

⚠️ ~**Blocked by #3592**~  ⚠️ 
This replaces our use of the `Match` named tuple and other tuples for passing data around when matching with unsaved `TextLogErrorMatch` instances.  It allows us to avoid tracking unmatched errors until the end of matching where we can do a set operation on the in-memory objects.
Unfortunately the changes [listed below] are all intertwined since I couldn't come up with a nice way to split the commits up.
A general overview of considered-nice changes:
* No more mutating the `unmatched_errors` list inside child functions
* All functionality removed from the Matcher parent class
* Pass one TextLogError to a matcher at a time instead of looping the matchers once and passing all errors to each one
This set of changes paves the way for pulling the scoring of …

Use TextLogErrorMatch Instances

---

ui/js/controllers/main.js

Since ESR52 support for Treeherder is wontfix, and this way users won't waste time trying to figure out why it isn't working.
Example:
(This warning will display "Firefox ESR52 not supported" for other browsers based on ESR52 but that aren't called Firefox, but using the correct wording in those scenarios is an edge case really not worth handling.)

Bug 1467545 - Display a warning when accessing Treeherder with ESR52

---

package.json
renovate.json
yarn.lock

These were previously being pulled in implicitly via sub-dependencies.
They are also added to the Renovate ignore list, since the old version of Neutrino we're using is designed to work with specific versions, and so we can't update to the newer versions until we're on latest Neutrino.

Bug 1468573 - Fix missing peer dependency warnings

---

ui/js/models/resultsets_store.js

Unfortunately I didn't notice that commit e40793192110f53bb5ecb94cb81c81c0a0a986b2 broke updating.
This was due to there being an unnecessary _.flatten which got converted to a reduce.  Just removing the line fixes updating.

Fix job updating

---

.eslintrc.js
.gitignore
package.json

Enabling the ESLint caching reduces `yarn lint` time by 60%. 
See:
https://eslint.org/docs/user-guide/command-line-interface#caching
This also adds JS files in the repo root to the list of files that are linted, and fixes a subsequent lint error in `.eslintrc.js`.

Bug 1468650 - Use caching with ESLint & lint more files

---

ui/intermittent-failures/BugDetailsView.jsx
ui/intermittent-failures/BugLogColumn.jsx

Tested as follows:
1) from the main IFV route - click on a bug (shows expected graph and table)
2) from a url of bugdetails view with a valid bug number (shows expected graph and table)
3) from a url of bugdetails view with an invalid bug number (shows the messaged added from this pr)

Fix a bug in bugdetails route that breaks page with invalid bug number

---

ui/job-view/details/summary/ActionBar.jsx

These calls are needed to tell Angular to show that notify box.
I'm actually going to convert the notifications to React next, so this will become moot soon.  But wanted to fix this for folks hitting the bug for now.

Bug 1467204 - Fix Cancel Job button not showing success notification

---

ui/job-view/JobView.jsx
ui/job-view/details/DetailsPanel.jsx

This was due to ``currentRepo`` not getting passed to the DetailsPanel, and it fell back
to the default value every time.  Also cleaned up a few props to make them required
without defaults.

Bug 1450022 - Fix backfilling unavailable

---

ui/js/directives/treeherder/main.js

Its last usage was in `ui/partials/main/thPinboardPanel.html`.
(I ran the script from bug 1441164 for the first time since then - this was the only unused thing found)

Bug 1450022 - Remove unused focusMe directive

---

ui/js/controllers/perf/graphs.js

This reverts the changes made to `ui/js/controllers/perf/graphs.js` in #3632 (bug 1467435) in order to fix:
`TypeError: seriesData[series.signature] is undefined`

Bug 1470453 - Revert controllers/perf/graphs.js _.map() removal

---

ui/job-view/details/summary/ActionBar.jsx

Previously the log URL object was being passed instead of the URL, causing the generated URL to contain `logurl=[object Object]`.

Bug 1470509 - Fix action bar links to reftest analyser

---

treeherder/model/models.py

This covers two separate but related changes:
* Fix the specific error case for the Job linked [in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1469777#c2)
* Catch the general error cases where the DB returns an error due to FTS syntax errors.
Note: I caught the error cases with `Exception` as using `ProgrammingError` and parsing out specific DB error codes felt too brittle given the log output is the useful part.

Bug 1469777 - Sanitise and Catch Bugs Cache FTS Errors

---

ui/js/models/perf/alerts.js

Since the functions reference `this`, and switching to the ES6 arrow function form changes the way `this` is bound, which caused the perf alert buttons to no longer appear.
Partially reverts dcc0c4a529e6216c4a7631b9c1c332c57c62cb7e (#3646).

Bug 1470554 - Revert ES6 arrow changes from bug 1468107

---

ui/job-view/details/DetailsPanel.jsx

I was treating ``pinnnedJobs`` as an array, but it's an object, so it doesn't have the ``includes`` function.  I was also passing the whole ``job`` to the ``unPinJob`` function when that function only takes the ``id``.  I considered making that function take the whole ``job`` to be consistent with ``pinJob``.  But then I felt that it's best to keep it as-is and pass as little information into the function as it needs to do its operation.
Tests:
* cmd+click on a job to pin and un-pin it.
* click ``x`` on pinned job to un-pin
* space-bar to pin
* filtering jobs to a small sub-set, clicking "pin all shown jobs" and then cmd+clicking to unpin some of them
* several combinations of these actions

Bug 1470506 - Fix ctrl+click to toggle pin job

---

treeherder/model/models.py

This fixes the calls to `record_exception` incorrectly added in #3703

Bug 1469777 - Fix call to NewRelic's record_exception method

---

ui/job-view/details/PinBoard.jsx

This fixes a secondary bug found by Andreea Pavel when you paste a SHA for a job after you've classified another job as intermittent.
Ends up I had some cruft in there from the Angular days.  Saving a ``classification`` in the state was wrong.  We store the values for it (id and comment) in the state, then create a ``classification`` object based on those values for ``POST``ing back to the API during ``save``.

Bug 1470532 - Fix fixed by commit after intermittent

---

ui/js/services/tcactions.js

The action spec[*] requires that this property be set, but allows it to be
null.
[*] https://docs.taskcluster.net/docs/manual/using/actions/spec#json-e-context
/cc @helfi92 @imbstack

Always pass taskId (possibly null) in action context

---

requirements/common.txt

This reverts commit 3ca4df665737e121214c5d57e7ace5bd383fd847 since the new version of pyyaml has been unpublished, causing:
https://travis-ci.org/mozilla/treeherder/jobs/398044815#L583

Revert "Update pyyaml from 3.12 to 4.1 (#3719)"

---

ui/job-view/details/summary/SummaryPanel.jsx

Previously the URL was being set to the empty string, rather than:
`https://tools.taskcluster.net/provisioners/...`

Bug 1472204 - Fix generation of job machine URL

---

ui/js/controllers/perf/compare.js

If we chain only to the return value of a promise, we miss the digest
cycle implicitly triggered by calling angular's $http or $q.

 Bug 1470600 - Explicitly call digest when displaying results in compare view

---

tests/autoclassify/test_classify_failures.py
tests/conftest.py
tests/etl/test_buildapi.py
tests/etl/test_runnable_jobs.py
tests/settings.py
tests/webapp/api/test_failureline.py
tests/webapp/api/test_text_log_error.py
treeherder/config/settings.py
treeherder/etl/buildapi.py
treeherder/etl/common.py
treeherder/etl/push_loader.py
treeherder/etl/runnable_jobs.py
treeherder/log_parser/tasks.py
treeherder/model/error_summary.py
treeherder/model/management/commands/cycle_data.py
treeherder/model/models.py
treeherder/webapp/api/utils.py
vagrant/env.sh

This organises our core settings into three groups: Django, Third Party, & Treeherder (project level).  Internally to the latter two the settings have been grouped into either App or related sections in alphabetical order (to aid scanning the file).  Any settings only used in one place have also been moved to the respective usage site.

Bug 1469561 - Reshape Settings

---

tests/model/test_bugscache.py
treeherder/model/models.py

This fixes the incorrect usage or `re.sub` introduced in #3727 and adds a test to ensure our FTS search queries aren't empty strings.

Bug 1469777 - Fix FTS search query sanitising

---

setup.cfg

Since the pytest-django update in #3672 included the fix for:
https://github.com/pytest-dev/pytest-django/issues/596

Remove fixed deprecation warning from filterwarnings

---

ui/job-view/PushJobs.jsx
ui/job-view/details/DetailsPanel.jsx

Whether a job is selected should come from outside the ``DetailsPanel`` in this case.  And it needs to be set on ``$rootScope`` still.
Also, where I was checking it in the ``DetailsPanel`` doesn't exist.  ``this.selectedJob`` should have been ``this.props.selectedJob`` anyway.

Bug 1473505 - Fix ctrl + click job should select it

---

ui/js/models/repository.js
ui/models/treeStatus.js

The handling for this changed when we moved to ``fetch``.  This now handles unsupported repos as well as getting an error from the endpoint, in that unlikely event.

Bug 1473777 - Fix Treestatus for unsupported repos

---

setup.cfg

This explicitly sets our `tests` directory as a first party in `isort`.
We started seeing errors from isort here: https://travis-ci.org/mozilla/treeherder/jobs/403057132
The [related PR](https://github.com/mozilla/treeherder/pull/3781) has no changes related to those errors, we hadn't updated our isort version or config in the last few months.

Fix iSort Tests

---

treeherder/model/fixtures/repository.json
treeherder/model/fixtures/repository_group.json

These are in a new dedicated repository_group.
I don't really know what the 'codebase' parameter does -- is that a foreign key that I'll need to update somewhere?

Bug 1465838 - add ci-admin and ci-configuration repos

---

treeherder/model/models.py

This is a collection of documentation and tweaks to the JobNote model that didn't seem worth splitting up.  Hopefully the commits are succinct enough to make review easy though.
Added docstrings and comments erring on the side of excessiveness since this model is heavily used in classification via the Failure Summary tab.  It's also used from auto-classification and I needed to work out why.
A couple of little bits that probably don't optimise anything but helped me get my head around what was happening.

Document JobNotes

---

ui/job-view/details/tabs/JobDetailsTab.jsx

Wasn't a safe assumption in that sort, obviously.  This makes them sort correctly when there's no title.

Bug 1476109 - Fix jobs disappear when selected job has null details title

---

tests/ui/unit/react/groups.tests.jsx
ui/job-view/JobButton.jsx

This somewhat improves the accessibility of Treeherder for blind users, as a screen reader can read the title tag, and the user doesn't need to open each log to find the status.

Bug 1475438 - Add the job status to the job button title attribute

---

ui/js/auth/LoginCallback.jsx
ui/js/auth/auth-utils.js

The parameter to ``parseHash`` changed in the new version.  Since we have a wrapper to that function, we need to pass the new format.
https://auth0.github.io/auth0.js/global.html#parseHash

Bug 1476702 - Fix login broken after update to Auth0-js 9.7.2

---

treeherder/model/error_summary.py

This reinstates the removal of caching search terms when looping over TextLogErrors and adds a comment to explain why we're doing that.

Bug 1476469 - Stop AMQP Filling Up

---

treeherder/webapp/api/refdata.py

Remove this type of FailureClassifcation from the API so they no longer
appear in the UI.

Bug 1116372 - exclude "intermittent needs filing" FailureClassifcations

---

.travis.yml
Makefile
docs/common_tasks.rst

This pushes the source RST files down into a separate directory so they don't live at the save level as the output folder.  This is both in-keeping with how new Sphinx projects are laid out and aids separation of the two types of files.  It has the bonus effect of making fuzzy searching better by not polluting results with built files.

Split Documentation Source and Build Files

---

ui/css/treeherder-navbar.css

The visited color was too close to the red background color for closed repos.  So needed to specifically set it to lightgrey.  This item was formerly a ``<span>`` in button format, but it changed to an ``<a>`` when converted to ReactJS.  So we needed this extra formatting.

Fix text color on closed repos

---

requirements/common.txt
treeherder/webapp/graphql/helpers.py
treeherder/webapp/graphql/schema.py

Travis was failing on the original pyup-bot PRs, since the updates need to all be made at once.
The `DjangoFilterConnectionField` workaround has been removed, since it should no longer required, as the new release includes:
https://github.com/graphql-python/graphene-django/pull/224
Release notes:
* https://github.com/graphql-python/graphql-core/releases/tag/v2.1.0
* https://github.com/graphql-python/graphene/releases/tag/v2.1.3
* https://github.com/graphql-python/graphene-django/releases/tag/v2.1rc0
* https://github.com/graphql-python/graphene-django/releases/tag/v2.1rc1
* https://github.com/graphql-python/graphene-django/releases/tag/v2.1.0
Closes #3806.
Closes #3807.
Closes #3808.

Bug 1478663 - Update graphql related libraries

---

requirements/docs.txt
setup.cfg

Since Read The Docs has a pre-installed older version installed, and doesn't use `--upgrade` with pip, so we have to force the latest version to be installed by using "editable" (`-e`) mode:
https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support
This fixes the exception that occurred on Read the Docs (but wasn't seen on Travis, since it doesn't have the pre-installed older version):
https://readthedocs.org/projects/treeherder/builds/7564451/

Bug 1466084 - Docs: Install recommonmark as an editable dependency

---

treeherder/config/settings.py

add minute=0 to ensure task only runs once during specified hour

Bug 1453760 - Fix intermittents_commenter task

---

treeherder/webapp/api/jobs.py

This endpoint (`/jobs/failure_lines`) is unused.

Bug 1478378 - Remove JobsViewSet.failure_lines

---

tests/etl/test_job_loader.py
tests/test_worker/test_pulse_tasks.py
treeherder/etl/buildapi.py
treeherder/etl/common.py
treeherder/etl/exceptions.py
treeherder/etl/job_loader.py
treeherder/etl/pushlog.py
treeherder/model/tasks.py
treeherder/perf/tasks.py
treeherder/workers/task.py

Most non-periodic (ie not schedule via celery beat) were already automatically retrying, apart from these two.

Bug 1113235 - Make all non-periodic tasks automatically retry

---

docs/common_tasks.md

⚠️ **Blocked by #3813** ⚠️ 
This adds documentation on how to connect to services running inside the Vagrant VM.  It specifically documents MySQL as an example with the reasoning that it's the most likely service to be connected to.

 Bug 1069249 - Document Connecting to Services

---

tests/intermittents_commenter/test_commenter.py
treeherder/intermittents_commenter/commenter.py

without an env API key, certain bug metadata is not retrievable (401);
skip those bugs since too much logic is dependent on that data;
update bug_changes whiteboard only if the whiteboard has changed"

Bug 1453760 - skip bug when bug metadata is not retrievable

---

ui/job-view/JobView.jsx
ui/job-view/PushActionMenu.jsx
ui/job-view/details/summary/ActionBar.jsx
ui/js/controllers/tcjobactions.js
ui/js/services/main.js
ui/partials/main/tcjobactions.html

The ``PushActionBar`` was mistakenly still using the AngularJS service for Custom Actions.  But the bigger problem was that the Custom Actions dialog was still relying on ``$rootScope`` to get the logged in ``user``.  When I converted the ``PrimaryNavBar`` to React, along with the login, I moved the storage of ``user`` into the ``state`` of ``JobView`` and removed it from ``$rootScope``.  So I had should have then been passing ``isLoggedIn`` into the Custom Actions dialog, but I didn't.  This corrects it.
Not using that Angular service for Custom Actions will now also fix [Bug 1437736](https://bugzilla.mozilla.org/show_bug.cgi?id=1437736).
I also moved the ``bind`` of ``user`` into the ``render`` function of ``JobView``.  To be honest, I'm not clear why this would be necessary, but it …

Bug 1479973 - Fix issues with login and using custom actions

---

ui/js/services/jobfilters.js

"Add new jobs" adds a set of "runnable" jobs to the push.  These job objects have no field ``tier``.  If we are filtering by a field (``tier`` is a special field filter that we always filter against) that is not in the ``job`` object, we should consider it a pass and show the job.
When I cast ``jobFieldValue`` to a String and did ``toLowerCase``, it would take a result of ``undefined`` and make it into a ``String`` "undefined".  When I then checked ``if(jobFieldValue)`` then it came back true, because the string was valid.  Then when we compared the showing ``tier``s of ``[1, 2]`` to "undefined", it didn't find it and was told not to show the job.  Oops.
So this defers the ``toLowerCase`` till after I've checked if it's ``undefined``.

Bug 1480009 - Fix add new jobs not showing

---

treeherder/config/settings.py

Adjust the daily celery task to reflect what's in the OrangeFactor crontab:
daily runs every day except the day the weekly task runs. (previous research
showed me otherwise, but we should probably go with what the crontab has).

Bug 1453760 - Intermittent commenter daily celery task fix

---

treeherder/intermittents_commenter/commenter.py

change logic so that it always updates whiteboard status,
unless whiteboard_needswork_owner already exists. Add
clarifying comments to other stock_well text regexs used in the
Commenter class

Bug 1453760 - Fix commenter check_needswork_owner method

---

treeherder/intermittents_commenter/commenter.py

handle the case where no existing stockwell text was found or whiteboard is an empty string

Bug 1453760 - fix commenter update_whiteboard

---

ui/job-view/details/PinBoard.jsx

Using a ``Form`` wrapper here was unnecessary.  And it had the site-effect of when you hit enter within the form, it adds the ``failureClassificationId`` param to the URL BEFORE the hash, which triggered a page reload due to the Angular route changing.  Very odd, but this fixes it.  
The diff looks bigger than it is because I had to change the nesting since it was all in the ``Form`` control.

Bug 1477208 -Fix Pressing ENTER key in the comment refreshes the page

---

treeherder/config/settings.py
treeherder/etl/management/commands/read_pulse_jobs.py
treeherder/etl/management/commands/read_pulse_pushes.py
treeherder/etl/pulse_consumer.py
treeherder/services/pulse/__init__.py
treeherder/services/pulse/connection.py
treeherder/services/pulse/consumers.py
treeherder/services/pulse/exchange.py
treeherder/services/pulse/sources.py

This moves all Pulse configuration into a "service".  Like Elasticsearch this is a way to abstract and hide the lower level parts of configuring a Pulse connection and one/many consumers of it behind a [hopefully!] intuitive API.  It pulls all the settings for reading Pulse queues out of the global settings but leaves the write settings as I'm under the impression that these are going away soon[ish].
I considered further refactoring the two scripts (`read_pulse_pushes` and `read_pulse_jobs`) since they're so similar but I think that would require changing how the `PulseConsumer` class works and I didn't want to go for an even deeper dive!

Wrap Pulse Config and Setup in a Service

---

docs/pulseload.md
tests/conftest.py
tests/settings.py
treeherder/config/settings.py
treeherder/model/tasks.py
treeherder/services/pulse/connection.py
treeherder/services/pulse/sources.py

This removes the ingestion specific Pulse URL (`PULSE_DATA_INGESTION_CONFIG`) in favour of `PULSE_URL`, removes the unused `PULSE_PUSH_SOURCES` setting, and splits the ingestion sources setting `PULSE_DATA_INGESTION_SOURCES` into three distinct ones.

Bug 1281821 - Consolidate PULSE_* Settings

---

treeherder/intermittents_commenter/commenter.py

Fix key error with whiteboard and change condition involving bug_info (bug meta)
since it isn't needed to generate comments, only to potentially change
whiteboard status and priority (so we shouldn't actually pass).
Locally tested the daily comments like so: `./manage.py run_intermittents_commenter --dry-run`
and with the `-w` flag for weekly.

Bug 1481137 - fix commenter weekly task

---

tests/settings.py
treeherder/config/settings.py
treeherder/model/tasks.py

This partially reverts the changes in 6e7b1efac so the code which publishes to Pulse keeps using the credentials in `PULSE_URI` so we can deploy that change separately.

Bug 1281821 - use PULSE_URI instead of PULSE_URL for publishing to Pulse

---

treeherder/intermittents_commenter/commenter.py

A bug's whiteboard is initially supplied from bug_info and
updated as certain conditions are met. The check_bug_info method
was obscuring this process and as a result, any whiteboard
status's changed to disable-recommended were being reassigned.
The following changes were made:
- remove check_bug_info method and replace with fetch_bug_details
- replace whiteboard variable in generate_bug_changes with
change_whiteboard
- update change_whiteboard only when conditions are met
- update a bug's whiteboard status in bugzilla only if
change_whiteboard is not None
- check_needswork and check_needswork_owner return
an updated whiteboard status or None
- reorder section of code that assigns recommend-disable to whiteboard
Locally tested the daily comments like so: `./manage.py …

Bug 1481499 - refactor whiteboard in commenter

---

treeherder/config/settings.py
treeherder/intermittents_commenter/commenter.py
treeherder/intermittents_commenter/tasks.py

Change intermittents-commenter task soft and hard time limits (Sunday's commenter only posted 482 comments out of 1,251 bugs) and time.sleep in print_or_submit_changes (per Dylan's comment about rate limit for post requests: " For authenticated requests, no limit currently. In general get-bug clients should not do more than two requests per second ... " [here](https://github.com/mozilla/treeherder/pull/3571), this wasn't actually updated).

Bug 1482833 - fix commenter celery task

---

ui/job-view/headerbars/NotificationsMenu.jsx

The dates were all off because the ``toShortDateStr`` function
expects timestamps in seconds, but we were passing
milliseconds.  Just need to divide by 1000.

Fix dates on NotificationsMenu

---

tests/conftest.py
tests/e2e/test_client_job_ingestion.py
tests/etl/test_buildapi.py
tests/etl/test_load_artifacts.py
tests/etl/test_perf_data_adapters.py
tests/webapp/api/test_bug_job_map_api.py
tests/webapp/api/test_performance_alerts_api.py
tests/webapp/api/test_performance_alertsummary_api.py

This makes use of Django's [`.first()` method](https://docs.djangoproject.com/en/2.1/ref/models/querysets/#django.db.models.query.QuerySet.first) instead of indexing the QuerySets.  It's a little nicer to use in practice.

Replace uses of some_queryset.all()[0] with some_queryset.first()

---

treeherder/services/pulse/sources.py

This removes the `get_*` functions from the Pulse sources module in favour of inline definitions, as per the comment [here](https://github.com/mozilla/treeherder/pull/3863/files/8bd1d6afdf76d205f1a9d85c0a9b56992b541edc#r209455041).
Wrapping these values in functions provided no benefit so lets save the indentation.

Flatten Pulse source definitions to inline constants

---

package.json
renovate.json
yarn.lock

And remove the Renovate exclusion, since unlike some of the other ESLint dependencies that aren't compatible with Neutrino 4/ESLint 3, this plugin is still compatible - so is fine to receive automatic updates.

Update eslint-plugin-import to v2.14.0

---

newrelic.ini

So that the agent has longer to upload the final submission when Heroku restarts gunicorn (eg daily restarts or deploys).
See:
https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration#shutdown-timeout

Bug 1483301 - Raise the New Relic Python agent's shutdown_timeout

---

docs/pulseload.md
docs/submitting_data.md
treeherder/etl/management/commands/read_pulse_jobs.py
treeherder/services/pulse/sources.py

This removes the ability to configure Pulse destinations since they're not really being used.

Remove Configurability of Pulse Destinations

---

treeherder/services/pulse/connection.py

~This sets the default for our Pulse connection to a local guest account.~
This wraps the Pulse connection so the package's import doesn't attempt to construct the connection.
This came up during Travis testing #3919.  The linter checks run the Django's checks framework which triggers an import of the Pulse service.  The connection is built on import but the linter job has a minimal environment set up.

Make Pulse Connection Lazy

---

docs/pulseload.md
docs/submitting_data.md
treeherder/etl/management/commands/read_pulse_jobs.py
treeherder/services/pulse/sources.py

Reverts mozilla/treeherder#3884 due to:
```
Pulse warning: queue "queue/treeherder-staging/jobs" is overgrowing
Warning: your queue "queue/treeherder-staging/jobs" on exchange "could not be determined" is
overgrowing (4083 ready messages, 4083 total messages).
The queue will be automatically deleted when it exceeds 20000 messages.
Make sure your clients are running correctly and are cleaning up unused
durable queues.
```
I think the `consumer.get_binding_str` line here is wrong: 
https://github.com/mozilla/treeherder/pull/3884/files#diff-560cb9fe18938c4d2ed9fbf29027ba03R29
(before it used `routing_key`, not `project`)
Reverting to reduce the amount of data loss on stage.

Revert "Remove Configurability of Pulse Destinations"

---

package.json
renovate.json
yarn.lock

To reduce the Renovate PR noise from them, since they only contain TypeScript definitions, which we don't use.
(We only list them in our dependencies to prevent the missing `peerDependencies` warnings due to `react2angular` listing them in its `package.json`. Once we no longer use `react2angular` we can remove them entirely.)

Renovate: Ignore @types/* packages

---

ui/job-view/PushList.jsx
ui/js/controllers/logviewer.js
ui/models/job.js

I think that this is much closer to the pattern I want to follow for error handling with ``fetch`` when we want to return model "instances" rather than raw JS objects.  There's more work to be done with these models to establish a consistent pattern.  And I will revisit this when I address [Bug 1473777](https://bugzilla.mozilla.org/show_bug.cgi?id=1473777) as a whole for all the models and ``fetch`` handling.
This, however, fixes two cases where the ``job.id`` comes from the url, and could therefore be easily invalid.

Bug 1473777 - Fix error message if job is missing

---

docs/pulseload.md
docs/submitting_data.md
treeherder/etl/management/commands/read_pulse_jobs.py
treeherder/services/pulse/sources.py

This is the second attempt at the changes from #3884 
This PR contains a fix for the routing key in the `read_pulse_jobs` command as per #3927

Remove Configurability of Pulse Destinations (2)

---

docs/pulseload.md
treeherder/etl/management/commands/read_pulse_pushes.py
treeherder/services/pulse/sources.py

This removes the `PULSE_PUSH_SOURCES` setting, converting it to a hardcoded list of strings.
In [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1281821#c17) we discussed removing the configurability of this entirely.  I tried out converting the settings to a list of strings (with delimiters) and leaving the configurability but @edmorley [rightly pointed](https://github.com/mozilla/treeherder/pull/3926#discussion_r212340818) out it's unlikely one needs to configure them.
The strings in `push_sources` contain both exchange and routing keys in this format:
```
<exchange>.<routing key>[,<another routing key>,<yet another routing key>]
```
Once this is deployed to a Heroku env we can remove the `PULSE_PUSH_SOURCES` value from its config.

Bug 1281821 - Convert Pulse push configuration into a list

---

tests/services/pulse/test_connection.py
treeherder/services/pulse/connection.py

This is another (better!) version of #3921 making use of Django's `lazy` wrapper instead of `SimpleLazyObject`.  It includes some basic tests to confirm the connection object acts as expected, similar to intent (but not execution) to our `test_setup` tests.
Locally I've used this with a manually set `PULSE_URL` to pull both Job and Push messages from Pulse.

Make Construction of the Pulse Connection Lazy

---

tests/conftest.py
tests/services/pulse/test_publisher.py
tests/settings.py
treeherder/config/settings.py
treeherder/model/tasks.py
treeherder/services/pulse/publisher.py

This removes the `PULSE_EXCHANGE_NAMESPACE` configuration option opting to force all exchanges to use either `treeherder` or `test`.

Bug 1483231 - Remove Pulse Namespace Configuration

---

schemas/pulse-job.yml

This schema is a version-6 schema, which uses $id instead of id.
I'm not sure why this is here at all -- perhaps it could just be omitted?  A search for `jobInfo` over the entire repo doesn't find anything that seems to be referring to this subschema.

Use $id instead of id

---

docs/pulseload.md
tests/conftest.py
tests/services/pulse/test_consumers.py
tests/services/pulse/test_exchange.py
tests/services/pulse/utils.py
tests/settings.py
treeherder/config/settings.py
treeherder/etl/management/commands/read_pulse_jobs.py
treeherder/etl/management/commands/read_pulse_pushes.py
treeherder/services/pulse/__init__.py
treeherder/services/pulse/consumers.py
treeherder/services/pulse/exchange.py
treeherder/services/pulse/sources.py

This refactors the two Pulse scripts, `read_pulse_jobs` and `read_pulse_pushes` to use a common function for their consumer construction and source parsing.  In doing so we can now test this part of both scripts.
Note: this changes the Job sources configuration to a list of strings and how the Push source's routing keys are delimited so they are both the same.
Note2: this makes our `get_exchange` function slightly more useful by allowing us to configure it to create exchanges upon declaration of a bound `Exchange` instance.  It also returns the bound instance so we can perform actions on it elsewhere.

Test Pulse Scripts

---

ui/css/intermittent-failures.css
ui/intermittent-failures/BugDetailsView.jsx
ui/intermittent-failures/ErrorBoundary.jsx
ui/intermittent-failures/ErrorMessages.jsx
ui/intermittent-failures/MainView.jsx
ui/intermittent-failures/constants.js
ui/intermittent-failures/helpers.js
ui/intermittent-failures/redux/actions.js
ui/intermittent-failures/redux/reducers.js

Add spinner to ease transitions, add error boundaries,
add query param validation prior to api requests.
This is part 2 (part 1 was [bug 1460999](https://bugzilla.mozilla.org/show_bug.cgi?id=1460999))
I ended up having to refactor some of the changes I had made in part 1 in part because it either added unnecessary complexity or because of a bug I found while working on the spinner (multiple requests being made when the parent component mounts and the table library mounts - that also created a dilemma where we don't want to hide this table library for an error alert or it'll remount when the error is fixed, causing said problem).
I tested the validateQueryParams functionality locally.

Bug 1486660 - IFV UI error-handling additions

---

ui/job-view/PushList.jsx
ui/job-view/headerbars/SecondaryNavBar.jsx
ui/shared/ErrorBoundary.jsx

This is a proposal for a generic ``ErrorBoundary`` that allows a little customization.  I wanted something that would fit into different shaped areas.  So we can pass classes that will color and shape it, based on the context.
Here's an error with a ``WatchedRepo``:
Here's an error with a ``Push``:
The advantage of this over having a ``componentDidCatch`` in a particular component is that, as the docs say they do NOT catch "Errors thrown in the error boundary itself (rather than its children)".  
I am **certain** there is room for improvement here, but it's a starting point.  Maybe it should support more than one line, not really sure.  Opinions?  :)

Add generic ErrorBoundary

---

treeherder/model/error_summary.py
treeherder/model/models.py

This adds more clarification to some of the lower level methods used in classification of a Job or TextLogError.

Document More of the Classification Flow

---

tests/autoclassify/test_classify_failures.py
tests/conftest.py
tests/model/test_classified_failure.py
tests/webapp/api/test_bug_job_map_api.py
treeherder/model/models.py
treeherder/webapp/api/bug.py

This replaces uses of BugJobMap's default manager methods `.create()` and `.get_or_create()` with the classmethod `create()`.  The use of `.save()` is a Django-ism that, while great if you know Django and think to check for it, is an implicit code path hidden behind standard ORM calls.
Previously the `update_autoclassification_bug` method updated the BugJobMap's Job's TextLogMetadata.best_classification's bug number to that of the one used to create the BugJobMap.  This is now done as part of the `.create()` classmethod so it's explicit and clear it's being done (and hopefully better documented!)

Replace BugJobMap.objects.create() with BugJobMap.create()

---

treeherder/log_parser/tasks.py

This re-raises Celery's `SoftTimeLimitExceeded` so it can be handled elsewhere and logs all non-timeout exceptions to NewRelic.  It tracks non-timeout exceptions using a boolean flag since we don't care about what they were, just that they happened so we don't do further processing.

Bug 1483267 - Respect Celery Soft Time Limit in Log Parsing

---

requirements/common.txt

Since it dropped Python 2 support:
https://github.com/carltongibson/django-filter/blob/master/CHANGES.rst#version-20-2018-7-13
Updating will be handled in bug 1489212 once we use Python 3.
Closes #3784.

Make pyup ignore django-filter v2

---

bin/travis-setup.sh
requirements/docs.txt

CommonMark has made a breaking package change in a minor version release (0.8.0), so we need to pin to the last working release. See:
https://github.com/rtfd/CommonMark-py/issues/134
Fixes:
```
...
File ".../recommonmark/recommonmark/parser.py", line 9, in <module>
from CommonMark import Parser
ImportError: No module named CommonMark
```
The Travis docs setup step has also been modified to always upgrade dependencies, which will mean we will catch cases like this on Travis next time.
I've not added a comment to `requirements/docs.txt`, since pyup will open a PR to update the dependency (which will fail for now, but pass once they fix upstream) - and it will be a pain to have to manually edit that pyup PR to remove the comment (we probably want to keep the commonmark explicit version entry …

Bug 1489407 - Docs: Pin to older version of CommonMark to fix build

---

neutrino-custom/base.js
package.json
ui/js/logviewer.js
ui/js/treeherder.js
ui/js/treeherder_app.js
yarn.lock

The last usage of it was removed in bug 1450039. See:
https://docs.angularjs.org/api/ngResource
Since the DI arguments were already being updated, I've also removed the configuration of `$logProvider`, since we no longer use `$log`.

Bug 1489284 - Remove unused angular-resource

---

treeherder/log_parser/crossreference.py
treeherder/log_parser/tasks.py
treeherder/model/models.py

Two changes that don't really fit anywhere else:
The `crossreference_error_lines` function was a defunct wrapper fo `crossreference_job`.
`as_dict` was a misnamed function to convert a `FailureLine` instance into a mozlog compatible dictionary.

Simplify Cross-referencing Machinery

---

ui/helpers/location.js
ui/job-view/pushes/PushList.jsx
ui/js/models/resultsets_store.js

This actually fixes a couple bugs I found along the way:
* The "get next N" bug was caused by passing an existing ``fromchange`` param to the ``/resultset/`` which prevented it from getting anything older than that change.  So, it would have been the same bug if you loaded the page with the ``fromchange`` already set.
* If you had an old ``fromchange`` param from prior to 10 pushes ago, it would only get the latest 10 pushes, because the count was set to 10, regardless, on first page load.
* If you had a single ``revision`` showing with the ``revision`` param in the URL, and you clicked "get next N", then it would reload the page before loading them.  It shouldn't reload.

Bug 1489507 - Fix not loading older pushes more than once

---

treeherder/config/settings.py

This will allow these celery queues to drain before we remove the code that handles them. The runnable jobs task is also buildbot-specific, since for taskcluster the jobs are calculated via the tasks graph instead.

Bug 1443251 - Disable buildbot celerybeat tasks

---

ui/job-view/details/DetailsPanel.jsx
ui/job-view/details/PinBoard.jsx
ui/job-view/details/summary/ActionBar.jsx
ui/job-view/pushes/PushList.jsx

There were lots of places where we needed to use ``$rootScope.$apply()`` and ``$timeout`` to get AngularJS to display things.  This was primarily for ``thNotify`` which is still Angular.  But now ``thNotify`` calls ``$timeout`` itself, so we don't need these.  This just removes them.
``thNotify`` will be converted once ``ThResultSetStore`` is converted, because it's used in that store.

Remove Angular timeout and rootScope.apply in React code

---

ui/helpers/filter.js
ui/job-view/pushes/PushList.jsx
ui/js/controllers/main.js
ui/js/models/resultsets_store.js

Moves handling of reloading the page when certain url params change from Angular to React.
This is rebased off my other PR bug fix, so only the second commit needs reviewing here.  But there were some conflicting changes (and code in ``helpers/location`` that I needed for both PRs).

Convert onlocationchangesuccess

---

ui/job-view/headerbars/SecondaryNavBar.jsx

I was filtering by a field, rather than just the value in the array.

Fix unwatching a repo on SecondaryNavBar

---

package.json
ui/job-view/JobView.jsx
ui/job-view/KeyboardShortcuts.jsx
ui/job-view/details/PinBoard.jsx
ui/job-view/headerbars/SecondaryNavBar.jsx
ui/js/constants.js
ui/js/controllers/main.js
ui/js/directives/treeherder/main.js
ui/models/filter.js
yarn.lock

This replaces our angular keyboard shortcuts with React ones.  This package seemed pretty good.  It got the highest rating of maintenance, quality and popularity on  ``npm`` for the "shortcuts" packages that I could find.  
There is one quirk with this package: It required focus on an element that is either itself, or a child for the keys to work.  So I Wrapped everything in ``JobView`` by it.  This is fine, but since we are hosted in ``AngularJS``, there are some cases where focus can go outside of ``JobView``.  Like if you call ``element.blur()``.  So I set a ``tabIndex`` on the ``HotKeys`` element and just call focus on that, rather than doing ``.blur()`` anywhere.
``HotKeys`` requires using a ``keyMap`` and ``handlers``.  It's possible to use JUST a ``handlers`` where the object …

Bug 1450028 - Convert Keyboard Navigation to ReactJS

---

tests/intermittents_commenter/test_commenter.py
treeherder/intermittents_commenter/commenter.py
treeherder/intermittents_commenter/constants.py
treeherder/model/models.py

* batch bugzilla queries for GET requests: 1250 is a "safe limit" (I added a bit of leeway in case more `include_fields` or other params are later added). The actual limit for url string is 16k (on Bugzilla's end) but I don't know exactly how many bug_ids that would translate to. I erred on the safe side with this and decided to limit it to 1200 per request.
Also, for the week that I was testing this I discovered that 1208 out of 1250 bugs needed access to bugs_info, so I opted to keep it simple and fetch data for all bugs.
* refactor and optimized queries: removing the filter repo by 'all' has reduced the query time by several seconds and still returns the same amount of results as with the filter on (more importantly, line 308 uses the same query as the Failures endpoint for IFV, and …

Bug 1491133 - Optimize intermittents commenter

---

ui/job-view/details/tabs/autoclassify/AutoclassifyToolbar.jsx
ui/job-view/pushes/Push.jsx
ui/job-view/pushes/PushActionMenu.jsx
ui/job-view/pushes/PushHeader.jsx
ui/job-view/pushes/PushList.jsx

...rather than just to users with the `is_staff` Django permission (which mostly maps to sheriffs). This prevents the confusing UX of UI elements being unknowingly hidden to users who are missing the `is_staff` permission.
The check existed since these features used to use pulse_actions via Treeherder's API (which had coarser permissions controls), whereas now they use Taskcluster's API client side - so this check is purely aesthetic, since people could just use Taskcluster's API/UIs directly.
If certain groups of users should be prevented from accidentally scheduling too many jobs, access should instead be controlled via Taskcluster scopes at the task configuration level.

Bug 1490832 - Show trigger missing/talos jobs UI to all users

---

neutrino-custom/production.js
setup.cfg
ui/css/treeherder-pinboard.css
ui/job-view/JobView.jsx
ui/job-view/KeyboardShortcuts.jsx
ui/job-view/context/PinnedJobs.jsx
ui/job-view/details/DetailsPanel.jsx
ui/job-view/details/PinBoard.jsx
ui/job-view/details/summary/ActionBar.jsx
ui/job-view/details/summary/SummaryPanel.jsx
ui/job-view/details/tabs/TabsPanel.jsx
ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx
ui/job-view/details/tabs/autoclassify/ErrorLine.jsx
ui/job-view/details/tabs/autoclassify/LineOption.jsx
ui/job-view/details/tabs/autoclassify/StaticLineOption.jsx
ui/job-view/details/tabs/failureSummary/BugListItem.jsx
ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx
ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx
ui/job-view/headerbars/FiltersMenu.jsx
ui/job-view/headerbars/PrimaryNavBar.jsx
ui/job-view/headerbars/SecondaryNavBar.jsx
ui/job-view/headerbars/WatchedRepo.jsx
ui/job-view/pushes/JobButton.jsx
ui/job-view/pushes/PushActionMenu.jsx
ui/job-view/pushes/PushHeader.jsx
ui/job-view/pushes/PushJobs.jsx
ui/job-view/pushes/PushList.jsx
ui/js/constants.js
ui/js/controllers/main.js

I found some crufty code while doing this, so fixed those cases as the first commit.
This converts the list of Pinned Jobs (and bugs) to a context so it can be managed in several locations more easily (a follow-up PR will to convert the ``selectedJob`` to a context).

Bug 1492270 - Convert list of pinned jobs to a Context

---

treeherder/webapp/api/performance_data.py
treeherder/webapp/api/performance_serializers.py

Not a complete solution but hopefully this will improve things enough
to stop the timeouts we're seeing.

Bug 1492768 - Optimize alert summary queries executed from graphs view

---

treeherder/config/settings.py

Change daily task time to run one hour earlier since it appears that
the tuesday daily task is running at the same time the RDS snapshot occurs
and might be contributing to the celery task timeout exception (more info is
outlined as a comment on the bugzilla bug).

Bug 1485089 - Change commenter daily task

---

treeherder/webapp/api/serializers.py

The bug id lookup in validate_bug is querying bugscache rather than bugjobmap to check for a valid bug id. This would be an easy fix but I'm thinking it should be removed instead since it's kind of an 'extra' feature and to change it I'd have to do:
`bugs = BugJobMap.objects.filter(bug_id=id)` which isn't as quick as a 'get' lookup (and a bit redundant since it'll be doing that in the View with additional filters).

IFV - remove bug lookup in serializer

---

ui/job-view/details/summary/ActionBar.jsx

Use the logged in user, for who to notify of interactive tasks, rather than the push user.

---

ui/job-view/headerbars/FiltersMenu.jsx

This isn't needed/used in this context.  We want all showing jobs spanning all pushes.  Copy paste error.

Remove unnecessary param from FiltersMenu

---

Vagrantfile
vagrant/setup.sh

In addition:
* The minimum Vagrant version has been bumped, to pick up fixes for newer Ubuntu versions.
* The Hyper-V config has been removed, since it hasn't worked for a while (issues with networking etc).
* Any provision clean-up steps that are redundant (given that we know people will be starting with a fresh VM) have been removed.
* The latest version of pip is now used.

Bug 1478059 - Vagrant: Switch from Ubuntu 16.04 to 18.04
