- ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2036)
> Bug 1322411 - Use requestIdleCallback to schedule job updates.

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2042)
> Bug 1325540 - Fix setting expected job duration during ingestion

- tests/conftest.py
- tests/model/test_job_notes.py
- tests/webapp/api/test_bug_job_map_api.py
- tests/webapp/api/test_job_details_api.py
- tests/webapp/api/test_jobs_api.py
- tests/webapp/api/test_note_api.py
- tests/webapp/api/test_performance_data_api.py
- treeherder/etl/classification_mirroring.py
- treeherder/model/derived/jobs.py
- treeherder/model/models.py
- treeherder/model/tasks.py
- treeherder/webapp/api/bug.py
- treeherder/webapp/api/job_log_url.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/logslice.py
- treeherder/webapp/api/note.py
- treeherder/webapp/api/performance_data.py
- treeherder/webapp/api/serializers.py
- ui/js/controllers/logviewer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2040)
> Bug 1318474 - Make web api's use ORM ids as input and output

- tests/conftest.py
- tests/webapp/api/test_performance_alerts_api.py
- treeherder/webapp/api/performance_serializers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2049)
> Bug 1326045 - Fix downstreaming perf alerts to different repository + add unit tests

- ui/css/treeherder-info-panel.css
- ui/css/treeherder-loading-overlay.css
- ui/index.html
- ui/js/components/loading.js
- ui/js/controllers/perf/graphs.js
- ui/partials/perf/graphsctrl.html
- ui/perf.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2031)
> Bug 1206173 - Have a loading symbol when changing the date range in Perfherder

- docs/submitting_data.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2067)
> Fixing link to Pulse Guardian

- tests/conftest.py
- tests/sample_data/pulse_consumer/job_data.json
- tests/sample_data/pulse_consumer/transformed_job_data.json
- tests/seta/conftest.py
- tests/seta/test_analyze_failures.py
- tests/seta/test_high_value_jobs.py
- treeherder/etl/seta.py
- treeherder/model/management/commands/load_initial_data.py
- treeherder/seta/analyze_failures.py
- treeherder/seta/high_value_jobs.py
- treeherder/seta/job_priorities.py
- treeherder/seta/management/commands/update_runnable_jobs.py
- treeherder/seta/models.py
- treeherder/webapp/api/seta.py
After testing on treeherder-stage several issues were discovered.
I need to fix a couple more issues before I ask for review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2072)
> Bug 1328618 - SETA follow up changes 

- ui/plugins/pinboard.js
Frontend change done where minimum length string added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2062)
> Bug 1323536 - Make text field for annotating jobs mandatory for "fixed by commit"

- ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2080)
> Bug 1330388 - Pass correct parameter to Perfherder comparison validator

- ui/js/models/perf/series.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2088)
> Bug 1331745 - Fix e10s and hasal dashboards

- tests/conftest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2091)
> Bug 1332695 - Fix test_runnable_jobs_api test failure

- ui/partials/main/intermittent.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2096)
> Bug 1333208 - Use header/footer elements for bug filer modal + add a close button

- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/performance_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2090)
> Bug 1311982 - Handle PerformanceDatumViewSet.list error more gracefully

- ui/plugins/controller.js
* Pop up a dialog to confirm action
* Confirm that request to cancel was sent to server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2101)
> Bug 1332732 - Improve ergonomics around cancelling jobs

- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/performance_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2102)
> Bug 1311982 - Fix accidentally broken endpoint

- treeherder/etl/job_loader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2106)
> Bug 1333894 - Stop storing taskcluster's "summary" property in job details

- treeherder/perf/fixtures/performance_bug_templates.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2111)
> Bug 1333204 - Update the perfherder bugzilla template cc list

- ui/js/controllers/perf/graphs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2113)
> Bug 1334527 - Fix data selection in perfherder graphs when > 1 job per push

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2115)
> Bug 1334650 - Use full series name in performance panel

- treeherder/seta/analyze_failures.py
- treeherder/seta/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2126)
> Bug 1335898 - Increase SETA logger level when changing job priority

- ui/logviewer.html
- ui/partials/main/jobs.html
- ui/partials/main/thActionButton.html
- ui/userguide.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2123)
> Bug 1184510 - Stop using the term 'resultset' for pushes

- ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2124)
> Bug 1297185 - Show an error if fetching runnable jobs fails

- ui/css/treeherder-navbar-panels.css
- ui/index.html
- ui/js/controllers/main.js
- ui/partials/main/thActiveFiltersBar.html
- ui/partials/main/thWatchedRepoNavPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2030)
> Bug 1322923 - Expose from/to-Change filter parameters in the main UI

- tests/ui/unit/controllers/jobs.tests.js
- tests/ui/unit/models/resultsets.tests.js
- ui/js/services/treestatus.js
- ui/partials/main/thInfraMenu.html
- ui/partials/main/thWatchedRepoInfoDropDown.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2120)
> Bug 1335496 - Use the new Treestatus api

- treeherder/seta/analyze_failures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2133)
> Bug 1336632 - SETA: fix analyze_failures exception

- tests/conftest.py
- tests/perfalert/test_create_alerts.py
- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/performance_serializers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2135)
> Bug 1336706 - Fix performance alert summary

- treeherder/etl/seta.py
- treeherder/seta/analyze_failures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2138)
> Bug 1337102 - SETA: fix analzye_failures testtype parser

- treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2136)
> Bug 1337090 - Add esr52 repos

- ui/js/directives/treeherder/resultsets.js
- ui/js/models/resultsets_store.js
- ui/plugins/similar_jobs/controller.js
- ui/userguide.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2137)
> Bug 1184510 - Change some more UI references to 'result set'

- tests/webapp/api/test_job_details_api.py
- tests/webapp/api/test_jobs_api.py
- treeherder/webapp/api/jobs.py
- ui/js/models/job.js
- ui/partials/main/thPinboardPanel.html
- ui/plugins/controller.js
- ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2112)
> Bug 1217570 - Allow cancelling all selected jobs in pinboard

- ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2141)
> Bug 1217570 - Confirm that user really wants to cancel all jobs in pinboard

- tests/etl/test_runnable_jobs.py
- tests/seta/test_job_priorities.py
- tests/webapp/api/test_runnable_jobs_api.py
- treeherder/config/settings.py
- treeherder/etl/runnable_jobs.py
- treeherder/etl/seta.py
- treeherder/seta/job_priorities.py
- treeherder/seta/runnable_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2128)
> Bug 1330652 - fix job priorities endpoint so it returns data from correct repo

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2139)
> Bug 1334650 - Fix display of non-summary tests in job performance panel

- treeherder/webapp/api/performance_serializers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2145)
> Bug 1336706 - Test options not showing in perf alert titles

- ui/js/values.js
These builds are getting added in bug 1336479.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2146)
> Bug 1336479 - Add descriptive names for the 32-bit QR builds

- ui/js/controllers/main.js
- ui/js/services/jobfilters.js
- ui/partials/main/jobs.html
I'm not fluent in Angular so I'm sure I'm missing something, but I look forward to feedback.  Thank you!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2007)
> Bug 1178400 - Preserve filters when switching between repos

- treeherder/seta/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2147)
> Bug 1337949 - SETA: Make job priority __str__ and unique consistent

- ui/logviewer.html
- ui/perf.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2150)
> Bug 1289824 - Fix perfherder and logviewer

- ui/plugins/tabs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2156)
> Bug 1338519 - Rename autoclassify panel and use title case.

- treeherder/etl/seta.py
- treeherder/seta/job_priorities.py
Just a small fix to make the function name unique as you suggested
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2157)
> Bug 1338103 - Rename SETA function so it doesn't match local vars

- ui/js/controllers/bugfiler.js
Changes split out from the autoclassification UI rewrite branch, and
are just minor cleanup of the existing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2151)
> Cleanup bugfiler.js

- tests/seta/test_analyze_failures.py
- treeherder/seta/analyze_failures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2162)
> Bug 1330354 - Use select_related in get_failures_fixed_by_commit()

- treeherder/model/models.py
- treeherder/seta/analyze_failures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2164)
> Bug 1330354 - Small optimization for Job.get_platform_option

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2167)
> Bug 1339503 - Enable the autoclassify panel on localhost

- ui/css/treeherder-global.css
- ui/partials/main/thShortcutTable.html
Make sure that the panel is centred on the screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2168)
> Bug 1339508 - Organise keyboard help panel into sections.

- treeherder/log_parser/tasks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2166)
> Bug 1339506 - Improve the logging when running the autoclassifier.

- .travis.yml
- requirements/dev.txt
- tests/conftest.py
- tests/selenium/test_basics.py
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/perf/graphsctrl.html
- ui/partials/perf/testdatachooser.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2170)
> Bug 1339547 - Basic set of selenium tests for treeherder

- ui/partials/main/thShortcutTable.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2184)
> Bug 1339508 - Followup to close the <kbd> tags

- tests/selenium/test_basics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2186)
> Bug 1339547 - Wait/poll for test chooser to come up in perfherder test

- treeherder/seta/job_priorities.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2188)
> Bug 1338102 - Reduce SETA job priority not found warnings

- treeherder/seta/preseed.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2190)
> Bug 1340693 - Enable SETA for linux64-pgo

- treeherder/etl/runnable_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2191)
> Bug 1340787 - Maybe fix runnable_jobs api for comm-* trees

- ui/js/controllers/main.js
- ui/partials/main/thActiveFiltersBar.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2175)
> Bug 1340072 - Show more filters in the active filters bar

- ui/js/components/auth.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2174)
> Bug 1339659 - Fix race condition in login

- treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2195)
> Bug 1341930 - Add repository for webrender

- treeherder/seta/analyze_failures.py
- treeherder/seta/job_priorities.py
- treeherder/seta/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2193)
> Bug 1339836 - SETA: Optimize analyze_failures

- tests/webapp/api/test_job_details_api.py
- treeherder/webapp/api/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2202)
> Bug 1342522 - Allow filtering job details via value as well as title

- tests/seta/conftest.py
- tests/seta/test_analyze_failures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2209)
> Bug 1342451 - SETA: Fix test_analyze_failures

- ui/js/controllers/jobs.js
- ui/partials/main/jobs.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2207)
> Bug 1342589 - Fix the cancel jobs button string

- treeherder/log_parser/crossreference.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2210)
> Bug 1342377 - Ignore unsupported actions when crossreferencing error lines

- treeherder/perf/fixtures/performance_bug_templates.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2215)
> Bug 1343607 - Add regression filing template for autophone

- treeherder/config/settings.py
- treeherder/etl/runnable_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2216)
> Bug 1339829 - SETA: Change taskcluster taskgraph URL

- ui/partials/main/thRepoMenuItem.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2219)
> Bug 1342651 - Update the condition for the checkboxes in the repo menu

- tests/seta/conftest.py
- tests/seta/test_job_priorities.py
- treeherder/config/settings.py
- treeherder/etl/seta.py
- treeherder/seta/job_priorities.py
- treeherder/seta/models.py
- treeherder/seta/settings.py
- treeherder/seta/update_job_priority.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2221)
> Bug 1339829 - Refactor of SETA job-priorities API

- tests/autoclassify/test_classify_failures.py
- tests/autoclassify/utils.py
- tests/model/test_classified_failure.py
- tests/webapp/api/test_jobs_api.py
- tests/webapp/api/test_text_log_error.py
- tests/webapp/api/test_text_log_summary_lines.py
- treeherder/autoclassify/autoclassify.py
- treeherder/autoclassify/detectors.py
- treeherder/autoclassify/matchers.py
- treeherder/log_parser/crossreference.py
- treeherder/log_parser/tasks.py
- treeherder/model/migrations/0005_autoclassify_status.py
- treeherder/model/models.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/serializers.py
- treeherder/webapp/api/text_log_error.py
- treeherder/webapp/api/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2179)
> Bug 1321787 - Autoclassify through the TextLogError rather than through the FailureLine

- tests/model/test_calculate_durations.py
- treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2226)
> Bug 1328453 - Only use completed jobs for calculating average job duration

- ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2218)
> Bug 1340708 - Add stylo builds to thPlatformMap

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2228)
> Bug 1286018 - Add a few other job_types that don't default to performance tab

- treeherder/model/tasks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2232)
> Bug 1284432 - Set timeout of cycle data command to 3 hours

- ui/partials/main/thPinboardPanel.html
- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2229)
> Bug 1344958 - Add revision comments to the fixed-by-commit suggestions

- ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2236)
> Bug 1345309 - Add Android 7.1 to thPlatformMap

- ui/js/perfapp.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2231)
> Bug 1345149 - Update default perfherder controller window titles

- .eslintrc
- Gruntfile.js
- ui/index.html
- ui/js/controllers/tcjobactions.js
- ui/js/models/resultsets_store.js
- ui/js/services/tcactions.js
- ui/partials/main/tcjobactions.html
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
- ui/vendor/defaults.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2220)
> Bug 1344018 - Add ability to execute custom taskcluster actions per job

- ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2240)
> Bug 1344321 - Linux Nightlies on Beta

- ui/js/controllers/perf/alerts.js
- ui/js/models/resultsets_store.js
- ui/js/services/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2246)
> Bug 1347189 - Remove or replace uses of deprecated _.where function

- ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2249)
> Bug 1347209 - Fix "pin all" function

- ui/js/services/jobfilters.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2248)
> Bug 1347232 - Simplify some frontend filtering functions

- ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2250)
> Bug 1347275 - Fix acknowledging performance alerts

- ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2251)
> Bug 1347275 - Another lodash fix for performance alerts

- ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2254)
> Bug 1347366 - Fix file bug feature for perfherder

- ui/plugins/controller.js
- ui/plugins/tabs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2227)
> Bug 1344546 - Enable the Failure Classification panel by default

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2252)
> Revert bug 1333604 for now

- tests/etl/test_job_loader.py
- treeherder/etl/jobs.py
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2245)
> Bug 1330762 - Implement Taskcluster "inspect task" links directly in Treeherder's UI

- ui/js/controllers/tcjobactions.js
- ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2257)
> Bug 1347655 - Don't use "inspect task" link to get tc id of decision task

- ui/js/controllers/tcjobactions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2259)
> Bug 1347732 - Fix interpretation of "context" for taskcluster actions

- ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1883)
> Bug 1305507- Make sure canSaveClassifications works while entering bug number

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2267)
> Bug 1347764 - followup to strip more useless paths

- treeherder/seta/preseed.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2271)
> Bug 1347526 - Reduce SETA log info output in load_preseed

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2263)
> Bug 1348210 - Auto-block stylo-bustage metabug

- ui/js/controllers/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2274)
> Bug 1348978 - Add 'revision' to active filters bar

- tests/selenium/test_basics.py
- ui/js/controllers/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2264)
> Bug 1348276 - Fix getting revision comments for title strings

- ui/js/controllers/jobs.js
- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2285)
> Bug 1349693 - Fix some typos to fix backfilling jobs

- ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2282)
> Bug 1349464 - Deal with jobs that don't have _json-ending logs

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2281)
> Bug 1349449 - Trim some more bits of reftest file paths

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2283)
> Bug 1349740 - Fix up file paths for spidermonkey tests

- treeherder/perfalert/perfalert/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2292)
> Bug 1344358 - Fix accidental breakage of data sorting algorithm

- treeherder/webapp/api/text_log_error.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2293)
> Bug 1350590 - Only update job once we have added all the bugs.

- treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2295)
> Bug 1350705 - Exclude ignored lines when adding job annotations from failure summary

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2298)
> Bug 1351162 - Add 'REFTEST ERROR' as an omitted lead

- ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2303)
> Bug 1348135 - Fix how the performance tab gets enabled

- tests/webapp/api/test_bugzilla.py
- treeherder/webapp/api/bugzilla.py
- ui/css/treeherder-bugfiler.css
- ui/js/controllers/bugfiler.js
- ui/partials/main/intermittent.html
- ui/plugins/failure_summary/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2294)
> Bug 1289333 - Set crash signature and related fields

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2310)
> Bug 1352987 - Ensure a valid severity is sest when filing bugs

- ui/css/treeherder-bugfiler.css
- ui/js/controllers/bugfiler.js
- ui/partials/main/intermittent.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2316)
> Bug 1353209 - Add a spinner when searching sources for product/component pairs

- schemas/pulse-job.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2307)
> Bug 1352403 - Replace invalid "url" format with "uri"

- treeherder/perf/fixtures/performance_bug_templates.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2317)
> Bug 1346852 - Update default talos bug template cc list

- docs/common_tasks.rst
- docs/submitting_data.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2304)
> Bug 1352184 - Document adding a Github repo to Treeherder

- requirements/common.txt
https://docs.djangoproject.com/en/1.11/releases/1.10.6/
https://docs.djangoproject.com/en/1.11/releases/1.10.7/
https://github.com/django/django/compare/1.10.5...1.10.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2318)
> Bug 1353555 - Update Django from 1.10.5 to 1.10.7

- docs/common_tasks.rst
- docs/installation.rst
- docs/submitting_data.rst
- docs/ui/installation.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2327)
> Moved the methods of submitting data beneath the top level heading

- ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2338)
> Bug 1352846 - Allow save to work after using bugfiler

- ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2332)
> Bug 1355141 - Make autoclassify's bugfiler work again

- ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2329)
> Bug 1196142 - Auto-save pinboard's bug entry on blur

- tests/ui/unit/controllers/bugfiler.tests.js
- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2344)
> Bug 1356722 - Strip out chrome:// path to accessibility tests

- treeherder/webapp/graphql/schema.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2345)
> Bug 1356737 - Add RepositoryGraph for GraphQL

- ui/js/controllers/main.js
- ui/partials/main/thActionButton.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2342)
> Bug 1335506 - Only show Trigger Missing Jobs on integration branches

- tests/webapp/api/test_bugzilla.py
- treeherder/webapp/api/bugzilla.py
- ui/partials/main/intermittent.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2325)
> Bug 1354433 - Restrict crash signature field to 2048 characters

- .travis.yml
- package.json
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.9.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2347)
> Bug 1357389 - Update to nodejs 7.9.0

- ui/partials/main/thActionButton.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2346)
> Bug 1353065 - Rearrange thActionButton.html items

- docs/troubleshooting.rst
- vagrant/.profile
- vagrant/setup.sh
Since it saves having to document the troubleshooting step.
> Bug 1353807 - Remove celerybeat-schedule during provision

- treeherder/webapp/graphql/schema.py
We need this so that jobs will show what platforms they belong to.
> Bug 1356736 - Add GraphQL support for OptionCollections

- ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2335)
> Bug 1354792 - Use DXR to flesh out file paths for the bug filer

- treeherder/webapp/graphql/schema.py
Dang, I forgot to add this earlier.  Sorry for all the tiny PRs.
> Bug 1359606 - Add GraphQL JobGroup schema

- treeherder/log_parser/crossreference.py
The regexp for matching lines started off somewhat complex but ended
up just being equivalent to str.endswith(). Therefore using re is just
unnecessary overhead.
> Bug 1358593 - Use simple string matching in crossreference_error_lines

- .gitignore
- neutrino-custom/test.js
- package.json
- ui/js/reactrevisions.jsx
Various cleanup changes split out of #2309.
> Bug 1353014 - Preparation for Neutrino v5

- .travis.yml
- bin/run_celery_worker
- bin/run_celery_worker_buildapi
- bin/run_celery_worker_hp
- bin/run_celery_worker_log_parser
- bin/run_celery_worker_pushlog
- bin/run_celerybeat
- bin/run_gunicorn
- bin/run_read_pulse_jobs
- bin/run_read_pulse_resultsets
- vagrant/.profile
- vagrant/env.sh
- vagrant/setup.sh
> Bug 1363333 - Use the same Python binaries in Vagrant as Heroku

- tests/jenkins/Jenkinsfile
@rbillings / @davehunt / @edmorley r?
> Bug 1286686 - Fix Jenkins selenium tests tox paths

- ui/plugins/controller.js
This goes with https://reviewboard.mozilla.org/r/141126/diff/1#index_header and should allow us to backfill bbb jobs.
> Bug 1364421 - Allow bbb jobs to be backfilled

- ui/css/treeherder-bugfiler.css
- ui/js/controllers/bugfiler.js
- ui/partials/main/intermittent.html
- ui/plugins/auto_classification/controller.js
- ui/plugins/failure_summary/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2336)
> Bug 1355339 - Make the bug filer aware of blacklisted strings

- ui/js/values.js
Add a UI string for the newly added "android-5-0-aarch64" build.
> Bug 1367915 - Add UI string for Fennec AArch64 build

- treeherder/log_parser/failureline.py
This code assumes that any caught error results in a retry. But
that isn't actaully true for OperationalError where we only want
to retry if it's a specific kind of error, and otherwise just raise.
> Bug 1368988 - OperationalError ignored during failure_line storage.

- tests/conftest.py
- tests/test_setup.py
This prevents tests from inadvertently depending on external resources (for example logs on S3) due to missing mocked responses.
> Bug 1370249 - Block unmocked HTTP requests during Python tests

- .travis.yml
In the hope it might fix the intermittent connection timeouts.
> Bug 1372180 - Travis: Update geckodriver from 0.14.0 to 0.17.0

- neutrino-custom/lint.js
- package.json
- ui/css/perf.css
- ui/entry-perf.js
- ui/js/components/perf/compare.js
- ui/js/filters.js
- ui/js/services/main.js
- ui/partials/perf/average.html
- ui/partials/perf/tooltipgraphs.html
- yarn.lock
The sample visualisation can be found on http://localhost:5000/perf.html#/tooltipgraphs
Right now, I have made a new controller toolTipGraphsCtrl to render the distribution. Once the distribution is rendered to the tooltip, I'll remove it.
> Bug 1164891 - Visualize the distribution of test results using Canvas API

- treeherder/etl/common.py
By default New Relic only tracks the overall time spent making an external HTTP request, when this could in fact cover multiple sub-requests, if the first redirected.
This adds a New Relic custom event that tracks the time spent redirecting, to help assess the priority of bug 1348072.
> Bug 1372639 - Track the time spent redirecting when making requests

- tests/ui/unit/controllers/bugfiler.tests.js
- ui/js/controllers/bugfiler.js
Fix missing search_terms in test
Fix a broken test and a broken findFilename() function
> Bug 1364033 - Fix test failures in BugFilerCtrl

- tests/jenkins/Jenkinsfile
@edmorley / @rbillings r?
Ad-hoc run here: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/treeherder.adhoc/27/console 
A few failures, but seems consistent with current master: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/treeherder.adhoc/28/console
> Upgrade to Firefox 54

- .travis.yml
Works around travis-ci/travis-ci#7924 and travis-ci/travis-ci#7951.
> Bug 1374593 - Fix compatibility with Travis's new Trusty image

- treeherder/etl/jobs.py
Instead of hitting an exception and logging that when we get two jobs with the same guid during ingestion, we will now use a get_or_create to try to create it, but not throw an exception if we can't because it's JUST been created right after the check.
This case looks to only happen when a pending and running job with the same guid are being processed by different workers/dynos simultaneously.  So the worst that would happen would be that a job would look pending longer and then become complete immediately.
> Bug 1368989 - Fix integrity error during pulse job ingestion

- ui/partials/main/tcjobactions.html
> Bug 1378962 - don't show the 'Trigger' button when not logged in

- tests/seta/test_job_priorities.py
- treeherder/webapp/api/auth.py
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1326247
> Bug 1326247 - Fix deprecation warning in webapp/api/auth.py and seta/test_job_priorities.py

- tests/webapp/api/test_jobs_api.py
- treeherder/webapp/api/jobs.py
Fix and test for Bug 1368991
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1368991
> Bug 1368991 - api.jobs:JobsViewSet.list "AttributeError: 'list' object has no attribute 'values_list'"

- tests/jenkins/tests/test_keyword.py
This corrects a failing test locator.
> Tests fix test_keyword locator

- tests/webapp/api/test_performance_alertsummary_api.py
Bugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1390155
> Bug 1390155 - Make test_alert_sumary_post() use test_user and test_sheriff pytest fixtures

- treeherder/model/fixtures/repository.json
> Bug 1395412 - Disable the ESR45 repositories

- .travis.yml
- requirements/common.txt
[Treeherder] Update the requirements file to be compatible with Python3. r=emorley
> Bug 1389592 - Update requirements files to be compatible with Python 3. Add a Travis job to prevent regressions.

- tests/jenkins/Jenkinsfile
@edmorley r?  
Build-console output: https://gist.github.com/stephendonner/0b744f37efe2fdb4787267c3fd82f6ce (same intermittent failures as current).
> Update to Firefox 55

- tests/jenkins/requirements.txt
@edmorley r?
Build output (same results as on master): https://gist.github.com/stephendonner/364c1aad9e76b1d6089b7d6460d3ed39
> Update Python UI-test dependencies

- docs/testcases.rst
- tests/webapp/api/test_jobs_api.py
- treeherder/etl/jobs.py
- treeherder/model/models.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/permissions.py
- treeherder/webapp/api/refdata.py
- treeherder/webapp/api/serializers.py
- treeherder/webapp/api/urls.py
- ui/css/treeherder-navbar.css
- ui/js/controllers/main.js
- ui/js/models/resultsets_store.js
- ui/partials/main/thWatchedRepoNavPanel.html
Addresses [Bug 1387640](https://bugzilla.mozilla.org/show_bug.cgi?id=1387640)
Note: This leaves the models and tables intact so that we can
revert without data loss in case we discover an issue.  A follow-up
commit will remove those tables and models.
> Bug 1387640 - Stop using exclusion profiles

- .travis.yml
https://github.com/mozilla/geckodriver/releases/tag/v0.18.0
https://github.com/mozilla/geckodriver/releases/tag/v0.19.0
> Bug 1400539 - Travis: Update geckodriver to v0.19.0

- ui/css/treeherder-navbar.css
- ui/entry-index.js
- ui/js/controllers/notification.js
- ui/js/services/main.js
- ui/partials/main/thGlobalTopNavPanel.html
As discussed in the channel the other day. Hopefully I've angular'd this correctly!
> Bug 1400047 - Add a recent-notifications dropdown to the top nav panel

- .travis.yml
- package.json
(https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.5.0)
> Bug 1407008 - Update Node.js from 8.5.0 to 8.6.0

- ui/js/components/auth.js
- ui/js/controllers/bugfiler.js
- ui/js/controllers/failureviewer.js
- ui/js/controllers/jobs.js
- ui/js/controllers/logviewer.js
- ui/js/controllers/tcjobactions.js
- ui/js/models/resultsets_store.js
- ui/js/services/buildapi.js
- ui/js/services/main.js
- ui/js/services/tcactions.js
- ui/plugins/annotations/controller.js
- ui/plugins/controller.js
This is to make it easier to catch changes in review and to be easier to understand in general.
> Bug 1402062 - Switch thNotify api to have named options

- .travis.yml
- package.json
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.7.0
> Bug 1408748 - Update node from 8.6.0 to 8.7.0

- tests/jenkins/pages/treeherder.py
- tests/jenkins/tests/test_expanding_group_count.py
This fixes test_expanding_group_count by repairing the locators and improves it further by creating a JobGroup region.
> Fix test_expanding_group_count

- package.json
- yarn.lock
> Bug 1408776 - Update JS dependencies, Oct 2017

- ui/js/controllers/main.js
Removed focus when quick-filter input is cleared @camd
> Bug 1406465 - Clearing the job filter should remove focus from the job field

- tests/jenkins/Jenkinsfile
@edmorley r?
Pretty similar to the usual intermittents: https://gist.github.com/stephendonner/744d105ef72f3ab909d5bdaad3d55e1c
> Upgrade to Firefox 56

- tests/jenkins/tests/test_pin_job.py
> Fix test_pin_all_jobs to allow for the maximum number of 500 pinned jobs

- tests/jenkins/Jenkinsfile
> Switch to email-ext plugin for Jenkins build-email notifications

- .travis.yml
https://github.com/mozilla/geckodriver/releases/tag/v0.19.1
https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md
> Bug 1413507 - Travis: Update to geckodriver 0.19.1

- ui/js/controllers/filters.js
- ui/js/controllers/jobs.js
- ui/js/models/resultsets_store.js
- ui/js/services/pinboard.js
- ui/js/treeherder.js
- ui/js/values.js
Update: Changed pinboard error constant name and moved to values.js file, changed quotation style and fixed line-break.
Replaced all pinboard error messages with a constant.
> Bug 1152389 - reconciliation of pinboard count error messages

- .travis.yml
- package.json
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.0
> Bug 1413509 - Update Node.js from 8.7.0 to 8.9.0

- .travis.yml
- bin/post_compile
- bin/run_celery_worker
- bin/run_celery_worker_buildapi
- bin/run_celery_worker_hp
- bin/run_celery_worker_log_parser
- bin/run_celery_worker_pushlog
- bin/run_celerybeat
- bin/run_gunicorn
- bin/run_read_pulse_jobs
- bin/run_read_pulse_pushes
- runtests.sh
- tests/jenkins/pages/run.sh
- vagrant/.profile
- vagrant/env.sh
- vagrant/setup.sh
Shellcheck is a great tool for helping avoid common bash pitfalls:
https://github.com/koalaman/shellcheck
With this PR, it's now run on Travis and available in the Vagrant environment.
> Bug 1414255 - Lint shell scripts using shellcheck

- tests/jenkins/tox.ini
@edmorley r?  This can be merged anytime; thanks!
> Pass along Git env variables to ActiveData

- tests/jenkins/Jenkinsfile
@davehunt r?  @edmorley: mind holding off on a merge until @davehunt gives the "all clear?" We're in the process of migrating and configuring new Jenkins instances; thanks!
> Set number of pytest processes via environment variable

- ui/entry-index.js
- ui/plugins/job_details_pane.jsx
- ui/plugins/pluginpanel.html
For line 153, do we need to map over jobLogUrls - does this array ever have more than one object?
Also, how should I handle spacing between the label and content (ex: Job: Text)?
> Bug 1409892 - create components to migrate job info left pane to react

- requirements/dev.txt
- setup.cfg
- tests/conftest.py
- tests/jenkins/pages/treeherder.py
- tests/selenium/conftest.py
- tests/selenium/pages/treeherder.py
- tests/selenium/test_basics.py
- tests/selenium/test_switch_repo.py
The first of the Jenkins tests to be migrated to Travis. /cc @rbillings
> Migrate test_switch_repo to Travis suite

- ui/css/treeherder-navbar.css
- ui/partials/main/thWatchedRepoNavPanel.html
This was broken by the Bootstrap 4 upgrade and I missed it.
> Bug 1418505 - Make filtered unclassified count visible again

- ui/css/treeherder-info-panel.css
- ui/plugins/job_details_pane.jsx
- ui/plugins/pluginpanel.html
The CSS wasn't working correctly with the change to ReactJS.  This fixes it.
> Bug 1419514 - Fix odd scrolling over bug suggestions

- vagrant/setup.sh
To reduce the potential for contributors thinking the provision didn't complete successfully.
> Bug 1418982 - Vagrant: Hide expected warnings during provision

- ui/js/models/job.js
- ui/plugins/controller.js
- ui/plugins/job_details_pane.jsx
- ui/plugins/pluginpanel.html
Removes the UI of this mostly broken feature, to see what response we get, before we remove the API/data ingestion/DB parts.
> Bug 1419965 - Remove the estimated job time remaining UI

- setup.py
Since as far as I can tell it's not required by anything.
> Remove unnecessary setup.py

- tests/jenkins/requirements.txt
@edmorley r?
Mostly-passing build (intermittents): https://gist.github.com/stephendonner/08c70398e9d1cdf02bb9361b7165c0fe
> Update all pytest- deps, except for pytest itself.

- tests/jenkins/requirements.txt
@edmorley r?
Same results as previous build from master: https://gist.github.com/stephendonner/c4b14a4edf4e98091ae6dd0c5d107d3d
> Updating pytest-selenium to latest

- tests/jenkins/requirements.txt
@edmorley r?
Ad-hoc build here: https://pastebin.com/NwR8Wktk
> Upgrade to latest pytest

- tests/jenkins/Jenkinsfile
@edmorley last tweak to this, promise!
Build here: https://pastebin.com/5vuj8i1m
> Correct, permanent fix from Sauce Labs for Firefox 57

- .travis.yml
https://www.python.org/downloads/release/python-364/
> Travis: Update Python 3 linters job to Python 3.6.4

- ui/partials/main/jobs.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1409679#c9
> Remove link to GraphQL based test viewer while Bug 1409679 is being investigated.

- neutrino-custom/base.js
- package.json
- tests/ui/unit/init.js
- ui/entry-failureviewer.js
- ui/entry-index.js
- ui/entry-logviewer.js
- ui/entry-perf.js
- ui/js/treeherder.js
- yarn.lock
Since we don't use any of the functionality provided by ~them~ it:
https://docs.angularjs.org/api/ngCookies#module-components
~https://docs.angularjs.org/api/ngSanitize#module-components~
> Bug 1427295 - Remove unused angular-cookies

- tests/jenkins/pages/treeherder.py
- tests/jenkins/tests/test_unclassified_job.py
- tests/selenium/pages/treeherder.py
- tests/selenium/test_select_unclassified_job.py
I also added `test_select_previous_unclassified_job`
/cc: @rbillings
> Migrate test_select_next_unclassified_job to Travis suite

- tests/settings.py
- tests/test_setup.py
- treeherder/config/settings.py
- treeherder/config/utils.py
- treeherder/etl/buildapi.py
- treeherder/etl/pushlog.py
- vagrant/.profile
See individual commits for details 😺
> Bug 1384518 - Caching/settings cleanup to prepare for Redis switch

- tests/jenkins/pages/treeherder.py
- tests/selenium/pages/treeherder.py
- tests/selenium/test_range.py
> Migrate test_range to Travis suite

- ui/js/controllers/filters.js
- ui/js/controllers/perf/compare.js
- ui/js/controllers/perf/graphs.js
- ui/js/controllers/tcjobactions.js
- ui/js/directives/treeherder/clonejobs.js
- ui/js/models/repository.js
- ui/js/models/resultset.js
- ui/js/models/resultsets_store.js
- ui/js/services/jobfilters.js
- ui/js/services/log.js
- includes -> indexOf === -1
- indexOf -> indexOf
- compact -> filter(v => v)
> [1413156] _ to ES6: includes, indexOf & compact

- tests/jenkins/Jenkinsfile
Mostly-passing tests here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/treeherder.adhoc/60/console
@edmorley @davehunt r?
> Update to Firefox 58

- tests/webapp/api/test_push_api.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/push.py
@edmorley review needed. Changed 'error' key to 'detail'. Let me know anything else needed.
> Bug 1427375 - error key changed to detail

- tests/jenkins/requirements.txt
@edmorley @davehunt r?
Build identical to master run, here: https://gist.github.com/stephendonner/ebb56a8b31a7f3de2dc51a5bbf939591
> Update pytest-* to latest

- ui/js/controllers/jobs.js
- ui/partials/main/thActionButton.html
This reverts commit d41c3181737a6fc3aa9b8863cae70e7f21b3c189 (#3077), for causing [bug 1435023](https://bugzilla.mozilla.org/show_bug.cgi?id=1435023).
> Revert "Bug 1401518 - Make Add new jobs menu require a decision task"

- .gitignore
- treeherder/config/settings.py
- treeherder/templates/404.html
> Bug 1436598 - Cleanup Django static/media configuration

- treeherder/auth/backends.py
- ui/js/components/auth.js
- ui/js/services/main.js
Added logging to the backend and front end.
> Bug 1437824 - Add logging to help debug session issue

- ui/job-view/JobGroup.jsx
No bug on this because it's pretty small and quick to fix.
> Bug 1242905 - Fix honoring group_state url param on load

- ui/js/auth/AuthService.js
https://auth0.com/docs/api-auth/tutorials/silent-authentication#error-response
> Bug 1437116 - Logout user if there is a new scope required

- ui/js/auth/auth-utils.js
Do **not** merge yet!
Will be ready when:
> Bug 1437116 - Change "full-user-credentials" scope to "taskcluster-credentials"

- ui/helpers/locationHelper.js
- ui/job-view/JobButton.jsx
- ui/job-view/JobGroup.jsx
- ui/job-view/PushJobs.jsx
- ui/job-view/PushLoadErrors.jsx
This is created just to help make getting url params easier.  It'll also be a nice central location for handling when we move away from the hashed urls.
> Add new locationHelper for getting url params

- tests/jenkins/Jenkinsfile
Per the 3rd best practice on https://github.com/jenkinsci/pipeline-examples/blob/0b834c0691b96d8dfc49229ba6effd66470bdee4/docs/BEST_PRACTICES.md#jenkinsfiles-and-multibranch
@edmorley r?
> Add Groovy hashbang

- tests/ui/unit/models/resultsets.tests.js
- tests/ui/unit/react/jobs.tests.jsx
- ui/job-view/Push.jsx
- ui/job-view/PushActionMenu.jsx
- ui/job-view/PushHeader.jsx
- ui/job-view/PushJobs.jsx
- ui/job-view/PushList.jsx
- ui/js/controllers/filters.js
- ui/js/controllers/main.js
- ui/js/controllers/tcjobactions.js
- ui/js/models/resultsets_store.js
- ui/js/services/jobfilters.js
- ui/js/services/pinboard.js
- ui/partials/main/thWatchedRepoNavPanel.html
- ui/plugins/annotations/controller.js
- ui/plugins/controller.js
See individual commits for details.
Arguably, the second commit isn't related to ``ThResultSetStore`` but I found it while working.  I can move to another PR, if desired.  :)
> Bug 1440057 - Cleanup ThResultSetStore functions

- ui/job-view/PushList.jsx
Just a few minor things I found when fixing another bug.  I was listening to the same event twice.
> Bug 1434677 - Cleanup a couple minor PushList code issues

- tests/jenkins/requirements.txt
> Update requirements to latest

- neutrino-custom/lint.js
- ui/details-panel/AnnotationsTab.jsx
- ui/entry-login.jsx
- ui/job-view/JobCount.jsx
- ui/job-view/JobGroup.jsx
- ui/job-view/Platform.jsx
- ui/job-view/PushActionMenu.jsx
- ui/job-view/PushHeader.jsx
- ui/job-view/PushJobs.jsx
- ui/job-view/PushList.jsx
- ui/job-view/PushLoadErrors.jsx
- ui/job-view/Revision.jsx
- ui/job-view/RevisionList.jsx
- ui/plugins/failure_summary_panel.jsx
- ui/plugins/job_details_pane.jsx
- ui/test-view/redux/configureStore.js
- ui/test-view/ui/App.jsx
- ui/test-view/ui/Groups.jsx
- ui/test-view/ui/LogViewer.jsx
- ui/test-view/ui/Test.jsx
I just want to call out the first commit in particular - the style we switch to there isn't enforced by an ESLint rule (since one doesn't exist for it), so we'll need to bear it in mind when writing/reviewing in the future :-)
> Bug 1442485 - Enable more React ESLint rules

- tests/jenkins/Jenkinsfile
@edmorley r?
Ad-hoc buid here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/treeherder.adhoc/78/console and https://gist.github.com/stephendonner/6e4e0f21bfcb6815990936ddac6f45e3
> Update Firefox via Sauce to 59.0

- ui/js/models/repository.js
- ui/js/models/resultsets_store.js
- ui/js/services/pinboard.js
Bug 1413156 - lodash to ES6: _.size to .length. Objects now use Object.keys(...).length. Arrays use .length.
> Bug 1413156 - lodash to ES6: _.size to .length

- treeherder/etl/management/commands/read_pulse_jobs.py
- treeherder/etl/management/commands/read_pulse_pushes.py
- treeherder/model/pulse_publisher.py
- treeherder/seta/common.py
- treeherder/webapp/graphql/helpers.py
This removes all uses of the `assert` statement from non-testing code, replacing them with conditionals raising [hopefully] appropriate exceptions.
> Bug 1325838 - Remove non-testing assert statements

- ui/css/intermittent-failures.css
- ui/intermittent-failures/BugColumn.jsx
- ui/intermittent-failures/MainView.jsx
* Bug ID -> Bug
* Left align column
* Make the bug number itself a link to the bug, instead of an additional link
* Use CSS instead of javascript to show/hide details link
> Simplify bug column in intermittents table a bit

- ui/js/components/perf/compare.js
- ui/js/controllers/filters.js
- ui/js/controllers/perf/alerts.js
- ui/js/controllers/perf/graphs.js
- ui/js/models/repository.js
> Bug 1413156 - lodash to ES6: replace _.some, _.keys in PerfHerder

- .travis.yml
https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final
> Travis: Update Python 3 linters job to Python 3.6.5

- docs/pulseload.rst
- docs/ui/installation.rst
My hope is that this makes it easier to get up and running with ingesting **Pulse** data.
> Bug 1330702 - Improve the Pulse ingestion docs

- treeherder/config/settings.py
These are leftover from 0aec43a (#3230).
> Bug 1357476 - Remove django-rest-swagger remnants

- .travis.yml
- tests/conftest.py
- tests/selenium/test_filter_jobs_by_result_status.py
- tests/webapp/api/test_jobs_api.py
- treeherder/autoclassify/management/commands/matchers.py
- treeherder/config/utils.py
- treeherder/etl/bugzilla.py
- treeherder/etl/job_loader.py
- treeherder/etl/management/commands/publish_to_pulse.py
- treeherder/etl/perf.py
- treeherder/etl/push_loader.py
- treeherder/etl/runnable_jobs.py
- treeherder/etl/text.py
- treeherder/log_parser/crossreference.py
- treeherder/log_parser/management/commands/test_parse_log.py
- treeherder/log_parser/parsers.py
- treeherder/model/search.py
- treeherder/model/tasks.py
- treeherder/perf/management/commands/create_test_perf_data.py
- treeherder/perf/management/commands/import_perf_data.py
- treeherder/seta/analyze_failures.py
- treeherder/seta/job_priorities.py
- treeherder/seta/runnable_jobs.py
- treeherder/webapp/api/intermittents_view.py
- treeherder/webapp/api/push.py
- treeherder/webapp/graphql/schema.py
Next on the [bug 1330474](https://bugzilla.mozilla.org/show_bug.cgi?id=1330474) journey is adding the django system check step, and making that pass. This check covers a fair amount of the Django code, and will ensure that we don't regress on the basics not covered by flake8 (such as the Python 3 module renames and similar).
> Bug 1451518 - Make Django check pass under Python 3

- manage.py
- setup.cfg
- treeherder/model/migrations/0001_squashed_0022_modify_bugscache_and_bugjobmap.py
- treeherder/webapp/api/jobs.py
> Bug 1389517 - Fix remaining Python warnings & add test coverage

- treeherder/etl/jobs.py
Previously any `store_job_data()` exceptions raised when running the unit tests were suppressed, since the `TREEHERDER_TEST_PROJECT` setting no longer exists.
This reduced test coverage and meant any later test failures were much harder to debug (since the failure mode would be something vague like "expected 2 jobs, found 0").
I'm not overly keen on special-casing production like this, but once buildbot support is removed we can refactor the entire jobs ingestion to handle just one job at a time from pulse - and remove this with it.
The conditional has been adjusted to something that should be more stable over time - and if the environment variable is ever renamed, then this will fail in the less hard to spot direction (raising all the time). The moved log call will also ensure there is …
> Bug 1370246 - Make store_job_data() surface exceptions during tests

- treeherder/webapp/api/pagination.py
- ui/intermittent-failures/GenericTable.jsx
> Bug 1453757 - intermittent failures

- treeherder/model/management/commands/es_import_failure_lines.py
- treeherder/model/models.py
- treeherder/model/search.py
- treeherder/utils/queryset.py
This adds a QuerySet chunking function and makes use of it in the Elasticsearch Document loading command and deletion code.
> Add Queryset Chunking

- ui/intermittent-failures/GenericTable.jsx
- ui/intermittent-failures/helpers.js
add client-side sorting as an override to react-table's manual/server-side sorting
> Bug 1453468 - IFV table sorting

- treeherder/autoclassify/matchers.py
After realising the decorator was common functionality to every subclass I've pulled it into the parent `__call__`.  There's still some functionality in the ES matcher but it's specific to that class (makes it a no-op when ES isn't configured).
> Centralise common TextLogError filter to Matcher.__call__

- treeherder/autoclassify/autoclassify.py
- treeherder/model/models.py
Exactly what it says on the tin, realised this essentially wasn't in use anymore so dropped it =)
> Remove TextLogErrorManager

- ui/js/services/pinboard.js
- ui/plugins/pinboard.js
Trying to contribute to Bug 1413156
> Bug 1413156 - Convert from lodash bind to ES6 native bind

- tests/webapp/api/test_intermittent_failures_api.py
- treeherder/webapp/api/intermittents_view.py
- treeherder/webapp/api/serializers.py
- ui/intermittent-failures/BugDetailsView.jsx
Bug 1460053 needs to be merged first
> Bug 1445527 - Add machine name column

- treeherder/config/settings.py
- ui/intermittent-failures/constants.js
replace firefox-esrs and comm-esrs with lastest esr
> Bug 1460731 - change menu options

- ui/plugins/controller.js
You caught this before I merged my PR, but I somehow missed that email comment.  Sorry about that, my bad.
> Bug 1450039 - Add missing null-check before cancelling fetch promise

- ui/details-panel/SimilarJobsTab.jsx
Oops, dumb math precedence mistake...
> Bug 1460393 - Fix huge values for Duration under Similar Jobs

- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/MainView.jsx
- ui/intermittent-failures/helpers.js
check for, and update,  missing query string params; this fix is necessary for OF redirects (bug# 1445301)
> IFV - check query strings

- README.md
Links to:
https://whatsdeployed.io/s-dqv
> Add README badge for What's Deployed

- tests/autoclassify/test_autoclassify.py
- tests/autoclassify/test_classify_failures.py
- tests/autoclassify/test_matchers.py
- tests/autoclassify/test_utils.py
- treeherder/autoclassify/autoclassify.py
- treeherder/autoclassify/matchers.py
- treeherder/autoclassify/utils.py
This converts the matchers to functions.
The diff for that is a little gnarly but it's a straight conversion of class/query_best method -> function.
> Functional Matchers

- treeherder/autoclassify/autoclassify.py
⚠️ **Blocked by #3604** ⚠️ 
This adds tracking for which matcher got the highest score for a given error.  I'd like to start tracking which matcher gets the highest scores over time.
> Track High Score Matches

- treeherder/model/models.py
Now that I have a better idea of what the best_classification et al methods I realised this is where this metric should be firing from.
> Move verifying-of-classification metrics to TextLogError

- tests/webapp/api/test_intermittent_failures_api.py
- treeherder/webapp/api/intermittents_view.py
- treeherder/webapp/api/serializers.py
- ui/css/intermittent-failures.css
- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/BugLogColumn.jsx
modify failuresByBug endpoint to include test-unexpected-fail lines per job; change bugdetails UI to include failure counts and tooltip with lines
> Bug 1339937 - IFV show unexpected fails

- ui/js/controllers/perf/graphs.js
These little patches will become more and more necessary until we convert Perfherder to React.  But at least the fixes are simple enough.  I promise to do better testing on this going forward.  Though I may not need to migrate any more models that Perfherder shares until we get to Perfherder itself.
> Bug 1467159 - Fix Graphs Add Test Data geting stuck

- ui/css/treeherder-details-panel.css
- ui/css/treeherder-global.css
- ui/entry-index.js
- ui/index.html
- ui/job-view/JobView.jsx
- ui/job-view/PushList.jsx
- ui/job-view/details/DetailsPanel.jsx
This addresses [Bug 1469047](https://bugzilla.mozilla.org/show_bug.cgi?id=1469047)
> Bug 1469047 - Create common React ancestor for PushList and DetailsPanel

- ui/css/perf.css
- ui/js/models/perf/alerts.js
I introduced the scrolling issue while doing the React work.  And I allowed the Alert status message error through with one of the PRs I reviewed.  
So this cleans up a couple messes I made.
> Fix perfherder scrolling

- ui/job-view/JobCount.jsx
- ui/job-view/JobGroup.jsx
- ui/job-view/Push.jsx
It was adding new jobs ok, but threw a bunch of error messages on the console
when you did so.  Unexpected values or types for props for the most part.
> Fix noise with "add new jobs"

- bin/travis-setup.sh
- vagrant/setup.sh
https://github.com/mozilla/geckodriver/releases/tag/v0.21.0
> Bug 1471182 - Update geckodriver to 0.21.0

- ui/job-view/details/PinBoard.jsx
This fixes [Bug 1470532](https://bugzilla.mozilla.org/show_bug.cgi?id=1470532)
> Bug 1470532 - Fix 'fixed by commit' classification

- package.json
- ui/css/treeherder-details-panel.css
- ui/css/treeherder-global.css
- ui/job-view/JobView.jsx
- ui/job-view/details/DetailsPanel.jsx
- yarn.lock
This fixes [Bug 1468623](https://bugzilla.mozilla.org/show_bug.cgi?id=1468623) as well as [Bug 1470517](https://bugzilla.mozilla.org/show_bug.cgi?id=1470517) for the resizing as well as default size.
> Bug 1468623 - Fix resizing job details / pinboard panel

- ui/job-view/details/summary/SummaryPanel.jsx
This is a follow-up to Ed's pr with some of the suggestions he'd made to the handling.  I also removed the deprecated ``componentWillReceiveProps`` while I was at it.  Since this operation was ``async`` I couldn't use ``getDerivedStateFromProps``.  And this adds the little status we talked about if the fetch fails.
> Bug 1472204 - Clean up error handling for machine name

- treeherder/model/models.py
This uses a regex to replace each of MySQL's FTS operators in our search terms (which are log lines) with a space.  This stops us submitting syntactically incorrect search strings to MySQL but preserves the ability for Sheriff's to paste in log lines to search for.
Note: I've preserved the complete removal of double quotes (`"`).
> Bug 1469777 - Replace all FTS operators with spaces

- tests/ui/unit/react/revisions.tests.jsx
- ui/job-view/JobsAndGroups.jsx
- ui/job-view/Platform.jsx
- ui/job-view/Push.jsx
- ui/job-view/PushHeader.jsx
- ui/job-view/PushJobs.jsx
- ui/job-view/Revision.jsx
I believe this adds clearing it back into the right places.
> Bug 1472717 - Fix clear selected job when clicking away

- ui/job-view/JobView.jsx
- ui/job-view/Push.jsx
- ui/job-view/PushList.jsx
Moving this click event to a the top-level to catch some of the outer areas as well.
> Bug 1472717 - Add more click-to-clear-job targets

- treeherder/model/error_summary.py
- treeherder/model/models.py
This adds more documentation to methods and functions involved in human and automated classification.  I've deliberately not grouped all these together (I'm sure there will be more!) so as to try and help with reviewing them.
> Further Document Classification Flow

- ui/js/controllers/perf/graphs.js
- ui/js/models/repository.js
- ui/js/models/resultsets_store.js
- ui/js/services/jobfilters.js
forEach() and Object.keys are used to replace lodash .each()
> Bug 1467975 - Convert lodash .each() to native ES6 JS

- treeherder/intermittents_commenter/commenter.py
log a summary with number of weekly or daily comments for verification
when on stage/dev
> Add summary to Intermittents Commenter

- tests/ui/unit/filters.tests.js
- tests/ui/unit/models/jobs.tests.js
- tests/ui/unit/models/resultsets.tests.js
- tests/ui/unit/react/bugfiler.tests.jsx
- tests/ui/unit/react/groups.tests.jsx
- ui/entry-index.js
Fix a bunch of things that got crufty in the ReactJS changeover.
> React work cleanup

- ui/helpers/url.js
- ui/job-view/headerbars/WatchedRepo.jsx
This function in was redundant anyway.  Just needed to add a few more params to strip.
> Bug 1479832 - Fix repo urls having inappropriate params

- ui/helpers/url.js
- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/redux/actions.js
- ui/job-view/details/BugFiler.jsx
- ui/job-view/details/DetailsPanel.jsx
- ui/job-view/details/tabs/autoclassify/LineOption.jsx
- ui/js/controllers/logviewer.js
I fixed up the items you mentioned.  But, yeah, the helpers will need a good tidying up once we're done.  I found a few more redundancies in there.  :)
> Bug 1465987 - BugFiler post-merge cleanup

- treeherder/services/pulse/connection.py
This reverts commit 96db2547cc8a8f78921980f277ac60cb87dc49fe, to try and fix Pulse ingestion on `master`.
> Revert "Default for Pulse Connection (#3921)"

- package.json
- yarn.lock
This will be removed with the next release of metrics-graphics
> Bug 1489497 - fix dependency issue that is breaking IFV graphs

- treeherder/log_parser/crossreference.py
This does some refactoring to the `_crossreference()` function and related code to aid in readability.
Specifically it pulled the comparison function out of the summary class response and put it directly into the core loop.
> Readability Tweaks for Cross-referencing

- tests/ui/unit/models/filter.tests.js
- ui/models/filter.js
Just needed an exception for author.
> Bug 1490967 - Fix filtering with uppercase email address

- bin/travis-setup.sh
- vagrant/setup.sh
https://github.com/mozilla/geckodriver/releases/tag/v0.22.0
> Update geckodriver to 0.22.0

- ui/job-view/pushes/PushList.jsx
- ui/js/models/resultsets_store.js
This also fixes a related issue with the ``startdate`` param set.
> Bug 1491532 - Fix clicking next-N with tochange param

- docs/code_style.md
- docs/installation.md
Add general info about how we use Bootstrap, react-strap and CSS.
> Ui documentation update

- ui/job-view/details/PinBoard.jsx
This removes usage of ``JQuery`` and ``Mousetrap``.  Ends up the ``esc`` key wasn't working at all anyway since we moved away from mousetrap on the shortcuts.  So I just went to generic JS event handling.
> Bug 1492422 - Fix manual bug entering

- neutrino-custom/lint.js
- package.json
- tests/ui/unit/filters.tests.js
- tests/ui/unit/models/jobs.tests.js
- tests/ui/unit/models/resultsets.tests.js
- tests/ui/unit/react/groups.tests.jsx
- tests/ui/unit/react/revisions.tests.jsx
- ui/entry-login.jsx
- ui/intermittent-failures/GenericTable.jsx
- ui/intermittent-failures/redux/actions.js
- ui/job-view/CustomJobActions.jsx
- ui/job-view/details/DetailsPanel.jsx
- ui/job-view/details/tabs/autoclassify/AutoclassifyToolbar.jsx
- ui/job-view/details/tabs/autoclassify/LineOptionModel.js
- ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx
- ui/job-view/headerbars/WatchedRepo.jsx
- ui/job-view/pushes/JobButton.jsx
- ui/job-view/pushes/Push.jsx
- ui/job-view/pushes/Revision.jsx
- ui/js/auth/LoginCallback.jsx
- ui/test-view/index.jsx
- ui/test-view/redux/configureStore.js
- ui/test-view/ui/Test.jsx
This pre-emptively fixes the issues found by the newer ESLint and ESLint plugins that come with Neutrino 9 - in order to reduce the size of the Neutrino 9 PR.
> Bug 1364894 - Fix ESLint issues found by Neutrino 9

- ui/job-view/pushes/Push.jsx
This must've been lost in a refactor, I guess.
> Bug 1494087 - Make sure thNotify is available in Push.jsx

- docs/pulseload.md
- treeherder/services/pulse/connection.py
To account for the changes in #3948.
> Bug 1281821 - Docs: Correct Pulse environment variable references

- bin/travis-setup.sh
- vagrant/setup.sh
https://github.com/mozilla/geckodriver/releases/tag/v0.23.0
> Update geckodriver to 0.23.0

- treeherder/webapp/api/performance_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1976)
> Bug 1308122 - Make it return 400 when PerformanceSignatureViewSet meet ValueError

- tests/ui/unit/react/groups.tests.jsx
- ui/helpers/constants.js
- ui/job-view/JobView.jsx
- ui/job-view/headerbars/PrimaryNavBar.jsx
- ui/job-view/headerbars/SecondaryNavBar.jsx
- ui/job-view/pushes/JobGroup.jsx
- ui/job-view/pushes/JobsAndGroups.jsx
- ui/job-view/pushes/Platform.jsx
- ui/job-view/pushes/Push.jsx
- ui/job-view/pushes/PushJobs.jsx
- ui/job-view/pushes/PushList.jsx
Convert two of the angular events to state/props.
> Bug 1450041 - Convert job dup and count to properties

- ui/js/controllers/perf/graphs.js
Fix error when highlighting revisions
> Bug 1499362 - Fix highlighted revision data points

- ui/job-view/pushes/PushHeader.jsx
- ui/models/job.js
Some of Hassan's changes and mine crossed in the air without colliding during merge.  So his was referencing a field that no longer exists.
> Bug 1499531 - Fix cancel all jobs

- tests/ui/unit/context/pushes.tests.jsx
- ui/helpers/constants.js
- ui/job-view/JobView.jsx
- ui/job-view/KeyboardShortcuts.jsx
- ui/job-view/details/DetailsPanel.jsx
- ui/job-view/details/PinBoard.jsx
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/details/summary/SummaryPanel.jsx
- ui/job-view/details/tabs/AnnotationsTab.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
- ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx
- ui/job-view/details/tabs/autoclassify/ErrorLine.jsx
- ui/job-view/details/tabs/autoclassify/LineOption.jsx
- ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx
This removes the last usages of both ``$rootScope`` and ``$injector`` by converting the event handling to ``CustomEvent``.
>  Bug 1450041 - Convert angular events to CustomEvent

- yarn.lock
Updating the lockfile manually since Monday's schedule run did not occur due to the GitHub incident that day.
> Lock file maintenance

- .travis.yml
- package.json
- vagrant/setup.sh
https://nodejs.org/en/blog/release/v11.0.0/
Needs to wait for heroku/heroku-buildpack-nodejs#576.
> Bug 1502290 - Update to Node.js 11

- ui/intermittent-failures/MainView.jsx
This builds on top of Bug 1495429(https://github.com/mozilla/treeherder/pull/4178), so you only need to look at the second commit (I'll rebase once the first is approved and merged).
> Bug 1456934 - add search to IFV main table

- .eslintrc.js
- ui/job-view/App.jsx
- ui/job-view/details/BugFiler.jsx
- ui/job-view/details/DetailsPanel.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
- ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx
I might try to knock off a few of these.  Especially where I am the main culprit.  :)
> Bug 1183749 - Enable eslint rule: react/no-unused-state

- ui/job-view/context/Pushes.jsx
This was hitting an error trying to get ``fromchange`` from an empty array ``pushList`` to get the latest revision.  Basically, I forgot to add support for this use-case.  This also cleans up the params passed to the ``PushModel.getList`` which included anything on the url.  It was supposed to be reduced only to the params in ``pushPollingKeys``.  Added inline comments to explain why certain choices get made.
> Bug 1502350 - Fix waiting for push

- ui/logviewer/App.jsx
Dang, just a simple oversight.  My bad.
> Bug 1506630 - Fix revision link in Logviewer

- ui/job-view/pushes/PushLoadErrors.jsx
* Better spacing and padding
* Reduce verbage a bit
> Make "waiting for push" message a little nicer

- ui/job-view/App.jsx
- ui/job-view/context/Pushes.jsx
- ui/job-view/context/SelectedJob.jsx
- ui/job-view/headerbars/SecondaryNavBar.jsx
- ui/job-view/pushes/JobGroup.jsx
- ui/shared/auth/Login.jsx
- ui/shared/context/Notifications.jsx
Based on some of the observations in this bug, I've addressed the issues mentioned.  I didn't find any of these changes to greatly reduce memory leaks, but they're still good to get in there.
> Bug 1499551 - Cleanup add/remove event listeners and binding

- ui/job-view/App.jsx
- ui/job-view/CustomJobActions.jsx
- ui/job-view/KeyboardShortcuts.jsx
I'll do these in groups, since it ends up being quite a few line changes.  Here are the ones for the files in ``job-view`` root.
> Bug 1480166 - Use class fields to avoid bind() calls for root files.

- treeherder/model/fixtures/repository.json
Continuing from https://github.com/mozilla/treeherder/pull/4249
> Add a "repository" for Servo pull requests

- .eslintrc.js
- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/Graph.jsx
- ui/intermittent-failures/Layout.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/default-props-match-prop-types.md
> Bug 1513576 - Fix/enable ESLint 'react/default-props-match-prop-types'

- .eslintrc.js
- .neutrinorc.js
- docs/installation.md
- jest.config.js
- package.json
- tests/ui/models/filter_test.js
- tests/ui/unit/context/pushes.tests.jsx
- tests/ui/unit/models/jobs.tests.js
- tests/ui/unit/react/revisions.tests.jsx
- yarn.lock
This also fixed a few things that were fixed with ``yarn lint --fix``
> Bug 1364045 - Introduce Jest unit test framework

- ui/intermittent-failures/App.jsx
- ui/intermittent-failures/BugLogColumn.jsx
- ui/intermittent-failures/DateOptions.jsx
- ui/intermittent-failures/DateRangePicker.jsx
- ui/intermittent-failures/GraphsContainer.jsx
- ui/intermittent-failures/Navigation.jsx
- ui/intermittent-failures/View.jsx
- ui/logviewer/App.jsx
- ui/models/filter.js
- ui/perfherder/CompareSelectorView.jsx
- ui/perfherder/SelectorCard.jsx
- ui/shared/auth/Login.jsx
- ui/shared/context/Notifications.jsx
- ui/test-view/ui/Test.jsx
This is really the rest...  with the exception of Perfherder...  :)
> Bug 1480166 - Use class fields to avoid bind() calls in the rest

- ui/job-view/headerbars/WatchedRepo.jsx
This patch should completely prevent treestatus from being queried for non-hg repos, and if an hg repo is found to be unsupported on the initial treestatus check, it will clear the two minute interval for re-polling.
Easy way to test this: 
Open the network monitor for a treeherder tab (and filter requests to matching "treestatus" to avoid all the push/job requests from spamming the log), then open repos such that the three watchedRepos shown in the header are mozilla-inbound, servo-master, and version-control-tools. Reload the page.
mozilla-inbound is a supported hg repo, and you'll see the initial check to treestatus succeed.
servo-master is an unsupported git repo, and you will not see an initial check to treestatus.
version-control-tools is an unsupported hg repo, and you'll see the …
> Bug 1513427 - Only check treestatus for hg repos, and stop polling for unsupported hg repos

- ui/js/controllers/perf/compare.js
Found while testing #4414 on stage.
> Perfherder - fix typo with new perf API

- docs/testcases.md
This had a few outdated things that should be updated.
> Bug 1520355 - Update docs/testcases.md

- ui/job-view/headerbars/PrimaryNavBar.jsx
This was caused by not checking all the proper props in
shouldComponentUpdate.
> Bug 1520979 - Fix expand/collapse job group counts

- ui/helpers/filter.js
I forgot to add this set of fields to the list of filters
that should get inspected in the App.handleUrlChange.
> Bug 1521484 - Fix fromchange showing in ActiveFiltersBar

- treeherder/webapp/api/push.py
Add ``repository`` field to filter args to avoid errors with ``get()`` in list view.
> Bug 1306707 - Fix Push list view MultipleObjectsReturned exceptions

- treeherder/webapp/api/push.py
- ui/js/controllers/perf/compare.js
- ui/perfherder/SelectorCard.jsx
This fixes searching for a push by a sub-commit
> Bug 1525789 - Add commit_revision filter field to /push endpoint

- bin/travis-setup.sh
- vagrant/setup.sh
https://github.com/mozilla/geckodriver/releases/tag/v0.24.0
> Update geckodriver to 0.24.0

- .travis.yml
- tests/auth/test_backends.py
- tests/e2e/test_job_ingestion.py
- tests/etl/test_load_artifacts.py
- tests/log_parser/test_job_artifact_builder.py
- tests/log_parser/test_log_view_artifact_builder.py
- tests/log_parser/test_performance_artifact_builder.py
- tests/log_parser/test_tasks.py
- tests/webapp/api/test_auth.py
To help prevent regressions whilst the remaining xfailed tests are fixed.
> Bug 1527020 - Travis: Enable unit tests under Python 3

- treeherder/model/models.py
This fixes `UnicodeDecodeError` exceptions during `cycle_data` when using Python 3, that are due to invalid unicode in `text_log_error.lines` being retrieved by Django's `.delete()` (since it fetches all fields even the ones not required for model deletion traversal).
These bad unicode values should no longer be inserted for logs parsed once we switch to Python 3 - and may already be fixed for Python 2 by:
https://github.com/mozilla/treeherder/commit/4bdf9f91018b3a3306bf78db947a512f24225bab
Once all pre-Python 3 migration data has expired, hopefully the New Relic custom event will show the workaround is no longer required.
> Bug 1528710 - Workaround cycle_data UnicodeDecodeError

- .dependabot/config.yml
- requirements/common.txt
Release notes:
https://docs.djangoproject.com/en/2.1/releases/2.1/
This PR depends on #4705 - I'll rebase once that's reviewed/merged.
> Bug 1529240 - Update Django from 2.0 to 2.1

- .eslintrc.js
- ui/intermittent-failures/DateOptions.jsx
- ui/intermittent-failures/GraphsContainer.jsx
- ui/intermittent-failures/Navigation.jsx
- ui/job-view/App.jsx
- ui/job-view/details/tabs/SimilarJobsTab.jsx
- ui/job-view/details/tabs/autoclassify/ErrorLine.jsx
- ui/job-view/details/tabs/autoclassify/LineOption.jsx
- ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx
- ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx
- ui/job-view/pushes/JobButton.jsx
- ui/job-view/pushes/JobGroup.jsx
- ui/job-view/pushes/Push.jsx
- ui/perfherder/CompareTableControls.jsx
- ui/perfherder/DropdownButton.jsx
- ui/perfherder/SelectorCard.jsx
- ui/push-health/Metric.jsx
- ui/test-view/ui/Navigation.jsx
Nothing too complicated here.  :)
> Bug 1513581 - Fix ESLint react/no-access-state-in-setstate

- Procfile
As recommended by:
https://devcenter.heroku.com/articles/celery-heroku#using-remap_sigterm
For more context see:
https://github.com/celery/celery/issues/2839
> Bug 1470243 - Use REMAP_SIGTERM=SIGQUIT with Celery on Heroku

- treeherder/model/fixtures/repository.json
- treeherder/model/fixtures/repository_group.json
- ui/job-view/headerbars/ReposMenu.jsx
Based off of #4249 (and #3452)  
r? @karlht
> Add Fenix and Reference browser repos

- ui/job-view/details/summary/SummaryPanel.jsx
- ui/job-view/details/tabs/AnnotationsTab.jsx
- ui/job-view/details/tabs/PerformanceTab.jsx
- ui/job-view/details/tabs/SimilarJobsTab.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
- ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx
- ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx
- ui/shared/JobDetails.jsx
This addresses [Bug 1531245](https://bugzilla.mozilla.org/show_bug.cgi?id=1531245)
> Bug 1531245 - Add some a11y regions to job-view details area

- ui/js/controllers/perf/graphs.js
Fix this regression that had been caused by bug 1527824
> Bug 1532533 - Perfherder graph highlighting revisions

- ui/push-health/TestFailure.jsx
Then the user can expand them with a "more..." link
> Bug 1521157 - Collapse some test details by default

- treeherder/push_health/classification.py
- treeherder/webapp/api/push.py
- ui/push-health/ClassificationGroup.jsx
- ui/push-health/Metric.jsx
- ui/push-health/TestFailure.jsx
- ui/push-health/TestFailures.jsx
Please see individual commits.
> Bug 1521157 - Show Push Health suggested classification for tests

- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/Layout.jsx
- ui/partials/perf/alertsctrl.html
- ui/partials/perf/graphsctrl.html
- ui/partials/perf/testdatachooser.html
- ui/perfherder/compare/CompareSubtestDistributionView.jsx
- ui/perfherder/compare/CompareTableView.jsx
- ui/perfherder/compare/ReplicatesGraph.jsx
- ui/perfherder/compare/Validation.jsx
In Intermittent Failures View and Perfherder, per #4807
> Add missing title prop to non-decorative font-awesome icons

- .gitignore
- docs/installation.md
- docs/troubleshooting_vagrant.md
- vagrant/setup.sh
This has been something I've wanted for a while and finally looked into how to do it.  See docs for explanation.  :)
> Bug 1056865 - Add support for custom env file in Vagrant that is ignored by git

- treeherder/push_health/push_health.py
- treeherder/push_health/similar_jobs.py
- ui/push-health/ClassificationGroup.jsx
- ui/push-health/Health.jsx
- ui/push-health/Job.jsx
- ui/push-health/Metric.jsx
- ui/push-health/TestFailure.jsx
- ui/push-health/TestFailures.jsx
- ui/push-health/index.jsx
See the individual commits for some details.
> Bug 1521157 - Enable retriggering jobs in Push Health

- treeherder/push_health/utils.py
Joel requested this in IRC a week or two ago.
> Update Push Health clean_config for 'shippable'

- treeherder/push_health/similar_jobs.py
Fix the ability to retrigger in Push Health view.
> Bug 1543935 - Fix retriggers in Push Health.  Add job_type_name

- tests/ui/unit/models/jobs_test.js
- ui/job-view/context/Pushes.jsx
- ui/job-view/details/tabs/SimilarJobsTab.jsx
- ui/job-view/pushes/Push.jsx
- ui/models/job.js
- ui/models/push.js
This addresses the issues found with the new linting in PR #4891.  I figured I'd fix it here so that PR will be cleaner.
> Fix circular dependency in JobModel/PushModel

- ui/job-view/details/summary/ActionBar.jsx
> Bug 1553063 - Fix a typo

- ui/perfherder/alerts/AlertsView.jsx
Add total pages and refactor generatePages; add new method to
generate current pages and add note about first and last navigation links
> Bug 1559149 and 1559146 - fix Perfherder alerts view pagination

- ui/js/controllers/perf/graphs.js
- ui/partials/perf/testdatachooser.html
- ui/perfherder/graphs/TestDataModal.jsx
A few changes for this modal that got pushed to prod this morning. I noticed these while working on pr #5096.
> Perfherder - changes to TestDataModal

- ui/css/perf.css
- ui/entry-perf.js
- ui/js/controllers/perf/graphs.js
- ui/partials/perf/graphsctrl.html
- ui/perfherder/graphs/SelectedTestsContainer.jsx
- ui/perfherder/graphs/TestCard.jsx
This is for the divs/cards containing tests that are selected from the `TestDataModal` (when you click the 'add more test data' button).
Edit: I've decided to move the changes to the `TestDataModal` to a separate pr since it contained a fix to the filter behavior.
> Bug 1519995 - Convert Graphs view to React - test cards section

- ui/intermittent-failures/BugDetailsView.jsx
- ui/intermittent-failures/MainView.jsx
A basic version of the breadcrumb. @sarah-clements requesting your help in understanding more about the implementation. 
What else could be a part of the breadcrumb.
https://bugzilla.mozilla.org/show_bug.cgi?id=1447535
> Bug 1447535 : added simple breadcrumb instead of a back button

- ui/css/perf.css
- ui/perfherder/graphs/TestCard.jsx
I just merged #5096 but realized I should move the checkbox to make better use of space since some test names are really long.
> Perfherder graph legend style changes 

- .neutrinorc.js
- tests/ui/helpers_test.js
- tests/ui/job-view/bugfiler_test.jsx
- tests/ui/job-view/context/pushes_test.jsx
- tests/ui/job-view/groups_test.jsx
- tests/ui/job-view/revisions_test.jsx
- tests/ui/job-view/selected_job_test.jsx
- tests/ui/models/jobs_test.js
- tests/ui/perfherder/alerts_test.jsx
- tests/ui/perfherder/compare_table_test.jsx
- tests/ui/perfherder/replicates_graph_test.jsx
- tests/ui/test-setup.js
I think this folder needed a little cleanup in accordance with our new ``/ui`` layout with react.  I'm wondering how you feel about this setup.  I figure we can have a different ``tests/ui`` item for each app.
> Cleanup tests/ui folder

- ui/helpers/filter.js
- ui/job-view/App.jsx
- ui/job-view/details/DetailsPanel.jsx
- ui/job-view/details/PinBoard.jsx
- ui/job-view/details/summary/StatusPanel.jsx
- ui/job-view/details/summary/SummaryPanel.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
- ui/job-view/pushes/Push.jsx
- ui/job-view/pushes/PushJobs.jsx
- ui/models/bugJobMap.js
- ui/models/classification.js
- ui/models/job.js
- ui/models/jobLogUrl.js
This cleans up several small things I found while converting ``Pushes.jsx`` to redux.  So to remove the noise in that PR, I wanted to get them in here.
> Cleanup selected job redux

- ui/job-view/details/DetailsPanel.jsx
> Bug 1564879 - Show selected job styling in pinboard

- treeherder/webapp/api/push.py
- ui/helpers/url.js
Here is the push where this issue was hit:
https://treeherder.mozilla.org/#/jobs?repo=autoland&revision=21fe727a9ebaff6d7842bb45594299da66ae5efd
> Bug 1565364 - Fix add new jobs when decision task was retried

- ui/css/perf.css
- ui/js/controllers/perf/graphs.js
- ui/perfherder/graphs/TestCard.jsx
I've changed the graph color scheme to include high contrast colors that were previously removed, per feedback. @davehunt Please let me know what you think of these changes.
> Perfherder graphs view - change graphs color scheme

- ui/job-view/context/PinnedJobs.jsx
- ui/job-view/details/DetailsPanel.jsx
Hopefully the comments help explain what the bug was and how I addressed it.
> Bug 1572387 - Fix lag for classified jobs getting updated

- treeherder/perf/management/commands/import_perf_data.py
The workers were easily breaking because of badly allocating the tasks + when accessing secured data.
This PR addresses both these problems.
> Bug 1524521 - Provisioning local perf data is hard

- ui/css/treeherder-details-panel.css
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/details/summary/ClassificationsPanel.jsx
- ui/job-view/details/summary/LogUrls.jsx
- ui/job-view/details/summary/StatusPanel.jsx
- ui/job-view/details/summary/SummaryPanel.jsx
- ui/shared/JobInfo.jsx
I'll be the first to admit that I went a bit far in fixing this tiny issue.  But our ``CSS`` for this area is way too complex.  So I deleted a bunch of stuff, added in just what was needed and made better use of the Bootstrap utilities classes.
This CSS needs more work, but this is a step in the right direction.
> Bug 1572521 - Improve click target size of job actions ellipses

- ui/perfherder/graphs/GraphTooltip.jsx
Remove createQueryParams from link. This was a silly oversight :)
> Bug 1580229 - Fix Job url on Perfherder tooltip

- tests/ui/perfherder/compare_table_test.jsx
- ui/css/perf.css
- ui/models/job.js
- ui/partials/perf/comparectrl.html
- ui/partials/perf/comparesubtestctrl.html
- ui/perfherder/compare/CompareSubtestsView.jsx
- ui/perfherder/compare/CompareTable.jsx
- ui/perfherder/compare/CompareTableControls.jsx
- ui/perfherder/compare/CompareTableView.jsx
- ui/perfherder/compare/CompareView.jsx
- ui/perfherder/constants.js
- ui/perfherder/helpers.js
[Bugzila bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1571643)
> Bug 1571643 - Retrigger jobs from compare view

- ui/job-view/pushes/PushHeader.jsx
> Bug 1578060 - Show number of selected runnable jobs

- tests/ui/helpers/helpers_test.js
- tests/ui/helpers/taskcluster_test.js
- tests/ui/models/push_test.js
- ui/helpers/taskcluster.js
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/pushes/PushActionMenu.jsx
- ui/models/job.js
- ui/models/push.js
"What we've got here... is a failure to communicate..."  We weren't checking if the requested action was available.  So we weren't accurately communicating the problem to the user.  This adds that check and exits with a notification if we don't get the action we want.
> Bug 1575941 - Fix error message when task action not available

- ui/perfherder/graphs/GraphTooltip.jsx
- ui/perfherder/graphs/GraphsView.jsx
Alert summary to be found by push id, since revision can be valid for multiple repositories
> Bug 1581473 - Fix Perfherder graphs tooltip

- ui/css/perf.css
- ui/perfherder/graphs/GraphsContainer.jsx
- ui/perfherder/graphs/GraphsView.jsx
- ui/perfherder/graphs/LegendCard.jsx
Change zoom so it doesn't reset when test visibility changes;
fix overflowing legend card links
> Bug 1581066 - Perfherder graphs zoom fix

- ui/perfherder/graphs/GraphsContainer.jsx
The Perf sheriffs weren't happy with the change to mouse zoom for the lower graph so this is swapping it out and removing code used to optimize the mouse zoom. Thanks to the Victory library maintainer, we're able to adopt the `SelectionContainer` with a workaround to the onClick issue (I had filed a bug because the onClick events weren't working with this container).
> Bug 1582731 - Perfherder lower graph change

- treeherder/model/management/commands/cycle_data.py
- treeherder/model/models.py
This *does* increase the verbosity of our logging for ``cycle_data``.  But since it happens only once per day, I don't think it'd be that bad.
This fixes the pruning of the job types, groups and machines.  The tables, at this point, are large enough that the current queries never succeed.  So this chunks them up.
> Bug 1583303 - Fix pruning job types, groups and machines in cycle_data

- treeherder/model/fixtures/repository.json
Same as https://github.com/mozilla/treeherder/pull/4758
r? @karlht 🙂
> Bug 1583870 - Add android-components repo

- tests/ui/perfherder/alerts_test.jsx
- ui/perfherder/alerts/AlertActionPanel.jsx
- ui/perfherder/constants.js
23-27 September 2019: @octavian-negru PTO. 
@ionutgoldan will make the changes after code review.
> Bug 1582692 - Ensure no one can add confirming state from Perfherder

- ui/perfherder/alerts/AlertsView.jsx
bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1584145
> bug 1584145 - fix single pagination in alerts page

- package.json
- ui/job-view/CustomJobActions.jsx
- yarn.lock
This removes the usage of ``react-select``.  I just used your ``DropdownMenuItems`` and it works great.  :)
``yarn`` wanted to rearrange the package order to alphabetize.  So that added some noise.
> Bug 1507903 - Stop using react-select component

- ui/helpers/http.js
- ui/job-view/details/BugFiler.jsx
- ui/job-view/details/PinBoard.jsx
- ui/perfherder/graphs/GraphTooltip.jsx
- ui/perfherder/graphs/GraphsContainer.jsx
- ui/perfherder/graphs/GraphsView.jsx
- ui/perfherder/graphs/GraphsViewControls.jsx
This was the last change to Perfherder that I wanted to keep separate since it involves changing the use of fetch in the `create` function and updating `createAlert`, Bugfiler and the JobModelClassification model. Since I'm not familiar with where these changes hit TH's UI, I haven't tested the changes except for with `createAlert`.
Cam do you want to test that these changes work as expected or should I have the sheriffs check on prototype or stage?
> Add error handling to Perfherder createAlert

- ui/job-view/headerbars/SecondaryNavBar.jsx
- ui/job-view/pushes/PushList.jsx
- ui/perfherder/compare/CompareTable.jsx
The following disabled rules are removed and pass
* jsx-a11y/control-has-associated-label
* SecondaryNavBar.jsx
* PushList.jsx
* CompareTable.jsx
* jsx-a11y/no-static-element-interactions
* SecondaryNavBar.jsx
* PushList.jsx
@sarah-clements please kindly review.
> Remove and pass disabled rules

- ui/css/treeherder-navbar.css
- ui/job-view/headerbars/SecondaryNavBar.jsx
- ui/models/filter.js
> Bug 1335929 - Treeherder "# unclassified" button gives no indication of being toggled

- ui/job-view/pushes/PushActionMenu.jsx
- ui/models/push.js
- ui/push-health/ClassificationGroup.jsx
This was a bug in fixing merge conflicts between one of my PRs and a PR from Dustin.
I also fixed an error in params in Push Health.
> Bug 1586875 - Fix trigger missing and talos jobs

- tests/etl/conftest.py
- tests/etl/test_perf_data_adapters.py
- tests/etl/test_perf_data_load.py
- treeherder/etl/perf.py
This branch depends on [measurement-units-support](https://github.com/octavian-negru/treeherder/tree/measurement-units-support) branch.
> Ingest measurement units

- ui/job-view/details/summary/ActionBar.jsx
This fixes creating a gecko profile.
> Bug 1583132 - Fix create gecko profile

- treeherder/webapp/api/performance_data.py
- treeherder/webapp/api/performance_serializers.py
- treeherder/webapp/api/urls.py
- treeherder/webapp/api/utils.py
[Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1580687)
> Bug 1580687 - Provide backend endpoint for test validity dashboard

- ui/job-view/pushes/Push.jsx
- ui/job-view/pushes/PushHeader.jsx
@camd It should be all fixed now!
:)
> Bug 1421273 - Add badge to show count of fixed by commit per push

- treeherder/perf/fixtures/performance_bug_templates.yaml
I'm attempting to reduce the amount of bugmail I recieve
> Remove dhunt from cc list in bugzilla templates

- .neutrinorc.js
- docs/pulseload.md
- docs/submitting_data.md
- treeherder/etl/common.py
- treeherder/etl/management/commands/ingest_push_and_tasks.py
- treeherder/etl/runnable_jobs.py
- treeherder/middleware.py
- treeherder/model/fixtures/repository.json
- treeherder/seta/update_job_priority.py
- ui/helpers/url.js
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/details/summary/SummaryPanel.jsx
- ui/job-view/headerbars/InfraMenu.jsx
- ui/job-view/pushes/Push.jsx
- ui/logviewer/App.jsx
- ui/models/runnableJob.js
- ui/shared/JobInfo.jsx
This will need to land before #5543
> Bug 1593869 - prep for Taskcluster migration

- ui/css/treeherder-details-panel.css
- ui/css/treeherder-job-buttons.css
- ui/job-view/details/summary/ActionBar.jsx
Hi, @sarah-clements and @camd!
Bug is: https://bugzilla.mozilla.org/show_bug.cgi?id=1554287
I've removed zooming effect and added `findJob` [icon](https://fontawesome.com/icons/crosshairs?style=solid) to `ActionBar`
[Here](https://ibb.co/kqgzCRM) is screenshot. 
Let me know If I can do anything else :)
> bug-1554287 - remove zooming effect and add scroll to selected job

- package.json
- ui/intermittent-failures/BugDetailsView.jsx
- yarn.lock
@sarah-clements  @camd 
1. Added `react-helmet` package.
2. Added `Helmet` fragment in `BugDetailsView.jsx`.
> Bug 1447537: Adjust document title when viewing particular intermittent

- treeherder/middleware.py
Accidentally removed in third party login bug 1566190
> Bug 1595639 - Update CSP with taskcluster.net

- ui/push-health/ClassificationGroup.jsx
- ui/push-health/Metric.jsx
These little items stood out to me after the last PR where I'd copied things that should have taken advantage of Reactstrap.  :)
> Bug 1596602 - Push Health use Reactstrap where needed

- ui/helpers/url.js
- ui/job-view/details/summary/ActionBar.jsx
- ui/shared/JobInfo.jsx
Refactor getInspectTaskUrl to check date for creation of task links.
FYI @armenzg
> Bug 1596297 - Support legacy task inspector links

- treeherder/model/management/commands/cache_failure_history.py
- treeherder/push_health/tests.py
- treeherder/webapp/api/push.py
- ui/push-health/Health.jsx
- ui/push-health/Metric.jsx
- ui/push-health/TestFailures.jsx
More description in individual commits.  :)
> Bug 1597835 - Refactor Push Health to ease adding new metric support

- treeherder/push_health/linting.py
- treeherder/webapp/api/push.py
- ui/push-health/Health.jsx
- ui/push-health/JobListMetric.jsx
- ui/push-health/TestMetric.jsx
This sits on top of #5661.  So only the last commit is relevant for this review.
> Bug 1561683 - Add linting results to Push Health

- treeherder/push_health/builds.py
- treeherder/webapp/api/push.py
- ui/push-health/Health.jsx
This sits on top of #5662.  Only the last commit is relevant.
> Bug 1561684 - Add Build results to Push Health

- treeherder/perf/fixtures/performance_framework.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1572356
> Bug 1572356 - Register the vcs framework in perfherder

- schemas/performance-artifact.json
Mirrors this [Phabricator PR](https://phabricator.services.mozilla.com/D53973).
> Bug 1587401 - Mirror new schema validations on Perfherder

- treeherder/etl/artifact.py
Use ``bulk_create`` and ``bulk_insert`` to batch creation and update of ``JobDetail`` records.
> Bug 1598333 - Optimize JobDetail inserts

- treeherder/perf/fixtures/performance_bug_templates.yaml
Changed my bugzilla/phab email address.
> Bug 1600550 Update alexandrui email address

- ui/perfherder/graphs/GraphsContainer.jsx
@sarah-clements I created a new branch and will close the old one, just started everything from the beginning, the only change is in the function `setRightPadding` I called the `checkDate` function in the return. Please let me know if there is something we can change.
> Bug-1584135-Perfherder-graph-change 

- ui/css/treeherder-navbar.css
Related to #5725 
This PR fixes the styling issue caused by the mentioned PR merging.
> Bug 1600757 - Dropdown menu SR keyboard support - fix

- treeherder/push_health/tests.py
This just adds a few code comments to help others (and me!) follow what is happening in the Push Health back-end code.
> Code comments for push_health functions

- .neutrinorc.js
This pull request adds favicon for perfherder as per Bug 1599761 on Bugzilla.
> Bug 1599761 - Add favicon for perfherder from ui/img/line_chart.png

- package.json
- ui/css/intermittent-failures.css
- ui/intermittent-failures/DateRangePicker.jsx
- yarn.lock
The Date Picker in the Intermittent Failures View is not keyboard accessible. It was recommended that we chose a different library, rather than trying to make the one we use accessible.
After some research, it was determined that [Airbnb's Date Picker](https://github.com/airbnb/react-dates) would be a good substitute to the current Date Picker library.
- A comparison of the results was done with the current changes and the `master` branch, to check if they were the same, in the chosen dates;
- Tab navigation test was performed;
- Simple NVDA navigation was performed to listen to labels.
**Screenshot with default view**
--------------
**Screenshot with a chosen date**
> Bug 1603245 - Date picker is not keyboard accessible

- .neutrinorc.js
- tests/ui/perfherder/compare_table_test.jsx
- tests/ui/perfherder/retrigger_modal_test.jsx
- ui/perfherder/compare/ComparePageTitle.jsx
- ui/perfherder/compare/CompareTable.jsx
- ui/perfherder/compare/CompareTableControls.jsx
- ui/perfherder/compare/CompareTableRow.jsx
- ui/perfherder/compare/RetriggerButton.jsx
- ui/perfherder/compare/RetriggerModal.jsx
- ui/perfherder/constants.js
- ui/perfherder/helpers.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1569584
> Bug 1569584 - retriggering dialog on compare view

- ui/css/treeherder-navbar.css
- ui/shared/HelpMenu.jsx
- ui/shared/auth/Login.jsx
convert Login menu to reactstrap
> Bug 1497931 - Finish bootstrap to reactstrap conversion

- requirements/common.txt
https://bugzilla.mozilla.org/show_bug.cgi?id=1610349
> Bug 1610349 - hashes for windows

- ui/helpers/url.js
- yarn.lock
This also updates the `yarn.lock` file to make it current.
> Bug 1611220 - Fix URLs for Intermittent Failures View

- ui/job-view/pushes/PushActionMenu.jsx
- ui/job-view/pushes/PushHeader.jsx
- ui/test-view/ui/Groups.jsx
Test-View is now superseded by Push Health.  So let's begin the process of decommissioning it.
> Bug 1611334 - Add notification to Test-View to use Push Health

- ui/push-health/Health.jsx
- ui/push-health/Navigation.jsx
Fix dropdowns on navbars as well as them not scrolling away when scrolling the page down.
> Bug 1610242 - Fix push-health navbars

- app.json
Since we recently bumped the database add-on we can ingest two repos.
> Review apps to also ingest try

- .travis.yml
- runtests.sh
> Add missing pytest flag to enable Python code coverage

- ui/helpers/url.js
- ui/perfherder/constants.js
- ui/perfherder/health/HealthView.jsx
[Back to Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1612892)
> Bug 1612892 - Perfherder's Health view is broken

- ui/shared/DropdownMenuItems.jsx
[Back to PR](https://bugzilla.mozilla.org/show_bug.cgi?id=1613344)
> Bug 1613344 - Dropdowns are broken

- treeherder/seta/settings.py
> Bug 1608427 SETA: Add fuzzing builds

- treeherder/seta/settings.py
Armen, sorry that I missed this one.
> Bug 1608427 SETA: Part 2: Add spidermonkey fuzzing build, r=armenzg.

- docs/accessibility.md
- docs/installation.md
- mkdocs.yml
This PR updates the documentation to reflect a11y changes and guidelines, as seen in #5725  and #5781.
Sections added:
- General Practices
- Reactstrap
- Font Awesome
- Colors
- Colors in buttons
- Inserting new colors
- Red and Green
- Images
- Image HTML tag
- SVG
- Interactive elements
- Dropdown menu
- Forms, inputs and buttons
- Specific elements
- Progress Bar
- Tables
- Other Components
- References
> Documentation Update - Accessibility page

- ui/intermittent-failures/DateRangePicker.jsx
- ui/intermittent-failures/helpers.js
This fixes the following warning errors, in Intermittent Failures View:
**DatePicker Component**
**Table row style in helpers.js**
> IFV warning fixes

- setup.cfg
isort to ignore all directories that start with dot
> Less isort

- ui/job-view/headerbars/SecondaryNavBar.jsx
- ui/job-view/headerbars/TierIndicator.jsx
> Bug 1594895: add a UI Indicator to show status of tier3 jobs

- ui/index.html
I think omitting this was causing the new relic synthetics alert.
> add title to new index.html template

- tests/ui/perfherder/alerts_test.jsx
- ui/perfherder/alerts/AlertsView.jsx
- ui/perfherder/constants.js
changed "all" options to "all statuses" and "all frameworks"
> Bug 1614578 - Differentiate the "all" items from status & framework dropdowns

- treeherder/config/settings.py
I added the perfSheriffBot settings in the Django settings file.
> Bug 1618827 - Create basic config for perfSheriffBot

- tests/ui/push-health/CommitHistory_test.jsx
- treeherder/push_health/tests.py
- ui/push-health/CommitHistory.jsx
- ui/push-health/GroupedTests.jsx
- ui/push-health/Health.jsx
I found a couple bugs while fixing this.  I split them into separate commits.  I hope you don't mind me piggy-backing on the main fix, which is in the last commit.  If you'd rather, I can create separate commits.
> Bug 1616311 - Add ability to copy test group name to clipboard

- ui/shared/Revision.jsx
This component used to save the `comment` in `this`.  I modified it to be more "react-ish" but only created `comment` as a localized var in the `isBackout` function.  I  needed to do it in `render`.  So here it is.
> Fix Revision comment

- schemas/perf-sheriff-bot-log-details.json
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618816)
> Bug 1618816 - BONUS: Define json schema for `log_details` column

- treeherder/perf/management/commands/synthesize_backfill_report.py
- treeherder/perf/perf_sheriff_bot.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618820)
> Bug 1618820 - Include reporter tool logic in the PerfSheriffBot

- .pre-commit-config.yaml
- package.json
@armenzg added format check for javascript files in the pre-commit file
Do let me know if any further changes are required!
> Add prettier pre commit hook

- docker-compose.yml
- treeherder/config/settings.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618846)
> Bug 1618846 - Grab variables via Django’s settings.py

- treeherder/webapp/api/push.py
After looking into New Relic aggregation, I think we MAY be able to get at least part way with just this.  Let's try this first.  If we need to go further later, then we can do that.
> Push health NewRelic api calls and log

- treeherder/perf/fixtures/performance_bug_templates.yaml
- treeherder/perf/fixtures/performance_framework.json
removed bug template and database record for AWFY
> Bug 1615540 - Remove AWFY from Perfherder

- ui/intermittent-failures/GraphAlternateView.jsx
Bug [ID](https://bugzilla.mozilla.org/show_bug.cgi?id=1619758)
@sarah-clements @yogmel
> Bug 1619758 - Remove sorting in Intermittent Failures View Table

- README.md
This PR adds a "Contributing" section, with some guidelines on contributors' flow, on Github `README.md` file
It covers:
1. Getting bugs assigned
2. Before sending a PR - testing and git rebase
3. PR requirements
> Update docs with contributing section

- ui/perfherder/alerts/AlertsView.jsx
This makes the pagination work correctly!!
fetchAlertSummaries was not passed correctly as props
> BUG 1622604: passed fetchAlertSummaries correctly as props

- docker-compose.yml
- docs/common_tasks.md
I finally got a python debugging tool to work with docker (and it was painless)!!
FYI @camd and @jmaher
> Enable pdb in a docker container

- treeherder/perf/perf_sheriff_bot.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618837)
> Bug 1618837 - PerfSheriffBot-should-condition-the-backfill-by-the-query-load-of-queue

- treeherder/etl/management/commands/heroku_environment.py
This is just a prototype but it shows how we could validate all Heroku environments from the comfort of our CLI.
> Bug 1625274 - Basic functionality to validate Heroku config vars

- treeherder/push_health/linting.py
- treeherder/push_health/tests.py
> Bug 1610916 - Fix some linting jobs showing up unsupported

- ui/css/perf.css
- ui/css/treeherder-custom-styles.css
- ui/perfherder/graphs/TableView.jsx
Bugzilla Bug: [1620734](https://bugzilla.mozilla.org/show_bug.cgi?id=1620734)
@yogmel
> Bug - 1620734: Fixed color ratio in Graph View

- treeherder/etl/perf.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1625450)
> Bug 1625450 - Default application field to unspecified or empty string

- ui/helpers/constants.js
I'm bad with git, and also Travis wasn't showing tests passed, so I've deleted the branch and re-created it.
> Bug 1620326 - add pretty label for linux1804-64-tsan

- ui/perfherder/alerts/AlertsView.jsx
Modified File: AlertsView.jsx
Fixed any linting issues found with yarn lint --fix
> Bug 1615365 - Redirecting to correct url on changing the status or framework filter

- treeherder/etl/perf.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1627265)
> Bug 1627265 - At data ingestion distinguish between firefox and chrome applications

- treeherder/etl/push_loader.py
[Back to Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1514412)
> Bug 1514412 - Fix KeyError in tag push situation of GithubPushTransformer

- ui/perfherder/alerts/AlertsViewControls.jsx
Change conditions to show page controls on last page.
> Bug 1595111 – Alerts view gets stuck on last page

- treeherder/webapp/api/push.py
- ui/css/intermittent-failures.css
- ui/css/treeherder-custom-styles.css
- ui/job-view/pushes/Push.jsx
- ui/job-view/pushes/PushHeader.jsx
- ui/shared/PushHealthStatus.jsx
- ui/shared/PushHealthSummary.jsx
- ui/shared/RevisionList.jsx
Shows a Push Health summary if the user followed a link directly to a single-revision on `try`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1630712
> Bug 1630712 - Single try push view show Push Health Summary

- treeherder/perf/fixtures/performance_bug_templates.yaml
- ui/perfherder/alerts/StatusDropdown.jsx
Update regression templates to include context, and FAQs.
> Bug 1605352 - Add Performance FAQ to reference to regression template

- setup.cfg
- tox.ini
#6283 
Edited flake8 config for running pre-commit run --all-files alongside black
> Automation: Run all pre-commit hooks

- .gitignore
- docs/testing.md
This fixes #6337 
@Archaeopteryx done!
> Document Tox as a requirement for running tests

- tests/model/test_error_summary.py
- treeherder/model/error_summary.py
They prevent finding failure suggestions e.g. for assertions and add noise to
bugs created with bugfiler.
Test steps:
0. [Set up pulse](https://treeherder.readthedocs.io/pulseload.html).
1. Run `docker-compose up`, wait until it is done initializing
2. In another console: `docker-compose run backend celery -A treeherder worker -B -Q log_parser,log_parser_fail --concurrency 5`
We will test parsing of this log: https://treeherder.mozilla.org/#/jobs?repo=autoland&resultStatus=testfailed%2Cbusted%2Cexception%2Cretry%2Cusercancel%2Crunnable&revision=c682ecac3b25e5cd465e4050c0c53617a0f9b1f6&selectedJob=298729942
3. In a third console: `docker-compose exec backend ./manage.py ingest push -p autoland -r c682ecac3b25e5cd465e4050c0c53617a0f9b1f6`
4. Again in that console: `docker-compose exec …
> Bug 1355940 - Drop process ids like 'GECKO(123)' and 'PID 123' from lines shown in 'Failure Summary' tab

- tests/ui/job-view/Filtering_test.jsx
- ui/helpers/job.js
- ui/logviewer/App.jsx
- ui/shared/JobInfo.jsx
Sheriffs said this is not used.
> Bug 1632946 - Remove signature link for filtering in the UI

- tox.ini
@armenzg removed tests/extract from tox
> Tox: Do not ignore "tests/extract" when running tests

- treeherder/push_health/utils.py
This fixes the general exception that I had too many items to unpack in line 29.  But also helps address the specific error to find the test name.
> Bug 1634506 - Fix error loading some push data

- treeherder/intermittents_commenter/commenter.py
add support for other stockwell disabled such as disabled(fission)
> Bug 1629408 - Update IFV commenter

- ui/job-view/details/DetailsPanel.jsx
- ui/logviewer/App.jsx
Update JobDetails panel and log viewer with built from artifact for Thunderbird repos
> TinderboxPrint "Built from" URLs replacement

- treeherder/extract/extract_alerts.json
- treeherder/extract/extract_jobs.json
- treeherder/extract/extract_perf.json
Debugging was on, and was slowing down the extract to the point where it was noticed
> Bug 1636052 - ensure debugging is off

- treeherder/perf/fixtures/performance_bug_templates.yaml
This PR is adding browsertime regression template to be able to file browsertime regression bugs.
> Bug 1637932 - Add browsertime regression template

- treeherder/log_parser/failureline.py
> Declare default variable in write_failure_lines

- ui/perfherder/graphs/TestDataModal.jsx
- ui/shared/DropdownMenuItems.jsx
Removed alphabetical sorting from dropdowns
> Bug 1618578 - All perfherder dropdowns have the items in alphabetical order

- package.json
- yarn.lock
Tested login locally and everything works.
> Bug 1587145 - Upgrade taskcluster-client-web to v30

- treeherder/perf/secretary_tool.py
do I need to file a bug in bugzilla for this? Just noticed it, I figured a small fix like this doesn't require a bug
> fixed misspelling of sheriff

- treeherder/config/settings.py
- treeherder/etl/management/commands/pulse_listener.py
- treeherder/etl/management/commands/pulse_listener_pushes.py
- treeherder/etl/management/commands/pulse_listener_tasks.py
> Skip ingestion when DATABASE_URL points to remote host

- ui/job-view/headerbars/SecondaryNavBar.jsx
This fixes so it doesn't focus the search field when you click the `( + )` button.
> Bug 1617882 - Fix expand groups button focusing search field

- treeherder/config/settings.py
I duplicated some code by mistake.
> Partially revert bc3d545

- treeherder/config/settings.py
- treeherder/etl/management/commands/pulse_listener.py
- treeherder/etl/management/commands/pulse_listener_pushes.py
- treeherder/etl/management/commands/pulse_listener_tasks.py
Since it is default to True on production.
> Revert SKIP_INGESTION changes

- ui/logviewer/App.jsx
> Bug 1643104 - Enable search in Log Viewer

- package.json
- ui/job-view/pushes/FuzzyJobFinder.jsx
- yarn.lock
> Upgrade fuze version and corresponding changes

- ui/perfherder/graphs/TestDataModal.jsx
This PR is just sorting the option in platform dropdown from add new test modal
> Bug 1644347 - Perfhderder: Add new test modal - order alphabetically the platforms dropdown

- ui/infra-compare/InfraCompare.jsx
- ui/infra-compare/InfraCompareTableControls.jsx
- ui/infra-compare/helpers.js
I have changed the old filter from 3 to 5%
Also, the slider to adjust jobs has been added
> Features added to infra compare

- tests/perf/test_sheriffing_criteria/conftest.py
- tests/perf/test_sheriffing_criteria/test_common_behaviour.py
- tests/perf/test_sheriffing_criteria/test_engineer_traction.py
- tests/perf/test_sheriffing_criteria/test_fix_ratio.py
- tests/perf/test_sheriffing_criteria/test_nonblockable_session.py
- treeherder/perf/sheriffing_criteria.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1643667
More details there.
> Bug 1643667 - Fix ratio implementation

- treeherder/model/fixtures/repository.json
- ui/intermittent-failures/constants.js
Follow-up to PR #6520 to activate comm-esr78.
> Bug 1646078 - Activate comm-esr78 repository.

- treeherder/perf/management/commands/compute_criteria_formulas.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1643709
> Bug 1643709 - Provide basic management script for Bugzilla formulas

- ui/helpers/url.js
- ui/infra-compare/InfraCompare.jsx
- ui/infra-compare/InfraCompareTable.jsx
- ui/infra-compare/InfraCompareTableControls.jsx
- ui/infra-compare/InfraCompareTableRow.jsx
- ui/infra-compare/InfraCompareTableView.jsx
- ui/infra-compare/helpers.js
Found a better way to remove to chunk number and removed that one
Add a tooltip to show the job details and provide the link to treeherder job view
> Bug 1617622 - add job details and link to treeherder job view in the Infra Compare Main view

- package.json
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1651299
> Bug 1651299 - Find workaround for usual fullstack mode

- requirements/common.txt
- requirements/dev.txt
- treeherder/extract/extract_alerts.json
- treeherder/extract/extract_jobs.json
- treeherder/extract/extract_jobs.py
- treeherder/extract/extract_perf.json
The extraction is still not logging: A higher priority is needed to get through to the PaperTrail
> Increase logging for extraction code

- requirements/common.in
- requirements/common.txt
Deployment to staging is failing at the NewRelic deploy step.  This PR is attempting to fix that
> Fix staging deploy by downgrading NewRelic package

- ui/push-health/ClassificationGroup.jsx
I forgot to change the `prop` name in my last PR for this area.
> Bug 1652791 - Fix Retrigger All button in Push Health

- ui/css/treeherder-custom-styles.css
- ui/job-view/Notifications.jsx
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/redux/stores/notifications.js
- ui/models/job.js
- ui/shared/NotificationList.jsx
This makes the default be `darker-info` and adds a `CSS` class to make that color work for `Alert`.
> Bug 1652808 - Fix Notifications with darker-info

- ui/job-view/details/tabs/SimilarJobsTab.jsx
Replace reduce with the data array from text_log_errors API (missed a step usage!)
> Bug 1652869 - Fix bug in Similar Jobs panel

- ui/push-health/Health.jsx
- ui/push-health/pushhealth.css
- ui/shared/StatusProgress.jsx
Fixes #6570 
replaced the progress bar with victory chart pie graph
> Bug 1647447 - Replace Push Health progess bar with donut graph

- ui/push-health/pushhealth.css
- ui/shared/StatusProgress.jsx
1. Fixed the height to relative box to keep the center text in place
2. Add victory tooltip to show the details of each section
> Bug 1653115 - Fix Percentage text position and add tooltip for showing details of each section

- ui/logviewer/App.jsx
[Bug 1649798](https://bugzilla.mozilla.org/show_bug.cgi?id=1649798)
Remembers their choice in `localStorage`.
> Bug 1649798 - Remember whether Log Viewer was showing job info

- treeherder/etl/management/commands/ingest.py
This makes the main function a little shorter by moving chunks of code
into their own functions.
When ingesting a task we will ingest the push if missing.
> Refactor ingestion code & store push when ingesting task

- tests/etl/test_job_loader.py
- treeherder/etl/job_loader.py
- treeherder/etl/taskcluster_pulse/handler.py
I'm seeing some [releng tasks](https://firefox-ci-tc.services.mozilla.com/tasks/PnXoo7COQRCj7lsCdy69DA) for `android-components` giving trouble in prototype.
> Bug 1656036 - Polish logic to ignore ingestion of tasks

- ui/shared/BugFiler.jsx
> For the comment in descriptionStrings, use the md syntax

- tests/perf/test_sheriffing_criteria/test_criteria_tracker.py
- tests/perf/test_sheriffing_criteria/test_engineer_traction.py
- tests/perf/test_sheriffing_criteria/test_fix_ratio.py
- tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/raptor-raptor-tp6-google-mail-firefox-cold.json
- tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5n-nonmain_startup_fileio.json
- tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5n.json
- tests/sample_data/betamax_cassettes/perf_sheriffing_criteria/talos-tp5o.json
- tests/sample_data/criteria-records.csv
- treeherder/perf/management/commands/compute_criteria_formulas.py
- treeherder/perf/sheriffing_criteria/bugzilla_formulas.py
- treeherder/perf/sheriffing_criteria/criteria_tracking.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1659656
> Bug 1659656 - Provide subtest granularity

- treeherder/config/settings.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1660779
> Bug 1660779 - Prepare feature flag in settings.py

- treeherder/etl/management/commands/ingest.py
I was finding errors while trying to ingest a revision of a try repo with an error
It seems mostly that the function ingest_hg_push was to be called. 
@sarah-clements @camd
> Fix the local ingestion command

- ui/perfherder/graphs/GraphsContainer.jsx
The y domain of the graph is shown from 0 when opening a graph using "graph" button from an alert item, unlike the top graph which shows y depending on the values of the test shown.
> Bug 1652681 - Auto zoom when opening graphs view

- .pre-commit-config.yaml
- tests/perf/test_sheriffing_criteria/test_common_behaviour.py
- tests/perf/test_sheriffing_criteria/test_criteria_tracker.py
- tests/sample_data/criteria-records.csv
- treeherder/perf/management/commands/compute_criteria_formulas.py
- treeherder/perf/sheriffing_criteria/__init__.py
- treeherder/perf/sheriffing_criteria/bugzilla_formulas.py
- treeherder/perf/sheriffing_criteria/criteria_tracking.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1663604
> Bug 1663604 - Extend the Bugzilla formulas columns to include the alerts amount for each excel row

- tests/conftest.py
- tests/model/test_cycle_data.py
- treeherder/model/management/commands/cycle_data.py
- treeherder/perf/exceptions.py
- treeherder/perf/models.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1667051
> Bug 1667051 - Remove `try` perf data older than 6 weeks

- tests/etl/test_perf_data_load.py
- treeherder/etl/perf.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1671893
> Bug 1671893 - Convert int timestamp to datetime

- tests/model/test_cycle_data.py
- treeherder/model/management/commands/cycle_data.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1668511
> Bug 1668511 - Remove empty summaries

- requirements/common.txt
- requirements/dev.txt
- tests/push_health/test_compare.py
django-filter
djangorestframework
flake8
mozci
> Bump python dependencies

- treeherder/perf/fixtures/performance_bug_templates.yaml
Probably the CC'ed person in this template changed their email and it gives an error when submitting new bug.
> Bug 1671550 Fix build metrics regression template

- ui/App.jsx
- ui/job-view/App.jsx
* fix favicon path
* set repoName when currentRepo is updated
> Routing change fixes

- treeherder/config/urls.py
- treeherder/webapp/api/urls.py
I have changed all the required `urls.py` files
> Bug 1671765 - Change django.conf.urls.url() to django.urls.re_path()

- ui/css/treeherder-base.css
- ui/css/treeherder.css
- ui/index.jsx
- ui/job-view/App.jsx
- ui/logviewer/logviewer.css
- ui/push-health/pushhealth.css
This un-reverts the fix for Push Health scrolling but fixes the breakage in Log Viewer display.
> Bug 1676186 - Fix scrolling in Push Health

- .pre-commit-config.yaml
- ui/css/perf.css
- ui/perfherder/alerts/AlertHeader.jsx
- ui/perfherder/alerts/AlertTable.jsx
I have moved the `gray(header)` part out of the table with same styling as before.
> Bug 1619724 - Alert's name should not be inside the table

- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/performance_data.py
- treeherder/webapp/api/performance_serializers.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1672110
> Bug 1672110 - Do not show results for retriggers

- tests/model/test_cycle_data.py
- treeherder/model/management/commands/cycle_data.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1675594
> Bug 1675594 - cycle_data task for treeherder data is not working

- ui/perfherder/graphs/GraphsContainer.jsx
This change was motivated by feeling confused when going from the performance tab, to view the perfherder results. Frequently, my data points were not visible on the screen, and it was difficult to understand the results.
Notice how the dots are rendered off the graph to the left and right:
And after the patch, the dots are visible on the screen.
[Url for example](https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&series=autoland,2812418,1,1&timerange=2592000)
I was looking for a solution using Victory, but their charting appears to be incorrect.
For instance, view the Scatter Graph documentation: https://formidable.com/open-source/victory/docs/victory-scatter/
Add a `domainPadding={{x: 30}}` to the graph, and see how the charting is skewed.
In addition, I filed [Bug …
> Ensure that all data points are rendered completely in the perfherder graph

- tests/conftest.py
- tests/model/test_cycle_data.py
- treeherder/config/settings.py
- treeherder/model/management/commands/cycle_data.py
- treeherder/perf/data_cycling/__init__.py
- treeherder/perf/data_cycling/max_runtime.py
- treeherder/perf/data_cycling/signature_remover.py
- treeherder/perf/models.py
- treeherder/services/taskcluster.py
> Bug 1671564 - Email summary of signatures

- tests/model/test_cycle_data.py
- treeherder/model/management/commands/cycle_data.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1668543
> Bug 1668543 - Remove unupdated perf data

- ui/perfherder/Navigation.jsx
- ui/perfherder/compare/CompareSelectorView.jsx
- ui/perfherder/compare/SelectorCard.jsx
> Bug 1515681 - Perfherder Compare Warning

- tests/model/cycle_data/test_perfherder_cycling.py
- tests/model/cycle_data/test_treeherder_cycling.py
- treeherder/model/management/commands/cycle_data.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1673911
> Bug 1673911 - Remove more data from treeherder-prototype2

- tests/push_health/test_builds.py
- tests/push_health/test_linting.py
- tests/push_health/test_tests.py
- tests/ui/mock/push_health.json
- tests/ui/push-health/JobListMetric_test.jsx
- tests/ui/push-health/Job_test.jsx
- tests/ui/push-health/TestMetric_test.jsx
- treeherder/push_health/builds.py
- treeherder/push_health/classification.py
- treeherder/push_health/compare.py
- treeherder/push_health/linting.py
- treeherder/push_health/tests.py
- treeherder/push_health/utils.py
- treeherder/webapp/api/push.py
- ui/push-health/Action.jsx
- ui/push-health/Health.jsx
- ui/push-health/Job.jsx
- ui/push-health/JobListMetric.jsx
- ui/push-health/PlatformConfig.jsx
- ui/push-health/Test.jsx
- ui/push-health/TestMetric.jsx
- ui/push-health/helpers.js
This just removes the parent compare feature.  It should simplify the Mozci integration PR
> Bug 1626746 - Remove Push Health parent compare

- tests/ui/mock/infra_changelog.json
- tests/ui/perfherder/graphs-view/graphs_view_test.jsx
- treeherder/changelog/changes.py
- treeherder/webapp/api/changelog.py
- treeherder/webapp/api/performance_data.py
- ui/perfherder/constants.js
- ui/perfherder/graphs/GraphTooltip.jsx
- ui/perfherder/graphs/GraphsContainer.jsx
- ui/perfherder/graphs/GraphsView.jsx
- ui/perfherder/graphs/GraphsViewControls.jsx
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1679152
> Bug 1679152 - UI work for CI changelog

- ui/models/job.js
This seemed a little too simple.  Not sure if I'm missing something, but I don't think so.  I tested this on try and it worked great.
> Bug 1678329 - Retrigger button should not use retrigger-multiple action

- tests/push_health/test_utils.py
- treeherder/push_health/tests.py
- treeherder/push_health/utils.py
- ui/push-health/Test.jsx
This also has a couple of small fixes to some screen-debris that have bugged me for a while.
If it would be helpful, I'd be happy to chat about how I determine the problem here and some basic info surrounding this change.  I know this one is pretty trivial, but in case it's not obvious how I tracked it down, we could walk through it.  Your choice.  :)
> Bug 1678421 - Better fail heading for crashes, when possible

- ui/job-view/pushes/PushJobs.jsx
Opening this to fix the issue that had an attempted fix in #6852
> Bug 1655379 - Remove role of div wrapping job table

- tests/log_parser/test_store_failure_lines.py
- treeherder/log_parser/failureline.py
Address issue with missing manifest name
> Bug 1684931 - include manifest name in result_groups

- treeherder/model/data_cycling/removal_strategies.py
The reason why this times out is the `repository_id NOT IN <relevant repositories>` SQL construct. For each data row (out of a total of 140 million), it checks if its repository is included in a list of 5 relevant repositories.
To fix this, I simply avoided using the `NOT IN` construct. Instead of basing the query on a list of relevant repositories, I based it on individual **ir**relevant repositories.
This is based on [PR 6919](https://github.com/mozilla/treeherder/pull/6919). Its changes are in the 3rd commit.
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1682849
> Bug 1682849 - Irrelevant data removal strategy timing out

- tests/model/cycle_data/test_perfherder_cycling.py
- treeherder/model/data_cycling/signature_remover.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1685037
> Bug 1685037 - Email dhunt@mozilla.com is denylisted

- requirements/dev.txt
The new pip-compile changes the formatting a bit.
This is a no-op change.
> Regenerate requirements file with latest pip-tools

- docs/data_cycling.md
- docs/infrastructure/architecture.md
- mkdocs.yml
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1683042
> Bug 1683042 - Document Perfherder's data retention policy

- treeherder/push_health/compare.py
* For cases where the parent push is not found in mozci, handle the raised exception (a note in the UI will specify that the parent push wasn't found).
> Push Health - add try except block to get_commit_history

- tests/ui/perfherder/graphs-view/timerange_dropdown_test.jsx
- ui/perfherder/graphs/GraphsView.jsx
- ui/perfherder/graphs/GraphsViewControls.jsx
- ui/perfherder/graphs/TestDataModal.jsx
- ui/perfherder/graphs/TimeRangeDropdown.jsx
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1604871
> Bug 1604871 - Unable to add data to graph when there are no recent results

- tests/webapp/api/test_performance_alertsummary_api.py
- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/performance_data.py
- ui/perfherder/graphs/GraphTooltip.jsx
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1680433
> Bug 1680433 - Wrong pushlog link in alert dropdown

- CODEOWNERS
* Add job-view and change all to treeherder-admins except for Perfherder directory
> Update codeowners coverage

- package.json
- yarn.lock
Update Reactstrap version from 8.3.2 to 8.5.1.
> Update Reactstrap version

- tests/ui/helpers/display_test.js
- ui/helpers/constants.js
- ui/helpers/display.js
- ui/perfherder/graphs/GraphTooltip.jsx
- ui/perfherder/helpers.js
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1676498
> Bug 1676498 - Dates appear in the future in perfherder

- ui/helpers/constants.js
- ui/perfherder/graphs/TestDataModal.jsx
[Bug 1656195 - Repository hyperlink from Graphs view does not show related tests from other repositories](https://bugzilla.mozilla.org/show_bug.cgi?id=1656195)
> Bug 1656195 - Repository hyperlink from Graphs view does not show related tests from other repositories

- ui/perfherder/graphs/TestDataModal.jsx
Steps to reproduce can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1694107
Also, when reviewing please take a look at @ionutgoldan's comment.
> Bug 1694107 - Time range dropdown not synced with Graphs view

- treeherder/perf/fixtures/performance_framework.json
- treeherder/perf/management/commands/remove_vcs_data.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1692409
> Bug 1692409 - Remove vcs data

- tests/perfalert/test_auto_perf_sheriffing/conftest.py
- tests/perfalert/test_auto_perf_sheriffing/test_perf_sheriff_bot.py
- tests/perfalert/test_auto_perf_sheriffing/test_secretary_tool.py
- treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1697146
> Bug 1697146 - Mark reports for backfill in perfsheriffbot

- treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
- treeherder/perf/auto_perf_sheriffing/secretary_tool.py
For monitoring purposes, we need the perfsheriff bot to log more.
Also, only for monitoring purposes, I added an alternative strategy for marking reports for backfill that only logs the potential results.
> Bug 1699296 - Log more for perfsheriff bot

- tests/etl/test_perf_data_adapters.py
- tests/test_utils.py
- treeherder/etl/perf.py
- treeherder/model/models.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1570906
> Bug 1570906 - Performance alert created from a [tier 3] job

- ui/perfherder/alerts/AlertHeader.jsx
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1700376
> Bug 1700376 - Use consistent date time format

- treeherder/etl/management/commands/ingest.py
- treeherder/etl/taskcluster_pulse/handler.py
The immediate issue here is that we're not passing `session` to `handleTaskException` -- which causes runtime exceptions, and that code not to run. I also noticed some warnings about sessions not being closed, so I switched to context manager instantiation for sessions, to fix that.
> bug 1700609: Fix unclosed session errors & pass session to exception handler

- treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
- treeherder/perf/management/commands/perf_sheriff.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1700327
> Bug 1700327 - Properly notify when backfill bot goes to sleep

- treeherder/services/taskcluster.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1701692
> Bug 1701692 - Fix backfill failure

- tests/model/cycle_data/test_perfherder_cycling.py
- treeherder/model/data_cycling/cyclers.py
- treeherder/model/data_cycling/signature_remover.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1700606
> Bug 1700606 - Expire garbage backfill reports

- tests/perfalert/test_auto_perf_sheriffing/test_perf_sheriff_bot.py
- tests/perfalert/test_auto_perf_sheriffing/test_secretary_tool.py
- treeherder/model/models.py
- treeherder/perf/auto_perf_sheriffing/outcome_checker.py
- treeherder/perf/auto_perf_sheriffing/perf_sheriff_bot.py
- treeherder/perf/auto_perf_sheriffing/secretary_tool.py
- treeherder/perf/email.py
- treeherder/perf/models.py
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1700946
> Bug 1700946 - Update BackfillRecord after soft launch

- treeherder/perf/auto_perf_sherrifing/sherlock.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1703024
> Bug 1703024 - More debug logs for Sherlock' s email notification

- tests/perf/auto_perf_sheriffing/conftest.py
- tests/perf/auto_perf_sheriffing/test_sherlock.py
- treeherder/config/settings.py
- treeherder/perf/auto_perf_sheriffing/secretary.py
- treeherder/perf/auto_perf_sheriffing/sherlock.py
- treeherder/perf/models.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1703507
> Bug 1703507 - Enable Sherlock on Windows

- tests/e2e/test_job_ingestion.py
- treeherder/etl/artifact.py
- treeherder/model/models.py
Until the query issue detected in Bugscache.search can be investigated, searching
and cache bug suggestions is disabled during task ingestion
> Bug 1704311 - Temporarily disable storing of bug suggestions during ingestion

- tests/model/test_bugscache.py
- treeherder/model/models.py
Some cleanup from today's emergency fix (#7100). Comments inline.
> Bugscache cleanup

- tests/perf/auto_perf_sheriffing/test_sherlock.py
- treeherder/perf/auto_perf_sheriffing/backfill_reports.py
- treeherder/perf/auto_perf_sheriffing/sherlock.py
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1705366
> Bug 1705366 - Sherlock targets incorrect alerts

- requirements/common.txt
Reverts mozilla/treeherder#7130
> Revert "Update version to version 2.0.2"

- ui/perfherder/compare/CompareTableView.jsx
- ui/perfherder/compare/CompareView.jsx
To test the changes: 
Go to http://localhost:5000/perfherder/compare?originalProject=try&originalRevision=6c12c64c9eaae542b2d4dc9a103ce92326197b4f&newProject=try&newRevision=14360458232db1000221c82831d01c8ad12cea25&framework=13 , the page should load in about 11 seconds or so.
> Bug 1706469 - Perfherder comparison just hangs

- ui/perfherder/compare/CompareSubtestsView.jsx
> Bug 1716542 - Update Subtests View to support documentation links

- treeherder/model/fixtures/repository.json
To be landed after the default branch in the repo has changed tomorrow.
> Update fenix branch

- treeherder/perf/management/commands/perf_sheriff.py
This adds support for devtools framework on Sherlock
> Enable auto-backfills for devtools framework

- tests/ui/mock/alert_summaries.json
- tests/ui/perfherder/alerts-view/alerts_test.jsx
- ui/perfherder/alerts/AlertTable.jsx
- ui/perfherder/alerts/AlertTableRow.jsx
https://mozilla-hub.atlassian.net/browse/FXP-1559
Change sorting for important alerts to appear first and change the looks of it
> FXP-1559 - Make important alerts more visible

- ui/perfherder/perf-helpers/perfdocs.js
Original link to the issue: https://treeherder.mozilla.org/perfherder/compare?originalProject=try&originalRevision=2127cc729d5cfe518b85a400ab5a9bd6e219ba95&newProject=try&newRevision=2406f69be8f65c5fe2702adca7a88c149825ffb0&framework=1&page=1
Link to test changes locally with "yarn start": http://localhost:5000/perfherder/compare?originalProject=try&originalRevision=2127cc729d5cfe518b85a400ab5a9bd6e219ba95&newProject=try&newRevision=2406f69be8f65c5fe2702adca7a88c149825ffb0&framework=1&page=1
> Bug 1729057 - Treat case when suite is undefined

- treeherder/intermittents_commenter/commenter.py
Until now, the intermittent failures commenter would often drop all stockwell
tags from the whiteboard when the bug got updated. Information got lost, e.g.
the test having already been disabled (at least partially on 1+ platforms).
> Bug 1735145 - only drop relevant stockwell tags from a bugs whiteboard

- tests/ui/helpers/helpers_test.js
- ui/perfherder/compare/CompareTableView.jsx
- ui/perfherder/perf-helpers/helpers.js
Link for testing http://localhost:5000/perfherder/compare?originalProject=try&originalRevision=ef9e0001bb2a1b8a28da44b6529c263eadef1bf1&newProject=try&newRevision=50daacdf07d304f54ff98b6a729ed602e4770d57&framework=1&page=1
> Bug 1741902 - Results missing from comparison for pdfpaint

- tests/ui/job-view/SecondaryNavBar_test.jsx
- ui/css/treeherder-navbar.css
- ui/job-view/headerbars/WatchedRepo.jsx
Changed the watched repo buttons from `<button>` to `<a>`
there's a hack for style, that's required to make `<a>` and drop-down button's `<button>` vertically aligned.
> Bug 1743545 - Make watched repo buttons links.

- package.json
- yarn.lock
Reverts mozilla/treeherder#6989
> Revert "Update dependency js-yaml to v4"

- package.json
- ui/job-view/CustomJobActions.jsx
- yarn.lock
A fix to #7361 since there was a breaking change I missed and it caused problems in the UI.
> Update to yaml4

- package.json
- yarn.lock
Reverts mozilla/treeherder#7310 due to https://bugzilla.mozilla.org/show_bug.cgi?id=1755334
> Revert "Update dependency webpack-dev-server to v4"

- tests/ui/perfherder/alerts-view/select_alert_framework_test.jsx
- ui/perfherder/alerts/AlertsViewControls.jsx
- ui/perfherder/perf-helpers/sort.js
- ui/shared/DropdownMenuItems.jsx
- ui/shared/FilterControls.jsx
I added a fix for https://mozilla-hub.atlassian.net/browse/FXP-1861
> Bug 1756800 - Grouped sheriffed frameworks in dropdown and sort frameworks

- ui/intermittent-failures/DateRangePicker.jsx
Please be gentle this is my first contribution and let me know if anything needs changed or is missing.
Thanks!
> Bug 1619739 - Fix accessibility wording for DateRangePicker

- ui/helpers/url.js
- ui/perfherder/alerts/AlertTableRow.jsx
- ui/perfherder/perf-helpers/helpers.js
- ui/perfherder/perf-helpers/textualSummary.js
This PR adds link to the graph of each alert item from the each row of ratio column in comment 0.
> Bug 1766972 - Add graph link to the Ratio column of the regression template

- docker/entrypoint_prod.sh
> Celery 5 upgrade: pass application name first in docker entrypoint script

- tests/webapp/api/test_performance_data_api.py
- treeherder/webapp/api/perfcompare_utils.py
- treeherder/webapp/api/performance_data.py
- treeherder/webapp/api/performance_serializers.py
Example of where this fields are used -> https://github.com/mozilla/treeherder/blob/master/ui/perfherder/compare/CompareTableRow.jsx#L121
> Add logic from method getClassName

- requirements/common.in
- requirements/common.txt
- tests/push_health/test_compare.py
This reverts commit adb05a9eb2088697a07473b6e9ae7e698e88a219.
> Revert "update redis to latest for security release"

- treeherder/model/fixtures/repository.json
Adding firefox-ios repo to support perfherder ingest of ios performance tests.
> add firefox-ios repo

- treeherder/utils/queryset.py
Fixed - added periods to complete commented sentences on lines 3, 44.
> Bug 1836152 - Added 2 periods to complete commented sentences

- ui/push-health/Usage.jsx
Satisfies bug 1836147 - _Fixes comment to remove extra capitalization_
> Bug 1836147 - Fixes comment to remove extra capitalization

- .pre-commit-config.yaml
- misc/compare_tasks.py
- ui/push-health/Usage.jsx
Bug-1836153 - Changed python version from 3.9 -> 3. Changed line 114 in compare_tasks.py from 'th_instancely' to "instance"
> Bug 1836153 - Changed line 114 in compare_tasks.py 

- treeherder/webapp/api/groups.py
added if conditional to ensure end and start date are 1 day apart
> Bug 1801239 - startdate and enddate are 1 day apart

- ui/job-view/headerbars/FiltersMenu.jsx
A link in Filters menu to hide code review pushes.
> Bug 1846548 - Add link to filter out code review pushes to Filters menu.

- treeherder/model/error_summary.py
> Allow comm-central to have NEW failures

- tests/ui/mock/alert_summaries.json
- tests/ui/perfherder/alerts-view/alerts_test.jsx
- ui/perfherder/alerts/AlertTable.jsx
- ui/perfherder/alerts/AlertTableRow.jsx
> Add tests for the Debug Tools column in alerts view

- treeherder/model/fixtures/repository.json
This is probably not going to work because of https://bugzilla.mozilla.org/show_bug.cgi?id=1834790, but I'd like to give it a shot at least, and get us one step closer to this repo in treeherder.
> Add application-services to treeherder

- treeherder/config/settings.py
Fixes the infinite loading + 502 error when reaching the jobs list endpoint from a browser (e.g. https://treeherder.mozilla.org/api/jobs/?push_id=1311611)
The error is related to `django-filter` template rendering in HTML mode, because of the auto-generated filter form (attached image below).
For example replacing `{{ filter.form.as_p }}` by `{{ filter }}` in `django_filters/templates/django_filters/rest_framework/form.html` prevent the infinite loading error (and prevent django-filter to render the form with filters).
* Endpoint : `http://localhost:8000/api/jobs/?push_id=1262311`
* Command : `DATABASE_URL=psql://postgres:postgres@straton.vpn:5432/treeherder TREEHERDER_DEBUG=true manage.py runserver`
```
class JobFilter(django_filters.FilterSet):
from django_filters import NumberFilter …
```
> Disable the rest framework browsable HTML API

- treeherder/model/fixtures/repository.json
- treeherder/webapp/api/utils.py
For Thunderbird monthly releases.
> Bug 1861474 - Add comm-release to Treeherder.

- treeherder/webapp/api/groups.py
- treeherder/webapp/api/serializers.py
The request for data from 2023-10-15 to 2023-10-16 times out and Valentin benchmarked the old code as completing the request.
This reverts commit d2388c172eb97ed7da295e163284e219b1cd93ba.
> Revert "Optimize summarygroup endpoint (#7812)"

- ui/css/treeherder-details-panel.css
for bugzilla.mozilla.org/show_bug.cgi?id=1683668
> Bug 1683668 - Show scrollbar in the job info panel.

- .git-blame-ignore-revs
Refs https://github.com/mozilla/treeherder/pull/7900#issuecomment-1909909826
> Bug 1823654 - Ignore Double quotes commit in git blame

- ui/job-view/pushes/JobButton.jsx
for https://bugzilla.mozilla.org/show_bug.cgi?id=1864125
> Bug 1864125 - Dynamically update intermittent icon when other sucessful job appears.

- ui/perfherder/alerts/AlertActionPanel.jsx
The acknowledge functionality on Alerts View is not working properly because of this call.
> Removed call to update the status summary

- pyproject.toml
updated-dependencies:
- dependency-name: mkdocs-material dependency-type: direct:production update-type: version-update:semver-patch ...
> Bump mkdocs-material from 9.5.22 to 9.5.24

- treeherder/model/fixtures/repository.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1899403
> Mark cypress as active again

- schemas/performance-artifact.json
Update performance-artifact.json to include focus
> Bug 1932219 - Add focus to performance-artifact,json

- ui/helpers/url.js
- ui/perfherder/alerts/AlertTableRow.jsx
- ui/perfherder/graphs/GraphTooltip.jsx
- ui/perfherder/graphs/TableView.jsx
Fulfills https://mozilla-hub.atlassian.net/jira/software/c/projects/PCF/boards/629 and https://mozilla-hub.atlassian.net/browse/PCF-513
> PCF-514 Update the link to the subtests view in the Graphs View and Alerts View

- ui/perfherder/alerts/AlertHeader.jsx
- ui/perfherder/alerts/AlertTable.jsx
FXP-3715 Add mechanism to edit culprit revision
> Front End Changes for Edit Culprit Revision

- tests/intermittents_commenter/expected_comment.text
- tests/intermittents_commenter/expected_comment_with_5_failures.text
- treeherder/intermittents_commenter/comment.template
- treeherder/intermittents_commenter/commenter.py
Using dataclasses to limit the use of dictionaries.
> Intermittent commenter refacto

- ui/perfherder/alerts/StatusDropdown.jsx
Add a check for the user's isStaff flag before allowing filing bugs.
> Bug 1942662 - Add a check for filing bugs in the alerts view.

- tests/ui/job-view/AppHistory_test.jsx
- tests/ui/job-view/AppRoutes_test.jsx
- tests/ui/job-view/App_test.jsx
- tests/ui/logviewer/Logviewer_test.jsx
- ui/App.jsx
- ui/index.html
- ui/job-view/App.jsx
Bookmarks did not update the favicon if a Treeherder page got visited. Additional investigation also showed switching between apps didn't update the favicon except for push health with sets an additional <link rel="shortcut icon" /> element.
> Bug 1946747 - have a favicon icon on initial load and change it when user switches between apps

- tests/log_parser/test_tasks.py
- tests/model/test_bugscache.py
- tests/ui/job-view/details/PinBoard_test.jsx
- tests/ui/mock/bug_suggestions.json
- tests/ui/shared/FailureSummaryTab_test.jsx
- tests/webapp/api/test_bug_job_map_api.py
- treeherder/config/settings.py
- treeherder/model/models.py
- treeherder/webapp/api/bug.py
- ui/job-view/details/PinBoard.jsx
- ui/job-view/redux/stores/pinnedJobs.js
- ui/shared/tabs/failureSummary/BugListItem.jsx
- ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
~~Based on #8467~~ (merged)
Implies few UI changes (but internal issues wont be shown yet):
>  Bug 1923923 - Support internal IDs during classification 

- treeherder/model/migrations/0036_bugjobmap_internal_bug_refs.py
Migration of production failed. Data about bugs can be missing from Bugscache if they are wrong or restricted.
> Bug 1923923 - create bugs mentioned in BugJobMap in Bugscache table to fix migration

- tests/ui/job-view/details/PinBoard_test.jsx
- tests/webapp/api/test_bug_job_map_api.py
- treeherder/webapp/api/bug.py
- treeherder/webapp/api/serializers.py
- ui/job-view/details/PinBoard.jsx
- ui/job-view/details/tabs/AnnotationsTab.jsx
- ui/models/bugJobMap.js
Refs. https://bugzilla.mozilla.org/show_bug.cgi?id=1923923#c4
* **Save** button for classification is disabled because of using Set.size (we use an Array since #8477)
* Support deletion of issues referenced from internal or Bugzilla ID
> Bug 1923923 - Fix remaining pinned bugs issues

- treeherder/model/migrations/0039_fix_bugscache_autoincrement.py
Ref. https://github.com/mozilla/treeherder/pull/8517#issuecomment-2692939714
> Bug 1923923 - Correctly initialize Bugscache pk sequence value

- tests/etl/test_classification_loader.py
- tests/etl/test_load_artifacts.py
- tests/log_parser/test_tasks.py
- treeherder/model/error_summary.py
- treeherder/webapp/api/note.py
This reverts commit d7bb1b40aee891c707658177983d4921da6eacf3.
> re-enable new failure lines cache

- treeherder/webapp/api/performance_data.py
This fixes an issue that came from the submit time changes.
> Bug 1956786 - Properly separate fields to gather in perf summary query.

- tests/ui/job-view/bugfiler_test.jsx
- ui/helpers/job.js
- ui/job-view/details/summary/ActionBar.jsx
- ui/job-view/details/tabs/TabsPanel.jsx
- ui/push-health/details/DetailsPanel.jsx
- ui/shared/BugFiler.jsx
- ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
This PR is based on https://github.com/mozilla/treeherder/pull/8596
> Confirm checkbox

- ui/helpers/url.js
- ui/job-view/App.jsx
- ui/job-view/pushes/PushList.jsx
- ui/job-view/pushes/PushLoadErrors.jsx
- ui/job-view/redux/stores/pushes.js
This patch adds a new parameter for lando commit IDs (landoCommitID), and some code to convert that lando commit ID into a revision that can be used as a normal revision.
> Bug 1964784 - Add a new parameter for lando IDs, and convert it to a revision.

- ui/intermittent-failures/MainView.jsx
> feat: add urlparams for filters in intermittent failure view

- tests/intermittents_commenter/expected_comment.text
- tests/intermittents_commenter/expected_comment_with_5_failures.text
- treeherder/intermittents_commenter/commenter.py
this should allow us to comment as normal and we can debug existing code
> Disable test_runs in intermittent commenter.

- .circleci/config.yml
Sync the `.circleci/config.yml` file with the one in the `master` branch.
> feat: pushing to GCP GAR

- treeherder/perf/auto_perf_sheriffing/sherlock.py
This patch adds a few additional telemetry probes to alert on.
> Add additional telemetry probes to alert on.
