treeherder/etl/buildapi.py, treeherder/etl/management/commands/ingest_push.py, treeherder/etl/pushlog.py, treeherder/model/derived/jobs.py, treeherder/model/sql/objectstore.json, treeherder/model/tasks.py
=> Bug 1110463 - Add a manage command to just ingest data for a single push

tests/etl/test_tbpl.py, treeherder/etl/tbpl.py, treeherder/settings/base.py, treeherder/settings/local.sample.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1069502
=> Bug 1069502 - Submit to elasticsearch

puppet/files/treeherder/local.production.py
There was a minor problem with the patch before which aki noticed, here's a fix.
=> Bug 1117856 - Fix error in logging configuration 

docs/installation.rst
This separates out the steps required for running the tests, from those for setting up a local instance. The running ingestion tasks step now clearly states the need for the API server to be running already. The log parser compile step is moved inline since it was otherwise easy to omit.
=> Bug 1088216 - docs: make the installation instructions easier to follow

requirements/pure.txt, vendor/datasource/bases/RDBSHub.py, vendor/datasource/data_sources.json, vendor/datasource/hubs/MySQL.py
To pick up the new require_host_type config option:
https://github.com/jeads/datasource/pull/22
Also includes:
https://github.com/jeads/datasource/pull/17
=> Bug 1125585 - Update datasource to fab643e0d5

tests/e2e/test_jobs_loaded.py, tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_resultset_api.py, treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json, treeherder/webapp/api/jobs.py, treeherder/webapp/api/resultset.py
Tests are passing. This is the service part of mozilla/treeherder-ui#340
=> Bug 1097090 - jobs endpoint refactoring

deployment/update/update.py
The @hostgroups decorator was causing us to call restart-jobs multiple
times (once for each host within a host group), when we only want to
call it once per group of hosts.
Abstracting the restart-jobs call to its own method also means the IRC
bot will output "restart_jobs complete" after each restart-jobs call,
making the progress through the deployment task clearer.
=> Bug 1130408 - deploy: Only call restart-jobs once per hostgroup

treeherder/etl/buildapi.py
In bug 1093743, the handling of request times was simplified (since we now use a single value from request_times rather than all of them). Unfortunately in the process, this broke the handling of cases where request_times does not exist, and we have to fall back to requesttime. The latter is an int, whereas the former a dict, so in addition to fixing the exception, we now no longer try to store both in the same variable, to avoid future confusion.
=> Bug 1133455 - Fix the exception when falling back to requesttimes

schemas/job-action-message.json, tests/conftest.py, tests/etl/test_pushlog.py, tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_resultset_api.py, treeherder/model/derived/base.py, treeherder/model/derived/jobs.py, treeherder/model/derived/refdata.py, treeherder/model/exchanges.py, treeherder/model/pulse_publisher.py, treeherder/model/sql/reference.json, treeherder/model/tasks.py, treeherder/settings/base.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/resultset.py
Handles sending of pulse messages on retrigger/cancel (including cancel all) also fixes various issues I found in older pulse emitting code (fixed + tests)
=> Bug 1113281 - Send event of actions over pulse (retrigger/cancel)

.dockerignore, Dockerfile, docker/etc/profile.d/treeherder.sh, docker/generate_test_credentials.py, docker/gunicorn.sh, docker/init.sh, fig.yml, treeherder/etl/management/commands/export_project_credentials.py, treeherder/settings/base.py
Note- I am not sure when I have time to finish this up for real... I deployed an image (lightsofapollo/treeherder) for testing and it is working really well for my TC related work... This is somewhat janky and aimed more at third party developers though it could be cleaned up.
=> Docker + Fig setup

treeherder/model/sql/jobs.json
After removing job classification , updated failure classification id of job to 1, making it an unclassified job .
review: @camd 
feedback : @wlach
=> Bug 1137675 - updated sql query to unclassify a classified job.

.travis.yml, tests/conftest.py
See the individual commit messages for explanations :-)
=> Speed up the Travis run

tests/etl/test_perf_data_adapters.py, treeherder/etl/perf_data_adapters.py, treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json, treeherder/model/sql/template_schema/project_jobs_1.sql.tmpl
* Use a text column instead of varchar for storing series property (since the
subtest signatures can be quite long). Also stop indexing it.
* Update query for getting series signatures to not use a coallation (which
also has a size limit by default)
=>  	Bug 1108832 - Fixes for summary series support

Dockerfile, docs/common_tasks.rst, docs/installation.rst, setup.py
This fixes Bugzilla bug [1137164](https://bugzilla.mozilla.org/show_bug.cgi?id=1137164).
In addition to the docs I also modified Dockerfile, but didn't touch .travis.yml, treeherder.pp or update.py. Not sure if that is correct, but my initial best guess.
Caveat I haven't tested all those related changes, so I defer to @edmorley  on his wisdom :)
Some additional trailing white space removed from installation.rst.
Adding Ed for review.
=> Bug 1137164 - Add a shebang to setup.py

treeherder/webapp/api/utils.py
Unused as of the refactor in bug 1097090.
=> Bug 1144608 - Remove dead code in webapp/api/utils.py

tests/log_parser/test_tasks.py, treeherder/etl/perf_data_adapters.py, treeherder/model/derived/jobs.py
Old uncompressed blobs will continue to work transparently
=>  	Bug 1142648 - Zlib compress new job_artifact, performance_artifact blobs

treeherder/log_parser/utils.py
If attempting to fetch the log from the provided URL results in a 404, mark the parse_status as failed but do not generate an exception. Whilst missing logs are not ideal, they are not an app error, nor something is likely to change over time (vs say an HTTP 500 from ftp.mozilla.org).
=> Bug 1155647 - Don't generate log parser exceptions if the log URL 404s

deployment/update/update.py
I took the update.py script in the mozillians repo as an example. I cut out the handling of the description and the changeset. I'll keep the bug open to make sure we add it once we have a unified repo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-service/469)
=> Bug 1076737 - notify newrelic on deployment

bin/run_celery_worker_log_parser
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/476)
=>  	Bug 1156746 - Bump the number of concurrent log processing workers

requirements/prod.txt
v2.44.0.36 (11th Feb) -> v2.50.0.39 (6th April)
Brings improvements to SQL reporting, Django 1.8 support, improved perf/resource usage in some cases.
For more info see:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/485)
=> Bug 1158212 - Update New Relic Python agent to v2.50.0.39

requirements/common.txt
Changes:
https://github.com/cython/cython/blob/master/CHANGES.rst
https://github.com/cython/cython/compare/0.19.2...0.22
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/488)
=> Bug 1158395 - Update Cython to v0.22

requirements/common.txt
Changes:
https://github.com/simplejson/simplejson/compare/v3.3.0...v3.6.5
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/486)
=> Bug 1158371 - Update simplejson to v3.6.5

puppet/manifests/classes/python.pp, requirements/dev.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/495)
=> Bug 1159250 - Update a few dev/testing dependencies

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/494)
=> Bug 1159334 - Add the mozilla-esr38 and comm-esr38 repositories

treeherder/etl/th_publisher.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/498)
=> Bug 1159782 - fix Job ingestion error

tests/client/test_treeherder_client.py, treeherder/client/setup.py, treeherder/client/thclient/client.py, treeherder/etl/mixins.py
"This time, with feeling...  and timeouts..."
This PR re-fixes [Bug 1144417](https://bugzilla.mozilla.org/show_bug.cgi?id=1144417)
This is the second attempt with ``requests`` library; now using the timeout param.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/506)
=> Client requests take 2

treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json, treeherder/model/sql/objectstore.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/515)
=> Bug 1161974 - Remove deadcode from jobs.py

treeherder/model/derived/jobs.py, treeherder/webapp/api/performance_data.py
It can get quite big so this is helpful
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/524)
=> Bug 1162578 - Use etag caching for performance data

README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/531)
=> Bug 1164023 - Remove references to the decommissioned treeherder-dev

treeherder/model/management/commands/run_sql.py
Otherwise any changes are discarded. The connection is also now closed properly after we're done with it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/534)
=> Bug 1164824 - run_sql: Commit the transaction after executing it

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/538)
=> Bug 1164021 - Disable the mozilla-b2g30_v1_4 repo

deployment/update/update.py, treeherder/etl/classification_mirroring.py, treeherder/etl/mixins.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/537)
=> Bug 1160873 - Add timeout to requests that are missing them

treeherder/log_parser/parsers.pyx
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/532)
=> Bug 1164439 - parse ESLint 'compact' reporting output

tests/conftest.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/552)
=> Bug 1080760 - Missing fixure added to fix tests

docs/installation.rst
Give some extra details related to Talos data, among other things
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/550)
=>  	Bug 1167364 - Expand documentation on ingesting a single push

ui/plugins/failure_summary/controller.js
We were leaving orphaned "timeout loops" around as you switched jobs.  This fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/553)
=> Bug 1167419 - fix constant reloads on failure summary tab

docs/common_tasks.rst
@wlach - as promised.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/559)
=> Bug 1167913 - Add Oauth credential lookup and export process to RTD

treeherder/model/utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/565)
=>  	Bug 1168615 - Log information about MySQL exceptions/errors when they occur

requirements/common.txt, tests/client/test_perfherder_client.py, treeherder/client/thclient/__init__.py, treeherder/client/thclient/client.py, treeherder/client/thclient/perfherder.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/import_perf_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/536)
=>  	Bug 1163138 - Add a management command to allow importing perf data

ui/js/directives/top_nav_bar.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/566)
=> Bug 1060313 - Fix the repo menu links when using web-server.js

treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/569)
=>  	Bug 1168989 - Sort json used for series summary cache key

ui/js/controllers/jobs.js, ui/js/controllers/main.js, ui/js/directives/clonejobs.js, ui/js/models/resultsets_store.js, ui/js/providers.js, ui/js/services/jobfilters.js
Remove code for toggling all jobs hidden/shown and per-resultset result filters.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/578)
=> Bug 1169481 - Dead clonejobs code

docs/ui/installation.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/579)
=>  	Bug 1139998 - Make it more clear in docs how to set things up to run ui tests

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/543)
=> Bug 1164491 - Make resultset and jobs api queryable in th-client.

docs/common_tasks.rst, docs/installation.rst
After updating the Vagrant image, the vagrant bash prompt has changed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/595)
=> Bug 1144804 - Docs: Update the Vagrant examples with the new bash prompt

tests/e2e/test_client_job_ingestion.py, treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/601)
=> Bug 1170636 - Fix log name typo in parse_status conditional

ui/index.html, ui/js/controllers/logviewer.js, ui/js/treeherder_app.js, ui/logviewer.html, ui/plugins/controller.js, ui/plugins/job_details/main.html, ui/plugins/talos/main.html, ui/vendor/toArrayFilter.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/581)
=>  	Bug 1160082 - Minor sorting issues with angular 1.4 upgrade

ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/606)
=> Bug 1170839 - Disable retrigger/cancel requests to buildapi on the ash branch

puppet/files/treeherder/.bash_aliases
missed this error when I checked the code in originally...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/619)
=> Bug 1173192 - thresetall function in vagrant has errors

ui/js/compareperf.js, ui/js/graphs.js, ui/js/perf.js, ui/js/perfapp.js, ui/partials/perf/comparechooserctrl.html
Not much to add, just some quick gratification :)
FF Nightly **41.0a1 (2015-06-10)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/622)
=> Bug 1173462 - Remove trailing whitespace from perf code

ui/partials/perf/comparechooserctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/626)
=> Bug 1174231 - Compare chooser shows red when validation has not failed

treeherder/client/thclient/perfherder.py, treeherder/settings/base.py, ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/636)
=>  	Bug 1149642 - Store one year's worth of performance data

puppet/files/apache/treeherder.conf, puppet/manifests/vagrant.pp, requirements/common.txt, treeherder/settings/base.py, treeherder/settings/local.sample.py, treeherder/webapp/urls.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/634)
=>  	Bug 1167349 - Turn swagger back on in production and update to latest

treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/628)
=>  	Bug 1174216 - Don't store series in reverse order

requirements/dev.txt
https://gitlab.com/pycqa/flake8/blob/master/CHANGES.rst
https://gitlab.com/pycqa/flake8/compare/2.4.0...2.4.1
https://github.com/pyflakes/pyflakes/blob/master/NEWS.txt
https://github.com/pyflakes/pyflakes/compare/0.8.1...0.9.2
https://github.com/flintwork/mccabe#changes
https://github.com/flintwork/mccabe/compare/0.3...0.3.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/643)
=> Bug 1175750 - Update to flake8 v2.4.1, Pyflakes v0.9.2 and McCabe v0.3.1

requirements/dev.txt
https://github.com/seb-m/pyinotify/wiki/Recent-Developments
https://github.com/seb-m/pyinotify/compare/0.9.5...0.9.6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/649)
=> Bug 1175848 - Update pyinotify to v0.9.6

requirements/dev.txt
https://github.com/django-extensions/django-extensions/blob/master/CHANGELOG.md
https://github.com/django-extensions/django-extensions/compare/1.5.2...1.5.5
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/651)
=> Bug 1175851 - Update django-extensions to v1.5.5

requirements/dev.txt
https://github.com/getsentry/responses/blob/master/CHANGES
https://github.com/getsentry/responses/compare/0.3.0...0.4.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/650)
=> Bug 1175854 - Update responses to v0.4.0

tests/client/data/job_data.json, tests/client/data/resultset_data.json, tests/sample_data/artifacts/job_artifact.json, tests/sample_data/artifacts/structured_log_artifact.json, tests/sample_data/logs/mozilla-central_mountainlion-debug_test-mochitest-2-bm80-tests1-macosx-build93.jobartifact.json, tests/sample_data/logs/mozilla-central_mountainlion_test-mochitest-2-bm77-tests1-macosx-build141.jobartifact.json, tests/sample_data/logs/mozilla-central_mountainlion_test-mochitest-2-bm80-tests1-macosx-build138.jobartifact.json, tests/sample_data/logs/mozilla-esr17_xp_test_pgo-mochitest-browser-chrome-bm74-tests1-windows-build12.jobartifact.json, tests/sample_data/logs/mozilla-inbound_ubuntu64_vm-debug_test-mochitest-other-bm53-tests1-linux-build122.jobartifact.json, tests/sample_data/logs/ux_ubuntu32_vm_test-jetpack-bm67-tests1-linux-build16.jobartifact.json, tests/sample_data/resultset_data.json, tests/ui/mock/job_group_list.json, tests/ui/mock/job_type_list.json
To make it easier to find the relevant lines when updating tests, as well as clearer when reviewing the subsequent diffs.
I've just used Sublime Text 3 with the [Pretty JSON](https://packagecontrol.io/packages/Pretty%20JSON) package.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/652)
=> Bug 1175882 - Prettify the json sample data

requirements/common.txt
http://docs.gunicorn.org/en/latest/2013-news.html
http://docs.gunicorn.org/en/latest/2014-news.html
http://docs.gunicorn.org/en/latest/news.html
https://github.com/benoitc/gunicorn/compare/17.5...19.3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/644)
=> Bug 1175478 - Update gunicorn to v19.3.0

tests/etl/test_common.py
Just a minor tweak I saw in passing while investigating something else on IRC.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/642)
=> No bug - Fix etl test_common comment

docs/submitting_data.rst, tests/e2e/test_client_job_ingestion.py, treeherder/client/thclient/client.py, treeherder/model/derived/jobs.py
Allow the client to specify what tier a job is in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/646)
=> Set tier with client

requirements/common.txt
https://github.com/mozilla/gecko-dev/commits/master/testing/mozbase/mozlog
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/647)
=> Bug 1175842 - Update mozlog to v2.11

treeherder/client/thclient/client.py
r? @wlach
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/657)
=> Bug 1175953 - th-client should be able to fetch ARTIFACT endpoint data.

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/658)
=>  	Bug 1176022 - Make treeherder client data retrieval raise exception on error

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/659)
=>  	Bug 1176023 - Add a method to treeherder client for getting option collection hash

ui/js/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/661)
=> Fix graphs

treeherder/client/setup.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/667)
=> Bug 1176498 - Fix treeherder client description on pypi

tests/webapp/api/test_resultset_api.py, treeherder/webapp/api/resultset.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/669)
=> Bug 1177460 - add resultset status endpoint

requirements/prod.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/665)
=> Bug 1176413 - Update to New Relic Python agent v2.52.0.40

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/672)
=>  	Bug 1177561 - Add API methods for getting job groups and types

ui/css/treeherder.css, ui/index.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/681)
=>  	Bug 1177857 - Make job elements buttons instead of spans, for a11y

treeherder/model/sql/template_schema/project_jobs_1.sql.tmpl, treeherder/model/sql/template_schema/treeherder_reference_1.sql.tmpl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/687)
=> Bug 1178225 - Remove the unused result_set_classification table

treeherder/model/models.py
Per:
https://docs.djangoproject.com/en/1.7/ref/models/options/#unique-together
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/695)
=> Bug 1178690 - Use tuples for models.py 'unique_together'

puppet/files/treeherder/.bash_aliases
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/670)
=> Cleanup syntax in .bash_aliases

tests/conftest.py, tests/etl/conftest.py, tests/test_utils.py, treeherder/client/thclient/client.py, treeherder/client/thclient/perfherder.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/688)
=> Bug 1178474 - Have a common function for calling various endpoints.

tests/conftest.py, treeherder/client/thclient/client.py, treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json, treeherder/model/sql/template_schema/project_jobs.sql.tmpl, treeherder/webapp/api/job_log_url.py
Since it's unused.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/691)
=> Bug 1178389 - Remove job_log_url.parse_timestamp

ui/js/models/job.js, ui/plugins/pluginpanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/676)
=> Bug 1096605 - Don't include time spent pending in time estimates, and change pending jobs to always display typical ETAs

treeherder/etl/perf_data_adapters.py
Max, min, median will only be set if the number of replicates is greater than 1. Otherwise, only mean will be set.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/698)
=> Bug 1174724 - Set max, min, median and stdev only for more than 1 pt

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/712)
=> Bug 1180932 - Add the mozilla-b2g37_v2_2r repo

docs/ui/installation.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/711)
=> Bug 1180967 - Add a note that node.js should be in treeherder ui docs.

ui/js/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/709)
=> Bug 1174259 - Zoom should reset when clicking on graph

requirements/dev.txt
http://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/NEWS.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/718)
=> Bug 1181525 - Update beautifulsoup4 to v4.4.0

requirements/dev.txt
http://pytest.org/latest/changelog.html
https://github.com/pytest-dev/pytest/compare/2.6.4...2.7.2
https://bitbucket.org/pytest-dev/py/src/aea9674297657e08980f0b9ab7e9d1a80a73ea2b/CHANGELOG
https://bitbucket.org/pytest-dev/py/branches/compare/1.4.30%0D1.4.26
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/720)
=> Bug 1181531 - Update py to v1.4.30 and pytest to v2.7.2

requirements/common.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/723)
=> Bug 1181600 - Update pytz to v2015.4

requirements/common.txt
https://github.com/bradjasper/django-jsonfield#changes
https://github.com/bradjasper/django-jsonfield/compare/68ee4349...1.0.3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/726)
=> Bug 1181696 - Update jsonfield to v1.0.3

treeherder/log_parser/parsers.py
* Convert constants in parsers.py to class attributes
* Remove unused RE_INFO constant
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/707)
=> Bug 1063695 - Clean up constants in parsers.py

requirements/common.txt
https://github.com/simplejson/simplejson/blob/master/CHANGES.txt
https://github.com/simplejson/simplejson/compare/v3.6.5...v3.7.3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/727)
=> Bug 1181700 - Update simplejson to v3.7.3

requirements/common.txt
https://github.com/jcgregorio/httplib2/blob/master/CHANGELOG
https://github.com/jcgregorio/httplib2/compare/8e63343d...v0.9.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/730)
=> Bug 1181778 - Update httplib2 to v0.9.1

requirements/common.txt
https://github.com/mikeorr/Unipath/blob/master/CHANGES
https://github.com/mikeorr/Unipath/compare/v1.0...v1.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/729)
=> Bug 1181813 - Update Unipath to v1.1

requirements/common.txt
https://github.com/kennethreitz/requests/blob/master/HISTORY.rst
https://github.com/kennethreitz/requests/compare/v2.6.2...v2.7.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/731)
=> Bug 1181816 - Update requests to v2.7.0

ui/js/controllers/main.js, ui/js/directives/treeherder/clonejobs.js, ui/js/models/resultsets_store.js, ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/705)
=> Bug 1179260 - n and p can hang browser if nothing more to select

requirements/common.txt
https://github.com/ottoyiu/django-cors-headers/releases
and older: https://github.com/ottoyiu/django-cors-headers#changelog
https://github.com/ottoyiu/django-cors-headers/compare/v0.11...1.1.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/732)
=> Bug 1181819 - Update django-cors-headers to v1.1.0

requirements/common.txt
https://docs.djangoproject.com/en/1.7/releases/1.7.8/
https://docs.djangoproject.com/en/1.7/releases/1.7.9/
https://github.com/django/django/compare/1.7.7...1.7.9
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/733)
=> Bug 1181836 - Update Django to v1.7.9

treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/741)
=> Bug 1182518 - Remove unused job_guid_where_in_list

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/742)
=> Bug 1182282 - Ensure there are no duplicate entries in the performance series

ui/js/graphs.js, ui/js/models/error.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/754)
=> Remove trailing whitespace

docs/ui/installation.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/762)
=> Bug 1184135 - Fix "Validating Javascript" eslint steps

ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/766)
=> Bug 1184302-Check if a user is logged in early on job cancel request

schemas/resultset-action-message.json, treeherder/model/derived/jobs.py, treeherder/model/exchanges.py, treeherder/model/tasks.py, treeherder/webapp/api/resultset.py, ui/js/controllers/jobs.js, ui/js/models/resultset.js, ui/partials/main/thActionButton.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/747)
=> Bug 1178524 - Publish trigger_missing_jobs action for revision to pulse

treeherder/model/derived/jobs.py, treeherder/webapp/api/jobs.py, ui/js/models/job.js, ui/plugins/controller.js, ui/plugins/pluginpanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/760)
=> Bug 1183923 - Front-end UI and publish to pulse for 'backfill' action

ui/js/directives/treeherder/top_nav_bar.js, ui/js/models/repository.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/682)
=> Bug 1078700 - Add a tree state for when treestatus is unreachable

treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/776)
=> Bug 1182282 - Fix one more case where dupe performance data could happen

ui/js/directives/perf/compare.js, ui/partials/perf/compareconfidence.html, ui/partials/perf/comparectrl.html, ui/partials/perf/comparesubtestctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/769)
=> Bug 1164898 - Warn when more retriggers needed to be confident in comparison

schemas/job-action-message.json
r? @maurodoglio
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/775)
=> Bug 1183923 - Fix for publish "backfill" action on pulse.

ui/js/controllers/sheriff.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/782)
=> Bug 1091957 - Add confirmation prompt when when deleting an exclusion

treeherder/webapp/api/serializers.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/784)
=> Bug 1184988 - write an update method for the JobExclusion serializer

ui/js/values.js
Follow up to #757
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/781)
=> Bug 1181255 - Add tsan field to thOptionOrder.

.eslintrc, ui/js/compareperf.js, ui/js/controllers/settings.js, ui/js/directives/perf/compare.js, ui/js/directives/treeherder/main.js, ui/js/graphs.js, ui/js/models/error.js, ui/js/perf.js, ui/js/perfapp.js, ui/js/services/main.js
semi: "require or disallow use of semicolons instead of ASI"
http://eslint.org/docs/rules/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/780)
=> Bug 1184775 - Fix missing semicolons and enable the ESLint 'semi' rule

ui/js/graphs.js, ui/js/perf.js, ui/partials/perf/testdatachooser.html
* Chooser is now ok with two tests with same name (but different signatures)
* If test is already added to graph (or has already been selected), don't
allow user to choose it again
* Improved variable names and general simplification of code
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/791)
=>  	Bug 1185148 - Fix various problems in perfherder test chooser

schemas/resultset-action-message.json, treeherder/model/derived/jobs.py, treeherder/model/tasks.py, treeherder/webapp/api/resultset.py, ui/js/controllers/jobs.js, ui/js/models/resultset.js, ui/partials/main/thActionButton.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/779)
=> Bug 1180742-Publish 'trigger_all_talos_jobs' for a revision to pulse

schemas/resultset-action-message.json, treeherder/model/derived/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/793)
=> Bug 1171575 - Treeherder should send pulse messages for cancel all

tests/conftest.py, tests/model/sql/test_models.py, treeherder/etl/management/commands/import_project_credentials.py, treeherder/model/derived/base.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/cycle_data.py, treeherder/model/management/commands/init_datasources.py, treeherder/model/management/commands/run_sql.py, treeherder/model/migrations/0001_initial.py, treeherder/model/models.py, treeherder/model/sql/template_schema/project.sql.tmpl, treeherder/model/sql/template_schema/treeherder.sql.tmpl
Since it's redundant now that the objectstore has been removed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/794)
=> Bug 1185030 - Remove the contenttype field from the datasource table

tests/webapp/api/test_version.py, treeherder/client/thclient/client.py, treeherder/settings/base.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/800)
=> Bug 1145720 - Setup api versioning

Gruntfile.js
…hitespace
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/804)
=>  	Bug 1187035 - Use conservativeCollapse everywhere for collapsing UI whitespace

tests/webapp/api/test_resultset_api.py, treeherder/settings/base.py, treeherder/webapp/api/artifact.py, treeherder/webapp/api/auth.py, treeherder/webapp/api/bug.py, treeherder/webapp/api/job_log_url.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/logslice.py, treeherder/webapp/api/note.py, treeherder/webapp/api/objectstore.py, treeherder/webapp/api/performance_artifact.py, treeherder/webapp/api/permissions.py, treeherder/webapp/api/refdata.py, treeherder/webapp/api/resultset.py, treeherder/webapp/api/utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/797)
=> Bug 1185520 - wrap the legacy oauth verification in drf authentication and permission classes

ui/css/treeherder.css, ui/js/controllers/filters.js, ui/js/controllers/main.js, ui/partials/main/thWatchedRepoNavPanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/807)
=> Bug 1185110 - Shorten the IDs for the quick filter field

treeherder/etl/buildapi.py
~~If posting the jobs results in an exception, clear the cached job ids, to ensure that we retry ingesting those jobs in the next run. Also moves the cache.set() as late as possible in the transform method.~~
~~Another way I could handle this case is by returning the list of "seen" job ids from transform() (eg by returning as a tuple and only setting the cached value in the run() method, after we'd already done the load().~~
~~Which approach do you prefer? I'm sort of leaning towards the latter maybe...~~
*Updated:*
Moves the updating of the cached "seen" job ids until after we've successfully posted the jobs to the API. Previously, if posting the jobs had failed, we'd have updated the cache prior to that, meaning the next run of the ingestion task would incorrectly treat those jobs as …
=> Bug 1178240 - Only cache the seen job ids after successful submission

ui/css/perf.css, ui/js/compareperf.js, ui/js/directives/perf/compare.js, ui/js/perf.js, ui/partials/perf/average.html, ui/partials/perf/compareconfidence.html, ui/partials/perf/comparectrl.html, ui/partials/perf/comparesubtestctrl.html, ui/partials/perf/comparetable.html, ui/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/818)
=>  Bug 1186228 - Simplify and clarify display of information in perfherder compare view

treeherder/client/thclient/client.py
Some collections can only return a limited number of results at a time. This
change allows the user to get all results by passing count=None to the relevant
get_ method of TreeherderClient, and letting the client perform enough requests
to fetch all results.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/834)
=> Support for getting a complete list from paginated collections.

treeherder/webapp/api/jobs.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/840)
=> Bug 1121998-Fix publishing retrigger action for multiple jobs to pulse

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/844)
=> Bug 1192223 - Log both request and response in case of client failures

docs/common_tasks.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/855)
=> Bug 1165929 - Docs: Add instructions on how to build the docs locally

treeherder/model/derived/jobs.py, treeherder/webapp/api/performance_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/833)
=> Bug 1189519 - Filter performance series summary by platform

tests/conftest.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/863)
=> Remove duplicate imports in conftest.py

ui/js/directives/treeherder/clonejobs.js, ui/plugins/controller.js, ui/plugins/talos/main.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/856)
=> Bug 1184748 - Link to compare view from resultset view for talos jobs

treeherder/model/derived/jobs.py, treeherder/webapp/api/performance_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/848)
=> Bug 1189519 - Add get platforms endpoint

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/868)
=>  	Bug 1193925 - Add a client method for getting list of machine platforms

treeherder/model/management/commands/import_reference_data.py
Ignore the second commit, it will disappear when bug 1193925 is merged.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/869)
=>  	Bug 1193923 - Initial ability to import reference data from another server

bin/run_gunicorn, treeherder/webapp/wsgi.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/884)
=> Bug 1191080 - Use newrelic-admin run-program rather than manual init

requirements/common.txt, tests/model/sql/test_models.py, treeherder/model/management/commands/init_master_db.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/886)
=> Bug 1181879 - upgrade django to 1.8.4

treeherder/client/thclient/client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/888)
=>  	Bug 1196427 - Add API method to get job log url

treeherder/model/sql/template_schema/treeherder_reference_1.sql.tmpl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/897)
=> Bug 1194226 - Use unsigned int in reference data tables

ui/js/directives/treeherder/persona.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/902)
=> Bug 1197550 - Fix csrf token validation on first persona login

tests/client/test_treeherder_client.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/894)
=> Bug 1177531 - Add tests for various get functions in treeherder-client

ui/partials/perf/comparetable.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/909)
=>  	Bug 1198493 - Sort test names and platforms in compare perf alphabetically

puppet/files/treeherder/.bash_aliases
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/910)
=>  	Bug 1198502 - Add bash aliases for restarting rabbitmq and memcached

ui/help.html
The revision files are now located at:
https://treeherder.allizom.org/revision.txt
https://treeherder.mozilla.org/revision.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/911)
=> Bug 1198452 - Update the "What's Deployed" URL for new revision location

.gitignore, treeherder/settings/base.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/900)
=> Bug 1124382 - Move static and media folders to treeherder/

ui/logviewer.html, ui/partials/perf/graphsctrl.html, ui/partials/perf/revisiondescribe.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/917)
=> Bug 1197273 - Add whitespace around pipe operator in getRevisionUrl

requirements/common.txt
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-254041
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/922)
=> Bug 1199378 - Update New Relic Python agent to v2.54.0.41

ui/js/models/resultsets_store.js
Hi All,
Tested this on Ubuntu 14.04 LTS 64 bit ,Firefox 33.0 and it seems to work fine . thanks camd for help and whimboo , jfrench for their cooperation..
Reference: www.w3schools.com
Regards,
Tapesh Mandal(tapesh)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/926)
=> Bug 1178736 - Sometimes groups are not correctly alphabetically sorted

treeherder/model/migrations/0001_initial.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/950)
=> Bug 1182464 - Add new action choice to the migrations file

treeherder/model/management/commands/test_analyze_perf.py
Here is what we can got now
vagrant ~/treeherder $ ./manage.py test_analyze_perf --server https://treeherder.mozilla.org --project 'mozilla-inbound' --time-interval 604800
project,platform,signature,series,testrun_id,push_timestamp,change,percent change,t-value,revision
mozilla-inbound,windows8-64,b44b932ff6ffa9e7f54b23e1c1ae3cc5456faed4,damp simple.jsdebugger.reload.DAMP e10s opt,19522,1441347649,3.65083333333,5.35561477714,7.46132127486,8b380feae2ae
mozilla-inbound,windows7-32,06b47ef0361390db71ed967bdb83cf2bd63b8636,ts_paint summary pgo,19523,1441353594,17.9166666667,1.96275333212,7.25399829154,3416308a1151
mozilla-inbound,windows7-32,445ec2a7b7382b8128323728b592fa0e1b6e1f1f,tp5o_scroll thepiratebay.org pgo,19522,1441347649,0.2,5.61009817672,12.1705603252,8b380feae2ae …
=> Bug 1186569 - Alert on data which != summary

treeherder/model/migrations/0001_initial.py, treeherder/model/models.py, treeherder/model/sql/template_schema/treeherder_reference_1.sql.tmpl
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/957)
=> Bug 1194824 - Add last modified timestamp to ExclusionProfile

requirements/common.txt, treeherder/model/migrations/0001_initial.py, treeherder/model/models.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/960)
=> Bug 1201140 add ref data indexes

puppet/manifests/classes/mysql.pp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/963)
=> Bug 1204918 - upgrade to mysql 5.6 for local development

ui/js/graphs.js, ui/js/perfapp.js, ui/partials/perf/graphsctrl.html, ui/perf.html, ui/vendor/angular/angular-ui-router.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/962)
=> Performance routing fixes

ui/js/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/974)
=>  	Bug 1205789 - Fix and clarify changing time range in perfherder graphs

ui/js/perfapp.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/973)
=>  	Bug 1206097 - Fix selection of invalid revision 'true' when adding graph

treeherder/perf/management/commands/import_perf_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/988)
=> Bug 1207138 - Allow user can use --time-interval to specify time interval

treeherder/perf/management/commands/import_perf_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1001)
=> Bug 1207726 - Fix importing perf data when a subset of it already exists

tests/webapp/api/test_jobs_api.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/refdata.py, treeherder/webapp/api/serializers.py, treeherder/webapp/api/urls.py
This provides an endpoint /api/failure_line?job_guid={something}
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/986)
=> Bug 1207126 - Implement an API endpoint for autoclassify data.

ui/css/logviewer.css, ui/js/controllers/logviewer.js, ui/partials/logviewer/lvLogLines.html, ui/partials/logviewer/lvLogSteps.html
This is the first draft.
I still have to change some stuffs(lot of stuffs), but I'd like to have some feedback, to see if I'm doing everything right, or if something can be changed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/948)
=> Bug 1108764 - Allow easy sharing of links to a specific log line in the log viewer

docs/common_tasks.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1020)
=> Docs: Minor cleanup to the "Building the docs" section

ui/js/controllers/perf/graphs.js, ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1024)
=> Bug 1205789 - Fix back/forward button in perfherder graphs

docs/index.rst, docs/pulseload.rst, requirements/common.txt, schemas/pulse-job.yml, tests/etl/test_job_loader.py, tests/etl/test_job_schema.py, tests/sample_data/pulse_consumer/job_data.json, tests/sampledata.py, treeherder/etl/job_loader.py, treeherder/etl/management/commands/ingest_from_pulse.py, treeherder/etl/management/commands/publish_to_pulse.py, treeherder/etl/pulse_consumer.py, treeherder/etl/schema.py, treeherder/etl/tasks/__init__.py, treeherder/etl/tasks/pulse_tasks.py, treeherder/settings/base.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1023)
=> Bug 1169320 - Adds support for job ingestion via Pulse

ui/plugins/failure_summary/controller.js, ui/plugins/failure_summary/main.html
Hi All,
Tested this on my system ..seems to work fine.. although feel free to test with more test cases/URLs.
your opinion will be valuable .
Regards,
Tapesh Mandal (IRC nick: tapesh)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1012)
=> Bug 1174645 - Improve job details message for missing logs

requirements/common.txt
https://github.com/kumar303/hawkrest/compare/0.0.6...0.0.8
Mauro - could you double check we don't need to make any further changes on our side? :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1029)
=> Bug 1210748 - Update to hawkrest v0.0.8 since v0.0.6 removed from PyPI

requirements/common.txt
https://github.com/evansd/whitenoise/blob/master/CHANGELOG.rst#v204
https://github.com/evansd/whitenoise/compare/v2.0.2...v2.0.4
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1041)
=> Bug 1211900 - Update whitenoise to v2.0.4

requirements/common.txt, requirements/dev.txt, treeherder/webapp/api/artifact.py, treeherder/webapp/api/auth.py, treeherder/webapp/api/bug.py, treeherder/webapp/api/job_log_url.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/logslice.py, treeherder/webapp/api/note.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/refdata.py, treeherder/webapp/api/resultset.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1039)
=> Bug 1211866 - Update Django related Python packages

puppet/manifests/vagrant.pp, treeherder/settings/base.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1046)
=> Bug 1212822 - Only load local.py in the Vagrant environment

treeherder/model/derived/jobs.py, treeherder/model/sql/template_schema/project.sql.tmpl
This field is self-populating, so no code changes required.  I'll just have to run a sql script to modify the tables after merge.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1052)
=> Bug 1196804 - Add last_modified field to resultset table

deployment/update/update.py
Also remove unnecessary check for the API key and app id, and make any errors raise (since it won't affect the deploy itself, but will make issues more obvious in the IRC bot comments).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1061)
=> Bug 1214183 - Make the deploy script use requests not urllib/urllib2

ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1064)
=> Bug 1214229 - Add ui support for OS X 10.11 (El Capitan)

treeherder/credentials/migrations/0002_auto_20151014_0900.py, treeherder/model/migrations/0002_auto_20151014_0900.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1067)
=> Add missing migrations

tests/etl/test_classification_mirroring.py, tests/webapp/conftest.py, treeherder/model/derived/artifacts.py, treeherder/model/utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1060)
=> Bug 1205674 - Remove decompress_if_needed()

tests/etl/test_perf_data_adapters.py, treeherder/etl/perf.py, treeherder/perf/management/commands/migrate_perf_signatures.py, treeherder/perf/migrations/0002_auto_20151014_0922.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1028)
=>  	Bug 1207648 - Speed up getting performance signatures

treeherder/webapp/api/performance_data.py
* Make fetching platform data for signatures use the new performance
signature data added in bug 1207648
* Use values_list when fetching performance datums
* Improve speed of getting performance signatures
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1072)
=>  	Bug 1215387 - Further optimizations for fetching performance data

ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1073)
=> Bug 1214229 - Ensure OS X 10.11 is correctly sorted. r=camd

ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1071)
=> Bug 1215316 - Removing ash repo's special-casing for retrigger/cancel

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1079)
=> Bug 1216531 - Disable unused gum, holly and maple repositories

schemas/pulse-job.yml, tests/etl/test_common.py, tests/model/derived/test_jobs_model.py, tests/sample_data/resultset_data.json, tests/webapp/api/test_resultset_api.py, treeherder/etl/buildapi.py, treeherder/etl/job_loader.py, treeherder/etl/management/commands/ingest_push.py, treeherder/etl/pushlog.py, treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json
Don't use these fields for anything yet, but begin populating data with them.  We will then back-fill older records with another process.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1062)
=> Bug 1079796 - Populate long and short revisions

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1099)
=> Bug 1218049 - Add support for the mozilla-b2g44_v2_5 repository

ui/css/perf.css, ui/partials/perf/comparetable.html, ui/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1110)
=> css tweaks

treeherder/perf/management/commands/remove_perf_signatures.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1115)
=>  	Bug 1221277 - Add a command for removing unwanted performance data

ui/css/perf.css, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/perf.js, ui/partials/perf/comparetable.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1114)
=> Add links to graphs from compare view + related fixes

treeherder/model/fixtures/failure_classification.json, ui/js/services/jobfilters.js, ui/partials/main/thFilterPanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1116)
=> Bug 1221079 - make unclassified failures mode show "auto classified" jobs

treeherder/webapp/api/bug.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1122)
=> Bug 1221936 - Don't raise an error when providing a duplicate bug association on a job

tests/e2e/test_perf_ingestion.py, treeherder/etl/perf.py, treeherder/perf/management/commands/remove_single_test_summaries.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1078)
=>  	Bug 1162522 - Don't summarize talos tests with only one subtest

treeherder/model/sql/jobs.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1124)
=> Bug 1221064 - make the job list order explicit

.eslintrc, package.json, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/directives/treeherder/clonejobs.js, ui/js/models/bug_job_map.js, ui/js/models/repository.js, ui/js/models/user.js, ui/js/providers.js, ui/js/services/jobfilters.js, ui/js/services/log.js, ui/js/services/main.js
Later bugs will enable more rules (including indent, which had to be turned off, since newer eslint catches more bad indent cases than before, so there are now new failures).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1125)
=> Bug 1220479 - Update grunt-eslint to 17.3.1 and eslint to 1.8.0

schemas/performance-artifact.json, tests/etl/test_perf_data_adapters.py, tests/sample_data/artifacts/performance/talos_perf.json, treeherder/etl/perf.py, treeherder/perf/migrations/0003_performancesignature_lower_is_better.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, ui/js/controllers/perf/compare.js, ui/js/perf.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1128)
=>  	Bug 1158233 - Store and use "lower is better" metadata for perf tests

ui/js/controllers/perf/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1129)
=> Bug 1222654 - Lose state when zooming in on graph

.eslintignore, Gruntfile.js, ui/plugins/controller.js, ui/plugins/pinboard.js, ui/plugins/similar_jobs/controller.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1126)
=> Bug 1222542 - Run eslint against all of the ui/ directory not just ui/js/

requirements/common.txt
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-256042
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1137)
=> Bug 1223497 - Update the New Relic Python agent to v2.56.0.42

tests/perfalert/test_analyze.py, treeherder/perf/management/commands/test_analyze_perf.py, treeherder/perfalert/perfalert/__init__.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1132)
=> Updates to perfalert for clarity and ease-of-use

ui/js/directives/treeherder/clonejobs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1134)
=>  	Bug 1223503 - Simplify population of job groups in frontend

ui/js/perf.js
…ompare
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1143)
=>  	Bug 1224238 - Fix display of regressions/improvements in perfherder compare

ui/js/controllers/main.js, ui/js/models/resultsets_store.js, ui/js/services/main.js, ui/partials/main/thNotificationsBox.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1133)
=> Bug 1222025 - persist selected job in URL so it re-selects on page reload

ui/js/controllers/perf/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1148)
=>  	Bug 1224603 - Show an error when we can't load a series in perfherder graphs

.gitignore, requirements/dev.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1145)
=> Bug 1223824 - Update dev-only Python packages

requirements/common.txt, tests/webapp/api/test_job_log_url.py, treeherder/model/derived/jobs.py, treeherder/webapp/api/job_log_url.py
See individual commits :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1155)
=> Bug 1226565 - Prevent update-parse-status 404s when there's DB replication lag

tests/perfalert/test_create_alerts.py, treeherder/config/settings.py, treeherder/perf/alerts.py, treeherder/perf/management/commands/generate_alerts.py, treeherder/perf/management/commands/test_analyze_perf.py, treeherder/perf/migrations/0004_auto_20151116_1041.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, treeherder/webapp/api/urls.py, ui/css/perf.css, ui/js/controllers/perf/alerts.js, ui/js/models/resultset.js, ui/js/models/resultsets_store.js, ui/js/perf.js, ui/js/perfapp.js, ui/js/services/main.js, ui/partials/perf/alertsctrl.html, ui/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1149)
=>  	Bug 1201154 - Basic read-only UI for performance alerts

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1170)
=> Bug 1227352 - Add the b2g-ota repository

requirements/common.txt
https://docs.djangoproject.com/en/1.8/releases/1.8.6/
https://docs.djangoproject.com/en/1.8/releases/1.8.7/
https://github.com/django/django/compare/1.8.5...1.8.7
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1168)
=> Bug 1227733 - Update Django from v1.8.5 to v1.8.7

tests/perfalert/test_analyze.py, tests/perfalert/test_create_alerts.py, treeherder/perf/alerts.py, treeherder/perfalert/perfalert/__init__.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1167)
=> Handle case where the alert is inside a retrigger

ui/css/treeherder-navbar.css, ui/js/perfapp.js, ui/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1159)
=> Add login button to perfherder

.travis.yml, puppet/manifests/vagrant.pp, requirements/common.txt, tests/test_setup.py, treeherder/config/settings.py, treeherder/config/settings_local.example.py, treeherder/model/derived/refdata.py, treeherder/model/management/commands/run_sql.py, treeherder/model/models.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1154)
=> Bug 1160561 - Switch more settings to django-environ & other cleanup

.gitignore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1162)
=> ignore ide files

ui/partials/perf/alertsctrl.html
* Alert Summary -> Alert
* Alert -> Detected Changes
* Include id # in summary (for people to look up and reference later)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1181)
=> Bug 1229101 - Change alert titling

treeherder/etl/classification_mirroring.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1174)
=> Bug 1228335 - Clean up ElasticSearch submission

bin/peep.py, puppet/manifests/classes/python.pp
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1188)
=> Bug 1230104 - Update peep to v2.5.0 and virtualenv to v13.1.2

tests/conftest.py, tests/perfalert/test_create_alerts.py, tests/webapp/api/test_performance_alerts_api.py, treeherder/perf/migrations/0006_add_perfalerts_revised_summary.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, treeherder/webapp/api/urls.py, ui/css/perf.css, ui/js/controllers/perf/alerts.js, ui/partials/perf/alertsctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1190)
=> Add ability to reassign perfherder alerts

docs/installation.rst
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1195)
=> Bug 1231421 - Add hint about UI-only treeherder to installation docs

treeherder/webapp/api/performance_serializers.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1197)
=> Bug 1231791 - Show e10s property in alerts view

requirements/common.txt, treeherder/config/settings.py
=> Bug 1231831 - Upgrade django-rest-framework to v3.3.1 and fix test failures

tests/conftest.py, tests/etl/test_buildapi.py, tests/etl/test_common.py, tests/log_parser/test_tasks.py, treeherder/config/settings.py, treeherder/etl/classification_mirroring.py, treeherder/etl/common.py, treeherder/etl/mixins.py, treeherder/etl/pushlog.py, treeherder/log_parser/artifactbuildercollection.py, treeherder/log_parser/artifactbuilders.py, treeherder/log_parser/management/commands/store_error_summary.py, treeherder/model/error_summary.py, treeherder/webapp/api/logslice.py
See individual commits - the combined diff looks worse than it is, I promise haha :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1193)
=> Bug 1230610 - Set a User-Agent for HTTP requests made by Treeherder

treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, treeherder/webapp/api/urls.py, ui/js/controllers/perf/compare.js, ui/js/directives/perf/compare.js, ui/js/models/perf/performance_framework.js, ui/js/perf.js, ui/js/perfapp.js, ui/partials/perf/comparectrl.html, ui/perf.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1203)
=> Bug 1227622 - Filter compare view results by framework id

requirements/dev.txt
datadiff (Current: 1.1.6 Latest: 2.0.0 [sdist])
django-extensions (Current: 1.5.9 Latest: 1.6.1 [wheel])
flake8 (Current: 2.5.0 Latest: 2.5.1 [wheel])
py (Current: 1.4.30 Latest: 1.4.31 [wheel])
pytest (Current: 2.8.2 Latest: 2.8.5 [wheel])
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1204)
=> Bug 1232550 - Update dev python packages, December edition

requirements/common.txt
django-browserid: v1.0.0 -> v1.0.2
functools32: v3.2.3-1 -> v3.2.3-2
pytz: v2015.4 -> v2015.7
simplejson: v3.7.3 -> v3.8.1
six: v1.9.0 -> v1.10.0
sqlparse: v0.1.16 -> v0.1.18
whitenoise: v2.0.4 -> v2.0.6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1205)
=> Bug 1232654 - Update common.txt Python packages: Part 1

requirements/common.txt
djangorestframework: v3.3.1 -> v3.3.2
gunicorn: v19.3.0 -> v19.4.1
kombu: v3.0.30 -> v3.0.32
mozlog: v3.0 -> v3.1
newrelic: v2.58.1.44 -> v2.60.0.46
requests: v2.7.0 -> v2.9.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1215)
=> Bug 1232654 - Update common.txt Python packages: Part 3

ui/css/perf.css, ui/js/controllers/perf/graphs.js, ui/partials/perf/graphsctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1217)
=> Bug 1234302 - Simplify and improve rendering of graph legend

treeherder/webapp/api/performance_serializers.py, ui/js/controllers/perf/alerts.js, ui/js/perfapp.js, ui/partials/perf/alertsctrl.html, ui/partials/perf/comparectrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1219)
=> Bug 1234621 - Add basic client-side filtering to perfherder alerts

.travis.yml, package.json
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1220)
=> Bug 1234897 - Pin the version of nodejs used on Heroku

requirements/common.txt
http://docs.gunicorn.org/en/latest/news.html
https://github.com/benoitc/gunicorn/compare/19.4.1...19.4.3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1224)
=> Bug 1232654 - Update gunicorn from v19.4.1 to v19.4.3

requirements.txt
This only affects Heroku.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1226)
=> Bug 1236592 - Update pylibmc to v1.5.0 and django-pylibmc to v0.6.1

ui/js/services/jobfilters.js, ui/partials/main/thWatchedRepoNavPanel.html
Please see commit details
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1230)
=> Bug 1237071,1237096 - Job filtering fixes

ui/css/perf.css, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/graphs.js, ui/js/models/repository.js, ui/js/services/main.js, ui/partials/perf/alertsctrl.html, ui/partials/perf/graphsctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1229)
=> Bug 1236729 - Allow user to go directly to hg pushlog from alerts view

ui/css/perf.css, ui/partials/perf/alertsctrl.html, ui/partials/perf/comparetable.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1231)
=> Bug 1237100 - UI tweaks to make compare and alerts view more space efficient

treeherder/model/fixtures/performance_framework.json
This allows us to push performance data for the AreWeSlimYet project.
@wlach Does this look good?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1237)
=> Bug 1238153 - Add awsy entry to performance_framework.json

requirements/common.txt
1) Update mohawk from v0.3.0 to v0.3.1
https://mohawk.readthedocs.org/en/latest/#changelog
https://github.com/kumar303/mohawk/compare/0.3.0...0.3.1
2) Update hawkrest from v0.0.8 to v0.0.9
https://hawkrest.readthedocs.org/en/latest/#changelog
https://github.com/kumar303/hawkrest/compare/0.0.8...0.0.9
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1238)
=> Bug 1238274 - Update mohawk to v0.3.1 and hawkrest to v0.0.9

ui/js/services/jobfilters.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1239)
=> Bug 1238432 - Only update job tables once when filtering settings change

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1252)
=> Bug 1229075 - Remove the gaia-try and staging-gaia-try repositories

treeherder/etl/perf.py
If the datum was already created, it means that we submitted the same
job information twice. No need to re-run the alert generation in that
case.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1251)
=> Bug 1240042 - Don't re-run alert generation if datum already created

tests/etl/test_perf_data_adapters.py, treeherder/etl/perf.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1250)
=> Bug 1240040 - Fail gracefully if performance framework does not exist on ingestion

ui/js/controllers/perf/graphs.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1249)
=> Display appropriate message in console when resultset not available

treeherder/config/settings.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1255)
=> Bug 1160561 - Part 4: Remaining environment variable cleanup

puppet/manifests/classes/init.pp, puppet/manifests/classes/mysql.pp, puppet/manifests/classes/python.pp, puppet/manifests/classes/varnish.pp
Plus some other cleanup.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1258)
=> Bug 1240523 - Fix puppet steps that run unnecessarily

ui/partials/perf/comparechooserctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1263)
=> Bug 1200222 - Provide a placeholder for the revision fields in Compare

.travis.yml, puppet/manifests/classes/python.pp
https://pip.pypa.io/en/stable/news/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1269)
=> Bug 1241144 - Update to pip 8.0.2

tests/test_utils.py, treeherder/etl/common.py, treeherder/etl/job_loader.py, treeherder/model/derived/base.py, treeherder/model/derived/jobs.py, treeherder/model/utils.py
https://pypi.python.org/pypi/vulture
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1257)
=> Bug 1144721 - Remove dead Python code found using vulture

ui/js/perf.js, ui/partials/perf/comparetable.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1275)
=> Bug 1242656 - Don't say we need more runs when they won't help in perfherder

treeherder/config/settings.py, treeherder/log_parser/tasks.py
I put this behind the conditional env var that is upcoming for the larger autoclassify feature.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1276)
=> Bug 1242776 - stop adding tasks to autoclassify queue

Procfile, tests/autoclassify/test_classify_failures.py, tests/autoclassify/test_detect_intermittents.py, tests/webapp/api/test_jobs_api.py, treeherder/model/migrations/0008__add_best_fields_to_failureline.py, treeherder/model/models.py
This contains, primarily, the model and migration changes for the autoclassify feature.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1266)
=> Bug 1177519 - Autoclassify model migration changes

treeherder/model/fixtures/performance_framework.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1277)
=> Bug 1243065 - Add fixture for awfy performance framework

Vagrantfile, docs/common_tasks.rst, puppet/manifests/classes/python.pp
* Remove support for creating a 'scratch' VM
* Remove unnecessary package install/updates
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1284)
=> Bug 1244142 - Vagrant environment cleanup

ui/js/controllers/perf/compare.js, ui/js/services/jsonpushes.js, ui/partials/perf/comparechooserctrl.html, ui/perf.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1283)
=> Bug 1210427 - compare view to pick revisions could aid developers with some simple changes

ui/js/models/resultsets_store.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1289)
=> Bug 1240391 - 'Get next X jobs' shouldn't create additional job pulling interval

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1295)
=> Bug 1246757 - Disable the no longer used bugzilla-4_2 repository

ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/controllers/sheriff.js, ui/js/models/option_collection.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1267)
=> Bug 1241611 - Simplify OptionCollection model in frontend

treeherder/perf/migrations/0004_auto_20151116_1041.py, treeherder/perf/migrations/0005_auto_20151124_1051.py, treeherder/perf/migrations/0006_add_perfalerts_revised_summary.py, treeherder/perf/migrations/0007_alert_status.py, treeherder/perf/migrations/0008_delete_perfalerts.py, treeherder/perf/migrations/0009_refactor_perfalerts.py
Delete everything via a manually generated migration, then recreate
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1297)
=> Bug 1246774 - Refactor perf migrations so stuff doesn't break on upgrade

ui/css/treeherder-info-panel.css, ui/plugins/controller.js, ui/plugins/perf_details/main.html, ui/plugins/tabs.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1288)
=> Bug 1239779 - Generalize talos panel to all performance data

ui/js/controllers/perf/graphs.js, ui/partials/perf/graphsctrl.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1304)
=> Bug 1249164 - Link directly to treeherder job from graph datapoint

ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1307)
=> Bug 1249395 - Fix issue where failure panel wouldn't display on first load

ui/js/controllers/perf/alerts.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1309)
=> Bug 1249780 - Fix links to ts_paint, tpaint documentation in bug template

ui/js/models/perf/alerts.js, ui/partials/perf/alertsctrl.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1310)
=> Bug 1249826 - Auto-load series on other branches when opening graph from alert

treeherder/model/derived/jobs.py
This adds the ``job_guid`` from the owning job to any artifact that
doesn’t have the field value already set.  This allows later calls that
rely on that field to find it, rather than hitting an error and not
storing the artifact.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1308)
=> Bug 1249692 - handle missing job_guid field in artifacts submitted with jobs

treeherder/model/fixtures/repository.json
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1314)
=> Bug 1250617 - Add new tree {mozilla,comm}-esr45 to Treeherder

ui/js/controllers/perf/compare.js, ui/js/controllers/perf/e10s.js, ui/js/directives/perf/compare.js, ui/js/models/perf/alerts.js, ui/js/perf.js, ui/js/perfapp.js, ui/partials/perf/comparectrl.html, ui/partials/perf/comparesubtestctrl.html, ui/partials/perf/comparetable.html, ui/partials/perf/e10s.html, ui/perf.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1316)
=> Bug 1251353 - Add a dashboard for tracking e10s vs. non-e10s performance

ui/userguide.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1319)
=> Bug 1251649 - Add firefox-ui-tests to userguide.html

requirements/common.txt
https://docs.djangoproject.com/en/stable/releases/1.8.8/
https://docs.djangoproject.com/en/stable/releases/1.8.9/
https://docs.djangoproject.com/en/stable/releases/1.8.10/
https://github.com/django/django/compare/1.8.7...1.8.10
=> Bug 1252515 - Update to Django 1.8.10

ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1331)
=> Bug 1253036 - Fix display of AWSY results in job panel

treeherder/perf/models.py
Mainly just for debugging purposes
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1334)
=> Bug 1254217 - Improve string representations of perfherder models

tests/etl/test_perf_data_adapters.py, treeherder/etl/perf.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1343)
=> Bug 1255118 - Respect "lower is better" for suite-level values in perfherder

tests/etl/test_perf_data_adapters.py, tests/webapp/api/test_performance_data_api.py, treeherder/etl/perf.py, treeherder/perf/management/commands/migrate_perf_signature_subtest_schema.py, treeherder/perf/migrations/0012_performancesignature_parent_signature.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py
Based on work by Mike Ling <sabergeass@gmail.com>
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1336)
=> Bug 1226693 - Store performance subtest info using a foreign key relation

ui/index.html, ui/js/directives/treeherder/clonejobs.js, ui/js/models/resultsets_store.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1339)
=> Bug 1254711 - De-emphasize tier information in job group display

treeherder/model/fixtures/performance_framework.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1349)
=> Bug 1256408 - Add a platform microbench perf framework

treeherder/model/migrations/0009_remove_refdata_signature_review.py, treeherder/model/migrations/0010_machine_name_unique.py, treeherder/model/models.py, treeherder/webapp/admin.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1351)
=> Bug 1239185 - Followups to reference data refactoring

.travis.yml, Procfile, bin/run_celery_worker, bin/run_celery_worker_log_parser, docs/pulseload.rst, lints/queuelint.py, runtests.sh, treeherder/config/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1342)
=> Bug 1255087 - Add a lint for checking that Procfile and CELERY_QUEUES match

ui/js/models/perf/alerts.js
* We should not incorporate downstream alert information into the title
* If there are any regressions that belong to the summary, only incorporate
the regression information into the title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1354)
=> Bug 1257625 - Be more selective about alerts we use to create summary titles

ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1355)
=> Bug 1257640 - Order performance alerts in each summary by title

treeherder/perf/management/commands/import_perf_data.py, treeherder/perf/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1353)
=> Bug 1217520 - Import perf data using bulk_create if possible 

treeherder/model/fixtures/performance_framework.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1358)
=> Bug 1253341 - Run duplicate Talos jobs in AWS for Linux. r=wlach

.travis.yml, puppet/manifests/classes/python.pp
pip:
https://pip.pypa.io/en/stable/news/
https://github.com/pypa/pip/compare/8.1.0...8.1.1
...and updating to virtualenv 15.0.1 since it includes pip 8.1.1:
https://virtualenv.pypa.io/en/latest/changes.html
https://github.com/pypa/virtualenv/compare/15.0.0...15.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1360)
=> Bug 1258676 - Update to pip 8.1.1 & virtualenv 15.0.1

treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1363)
=> Fix a typo in the matcher registration

ui/plugins/job_details/main.html
I think this part could be merged. I'll work on the other PR after this which will fix the target issue. Can't understand what's happening there.
=> Bug 1251988 - Update name of <a> element for wptview

ui/js/filters.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1364)
=> Bug 1243155 - Removing undefined letters from commit author's initials.

ui/js/controllers/perf/e10s.js, ui/js/perfapp.js, ui/js/values.js, ui/partials/perf/e10s-subtest.html, ui/partials/perf/e10s.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1367)
=> Bug 1257509 - Allow selection of branch, sampling intervals for e10s comparisons

tests/conftest.py, tests/webapp/api/test_performance_data_api.py, treeherder/etl/perf.py, treeherder/perf/migrations/0013_add_has_subtests_property.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/e10s.js, ui/js/controllers/perf/graphs.js, ui/js/perf.js, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1371)
=> Bug 1260110 - Re-work the signature fetching API to be faster

ui/partials/main/thInfraMenu.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1381)
=> Bug 1260608 - Update links on the Infra menu

ui/js/controllers/perf/compare.js, ui/js/controllers/perf/e10s.js, ui/js/controllers/perf/graphs.js, ui/js/perf.js, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1382)
=> Bug 1261176 - Simplifications of the client-side performance API

treeherder/etl/management/commands/ingest_push.py, treeherder/etl/tasks/buildapi_tasks.py, treeherder/etl/tasks/cleanup_tasks.py, treeherder/model/derived/jobs.py, treeherder/model/derived/refdata.py, treeherder/model/sql/reference.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1378)
=> Bug 1231361 - Remove refdata model repository methods

setup.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1388)
=> Make flake8/pep8 ignore perf migrations as well

tests/etl/test_perf_data_adapters.py, tests/webapp/api/test_performance_data_api.py, treeherder/etl/perf.py, treeherder/perf/migrations/0014_allow_same_signature_hash_different_frameworks.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/directives/perf/compare.js, ui/js/perfapp.js, ui/partials/perf/graphsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1384)
=> Bug 1260926 - Properly handle some edge cases related to performance frameworks

schemas/performance-artifact.json, tests/etl/test_perf_data_adapters.py, tests/perfalert/test_create_alerts.py, treeherder/config/settings.py, treeherder/etl/perf.py, treeherder/perf/alerts.py, treeherder/perf/migrations/0015_make_alerting_configurable_per_series.py, treeherder/perf/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1344)
=> Bug 1254595 - Make alert generation parameters configurable per-series

tests/log_parser/test_error_parser.py, treeherder/log_parser/parsers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1392)
=> Bug 1262584 - Improve taskcluster error regex

ui/js/controllers/perf/graphs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1394)
=> Bug 1255797 - Fix highlighting revisions / alert toggles in graphs

treeherder/model/derived/artifacts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1396)
=> Bug 1231361 - Fix performance artifact ingestion more robustly

treeherder/model/sql/jobs.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1387)
=> Bug 1261515 - Ignore tier3 jobs in resultset status

ui/js/controllers/perf/e10s.js, ui/js/perfapp.js, ui/partials/perf/e10s-subtest.html, ui/partials/perf/e10s.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1399)
=> Bug 1254341 - Support e10s-vs-base comparisons on a specific push

ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1402)
=> Bug 1261176 - Fix a minor bug in clientside compare

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, ui/css/perf.css, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/models/perf/performance_framework.js, ui/js/perf.js, ui/js/values.js, ui/partials/perf/testdatachooser.html
Includes a few smaller related fixes to make the view reasonable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1404)
=> Bug 1230652 - Filter test list by performance framework in UI

treeherder/etl/bugzilla.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1405)
=> Bug 1264212 - Ignore timezone when updating bugscache

ui/js/controllers/perf/graphs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1406)
=> Bug 1230652 - Fix default selection of framework in chooser

treeherder/client/thclient/client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1407)
=> Bump treeherder client version to 2.1.0

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, ui/js/controllers/perf/e10s.js, ui/js/controllers/perf/graphs.js, ui/js/perf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1412)
=> Bug 1265655 - Filter by framework when getting performance data

ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1413)
=> Bug 1265721 - Fix repeating tests in subtest comparison view

treeherder/perf/management/commands/import_perf_data.py
Modify the import_perf_data script to add each of a parent signatures'
subtest signatures, setting the parent_signature property appropriately.
Add a parent_signature argument to the _add_series function that
allows setting the parent_signature property on the
PerformanceSignature object to either None (if it is a parent)
or the hash of its parent (if it is a subtest signature).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1375)
=> Bug 1257954 - Use parent signature property in import_perf_data

treeherder/perf/management/commands/import_perf_data.py
Stop ignoring --time-interval command option when
adding a signature or series.
Use default value of one week if the user doesn't
specify an interval.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1418)
=> Bug 1266413 - Use specified time interval when adding series

tests/etl/test_buildapi.py, tests/log_parser/test_tasks.py, tests/model/derived/test_jobs_model.py, tests/webapp/api/test_artifact_api.py, tests/webapp/api/test_bug_job_map_api.py, tests/webapp/api/test_failureline.py, tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_note_api.py, tests/webapp/api/test_resultset_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1416)
=> Bug 1266398 - Remove unnecessary calls to jm.disconnect() from tests

tests/webapp/api/test_jobs_api.py, treeherder/model/derived/jobs.py, ui/css/treeherder-navbar-panels.css, ui/js/controllers/sheriff.js, ui/js/models/resultset.js, ui/js/models/resultsets_store.js, ui/partials/main/thSheriffPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1409)
=> Bug 1264495 - honor visibility url param to see what jobs are excluded

treeherder/model/migrations/0016_enforce repository name uniqueness.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1422)
=> Bug 1266879 - Enforce uniqueness on repository name

treeherder/webapp/api/bugzilla.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1419)
=> Bug 1266619 - add an accept header to the bug filer's request to bugzilla

ui/partials/main/thPinboardPanel.html, ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1398)
=> Bug 1263078 - Don't allow classifications without putting some effort into it

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/migrate_to_intermediate_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1425)
=> Bug 1265037 - Enable dynamic intermediate job ingestion

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1401)
=> Bug 1263327 - Don't append job signatures to existing searchStr query params, just overwrite them

tests/autoclassify/test_classify_failures.py, treeherder/model/migrations/0018_merge_duplicate_classifications.py, treeherder/model/migrations/0019_bug_number_unique.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1427)
=> Bug 1265188 - Enforce uniqueness constraint on classified failure bug numbers.

ui/css/perf.css, ui/js/controllers/perf/graphs.js, ui/partials/perf/testdatachooser.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1428)
=> Bug 1234872 - Don't show subtests in performance data chooser

treeherder/model/fixtures/repository.json, treeherder/model/fixtures/repository_group.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1440)
=> Bug 1268802 - Add servo repository

tests/model/derived/test_jobs_model.py, treeherder/model/management/commands/cycle_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1429)
=> Bug 1268593 - Cycle job type / group / runnable job reference data

treeherder/model/models.py, ui/css/treeherder-info-panel.css, ui/plugins/auto_classification/controller.js, ui/plugins/auto_classification/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1437)
=> Bug 1268330 - Show all bug suggestions in the autoclassify panel

treeherder/model/fixtures/repository.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1267277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1441)
=> Bug 1267277 - Add the version-control-tools repository

treeherder/model/fixtures/repository.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1267716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1442)
=> Bug 1267716 - Add the Autoland repository

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1439)
=> Bug 1268676 - fix key errors on resultsets with 12 char revisions

tests/conftest.py, tests/webapp/api/test_bug_job_map_api.py, tests/webapp/api/test_bugzilla.py, tests/webapp/api/test_classified_failure.py, tests/webapp/api/test_failureline.py, tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_note_api.py, tests/webapp/api/test_performance_alerts_api.py, tests/webapp/api/test_performance_alertsummary_api.py, tests/webapp/api/test_resultset_api.py, tests/webapp/api/test_text_log_summary_lines.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1443)
=> Bug 1269433 - Consolidate user creation in tests into fixtures

treeherder/model/fixtures/repository.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1268958
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1454)
=> Bug 1268958 - Add the autopush repository

tests/etl/test_buildbot.py, treeherder/etl/buildbot.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1263315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1444)
=> Bug 1263315 - Add support for partner repack jobs

tests/model/derived/test_artifacts_model.py, tests/webapp/api/test_failureline.py, treeherder/model/derived/artifacts.py, treeherder/model/derived/jobs.py, treeherder/model/error_summary.py, treeherder/model/tasks.py, treeherder/webapp/api/artifact.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1461)
=> Bug 1270561 - Use intermediate jobs as lookup when ingesting artifacts

tests/etl/test_buildbot.py, treeherder/etl/buildbot.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1263316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1459)
=> Bug 1263316 - Support update-verify jobs

ui/js/controllers/perf/graphs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1467)
=> Bug 1269842 - Fix getting same series on different branches in graphs UI

ui/js/controllers/perf/compare.js, ui/js/controllers/perf/e10s.js, ui/js/controllers/perf/graphs.js, ui/js/perf.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1468)
=> Bug 1270970 - Account for performance framework through perfherder graphs

tests/e2e/test_client_job_ingestion.py, tests/etl/test_job_loader.py, tests/log_parser/test_tasks.py, tests/model/derived/test_jobs_model.py, tests/webapp/api/test_job_details_api.py, treeherder/model/derived/artifacts.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/migrate_job_info_artifacts.py, treeherder/model/migrations/0021_add_jobdetail_model.py, treeherder/model/models.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/serializers.py, treeherder/webapp/api/urls.py, ui/index.html, ui/js/controllers/logviewer.js, ui/js/models/job_detail.js, ui/logviewer.html, ui/plugins/controller.js, ui/plugins/job_details/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1462)
=> Bug 1270629 - Replace Job Info artifacts with a "jobdetail" model

tests/autoclassify/test_classify_failures.py, tests/autoclassify/test_detect_intermittents.py, tests/conftest.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1480)
=> Bug 1271591 - Enable disabled autoclassification tests.

treeherder/model/fixtures/performance_framework.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1476)
=> Bug 1271472 - Add a performance framework for servo

tests/e2e/test_client_job_ingestion.py, tests/etl/test_job_loader.py, tests/log_parser/test_tasks.py, tests/model/derived/test_artifacts_model.py, tests/model/derived/test_jobs_model.py, tests/webapp/api/test_job_details_api.py, treeherder/model/derived/artifacts.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/migrate_job_info_artifacts.py, treeherder/model/migrations/0021_add_jobdetail_model.py, treeherder/model/models.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/serializers.py, treeherder/webapp/api/urls.py, ui/index.html, ui/js/controllers/logviewer.js, ui/js/models/job_detail.js, ui/logviewer.html, ui/plugins/controller.js, ui/plugins/job_details/main.html
This incorporates a bunch of fixes needed when pushing to stage. It also
keeps on ingesting job info artifacts for now, in case we need to revert
these changes for some reason.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1475)
=> Bug 1270629 - Take 2

tests/autoclassify/test_classify_failures.py, tests/autoclassify/utils.py, tests/conftest.py, tests/webapp/api/test_failureline.py, treeherder/autoclassify/matchers.py, treeherder/model/migrations/0021_add_index_failureline_signature.py, treeherder/model/migrations/0022_add_index_failureline_signature.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1481)
=> Bug 1271598 - Crash matcher based on literal signature matching.

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/cycle_data.py, treeherder/model/migrations/0023_simplify_machine_model.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1487)
=> Bug 1271723 - Further optimize the machine table (and cycle its data)

ui/css/perf.css, ui/partials/perf/graphsctrl.html
The graph popup close button as you requested @wlach
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1498)
=> Bug 1263173 - Use bootstrap-style close button for graph popup

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1499)
=> Bug 1273616 - Add the NSS repository

tests/autoclassify/test_classify_failures.py, treeherder/model/derived/artifacts.py, treeherder/model/error_summary.py, ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1436)
=> Bug 1268331, 1268333 - Improve blacklist of useless log lines

ui/js/controllers/perf/alerts.js, ui/partials/perf/alertsctrl.html
I generated a list of downstream alerts and displayed them on the html according to the style suggested in the bug report. Have a look @wlach
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1495)
=> Bug 1247028 - Downstream alerts comment.

ui/js/controllers/jobs.js, ui/js/controllers/sheriff.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1504)
=> Bug 1274099 - Clarify confirm() dialogs a bit

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1506)
=> Bug 1274377 - Update NSS repository entry

ui/js/directives/treeherder/top_nav_bar.js, ui/partials/main/thWatchedRepo.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1503)
=> Bug 1274040 - Make spinner pulse when loading tree status

ui/js/controllers/main.js, ui/js/directives/treeherder/resultsets.js, ui/js/values.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/683)
=> Bug 1045602 - Port TBPL's feature to add a single revision's details to the page title

bin/run_pulse_ingestion
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1514)
=> Bug 1266584 - Create ingest_from_pulse command script for supervisord

ui/partials/main/thMultiSelect.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1513)
=> Bug 1275695 - Make filtering in job exclusion panel much faster and smoother

treeherder/webapp/api/logslice.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1517)
=> Bug 1275796 - Update logslice API to use new job log ORM class

tests/conftest.py, tests/etl/test_bugzilla.py, tests/etl/test_buildapi.py, treeherder/etl/allthethings.py, treeherder/etl/bugzilla.py, treeherder/etl/buildapi.py, treeherder/etl/mixins.py
Another step in switching away from urllib2 :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1519)
=> Bug 1240809 - Use fetch_json instead of the urllib2 JsonExtractorMixin

treeherder/etl/bugzilla.py
Removes usage of urllib & improves readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1525)
=> Bug 1276219 - Refactor BzApiBugProcess / get_bz_source_url

bin/pre_deploy
This will give us greater visibility into slow migrations and help correlate them against any perf issues seen elsewhere at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1526)
=> Bug 1276249 - Heroku: Wrap deploy migration/init with newrelic wrapper

tests/webapp/api/test_logslice_api.py, treeherder/webapp/api/logslice.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1521)
=> Bug 1275903 - Add unit tests for logslice API

docs/common_tasks.rst, docs/index.rst, docs/rest_api.rst, docs/retrieving_data.rst, docs/submitting_data.rst
I've split the docs changes out of #1482, since I need them to land prior to the newsgroup post, so it can link to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1534)
=> Bug 1267683 - Docs: Describe the upcoming User Agent requirements

ui/partials/main/thHelpMenu.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1197988
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1536)
=> Bug 1197988 - Link to the Treeherder mailing list from the help menu

docs/common_tasks.rst, treeherder/client/thclient/client.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1269715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1537)
=> Bug 1269715 - Docs: Add steps for releasing a new Python client version

docs/Makefile, docs/installation.rst, docs/troubleshooting.rst, requirements/docs.txt
Most of this based on earlier work by @armenzg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1545)
=> Doc updates

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1550)
=> Bug 1276178 - Load performance data regardless of job status.

ui/partials/perf/graphsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1556)
=> Bug 1260791 - Disable create alert UI if not logged in as sheriff

treeherder/perf/fixtures/test_performance_data.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1551)
=> Bug 1276934 - Fix improperly added fake performance data fixture

tests/webapp/api/test_logslice_api.py, treeherder/webapp/api/logslice.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1555)
=> Bug 1277499 - Handle non-gzipped files in logslice API

tests/log_parser/test_store_failure_lines.py, treeherder/log_parser/failureline.py
This matches the behaviour of fetching the full logs and represents
a belief that 404 errors will not magically correct themselves when
we retry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1554)
=> Bug 1277506 - Don't raise an error when storing failure lines generates 403/404.

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1558)
=> Bug 1277024 - Specify framework when linking to graphs from jobs ui

treeherder/config/settings.py, treeherder/etl/management/commands/read_pulse_jobs.py
I flurbed on this.  Got it wrong in the settings when I copied things over from my local settings.
Sorry for the busy work...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1557)
=> Bug 1277724 - change pulse binding api to pulseguardian.m.o

contribute.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1563)
=> Bug 1186912 - Add a contribute.json file

ui/js/directives/treeherder/clonejobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1562)
=> Bug 1278018 - Increase the scroll offset when selecting jobs

tests/webapp/api/test_job_details_api.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/serializers.py, ui/js/models/job_detail.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1570)
=> Bug 1278597 - Add job_id__in and repository filtering to /jobdetail/ endpoint

treeherder/webapp/api/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1571)
=> Bug 1278597 - Increase the limit / count of jobdetail objects returned

ui/js/controllers/perf/alerts.js, ui/partials/perf/bugzilla_talos.tmpl
Remove try syntax and links to documentation for specific tests in favor
of just linking to general resources. Shorter and simpler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1552)
=> Bug 1277364 - Simplify talos bugzilla template

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1575)
=> Bug 1278952 - Fix detail panel JS exception when no logs exist

treeherder/autoclassify/matchers.py, treeherder/model/migrations/0027_failure_line_idx_signature_test.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1576)
=> Bug 1278962 - Fix some small performance issues with autoclassification

tests/test_worker/test_task.py, treeherder/autoclassify/tasks.py, treeherder/workers/task.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1574)
=> Bug 1278858 - Add retryable_task decorator that provides the ability to not retry for given exceptions

treeherder/workers/task.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1584)
=> Don't retry tasks for ProgrammingError.

treeherder/webapp/api/performance_serializers.py, ui/js/models/perf/alerts.js, ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1560)
=> Bug 1262981 - Filter subtests in graph view and show link when subtests are present

tests/webapp/api/test_performance_bug_template_api.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1586)
=> Bug 1260805 - Add unit test for bug template API

docs/ui/installation.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1590)
=> Bug 1280185 - Mention npm install earlier in the UI docs

schemas/pulse-job.yml, tests/sample_data/pulse_consumer/job_data.json, tests/sample_data/pulse_consumer/transformed_job_data.json, treeherder/etl/job_loader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1600)
=> Bug 1280306 - Add buildSystem field to pulse-job.yml

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1597)
=> Bug 1229077 - Move the gaia repo to the try repo group

ui/partials/main/thSheriffPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1595)
=> Bug 1117564 - Linkify bugs in job exclusion descriptions

tests/perfalert/test_analyze.py, treeherder/perf/alerts.py, treeherder/perf/management/commands/test_analyze_perf.py, treeherder/perfalert/perfalert/__init__.py
Here are initial changes to __init__.py. Will be posting changes to related files soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1581)
=> Bug 1276905 - Performance alert analysis code doesn't need its own class

ui/js/filters.js, ui/plugins/pluginpanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1591)
=> Bug 1240578 - Try to linkify SHA shortrevs

treeherder/webapp/api/resultset.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1593)
=> Bug 1221485 - Don't allow count to exceed the upper limit on resultsets

treeherder/webapp/api/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1594)
=> Bug 1203551 - Don't allow count to exceed MAX_JOBS_COUNT in the jobs api

ui/css/treeherder-navbar-panels.css, ui/partials/main/thSheriffPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1598)
=> Bug 1244989 - Move the 'add profile' and 'add exclusion' buttons to the top of the sheriff panel

treeherder/etl/pushlog.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1606)
=> Bug 1280913 - Don't go via HTTP API when submitting result_set data

tests/webapp/api/test_bugscache.py, treeherder/config/settings.py, treeherder/model/error_summary.py, treeherder/model/models.py, treeherder/webapp/api/refdata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1605)
=> Bug 1280910 - Don't use HTTP API when looking up bug suggestions

treeherder/autoclassify/matchers.py, treeherder/etl/buildapi.py, treeherder/etl/job_loader.py, treeherder/etl/pushlog.py, treeherder/model/derived/jobs.py, treeherder/model/fields.py, treeherder/model/management/commands/migrate_job_logs.py, treeherder/model/management/commands/migrate_to_intermediate_jobs.py, treeherder/model/utils.py, treeherder/perf/management/commands/migrate_perf_signature_subtest_schema.py, treeherder/perf/management/commands/remove_single_test_summaries.py, treeherder/webapp/api/artifact.py, treeherder/webapp/api/bug.py, treeherder/webapp/api/bugzilla.py, treeherder/webapp/api/classifiedfailure.py, treeherder/webapp/api/exceptions.py, treeherder/webapp/api/failureline.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/logslice.py, treeherder/webapp/api/note.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/refdata.py, treeherder/webapp/api/resultset.py, treeherder/webapp/api/text_log_summary_line.py, treeherder/webapp/api/utils.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1588)
=> Bug 1279880 - Misc code style/best practices cleanup

tests/webapp/api/test_bugscache.py, treeherder/model/models.py
This is not trivially JSON serializable and is not used, so just
exclude it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1609)
=> Bug 1280910 - Don't return modified field for bug suggestions.

tests/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1612)
=> Bug 1281516 - Correct the spelling of 'unknown'

treeherder/etl/buildbot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1613)
=> Bug 1281620 - Switch a link from mxr to dxr in a comment

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1614)
=> Bug 1281601 - Don't try to switch to performance tab if no perf data

tests/log_parser/test_store_failure_lines.py, treeherder/log_parser/failureline.py, treeherder/log_parser/tasks.py
If it happens that the failure lines for a log are partially stored,
retry storing only the missing lines. In the case that this doesn't
fix the problem, don't try to retry at the celery level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1615)
=> Bug 1281809 - Handle IntegrityError when storing failure lines.

tests/webapp/api/test_bugzilla.py, treeherder/webapp/api/bugzilla.py, ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1616)
=>  Bug 1281808 - Check to make sure product, component, summary, and version are defined before attempting to file the bug

tests/conftest.py, treeherder/model/fixtures/failure_classification.json, treeherder/model/fixtures/repository_group.json, treeherder/model/migrations/0029_remove_named_model_metadata.py, treeherder/model/models.py
* Remove unused members from NamedModel (define in subclass where really
needed)
* Enforce uniqueness on name properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1624)
=> Bug 1282907 - Fix named models to be more sane

ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1625)
=> Bug 1254325 - Fixing the small UI error for TaskCluster Add New Jobs

ui/js/directives/treeherder/clonejobs.js, ui/js/providers.js, ui/js/services/pinboard.js, ui/partials/main/thShortcutTable.html, ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1603)
=> Bug 1256751 - Make ctrl-click toggle pinning, not just pinning always

.travis.yml, puppet/manifests/vagrant.pp, requirements/common.txt, tests/autoclassify/test_classify_failures.py, tests/autoclassify/utils.py, tests/conftest.py, tests/log_parser/test_store_failure_lines.py, tests/model/derived/test_jobs_model.py, tests/settings.py, tests/webapp/api/test_failureline.py, treeherder/autoclassify/management/commands/autoclassify.py, treeherder/autoclassify/management/commands/es_benchmark.py, treeherder/autoclassify/matchers.py, treeherder/config/settings.py, treeherder/log_parser/failureline.py, treeherder/model/derived/jobs.py, treeherder/model/management/commands/es_import_failure_lines.py, treeherder/model/models.py, treeherder/model/search.py, treeherder/model/utils.py, treeherder/webapp/api/failureline.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1488)
=> Bug 1268484 - Add elastic-search based matcher for test failure lines

treeherder/model/migrations/0030_remove_machine_double_index.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1628)
=> Bug 1283087 - Machine reference data model should inherit from NamedModel

treeherder/perf/fixtures/performance_bug_templates.yaml, ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1621)
=> Bug 1270524 - Display textual summary of what regressed

treeherder/model/models.py
…ection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1636)
=> Bug 1283252 - Only try to insert into elasticsearch if we have a connection.

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1631)
=> Bug 1283298 - Add the NSS try repository

treeherder/model/migrations/0031_bump_max_name_length.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1637)
=> Bug 1283510 - Bump max length of name field in named models

treeherder/log_parser/utils.py, treeherder/webapp/api/artifact.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1638)
=> Bug 1281058 - Don't go via the HTTP API for creating artifacts during log parsing

ui/plugins/auto_classification/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1641)
=> Bug 1268242 - Open all links from autoclassification panel in new window/tab

tests/conftest.py, tests/e2e/test_perf_ingestion.py, tests/etl/test_perf_data_adapters.py, tests/webapp/api/test_performance_bug_template_api.py, tests/webapp/api/test_performance_data_api.py, treeherder/etl/perf.py, treeherder/perf/fixtures/performance_framework.json, treeherder/perf/migrations/0017_add_performanceframework_enabled.py, treeherder/perf/migrations/0018_merge.py, treeherder/perf/models.py, treeherder/webapp/admin.py
Here are the changes without the pytests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1620)
=> Bug 1273983 - Allow enabling/disabling a performance framework

ui/js/controllers/jobs.js, ui/partials/main/jobs.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1645)
=> Bug 1278800 - Making Cancel All Jobs cancel only selected Job

ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1650)
=> Bug 1284512 - Handle alert filtering when hitting select all / select none

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1652)
=> Bug 1284595 - Compare link in performance tab incomplete

treeherder/webapp/api/performance_data.py, ui/js/controllers/perf/alerts.js, ui/js/models/perf/alerts.js, ui/js/perfapp.js, ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1632)
=> Bug 1263699 - Use pagination in perfherder instead of ``Get more``

ui/css/treeherder-navbar.css, ui/js/directives/treeherder/top_nav_bar.js, ui/partials/main/thWatchedRepoNavPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1596)
=> Bug 1120477 - Change the hidden jobs toggle's glyphs to something hopefully more discoverable

docs/pulseload.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1656)
=> Bug 1266229 - Pulse doc fix for link to YML

ui/js/controllers/perf/alerts.js, ui/js/models/perf/alerts.js, ui/js/perf.js, ui/partials/perf/alertsctrl.html, ui/perf.html, ui/vendor/angular-clipboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1646)
=> Bug 1284325 - Add ability to copy summary of changes in alert to clipboard

ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1659)
=> Bug 1270524 - Improve formatting of textual description of alert summary

treeherder/config/settings.py, treeherder/webapp/api/resultset.py, treeherder/webapp/api/runnable_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1633)
=> Bug 1282906 - Fix a few issues in the schedule TC jobs patch

docs/rest_api.rst, puppet/manifests/classes/dev.pp, tests/conftest.py, treeherder/config/settings.py, treeherder/credentials/management/commands/create_credentials.py, treeherder/credentials/migrations/0003_allow_credentials_with_no_owner.py, treeherder/credentials/models.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1653)
=> Bug 1284853 - Hawk credential cleanup now that ETL no longer posts to our API

ui/plugins/failure_summary/controller.js, ui/plugins/failure_summary/main.html
How about this, then, instead?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1657)
=> Bug 1285046 - Improve the wording of the 'Max suggestions exceeded' error

treeherder/model/fixtures/repository.json, ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1660)
=> Bug 1283693 - Update perfherder settings for new autoland branch

tests/test_setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1663)
=> Bug 1284883 - Add a unit test making sure load_initial_data works

tests/conftest.py, tests/webapp/api/test_performance_alerts_api.py, treeherder/webapp/api/performance_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1664)
=> Bug 1285521 - Generate correct values for manually-generated alerts

ui/js/controllers/jobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1672)
=> Bug 1278800 - Fix harmless console error when user is not logged in

tests/model/test_bugscache.py, treeherder/webapp/api/refdata.py, treeherder/webapp/api/urls.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1676)
=> Bug 1281044 - Remove the bugscache API endpoint

ui/css/treeherder-navbar.css, ui/js/directives/treeherder/top_nav_bar.js, ui/partials/main/thWatchedRepoNavPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1679)
=> Bug 1286314 - Use correct font with new "hidden jobs" text in navbar

ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1683)
=> Bug 1284275 - Fix modal dialogs in perfherder alert views

docs/data_validation.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1684)
=> Fix typo in code example for data validation

docs/common_tasks.rst, docs/installation.rst, docs/list_of_services.rst, tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py, treeherder/model/models.py, treeherder/webapp/api/jobs.py, ui/js/providers.js, ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1686)
=> minor spelling fixes

ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1689)
=> Bug 1286891 - Don't include TEST-UNEXPECTED-TIMEOUT in bugfiler's omittedLeads

ui/js/controllers/logviewer.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1680)
=> Bug 1286382 - Fix console errors about undefined $event in log viewer

ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1693)
=> Bug 1284275 - Another fix for reassign perf alerts dialog

ui/js/controllers/perf/graphs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1705)
=> Bug 1287679 - Make highlighting an alert work again

treeherder/webapp/api/runnable_jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1710)
=> Bug 1288053 - Fixing failing Add New Jobs due to new TaskGraph changes

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1713)
=> Bug 1288230 - Show autoclassify panel by default for sheriffs

treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1699)
=> Bug 1284432 - Delete failure lines from es in chunks to prevent slow queries.

tests/model/test_search.py, treeherder/model/search.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1700)
=> Bug 1283253 - Don't require a subtest name in elasticsearch.

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1661)
=> Bug 1277993 - Improve mechanism for excluding jobs and setting tiers

docs/submitting_data.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1690)
=> Bug 1286939 - Instructions for registering a Pulse Job Exchange

treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1715)
=> Bug 1284432 - Refactor the code for deleting chunks of failure lines from elasticsearch to make the intent clearer

treeherder/perf/fixtures/performance_bug_templates.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1712)
=> Bug 1288221 - Add a performance bug template for build_metrics

.eslintrc, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/graphs.js, ui/js/directives/treeherder/clonejobs.js, ui/js/models/job.js, ui/js/models/resultset.js, ui/js/perf.js, ui/js/services/main.js, ui/plugins/auto_classification/controller.js, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1721)
=> Bug 1289127 - Enable eslint "no-multi-spaces" rule

ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1724)
=> Bug 1285004 - Use httpParamSerializer

tests/webapp/api/test_failureline.py, treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1728)
=> Bug 1289354 - Fix regression creating job bug associations after verifying classifications.

treeherder/webapp/api/classifiedfailure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1727)
=> Bug 1289404 - Convert set of integers to strings before trying to construct error message

treeherder/perf/fixtures/performance_bug_templates.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1730)
=> Bug 1289408 - Fix typo in talos perfherder bug template

ui/js/models/resultsets_store.js
For this case, we should just refetch everything rather than looking for
updates (since we don't have a "last modified" time to key off of)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1729)
=> Bug 1287501 - Poll for pushes with no jobs associated with them correctly

ui/js/directives/treeherder/persona.js, ui/plugins/controller.js
Use it to display the autoclassify panel if appropriate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1731)
=> Broadcast an event when the logged in user changes.

ui/plugins/controller.js
Reverts mozilla/treeherder#1713
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1738)
=> Revert "Bug 1288230 - Show autoclassify panel by default for sheriffs"

ui/partials/perf/graphsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1734)
=> Bug 1289329 - Display AlertSummary status if Alert is acknowledged

tests/perfalert/test_create_alerts.py, tests/webapp/api/test_performance_alerts_api.py, tests/webapp/api/test_performance_alertsummary_api.py, treeherder/perf/migrations/0019_performancealert_classifier.py, treeherder/perf/models.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1718)
=> Bug 1288530 - Add a "classifier" field to PerformanceAlert, referencing the user model

ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1737)
=> Bug 1269825 - Auto load mozilla-aurora data for mozilla-beta alerts

ui/css/treeherder-resultsets.css, ui/index.html, ui/js/directives/treeherder/clonejobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1706)
=> Bug 1287911 - Add the ability to tag revisions with metadata

treeherder/webapp/api/performance_data.py, ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1742)
=> Bug 1288530 - Update classifier unconditionally, and move classifier tooltip in AlertView

ui/js/directives/treeherder/clonejobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1735)
=> Bug 1289651 - Only scroll job into view if it's not already visible

ui/js/controllers/perf/alerts.js, ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1741)
=> Bug 1285368 - Add more details to the clipboard for copy summary

ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1747)
=> Bug 1289726 - Fix subtest compare view window title and header

tests/etl/test_bugzilla.py, tests/model/test_bugscache.py, tests/sample_data/bug_list.json, treeherder/etl/bugzilla.py, treeherder/etl/management/commands/update_bugscache.py
* UTF-8 characters in summary
* Summary exceeds 255 characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1732)
=> Bug 1289574 - Handle various edge cases with bugzilla mirroring

treeherder/config/settings.py
Celery uses Kombu to connect to the RabbitMQ instance, which defaults to not enabling SSL, unless the URL scheme is `amqps://` or the query string contains `ssl=1` / `ssl=true`.
On Heroku we're using CloudAMQP, who don't use either string in their automatically defined `CLOUDAMQP_URL` environment variable, so we must set the Celery preference `BROKER_USE_SSL` to ensure TLS is still used:
http://docs.celeryproject.org/en/latest/configuration.html#broker-use-ssl
I've contacted CloudAMQP to encourage them to use `amqps://` in their URLs, however even if they do switch, using `BROKER_USE_SSL` is a sensible defence-in-depth measure we should take regardless.
TLS support isn't set up for the rabbitmq servers on SCL3, Travis or in the Vagrant environment, so `BROKER_USE_SSL` must not be set …
=> Bug 1286702 - Enable TLS for Celery RabbitMQ connections that support it

tests/webapp/api/test_classified_failure.py, treeherder/model/models.py, treeherder/webapp/api/classifiedfailure.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1749)
=> Bug 1289406 - Handle multiple classifications with the same bug id better.

ui/js/providers.js, ui/plugins/auto_classification/controller.js, ui/plugins/controller.js
This allows us to force an update of the rest of the UI in response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1743)
=> Bug 1290134 - Send an event when one or more classifications are verified.

ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1744)
=> Bug 1290127 - Update fetchJob to work with id rather than guid

ui/js/controllers/jobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1752)
=> Bug 1290525 - Fix cancelling buildbot jobs from revision bar

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1756)
=> Bug 1288230 - Show autoclassify panel by default for sheriffs (#1713)

tests/settings.py, tests/webapp/api/test_text_log_summary_lines.py, treeherder/config/settings.py, treeherder/model/derived/jobs.py, treeherder/webapp/api/text_log_summary_line.py
This is required to create the BugJobMap instance in the post-datasource world.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1760)
=> Bug 1292270 - Pass a User object down to JobManager.update_after_verification.

tests/model/test_error_summary.py, treeherder/model/error_summary.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1761)
=> Bug 1292338 - Remove reftest references from error summary search terms.

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1764)
=> Bug 1292834 - Add an opt out for autoclassify UI

ui/css/treeherder-info-panel.css, ui/plugins/auto_classification/main.html
This makes them clickable to select the corresponding radio input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1766)
=> Bug 1292672 - Put autoclassification radio labels inside a <label> element.

ui/css/treeherder-info-panel.css, ui/plugins/auto_classification/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1765)
=> Bug 1292643 - Flip the Ignore/Save All buttons to the other side of the panel and prevent them scrolling

ui/js/controllers/main.js, ui/js/providers.js, ui/partials/main/thShortcutTable.html, ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1767)
=> Bug 1293224 - Add 'a' keyboard shortcut for Ignore All autoclassification option

ui/js/services/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1758)
=> Bug 1291955 - Show a better error if we've managed to lose authentication when classifying failures

ui/css/treeherder-bugfiler.css, ui/js/controllers/bugfiler.js, ui/partials/main/intermittent.html
Breaking this out so it can land independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1773)
=> Bug 1278746 - Restrict the summary field to 255 characters

ui/plugins/auto_classification/controller.js, ui/plugins/auto_classification/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1768)
=> Bug 1293337 - Disable 'Save All' button when the user is not logged in

ui/js/controllers/bugfiler.js, ui/partials/main/intermittent.html
Breaking this out so it can land independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1772)
=> Bug 1278746 - Make 'intermittent-failure' keyword optional

tests/ui/unit/controllers/autoclassify.tests.js, ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1748)
=> Bug 1290231 - Clarify ui building code for failure line option classification

ui/index.html, ui/js/controllers/main.js, ui/js/directives/treeherder/main.js, ui/partials/main/thPinboardPanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1778)
=> Bug 1294155 - Don't disable keyboard shortcuts when input type=checkbox|radio have focus.

ui/js/controllers/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1782)
=> Bug 1294155 - Make ctrl+enter work irrespective of which element has focus.

.eslintrc, ui/js/controllers/bugfiler.js, ui/js/controllers/filters.js, ui/js/controllers/jobs.js, ui/js/controllers/logviewer.js, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/graphs.js, ui/js/filters.js, ui/js/models/repository.js, ui/js/models/resultset.js, ui/js/models/resultsets_store.js, ui/js/models/user.js, ui/js/perf.js, ui/js/providers.js, ui/js/services/jobfilters.js, ui/js/services/jsonpushes.js, ui/plugins/auto_classification/controller.js, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1780)
=> Bug 1294494 - Enable no-else-return eslint rule

schemas/performance-artifact.json, tests/etl/test_perf_schema.py
Especially make sure that we have no "infinite" values, as those can
cause exceptions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1786)
=> Bug 1295536 - Validate that perfherder values are within acceptable ranges

schemas/performance-artifact.json, tests/etl/test_perf_schema.py, tests/log_parser/test_performance_parser.py, treeherder/log_parser/parsers.py, treeherder/workers/task.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1789)
=> Bug 1295536 - Validate that perfherder values are within acceptable ranges - take 2

.eslintrc, ui/js/directives/treeherder/clonejobs.js, ui/js/models/exclusion_profile.js, ui/js/models/repository.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1790)
=> Bug 1296044 - Enable no-lonely-if eslint rule

ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1793)
=> Bug 1296057 - Pin the selected job upon opening bugfiler

ui/logviewer.html, ui/partials/main/thHelpMenu.html, ui/partials/main/thInfraMenu.html, ui/plugins/job_details/main.html, ui/plugins/perf_details/main.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1794)
=> Bug 1295382 - Switch a bunch of URLs to https

ui/logviewer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1797)
=> Bug 1296553 - Make the revision link point directly to the log's job

ui/js/controllers/main.js, ui/plugins/failure_summary/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1792)
=> Bug 1296071 - Prevent main UI keyboard shortcuts while the bugfiler is open

ui/partials/main/jobs.html, ui/vendor/angular/angular-animate.js, ui/vendor/angular/angular-aria.js, ui/vendor/angular/angular-cookies.js, ui/vendor/angular/angular-loader.js, ui/vendor/angular/angular-message-format.js, ui/vendor/angular/angular-messages.js, ui/vendor/angular/angular-mocks.js, ui/vendor/angular/angular-resource.js, ui/vendor/angular/angular-route.js, ui/vendor/angular/angular-sanitize.js, ui/vendor/angular/angular-touch.js, ui/vendor/angular/angular.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1796)
=> Bug 1296383 - Upgrade Angular to version 1.5.8

ui/js/models/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1801)
=> Bug 1294798 - Order of alerts in textual summary in order of severity

.eslintrc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1806)
=> Bug 1297722 - Allow ES6 features to pass eslint

ui/js/controllers/jobs.js, ui/partials/main/thPinnedJob.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1805)
=> Bug 1297696 - Remove broken and unused pinboard code

ui/js/models/classified_failure.js, ui/js/models/failure_lines.js, ui/js/models/text_log_summary_line.js, ui/js/providers.js, ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1823)
=> Bug 1292651 - Work around an angular bug where promises resolve in the wrong order.

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1820)
=> Bug 1298558 - Show automation for stylo and stylo-try repos

ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1813)
=> Bug 1298457 - Make sure autoclassify tab is shown when it should

tests/ui/unit/filtersSpec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1828)
=> Bug 1299946 - Add some tests for filters.js

tests/log_parser/test_store_failure_lines.py, treeherder/etl/text.py, treeherder/log_parser/failureline.py, treeherder/model/management/commands/migrate_text_log_artifacts.py, treeherder/model/migrations/0038_text_log_db.py, treeherder/model/models.py
* Model updates, new db tables, migration script for text log db
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1822)
=> Bug 1258861 - Preparatory work for storing text log steps / errors in main db

treeherder/workers/task.py
Since the task will fail every time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1844)
=> Bug 1301700 - Don't retry tasks that fail due to UnicodeDecodeError

tests/log_parser/test_error_parser.py, treeherder/log_parser/parsers.py
Upcoming changes in bug 1295380 will change log output for many tests
in TaskCluster resulting in lines being prefixed with a timestamp and
the task step name. Unless these line prefixes are handled, it
confuses the error parser.
This commit detects logs as coming from TaskCluster and strips their
line prefix accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1842)
=> Bug 1297184 - Strip TaskCluster log prefix when parsing logs

ui/js/controllers/logviewer.js, ui/logviewer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1845)
=> Bug 1302224 - Fix link to raw log in logviewer

tests/e2e/test_client_job_ingestion.py, tests/webapp/api/test_job_details_api.py, treeherder/model/derived/artifacts.py, treeherder/model/management/commands/migrate_buildapi_artifacts.py, treeherder/webapp/api/jobs.py, ui/js/controllers/jobs.js, ui/js/controllers/logviewer.js, ui/js/models/job_detail.js, ui/js/models/resultsets_store.js, ui/plugins/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1840)
=> Bug 1301729 - Store buildbot request id as a job detail

treeherder/perf/alerts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1846)
=> Bug 1301702 - Fix race when creating a performance alert (server side)

tests/ui/config/karma.conf.js, ui/admin.html, ui/js/controllers/admin/admin.js
trying to determine the illegal character in the node ui tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1860)
=> Bug 1303215 - Fix UI test failure due to lack of es6 support

tests/webapp/api/test_job_log_url_api.py, treeherder/webapp/api/job_log_url.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1865)
=> Bug 1304148 - Fixes / improvements to job-log-url endpoint

tests/webapp/api/test_job_details_api.py, treeherder/webapp/api/jobs.py
If not present, the server could be forced to process some really slow
queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1866)
=> Bug 1280039 - Enforce the presence of a suitable filter on the jobdetail endpoint

treeherder/client/thclient/client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1862)
=> Bug 1303816 - Add a method for getting job details to python client

schemas/resultset-runnable-job-action-message.json, treeherder/model/tasks.py, treeherder/webapp/api/resultset.py, treeherder/webapp/api/runnable_jobs.py, ui/js/models/resultset.js, ui/js/models/resultsets_store.js
Changed naming convention from decisionTaskID to decision_task_id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1819)
=> Bug 1286897 - Change references of decisionTaskID to decision_task_id

treeherder/client/thclient/client.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1870)
=> Bug 1304420 - Bump treeherder python client to version 3.1.0

tests/webapp/api/test_job_log_url_api.py, treeherder/webapp/api/job_log_url.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1873)
=> Bug 1304557 - Allow passing multiple job_id parameters to job log url endpoint

ui/plugins/pinboard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1875)
=>  	Bug 1305507 - Save whatever's typed into the bug field before seeing if we can save the classification

ui/js/controllers/main.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1877)
=> Bug 1305859 - Make sure HTML-encoded characters render correctly in the title

ui/js/components/perf/compare.js, ui/js/controllers/perf/e10s-trend.js, ui/js/controllers/perf/e10s.js, ui/js/perfapp.js, ui/js/services/perf/compare.js, ui/js/values.js, ui/partials/perf/e10s-trend-subtest.html, ui/partials/perf/e10s-trend.html, ui/partials/perf/trendtable.html, ui/perf.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1863)
=> Bug 1288007 - Add e10s-trend dashboard

tests/etl/test_job_loader.py, tests/model/derived/test_jobs_model.py, tests/test_worker/test_pulse_tasks.py, treeherder/etl/job_loader.py, treeherder/etl/tasks/pulse_tasks.py, treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1872)
=> Bug 1286578 - Retry job task if resultset doesn't exist

ui/plugins/auto_classification/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1885)
=> Bug 1292910 - Fix handling of text log summary model load errors in autoclassify panel

ui/js/components/perf/compare.js, ui/js/services/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1886)
=> Bug 1306601 - Fix e10s dashboard filtering

ui/admin.html, ui/perf.html
Otherwise, you can't login on those pages and if you were previously logged in, it will think you're not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1888)
=> Bug 1306760 - Import error.js on admin and perfherder

tests/etl/test_job_loader.py, tests/test_worker/test_pulse_tasks.py, treeherder/etl/job_loader.py, treeherder/etl/tasks/pulse_tasks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1892)
=> Bug 1306578 - Fix retry on pulse job ingestion

ui/partials/main/thActionButton.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1889)
=> Bug 1301986 - Standardize action menu_capitalization

treeherder/perf/fixtures/performance_framework.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1897)
=> Bug 1307695 - Add a performance framework for Hasal

treeherder/etl/job_loader.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1896)
=> Bug 1307490 - Include project in exception for missing resultset

docs/index.rst, docs/testcases.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1902)
=> Bug 1308328 - Add Treeherder test cases to docs

ui/logviewer.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1907)
=> Bug 1308557 - Make sure the reftest analyser works from the logviewer

treeherder/webapp/api/job_log_url.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1903)
=> Bug 1306903 - Return project specific id from job-log-url endpoint

bin/run_celery_worker_log_parser, tests/model/derived/test_jobs_model.py, treeherder/log_parser/tasks.py, treeherder/model/derived/jobs.py, treeherder/model/sql/jobs.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1906)
=> Bug 1308528 - Serialize ingestion of job data

tests/e2e/test_client_job_ingestion.py, treeherder/model/error_summary.py
It might be that they'll be updated later
=> Bug 1309521 - Don't cache empty bug suggestion lists

tests/webapp/api/test_jobs_api.py, treeherder/model/error_summary.py, treeherder/model/models.py, treeherder/webapp/api/jobs.py, treeherder/webapp/api/serializers.py, treeherder/webapp/api/text_log_summary.py
This includes all the bug suggestions and is therefore possible to
use directly for classification ui.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1917)
=> Bug 1309511 - Add a per-job text_log_error api endpoint

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1921)
=> Add the .vscode directory to .gitignore

treeherder/etl/perf.py, treeherder/perf/management/commands/remove_duplicate_signatures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1915)
=> Bug 1309294 - Don't use subtests in perf signature calculation

treeherder/workers/task.py
Since retries are not going to succeed either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1923)
=> Bug 1310053 - Don't retry tasks on ValueError

treeherder/perf/management/commands/remove_duplicate_signatures.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1924)
=> Bug 1309294 - Fixes to signature calculation

tests/model/derived/test_artifacts_model.py, treeherder/model/derived/artifacts.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1926)
=> Bug 1310262 - Process text log artifacts in an atomic transaction

tests/model/derived/test_jobs_model.py, treeherder/model/derived/jobs.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1913)
=> Bug 1308773 - Memoize calls to get per-project exclusion profiles

ui/js/logviewer.js, ui/js/treeherder_app.js, ui/plugins/failure_summary/controller.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1936)
=> Bug 1311436 - Cancel existing query before loading in failure summary

treeherder/webapp/api/refdata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1938)
=> Bug 1311511 - Fix unnecessary database querying in /api/repository/ endpoint

treeherder/webapp/api/refdata.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1944)
=> Bug 1312012 - Remove max_job_id return value from repository detail endpoint

requirements/common.txt
See individual commits for changelogs etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1943)
=> Bug 1302689 - Update Python common dependencies (part 2)

tests/log_parser/test_crossreference_error_lines.py, treeherder/log_parser/crossreference.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1942)
=> Bug 1311840 - Bail if we try to run crossreference_error_lines on a job with an existing TextLogSummary

ui/js/controllers/perf/alerts.js, ui/js/perfapp.js, ui/partials/perf/alertsctrl.html, ui/perf.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1882)
=> Bug 1272355 - Hide invalid/reassigned/downstream alerts by default

tests/log_parser/test_text_log_summary.py, treeherder/log_parser/management/commands/remove_duplicate_summaries.py
…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1946)
=> Bug 1311840 - Add temporary command to remove duplicate text_log_summary_line entries

ui/js/directives/treeherder/clonejobs.js
This doesn't comment EVERY function.  But the primary ones.  Should help enough to make it easier to follow, I hope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1928)
=> Bug 1310336 - Add comments to functions in clonejobs.js

ui/js/controllers/perf/alerts.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1961)
=> Bug 1268985 - Support filtering by bug number and revision

treeherder/perf/fixtures/performance_framework.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1962)
=> Bug 1313606 - Enabling the hasal performance framework

treeherder/perf/migrations/0020_remove_useless_perf_indexes.py, treeherder/perf/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1964)
=> Bug 1313760 - Remove useless indexes on performance tables

requirements/common.txt, tests/e2e/test_client_job_ingestion.py, tests/log_parser/test_tasks.py, treeherder/config/settings.py, treeherder/model/derived/artifacts.py, treeherder/model/error_summary.py, treeherder/model/models.py, treeherder/webapp/api/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1937)
=> Bug 1311465 - Replace uses of django-memoize with django's default cache

docs/installation.rst, treeherder/etl/management/commands/ingest_push.py, treeherder/etl/pushlog.py
Read the commit messages for rationale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1953)
=> Bug 1312809 - Pushlog ingest improvements

docs/pulseload.rst, treeherder/etl/pulse_consumer.py
See the commit messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1954)
=> Bug 1312839 - Pulse ingestion improvements

tests/etl/test_perf_data_adapters.py, tests/perfalert/test_create_alerts.py, tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_performance_data_api.py, tests/webapp/api/test_resultset_api.py, treeherder/config/settings.py, treeherder/etl/perf.py, treeherder/model/management/commands/migrate_bugjobmap_jobnote.py, treeherder/model/management/commands/migrate_resultset_orm.py, treeherder/perf/alerts.py, treeherder/perf/management/commands/create_test_perf_data.py, treeherder/perf/management/commands/import_perf_data.py, treeherder/webapp/api/performance_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1972)
=> Bug 1209474 - Change Django TIME_ZONE setting to UTC

treeherder/model/fixtures/repository.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1967)
=> Bug 1315050 - Mark fx-team as onhold

ui/js/directives/treeherder/clonejobs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1971)
=> Bug 1315375 - Allow selecting jobs by pressing enter on keyboard

ui/css/treeherder-job-buttons.css
Just a simple z-index fix. I'm not a frontend person so if this is wrong somehow, please feel free to reject!
=> Bug 1317515 - Fix rendering order of job buttons

docs/rest_api.rst
Just a quick fix!
@edmorley it seems like you own that file in case you're interested.
=> Bug 1318794 - Fix docs User-Agent example

tests/autoclassify/test_classify_failures.py, tests/autoclassify/utils.py, tests/conftest.py, tests/e2e/test_client_job_ingestion.py, tests/log_parser/test_crossreference_error_lines.py, tests/webapp/api/test_failureline.py, tests/webapp/api/test_jobs_api.py, treeherder/autoclassify/autoclassify.py, treeherder/autoclassify/detect_intermittents.py, treeherder/log_parser/crossreference.py, treeherder/model/fields.py, treeherder/model/migrations/0041_duplicate_failure_classifications.py, treeherder/model/models.py, treeherder/webapp/api/serializers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1950)
=> Bug 1312575 - Duplicate autoclassification information across TextLogError and FailureLine

ui/plugins/pluginpanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1935)
=> Bug 1311130 - Don't link to buildbot machine health if this is a taskcluster job

ui/plugins/pluginpanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1934)
=> Bug 1158283 - Don't show links to build directories for taskcluster jobs

.travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2012)
=> Work around travis issue with java

treeherder/auth/backends.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2014)
=> Bug 1318691 - Replace backends.py hard-coded resource path with reverse

treeherder/model/migrations/0044_increase_symbol_lengths.py, treeherder/model/models.py
See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1320926#c3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2017)
=> Bug 1320926 - Increase Job{Type,Group} symbol length to match production

tests/webapp/api/test_jobs_api.py, tests/webapp/api/test_note_api.py, treeherder/model/derived/jobs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2021)
=> Bug 1322067 - Update `last_modified` when job is starred or cancelled

ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2024)
=> Add nice labels for the QR builds on the graphics branch.

ui/js/models/resultsets_store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2022)
=> Bug 1322411 - Use requestIdleCallback to get jobs data updates.

requirements/common.txt, tests/test_setup.py, treeherder/config/settings.py, treeherder/embed/views.py, treeherder/webapp/api/auth.py
Release notes:
https://docs.djangoproject.com/en/stable/releases/1.9/
Seems to work fine locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2025)
=> Bug 1266065 - Update to Django 1.9

ui/js/values.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2028)
=> Bug 1322840 - Mark Linux QR build as x64

tests/conftest.py, tests/etl/test_perf_data_adapters.py, tests/perfalert/test_alert_modification.py, tests/perfalert/test_create_alerts.py, tests/webapp/api/test_performance_alerts_api.py, treeherder/perf/alerts.py, treeherder/perf/migrations/0026_drop_alertsummary_rsid.py, treeherder/perf/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2006)
=> Bug 1320936 - Drop result_set_id columns from alert summary table

ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2033)
=> Bug 1262202 - Really fix automatically getting base revision in comparechooser

treeherder/model/migrations/0047_disallow_null_job_metadata.py, treeherder/model/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2034)
=> Bug 1318474 - Disallow null job metadata

ui/js/controllers/bugfiler.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/2035)
=> Bug 1324768 - Better notify if authentication fails when using the bug filer
