- treeherder/log_parser/parsers.pyx
For buildbot jobs there are headers/separators at the start and end of
each step within the job log, which contain various stats about the
step. Since buildbot buffers the output, it's able to add the result for
the current step to not just the end separator, but the start one too.
However, for non-buildbot submitters of results, they may not buffer the
output, and so cannot output the step result in the start line, only the
end one. As such, this commit switches the log parser to using the
latter instead of the former to determine the step result.
> Bug 1086896 - Use the log step finish line for determining result

- deployment/update/update.py
Without this fetch, you can only deploy to branches that existed when the LAST deploy was done.  By doing ``git fetch`` you get any new branches that were created since the last deploy.  This allows the ``git checkout`` to succeed on line 32.
> Bug 1113160 - add git fetch to get new branches for deploying

- tests/etl/test_tbpl.py
- treeherder/etl/tbpl.py
- treeherder/settings/base.py
> Bug 1118266 - Remove '/ui' from logviewer URLs in TBPLbot comments

- tests/etl/test_tbpl.py
- treeherder/etl/tbpl.py
Previously classifying failures with a bug number would add a comment to
the bug that listed the datetime of classification. However this is
redundant, since it's virtually the same as the datetime of the bug
comment itself. Instead, it's more useful to list the job start time.
Only classifications for completed jobs are submitted to Bugzilla, so we
do not need to add handling for pending jobs, that do not have a start
time.
> Bug 1085100 - Use start_time instead of classification time in bug comments

- tests/sample_data/logs/mozilla-esr17_xp_test_pgo-mochitest-browser-chrome-bm74-tests1-windows-build12.jobartifact.json
- tests/sample_data/logs/ux_ubuntu32_vm_test-jetpack-bm67-tests1-linux-build16.jobartifact.json
- treeherder/log_parser/parsers.pyx
So that we don't miss "Built from revision X" TinderboxPrints.
> Bug 1086663 - Make the TinderboxPrint regex less strict about whitespace

- treeherder/model/management/commands/init_datasources.py
- treeherder/model/tasks.py
We should only include active repositories when performing
init_datasources or calculating job etas.
> Bug 1067409 - Filter on repository active_status in more cases

- tests/log_parser/test_step_parser.py
- treeherder/log_parser/parsers.pyx
sometimes the dates in the buildbot steps are not quite the format we
expect.  Massage them to match so we don’t fail log parsing.
> Bug 1124270 - fix parsing step dates without decimal

- treeherder/etl/buildbot.py
- treeherder/log_parser/parsers.pyx
- treeherder/log_parser/utils.py
- treeherder/webapp/api/resultset.py
Since it avoids backslash expressions from being mis-interpreted if they
happen to match an escape sequence (eg '\b', '\n', ...).
> Bug 1063688 - Use raw string literals for regexes

- treeherder/etl/pushlog.py
We only use the latest 20 revisions.  And fetching 21 will tell us there is "more" and that we should link to the repo change log.
> Bug 1119028 - Only ingest last 21 revisions per resultset

- tests/log_parser/test_utils.py
- treeherder/log_parser/utils.py
Since we were missing leak failure messages that were prefixed with the process name, eg:
"... | leakcheck | tab process: 42114 bytes leaked (...)"
Using .search() is quicker than using .match() with '.*' prefixed to the regex - see https://bugzilla.mozilla.org/show_bug.cgi?id=1076770#c1
> Bug 1121670 - Use search() instead of match() for search term leak regex

- treeherder/etl/tasks/tbpl_tasks.py
- treeherder/log_parser/tasks.py
With this change, the first retry is now after 1 minute, then the time for each subsequent
retry lengthens by a further minute each time.
> Bug 1124269 - Add smarter celery retry times

- tests/etl/test_tbpl.py
- treeherder/__init__.py
- treeherder/etl/daemon.py
- treeherder/model/derived/jobs.py
- treeherder/workers/models.py
This fixes:
tests/etl/test_tbpl.py:5:1: F401 'datetime' imported but unused
treeherder/__init__.py:4:1: F401 'celery_app' imported but unused
treeherder/etl/daemon.py:71:19: F841 local variable 'e' is assigned to but never used
treeherder/model/derived/jobs.py:893:9: F841 local variable 'where_in_clause' is assigned to but never used
treeherder/model/derived/jobs.py:2177:13: F841 local variable 'job_id' is assigned to but never used
treeherder/workers/models.py:5:1: F401 'models' imported but unused
However I'm dubious about the unused 'where_in_clause' in jobs.py - it looks perhaps that it was intended to have been passed to jobs_execute()'s 'replace', here:
https://github.com/mozilla/treeherder-service/blob/c99cc67a70ed94f6694b9bed968373edb89e4fd2/treeherder/model/derived/jobs.py#L899
> Bug 1059811 - Fix remaining pyflakes warnings

- treeherder/etl/management/commands/ingest_push.py
- treeherder/etl/pushlog.py
The most recent push from a repository is given the tag 'tip' in Mercurial. To save having to look up a specific revision to ingest when testing, 'tip' can now be passed to ingest_push, and the revision that 'tip' currently maps to, will be used during push and jobs ingestion. Previously, jobs ingestion would have used the non-existent SHA of 'tip' when trying to associate jobs with pushes, resulting in no jobs being imported from builds-{pending,running,4hr}.
> Bug 1126356 - Add support for |manage.py ingest_push <project> tip|

- treeherder/etl/tbpl.py
Previously we only get the HTTPError code in the exception, without the server response that gives more context. The latter would help explain the 400s in bug 1114785.
Example output with this change:
HTTPError 401 submitting to https://bugzilla.mozilla.org/rest/bug/1078237/comment: {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":410,"message":"You must log in before using this part of Bugzilla."}
Traceback (most recent call last):
File "C:/Users/Ed/Desktop/requests-foo.py", line 5, in <module>
r.raise_for_status()
File "C:\Python27\lib\site-packages\requests\models.py", line 831, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required
> Bug 1124842 - Log the server response for Bugzilla/ES submission errors

- treeherder/model/derived/refdata.py
- treeherder/model/models.py
Uses the new datasource option added by bug 1125585, to enforce that a
host_type is always specified, and thus avoid silently falling back to
the master_host when the read_host might have been more suitable.
> Bug 1125586 - Enable the 'require_host_type' datasource option

- tests/etl/test_tbpl.py
- tests/model/derived/test_jobs_model.py
- treeherder/etl/tasks/tbpl_tasks.py
- treeherder/etl/tbpl.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
We did not previously pass the username of the person who made a failure classification to BugzillaBugRequest. As a result, BugzillaBugRequest has to fetch the bug mapping again to find it out. After the fix for our master-read DB setup, this fetch of the bug mapping was being performed against the read host, which occasionally did not yet have the requested mapping (due to replication delay) causing an ObjectNotFoundException.
The 'get_bug_job_map_detail' query could have been switched to use the master host to avoid the race, however the more efficient fix is just to pass the username to BugzillaBugRequest directly, like we already do for OrangeFactorBugRequest, avoiding the query entirely.
As a result, get_bug_job_map_detail() is then unused, so can be removed.
> Bug 1127940 - Simplify BugzillaBugRequest username handling to avoid host DB race

- tests/webapp/api/test_jobs_api.py
- treeherder/model/sql/jobs.json
This field is required to filter in the ui by buildername.
> Bug 1097090 - Re-add ref_data_name to jobs endpoints

- treeherder/etl/buildapi.py
Ed and I went through and tested several jobs with multiple request ids.  It was always the last in the list that had the correct revision.  So this small change will correct which request id is used for the retrigger.
Also fixed:
Bug 1097328 - fixed coalesced job_guid for running/complete jobs
This second bug was heavily related to the main bug.
> Bug 1093743 - use correct request id when multiple exist

- treeherder/etl/buildapi.py
- treeherder/etl/management/commands/export_project_credentials.py
- treeherder/etl/management/commands/import_project_credentials.py
- treeherder/etl/oauth_utils.py
- treeherder/etl/perf_data_adapters.py
- treeherder/etl/pulse.py
- treeherder/etl/tbpl.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/populate_performance_series.py
- treeherder/model/utils.py
- treeherder/webapp/api/objectstore.py
- treeherder/webapp/api/projects.py
For a large set of series, we can wind up processing a fair bit of json.
Each time isn't huge (0.07s on my laptop for the biggest series over 90 days),
but in aggregate (e.g. 51 series in tp5 * 5 time series) that could add up.
simplejson is nearly 10 times (0.009s for the same series) and we already have
it installed, so let's just use it. ujson is slightly faster still (0.006s)
but it's not installed.
>  Use simplejson instead of json in production code

- treeherder/model/fixtures/repository.json
In the near future, we want to switch off of Travis CI and use the new TaskCluster system for performing CI testing for upstream Bugzilla and also BMO (bugzilla.mozilla.org). To see the test results from the TaskCluster jobs, we would like to be able to feed the results into TreeHerder. Please advise if more than what is here is needed to make this a possibility.
Thanks
dkl@mozilla.com
> Add support for the Bugzilla and BMO projects

- treeherder/model/sql/jobs.json
This is a quick&dirty solution to circumvent the problem of the duplicate signatures.
The buildername is selected randomly by the group by, but that's more or
less what we have done until now so we can probably keep living with that.
> Bug 1131133 - group jobs by id

- tests/etl/test_tbpl.py
- treeherder/etl/tbpl.py
- treeherder/settings/base.py
Bugzilla comments can be no more than 65535 characters in length. To
both avoid hitting this limit (and the comment being rejected) and to
reduce the spam left on bugs, truncate the comment body at 40000
characters.
> Bug 1114785 - Limit the total length of comments submitted to Bugzilla

- setup.cfg
* Add ```__pycache__``` to ```exclude```. It's in the default exclude list for pep8, and we clobber this by setting our own.
* Ignore error types that pep8 does by default. Defining ```ignore``` ourselves overwrites the default ignore list. This adds in the current pep8 ignore list, to ensure we don't re-enable noisy error types inadvertently.
* Add explanation for the duplicated config.
> Bug 1133362 - Update flake8/pep8 config

- treeherder/etl/buildapi.py
Unfortunately whilst the changes in bug 1093743 were slightly more correct than the previous approach, due to inconsistencies in builds-4hr, we're seeing some issues with running jobs being orphaned/duplicated. 
For now, I think it's best to revert PR #359 (and its followup PR #381) so we can deploy the other changes in the meantime.
For more info, see https://bugzilla.mozilla.org/show_bug.cgi?id=1133455#c8 onwards.
> Revert bug 1093743 due to builds-4hr inconsistencies causing orphaned running jobs

- requirements/pure.txt
To pick up the version number bump. This doesn't change the contents of vendor/datasource/ so in theory shouldn't be necessary. However prod pip installs the requirements in pure.txt when it shouldn't, and the vendor directory is later in python.path than site-packages, so we end up using the version installed globally. Unfortunately some of the nodes have an older version of datasource installed, but without the version bump it's hard to tell which.
https://github.com/jeads/datasource/compare/fab643e0d5...2f09c9cc87
> Bug 1125585 - Update datasource to 2f09c9cc87

- treeherder/webapp/api/logslice.py
This PR fixes:
* [Bug 1133910](https://bugzilla.mozilla.org/show_bug.cgi?id=1133910) - Fix logslice by using pickle-able BytesIO in cache
* [Bug 1133870](https://bugzilla.mozilla.org/show_bug.cgi?id=1133870) - Raise real exception and let it bubble up so real error is not hidden
* [Bug 1133875](https://bugzilla.mozilla.org/show_bug.cgi?id=1133875) - Better messages for missing params
Fixes the error where you can't view log lines in the logviewer with the Django 1.7 upgrade.
> Bug 1133910 logviewer lines

- treeherder/settings/base.py
There is currently duplication between the packages in vendor/ and those
globally installed on stage/production. This change ensures we use those
in vendor/ in preference to those in site-packages & so are using the
version we expected.
> Bug 1134740 - Use vendor packages in preference to globally installed

- docs/installation.rst
- docs/ui_integration.rst
This tweak addresses bug [1135117](https://bugzilla.mozilla.org/show_bug.cgi?id=1135117).
Nothing major, it just hopefully explains what each of the two configurations mean, why they would choose to do either of them, and hinting at the one which is most common.
As a newbie I found that phrase 'in' in the integrating the ui doc confusing, but maybe it's just me. :) To me it sort of implied I'd be running the browser directly within a VM.
> Bug 1135117 - Minor tweaks to readthedocs vagrant setup for clarity

- tests/etl/test_tbpl.py
- tests/webapp/api/test_bug_job_map_api.py
- tests/webapp/api/test_jobs_api.py
- tests/webapp/api/test_note_api.py
- treeherder/model/sql/jobs.json
Bug 1097090 combined get_job_list and get_job_list_full, but the two queries were actually subtly different. The former had an ORDER BY push_timestamp, which was lost when they were combined. This means jobs displayed in the similar jobs panel are from the past, and not the most recent jobs of the same type.
The get_job_list query also sorted on platform, however I don't believe this is necessary, so I've not added it back in here. Please do double check though! :-)
Unfortunately we also had tests that were not aimed at the jobs API that were dependant on the
order of jobs returned by get_job_list(). The second commit fixes these:
* test_tbpl.py does not even need to use get_job_list() since the only accessed property is the job_id, which we are better off hard-coding.
* test_note_apy.py …
> Bug 1134916 - Make jobs API return jobs sorted by push_timestamp again

- docker/gunicorn.sh
This ensures operations like |docker restart| send signials to gunicorn which
will handle them correctly (where as previously bash would just ignore them)
> Ensure gunicon is pid 1 in docker scripts

- docker/generate_test_credentials.py
Add retries to the generate credentials helper so we can handle cases where
mysql database has not yet been bootstrapped or when the fixtures have not yet
been loaded.
> Fix some race conditions in docker gunicon startup (docker only)

- treeherder/settings/base.py
There's a bug with gevent and Python 2.7.9 which the pulse publisher hits.
Disable it until a workaround is found.
> Bug 1138400 - Disable pulse publishing due to Python 2.7.9 incompatibility

- deployment/update/update.py
This includes fixes for bug 1059814, bug 1135798, bug 1088705 & bug 1138392.
Please see the individual commit diffs and multi-line commit messages for easier review :-)
> Deploy script fixes & cleanup

- tests/log_parser/test_tinderbox_print_parser.py
- treeherder/log_parser/parsers.pyx
Currently if a TinderboxPrint line contains a space in the link title,
eg in 'hazard results' here:
TinderboxPrint: hazard results: https://ftp-ssl.mozilla.org/...
...then we ingest it as content_type 'raw_html' rather than 'link'.
> Bug 1137162 - Allow spaces in TinderboxPrint link titles

- treeherder/model/management/commands/cycle_data.py
The current chunk size of 100 translates to 100 pushes, which can be as many as 40,000 jobs, which can result in deletes of 100,000+ rows at a time from the artifact tables. This blocks other DB activity & also means the cycle-data task sometimes hits:
OperationalError: (2006, 'MySQL server has gone away')
> Bug 1130355 - Data cycling: Reduce chunk size to avoid timeouts/alerts

- .travis.yml
- requirements/dev.txt
In a later PR I'll add docs for setting up locally & also how to set up as a git commit hook locally to avoid frustration by people forgetting to run flake8 before pushing to a PR branch. However for now I'm just keen to get this running so we don't regress things, now that I have all errors/warnings fixed.
Few notes:
* flake8 is pyflakes+pep8.
* Errors will cause the entire job to report as a failure, however the whole job will still run (including our existing tests).
* flake8 will use setup.cfg that I've already set up - happy to add/tweak which warnings it ignores if we find some to be too noisy in the future.
> Bug 1107523 - Run flake8 as part of the Travis build

- deployment/update/update.py
The restart-jobs script now also gracefuls apache (after draining the nodes to avoid errors), so we don't want to do so in update.py any more.
> Bug 1139917 - Deploy script: Don't restart apache in rsync_code()

- .landscape.yaml
- setup.cfg
* Turn on warnings in test code.
* Set strictness explicitly to medium, since it's currently at 'None'.
* Explicitly set the list of requirements files, since otherwise unnecessary packages will be installed, slowing down the landscape.io run.
* Disable pep8/pyflakes, since they are already run as part of the Travis job.
> Bug 1138902 - Adjust linter configs

- .travis.yml
Travis |cache: pip| should do this for us, except it only works if we don't set our own install step, due to:
https://github.com/travis-ci/travis-ci/issues/3239
Instead, let's manually specify the directory to cache.
> Bug 1137278 - Travis: Cache the .cache/pip/ directory explicitly

- .travis.yml
Whilst making Travis store the pip cache saves us from having to download the packages from PyPI each time, the vast majority of time spent during Travis run setup is compiling the packages that contain binary components. As such, let's try caching the virtualenv itself so we don't have to repeat this each time. We no longer get Travis to store the pip cache since it will only be used when the virtualenv is first created & will bloat the Travis cache archive that has to be downloaded from AWS at the start of each run.
> Bug 1137278 - Travis: Re-use the virtualenv rather than the pip cache

- requirements/dev.txt
This has passed Travis & running tests (with code coverage enabled) locally.
I think it's going to be quicker in the long run to just land this and revert bits if we hit any problems later, rather than reading through every change in the release notes for everything that's been updated.
> Bug 1143033 - Update packages in dev.txt

- .travis.yml
- docs/common_tasks.rst
- docs/installation.rst
- runtests.sh
* Bug 1143086 - Travis: Run flake8 first & end the job early if it fails. Steps in before_script (and any other part of the build lifecycle apart from 'script') terminate the run immediately on failure. This means in the case of flake8 failures, the job changes from "in progress" to "errored" virtually immediately (with the virtualenv caching changes) so the user can see the problem and re-push straight away. See: http://docs.travis-ci.com/user/build-lifecycle/
* Bug 1139894 - Add flake8 to runtests.sh. flake8 is run on Travis, so let's make it harder to forget to run locally for people who use runtests.sh. Eventually we should move all of this to setup.py.
* Bug 1139894 - Docs: Move the "Running the tests" section to common tasks. At some point in the future, we may break the "Running …
> Flake8 improvements

- puppet/manifests/classes/dev.pp
- puppet/manifests/classes/python.pp
* Don't use out of date pip/virtualenv packages …
We use an Ubuntu Precise image for the Vagrant project, whose package repository contains extremely out of date versions of setuptools, pip and virtualenv. So we stop using the package repository, and instead use the official PyPA bootstrap script, which installs the latest versions of setuptools and pip, and then we follow that with a pip install of the latest virtualenv. We need curl to fetch the pip bootstrap script, but it's handy for development anyway.
References to distribute are removed, since it's an older fork of setuptools and long since deprecated.
* Remove deprecated --download-cache pip option …
pip v6+ has an on by default cache, that it manages itself, so the --download-cache option is deprecated: …
> Bug 1144916 - Vagrant: Use latest pip/setuptools/virtualenv

- .travis.yml
- Dockerfile
- bin/generate-vendor-lib.py
- bin/peep.py
- puppet/manifests/classes/dev.pp
- puppet/manifests/classes/python.pp
- requirements/checked-in.txt
- requirements/common.txt
- requirements/dev.txt
- requirements/prod.txt
- setup.cfg
* Check in peep v2.2. We're checking this in so we have a known good starting point in the
chain of trust. It also simplifies our deployment requirements. peep.py was taken from:
https://github.com/erikrose/peep/archive/2.2.tar.gz . The only alteration made was the addition of the licence block at the top of the file, taken from LICENCE in the peep repo.
* Add peep hashes to the requirements files. The whole point of peep is that it errors out if (a) hashes aren't specified for a package, or (b) the provided hash is incorrect. As such before we can start using peep, we must add the hashes. The requirements files are still compatible with pip, since it just treats them like any other comment.
* Use peep instead of pip locally, on Travis & in Docker. We want to start using peep in …
> Bug 1143350 - Switch to using peep instead of pip locally and on Travis

- puppet/manifests/vagrant.pp
We need to force output on_failure, since we're using Puppet 2.x which does not have the fix for https://projects.puppetlabs.com/issues/10907
> Bug 1144805 - Vagrant: Show command output for errors during provision

- Dockerfile
The current directory isn't on the PATH, so the docker build was failing with:
/bin/sh: 1: setup.py: not found
The bin/peep.py call was fine, but I've changed it for consistency.
> Bug 1137164 - Docker: Use ./setup.py since current directory not on path

- tests/webapp/api/test_jobs_api.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
- treeherder/model/sql/template_schema/project_jobs_1.sql.tmpl
Add support for Tier 2 jobs
Fixes [bug 1113322](https://bugzilla.mozilla.org/show_bug.cgi?id=1113322)
* Add a ``tier`` field to the job table to establish whether a job is tier 1 or 2.  Default to 1
* Check for existence of a ``Tier-2`` exclusion profile.  Any job matching a signature in this profile will get its ``tier`` field set to 2.
Before merging this, must get a DBA to add the ``tier`` field to all the ``job`` tables.
> Bug 1113322 - Tier n jobs

- puppet/manifests/classes/python.pp
Since higher versions include pip 6.1.1, which is currently incompatible with peep.
Virtualenv v12.0.7 ships with pip 6.0.8.
> Bug 1151868 - Vagrant: Pin virtualenv to v12.0.7

- Vagrantfile
This fixes Bugzilla bug [1089639](https://bugzilla.mozilla.org/show_bug.cgi?id=1089639).
This eliminates the warning:
`warning: Could not retrieve fact fqdn`
during a `vagrant up`, when creating a local treeherder instance.
I only did one destroy and up, but it seems to be fine and behaving as expected. I am assuming we use the same hostname we specify in [RTD](https://treeherder-service.readthedocs.org/en/latest/installation.html#setting-up-a-local-treeherder-instance), rather than vagrant.example.com
I've confirmed the error goes away during an up, and the server seems fine and ingesting jobs with a local service.
Tested on OSX 10.9.5:
FF Release **36.0.4**
Chrome Latest Release **41.0.2272.104** (64-bit)
> Bug 1089639 - Add treeherder hostname to Vagrantfile for a clean up

- treeherder/etl/bugzilla.py
Previously we limited the number of pages to 30, which with a page size of 500, meant a max of 15,000 intermittent-failure bugs retrieved from Bugzilla, with no exceptions or log output to indicate this had occurred.
We now have more than 15,000 intermittent failure bugs, so the limit is being removed, since we're both confident that the search terms are correct, and any other infinite loop would be caught by the existing 600s timeout.
The task currently takes ~300s to run, so there is still plenty of headroom. Plus a timeout exception would be immediately visible in New Relic and so much less of a pain to debug.
> Bug 1151629 - Don't limit the number of bugs retrieved by fetch_bugs

- treeherder/log_parser/tasks.py
Since it is taking 80x longer than it did previously and is causing backlogs in the standard log parsing tasks too.
> Bug 1152681 - Temporarily disable the parse-json-log task

- tests/log_parser/test_tasks.py
We've disabled json log parsing, so we need to temporarily mark the corresponding test as expected fail.
> Bug 1152681 - Mark test_parse_mozlog_log as xfail to make Travis green

- tests/webapp/api/test_jobs_api.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
This allows for more precise filtering with the ``job`` (buildername)
link in the detail panel.
> Bug 1150734 - add signature field to jobs in job list

- treeherder/log_parser/utils.py
In order to find the job in question, the project name is required in addition to the job guid. We also now specify the URL for errors, to save having to look up the job at all in many cases.
I also made the strings more terse to reduce wrapping, save log usage (eg when we're paying for it on Papertrail) and since I'm a pedant and "download and/or parse" isn't possible, since "and" is never an option.
> Bug 1152769 - Log parser: Make error & debug output strings more useful

- treeherder/etl/bugzilla.py
The API query will now be of form:
bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status&keywords=intermittent-failure&chfieldfrom=-1y
To test, try using shorter values, eg:
https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status&keywords=intermittent-failure&chfieldfrom=-6h
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-service/460)
> Bug 1152426 - Only add bugs modified in the last year to the bugscache

- requirements/prod.txt
Since it has to be installed globally & run as a daemon, and so we have no use for it in the virtualenv.
Reverts 37ae564296882745eed95625716c298b6a9e4711 from bug 1070470.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-service/463)
> Bug 1154471 - Remove newrelic-plugin-agent from requirements/prod.txt

- bin/peep.py
Copied verbatim from:
https://github.com/erikrose/peep/archive/2.3.zip
Changes:
https://github.com/erikrose/peep/compare/2.2...2.3
Peep now passes pep8/flake8, so can be removed from the exclude list.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-service/467)
> Bug 1155293 - Update to peep v2.3

- treeherder/settings/base.py
OrangeFactor is moving to a new ES cluster, so we need to submit the intermittent bug associations to the new endpoint instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/473)
> Bug 1156448 - Switch to the new OrangeFactor-only ES cluster

- deployment/update/update.py
So we don't use the default.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/474)
> Bug 1156457 - Set the New Relic deploy user to "Chief"

- tests/conftest.py
- tests/etl/test_classification_mirroring.py
- tests/log_parser/test_tasks.py
- tests/model/derived/test_jobs_model.py
- tests/webapp/api/test_artifact_api.py
- tests/webapp/conftest.py
- treeherder/etl/classification_mirroring.py
- treeherder/model/derived/artifacts.py
- treeherder/model/derived/base.py
- treeherder/model/derived/jobs.py
- treeherder/webapp/api/artifact.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/projects.py
There comes a time when a class should not grow any larger.  ``model/derived/jobs.py`` is nearing 3000 lines!  I can't, in good conscience, add MORE code that throws it over that size.  While working on auto-generation of ``bug_suggestions`` for non-buildbot submissions for artifacts, I hit on this.
This PR creates a new ``ArtifactsModel`` which refactors ``artifact`` handling out of ``JobsModel``.  The ``JobsModel`` still calls ``ArtifactsModel`` during job ingestion.
Let's discuss this proposal and see if it makes sense to all of us.  Thanks!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder-service/462)
> Bug 1154470 - refactor artifact handling into its own model

- bin/run_celery_worker
- bin/run_celery_worker_buildapi
- bin/run_celery_worker_hp
- bin/run_celery_worker_log_parser
- bin/run_celery_worker_pushlog
- bin/run_celerybeat
- bin/run_gunicorn
- deployment/update/update.py
I've tested this on stage and it appear to work well. eg:
First deploy:
http://treeherderadm.private.scl3.mozilla.com/chief/treeherder.stage/logs/virtualenv-deploy.1429119652
Later deploy (with no-op package install step, since the venv is already populated):
http://treeherderadm.private.scl3.mozilla.com/chief/treeherder.stage/logs/virtualenv-deploy.1429123134
I've also verified that we're using the binaries from the virtualenv bin:
```bash
[root@treeherder1.stage.webapp.scl3 ~]# ps aux | grep [g]unicorn
<snip>
495      20228  5.6  1.1 551368 71500 ?        Sl   18:01   0:04 python2.7 /data/www/treeherder.allizom.org/venv/bin/gunicorn <snip>
[root@treeherder1.stage.webapp.scl3 ~]# ls -l /proc/20228/exe
lrwxrwxrwx 1 treeherder treeherder 0 Apr 15 18:02 /proc/20228/exe -> …
```
> Bug 1146184 - Deploying should peep install into a virtualenv and rsync to all nodes

- docs/installation.rst
This tweak fixes Bugzilla bug [1156420](https://bugzilla.mozilla.org/show_bug.cgi?id=1156420).
This adds additional troubleshooting information for RTD, specifically for users who don't have Virtualization Technology (vt-x) enabled on various systems.
I defer to @wlach and the exact sequence of vagrant `destroy`, `up`'s for both failure conditions (if required?) when the user encounters the nfs-error in question. I think they may need to do a destroy but let me know and I will tweak as needed.
I have only checked the .rst file on Github, I haven't built the docs locally. But formatting seems fine. I changed the "Note" to **Troubleshooting** for prominence. It seems to get lost or look like a regular part of the setup otherwise.
[<img …
> Bug 1156420 - Update vagrant troubleshooting during installation

- docs/installation.rst
This fixes Bugzilla bug [1155868](https://bugzilla.mozilla.org/show_bug.cgi?id=1155868).
I ran this change through http://rst.ninjs.org/ and it appears to be fine. I thought it might be reasonable to provide a little extra context on what builds-4hr is, by linking to the build dir so people can see it. I was unable to find other MDN / RelEng docs which describe builds-4hr in any great detail.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/478)
> Bug 1155868 - Update RTD that single ingestion is limited to builds4hr

- deployment/update/update.py
We're passing settings.UPDATE_REF, which is the default ref value, not the actual value that was passed via the Chief web UI. As such, New Relic was always displaying the revision deployed as "master", even if it was a non-master branch deploy. Ideally we'd use the value of 'ref' from pre_update(), but that's not available during the deploy() task (the script is run in three independent stages & Chief unhelpfully only passes 'ref' to the first stage), so we'll have to read it back from the media/revision file - which will require more mangling in bug 1076886.
For now, seeing as the 'revision' property is optional, lets just omit it, rather than setting it to a sometimes-wrong value. …
> Bug 1076886 - Deploy: Don't specify the wrong revision to New Relic

- treeherder/model/models.py
- treeherder/webapp/api/refdata.py
Simple fix to update the ``flat_exclusions`` on save of a ``job_exclusion``.  In fact, the save of the ``job_exclusion`` was already re-saving the ``exclusion profile``, but that save wasn't explicitly updating its ``flat_exclusions``.  The ``flat_exclusions`` are the important part of which jobs to exclude for a profile.  Now any save on the exclusion profile updates its ``flat_exclusion``.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/479)
> Bug 1066727 - update exclusion profile on save

- requirements/common.txt
Changes:
https://github.com/mozilla/treeherder-client/compare/f236a3487eb042638836d4d9c9f79d51cab2a362...1.1
Using a specific version release of treeherder-client (vs the Git zip archive for a specific revision) also means peep doesn't have to re-download the package each time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/484)
> Bug 1158202 - Update to treeherder-client v1.1

- requirements/common.txt
This is a no-op, the v0.6 release tag corresponds to the same revision, it just avoids peeps SHA special-casing which causes continual re-installation of the package & subsequent Travis cache invalidation.
https://github.com/jeads/datasource/releases/tag/v0.6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/489)
> Bug 1158766 - Pin datasource dependency using a tagged version not SHA

- puppet/manifests/classes/init.pp
- puppet/manifests/classes/python.pp
Now we're using an Ubuntu 12.04 image for Vagrant, and the latest Python available officially is 2.7.3, so we have to use a third party PPA:
https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7
https://launchpad.net/+help-soyuz/ppa-sources-list.html
The easiest way to add this PPA is using |add-apt-repository|, but Ubuntu 12.04 doesn't ship with it by default, so we also have to install the python-software-properties package, sigh:
http://ubuntuforums.org/showthread.php?t=1320536
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/482)
> Bug 1158177 - Vagrant: Update from Python 2.7.3 to 2.7.9

- requirements/common.txt
Changes:
https://github.com/mozilla/django-browserid/compare/e8d1d57145401cf3f42993fe84edc32e29e5903f...v0.11.1
This will fix the spurious "Setting BROWSERID_VERIFY_CLASS not found" errors in logs, as well as possibly help with people getting logged out intermittently. It also brings us up to the latest django-browserid release, which means updating later to a (yet to be released) Django 1.8 compatible version of django-browserid should be much easier.
Using a specific version release of django-browserid (vs the Git zip archive for a specific revision) also means peep doesn't have to re-download the package each time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/483)
> Bug 1118023 - Update to django-browserid v0.11.1

- deployment/update/update.py
The Cython build process creates .c and .so files in the log_parser directory, which only get re-created if the original source changes. We recently updated the version of Cython, however this doesn't trigger
re-building them. To avoid surprises, we should purge them like we do for the .pyc files.
In addition, there is no need to delete .pyc files from the UI source directory, since that does not contain any Python files.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/490)
> Bug 1158893 - Delete any existing Cython build output as part of deploy

- requirements/common.txt
Fixes security bugs, includes perf improvements & also means we can use the 'json' param for uploads instead of having to json.dumps() them.
https://github.com/kennethreitz/requests/blob/master/HISTORY.rst
https://github.com/kennethreitz/requests/compare/v2.4.1...v2.6.2
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/487)
> Bug 1158380 - Update requests to v2.6.2

- tests/e2e/test_client_job_ingestion.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
This supports ingesting job ``log_references`` that have a
``parse_status`` value.  This is so that external tools can submit jobs
that don’t require our internal log parsing.  They will then submit
their own log summary artifact.
I will add a ``parse_status`` field to the ``add_log_references()`` function in ``treeherder-client`` as well.  But they user can still submit like this if they create the job object with a dict, like the test does here.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/491)
> Bug 1158878 - support job submission with pre-parsed logs

- requirements/common.txt
- treeherder/settings/base.py
Changes:
https://github.com/mozilla/django-browserid/compare/e8d1d57145401cf3f42993fe84edc32e29e5903f...v0.10
Using a specific version release of django-browserid (vs the Git zip archive for a specific revision) means peep doesn't have to re-download the package each time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/492)
> Bug 1118023 - Update to django-browserid v0.10

- docs/installation.rst
This tweak hopefully fixes Bugzilla bug [1159288](https://bugzilla.mozilla.org/show_bug.cgi?id=1159288) and the contributor problem encountered in this [bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1144417#c18).
From what I can tell from the bug thread, he was later successful and perhaps hadn't been in his `/treeherder` directory when issuing a vagrant command.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/493)
> Bug 1159288 - Add clarity to RTD for vagrant ssh access

- docs/installation.rst
This change fixes Bugzilla bug [1159236](https://bugzilla.mozilla.org/show_bug.cgi?id=1159236).
This guides the user to use `vagrant provision` in the event of a network interruption during their vagrant creation.
I also included a reference to the Vagrant CLI while I was there in an appropriate spot, and removed the *"Once to this point in installation.."* clause, since installation may have already completed.
I tested the markdown with http://rst.ninjs.org, it seems to look as I intend/expect.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/496)
> Bug 1159236 - Add a timeout troubleshooting section to RTD

- tests/log_parser/test_utils.py
- tests/sample_data/artifacts/text_log_summary.json
- tests/sampledata.py
- tests/webapp/api/test_artifact_api.py
- treeherder/etl/mixins.py
- treeherder/etl/th_publisher.py
- treeherder/log_parser/utils.py
- treeherder/model/bug_suggestions.py
- treeherder/webapp/api/artifact.py
This PR addresses [Bug 1080760](https://bugzilla.mozilla.org/show_bug.cgi?id=1080760)
The big change is that the ``artifacts`` creation endpoint now checks the incoming artifact.  If it is named "text_log_summary" and has a blob that contains ``error_lines``, then a ``Bug suggestions`` artifact is generated for it.
Also:
* extracts the generation of ``Bug suggestions`` artifacts from the ``log_parser`` into a ``model/bug_suggestions`` file.  
* added a test for this functionality.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/466)
> Bug 1080760 - Bug suggestions artifact auto generation

- tests/webapp/api/test_resultset_api.py
Since it was removed in bug 1097090.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/497)
> Bug 1139941 - Remove leftover references to with_jobs URL parameter

- treeherder/log_parser/utils.py
Similar to the 404 case, 403s are not something within our control, and are not unusual due to the current taskcluster implementation. As such, let's suppress these from New Relic (and retries) too.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/505)
> Bug 1159934 - Don't generate log parser exceptions if the log URL 403s

- treeherder/embed/templates/embed/resultset_status.html
The reload javascript block was neither in <head> nor <body>.
I've also moved the {% load staticfiles %} since it was adding a newline at start of file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/508)
> Bug 1161449 - Fix validation errors in /embed/resultset-status/ template

- treeherder/etl/pushlog.py
At some point as we move more things to using the requests library, we should probably add some wrappers around requests to common.py and use those instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/511)
> Bug 1127774 - Include the URL in the logs for pushlog HTTPErrors

- treeherder/etl/buildapi.py
* The warnings need to specify the buildername, otherwise it's impossible to track them down. 
* The fuzzer jobs' branch of 'idle' is expected to not be in our list of projects, so suppress warnings for them.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/510)
> Bug 1161520 - Improve log output for builds-4hr ingestion warnings

- treeherder/etl/buildapi.py
Some l10n jobs specify the l10n repo revision under 'revision', rather than the gecko revision. This results in fetch_missing_resultsets requests that are guaranteed to 404. As such, these should be skipped until this is fixed in builds-4hr by bug 1125433.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/509)
> Bug 1090289 - Skip jobs in builds-4hr that specify the wrong revision

- treeherder/etl/buildapi.py
Since we now use the buildername as part of the error messages, we get a KeyError if it's not present. We were already skipping over these jobs previously, since they are also missing the branch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/517)
> Bug 1161520 - Handle jobs that are missing the buildername

- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/cycle_data.py
- treeherder/model/sql/objectstore.json
Items in the objectstore are currently expired by finding the list of result sets matching the date range, then looking up the jobs for those result sets, and finally searching for matching job guids in the datastore table. This is not only bad for performance of objectstore deletes (since we end up with lists of thousands of guids), but also means we cannot set a different cycle interval for the objectstore.
The new approach is much simpler: we only query the objectstore, and use loaded_timestamp to determine which rows to cycle. The objectstore does not have any foreign keys, so this isn't a problem. The only constraint is that we must keep the complete jobs long enough for the job to stop appearing in builds-4hr, to prevent us from continually re-adding it to the objectstore. For now, …
> Bug 1126943 - Expire data from the objectstore independently of the others

- treeherder/etl/buildapi.py
- treeherder/model/derived/jobs.py
* builds-4hr ingestion: Only add mozlog_json URLs to log_references if not null.
The url for items in blobber_properties can sometimes be null, so skip adding a mozlog_json entry for them to log_references if so.
* Objectstore processing: Protect against null properties during ingestion.
Sometimes a property is present, but its value is null in the json_blob in the objectstore. We must set the default value in this case too, and not just when the property does not exist at all, to prevent exceptions when we later perform string operations on it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/521)
> Bug 1162526 - Protect against null properties during ingestion

- treeherder/etl/buildapi.py
- treeherder/etl/common.py
In order that Treeherder can track a buildbot ingested job as it moves from pending to running to completed, a unique job_guid must be generated, since buildbot doesn't directly give us one. To make things worse, each of the three data sources (builds-{pending,running,4hr}) make slightly different properties available to us, and the data in them is not always correct. Until now we've been calculating the guid in such a way that as some jobs (particularly those that are coalesced) change state, the guid generated changes, causing us to think it's a brand new job, thereby leaving behind an orphaned pending/running job.
The new method of generating a guid uses only the single request_id corresponding to the job that ran, rather than all of the request_ids. This is because when in the pending …
> Bug 1093743 - Attempt to generate job_guids more consistently

- treeherder/model/derived/jobs.py
Now if an exception occurs during _load_ref_and_job_data_structs(), we mark that job in the objectstore as errored and continue inserting the other jobs. Previously the exception would have meant all of the other jobs were not inserted, causing up to 100 rows in the objectstore to be stuck in the 'loading' processed_state indefinitely.
The exception string passed to mark_object_error() isn't ideal, but it's the same as the handling above, so will do for now until we remove the objectstore.
In addition, this change means that we lose visibility in New Relic for these exceptions - and someone has to manually check the objectstore for jobs with error = "Y". However short term this seems preferable to dropping 100 jobs every time we get an exception, particularly since this is already the …
> Bug 1162682 - Catch exceptions whilst processing objectstore jobs

- docs/common_tasks.rst
- treeherder/model/management/commands/run_sql.py
Previously the run_sql manage.py command only supported reading the SQL command from a specified file. It can now also be provided via the CLI.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/527)
> Bug 1163591 - run_sql: support specifying the SQL statement via the CLI

- treeherder/model/management/commands/run_sql.py
This gives output like:
```
(venv)vagrant@local:~/treeherder$ ./manage.py run_sql --data-type objectstore -s "OPTIMIZE TABLE objectstore"
SQL command: OPTIMIZE TABLE objectstore
46 datasource found
--------------------------
Sql code executed on mozilla-central - objectstore - 1:
('mozilla_central_objectstore_1.objectstore', 'optimize', 'note', 'Table does not support optimize, doing recreate + analyze instead')
('mozilla_central_objectstore_1.objectstore', 'optimize', 'status', 'OK')
--------------------------
Sql code executed on mozilla-inbound - objectstore - 1:
('mozilla_inbound_objectstore_1.objectstore', 'optimize', 'note', 'Table does not support optimize, doing recreate + analyze instead')
('mozilla_inbound_objectstore_1.objectstore', 'optimize', 'status', 'OK')
````
[<img …
> Bug 1163996 - run_sql: Print the query response to stdout

- tests/log_parser/test_utils.py
- treeherder/etl/mixins.py
- treeherder/etl/th_publisher.py
- treeherder/log_parser/utils.py
- treeherder/model/error_summary.py
Fixes [Bug 1163182](https://bugzilla.mozilla.org/show_bug.cgi?id=1163182)
Refactor the code for generating ``Bug suggestions`` artifacts into its own library.  Also extract out some code for posting ``TreeherderRequests`` into a ``th_publisher`` library.  This is preliminary work to the auto-generation of ``Bug suggestions`` artifacts on new ``text_log_summary`` artifacts from external sources.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/525)
> Bug 1163182 - refactor bug suggestions artifact generation

- docs/installation.rst
This change fixes Bugzilla bug [1056049](https://bugzilla.mozilla.org/show_bug.cgi?id=1164166).
This guides the user to restart `nfs-kernel-server.service` in the event of the specified vagrant up failure case. I tested the markdown with http://rst.ninjs.org, it seems to look as I intend/expect.
I didn't have a failure condition to locally test and confirm the fix/workaround.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/530)
> Bug 1056049 - Add NFS transport protocol troubleshooting to RTD

- README-UI.md
- README.md
- docs/common_tasks.rst
- docs/submitting_data.rst
- docs/ui/installation.rst
- treeherder/client/setup.py
The docs have been moved from treeherder-service.readthedocs.org to treeherder.readthedocs.org.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/546)
> Bug 1166426 - Update readthedocs links to point at the new RTD location

- tests/client/test_treeherder_client.py
- tests/conftest.py
- tests/etl/conftest.py
- treeherder/client/thclient/client.py
- treeherder/etl/buildapi.py
- treeherder/etl/mixins.py
- treeherder/etl/th_publisher.py
- treeherder/settings/base.py
This PR addresses [Bug 1151806](https://bugzilla.mozilla.org/show_bug.cgi?id=1151806)
This has been deployed to stage and heroku and seems to work well on both.  We may need to dial in the chunk size.  For now 50 seems to work ok.
On Heroku, so far, this has eliminated the timeouts due to job ingestion.  We still have a memory leak there, is unrelated to this PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/533)
> Bug 1151806 - Implement chunking for job ingestion

- bin/run_celery_worker_log_parser
- docs/submitting_data.rst
- tests/e2e/test_client_job_ingestion.py
- tests/model/derived/test_artifacts_model.py
- tests/sample_data/artifacts/text_log_summary.json
- tests/sampledata.py
- tests/webapp/api/test_artifact_api.py
- tests/webapp/api/test_note_api.py
- treeherder/model/derived/artifacts.py
- treeherder/model/derived/jobs.py
- treeherder/model/error_summary.py
- treeherder/model/tasks.py
- treeherder/settings/base.py
- treeherder/webapp/api/artifact.py
- ui/js/models/job_log_url.js
- ui/plugins/controller.js
- ui/plugins/failure_summary/controller.js
- ui/plugins/failure_summary/main.html
Fixes [Bug 1080760](https://bugzilla.mozilla.org/show_bug.cgi?id=1080760)
Follow-on to [PR 525](https://github.com/mozilla/treeherder/pull/525)
This generates bug suggestions for ``text_log_summary`` artifacts submitted to the ``artifact``  REST endpoint.  It schedules those asynchronously with ``celery``.
If a job is submitted to through the ``job`` REST endpoint and it contains a ``text_log_summary`` artifact with it, then the ``Bug suggestions`` artifact is created immediately (not asynchronously).  I created [Bug 1163253](https://bugzilla.mozilla.org/show_bug.cgi?id=1163253) to address possibly making that ``jobs`` endpoint asynchronous as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/5 …
> Bug suggestions take 3

- Procfile
- bin/run_celery_worker_buildapi
- treeherder/settings/base.py
Previously all three of the buildapi ETL ingestion tasks (pending, running, 4hr) were run under one queue. In order to be able to tell issues (such as backlogs or leaks) apart, these have now been split onto their own queues.
On Heroku, these queues now also have a dyno each - which should mean we can easily tell which is leaking and possibly also downgrade from the expensive performance dyno even before the leak is fixed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/548)
> Bug 1164868 - Split the buildapi tasks into {pending,running,4hr} queues

- ui/css/treeherder.css
- ui/plugins/annotations/main.html
The treeherder and treeherder-ui repos were unified today. This treeherder PR is a continuation of -ui PR https://github.com/mozilla/treeherder-ui/pull/528 from the now retired treeherder-ui repo.
This PR has already been r+'d by @wlach so we are ok to merge, which I will do shortly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/547)
> Bug 1165441 - Tidy up Annotations panel layout

- ui/css/treeherder.css
- ui/partials/main/thWatchedRepoNavPanel.html
The filter box is too small to see any filters of somewhat-significant length. This patch keeps it small most of the time, but grows to a larger size when it has focus and/or when there's something typed into the filter box.
It (ab)uses the 'required' property to make the :valid CSS selector work when the filter box has something typed in it, since apparently CSS has no selector for this use case.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/551)
> Make the filter textbox grow when focused or has content

- requirements/common.txt
See [Django rest framework](https://github.com/tomchristie/django-rest-framework/blob/version-2.4.x/docs/topics/release-notes.md#240) and [drf-extensions](http://chibisov.github.io/drf-extensions/docs/#0-2-7) relase notes
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/555)
> Bug 1167548 - update rest_framework to 2.4.5 and drf-extensions to 1.5.2

- requirements/docs.txt
Since otherwise we play tug of war with Read the Docs build process. Instead let's allow them to update us as they see fit, but at the same time retain a docs.txt that will work locally.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/556)
> Bug 1167560 - Don't pin the packages in doc.txt to specific versions

- ui/css/treeherder.css
- ui/index.html
- ui/js/directives/clonejobs.js
This fixes Bugzilla bug [1166474](https://bugzilla.mozilla.org/show_bug.cgi?id=1166474).
This adds our alternate job-row backgrounds, when the user invokes Hide revisions, and the job table is full page width. Prior to the fix, at full width the row coloring was missing.
Show/hide (revisions showing, unchanged):
Show/hide (revision hidden, the fix)
We basically hook the styling to `job-list` instead of the dynamic `job-list-pad-left`, which we change to be a generic `job-list-pad`. It now only ensures zero padding on the right hand side of the table when showing revisions.
Everything seems fine on both browsers.
FF Release **38.0.1**
FF Nightly **41.0a1**
Chrome Latest Release **42.0.2311.152** (64-bit)
[<img …
> Bug 1166474 - Add even/odd job-row backgrounds when revisions hidden

- docs/conf.py
- requirements/docs.txt
Using the instructions from:
https://docs.readthedocs.org/en/latest/theme.html#how-do-i-use-this-locally-and-on-read-the-docs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/564)
> Bug 1085579 - Docs: Use the Read the Docs theme for local builds too

- .travis.yml
- deployment/update/update.py
There's no need to make multiple calls to peep - we can just combine them into one. Not changing the puppet instances for Vagrant, since the calls are made in two separate puppet modules and so would require a bit of re-factoring, which is going to occur in bug 1074151 and friends.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/573)
> Bug 1169178 - Consolidate peep invocations

- docs/ui/installation.rst
- web-server.js
Instead of always displaying the directory file listing, if index.html is present we serve that instead. This not only fixes the remaining broken URLs when using web-server.js, but also means people can click the "Starting web server at <URL>" link in the console and immediately see Treeherder, without having to then manually navigate to index.html themselves.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/567)
> Bug 1168770 - web-server.js: Serve index.html by default, if present

- ui/css/treeherder.css
- ui/partials/main/thRelatedBugQueued.html
- ui/partials/main/thRelatedBugSaved.html
- ui/plugins/annotations/main.html
This work fixes Bugzilla bug [1168211](https://bugzilla.mozilla.org/show_bug.cgi?id=1168211).
This makes some more layout and consistency improvements to the Annotations tab, specifically:
* Switching to the same blue italic link style for annotation bugs
* Decluttering and removing bug button borders
* Using the same `table-super-condensed` table class as Similar jobs
* Using the same `0.9em` font size used elsewhere in the job panel
* Aligning classification rows to their adjacent bug rows when multiples exist
* Renaming "Datetime" to "Classified"; "Note" to "Comment", and "Failure type" to "Classification"
* Using the same date format used in the rest of Treeherder
Here's the before:
Here's after:
In the above scenario when no *Comment* exists, I had thought about having a mid-grey …
> Bug 1168211 - Continued Annotations panel improvements

- ui/js/controllers/jobs.js
- ui/js/controllers/main.js
- ui/js/models/resultset.js
- ui/js/models/resultsets_store.js
- ui/partials/main/jobs.html
- ui/partials/main/thActionButton.html
This addresses [Bug 1078209](https://bugzilla.mozilla.org/show_bug.cgi?id=1078209)
Here are the workflows this change facilitates:
1. If you have the ``revision`` value set (so you're viewing a single revision) hitting "Next N" will change the param from ``revision`` to ``tochange`` and set the ``fromchange`` to the latest loaded (earliest) resultset.
2. after loading default of latest 10, click next 10 will load them and set only the ``fromchange`` value to the latest revision loaded.  Hit next N again and it will update the ``fromchange`` to the latest again.  
Note: ``tochange`` is not updated in this scenario, so that new resultsets will continue to be loaded by default
3. The "action" menu (at the right end of each resultset) has two new menu items:
1. "Set as tochange" will set the …
> Bug 1078209 - Get next N fixes

- setup.cfg
- treeherder/log_parser/artifactbuildercollection.pyx
- treeherder/log_parser/artifactbuilders.pyx
- treeherder/log_parser/parsers.pyx
flake8/pep8 default to just checking *.py, but we have Cython .pyx files in treeherder/log_parser/.
Fixes some flake8 warnings in the pyx files so Travis is green when this lands.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/585)
> Bug 1169915 - Make flake8 check .pyx files too

- setup.py
Read the Docs has no need to install the full list of packages in requirements/common.txt, so currently gets an ImportError when trying to import from Cython. This doesn't break the build, but is misleading when it comes to debugging unrelated Read the Docs build issues.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/587)
> Bug 1169943 - Prevent setup.py ImportError on Read the Docs

- Vagrantfile
- puppet/files/apache/treeherder.conf
- puppet/manifests/classes/apache.pp
- puppet/manifests/classes/init.pp
- puppet/manifests/classes/python.pp
- puppet/manifests/classes/treeherder.pp
- puppet/manifests/vagrant.pp
* Fix race conditions with apache setup steps
* Update base image from Ubuntu 12.04 to 14.04 
* Make treeherder apache config compatible with apache 2.4 (which is now the default in 14.04)
* Clean up unnecessary installation of packages that ship with Ubuntu 14.04 by default.
* Remove workaround for older versions of puppet (since 14.04 comes with puppet 3.4.3)
(See individual commit messages for more detail)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/584)
> Bug 1144804 - Vagrant: Update base image from Ubuntu 12.04 to 14.04

- ui/js/logviewer.js
- ui/js/perfapp.js
- ui/js/treeherder_app.js
As recommended by:
https://docs.angularjs.org/guide/production
http://blog.thoughtram.io/angularjs/2014/12/22/exploring-angular-1.3-disabling-debug-info.html
The debug data can be repopulated on the fly using:
angular.reloadWithDebugInfo();
...from the console.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/590)
> Bug 1159375 - Disable Angular's debug data to improve perf

- ui/js/controllers/main.js
- ui/js/directives/clonejobs.js
- ui/js/providers.js
- ui/js/values.js
This addresses the Treeherder portion of [Bug 1164545](https://bugzilla.mozilla.org/show_bug.cgi?id=1164545)
A contributor added a feature to move to the next/previous job with the arrows.  This change modifies it slightly so it also works with unclassified failures.  That way we can remove a TON of complex code that was used for that purpose.
This way we are not relying on the ``jobMap``, we are only relying on the CSS.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/577)
> Bug 1164545 - Select next prev unclassified failure

- Gruntfile.js
grunt-usemin uses ``.tmp/`` as a staging area, however doesn't clean up after itself. As such, let's run an additional grunt-clean step at the end of the build, which removes this temporary staging directory.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/589)
> Bug 1063473 - Make grunt build clean up the .tmp directory

- docs/installation.rst
Puppet runs it on provision, so it's not necessary to do so manually.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/596)
> Bug 1170269 - Docs: Remove unnecessary initial-setup Cython compile step

- package.json
This fixes Bugzilla bug [1170330](https://bugzilla.mozilla.org/show_bug.cgi?id=1170330).
This updates the package descriptors for Treeherder, post repo-merge. I am assuming this is cosmetic only. In the interim I will do some testing with this change.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/597)
> Bug 1170330 - Update treeherder package.json post repo-merge

- treeherder/etl/perf_data_adapters.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/rewrite_perf_data.py
- treeherder/model/sql/jobs.json
- ui/js/perf.js
* We were not sorting subtest signatures before making them a property,
causing duplicate signatures
* We had tons of redundant properties
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/580)
>  	Bug 1168214 - Fix various problems with series signature calculation

- docs/deployment.rst
- docs/ui/installation.rst
This work fixes Bugzilla bug [1170172](https://bugzilla.mozilla.org/show_bug.cgi?id=1170172).
In it we do a bunch of updates for Grunt, specifically:
* centralize the documentation in the 'Development' page (should we move it to Common Tasks?)
* link to it in our main Installation page for vagrant users
* remove the (sort of duplicated) grunt docs for UI-only/web-server.js users (should we link there too?)
* remove the use of `sudo` and just say "As root" for all platforms
* try to use "project root" everywhere, and other wordsmithing
I may still need to tweak a couple of things per Ed's comments in bug [1139998](https://bugzilla.mozilla.org/show_bug.cgi?id=1139998#c0) and build the docs to test the new `development` link locally. After that I'll add a review flag.
Adding @edmorley and …
> Bug 1170172 - RTD Grunt build updates

- ui/index.html
- ui/js/directives/clonejobs.js
- ui/vendor/jquery.scrollTo.js
This addresses [Bug 1170577](https://bugzilla.mozilla.org/show_bug.cgi?id=1170577)
This adds a jquery lib to handle the scrolling, so we don't have to have the math in there to figure things out.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/599)
> Bug 1170577 - fix scrollTo after debug info removed

- ui/js/controllers/jobs.js
This just needed a check if any revisions were actually loaded, which would change the ``fromchange`` value.  If that value wasn't going to change, we don't set the ``skipNextPageReload`` bit.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/603)
> Bug 1169758 - reload repo after author filter + get next N

- docs/deployment.rst
- docs/ui/installation.rst
A small tweak to the previously landed https://github.com/mozilla/treeherder/pull/593.
I think the "if you haven't already done so" was kind of implied and not really needed. Simpler and less to read, is better.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/607)
> Bug 1170172 - RTD Grunt Build updates - supplemental

- ui/js/compareperf.js
- ui/partials/perf/comparechooserctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/588)
> Bug 1169340 - Perf Compare should validate revisions before loading

- ui/css/perf.css
This fixes 1172124 by adding setting cursor of overview plot to crosshair.
Adding @tojonmz  for review.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/613)
> Bug 1172124 - Change to crosshair cursor over graph summary

- ui/css/treeherder.css
- ui/partials/main/thRelatedBugSaved.html
- ui/plugins/annotations/main.html
- ui/plugins/pluginpanel.html
This fixes Bugzilla bug [1172039](https://bugzilla.mozilla.org/show_bug.cgi?id=1172039).
This makes the Annotation tab deletion icons more prominent, specifically:
* moving the classification deletion icon a bit closer to its adjacent column
* converting to fa-times-circle, analogue to a pinboard queued bug which uses fa-times
* darker grey for visibility, and red hover, like other 'destructive' actions like cancel job
Here's the before:
Here's after:
And on hover (sans tooltip in this screen grab):
I added a bug link tooltip while I was there, and tweaked its equivalent in the job details panel for consistency.
FF Nightly **41.0a1 (2015-06-04)**
Chrome Latest Release **43.0.2357.81 (64-bit)**
[<img …
> Bug 1172039 -  Make the classification deletion icons more prominent

- docs/installation.rst
- puppet/manifests/classes/dev.pp
* Bug 1172020 - Docs: Remove port 8000 mention on installation docs
* Bug 1172021 - Docs: Remove unnecessary steps from setup instructions
* Bug 1168741 - Docs: Emphasise that the hosts entry must be copied as-is 
* Bug 1172036 - Vagrant: Run export_project_credentials during provision
* Bug 1170827 - Docs: Add |--concurrency| to the example celery command
(See individual commit messages for more details)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/610)
> Docs: Further streamlining of initial setup docs

- treeherder/model/derived/jobs.py
I found this check not very readable, this is slightly less optimal from a performance point of view but I find it more straightforward.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/616)
> Bug 1172485 - simplify check on text_log_summary existence

- Vagrantfile
- docs/common_tasks.rst
It's sometimes useful to be able to spin up an additional Vagrant environment without affecting the first. To do this, we create two named machines, both identical (since they inherit the main Vagrantfile configuration) - one called default (to match the machine name used up until now, so we don't force people to recreate their existing VMs when we land this) and one called scratch.
The former is set to be the primary, so that single-machine commands (eg `vagrant ssh`) work without having to append the machine name every time.
The scratch machine has autostart set to false, so that it does not spin up without explicitly using: `vagrant up scratch`
The name `scratch` is entirely arbitrary, and we can add additional temporary machine names later, if people wish to have more than two …
> Bug 1173409 - Vagrant: Add support for creating a 'scratch' VM

- treeherder/log_parser/parsers.pyx
Goal here is to be able to see taskcluster specific error messages on the Failure Summary tab in TH so sheriffs have better information to go off of.
This should match error lines like:
"[taskcluster] Error: Task timeout after 3600 seconds. Force killing container."
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/627)
> Bug 1174557 - Parse taskcluster error messages

- ui/js/compareperf.js
- ui/partials/perf/comparechooserctrl.html
I fix some code style problem for bug-1169340 which has been merged. Follow French's advice, I use JSLint to find my style issue. But I found it's a little different from original code style of this file(like }); looks like code style mistake in JSLint). So, please tell me if you found some places I should improve, thank you:)
@tojonmz
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/614)
> Bug 1169340 - Supplemental linting to use correct js indentation

- ui/css/logviewer.css
- ui/css/treeherder.css
- ui/js/controllers/logviewer.js
- ui/js/directives/log_viewer_steps.js
- ui/js/models/job.js
- ui/js/models/resultset.js
- ui/logviewer.html
- ui/partials/logviewer/lvLogLines.html
- ui/partials/logviewer/lvLogSteps.html
- ui/plugins/pluginpanel.html
Now getting the header field values directly from the ``jobs`` endpoint, rather than the ``header`` field in the ``text_log_summary`` artifact.  So these are more consistent and accurate.  Also, Task Cluster won't have to fake them anymore.
Also adjusted the coloring to match the job result and the color scheme used for the main Treeherder UI.
Before:
After:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/624)
> Bug 1057341 - The log viewer overview should display properties from the job

- ui/logviewer.html
This fixes Bugzilla bug [1175191](https://bugzilla.mozilla.org/show_bug.cgi?id=1175191).
This prevents the header template from appearing during page load, particularly if the page wasn't previously loaded or cached.
Log viewer mid-load:
Everything seems fine with the change on Nightly and Chrome, and we don't see the above during page load.
We do see a few other bits but those are unrelated to the recent header work.
FF Nightly **41.0a1 (2015-06-15)**
Chrome Latest Release **43.0.2357.124**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/632)
> Bug 1175191 - Add a cloak to our new logviewer header label

- puppet/files/treeherder/.bash_aliases
delete ``celerybeat-schedule``, restart rabbitmq, and echo what it’s
doing as it goes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/638)
> Bug 1175334 - improve thresetall alias in vagrant

- ui/css/treeherder.css
- ui/help.html
- ui/js/controllers/main.js
- ui/js/services/jobfilters.js
- ui/partials/main/thWatchedRepoNavPanel.html
This adds a button to the filter search box that when clicked clears the value of the filter box.
I'm trying to get it to apply the change automatically (so that all of the currently filtered jobs become visible when the value changes to blank) but am having trouble calling or simulating the correct event to apply it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/617)
> Bug 1083725 - Add a clear button to the filter search box

- treeherder/model/derived/jobs.py
- treeherder/webapp/api/jobs.py
This adds a new param of ``visibility`` on the jobs endpoint
``visibility=included`` (the default) will return only jobs NOT excluded by the ``exclusion_profile``
``visibility=excluded`` returns ONLY jobs excluded by the ``exclusion_profile``
Has no effect if the param ``exclusion_profile=false`` is present.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/645)
> Bug 1137370 - add param to jobs endpoint to return only hidden

- requirements/common.txt
Celery 3.1.18 now requires at least Kombu 3.0.25 and billiard 3.3.0.20, so we have to update them at the same time.
http://docs.celeryproject.org/en/latest/changelog.html
https://github.com/celery/celery/compare/v3.1.16...v3.1.18
http://kombu.readthedocs.org/en/latest/changelog.html
https://github.com/celery/kombu/compare/v3.0.23...v3.0.26
https://github.com/celery/billiard/blob/v3.3.0.20/CHANGES.txt
https://github.com/celery/billiard/compare/v3.3.0.19...v3.3.0.20
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/648)
> Bug 1167212 - Update to Celery v3.1.18, Kombu v3.0.26, billiard v3.3.0.20

- ui/help.html
This fixes Bugzilla bug [1175948](https://bugzilla.mozilla.org/show_bug.cgi?id=1175948).
Nothing exciting, an extra line got added in PR https://github.com/mozilla/treeherder/pull/617, so I'm just removing it.
Before:
After:
FF Nightly **41.0a1 (2015-06-17)**
Chrome Latest Release **43.0.2357.124**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/656)
> Bug 1175948 - Remove duplicate line in Help keyboard table

- ui/help.html
- ui/js/controllers/main.js
- ui/js/providers.js
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
This work fixes Bugzilla bug [1174277](https://bugzilla.mozilla.org/show_bug.cgi?id=1174277).
This adds a shortcut `l` to open the Logviewer on the selected job. A series of screen grabs for the workflow:
Starting with a selected job:
Depress the `l` key and we launch the Logviewer the same as if the user had clicked on the icon:
I added some notifications in for users who may not notice the Job info panel or icon tooltip when job logs are either unavailable, pending, or failed and they still depress the `l` key.
Everything seems to be fine on Chrome, Opera, Safari.
Firefox - is the only browser which for better or worse treats a shortcut `.click()` as requiring the user to allow the popup. But once allowed, it's fine. There doesn't seem to be any way of getting around that. `window.open` …
> Bug 1174277 - Add a shortcut to open the Logviewer

- bin/run_celerybeat
Copies the same pattern used in the other celery wrapper scripts.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/654)
> Bug 1131244 - Use newrelic-admin run-program when running celery beat

- docs/index.rst
- docs/retrieving_data.rst
Currently documents the swagger interface to the REST API and the python
client API.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/655)
>  	Bug 1175935 - Add a section on "retrieving data" to docs

- runtime.txt
Since it breaks the Heroku Python buildpack build script.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/666)
> Bug 1176253 - Heroku: Remove licence boilerplate from runtime.txt

- ui/css/treeherder.css
This hopefully fixes our side of Bugzilla bug [1175991](https://bugzilla.mozilla.org/show_bug.cgi?id=1175991).
In it, a regression in Nightly (1173826) was [causing a variety of oversized fonts and resulting ellipses](https://bug1175991.bugzilla.mozilla.org/attachment.cgi?id=8624339) for the resultset author, sha, and revisions, on Ubuntu.
That's outside of our control, but to avoid ragged presentation of the revision column, this PR makes the revisions and main header revision monospaced, and removes the fixed width so user font size changes will push the revision comments to the right instead of ellipsizing the revisions.
I matched the spacing for the revision columns exactly so there is no change other than the font family.
Current:
Proposed:
Everything seems fine in both browsers. …
> Bug 1175991 - Use monospaced revisions for column readability

- treeherder/model/derived/artifacts.py
Currently we only gzip artifacts submitted via the artifacts endpoint and not those submitted at the same time as the job (ie using the jobs endpoint).
I'll land a test as a follow-up bug, I just don't want to block landing the fix any longer (and testing requires doing manual queries, since the API does a try-except to handle old non-compressed data; so isn't just a simple copy-paste of some of the existing tests - and I haven't had a chance to come back to it).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/674)
> Bug 1170613 - gzip artifact blobs submitted via the jobs endpoint too

- treeherder/client/thclient/perfherder.py
- treeherder/webapp/api/performance_data.py
- ui/js/graphs.js
- ui/js/perf.js
Replaced use of link decorator with the list_route decorator in performance_data.py. Also, removed the usage of /0/ in the client file client/thclient/perfherder.py.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/668)
> Bug 1167353 - Perfherder API's have a superfluous /0/ in them

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/generic.json
- treeherder/settings/base.py
Before if two celery jobs were updating the same series, one would overwrite
the other because the locking code did not actually work (it just always
unconditonally got a new lock without checking if anything was using it).
This fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/663)
>  	Bug 1171707 - Fix locking when concurrently updating performance series

- ui/css/treeherder.css
This tweak fixes the baseline text alignment in the new monospaced revisions. It was slightly high relative to the adjacent push message summaries.
FF Nightly **41.0a1 (2015-06-26)**
Chrome Latest Release 43.0.2357.130
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/686)
> Bug 1175991 - Supplemental tweak for monospaced revisions

- ui/partials/main/thActionButton.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/679)
> Bug 1156098 - Clarify the link text for Bugherder in the per-push dropdown menu

- deployment/update/update.py
- tests/conftest.py
- treeherder/model/management/commands/init_master_db.py
Since otherwise we may end up with interactive prompts.
Note: When using call_command() we instead have to use 'interactive' instead of 'noinput' due to https://code.djangoproject.com/ticket/22985, which is only fixed in Django 1.8+.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/696)
> Bug 1178719 - Use --noinput when running migrate from scripts

- tests/etl/test_buildapi.py
Fixes test_ingest_builds4h_jobs_1_missing_resultset to stop it from accessing hg.mozilla.org during the test run, causing it to fail when offline.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/690)
> Bug 1178235 - Fix test_buildapi.py so it doesn't hit the network

- .gitignore
- deployment/update/update.py
Also remove some .gitignore entries from when we had a vendor directory.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/700)
> Bug 1178832 - Cleanup leftovers from using Cython

- ui/css/logviewer.css
- ui/js/controllers/logviewer.js
- ui/js/providers.js
- ui/logviewer.html
- ui/partials/logviewer/lvLogSteps.html
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
This work fixes Bugzilla bug [1087578](https://bugzilla.mozilla.org/show_bug.cgi?id=1087578).
This adds a Reftest analyzer link to the logviewer if the loaded job belongs to a R() or R-e10s() reftest group. Here's the basic workflow and appearance:
Select any Reftest job and click on the log icon:
And in Logviewer we see our new Reftest link *'open reftest'* the same as in treeherder:
Click on the link and we get (what I understand to be) the desired results:
While I was there I added a new `actionbar` div and set a min-width so that action buttons don't wrap like they do in production below:
That became more frequent with the new link addition. If we need to add more action icons I imagine we might want to look at a navbar of some kind.
I didn't touch the parent `col-md-6` div, so the …
> Bug 1087578 - Add a ref test analyzer link in logviewer

- ui/css/treeherder.css
This tweak fixes Bugzilla bug [1132662](https://bugzilla.mozilla.org/show_bug.cgi?id=1132662).
This prevents the pinboard from shifting vertically on Firefox when the user enters a comment like so:
It seems ok to just set the height of this container to the same computed height as its child input. Since the adjacent pinboard and related bugs containers are what drive the height of the pinboard, and the comment is always only one line.
Chrome was fine anyway, but I checked the change on both browsers.
FF Nightly **41.0a1 (2015-07-01)**
Chrome Latest Release **43.0.2357.130**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/703)
> Bug 1132662 - Prevent classification comment shift on Firefox

- ui/partials/main/thWatchedRepoNavPanel.html
This tweak fixes Bugzilla bug [1180266](https://bugzilla.mozilla.org/show_bug.cgi?id=1180266).
This adds a tooltip for the Filter Platforms & Jobs input, so we don't just inherit the Firefox default of "Please fill out this field." which seems imperative/misleading, and the Chrome default of (nothing).
Everything seems fine, plus some trailing whitespace removal.
FF Nightly **41.0a1 (2015-07-03)**
Chrome Latest Release **43.0.2357.130**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/708)
> Bug 1180266 - Add a quick filter input tooltip

- tests/etl/test_classification_mirroring.py
- treeherder/etl/classification_mirroring.py
- treeherder/etl/tasks/classification_mirroring_tasks.py
* Rename submit_timestamp to classification_timestamp when referring to the datetime that a classification was made.
This avoids confusion in ElasticsearchDocRequest, since previously we had
two similarly named variables: 'job_data["submit_timestamp"]' and 'self.submit_timestamp', the former referring to the time the job was scheduled, the latter to the time the classification was submitted. 
* Include the job_id in the submission to ElasticSearch. 
So that OrangeFactor can use it to link to the log viewer (and more). Also stop sending the dummy 'logfile' key, since it's not used by OrangeFactor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/706)
> Bug 1180052 - Include the job_id in the submission to ElasticSearch

- ui/css/treeherder.css
- ui/index.html
- ui/partials/main/jobs.html
- ui/plugins/failure_summary/main.html
- ui/plugins/pluginpanel.html
- ui/plugins/similar_jobs/main.html
This tweak fixes Bugzilla bug [1180740](https://bugzilla.mozilla.org/show_bug.cgi?id=1180740).
This improves our wait/spinner cursors from the all black "smooth rotation" (which wasn't really) icon, to an 8-step pulse which seems to give a bit more polished look.
There are two new opacities; one for our 'large' spinners in the job details tabs, and a more opaque one for our 'small' spinners in the resultset container.
The animation is pretty attention getting, so I think we can use this more subtle color (`hex: #91a4dd`). It's sort of a blend of pinboard blue and search provider purple :) If anyone has another color preference let me know we can try it.
Job details current:
Job details proposed:
Main page:
Everything seems fine on both browsers.
nb. I tried to make the `-lg` spinner a bit …
> Bug 1180740 - Improve the wait/spinner cursors

- ui/help.html
- ui/js/controllers/main.js
- ui/js/directives/clonejobs.js
- ui/js/providers.js
- ui/plugins/annotations/controller.js
- ui/plugins/controller.js
- ui/plugins/pinboard.js
The treeherder and treeherder-ui repos were unified today. This treeherder PR is a continuation of -ui PR https://github.com/mozilla/treeherder-ui/pull/534 from the now retired treeherder-ui repo.
There are no changes beyond those last visible in the old PR. There is one additional check with @camd I'd like to do, plus additional testing in the new unified repo structure.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/544)
> Bug 1164166 - Create a shortcut to delete a classification

- tests/client/data/resultset_data.json
- tests/client/test_treeherder_client.py
- tests/etl/test_buildapi.py
- tests/model/derived/conftest.py
- tests/sample_data/hg_pushlog.json
- tests/sample_data/resultset_data.json
- treeherder/client/thclient/client.py
- treeherder/etl/common.py
- treeherder/etl/mixins.py
- treeherder/etl/pushlog.py
- treeherder/model/derived/jobs.py
- treeherder/model/sample_data/pushlog.json.sample
- treeherder/model/sql/jobs.json
- treeherder/model/sql/template_schema/project_jobs.sql.tmpl
Since we're not currently using it, and the schema we need will likely be different if we were to start using it in the future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/714)
> Bug 1179214 - Stop storing the list of files changed in a revision

- requirements/common.txt
- treeherder/settings/base.py
- treeherder/webapp/urls.py
- treeherder/webapp/whitenoise_custom.py
- treeherder/webapp/wsgi.py
* Use WHITENOISE_ROOT instead of add_files() …
Instead of manually adding the UI directory using add_files(), we can use WhiteNoise's `WHITENOISE_ROOT` variable, per: http://whitenoise.evans.io/en/latest/django.html?#WHITENOISE_ROOT
* Update to v2.0.2 …
https://github.com/evansd/whitenoise/blob/master/CHANGELOG.rst
https://github.com/evansd/whitenoise/compare/v1.0.6...v2.0.2
* Remove superfluous `staticfiles_urlpatterns()` …
WhiteNoise 2.0 now uses staticfiles "finders" in development as of evansd/whitenoise@25f5757 so we don't need to handle urlpatterns for static asserts in urls.py.
* Combine definitions of `urlpatterns`
* Serve index.html for bare '/' URIs too …
Customise the DjangoWhiteNoise class, so that we add additional dummy '/' entries to the file mapping, for each index.html …
> Bug 1176482 - Update to WhiteNoise v2.0.2 and add custom index file & cache max-age support

- bin/peep.py
- setup.cfg
* Tolerates `pip.__version__` being missing, which can happen in arcane
situations during error handling, obscuring informative tracebacks.
* flake8 warnings are fixed again, so peep.py can be removed from the
exclude list.
https://github.com/erikrose/peep/releases/tag/2.4.1
https://github.com/erikrose/peep/compare/2.4...2.4.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/719)
> Bug 1181529 - Update peep to v2.4.1

- requirements/common.txt
- requirements/dev.txt
https://github.com/linsomniac/python-memcached/blob/master/ChangeLog
https://github.com/linsomniac/python-memcached/compare/8078ecfe...release-1.54
python-memcached now requires the package 'six', so that has to be listed in common.txt and not just dev.txt.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/722)
> Bug 1181587 - Update python-memcached to v1.54

- requirements/common.txt
Only one change:
* Fixed AttributeErrors on exit on Python 2.x
https://github.com/agronholm/pythonfutures/blob/master/CHANGES
https://github.com/agronholm/pythonfutures/compare/3.0.2...3.0.3
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/725)
> Bug 1181693 - Update futures to v3.0.3

- ui/index.html
- ui/js/directives/treeherder/resultsets.js
- ui/partials/main/jobs.html
This tweak fixes Bugzilla bug [1181636](https://bugzilla.mozilla.org/show_bug.cgi?id=1181636).
This makes the Author title use the same term ('View') as the Date title, and capitalizes other titles in the bar for consistency.
FF Nightly 41.0a1 (2015-07-05)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/724)
> Bug 1181636 - Improve the resultset bar tooltips

- requirements/common.txt
https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst
https://github.com/Julian/jsonschema/compare/v2.4.0...v2.5.1
jsonschema now also requires functools32.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/728)
> Bug 1181776 - Update jsonschema to v2.5.1

- requirements/common.txt
https://github.com/linsomniac/python-memcached/blob/master/ChangeLog
https://github.com/linsomniac/python-memcached/compare/8078ecfe...release-1.53
python-memcached v1.54 has a performance regression, so only update to v1.53 for now. See:
https://github.com/linsomniac/python-memcached/issues/71
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/734)
> Bug 1181587 - Update python-memcached to v1.53

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
Since they can be up to 800+ KB in size and whilst there are not many rows in the table, if they are not compressed it bloats the binlogs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/736)
> Bug 1182201 - Compress blobs in the performance_series table

- treeherder/model/derived/artifacts.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/rewrite_perf_data.py
- treeherder/model/utils.py
* Create a utils.py helper for zlib.decompress try-except …
We have several places where we need to decompress blobs, but have to gracefully handle old data that is not compressed. Let's use a helper function to save repeating the same pattern everywhere.
* Decompress performance_series blobs in a few more places …
Fix a few places where we weren't decompressing the blob retrieved from the performance_series table.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/737)
> Bug 1182201 - performance_series blobs are not compressed (part 2)

- ui/css/treeherder.css
- ui/index.html
- ui/js/directives/treeherder/clonejobs.js
- ui/partials/main/jobs.html
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thWatchedRepoNavPanel.html
- ui/plugins/pluginpanel.html
This work fixes Bugzilla bug [1181685](https://bugzilla.mozilla.org/show_bug.cgi?id=1181685).
This reconciles the name of the main Treeherder elements for future selenium testing, and a shared understanding/terminology for the various parts of the UI for new and current users.
I opted to use '*info-panel*' instead of the originally proposed '*details-panel*', for our main lower panel, as it's a bit more generalized and doesn't overload the word 'details' which we are also using here for job details.
I also did a pass on the main navbar, resultset elements, and minor css rearrangement where it made sense.
FF Nightly **42.0a1 (2015-07-09)**
Chrome Latest Release **43.0.2357.132 (64-bit)**
Adding @wlach for review and @rbillings …
> Bug 1181685 - Reconcile main UI element names/ids

- requirements/common.txt
To pick up the whitespace-stripping change, amongst others:
https://github.com/jeads/datasource/compare/v0.7...v0.8
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/746)
> Bug 1182485 - Update to datasource v0.8

- tests/test_setup.py
- treeherder/model/management/commands/run_sql.py
Since otherwise we get access denied errors using run_sql on Heroku.
All other calls use datasource, so have already been set up to pass the SSL options.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/743)
> Bug 1182372 - Pass the database SSL options to MySQLdb.connect()

- tests/conftest.py
- tests/model/sql/test_models.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/init_datasources.py
- treeherder/model/management/commands/run_sql.py
- treeherder/model/migrations/0001_initial.py
- treeherder/model/models.py
- treeherder/model/sql/template_schema/treeherder.sql.tmpl
Having the ability to use different DB hosts for each project sounded like a good idea, but in reality, we have no need for it.
This switches us to using the global read-write and read-only database host names rather than the fields on the datasource table. As such, the 'host', 'read_only_host' and 'type' (eg 'mysql') fields can be removed. The Django model had a unique_together on host+name, so we now need to make 'name' (ie database name) a unique key on it's own.
In addition, this removes the 'creation_date' field, since we don't use it anywhere, and we can just look at the commit history to see when a repo was created. (I imagine it may have had more use if we actually had started partitioning the databases uses the old 'dataset' count field).
In a future bug, I'll remove the …
> Bug 1182455 - Remove support for different DB hosts per datasource

- treeherder/webapp/api/artifact.py
- treeherder/webapp/api/bug.py
- treeherder/webapp/api/performance_artifact.py
- treeherder/webapp/api/resultset.py
Since currently the datasource package does not validate the limit parameter correctly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/750)
> Bug 1182994 - Cast API offset parameter to int

- requirements/common.txt
- treeherder/model/derived/artifacts.py
- treeherder/model/derived/jobs.py
* Update to Datasource v0.9, to get the SQL injection and `offset` parameter fixes (https://github.com/jeads/datasource/compare/v0.8...v0.9)
* Use datasource's `offset` parameter. As part of Datasource v0.9's SQL injection fix, it no longer supports passing comma-delimited strings to the `limit` parameter, to denote the SQL LIMIT/OFFSET. Instead we need to pass integers to Datasource's `limit` and `offset` params separately. The `offset` param now actually works in Datasource v0.9, unlike previous releases.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/751)
> Bug 1182994 - Use datasource v0.9's fixed offset parameter

- treeherder/model/models.py
- treeherder/model/sql/template_schema/project_jobs.sql.tmpl
- treeherder/model/sql/template_schema/project_objectstore.sql.tmpl
- treeherder/model/sql/template_schema/treeherder.sql.tmpl
- treeherder/model/sql/template_schema/treeherder_reference_1.sql.tmpl
Since after bug 1182455, engine is now guaranteed to always the same for all projects, so we can just specify it in the schema directly.
As an added bonus, the templates are now valid SQL.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/748)
> Bug 1182465 - Remove substitution of 'engine' in the template schema

- docs/submitting_data.rst
- treeherder/webapp/api/logslice.py
- ui/js/controllers/logviewer.js
- ui/js/models/log_slice.js
This allows a user to submit log references with custom names.  They then must specify that name in their custom ``text_log_summary`` for the log viewer to find the log to slice and show lines.
The docs in this PR explain how this will work.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/738)
> Bug 1182299 - Support custom logname param in logslice

- tests/client/test_treeherder_client.py
- tests/e2e/test_client_job_ingestion.py
- tests/etl/test_buildapi.py
- tests/webapp/api/test_objectstore_api.py
- treeherder/client/thclient/client.py
- treeherder/webapp/api/objectstore.py
This branch will:
1. Stop adding jobs to the ``objectstore`` but still process what is in there to allow it to "drain".
2. Add new jobs directly to the jobs tables
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/689)
> Bug 1140349 - Bypass and drain the objectstore

- ui/plugins/pluginpanel.html
This fixes Bugzillla bug [1166984](https://bugzilla.mozilla.org/show_bug.cgi?id=1166984).
This provides a '**Taskcluster:** Inspect Task' link in the Job details panel, while preserving the current Inspect Task in the Job details tab, per the bug thread.
We are ok with the labels deviating for a more user friendly label in the Job details panel vs. the artifact blob name in the tab. Here's the new appearance:
Everything seems fine on both browsers, with both buildbot jobs (suppressed) and taskcluster jobs (displayed) in various repos, n/p navigation, refresh, and link navigation.
Nightly **42.0a1 (2015-07-13)**
Chrome Latest Release **43.0.2357.132 (64-bit)** …
> Bug 1166984 - Provide inspect-task link in Job details panel

- treeherder/model/sql/generic.json
- treeherder/model/sql/jobs.json
- treeherder/model/sql/reference.json
These SQL procs are not used anywhere in the repo:
generic.selects.get_db_size
jobs.selects.get_result_set_job_list
jobs.selects.get_result_set_job_list_full
jobs.selects.get_revision_map_id
objectstore.selects.get_json_blob_for_test_run
objectstore.selects.get_error_metadata
objectstore.selects.get_all_errors
objectstore.selects.get_error_counts
reference.inserts.create_repository_group
reference.selects.get_option_collection_hash
reference.selects.get_max_collection_hash
reference.selects.get_option_names
reference.selects.get_repository_group_id
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/752)
> Bug 1183137 - Remove unused in-repo SQL procs

- ui/css/perf.css
- ui/partials/perf/comparectrl.html
- ui/partials/perf/comparesubtestctrl.html
Use "base" as opposed to "old". Reformat revision information into
clearer list form
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/758)
>  	Bug 1181686 - Make nature of revisions in perfcompare more clear

- docs/troubleshooting.rst
This fixes Bugzilla bug [1184247](https://bugzilla.mozilla.org/show_bug.cgi?id=1184247).
This adds a small Troubleshooting entry for celerybeat-schedule removal for occasions where ingestion doesn't appear to be working.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/765)
> Bug 1184247 - Add celerybeat-schedule removal to RTD Troubleshooting

- treeherder/client/thclient/client.py
- treeherder/settings/base.py
I enabled the api html rendered so that if you fetch one of the endpoints using your browser
(i.e. with a 'Accept: text/html' header) it will return the right content type.
The default renderer is still the json one though, so it should be back-compatible.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/773)
> Bug 1184542 - enable browsable api

- .eslintrc
- Gruntfile.js
Previously we disabled all default rules, and only turned on those that were explicitly listed in .eslintrc. Now we leave the default rules alone, apart from those that we are currently failing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/774)
> Bug 1184614 - ESLint: Switch from a whitelist to a blacklist approach

- ui/js/directives/treeherder/clonejobs.js
- ui/js/values.js
Fix to the fix: My earlier attempt used a JQuery ``filter`` where it should have used a
``find``
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/777)
> Bug 1184311 - Get classification looping correctly again with 1st/last pinned

- ui/css/logviewer.css
This fixes Bugzilla bug [1183847](https://bugzilla.mozilla.org/show_bug.cgi?id=1183847).
This provides a Github/Mozreview style pink background to error lines in logviewer, so when the user is scrolling quickly they are less likely to scroll past or miss the errors.
Current:
Proposed:
It also works reasonably well with all colorblind conditions including the worst case,  Achromatopsia.
It also seems fine with line-errors both large and small.
Nightly **42.0a1 (2015-07-16)**
Chrome Latest Release **43.0.2357.132 (64-bit)**
Adding @wlach for review and @jonallengriffin for visibility.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/783)
> Bug 1183847 - Style logviewer line errors for fast scrolling

- ui/plugins/controller.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/771)
> Bug 1171575 - Remove unused cancel_all function from controller.js

- treeherder/events/publisher.py
- treeherder/webapp/api/note.py
- ui/js/controllers/jobs.js
This hopefully fixes Bugzilla bug [1168652](https://bugzilla.mozilla.org/show_bug.cgi?id=1168652).
This removes what we believe to be dead code in updateClassification(). I have tested fairly exhaustively with saving/deleting classifications, deleting multiple classifications (shortcut and via Annotations panel) and everything seems to still be working correctly in vagrant w/runserver. I also did a full Moztrap run with the branch yesterday.
Some minor pseudo-eslint compliance was added in an adjacent but unrelated block.
Please add extra scrutiny to this PR if possible, but there is no rush for this change :)
Nightly **42.0a1 (2015-07-16)**
Chrome Latest Release **43.0.2357.134 (64-bit)**
Adding @camd and @maurodoglio for review.
[<img …
> Bug 1168652 - Remove unused updateClassification and related code

- tests/etl/test_buildapi.py
- treeherder/etl/buildapi.py
- treeherder/etl/mixins.py
To avoid continually attempting to re-ingest them, thereby reducing task runtime and database load.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/767)
> Bug 1178240 - Cache previously seen builds-{pending,running,4hr} jobs

- ui/css/logviewer.css
- ui/js/controllers/logviewer.js
- ui/logviewer.html
This work (hopefully) fixes Bugzilla bug [1092209](https://bugzilla.mozilla.org/show_bug.cgi?id=1092209).
In it we add the equivalent of the Treeherder *job_details* artifact content to logviewer so the user doesn't have to navigate back to Treeherder to find the same information. We decided not to bother including Buildbot artifacts since they will soon be retired. Here are examples of the new content (yellow highlights for the PR only):
Basically anything that appears in our Treeherder **Job Info** tab, excluding 'Buildername', should show up here.
I also dropped the main header font size from 12 to 11px and tried to economize space a bit more since generally we'll have more content, and if the only item added is 'Inspect Task' it should fit without a scroll bar.
Everything seems fine …
> Bug 1092209 - Add tinderbox lines to logviewer

- ui/js/directives/treeherder/clonejobs.js
This tweak fixes Bugzilla bug [1186496](https://bugzilla.mozilla.org/show_bug.cgi?id=1186496).
This change ensures thNotify isn't misleading during page load, since there aren't "more" available yet. Instead we omit it in the message to work for all cases.
Proposed:
Nightly **42.0a1 (2015-07-21)**
Chrome Latest Release **44.0.2403.89 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/799)
> Bug 1186496 -  Improve the unclassified failure selection message

- treeherder/etl/buildapi.py
The blobber_files property on jobs in builds-4hr is a json blob, containing a number of name-url pairs. In some cases this blob is truncated, so fails to decode. This change makes us handle these failures more gracefully (by treating it as though the blobber_files property was not set for that job), rather than causing the entire builds-4hr task to fail.
Bug 1187284 is filed to try and make mozharness never output truncated json in the first place.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/809)
> Bug 1187267 - Handle invalid builds-4hr blobber_files json gracefully

- ui/css/treeherder.css
- ui/index.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/678)
> Bug 1136918 - Get rid of the link to hg.m.o in the revision list and move it to a separate button

- ui/help.html
This fixes Bugzilla bug [1186936](https://bugzilla.mozilla.org/show_bug.cgi?id=1186936)
This switches our former 'Build' link to the new **WhatsDeployed** service at https://whatsdeployed.paas.allizom.org
Proposed:
Nightly **42.0a1 (2015-07-22)**
Chrome Latest Release **44.0.2403.89 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/803)
> Bug 1186936 - Add WhatsDeployed to the Help footer

- ui/css/treeherder.css
- ui/partials/main/jobs.html
This fixes Bugzilla bug [1187403](https://bugzilla.mozilla.org/show_bug.cgi?id=1187403).
This improves the resultset bar layout post-bug 1136918, which added double-click space to the left of the revision column for copy-selection. So with this proposed change we have a clean layout again.
Current:
Proposed:
And our SHA selection still works fine:
And our *Hide revision list* also aligns to the new location:
We only consume 20px in the adjustment and we still have plenty of space in the resultset bar for its contents. It just wraps the contents 20px earlier at extremely narrow browser widths.
We add one div per resultset, which seems low cost. The nature of the existing containers prevented using them for the light grey boundary, which Wes wanted to preserve.
Everything seems fine on both …
> Bug 1187403 - Improve resultset bar layout for bug 1136918

- tests/log_parser/test_performance_log_parser.py
- treeherder/log_parser/parsers.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/812)
>  	Bug 1188132 - Fix log parsing when logs have TALOSDATA in them

- treeherder/model/fixtures/repository.json
Since they are EOL.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/813)
> Bug 1188346 - Disable the mozilla-b2g32_v2_0 & mozilla-b2g34_v2_1 repos

- tests/webapp/api/test_note_api.py
- treeherder/model/sql/jobs.json
The sample notes added for the test normally have the same timestamp for several notes, but not always. With the previous `ORDER BY`, this meant the list of notes retrieved could vary in order depending on if the timestamps were identical. We now additionally sort by id (descending, to match the timestamp sort), so the returned list is deterministic.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/815)
> Bug 1188832 - Fix intermittent Travis test failure in test_note_api

- ui/css/logviewer.css
- ui/js/directives/treeherder/log_viewer_steps.js
- ui/logviewer.html
- ui/partials/logviewer/lvLogSteps.html
This work fixes Bugzilla bugs:
[1183872](https://bugzilla.mozilla.org/show_bug.cgi?id=1183872) address the inherent space limit to our logviewer "actionbar" under the failure steps container
[1183880](https://bugzilla.mozilla.org/show_bug.cgi?id=1183880) provide cross service navigation and easier Treeherder-esque recognition
Both were resolved by a bootstrap navbar, similar to Treeherder and Perfherder. We now have the ability to add as many action functions as we need, and users can easily navigate to Treeherder or Perfherder, and at a glance identify what product set they are using.
Current:
Proposed, also matches our Bugzilla [mockup](https://bug1183872.bmoattachments.org/attachment.cgi?id=8638108):
And a reftest example with additional analyser button:
And an adjusted scrollTo …
> Bugs 1183872 1183880 - Improve logviewer layout with a navbar

- requirements/common.txt
The wheel package which is the default to be installed accidentally got
swapped with 1.55: https://github.com/linsomniac/python-memcached/issues/72
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/819)
>  	Bug 1189499 - Use link to .tar.gz when downloading python-memcached

- ui/logviewer.html
This fixes Bugzilla bug [1189479](https://bugzilla.mozilla.org/show_bug.cgi?id=1189479).
This should remove any outstanding angular template flicker in logviewer during page load.
I tested the changes on my gh-pages since my macbook pro is so quick it's hard to locally test the failure condition. So now we correctly suppress the {{line.value}} row.
(mid-load apparance with the fix)
Nightly **42.0a1 (2015-07-30)**
Chrome Latest Release **44.0.2403.125 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/820)
> Bug 1189479 - Fix angular template flicker in logviewer

- ui/css/logviewer.css
- ui/logviewer.html
This fixes Bugzilla bug [1189475](https://bugzilla.mozilla.org/show_bug.cgi?id=1189475).
This improves our Logviewer navbar action buttons by removing the perception they may be disabled, and using the same Perfherder colors ie. bootstrap behavior.
Current ( appears somewhat disabled at `#9fa3a5` now that it is in the navbar ):
Proposed ( matches Perfherder's navbar aka. bootstrap, `#777` ):
And on hover, the same matching behavior and color styles:
I needed to leave one `#777` targeting the child span of show successful steps, since bootstrap only targets the anchors and for that button there isn't one. I also vertically aligned the checkbox with show successful steps while there.
Everything seems fine on both browsers.
Nightly **42.0a1 (2015-07-31)**
Chrome Latest …
> Bug 1189475 - Match logviewer navbar action buttons w/bootstrap

- ui/partials/perf/comparetable.html
If we already have 6 runs for base / new, more won't really help, even
if we have low/medium confidence.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/824)
>  	Bug 1189826 - Don't recommend retriggering if we have full set of runs

- ui/css/treeherder.css
- ui/plugins/pluginpanel.html
This tweak fixes Bugzilla bug [1189484](https://bugzilla.mozilla.org/show_bug.cgi?id=1189484).
In Bug [1183880](https://bugzilla.mozilla.org/show_bug.cgi?id=1183880) we adjusted the raw log icon in Logviewer's navbar to `fa-file-text-o`:
So this PR applies the same treatment in Treeherder's job details action bar.
Current:
Proposed:
I split the difference between our larger Logviewer .svg icon (which we emphasize to users), and the default 12px icons for the rest of the action bar, at `14px`. The interior lines of the icon seem to hold up well at that size on both my OSX retina and my ancient windows PC :)
Nightly **42.0a1 (2015-07-31)**
Chrome Latest Release **44.0.2403.125 (64-bit)**
[<img src="https://reviewable.io/review_button.png" …
> Bug 1189484 - Match treeherder raw log icon to logviewer's

- tests/conftest.py
- treeherder/etl/common.py
- treeherder/model/error_summary.py
* Remove unused `etl.common.retrieve_api_content()`
* Switch from urllib to requests for bugscache API query. urllib isn't handling the unicode found in some log lines correctly, whereas requests does. This prevents UnicodeEncodeError exceptions when making the request to the bugscache API to find the bug suggestions for these log lines.
Note: webtest's TestApp raises if the HTTP status code is not 200, due to the `status=200` param, which makes the check of `response.status_int` redundant.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/825)
> Bug 1165335 - Switch from urllib to requests for bugscache API query

- Vagrantfile
- docs/installation.rst
We require 1.5+ due to the use of just the box name, without the box URL.
This is now listed in the setup docs, plus fails more with a clearer error message during `vagrant up`, thanks to `Vagrant.require_version`:
http://docs.vagrantup.com/v2/vagrantfile/vagrant_version.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/827)
> Bug 1190894 - Vagrant: Make it clearer that vagrant v1.5+ is required

- tests/webapp/api/test_auth.py
- tests/webapp/api/test_resultset_api.py
- treeherder/settings/base.py
- treeherder/webapp/api/artifact.py
- treeherder/webapp/api/auth.py
- treeherder/webapp/api/bug.py
- treeherder/webapp/api/job_log_url.py
- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/logslice.py
- treeherder/webapp/api/note.py
- treeherder/webapp/api/performance_artifact.py
- treeherder/webapp/api/permissions.py
- treeherder/webapp/api/refdata.py
- treeherder/webapp/api/resultset.py
- treeherder/webapp/api/utils.py
The changes in the first version of this patch introduced a regression due to the different way the oauth user parameter is interpreted by the python client vs the nodejs client. To maintain backward compatibility now we first look at the project name provided in the uri, and then we fallback to the user parameter on the querystring
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/826)
> Bug 1185520 make the oauth check backward compatible

- .eslintrc
- ui/css/treeherder.css
- ui/index.html
- ui/js/controllers/main.js
- ui/js/directives/treeherder/clonejobs.js
- ui/js/models/resultsets_store.js
- ui/js/providers.js
- ui/js/services/main.js
- ui/partials/main/jobs.html
- ui/partials/main/thWatchedRepoNavPanel.html
This branch aggregates non-failed jobs within groups and shows the counts of each result/state within.  A ``+`` precedes each count to indicate that's what it is.
A few points of interest:
* Clicking any group or count will expand or collapse the group.  This choice is remembered as jobs are updated and filters are changed.  Page reload resets it.
* Clicking on the ``( + )`` and ``( - )`` buttons will toggle groups expanded/collapsed globally.  This is persisted in the URL.  Clicking this button will reset any group expand/collapse state that was set individually.
* Failed Unclassified jobs are never put into "counts".  They show as top-level jobs and are still hit with the ``n`` and ``p`` hot keys, etc.
Play with it live here: http://camd.github.io/treeherder/ui/#/jobs?repo=mozilla-inboun …
> Bug 1163064 - Collapse test groups and chunks

- treeherder/client/setup.py
- treeherder/client/thclient/client.py
* Make the version available at runtime …
So we can use it in the User-Agent later. Uses the suggestion from:
https://packaging.python.org/en/latest/single_source_version.html
* Use a constant for request headers …
In the next commit we'll be adding a custom user agent header, which will increase duplication. Therefore let's define the headers only once to avoid this. The `Content-Type` header is redundant for `.post()` since one is set automatically when using the `json` param:
https://github.com/kennethreitz/requests/blob/f5dacf84468ab7e0631cc61a3f1431a32e3e143c/requests/models.py#L418
* List client name+version in the User-Agent …
So we can more easily see which API requests are coming from which client type, and know how many people are on older versions of the client.
[<img …
> Bug 1186918 - Set a custom user-agent for python client requests

- docs/submitting_data.rst
It was using Markdown rather than reStructuredText syntax.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/838)
> Bug 1191738 - Fix code block markup in submitting_data.rst

- ui/partials/perf/revisiondescribe.html
Previously the link target was pointing at a different revision to that displayed in the link text.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/837)
> Bug 1191632 - Use correct 'new' revision for hg.m.o link generation

- tests/webapp/api/test_jobs_api.py
- treeherder/webapp/api/jobs.py
- ui/js/models/job.js
- ui/partials/main/thPinboardPanel.html
- ui/plugins/controller.js
- ui/plugins/pinboard.js
- ui/plugins/pluginpanel.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/787)
> Bug 1121998 - Add the ability to retrigger all pinned jobs

- ui/css/perf.css
- ui/js/perf.js
- ui/partials/perf/comparetable.html
* Show visual scale of results so it's more obvious what the bar means
(% improvement capped at 100%)
* Allocate a smaller, fixed space for the bar graph (give more space for
the test labels, which are often quite long)
* Show differences > % even if unsure (just show a greyed out bar chart
for those)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/829)
>  	Bug 1170305 - Improve display of bar graphs in perfherder compare view

- ui/js/directives/treeherder/clonejobs.js
This fixes Bugzilla bug [1077338](https://bugzilla.mozilla.org/show_bug.cgi?id=1077338).
In the change we open Logviewer for a completed job, when the user selects a job via middle-mouse click. So we start here:
We land here:
Everything seems fine on both browsers, testing a variety of jobs (testfailed, busted, success, retry) where we launch, and pending and running where we will do nothing on the click event, the same as we do now when a raw log doesn't exist.
Nightly **42.0a1 (2015-08-05)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/839)
> Bug 1077338 - Open logviewer on middle-mouse job click

- ui/logviewer.html
- ui/partials/logviewer/lvLogLines.html
- ui/partials/logviewer/lvLogSteps.html
This fixes Bugzilla bug [1189481](https://bugzilla.mozilla.org/show_bug.cgi?id=1189481) and converts logviewer markup from a mix of 4 and 2 space indentation, to 2 space indentation.
Nightly **42.0a1 (2015-08-06)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/843)
> Bug 1189481 - Convert logviewer markup to 2 space indent

- ui/css/treeherder.css
This tweak fixes Bugzilla bug [1192195 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1192195).
In it we provide a style and Bootstrap-esqe 'info' color for skipped steps.
Bootstrap [alert info](http://getbootstrap.com/components/#alerts) is **rgb**(208, 232, 246) and the proposed PR computed color with our 0.25 transparency over white, is **rgb**(207, 235, 244) which is very close.
Current (missed styling on skipped step):
Proposed:
Everything seems ok on both browsers. I did some minor linting during the change.
Nightly **42.0a1 (2015-08-06)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/845)
> Bug 1192195 - Provide a style for result-status skipped

- ui/js/controllers/logviewer.js
This fixes Bugzilla bug [1192198](https://bugzilla.mozilla.org/show_bug.cgi?id=1192198).
This prevents a skipped step from being interpreted as a failed step, which undesirably suppresses successful steps and exposes the 'show successful steps' UI in the logviewer navbar.
A skipped step should be interpreted more as an 'info' step, in the sense it should be present everywhere, but not considered a failure.
Current (successful job):
Proposed:
(same job above, scrolled to show the presence of the skipped step)
And a testfailed example which will continue to display skipped steps also:
Everything seems fine testing a variety of jobs containing skipped steps.
Nightly **42.0a1 (2015-08-06)** …
> Bug 1192198 - Evaluate a skipped step as a non-failure

- ui/css/treeherder.css
- ui/help.html
- ui/plugins/pluginpanel.html
This fixes Bugzilla bug [1189484](https://bugzilla.mozilla.org/show_bug.cgi?id=1189484).
This updates the raw log to our new `fa-file-text-o` in two additional cases:
* selecting a pending job when no raw log is available
* opening Help
The first case looks identical to our new raw log icon in https://github.com/mozilla/treeherder/pull/822 so I'm not including a screen grab, but here is the Help update:
Nightly **42.0a1 (2015-08-04)**
Chrome Latest Release **44.0.2403.125 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/832)
> Bug 1189484 - Update disabled/help raw log icons

- ui/css/logviewer.css
- ui/js/controllers/logviewer.js
- ui/js/directives/treeherder/log_viewer_steps.js
- ui/partials/logviewer/lvLogLines.html
This work fixes Bugzilla bug [1182068](https://bugzilla.mozilla.org/show_bug.cgi?id=1182068).
In this change we load the first failed step and error line available if one exists for the Logviewer, and if an error doesn't exist we load the head of the log.
Current:
Proposed (failure):
Proposed (success):
There are a few outlier logs around where the artifact appears to be in conflict eg. a green success but the artifact contains failure lines (which are "Info"), but I think those may be issues for follow up bugs unrelated to Logviewer. I will try to isolate those later and enter bugs for them.
Nightly **42.0a1 (2015-08-04)**
Chrome Latest Release **44.0.2403.125 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 …
> Bug 1182068 - Load log content in Logviewer by default

- docs/common_tasks.rst
- docs/installation.rst
The shell prompts for each command example already mention vagrant, but this can still be missed, so make the distinction extra clear.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/852)
> Bug 1191602 - Docs: Clarify which commands should be run inside the VM

- docs/installation.rst
- docs/troubleshooting.rst
* Move Vagrant troubleshooting steps to their own page - since most people will not require them, and the list is growing quite large.
* Add a prerequisites section which links to Bootcamp. Also mention the need for Git to be installed & link to Git website.
* Add Windows-specific setup help. Fixes #684.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/854)
> Bug 1178300 - Add Windows-specific setup help & clean up troubleshooting section

- treeherder/webapp/wsgi.py
The agent is supposed to be initialised before any other imports. In addition, we're supposed to use WSGIApplicationWrapper() if we're not using it as a decorator.
This unfortunately doesn't fix bug 1191080 itself, or answer the question of whether we should instead be using the wrapper scripts (which incidentally don't fix the bug either), but if we're going to initialise the agent manually, then at least let's do it the way the docs recommend.
See:
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-integration#wsgi-application
https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-instrumentation-api#WSGIApplicationWrapper …
> Bug 1191080 - Initialise the New Relic agent correctly

- ui/plugins/annotations/controller.js
- ui/plugins/controller.js
- ui/plugins/pinboard.js
Need this change for the Collapsed Job Groups PR.  Certain circumstances had an issue when the extra select happened.  This removes the requirement to re-select the job after classifying/declassifying.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/861)
> Bug 1192375 - Refactor save classification to update Annotations correctly

- deployment/update/update.py
- puppet/manifests/vagrant.pp
- requirements.txt
- requirements/common.txt
- requirements/prod.txt
- treeherder/webapp/wsgi.py
For bug 1124278, we're going to want to sprinkle new relic annotations around the codebase, so by always installing it, we save having to stub these out in development/on Travis. It also seems wise to have prod running as close to the same packages as in development.
Since NEW_RELIC_LICENSE_KEY isn't set locally, plus NEW_RELIC_DEVELOPER_MODE is set to true, the New Relic agent doesn't submit anything.
See:
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-configuration#developer_mode
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/858)
> Bug 1169944 - Always install the New Relic package, not just on prod

- ui/partials/perf/comparesubtestctrl.html
The reason why subtest compare doesn't show error message is because somehow the error message part been nested into the dataLoading block. So it doesn't shows up if the dataLoading is false because error list wasn't empty. ;)
Now the error can shows up normally.
Test on OS X 10.10.4
Firefox 39.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/862)
> Bug 1189599 - subtest compare view doesn't show error message

- treeherder/log_parser/artifactbuilders.py
- treeherder/log_parser/parsers.py
There is only ever one TALOSDATA line in a log file, so once it has been seen there is no need to run TalosParser against later log lines.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/864)
> Bug 1193715 - Mark TalosParser complete once the TALOSDATA log line seen

- treeherder/settings/base.py
PULSE_USERNAME and PULSE_PASSWORD are not actually defined anywhere, including in production. Instead we're relying on production's local.py to set the value, rather than prod's PULSE_URI, which _is_ set. By switching to use PULSE_URI, we're one step closer to not needing local.py on prod.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/871)
> Bug 1160561 - Use correct env variable for PULSE_URI

- ui/css/logviewer.css
- ui/js/controllers/logviewer.js
- ui/logviewer.html
- ui/partials/logviewer/lvLogLines.html
This work fixes Bugzilla bug [1193216](https://bugzilla.mozilla.org/show_bug.cgi?id=1193216).
This provides both a landing and navigation notification, and a persistent UI warning that the log is unavailable (ie. if the user had simply pinned the page and returned to it.)
I decided to not inject the domain into the error message or link to the log; but instead cue the user to click on the raw log link we already provide in the navbar, which implicitly contains both the domain and the link.
I'm also making the case here - that since we have valid data in the form of the job header it's not a completely invalid page, so our bootstrap warning color (yellow) is appropriate. I do fully intend to use our bootstrap error (red) for bug [1193222](https://bugzilla.mozilla.org/show_bug.cgi?id=1193222 …
> Bug 1193216 - Improve log not found notifications in logviewer

- ui/css/logviewer.css
- ui/css/treeherder.css
- ui/js/directives/treeherder/log_viewer_lines.js
- ui/js/directives/treeherder/log_viewer_steps.js
- ui/logviewer.html
- ui/partials/logviewer/lvLogSteps.html
This work fixes Bugzilla bug [1189482](https://bugzilla.mozilla.org/show_bug.cgi?id=1189482).
This converts the remaining `.logviewer-` classes to `.lv-` and also retires some dead classes and an unnecessary step property.
Nightly **42.0a1 (2015-08-10)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/860)
> Bug 1189482 - Convert remainder of 'logviewer-' to 'lv-'

- docs/common_tasks.rst
This has several advantages over pushing a custom branch to stage:
1) No need to continually grunt build.
2) Several people can test their own UI changes at once, on their own github pages fork.
3) Reduced churn of stage deployments / avoids regressing what is deployed there (eg forgetting to rebase the UI test branch on master).
4) Means we don't get in the way of other people trying to use stage for normal testing of master.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/866)
> Bug 1193775 - Document how to test UI-only changes using GitHub pages

- tests/log_parser/test_log_view_artifact_builder.py
Previously the tests were created after `act["logurl"]` was deleted, so the resultant expected output .json file was missing the "logurl" key. The json import was also missing - people now just have to uncomment the test creation block, and not also add the missing import each time.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/874)
> Bug 1062995 - Fix test creation in test_log_view_artifact_builder.py

- ui/partials/main/thWatchedRepoNavPanel.html
This tweak fixes Bugzilla bug [1195381](https://bugzilla.mozilla.org/show_bug.cgi?id=1195381).
This provides an ID for the unclassified failure count, so the webqa team can reliably access its value and ensure a failure exists in the DOM before a test proceeds.
Nightly **43.0a1 (2015-08-16)**
Chrome Latest Release **44.0.2403.155 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/877)
> Bug 1195381 - Provide an unclassified count ID for webqa testing

- ui/partials/main/jobs.html
- ui/partials/main/thActionButton.html
- ui/partials/main/thFilterCheckbox.html
- ui/partials/main/thFilterPanel.html
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thInfraMenu.html
- ui/partials/main/thLogoutMenu.html
- ui/partials/main/thMultiSelect.html
- ui/partials/main/thPinboardPanel.html
- ui/partials/main/thPinnedJob.html
- ui/partials/main/thRelatedBugQueued.html
- ui/partials/main/thRelatedBugSaved.html
- ui/partials/main/thRepoMenuItem.html
- ui/partials/main/thResultCounts.html
- ui/partials/main/thSettingsPanel.html
- ui/partials/main/thSheriffPanel.html
- ui/partials/main/thWatchedRepo.html
- ui/partials/main/thWatchedRepoInfoDropDown.html
- ui/partials/main/thWatchedRepoNavPanel.html
This work fixes Bugzilla bug [1195493](https://bugzilla.mozilla.org/show_bug.cgi?id=1195493).
This converts all 4 space indent in partials/main to 2 space, and while there
* tidies up of long/wrapping lines to 80-100 chars
* consistently orders attributes in a few conspicuous cases
* removes dead closing tags
* adds a few more section comments for clarity
I need to do some blink testing of the affected areas comparing stage vs. this branch, and after that I think will be ready for merge.
Nightly **43.0a1 (2015-08-18)**
Chrome Latest Release **44.0.2403.155 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/880)
> Bug 1195493 - Convert partials/main to 2 space indent

- ui/index.html
- ui/logviewer.html
- ui/perf.html
The parameter after "build:" is the block type, which is normally 'js', 'css' or a custom type. If we use a non-existent custom type (such as "dontbuild"), grunt-usemin will just exclude the block, which is just what we need to exclude this development-only file from the generated assets used on stage/production.
See:
https://github.com/yeoman/grunt-usemin#blocks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/882)
> Bug 1147676 - Exclude local.conf.js from grunt build to avoid 404s

- ui/css/treeherder.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/885)
> Bug 1195886 - Remove unused .revision-button CSS class

- ui/partials/logviewer/lvLogSteps.html
This fixes Bugzilla bug [1179337](https://bugzilla.mozilla.org/show_bug.cgi?id=1179337).
World's shortest PR :)
Currently we suppress successful steps by default via `ng-if`. But in that condition the available `order=(n)` step attributes in the DOM is incomplete, and when selecting a step (the colored button boundary) we get the console error:
`TypeError: el.offset(...) is undefined`
That related `getOffsetOfStep()` stuff is handled [here](https://github.com/mozilla/treeherder/blob/01beccbedafc9490da212cabb4bfc264065f7fe3/ui/js/directives/treeherder/log_viewer_lines.js#L26-L36).
It seems the simplest solution is to ensure the step count is always correct, by switching from `ng-if` to `ng-show`, so all steps are always available in the DOM, not just when showSuccessful() is true. …
> Bug 1179337 - Quiet logviewer error on first-click of a failure-step

- ui/logviewer.html
This tweak fixes Bugzilla bug [1189498](https://bugzilla.mozilla.org/show_bug.cgi?id=1189498).
This provides a fallback for the job details artifact property `content_type`, when it is neither **link** or **raw_html**.
Current (missing when **text**):
Proposed:
We plan to consolidate the logviewer and treeherder partials if possible, in a separate fix.
Nightly **43.0a1 (2015-08-18)**
Chrome Latest Release **44.0.2403.155 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/887)
> Bug 1189498 - Provide a text value fallback for logviewer job details

- requirements/common.txt
- ui/js/directives/treeherder/persona.js
- ui/js/models/user.js
- ui/js/services/main.js
The latest version of django-browserid removes a view that we used to fetch to retrieve
basig config params for the browserid client initialization. We now have loginUrl and logoutUrl
hardcoded in the client and we fetch the user login status from a dedicated endpoint.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/890)
> Bug 1159167 - Update to latest django-browserid

- ui/index.html
- ui/js/controllers/machines.js
- ui/js/controllers/timeline.js
- ui/js/treeherder_app.js
- ui/partials/main/machines.html
- ui/partials/main/timeline.html
This tweak fixes Bugzilla bug [1197265](https://bugzilla.mozilla.org/show_bug.cgi?id=1197265).
This removes the remaining front end code for the 'timeline' and 'machines' tabs removed last year in bug [1032470](https://bugzilla.mozilla.org/show_bug.cgi?id=1032470). The back end code will still remain for data ingestion.
I ingested and ran the UI with a local vagrant and both browser consoles seem fine.
Nightly **43.0a1 (2015-08-20)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/896)
> Bug 1197265 - Remove frontend code for 'timeline' and 'machines'

- ui/js/controllers/logviewer.js
- ui/logviewer.html
This fixes Bugzilla bug [1193222](https://bugzilla.mozilla.org/show_bug.cgi?id=1193222)
This provides a suitable display state when a job and/or its related logviewer url is not available the job has been expired.
Current:
Proposed (with tooltip if the user had closed the notification, same as our log not available):
Nightly **43.0a1 (2015-08-20)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/895)
> Bug 1193222 - Handle invalid logviewer jobs in the UI

- .slugignore
https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore
This reduces slug size from 68.5MB to 52.6MB.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/904)
> Bug 1198053 - Add a .slugignore file to reduce Heroku slug size

- tests/etl/test_buildapi.py
- tests/etl/test_pushlog.py
- tests/sample_data/hg_pushlog.json
- treeherder/etl/common.py
- treeherder/etl/management/commands/ingest_push.py
- treeherder/etl/pushlog.py
- treeherder/etl/tasks/buildapi_tasks.py
- treeherder/etl/tasks/cleanup_tasks.py
This fixes [Bug 1076826](https://bugzilla.mozilla.org/show_bug.cgi?id=1076826)
This moves us to using ``version=2`` with our calls to json-pushes to fetch ``resultsets`` from Mercurial.  In doing this, we can call to the server more often than once perminute.  GPS says every 15 seconds is fine.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/881)
> Json-pushes version 2

- ui/js/controllers/jobs.js
- ui/partials/main/jobs.html
This first pull request is not working properly.
When the link http://local.treeherder.mozilla.org/index.html#/jobs?repo=mozilla-inbound&revision=%s
is clicked, it is redirected to 
http://local.treeherder.mozilla.org/index.html#/jobs?repo=mozilla-inbound&revision=undefined
without any error alert.
However, when the link
http://local.treeherder.mozilla.org/index.html#/jobs?repo=mozilla-inbound&revision=undefined
is clicked. An error is showed.
Besides, the error messages are not completely right.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/830)
> Bug 1046229 - Handle invalid values for 'revision' in the URL (eg "%s")

- ui/js/directives/treeherder/clonejobs.js
- ui/js/models/resultsets_store.js
- ui/js/providers.js
The issue with this bug was grouping, as it turns out.  ``resultset_store`` was grouping jobs by their ``name`` and ``symbol``.  However, we had the same ``symbol`` with two different names (one from Task Cluster, one from Buildbot).  In this case, it was the ``?`` group which shows as not within any group.
Since the name from each source was different, we had 2 groups both with the symbol of ``?``.  We would render the first one, then see another group named ``?`` and empty the first one, and add the new jobs.  
What I've done is to fix both parts of that.  
1. We group in ``resultset_store`` by *only* the group symbol to prevent conflicts there.  
2. But if we DO, by magic, get two groups with the same symbol, then ``clonejobs.js`` can handle that.  The fix for this is actually an …
> Bug 1197827 - Treeherder unclassified failure count is off

- ui/js/controllers/logviewer.js
This fixes Bugzilla bug [1192199](https://bugzilla.mozilla.org/show_bug.cgi?id=1192199)
This adjusts `logFileLineCount` so it produces a correct count for the scope variable `displayedLogLines`. The array was clipped and the last line omitted in Logviewer.
Current (misses the last line, it should be 'Finished'):
Proposed:
There were two unused variables in `loadMore` so I removed them at the same time. Everything seems find in local testing with:
* logviewer failure step preload
* step button navigation
* step failure line navigation
* freeform mouse/wheel/slider navigation
* show successful steps (enabling, disabling) with navigation
I might do a bit more testing before merge.
Nightly **43.0a1 (2015-08-20)**
Adding …
> Bug 1192199 - Return a correct line count for logviewer navigation

- ui/partials/main/jobs.html
This is a supplementary fix for Bugzilla bug [1046229](https://bugzilla.mozilla.org/show_bug.cgi?id=1046229).
This fixes the console errors resulting from the invalid operator.
`"Error: [$parse:syntax] Syntax Error: Token '=' not a primary expression at column 13 of the expression [revision !=== 'undefined'] starting at [= 'undefined'].`
Nightly **43.0a1 (2015-08-24)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/907)
> Bug 1046229 - Fix operator for invalid revison url param

- .gitignore
- deployment/update/update.py
Since WhiteNoise won't serve files from /media/, so the existing file in `treeherder/webapp/media/` 404s when accessed via:
https://treeherder.{mozilla,allizom}.org/media/revision
IMO the site root makes more sense for this file anyway, so let's just save it under `dist/`. Also adds a .txt extension for clarity.
The old file has been left for now to ease the transition, and will be deleted once the IRC pushbots config and What's Deployed URLs have been updated.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/908)
> Bug 1198452 - Save the deployed revision to <site-root>/revision.txt

- Gruntfile.js
This fixes Bugzilla bug [1198507](https://bugzilla.mozilla.org/show_bug.cgi?id=1198507).
This provides a minified thNotificationsBox.html for Logviewer. Previously stage and prod were serving some unminified assets prior to Whitenoise which until we switched, masked the problem.
With a local grunt build, and running gunicorn with `SERVE_MINIFIED_UI` it now appears to be ok:
Nightly **43.0a1 (2015-08-25)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/915)
> Bug 1198507 - Provide a minified notifications partial for Logviewer

- deployment/update/update.py
Once the IRC pushbot configs/What's Deployed links have been updated to use the new revision.txt file location, we can stop creating the file in the old location.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/912)
> Bug 1198452 - Stop creating treeherder.*.org/media/revision

- .gitignore
- bin/post_compile
- deployment/update/update.py
- treeherder/settings/base.py
- treeherder/webapp/whitenoise_custom.py
**1) Make WhiteNoise serve the static assets gzipped:**
On Heroku, there is no load balancer or Varnish-like cache in front of gunicorn, so we must handle gzipping responses in the app. In order for WhiteNoise to serve gzipped static content, assets must be gzipped on disk in advance (doing so on-demand in Python would not be as performant). WhiteNoise will then serve the `.gz` version of files in preference to the original, if the client indicated it supported gzip.
For assets covered by Django's collectstatic, gzipping the assets only requires using WhiteNoise's `GzipManifestStaticFilesStorage` backend, which wraps Django's `ManifestStaticFilesStorage` to create hashed+gzipped versions of static assets:
http://whitenoise.evans.io/en/latest/django.html#add-gzip-and-caching-support
The …
> Bug 1197796 - Make WhiteNoise serve the static assets gzipped

- ui/css/logviewer.css
- ui/css/treeherder.css
- ui/help.html
- ui/js/providers.js
- ui/partials/logviewer/lvLogSteps.html
This work fixes Bugzilla bug [1192917](https://bugzilla.mozilla.org/show_bug.cgi?id=1192917).
This provides a new color treatment for unknown jobs (formerly black), and raises visibility in the UI when the log artifact has a similar result, which we see fairly frequently. We use Bootstrap [warning](http://getbootstrap.com/components/#alerts) alert colors.
Unknown jobs (mocked on running jobs, since they are relatively rare):
Unknown Logviewer step result:
And a corresponding tooltip to spell it out to the consumer:
Everything seems fine on both browsers, testing a variety of jobs, successful, failed, busted, etc.
While this job exists on stage, this is a suitable logviewer path for branch testing. But there are many other Gaia Python Integration Tests and other tests available for the …
> Bug 1192917 - Handle 'unknown' steps and jobs with improved UI

- ui/help.html
This fixes Bugzilla bug [1199341](https://bugzilla.mozilla.org/show_bug.cgi?id=1199341).
This adds a row to illustrate collapsed job counts to the Help notations table, now that bug [1163064](https://bugzilla.mozilla.org/show_bug.cgi?id=1163064) has landed. I also adjusted the classified style so it looks more like a typically classified job, the same with counts, and also removed some unused `th` classes while there.
Current:
Proposed:
Nightly **43.0a1 (2015-08-26)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/921)
> Bug 1199341 - Add job counts to the Help notations table

- treeherder/settings/base.py
The default value of 10 is currently used by stage/prod, however on Heroku it was set to 1, presumably since the guide here suggests it:
https://devcenter.heroku.com/articles/cloudamqp#celery
However, we're not using the free CloudAMQP plan mentioned by the guide, but instead use their 'Big Bunny' plan, which supports up to 5000 concurrent connections.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/918)
> Bug 1194142 - Use the default Celery BROKER_POOL_LIMIT on Heroku

- .travis.yml
- docker/etc/profile.d/treeherder.sh
- puppet/manifests/vagrant.pp
- treeherder/settings/base.py
Previously if `TREEHERDER_DJANGO_SECRET_KEY` was not set, we'd silently fall back to a default value for `SECRET_KEY`, meaning we wouldn't realise we were using an insecure key on a live deployment instance (eg like we were on Heroku until now).
With this change, `TREEHERDER_DJANGO_SECRET_KEY` being missing from the environment is fatal, resulting in:
`ImproperlyConfigured: The SECRET_KEY setting must not be empty.`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/919)
> Bug 1199179 - Remove default Django SECRET_KEY

- ui/robots.txt
Stage/prod's robots.txt is currently served by Apache, and is in the private puppet repo. Since Heroku can't use it, we need to check one into our repo, that will then be served by WhiteNoise along with the other static files.
The robots.txt file here is a direct copy of that currently at:
https://treeherder.mozilla.org/robots.txt
Once this change is deployed, we can remove the alias in the stage/prod Apache config, leaving WhiteNoise to serve this file. As an added bonus, it will also then be much easier for us to alter it in the future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/920)
> Bug 1199046 - Add an in-repo robots.txt to be served by WhiteNoise

- bin/post_compile
**1) Override the hostname reported by New Relic on Heroku:**
On Heroku, the hostname is just a bunch of hex characters, which the New Relic dashboard displays as "Dynamic Hostname". The New Relic Python agent (as of v2.52.0.40) supports overriding this, by setting the environment variable `NEW_RELIC_PROCESS_HOST_DISPLAY_NAME`:
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-configuration#process_host-display_name
We use the value of `DYNO`, since this is set for us in each dyno's environment, and is of form "web.2", "worker_pushlog.1" etc. Rather than prefixing every line in the Procfile, we instead append the export to the profile script created by the Python buildpack, so it's populated at runtime on every dyno. See: …
> Bug 1176412 - Override the hostname reported by New Relic on Heroku

- Gruntfile.js
- ui/css/treeherder.css
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thHelpMenu.html
- ui/userguide.html
This fixes the UI side of Bugzilla bug [1199078](https://bugzilla.mozilla.org/show_bug.cgi?id=1199078).
This adds a drop down menu for the Help icon for access to feature development news, and provides a variety of other useful entries for new/experienced users. The actual URL of the feed for Treeherder development news is still tbd. Presently it just points to the ATeam blog.
Current (no menu):
Proposed (dropdown added):
Proposed (dropdown open):
I'm actually inclined to just call the 2nd entry "Developer Guide". I also left WhatsDeployed in the UserGuide footer, since users have experience with it being there, and I don't think it does harm to have it in two places.
The notable mappings are:
* User Guide (formerly help.html)
* Development Documentation (readthedocs)
* Development News …
> Bug 1199078 - Add Help menu and useful menu entries

- ui/css/logviewer.css
- ui/js/controllers/logviewer.js
- ui/partials/logviewer/lvLogSteps.html
This fixes Bugzilla bug [1199659](https://bugzilla.mozilla.org/show_bug.cgi?id=1199659).
This returns the previous behavior of unstyled Taskcluster steps in Logviewer. They were styled yellow in bug [1192917](https://bugzilla.mozilla.org/show_bug.cgi?id=1192917).
I tried returning the behavior just with angular markup in this partial (since we now need to preserve the yellow styling for Unknown jobs in Treeherder job tables), but it became unwieldy looking. So I went with a stopgap method in the controller, if/until later on Taskcluster produces their own logs or more compliant ones where `step.result: unknown` has real meaning and should be flagged.
Current  (landed yesterday):
Proposed (same as what we had):
This means that part of the intent of bug …
> Bug 1199659 - Remove 'unknown step result' step styling in Logviewer

- ui/css/logviewer.css
This fixes Bugzilla bug [1201235](https://bugzilla.mozilla.org/show_bug.cgi?id=1201235).
This change preserves white space on loaded log lines in Logviewer, so various text blocks are more readable.
Before:
Proposed:
And another example showing the benefit:
In some cases we consume more horizontal space and in other cases we save space. We are faithful to the logs produced upstream, which seems reasonable.
Historical note: back in May @wlach made [this change](https://github.com/mozilla/treeherder/commit/afc3d2f5011f629e853991f5358b33381b763e4c) in [bug 1163083](https://bugzilla.mozilla.org/show_bug.cgi?id=1163083) and we were going to trim extraneous white space off the end of lines, but we ended up not doing so.
Nightly **43.0a1 (2015-09-01)**
Chrome Latest …
> Bug 1201235 - Preserve white space in Logviewer loglines

- ui/css/treeherder.css
- ui/partials/main/persona_buttons.html
- ui/partials/main/thGlobalTopNavPanel.html
This fixes Bugzilla bug [1199770](https://bugzilla.mozilla.org/show_bug.cgi?id=1199770).
This cleans up the right hand navbar menu buttons so we use the least amount of custom classes, stop abusing `.repo` classes for other buttons, and preserve the same computed dimensions for all.
There's no before/after since the UI is essentially the same:
Release **40.0.3**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/929)
> Bug 1199770 - Clean up navbar menu button classes

- ui/js/directives/treeherder/clonejobs.js
This hopefully fixes Bugzilla bug [1199139](https://bugzilla.mozilla.org/show_bug.cgi?id=1199139).
This prevents accidental job count group collapse, when clicking in between jobs in an expanded job group.
The -ve right hand margins we used appeared to be allowing the element "behind" to be selected which triggers the collapse. So for the fix, we use -ve *left* hand margins (and compensate in a variety of places) and retain the same spacing and white space as before.
Maybe there's a better way of doing it, but it seems to be fine. There are a lot of layout inter-dependencies now, so touching one thing, means you have to compensate in one or several other places.
View of the job element post-fix (looks essentially the same):
So when we hover over the "right hand" side of the green button …
> Bug 1199139 - Prevent accidental job count group collapse

- ui/css/treeherder.css
- ui/partials/main/thPinboardPanel.html
- ui/partials/main/thSheriffPanel.html
- ui/plugins/annotations/main.html
This work fixes Bugzilla bug [1193951](https://bugzilla.mozilla.org/show_bug.cgi?id=1193951).
This addresses the UX issues described in the bug, and goes a ways further by generally improving the layout of the Sheriff panel, specifically:
* the "Set default", "Edit", and the destructive "Delete" action are now separated from each other
* extra UI has been removed (buttons, panels) and other de-cluttering to maximize space
* `title`'s have been added for all actions
* we use Bootstrap tabs for simplicity
* profile entries are separated by visible white space for readability
* profile entries are no longer split in half on new lines
* other alignment improvements
* wordsmithing
Here's current:
Proposed:
To edit a profile you just click on the name:
To change the default you just click on a …
> Bug 1193951 - Improve the layout of the Sheriff panel

- ui/js/compareperf.js
- ui/js/perf.js
- ui/js/perfapp.js
You can force display by adding &showExcludedPlatforms=1 to your URL
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/937)
>  	Bug 1201615 - Exclude macosx 10.10 from compareperf by default

- bin/post_compile
- deployment/update/update.py
- ui/partials/main/thHelpMenu.html
- ui/userguide.html
The Git SHA is available in the SOURCE_VERSION environment variable:
https://devcenter.heroku.com/articles/buildpack-api#bin-compile-summary
Also update the What's Deployed links to include Heroku in the comparison alongside stage/prod.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/942)
> Bug 1201517 - Export a revision.txt containing the Git SHA on Heroku too

- ui/css/logviewer.css
- ui/css/treeherder-navbar.css
- ui/css/treeherder.css
- ui/index.html
- ui/js/directives/treeherder/top_nav_bar.js
This fixes part2 of Bugzilla bug [1193804](https://bugzilla.mozilla.org/show_bug.cgi?id=1193804).
This splits up the css for the navbar into a separate file, `treeherder-navbar.css`. The Logviewer relied on one class in treeherder.css so I replicated it in Logviewer rather than adding a dependency on the larger file.
The appearance of the navbar and related menus / panels, Logviewer, and Perfherder, should be unchanged:
I did a bunch of other cleanup, and removed unused classes.
Release **43.0a1 (2015-09-06)**
Chrome Latest Release **45.0.2454.85 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/945)
> Bug 1193804 - Break up treeherder.css - navbar.css

- ui/css/treeherder-userguide.css
- ui/css/treeherder.css
- ui/userguide.html
This fixes Bugzilla bug [1202476](https://bugzilla.mozilla.org/show_bug.cgi?id=1202476).
This moves remaining help aka. userguide css from treeherder.css to userguide.css, consolidates the naming of `.help-` to `.ug-`, converts all of userguide.html to 2-space indent, and makes a few small fixes along the way.
Post change we have the same layout as before except the lower two Builds and Tests panels are correct children of the the main panel body div, so they are now as wide as they should be (like the Notation and Shortcuts panels).
Proposed (unchanged):
And yes, we still have open bug [1053203](https://bugzilla.mozilla.org/show_bug.cgi?id=1053203) for dealing with the lengthy Builds/Tests tables and moving them to some more appropriate place, eg. readthedocs, or elsewhere.
Tested on OSX …
> Bug 1202476 - Move remaining userguide css, naming and indent

- treeherder/settings/base.py
Removes settings that are identical to the Django 1.8 defaults:
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-ADMINS
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MANAGERS
https://docs.djangoproject.com/en/1.8/ref/settings/#language-code
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-USE_TZ
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-STATICFILES_DIRS
https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-STATICFILES_FINDERS
https://docs.djangoproject.com/en/1.8/ref/settings/#test-runner
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/952)
> Bug 1203165 - Remove settings that are identical to the Django defaults

- ui/css/treeherder.css
- ui/partials/main/thFilterPanel.html
This fixes Bugzilla bug [1201989](https://bugzilla.mozilla.org/show_bug.cgi?id=1201989)
This reduces the font sizes (14px to 12px) in the Sheriff and Filter panels. Some minor tweaks to improve the alignment checkboxes, although I anticipating those tweaks being replaced in [1202003](https://bugzilla.mozilla.org/show_bug.cgi?id=1202003).
Current (Sheriff):
Proposed:
Current (Filter):
Proposed:
At some browser widths like above, it will also delay initial container flow.
Release **43.0a1 (2015-09-07)**
Chrome Latest Release **45.0.2454.85 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/949)
> Bug 1201989 - Reduce space consumption in Sheriff/Filter panels

- ui/css/treeherder.css
- ui/partials/main/thSheriffPanel.html
This fixes Bugzilla bug [1203255](https://bugzilla.mozilla.org/show_bug.cgi?id=1203255).
This prevents the Add exclusion and Add profile buttons get a bit clipped at the bottom of the Sheriff panel, particularly at narrower browser widths. @camd feel free to let me know if you think there's a better way to do this. I kept thinking it should have been simpler.
I suppose I also could have wrapped this change into [PR949](https://github.com/mozilla/treeherder/pull/949) but I'll rebase this PR on top of that one when it is merged.
Here's before (note the blue 'Add exclusion' button):
Proposed (a uniform 10px border bottom for all elements that reach the bottom of the panel):
This now includes the Add/Update dialogues:
Everything seems fine in local testing, web-server (for viewing real …
> Bug 1203255 - Keep sheriff 'Add' buttons well spaced

- ui/partials/main/thActionButton.html
- ui/partials/main/thPinboardPanel.html
- ui/partials/main/thWatchedRepoInfoDropDown.html
This tweak fixes Bugzilla bug [1200025](https://bugzilla.mozilla.org/show_bug.cgi?id=1200025).
This makes some minor tweaks for our current menu presentation logic:
* Title Case for the main navbar menus
* Modified title Case or Sentence case, for small supplementary menus as applicable
Here's the changes and their new appearance:
Main navbar - Tree Status, Pushlog, Clobberer:
Supplementary menu - Pinboard - Save menu
Supplementary menu - Resultset bar - Revision URL list
I had tried full Title Case for the pinboard Save menu, and to be honest it did seem a bit overwhelming graphically. If folks feel strongly I can make it full Title Case though.
Revision URL list - is also going to disappear soon anyway, with @KWierso's open PR https://github.com/mozilla/treeherder/pull/677 to retire it. …
> Bug 1200025 - selected Title Case for supplementary menus

- treeherder/log_parser/management/commands/store_error_summary.py
This should prevent occurences of IntegrityError happening when something goes wrong
on first insertion and the task is retried.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/966)
> Bug 1205049 - make FailureLine bulk creation atomic

- ui/js/graphs.js
When we had two series with the same signature on different branches, we
would incorrectly highlight two points on the same graph instead of
highlighting the relevant revisions on each. This used to work because
we associated a branch with each series signature, so could identify
them uniquely before, but we don't do this any more. Fortunately the fix here
is simple: just use the previously defined series instead of trying to
look it up all over again.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/970)
>  	Bug 1205412 - Fix highlighting of revisions in perf graphs

- ui/css/treeherder.css
- ui/partials/main/thJobDetailsRetriggerMenu.html
- ui/plugins/pluginpanel.html
This work fixes Bugzilla bug [1187394](https://bugzilla.mozilla.org/show_bug.cgi?id=1187394)
This moves the blue "**Backfill this job**" text link in the bottom of the job details pane, into a unified menu in the job details actionbar.
Current (see bottom left):
Proposed (see retrigger icon in the actionbar, with added dropdown menu arrow):
Proposed (posted menu):
To facilitate this we needed to remove two overflow hidden properties, so the bootstrap menu could post below the actionbar and not be obscured underneath the job details pane container. The net of this, is we have a fixed minimum size for the job details pane and the job tabs containers, and they don't collapse down as they did prior. That being said, as super narrow widths it's questionable how useful that was anyway. @KWierso …
> Bug 1187394 - Move backfill ui to Job details actionbar

- ui/css/treeherder-navbar-panels.css
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thSheriffPanel.html
This work fixes Bugzilla bug [1117556](https://bugzilla.mozilla.org/show_bug.cgi?id=1117556).
This provides a read-only version of the Sheriff panel for non-staff users. A few points:
* navbar menu access is now `.loggedin` as the UX seems to make sense
* so you get a staged menu experience
* suppressed when not logged in, visible read-only when logged in, editable when staff
* all former spans and anchors have been switched to buttons to facilitate `ng-disable`
* those buttons are styled so the UI will appear unchanged
* we do lose underlining on clickable names during hover, but we plan to hover `fa-pencil` later
* Add/Update panels remain unchanged since their access is prevented via the disabled Add buttons
PR Testing:
If you have the ability to push a branch to stage and modify your …
> Bug 1117556 - Add read only sheriff panel for non-staff

- ui/js/graphs.js
- ui/js/perfapp.js
… graphs
Before we would persist the name of the series when navigating to (e.g.)
compare. Let's fix this in a robust way.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/976)
>  	Bug 1206118 - Fix document title when navigating away from perfherder graphs

- Gruntfile.js
- package.json
**1) Separate grunt build npm packages from those for testing**
To run grunt build as part of deploy, we're going to need to npm install the dependencies required for it. However we do not need to install the testing related packages, so by splitting the two between `dependencies` and `devDependencies` we'll have more control. eg: `npm install --production` will only install those under `dependencies`.
See:
https://docs.npmjs.com/files/package.json#dependencies
https://docs.npmjs.com/files/package.json#devdependencies
https://docs.npmjs.com/misc/config#production
**2) Remove unnecessary loadNpmTasks() calls**
Since they're duplicating what the `require('load-grunt-tasks')(grunt)` call is already doing. See:
https://github.com/sindresorhus/load-grunt-tasks/blob/master/readme.md
**3) Add …
> Bug 1206108 - Split up devDependencies packages into those for testing vs `grunt build`

- ui/css/treeherder-job-buttons.css
* Selecting a job (scale up from standard size)
* Expanding a job group (fade in)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/980)
>  	Bug 1206160 - Add some fast transitions for basic treeherder actions

- bin/run_celery_worker
- tests/autoclassify/test_classify_failures.py
- tests/autoclassify/test_detect_intermittents.py
- tests/autoclassify/utils.py
- tests/conftest.py
- tests/jobs_test.json
- treeherder/autoclassify/detectors.py
- treeherder/autoclassify/management/commands/autoclassify.py
- treeherder/autoclassify/management/commands/detect_intermittents.py
- treeherder/autoclassify/management/commands/matchers.py
- treeherder/autoclassify/matchers.py
- treeherder/autoclassify/tasks.py
- treeherder/log_parser/tasks.py
- treeherder/model/derived/jobs.py
- treeherder/model/models.py
- treeherder/model/sql/jobs.json
- treeherder/settings/base.py
This adds an autostar command and a detect_intermittents command.  The
former is designed to take an incoming job with an error summary and
look for existing results marked as intermittent that are a close
match for the new result. At present only two matchers are
implemented; one that requires an exact match in terms of tests, and
one that requires an exact match in terms of logs. Matching is also
constrained to be based on single lines; it is anticipated that future
iterations may add support for matching on groups of lines.
The detect_intermittents command is designed to take a group of jobs
running on the same push and with the same build job (i.e. same
testsuite, same chunk, etc.) and look for new intermittents to add to
the database. This currently only looks for test failures where …
> First cut at autostar / intermittent orange detection.

- ui/css/treeherder-job-buttons.css
We were applying the "pointer" style, which implied you could select
something when you couldn't before. We should only use that style when
hovering over the job buttons themselves.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/993)
>  	Bug 1207237 - Fix cursor when hovering over non-selectable job group

- treeherder/model/fixtures/repository.json
Deactivates:
* ux
* fig
* mozilla-esr31
* comm-esr31
* mozilla-b2g34_v2_1s
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/990)
> Bug 1206196 - Deactivate some obsolete repositories

- ui/css/treeherder-info-panel.css
This fixes Bugzilla bug [1207163](https://bugzilla.mozilla.org/show_bug.cgi?id=1207163).
This increases the min-width of our `job-tabs-panel` to support the 5th *Talos* tab when present and prevent wrapping of the Pinboard^ and Talos content at narrow browser sizes.
Nightly/Release wanted 622, Chrome wanted 623, so we'll play it safe and go with 625 in case someone adds a vertical somewhere.
If the user narrows it further, it just progressively obscures the [x] and Pinboard^ buttons, the same as current master in a 4 tab non-Talos job. But as a side effect it means for non-Talos jobs we aren't as narrow as we could be.
Before:
After:
Release **43.0a1 (2015-09-21)**
Adding …
> Bug 1207163 - Increase min-width to accommodate Talos tab

- ui/plugins/failure_summary/main.html
Rather than just the summary text. Also removes the redundant bug summary from the title (since it matches the link text) - which means that there is no tooltip to show for bug suggestions unless the bugs are resolved.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/994)
> Bug 1192407 - Make bug suggestion tooltips show for the whole link

- requirements/common.txt
- treeherder/settings/base.py
These are the settings (which can be overridden by environment variables)
that will be used to specify which Pulse exchanges we ingest data from
This also introduces the ``django-environ`` package which will be used
elsewhere as we move away from ``local.py`` files on the stage/prod
servers.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/977)
> Bug 1205888 - Adds base settings for pulse exchange ingestion

- tests/jobs_test.json
- tests/model/derived/conftest.py
- tests/test_utils.py
- tests/ui/mock/resultset_list.json
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
- treeherder/model/sql/template_schema/project.sql.tmpl
It's unused in the UI and doesn't add any value, since we're normally much more interested in the push_timestamp.
This can land without causing errors, since the field is DEFAULT NULL, so can be dropped at our leisure later.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/992)
> Bug 1202626 - Stop storing each revision's commit_timestamp

- ui/css/treeherder-info-panel.css
This fixes Bugzilla bug [1207197](https://bugzilla.mozilla.org/show_bug.cgi?id=1207197).
This adds a pointer cursor for any existing or future dropdowns that will exist in the info-panel. I chose not to brute force apply it everywhere, since the main navbar (Infra, Repo, Help) is already inheriting its pointer property correctly via some other bootstrap mojo.
So retrigger/backfill is the only info-panel dropdown at present that receives the change.
Release **43.0a1 (2015-09-21)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/991)
> Bug 1207197 - Add a cursor property for the Retrigger dropdown

- ui/css/treeherder-info-panel.css
This fixes Bugzilla bug [1206825](https://bugzilla.mozilla.org/show_bug.cgi?id=1206825).
This `!important` rule is still required after the commented bug was fixed, so we're removing the referencing comment here.
Release **44.0a1 (2015-09-22)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/999)
> Bug 1206825 - Remove obsolete comment for div.talos-panel

- ui/css/treeherder-info-panel.css
- ui/plugins/pluginpanel.html
This fixes Bugzilla bug [1207304](https://bugzilla.mozilla.org/show_bug.cgi?id=1207304).
This adjusts the button wrap-preventing `min-width` of the job-tabs-panel, so that we optimize for Talos and non-Talos jobs. If you select a non-Talos, you can reduce the size of the browser further, while still having view of the Pinboard^ and [x] close icon.
What we'd like to optimize for (non-Talos job, see lower right):
Proposed (non-Talos job):
And Talos job selection is unchanged from master (wider, 625px):
Release **44.0a1 (2015-09-22)** …
> Bug 1207304 - Dynamically set the min-width for job-tabs-panel

- puppet/manifests/vagrant.pp
Without this line, ``local.py`` will get overwritten every time ``vagrant provision`` is executed. But some folks mike LIKE their ``local.py`` file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/998)
> Bug 1207403 - don't replace existing local.py on vagrant

- Vagrantfile
It seems like 1G is too little for mysql as it is currently configured,
bumping the default memory on the Vagrant instance is an easy way of
addressing this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1003)
>  	Bug 1207816 - Bump default vagrant memory to 2G from 1G

- ui/partials/main/thHelpMenu.html
- ui/userguide.html
It currently doesn't do anything useful. Commenting it out instead of eliminating
it just in case someone wants to bring it back.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1004)
>  	Bug 1208086 - Hide links to whatsdeployed

- ui/css/treeherder-resultsets.css
- ui/css/treeherder.css
- ui/index.html
This fixes part 7 of Bugzilla bug [1193804](https://bugzilla.mozilla.org/show_bug.cgi?id=1193804).
This splits up the css for the Resultset UI (resultset bar, revisions, job table) into a separate file, `treeherder-resultsets.css`.
I did a bunch of other cleanup, removed unused classes, converted to 2 space indent, and commented and re-ordered the entries so they were easier to find. The appearance of a Resultset bar, the Revision column, Resultset button controls, and the underlying push containers should be unchanged:
Everything seems fine and matches in blink testing between my local branch and stage.
Release **44.0a1 (2015-09-22)**
[<img src="https://reviewable.io/review_button.png" …
> Bug 1193804 - Break up treeherder.css - resultsets.css

- ui/plugins/pluginpanel.html
This fixes Bugzilla bug [1207771](https://bugzilla.mozilla.org/show_bug.cgi?id=1207771).
This disables the info-panel Cancel button unless the user is logged in.
I had disabled the ng-click also via `ng-click="!user.loggedin || cancelJob()"` but decided to allow it and continue to put up the identical pink thNotify *"Must be logged in to cancel a job"* message in that condition.
We still want that thNotify message in the code also, in the event we adopt a shortcut or other means of cancelling.
Proposed:
Release **44.0a1 (2015-09-24)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1006)
> Bug 1207771 - Disable Cancel job button when not logged in

- tests/ui/config/karma.conf.js
- ui/css/treeherder-global.css
- ui/index.html
- ui/js/controllers/main.js
- ui/js/controllers/userguide.js
- ui/js/userguide.js
- ui/partials/main/thShortcutTable.html
- ui/userguide.html
This work fixes part1 of Bugzilla bug [1141569](https://bugzilla.mozilla.org/show_bug.cgi?id=1141569).
This provides an onscreen help for keyboard shortcuts.
**Note**: I anticipate we'd ultimately add this F1 entry below to the shortcut list, once we have part2 of the bug (an inline Help for all UI elements) done, and perhaps emphasize it with `btn-primary` in the onscreen version, versus the UserGuide version:
But that's for later, for now we'll just display the existing shortcuts. So here's the current PR.
Proposed ('?' key depressed, click [x] to close like Github):
I decided to keep the two shortcut tables (here, and UserGuide.html) separate since they get different stylings, and I want to add the shortcut `?` to the UserGuide, but it isn't necessary in the onscreen version. I don't …
> Bug 1141569 - Display onscreen keyboard shortcuts

- treeherder/etl/classification_mirroring.py
Since `.fromtimestamp()` is being overridden by Django's TIME_ZONE and so uses Pacific Time, even though rabbitmq's server time is UTC.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1013)
> Bug 1208102 - Submit the job start time date as UTC to ElasticSearch

- ui/js/directives/treeherder/log_viewer_infinite_scroll.js
- ui/js/directives/treeherder/log_viewer_lines.js
- ui/js/directives/treeherder/log_viewer_steps.js
These tweaks fix Bugzilla bug [1208486](https://bugzilla.mozilla.org/show_bug.cgi?id=1208486).
Nothing exciting just some very minor tidying up of the logviewer directives. There's no functionality change or other bug fixes, just readability and linting.
I don't have an opinion on `function(param)` vs `function (param)` but we have a mix in the codebase, and old/new jslint emphatically claims it should be `function ()`.
Everything seems fine in local testing, as expected.
Release **44.0a1 (2015-09-29)**
Chrome Latest Release **45.0.2454.101 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1017)
> Bug 1208486 - Lint and tidy up logviewer directives

- Gruntfile.js
- ui/js/userguide.js
- ui/partials/main/thShortcutTable.html
- ui/userguide.html
1) Fix parse error during grunt build …
2) Fix grunt build minification of userguide.html …
Also the s/userguide.app/userguide/ was to fix:
> Error: [$injector:nomod] Module 'userguide' is not available!
As part of my work to get grunt build running automatically on deploy, I'm going to run it on Travis to make sure we catch things like this before deploy :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1014)
> Bug 1209523 - Fix grunt build of userguide.html

- ui/partials/main/thShortcutTable.html
This tweak fixes Bugzilla bug [1209567](https://bugzilla.mozilla.org/show_bug.cgi?id=1209567).
This updates the **esc** keyboard shortcut to a more generalized description since the shortcut/overlay panel itself, is now part of what closes on 'esc'.
Release **44.0a1 (2015-09-29)**
Chrome Latest Release **45.0.2454.101 (64-bit)**
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1015)
> Bug 1209567 - Update 'esc' keyboard shortcut description

- ui/css/treeherder-global.css
- ui/css/treeherder-info-panel.css
This tweak fixes Bugzilla bug [1209079](https://bugzilla.mozilla.org/show_bug.cgi?id=1209079).
This makes all dropdowns present with a pointer cursor, even if they don't contain an `href` in the markup. I don't think we want to stick empty hrefs into the menus to fix them, since you'd get context menus to "Open this link in a new window" which don't go anywhere.
So instead we add a global property to `treeherder-global.css` which provides `pointer` for:
* Navbar > Logout
* Pinboard > Save ^
* Info Panel > Retrigger ^
Everything seems fine in local testing. Other dropdowns which *do* have an href do their own thing, and present with a pointer anyway (Treeherder > Logo menu, Logviewer > Logo menu).
Release **44.0a1 (2015-09-29)**
Chrome Latest Release **45.0.2454.101 …
> Bug 1209079 - Make all dropdowns use a pointer cursor

- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thSheriffPanel.html
This fixes Bugzilla bug [1209922](https://bugzilla.mozilla.org/show_bug.cgi?id=1209922).
This exposes the read-only Sheriff menu/panel to anyone on the web, not just users who are logged in.
Current:
Proposed (Sheriff menu available):
Proposed (Sheriff panel open):
Everything seems fine in local testing and we don't need the extra span for any child element css targeting, so it was removed. I also checked it under vagrant logging in and logging out with a django `is_staff=true` and the panel presents itself as read/write, as expected.
Release **44.0a1 (2015-09-30)**
Chrome Latest Release **45.0.2454.101 (64-bit)** …
> Bug 1209922 - Display sheriff menu for all users

- ui/js/controllers/perf/compare.js
When original repository was not the same as the new repository, we wouldn't
show new results. This commit fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1021)
> Fix bug in display of perf subtest comparison results

- .slugignore
- bin/post_compile
- package.json
1) Add grunt-cli to local dependencies list
2) Run grunt build during the Heroku deploy
See individual commit messages for more details.
Example successful Heroku build log:
https://dashboard.heroku.com/apps/treeherder-heroku/activity/builds/01fad156-3378-41a3-9e7c-e3c7567ab049
And Heroku has this branch deployed currently, which can be confirmed by testing one of the recent UI features that is not in `dist/` on master (eg pressing "?" to open the keyboard shortcuts list), on:
https://treeherder-heroku.herokuapp.com/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1022)
> Bug 1201523 - Run grunt build during the Heroku deploy

- .travis.yml
To ensure build script/parsing breakage is detected early.
It only adds 18s to the travis job, so seems like a no-brainer :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1027)
> Bug 1210546 - Run `grunt build` on Travis

- docs/data_validation.rst
- docs/index.rst
- docs/submitting_data.rst
- schemas/text-log-summary-artifact.yml
This PR was going to have endpoints to do this validation.  But based on feedback, I'm just including the raw YML file and we can point people to it so they can validate their ``text_log_summary`` artifacts, if they like.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/978)
> Bug 1205906 - Adds JSON schema YML to validate text_log_summary artifacts

- README.md
So we can more easily track out of date dependencies.
Note that since we pin our nodejs packages, the Node badges will remain green even if dependencies are out of date, due to:
https://github.com/alanshaw/david-www/issues/48
...however the badge is still useful since it's just one click to see the table.
To get the requires.io badge working a GitHub hook has to be set up, which I've already done.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1035)
> Bug 1211524 - Add readme badges for requires.io and david-dm.org

- package.json
To suppress the warning shown when using `npm install`.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1038)
> Bug 1210738 - Declare the license type in package.json

- requirements/common.txt
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1040)
> Bug 1211893 - Update oauth2 to v1.9.0.post1 and httplib2 to v0.9.2

- treeherder/model/sql/template_schema/project.sql.tmpl
Since we're not using it anywhere and if we did ever start want to handle pull requests I think the implementation would need to be different anyway.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1037)
> Bug 1211836 - Remove unused resultset.aggregate_id

- tests/model/derived/test_jobs_model.py
- treeherder/model/management/commands/cycle_data.py
- treeherder/settings/base.py
Since we'll then we able to set it via the environment, avoiding the need for local.py. Prior to this landing, stage will need `DATA_CYCLE_DAYS` to be added to the environment (in bug 1212461).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1043)
> Bug 1212447 - Rename DATA_CYCLE_INTERVAL and make it an int

- puppet/manifests/classes/dev.pp
- requirements/common.txt
- tests/conftest.py
- tests/e2e/conftest.py
- tests/e2e/test_client_job_ingestion.py
- tests/e2e/test_perf_ingestion.py
- tests/test_utils.py
- tests/webapp/api/test_artifact_api.py
- tests/webapp/api/test_auth.py
- tests/webapp/api/test_resultset_api.py
- treeherder/client/setup.py
- treeherder/client/thclient/auth.py
- treeherder/client/thclient/client.py
- treeherder/credentials/management/commands/create_credentials.py
- treeherder/etl/th_publisher.py
- treeherder/log_parser/utils.py
- treeherder/settings/base.py
- treeherder/webapp/api/job_log_url.py
I updated the etl code to use HawkAuth instead of TreeherderAuth.
I bumped up the TreeherderClient version to reflect the updated requirements.
I also sneaked in a fix for an error in the job_log_url permission_classes. 
Please note that I kept the last commit separated just for the review. I'll squash it before I merge it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1042)
> Bug 1209555 client hawk new

- deployment/update/update.py
This prevents 404s on the UI if the output from `grunt build` hasn't been committed to the repo prior to deploying to stage/prod.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1047)
> Bug 1212886 - Fail early if stage/prod grunt build forgotten

- bin/post_compile
The Python buildpack's automatic collectstatic is slower, since it does a `--dry-run` first. To avoid the time penalty of this, we disable it by setting `DISABLE_COLLECTSTATIC` in the Heroku environment, and run collectstatic manually in `bin/post_compile`. See:
https://github.com/heroku/heroku-buildpack-python/issues/252
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1050)
> Bug 1210367 - Heroku: Run collectstatic manually to speed up deploy

- treeherder/credentials/models.py
- treeherder/model/models.py
By default Django appends an 's' onto the singular model name (in addition to munging CamelCase) when generating the plural form that is used in the admin panel/elsewhere. For example:
Device -> "devices"
RepositoryGroup -> "repository groups"
For some of our model names this doesn't make sense and results in items in the admin panel like "Credentialss", "Bugscaches" or "Repositorys", so we use verbose-name-plural to explicitly set the name that should be used:
https://docs.djangoproject.com/en/1.8/ref/models/options/#verbose-name-plural
"Credentials" is valid for the singular (ie: model name), according to:
http://english.stackexchange.com/questions/252073/which-is-correct-credential-or-credentials
"ReferenceDataSignatures" should really be renamed to the singular, but for now I've just …
> Bug 1212951 - Set 'verbose-name-plural' for models that need it

- treeherder/config/settings.py
- treeherder/credentials/models.py
- treeherder/credentials/templates/credentials/base.html
- treeherder/credentials/templates/credentials/credentials_confirm_delete.html
- treeherder/credentials/templates/credentials/credentials_detail.html
- treeherder/credentials/templates/credentials/credentials_list.html
* Replace leftover references to "App ID" with "Client ID". So it's clearer to users of the credentials management pages, since "Client ID" is used everywhere else.
* Make capitalisation on credentials pages consistent.
Sets a verbose name for client_id so "ID" always appears capitalised:
https://docs.djangoproject.com/en/1.8/topics/db/models/#verbose-field-names
Also tweaks the mixed capitalisation for the page title/heading.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1055)
> Bug 1213263 - Replace leftover references to "App ID" with "Client ID"

- docs/submitting_data.rst
- tests/client/test_treeherder_client.py
- treeherder/client/thclient/client.py
Since with the new per-user Hawk credentials, the same auth object can be used for the whole session, so should just be passed when instantiating TreeherderClient.
The tests in test_treeherder_client.py need updating to use HawkAuth, but that's unrelated for now, so I'll do that in another bug/PR.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1056)
> Bug 1213847 - Deprecate passing the auth object to the client's methods

- tests/webapp/api/test_resultset_api.py
- treeherder/webapp/api/resultset.py
This will simply truncate the revision down to 12 chars, so it will work with our existing data.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1059)
> Bug 1214039 - Handle either 12 or 40 char revision hashes in resultset API

- tests/client/test_treeherder_client.py
- treeherder/client/setup.py
- treeherder/client/thclient/auth.py
- treeherder/client/thclient/client.py
- treeherder/etl/th_publisher.py
- treeherder/log_parser/utils.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1065)
> Bug 1213857 - Allow passing Hawk client_id/secret directly to the client

- runtests.sh
It shouldn't be enabled by default IMO. For better overall visibility, we should be using something like coveralls or codeclimate.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1066)
> Bug 1058531 - Don't enable pytest coverage checker in runtests.sh

- treeherder/model/derived/jobs.py
- treeherder/model/sql/template_schema/project.sql.tmpl
Adds support for storing and searching by either a 12 char or 40 char
revision
On the ``result_set`` table, these fields indicate the short and long
revisions of the top revision for that push.
On the revisions table, eventually, ``short_revision`` will replace the
``revision`` field.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1058)
> Bug 1214015 - add short_revision and long_revision fields to result_set and revision tables

- ui/js/controllers/perf/graphs.js
- ui/partials/perf/testdatachooser.html
* Preserve selected platform when switching between branches
* Automatically pick the platform of the last series when bringing up test selector
* Give an indicator that we are reloading test data when switching platforms
* Fix filtering out of selected tests
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1070)
>  	Bug 1215297 - Fix various usability issues/bugs in the graphs view

- ui/js/controllers/perf/compare.js
- ui/js/perf.js
- ui/js/perfapp.js
We can add some kind of a filtering interface later, but until that's
ready it's confusing to just not display it unless people specify
a magic flag (e10s=1).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1074)
>  	Bug 1187000 - Always show e10s data in compare view

- ui/index.html
- ui/js/directives/treeherder/main.js
This fixes Bugzilla bug [1210158](https://bugzilla.mozilla.org/show_bug.cgi?id=1210158).
This dismisses the keyboard shortcut overlay if the user clicks on the dimmed perimeter area. Previously only hitting `esc` or clicking on the [x] icon dismissed the panel.
Current (overlay visible via `?`, then click in the dimmed/grey surround region):
Proposed (overlay and shortcuts are dismissed):
Shortcut table selection, still allowed:
We add a new stop propagation directive to support the above. This allows the user to click and select the shortcut table itself without the event bubbling up and closing the panel.
Eventually, if a full onscreen/inline-help UI is built, we'd tweak it further and wrap the close action(s) eg. `setOnscreenShortcutsShowing()` in a parent function. For now it seems to …
> Bug 1210158 - Clear onscreen help overlay on click

- treeherder/webapp/api/performance_data.py
- ui/js/controllers/perf/compare.js
- ui/js/perf.js
We only need the data associated with the result sets we are comparing,
instead of a large time interval covering it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1076)
>  	Bug 1214860 - Reduce amount of data loaded in perfherder compare view

- docs/code_style.rst
- docs/submitting_data.rst
Since the old auth "TreeherderAuth" system is now deprecated.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1054)
>  	Bug 1212931 - Update the client documentation to describe hawk auth

- tests/webapp/api/test_resultset_api.py
- treeherder/webapp/api/resultset.py
Some repos have been storing 40 char revisions, though most only store
12.
But a recent change to search by only 12 chars, even if 40 passed in
broke
the ability to search when the stored length was 40.  This change will
search for both length revisions, if the 40 char is passed in.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1075)
> Bug 1215450 - single resultset view stuck when using long revision

- docs/common_tasks.rst
And also:
* Explain the process for request/approval on stage/prod
* Remove the unnecessary export_project_credentials step in the "add a new repository" section, since Treeherder's ETL no longer uses credentials.json.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1077)
> Bug 1216247 - Document how to create Hawk credentials locally

- puppet/files/treeherder/local.vagrant.py
- treeherder/config/settings.py
See individual commit messages.
After these commits, and with the typical Vagrant local settings file removed (so we can see the default settings that get used on stage/prod) [logging_tree](http://rhodesmill.org/brandon/2012/logging_tree/) shows the logging hierarchy as:
```
<--""
Level WARNING
|
o<--[/home/vagrant/venv/local/lib/python2]
|   |
|   o<--[/home/vagrant/venv/local/lib/python2.7/site-packages/environ/environ]
|       |
|       o<--"/home/vagrant/venv/local/lib/python2.7/site-packages/environ/environ.pyc"
|           Level NOTSET so inherits level WARNING
|
o<--"amqp"
|   Level NOTSET so inherits level WARNING
|
o<--"celery"
|   Level NOTSET so inherits level WARNING
|   Handler <kombu.log.NullHandler object at 0xb6b6922c>
|   |
|   o<--[celery.app]
|   |   |
|   | …
```
> Bug 1217374 - Improve logging for "Hawk authentication failed" errors on stage/prod

- .travis.yml
Stage/production/Vagrant/Heroku's RDS all use mysql 5.6, however Travis is currently running v5.5. Installing mysql 5.6 manually on the Travis container infra is currently broken:
https://github.com/travis-ci/apt-package-whitelist/issues/1206#issuecomment-149884653
To use sudo (for apt-get) we either have to fall back to the legacy non-container infra, or else use the new Trusty beta infra:
http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
http://docs.travis-ci.com/user/trusty-ci-environment/#Runtimes
The Trusty beta infra is also non-container, but at least isn't EOL. Unfortunately similar to the legacy non-container infra, it doesn't offer caching, so incurs a setup time penalty of approx 3 minutes (including the mysql 5.6 install, npm install and peep install). …
> Bug 1205316 - Travis: Use the beta Trusty infra & update to mysql 5.6

- treeherder/model/management/commands/import_reference_data.py
This shouldn't happen, but it does if there's something wrong with the
database (as is currently the case). So just print a warning instead of
throwing an exception.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1085)
>  	Bug 1217461 - Handle missing job group info in import_reference_data

- tests/autoclassify/test_classify_failures.py
- tests/autoclassify/test_detect_intermittents.py
- tests/autoclassify/utils.py
- tests/conftest.py
- treeherder/autoclassify/detectors.py
- treeherder/autoclassify/management/commands/autoclassify.py
- treeherder/autoclassify/management/commands/detect_intermittents.py
- treeherder/autoclassify/matchers.py
- treeherder/model/derived/jobs.py
- treeherder/model/fixtures/failure_classification.json
- treeherder/model/migrations/0003_auto_20151022_0245.py
- treeherder/model/models.py
- ui/css/treeherder-info-panel.css
- ui/css/treeherder-job-buttons.css
- ui/js/directives/treeherder/bottom_nav_panel.js
- ui/js/providers.js
- ui/js/services/classifications.js
This adds a new FailureClassification for autoclassified
intermittent. When a job is completely classified by the
autoclassifer, and it has the same number of structured and
unstructured error lines, it is marked as an autoclassified
intermittent.
Conversely, when there is exactly one structured and one unstructured
error line, the autoclassifier did not match the job, but has a
detector that could match the job, and the job is marked as
intermittent by a human, add a new autoclassification target
corresponding to the error line.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1051)
> Add integration between autoclassification and manual starring.

- treeherder/model/sql/template_schema/treeherder_reference_1.sql.tmpl
Since MySQL 5.6 supports full text searching, so we no longer need to use MyISAM - and Django doesn't let us mix and match engines, so we need this for bug 1193836.
The bugscache table has already been updated manually on stage/prod and Heroku; this switches it for Travis/the local Vagrant environment.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1089)
> Bug 1185901 - Convert the bugscache table from MyISAM to InnoDB

- docs/submitting_data.rst
Since if submitters' clocks are out of sync, Hawk auth will fail.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1086)
> Bug 1217496 - Docs: Mention Hawk auth requires correct system clock

- puppet/manifests/classes/dev.pp
This is a followup of 829cf22bc482937406a22f1511db7a0db53a0648
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1095)
> Bug 1193836 - use `--noinput` on migrate

- docs/common_tasks.rst
- npm-shrinkwrap.json
Whilst the packages listed in package.json are pinned to exact versions, they will have their own dependencies, which may be specified via version ranges. In order to make production/local behaviour more deterministic, these can be pinned too, using `npm shrinkwrap`. However the stock shrinkwrap command has a few deficiencies, so we're using a wrapper around it:
https://github.com/uber/npm-shrinkwrap
Using shrinkwrap for nodejs dependencies is basically the equivalent to making pip requirements files use ``==`` rather than ranges, plus listing inherited dependencies too, not just the parent packages.
Note: Only packages listed under `dependencies` will be shrinkwrapped, not those under `devDependencies`. This is because using the `--dev` option (which would also include the dev packages …
> Bug 1206381 - Add npm-shrinkwrap.json to pin grunt build dependencies

- deployment/update/update.py
Install the non-development packages listed under `dependencies` in package.json, in preparation for running grunt build during the deploy.
I've split this out of the other PR in bug 1205758, so we can at least check the dependencies all install ok, before fully switching over to running `grunt build` during the deploy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1092)
> Bug 1205758 - Run `npm install --production` during stage/prod deploy

- ui/partials/main/thActionButton.html
The old Stackato PaaS link 404s, so point at the Heroku instance's herokuapp.com domain whilst we wait for the certificate/DNS to be set up for it at bugherder.mozilla.org.
Merging without review since the updated link works locally and I'd like this to catch today's deploy, given the current link 404s.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1097)
> Bug 1219222 - Update bugherder link to point at the new Heroku instance

- ui/plugins/controller.js
Due to the comment in https://github.com/mozilla/treeherder/pull/1009/files#r40550740, I think we need fix this. It make my Travis CI build failed all the time :(
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1045)
> a trivial fix for controller.js

- ui/partials/main/thActionButton.html
The new prod domain has now been set up, so we can point directly to that rather than the herokuapp.com domain.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1098)
> Bug 1219222 - Update bugherder link to point at bugherder.mozilla.org

- .travis.yml
Time until result... (includes "hidden" non-container boot time)
Before:
* linters/JS tests: ~3.5 mins
* python tests: ~7.5 mins
* grunt build: ~8 mins
After:
* linters: 24s
* JS tests/grunt build: 55s
* python tests (main): ~4.75 mins
* python tests (e2e + log parser): ~3.5 mins
As an added bonus, failing the linters tests will now not stop all of the other tests from running.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1101)
> Bug 1219889 - Speed up the Travis run by splitting it up

- tests/etl/test_bugzilla.py
I haven't found the exact reason why the tests were failing but it must
be a test isolation problem because they were passing individually.
I debugged this issue disabling the tests backwards starting from the
first failure and I found out that test_bz_api_process was the offender.
The test itself is not doing anything wrong but the refdata fixture
used to setup the test seems to be the root cause..
I replaced the two method calls with their orm counterpart and the
problem disappeared.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1105)
> Bug 1219922 - Stop using the refdata test fixture

- requirements/common.txt
As of django-browserid v1.0.0, it no longer uses fancy_tag:
https://github.com/mozilla/django-browserid/pull/281
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1104)
> Bug 1220105 - Remove unused fancy_tag package dependency

- requirements/dev.txt
We don't currently have code coverage enabled, and whilst we want to do so, it will likely be in a form different from here (eg coveralls.io). 
The packages removed by this commit are also older releases - and the latest versions have changed their dependencies (for example cov-core is no longer a separate package). By removing them it will reduce the number of packages we have to install locally & on Travis, as well as mean fewer warnings for out of date packages from requires.io.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1103)
> Bug 1220111 - Remove unused Python coverage packages

- ui/js/models/bug_job_map.js
- ui/js/models/classification.js
- ui/js/models/job.js
We want to find a better ui for the integration between manual and
automatic classification.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1107)
> Bug 1220445 - hide automatic classification

- requirements/common.txt
The wheel archive is preferred over the standard one, so we need to update the hash associated with django-browserid.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1113)
> Bug 1221157 - Update hash for django-browserid now it has a wheel

- puppet/files/treeherder/.bash_aliases
This will empty all the per-repo databases, empty all the refdata and
then clear all the rabbitmq queues.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1118)
> Bug 1221516 - Adds command to get vagrant databases and env back to a clean state

- tests/webapp/api/test_jobs_api.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
- treeherder/webapp/api/jobs.py
- ui/js/models/job.js
- ui/plugins/similar_jobs/controller.js
- ui/plugins/similar_jobs/main.html
The job list endpoint was joining the job table and the resultset table
with the only purpose of sorting the results by push_timestamp. Sorting
by result_set_id seems to be a good enough solution and at the same time
it avoids running a poor performing join between job and resultset.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1111)
> Bug 1221064 - improve job list performance

- tests/webapp/api/test_jobs_api.py
- treeherder/webapp/api/serializers.py
This adds the matched bugs to the failure_lines endpoint for a job so that the user will be able to choose the "right" one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1120)
> Bug 1221095 - Adds autoclassification options (bugs) to failure lines endpoint

- docs/installation.rst
If the worker is not running, any `apply_async()` calls are silently thrown away, due to `ingest_push`'s use of `CELERY_ALWAYS_EAGER` and:
https://github.com/celery/celery/issues/2910
As such, running the worker after ingest_push doesn't help (since the rabbitmq queues are empty) and so if people are interested in perf/log data, then they must start the worker first instead.
James hit this today and it took several of us a while to figure out what was happening.
Ideally ingest_push would run the log parser tasks and things as well, but that's more involved (and the list of tasks is likely going to get out of date as we add things like autoclassification). …
> Bug 1221536 - Docs: Emphasise starting the worker before ingest_push

- bin/run_gunicorn
- docker/gunicorn.sh
To help prevent excessively demanding queries from having a detrimental effect on the API/DBs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1121)
> Bug 1221806 - Change the stage/prod Gunicorn timeout from 120s to 30s

- treeherder/webapp/api/exceptions.py
The treeherder custom api exception handler always converts unexpected
errors into ApiExceptions. In order to keep track of those errors in
newrelic we shouldn't do the conversion and let the default exception
handler decide what to do instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1123)
> Bug 1201086 - new relic should track exceptions

- tests/e2e/test_perf_ingestion.py
- tests/etl/test_perf_data_adapters.py
Now that bug 1193836 is fixed, this is no longer necessary.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1127)
>  	Bug 1222540 - Remove cleanup at beginning of perfherder tests

- ui/js/controllers/perf/graphs.js
This can cause unexpected behaviour if the user is clicking to select
a datapoint.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1131)
>  	Bug 1223077 - Don't zoom out on click to main graph

- ui/css/treeherder-info-panel.css
- ui/index.html
- ui/js/filters.js
- ui/js/models/failure_lines.js
- ui/js/services/main.js
- ui/plugins/auto_classification/controller.js
- ui/plugins/auto_classification/main.html
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
- ui/plugins/tabs.js
Read-Only (prototype) UI for the Auto Classify panel.  This does not have any actions, just formats the data in a read-able way.
The panel tab only shows if the query string param of ``autoclassify`` is included.
An example can be seen here:
http://camd.github.io/treeherder/ui/#/jobs?repo=mozilla-inbound&revision=f968c82a1b15&autoclassify&filter-searchStr=ba74f7346fafb5d77d937cc9f8435107e67c348c
With Classified and Unclassified lines:
Expanded stack trace:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1096)
> Bug 1220200 - Autoclassify read-only ui

- app.json
Uses Heroku's new 'Release Phase' beta to run external-resource-touching tasks (that shouldn't be run during the slug compile) in a one-off dyno that runs after the deploy. See:
https://devcenter.heroku.com/articles/release-phase?preview=1
We're using the buildpack to help populate the `.heroku/bin/release` file from the `post-release` key in app.json:
https://github.com/heroku/heroku-buildpack-postrelease/blob/master/README.md
https://github.com/heroku/heroku-buildpack-postrelease/blob/master/bin/compile
(The devcenter release phase docs page instructions haven't yet been updated to cover this buildpack).
The tasks being run are the external-resource ones from `update.py`:
https://github.com/mozilla/treeherder/blob/0ecb647f795c15604b191c5b4010956068b9fb8f/deployment/update/update.py#L79-L …
> Bug 1201455 - Heroku: Run migrate & other DB tasks after deploy

- requirements/common.txt
Gives us the fix in:
https://github.com/jeads/datasource/pull/36
https://github.com/jeads/datasource/compare/v0.9...v0.9.1
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1138)
> Bug 1182485 - Update datasource to v0.9.1 for the whitespace fix

- .travis.yml
Previously the python chunks were approx 3m55s and 2m55s respectively, since we couldn't move one of the largest running directories (etl) to the second chunk, since the tests would fail due to bug 1219922.
After this change the python chunk run times are 3m15s and 3m25s.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1139)
> Bug 1223739 - Travis: Put etl tests in the 2nd chunk to balance runtimes

- ui/js/directives/treeherder/clonejobs.js
If the same job symbol is detected within the same group, don’t collapse
them to counts.  They are almost surely retriggers and will be shown to
make intermittent failures more obvious.
before:
after:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1135)
> Bug 1197258 - Don't collapse retriggered jobs

- deployment/update/update.py
Since it should be unnecessary, and causes additional load until the cache is re-populated, since:
* the builds-{4hr,running,pending} tasks have to ingest all jobs, including those previously seen
* the pushlog task defaults back to "the last 10 pushes", which in the case of inactive repos, means extra busy work, and for active repos means we might actually miss commits (particularly if the prod push was to fix an issue that has say broken ingestion for the last X mins)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1140)
> Bug 1223384 - Stop running clear_cache on stage/prod deploy

- tests/webapp/api/test_resultset_api.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1147)
> Bug 1224551 - resultset status shouldn't include classified failures

- Procfile
- bin/run_celery_worker
- schemas/resultset-runnable-job-action-message.json
- treeherder/config/settings.py
- treeherder/etl/allthethings.py
- treeherder/etl/buildbot.py
- treeherder/etl/tasks/buildapi_tasks.py
- treeherder/model/exchanges.py
- treeherder/model/migrations/0004_add_runnable_job_table.py
- treeherder/model/models.py
- treeherder/model/tasks.py
- treeherder/webapp/api/resultset.py
- treeherder/webapp/api/runnable_jobs.py
- treeherder/webapp/api/urls.py
- ui/css/treeherder-job-buttons.css
- ui/index.html
- ui/js/controllers/jobs.js
- ui/js/directives/treeherder/clonejobs.js
- ui/js/models/resultset.js
- ui/js/models/resultsets_store.js
- ui/js/models/runnable_job.js
- ui/js/providers.js
- ui/js/services/main.js
- ui/logviewer.html
- ui/partials/main/jobs.html
- ui/partials/main/thActionButton.html
- ui/perf.html
This adds a '+' button to resultsets that allows users to trigger new buildbot jobs.
Screenshots of this in action are in: https://drive.google.com/folderview?id=0B7rHgvgC7s4ZflY4cmtSSUJjcHVqQktIMGljcE5nLW9jaWx5T21CQ3F5QllSVGtDQl9sSGM&usp=sharing
When users click on '+' TH renders every possible job. Users can then click on the jobs they want and then click on 'Trigger New Jobs' to trigger the selected jobs. This will send a pulse message that Pulse Actions will use to trigger the jobs.
Currently it takes a long time (~ 7 seconds) for the full list of possible jobs to show up, because it is downloading and processing the list of builders every time. I'm working on adding this info to the TH database by adding a table and running an ETL job to fill it.
I'm planning on dealing with …
> Bug 1194830 - Add button to trigger new buildbot jobs

- ui/css/treeherder-navbar.css
- ui/js/controllers/filters.js
- ui/js/directives/treeherder/top_nav_bar.js
- ui/js/providers.js
- ui/js/services/jobfilters.js
- ui/partials/main/thFilterChicklets.html
- ui/partials/main/thResultStatusChicklet.html
- ui/partials/main/thShortcutTable.html
- ui/partials/main/thWatchedRepoNavPanel.html
We mentioned this briefly at the work week, so I decided to take a few minutes and dust this branch off and rebase it. 
I removed the "compact mode" on/off stuff and just made it compact.  We can add that in later, if we like.  Seems like that would be good in a separate PR where we compactify/verbosinate lots of things.
This aggregates ``busted``, ``testfailed``, and ``exception`` to one chicklet called "failures".  Also
``pending`` and ``running`` are one chicklet called "in progress".
So here's what it currently looks like:
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/633)
> Bug 1045606 - make filters more discoverable

- newrelic.ini
The settings for the New Relic Python agent are defined via the following methods (later items override the earlier ones):
1. Agent defaults
2. Environment variables
3. Local agent configuration file (iff `NEW_RELIC_CONFIG_FILE` set)
4. Server-side configuration (ie via the New Relic website)
5. Per-request configuration
Some settings can only be controlled by a subset of these methods, eg the more security-sensitive ones (like whether request parameters should be recorded) must be set via [3].
In addition, once [4] is activated, *all* settings that can be set via their website will override those from 1-3, even if they are set to the empty string. As such, it's recommended to *only* use the local agent config file for settings that are unavailable on the website.
Stage/prod do currently …
> Bug 1182425 - Add a config file for the New Relic Python agent

- newrelic.ini
- requirements/common.txt
See:
https://docs.newrelic.com/docs/agents/python-agent/attributes/python-agent-attributes#requestParameters
https://docs.newrelic.com/docs/agents/python-agent/attributes/python-attribute-examples#ex_req_params
There's also a commit to update to the newest New Relic Python agent:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-258043
https://github.com/edmorley/newrelic-python-agent/commit/d0317a260172e081a28d3851af61983655253227
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1153)
> Bug 1223496 - Make New Relic capture request parameters too

- ui/js/values.js
The extra context is useful.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1150)
>  	Bug 1224740 - Show 14 days of perf data in graphs view by default

- treeherder/etl/perf.py
Instead of having two completely different paths to inserting data
into the database, we can consolidate into one if we make the (deprecated)
talos data ingestion path simply create a PERFHERDER_DATA blob.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1156)
>  	Bug 1226763 - Make talos data ingestion a simple translation layer

- .eslintrc
- ui/js/controllers/perf/graphs.js
- ui/js/models/repository.js
- ui/js/models/resultsets_store.js
- ui/js/perf.js
Disallows unnecessary semicolons:
http://eslint.org/docs/rules/no-extra-semi
I converted `_getSeriesOptions()` to a variable, to match the others in that file - let me know if you'd instead prefer to just remove the trailing semi-colon from the function instead (it appears to be unused either way).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1166)
> Bug 1227682 - Enable the ESLint no-extra-semi rule & fix infringements

- docs/common_tasks.rst
- docs/submitting_data.rst
Also:
* Remove the duplication between the two pages, by having the submitting data section not mention requesting credentials at all, and leave that to the common tasks page instead.
* Use anonymous links to avoid build warnings
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1171)
> Bug 1225597 - Docs: Make local hawk credentials section easier to find

- treeherder/model/migrations/0001_initial.py
- treeherder/model/models.py
These were present in the raw SQL used prior to bug 1193836, so should already exist on stage/prod/heroku. As such, I've added these to the initial migration to avoid errors during migrate/having to use `--fake`.
Please do double check I've transposed correctly from https://github.com/mozilla/treeherder/commit/0f3788036290146d99df76dea73edbebaa2b1aab#diff-8fb6f09f253240c1fed214aec80c1896 :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1169)
> Bug 1226651 - Add missing unique_together model constraints

- tests/test_setup.py
This test checks that `./manage.py makemigrations` was run, and the resultant migrations file committed to the repo, since the last time the Django models were updated.
Django 1.8 only supports an `exit_code` option, which unhelpfully makes the command `sys.exit(1)` if there are *no* missing migrations, when we're more interested in the opposite. As such, we have to confirm that it does exit 1 (which causes a `SystemExit` exception).
On Django master they've replaced `exit_code` with `check_changes` that inverts the check, which we should switch to once we're using a version of Django that includes that fix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1172)
> Bug 1228013 - Add a test for missing Django migrations

- treeherder/embed/urls.py
- treeherder/webapp/api/urls.py
Since the `patterns()` syntax is now deprecated:
https://docs.djangoproject.com/en/1.8/releases/1.8/#django-conf-urls-patterns
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1173)
> Bug 1228324 - Use the new style urlpatterns syntax

- ui/js/perf.js
- ui/partials/perf/comparetable.html
* Remove confidence text (low/med/high) as it implies a value judgement
on the data we aren't able to really make
* Expand the explanation of what the result means
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1164)
>  	Bug 1227635 - Update display of confidence in compare view

- Procfile
- bin/run_celery_worker
- tests/conftest.py
- tests/log_parser/test_tasks.py
- tests/model/derived/test_jobs_model.py
- treeherder/config/settings.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/calculate_durations.py
- treeherder/model/migrations/0005_add_job_duration_table.py
- treeherder/model/models.py
- treeherder/model/sql/jobs.json
- treeherder/model/sql/template_schema/project.sql.tmpl
- treeherder/model/tasks.py
In order that the UI can show ETAs for running jobs, we have to generate average job durations based on historic data. This currently happens via a periodically run `calculate_eta` task, which:
1. Looks at the last X hours of jobs for each repo and generates averages/min/max/median/... for each job signature.
2. Stores those stats in a `job_eta` table (one for each repository) using Datasource, by appending new rows every time it runs.
...then when jobs are ingested:
3. The `job_eta` table for that repository is queried for matching signatures.
4. The results are used to populate the `running_eta` field for each job inserted into the `job` table.
There are a few problems with this:
* We're appending rather than updating existing rows, such that there are now ~3-4 million rows in …
> Bug 1196764 - Rewrite handling of estimated job durations

- treeherder/client/thclient/client.py
The request body, request headers & response headers are now output with a log level of `debug` rather than `error`, to reduce verbosity of logs.
In addition, the response body has now been combined with the log line that outputs the URL, to make it easier to correlate lines in the log. The type in the `_get_json()` ("Error *submitting* data") has also been fixed, and string substitution now occurs lazily.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1180)
> Bug 1229022 - Make treeherder-client HTTPError output less verbose

- ui/js/controllers/perf/graphs.js
Hmm, I think it will become clumsiness in some degree if we highlight all datapoints at once. Maybe we could add a checkout, so user can decide if they need show all datapoints. 
Anyway, I  could address my PR if you guys think it's worth to add or just forget it :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1182)
> Bug 1229049 - Highlight all points that match the given revision

- treeherder/etl/allthethings.py
Since "W3C Web Platform Reftests" is being grouped as "W" instead
of "Wr" on production, we are getting a duplicate symbol error.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1163)
> Bug 1227552: Don't force a new job_group on fetch_allthethings

- ui/js/directives/perf/compare.js
- ui/partials/perf/comparetable.html
Hmm, the orderBy in Angularjs is deal with array or array like object, but our result in here is just a object and we need sort those key for them. So I just add a function to help us sort the result out, and actually I had add same function in last pr (https://github.com/mozilla/treeherder/pull/1160#discussion-diff-45887635R38).
But somehow the results still have same order after I remove this function. Hope it's on the right direction, or I must find another way to fix it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1185)
> Bug 1223085 - Sort filted results (further improvment for bug 1223085)

- treeherder/model/models.py
- treeherder/webapp/api/refdata.py
It doesn't handle cache invalidation/updates properly. Since the
savings are almost certainly negligible, let's just get rid of it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1184)
> Bug 1229203 - Remove etag caching from frontend views

- Procfile
- bin/run_celery_worker
- tests/etl/test_perf_data_adapters.py
- treeherder/config/settings.py
- treeherder/etl/perf.py
- treeherder/perf/tasks.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1177)
>  	Bug 1228154 - Generate new performance alerts as data is ingested

- tests/etl/test_perf_data_adapters.py
- tests/perfalert/test_create_alerts.py
- treeherder/config/settings.py
- treeherder/perf/alerts.py
Generating data for old alerts is pointless in a production environment is
pointless and resource intensive.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1189)
> Bug 1230188 - Only generate alerts for recent performance data

- ui/js/controllers/perf/compare.js
- ui/js/directives/perf/compare.js
- ui/js/perfapp.js
- ui/js/values.js
- ui/partials/perf/comparectrl.html
- ui/partials/perf/comparesubtestctrl.html
Also remove the "unreliable platforms" option, since it's no longer required.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1192)
> Bug 1230616 - Show MacOS X 10.10 by default in perf compare view

- treeherder/etl/pushlog.py
We don't ingest from Git ourselves at the moment and may never do so.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1191)
> Bug 1230601 - Remove unused GitPushlogProcess/GitPushlogTransformerMixin

- ui/js/perf.js
@wlach This is the minor change I described to you. Actually probably not need an associated bug, I just noticed that duplication while looking at the file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1196)
> remove code duplication by using _getSeriesOptions

- treeherder/config/settings.py
For probably not-so-great reasons, we seem to be hitting the limits of
what we can submit in production. Until we've addressed the root causes,
let's temporarily increase things, since the rate limiting is causing
more problems than it's solving.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1208)
> Bug 1232776 - Temporarily increase rate limit on /resultset/ endpoint

- requirements/common.txt
- tests/conftest.py
- treeherder/client/thclient/client.py
v1.0.0 has a simplified API for passing the id and key, see:
https://github.com/mozilla-services/requests-hawk#great-how-can-i-use-it
https://github.com/mozilla-services/requests-hawk/blob/master/CHANGES.txt
https://github.com/mozilla-services/requests-hawk/compare/0.2.0...1.0.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1206)
> Bug 1232654 - Update requests-hawk from v0.2.0 to v1.0.0

- requirements/common.txt
The kombu update is needed for compatibility with Python 2.7.11.
The newer celery/kombu require newer billiard and amqp.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1209)
> Bug 1232654 - Update common.txt Python packages: Part 2

- treeherder/etl/buildapi.py
- treeherder/etl/common.py
- treeherder/etl/management/commands/ingest_push.py
Fixes bug 1162947 and bug 1090289 -- but most importantly should help with bug 1232776.
See individual commits for more detail :-)
A lot of the complexity here comes from us having to look up the revisions in advance (since we loop through each dataset twice to improve performance). I wonder if when we move away from the revision hash concept, whether we can avoid that? (Since we'll already know all we need to submit to the /jobs/ endpoint directly).  Anyway topic for another bug :-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1210)
> Bug 1162947 - Refactor & improve buildapi.py's skipping of bad jobs

- ui/css/treeherder-navbar.css
- ui/js/controllers/main.js
- ui/js/directives/treeherder/top_nav_bar.js
- ui/js/services/jobfilters.js
- ui/logviewer.html
- ui/partials/main/thGlobalTopNavPanel.html
- ui/partials/main/thRepoMenuItem.html
- ui/partials/main/thWatchedRepoNavPanel.html
This changes the navbar button titled "1" to be "Tiers"  It is now a dropdown that lets you choose which tiers to show.  
The default is now to show all Tier 1 and 2 jobs and filter away Tier 3 jobs.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1213)
> Bug 1231774 - Exlude Tier3 jobs from being displayed by default

- ui/plugins/controller.js
A little holiday stocking-stuffer :) This hopefully fixes Bugzilla bug [1215324](https://bugzilla.mozilla.org/show_bug.cgi?id=1215324).
This ensures we scroll to the top in the job details pane during job selection. For example, the user had scrolled down to the bottom of the details pane on one job, then selected another job.
Scenario - viewing a build, then selecting a unit test:
Selecting the unit test - current behavior:
Selecting the unit test - proposed:
I checked the Failure Summary tab, and in similar conditions it appears to be doing the right thing already.
Release **45.0a1 (2015-12-11)**
Chrome Latest Release **47.0.2526.80 (64-bit)** …
> Bug 1215324 - Scroll job-details-pane to the top on job selection

- treeherder/client/thclient/client.py
To avoid 301 redirects during the request. This only affects client functions that are not project-specific (the others use `_get_project_uri()` instead).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1228)
> Bug 1236894 - Add missing trailing slash to python client API URLs

- requirements/common.txt
- treeherder/config/wsgi.py
Since Heroku doesn't use nginx/Apache we must perform this via wsgi middleware. We cannot use Django's HTTPS/HSTS features since they won't help with requests that were served by WhiteNoise directly (eg the site homepage).
Instead we use wsgi-sslify, as recommended by:
https://github.com/evansd/whitenoise/issues/53#issuecomment-166972824
We only enable it when IS_HEROKU is set, since stage/prod is handled by Apache, and for local development we have to use HTTP.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1221)
> Bug 1203597 - Heroku: Redirect HTTP to HTTPS and set an HSTS header

- requirements/common.txt
- tests/etl/test_pushlog.py
- tests/webapp/api/test_jobs_api.py
- tests/webapp/api/test_resultset_api.py
For rabbitmq transports specified using `amqp://`, Celery/Kombu will use librabbitmq automatically if it's available, otherwise will fall back to the pure Python (and therefore slower) amqp:
http://celery.readthedocs.org/en/latest/userguide/optimizing.html#librabbitmq
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1225)
> Bug 1169696 - Use librabbitmq with Celery/Kombu for improved performance

- package.json
socket.io released backwards incompatible API changes in a minor version update, causing failures during our ui-tests travis run. See:
https://github.com/socketio/socket.io/issues/2368
However the latest version of Karma has added support for it:
https://github.com/karma-runner/karma/issues/1782
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1232)
> Bug 1237244 - Update to karma v0.13.19 to support new socket.io API

- tests/log_parser/test_step_parser.py
- treeherder/log_parser/parsers.py
This avoids breaking the whole log parsing task (including error summary generation) if the dates are invalid (eg like in bug 1236655). Instead the UI will just display 'unknown duration'.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1233)
> Bug 1237237 - Log parser: Handle malformed step marker dates gracefully

- treeherder/config/settings.py
The Heroku router doesn't support gzipping content itself, so we have to do so in the application. WhiteNoise handles serving gzipped static content already, but this change means that content served by Django will now be compressed by Django's gzip middleware:
https://docs.djangoproject.com/en/1.8/ref/middleware/#module-django.middleware.gzip
[~/src/treeherder]$ curl -i --compress http://local.treeherder.mozilla.org/api/
HTTP/1.1 200 OK
Server: WSGIServer/0.1 Python/2.7.11
Vary: Accept, Cookie, Accept-Encoding
Content-Length: 268
Content-Type: application/json
Allow: GET, HEAD, OPTIONS
Content-Encoding: gzip
Accept-Ranges: bytes
Date: Mon, 11 Jan 2016 17:32:28 GMT
X-Varnish: 173196109
Age: 0
Via: 1.1 varnish
Connection: keep-alive
...
[<img src="https://reviewable.io/review_button.png" …
> Bug 1176489 - Use Django's GZip middleware

- ui/plugins/job_details/main.html
This hopefully fixes Bugzilla bug [1224069](https://bugzilla.mozilla.org/show_bug.cgi?id=1224069).
This removes the **TalosResult:** entry from the Job Details pane, without altering the job_details blob. This is case we use it / want to use it elsewhere in this scope, and to keep it consistent with the logviewer blob of the same name. So instead we just suppress it from the array in the markup.
Current:
Proposed:
Everything seems fine locally with both Talos jobs and non-Talos jobs.
Nightly **46.0a1 (2016-01-11)**
Chrome Latest Release **47.0.2526.106** (64-bit)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1242)
> Bug 1224069 - Remove Talos entry from job details

- ui/plugins/pluginpanel.html
* Reftest analyzer goes after log buttons (since it's logically similar)
* Cancel button comes after retrigger (so it doesn't displace the retrigger
button if it's slow to load)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1241)
> Bug 1238468 - Update ordering of job panel buttons

- ui/js/directives/treeherder/top_nav_bar.js
- ui/partials/main/thWatchedRepoNavPanel.html
* Can now click on label, as well as checkbox to toggle tier on/off
* Clicking on label no longer dismisses the menu
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1236)
> Bug 1237765 - Usability improvements to new tier menu

- treeherder/config/settings.py
Rather than play whac-a-mole as and when people use API URLs that are missing the trailing slash, let's just stop redirecting to make the mistake more obvious:
https://docs.djangoproject.com/en/1.8/ref/settings/#append-slash
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1216)
> Bug 1234233 - Disable APPEND_SLASH to prevent usage of API URLs that 301

- docs/common_tasks.rst
* Recommend using the same `client_id` for stage/prod.
* Mention the need to file a bug (and where) for requesting approval.
* Explain prod approval needs submission to be working on stage first.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1248)
> Bug 1239428 - Docs: Clarify process for API credential approval

- ui/js/controllers/perf/graphs.js
- ui/partials/perf/graphsctrl.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1246)
> Bug 1187469 - Provide alternate tooltip content when (pushlog, compare) isn't available

- ui/js/controllers/perf/alerts.js
- ui/js/values.js
- ui/partials/perf/bugzilla_talos.tmpl
This is based on the existing Talos template we're using in AlertManager.
The code is somewhat hacky and will need to be updated for other performance
frameworks like awsy as that comes online, but it's a start!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1244)
> Bug 1234320 - Prepopulate filed perf regression bugs based on a template

- ui/partials/main/thHelpMenu.html
- ui/userguide.html
It has since moved from the Stackato Paas (which was EOL). I've omitted the Heroku revision since WhatsDeployed doesn't handle divergent branches well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1254)
> Bug 1227495 - Add the WhatsDeployed link back to the help menu

- ui/js/perf.js
- ui/partials/perf/comparectrl.html
* Only results with at least "med" confidence considered to be worth
showing by default
* Minimum t value for "high" confidence bumped to 5
* Minimum difference for regression/improvement bumped from 1.5 to 2
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1259)
> Bug 1240612 - Tweak thresholds and algorithms for perfherder compare view

- treeherder/etl/management/commands/ingest_push.py
In particular, make it so that the revision filter only need to be in
the revision, rather than it be equal. This lets us run ingest_push with
a shortened revision.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1261)
> Bug 1240831 - Loosen revision filtering criteria

- .travis.yml
- bin/peep.py
- puppet/manifests/classes/python.pp
* Update to peep v3.0.0 to pick up pip 8.x compatibility fixes.
* Use pip 8.0.0 on Travis.
* Update Vagrant virtualenv to the new release, which bundles pip 8.0.0.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1265)
> Bug 1241144 - Update to pip v8.0.0 on Travis/Vagrant

- treeherder/model/fixtures/repository.json
Since they are unused.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1271)
> Bug 1240385 - Remove taskcluster-integration, try-taskcluster & qa-try

- ui/js/models/job.js
- ui/plugins/controller.js
- ui/plugins/pluginpanel.html
Previously the "ETA" incorrectly used the submit time rather than the start time to calculate the time remaining.
This PR fixes that, clarifies what's shown for "duration" when the job hasn't started yet, and also cleans up a few other issues.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1260)
> Bug 1233653 - Fix the UI display of job durations & time remaining

- ui/perf.html
This happen when we already are viewing a specific alert id.
The problem is that ui-router merge the parameters from the current url
to determine the new parameters state. So the current is is merged, and
ui-router thinks that there is nothing to do since the states and
parameters are equivalent...
This fixes the issue, but it looks like a hack.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1272)
> Bug 1239841 - clicking on the top level 'alerts' link yields no action

- bin/post_compile
The Heroku build successfully completed with the changes in this PR.
It reduced the size of the slug by a third.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1274)
> Bug 1242471 - Heroku compile step cleanup

- ui/js/controllers/main.js
- ui/js/models/resultsets_store.js
- ui/js/providers.js
- ui/partials/main/thWatchedRepoNavPanel.html
Keep track of the count of unclassified jobs currently loaded that match the selected Tier settings.
When an event takes place that could change that value (new jobs loaded, classified or unclassified) then update that count again.  This uses the unclassified map like we did before, but re-evaluates it as needed.
This same technique can be leveraged (in the future) to get a count of unclassified for the current filter set as well.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1281)
> Bug 1157149 - The unclassified failure count should respect selected tiers of jobs

- Procfile
- app.json
The beta release-phase feature is making a backwards incompatible change today - moving from an app.json (and corresponding buildpack) approach to specifying a `release` Procfile entry that blocks the app deploy.
For more info, see:
https://devcenter.heroku.com/articles/release-phase?preview=1
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1290)
> Bug 1245472 - Heroku: Update to the new release-phase implementation

- puppet/manifests/classes/python.pp
- requirements.txt
- requirements/common.txt
- treeherder/config/settings.py
We're already using pylibmc on Heroku, since we need its SASL authentication support. However we were still using python-memcached on Vagrant, Travis, stage & prod.
To reduce the number of simultaneous changes when we migrate to Heroku, and to ensure at that point we're testing what we ship, this switches us to pylibmc pre-emptively for all environments.
Django does have a native pylibmc backend [1], however it doesn't support SASL authentication, so we have to use the custom django-pylibmc backend instead [2], which we choose to use everywhere (even though only Heroku's memcache instances require auth) for consistency.
Installing pylibmc requires libmemcached-dev, which is installed by default on Travis, has just been installed on stage/prod (bug 1243767), and as of this change, is now …
> Bug 1182043 - Use pylibmc instead of python-memcached

- bin/post_compile
The Python buildpack has now rewritten the automatic collectstatic feature, such that it no longer does an unnecessary (and time-consuming) dry-run every time. As such, we can switch back to the buildpack's automatic collectstatic:
https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/collectstatic
Prior to this landing, I'll update us to the latest version of the buildpack (using the `heroku buildpacks:set -i X ...` command) and remove the `DISABLE_COLLECTSTATIC` environment variable.
[ci skip]
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1292)
> Bug 1246208 - Heroku: Remove manual collectstatic workaround

- ui/plugins/talos/main.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1287)
> Bug 1244367 - Link to perfherder compare shouldn't always be against treeherder prod

- treeherder/perf/migrations/0010_add_alertsummary_backed_out.py
- treeherder/perf/models.py
- ui/js/controllers/perf/alerts.js
- ui/js/values.js
- ui/partials/perf/alertsctrl.html
* Rename 'resolved' -> 'fixed'
* Don't require a bug # for setting resolution status
* Some other related code cleanup
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1300)
> Bug 1247376 - Improve alert summary status options

- tests/settings.py
- treeherder/config/settings.py
- treeherder/config/settings_local.example.py
- treeherder/etl/classification_mirroring.py
- treeherder/model/derived/jobs.py
* Submit to OrangeFactor's new API rather than ES directly: Since Elasticsearch is protected by VPN (ES doesn't do auth) and setting up access is more hassle than it's worth on Heroku. Instead a new API endpoint is being added by bug 1235097 to OrangeFactor that forwards our classification report on for us. Hawk is used for authentication, the secret key for which will need to be set in the environment of prod before this lands (bug 1238584).
* Remove unused MIRROR_CLASSIFICATIONS setting: Since it's been replaced by the presence (or not) of the OrangeFactor Hawk key instead.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1222)
> Bug 1153324 - Submit to OrangeFactor's API rather than ES directly

- ui/js/controllers/perf/compare.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1305)
> Bug 1246398 - Automatically offer to set base revision when preloading perf compare chooser

- ui/js/values.js
This means that perfherder won't try to get performance series related to
this repository when getting related branch information.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1306)
> Bug 1249383 - Remove b2g-inbound as a performance branch

- tests/perfalert/test_analyze.py
- treeherder/perfalert/perfalert/__init__.py
Where we haven't seen a regression recently, it can be useful to incorporate
a bit of extra historical data into our calculation to get more accurate
results.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1302)
> Bug 1248031 - Incorporate extra historical data into perfalert calculation

- treeherder/model/fixtures/repository.json
Since it's EOL.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1315)
> Bug 1249674 - Remove addon-sdk repository

- tests/etl/test_job_loader.py
- treeherder/etl/job_loader.py
- treeherder/model/derived/jobs.py
- treeherder/webapp/api/resultset.py
With this change, if you get an exception during data ingestion in
DEBUG mode, it will simply throw the exception.  If not, it will
post the exception to New Relic with ``record_exception`` and move on
as we did before.  This will make it easier to detect errors in Vagrant
and prevent us from misssing them entirely on production and stage.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1313)
> Bug 1184795 - Stop hiding data ingestion exceptions

- ui/js/controllers/perf/e10s.js
- ui/js/directives/perf/compare.js
- ui/js/perf.js
- ui/js/perfapp.js
- ui/partials/perf/comparetable.html
- ui/partials/perf/e10s.html
* Allow to filter results to exclude results which wouldn't block the
release
* Link to wiki page outlining blocker criteria
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1323)
> Bug 1252203 - Add some release blocker features to the e10s dashboard

- ui/css/treeherder-job-buttons.css
- ui/js/directives/treeherder/clonejobs.js
We were animating all transitions for the job elements before, which
could be extremely expensive.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1318)
> Bug 1250574 - Animate job group expansion/deletion only on click

- .travis.yml
- puppet/manifests/classes/python.pp
To pick up require-hashes improvements, amongst other things:
https://pip.pypa.io/en/stable/news/
https://github.com/pypa/pip/compare/8.0.2...8.1.0
The Vagrant environment's virtualenv has been updated to 15.0.0, since that includes pip 8.1.0:
https://virtualenv.pypa.io/en/latest/changes.html
https://github.com/pypa/virtualenv/compare/14.0.1...15.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1341)
> Bug 1254961 - Update to pip 8.1.0

- tests/conftest.py
- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
- treeherder/model/migrations/0011_auto_20160316_1023.py
- treeherder/model/models.py
- treeherder/model/sql/jobs.json
When jobs are cycled, also remove the failure_line rows for
those jobs, to limit data consumption of the failure_line
table.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1333)
> Bug 1245080 - Remove failure lines with corresponding jobs

- treeherder/model/migrations/0011_longer_platform_names.py
- treeherder/model/models.py
It was 100 in the reference data signature, but only 25 in the build and
machine platform models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1352)
> Bug 1239185 - Bump maximum platform length to 100 characters in all cases

- tests/autoclassify/test_classify_failures.py
- tests/autoclassify/test_detect_intermittents.py
- tests/conftest.py
- tests/e2e/test_jobs_loaded.py
- tests/e2e/test_perf_ingestion.py
- tests/etl/test_buildapi.py
- tests/etl/test_common.py
- tests/etl/test_pushlog.py
- tests/log_parser/test_job_artifact_builder.py
- tests/log_parser/test_log_view_artifact_builder.py
- tests/log_parser/test_store_error_summary.py
- tests/log_parser/test_tasks.py
- tests/model/derived/test_jobs_model.py
- tests/webapp/api/test_resultset_api.py
It's almost entirely unnecessary (the few times we need base data
we can generate it ourselves) and can overwrite other test data
if we're not careful. Better just to remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1350)
> Bug 1256485 - Don't load initial data in unit tests

- Procfile
- bin/pre_deploy
**1)  Move the Heroku deploy tasks to their own script:**
Since the next commit adds reporting deploys to New Relic, which will be too verbose to include in the Procfile. Also adds additional log output (which follows the buildpack compile log formatting convention) to make it easier to find & follow the release tasks on Papertrail. Uses the `set -euo pipefail` recommendation from: http://redsymbol.net/articles/unofficial-bash-strict-mode/
**2) Report Heroku deployments to New Relic:**
Requires that `NEW_RELIC_APP_NAME` and `NEW_RELIC_API_KEY` be set in the environment. NB: `NEW_RELIC_API_KEY` is different from the existing `NEW_RELIC_LICENSE_KEY`. We're also making use of the runtime-dyno-metadata labs feature, which sets the slug/release related environment variables used in this …
> Bug 1165229 - Heroku: Report deployments to New Relic

- tests/conftest.py
- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
- ui/js/models/resultsets_store.js
This will look for the ``revision`` field in a job during ingestion.  If a resultset for that job can not be found, it will create a "skeleton" of one based on the ``revision``.  The skeleton resultset will look like:
{
"revision": <new_revision>,
"push_timestamp": 0,
"author": "pending...",
"revisions": []
}
Having no revisions, the resultset will not be visible in the UI until its data has been filled.  The data for the resultset will be filled by our periodic call to ``json-pushes``.
The BuildBot mechanism won't change in that we will wait to ingest jobs till we have the resultset created already.  This is for users of the ``Client`` (and the Pulse Job Ingestion, when Task Cluster starts using that).
The Client has been updated to require submitting the ``revision`` for a job and no …
> Bug 1199291 - Create result set on the fly for jobs ingested where the resultset is missing

- ui/css/treeherder-global.css
- ui/css/treeherder-navbar.css
- ui/partials/main/thWatchedRepoNavPanel.html
This hopefully fixes Bugzilla bug [1259567](https://bugzilla.mozilla.org/show_bug.cgi?id=1259567).
This (maybe?) improves the new Tier menu with a few things:
* a new Title property, consistent with its neighbors
* a menu using lowercase 'tier' visually consistent with our actual job labels
* removing 'Show' which was repeated in the menus
* some minor padding improvements
Current:
Proposed:
We also get a bit better padding on the checkboxes in the Similar Jobs details pane (I've just noted it in pink in the screen grab only).
Everything seems fine on both browsers. I wasn't able to find anywhere else which might be impacted by that extra `4px` padding, Perfherder, etc.
I defer to you guys though on these proposed changes :)
Tested on OSX 10.11.4:
Nightly **47.0a1 (2016-03-03)**
Chrome …
> Bug 1259567 - Add a title and UI improvements for the Tier menu

- ui/plugins/controller.js
The /artifacts endpoint defaults to only returning the first 10 items
unless a count is passed in.  We weren’t passing in that param, so we’d
only get back the first 10 (we need them for the buildbot request_ids).
This fixes it by passing in a “count” param equal to the number of jobs
we want to retrigger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1373)
> Bug 1255406 - "Retrigger all" on a >10 pinned jobs only retriggers 10

- ui/plugins/pinboard.js
For some reason changing the span to a button broke keyboard input
after job classification on Firefox on Linux/Windows (not Mac,
any flavor of Chrome also works fine). Blurring the input element
seems to fix this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1376)
> Bug 1198978 - Fix keyboard input after job classification

- bin/post_compile
- deployment/update/update.py
- puppet/manifests/classes/python.pp
- requirements/common.txt
- requirements/dev.txt
- treeherder/config/settings.py
- treeherder/config/whitenoise_custom.py
- treeherder/config/wsgi.py
WhiteNoise 3.0 now uses a Django middleware-based approach of integrating with Django, which means:
* simpler integration
* the ability to still use [Django's security middleware](https://docs.djangoproject.com/en/1.8/ref/middleware/#django.middleware.security.SecurityMiddleware) for things like HTTPS redirection, avoiding the need for yet another package (wsgi-sslify)
* Brotli compression support
* improved mimetype handling
* more consistent behaviour between development and production environments
For more info, see the [WhiteNoise changelog](http://whitenoise.evans.io/en/latest/changelog.html).
David Evans asked if I could give it a spin before he produced the final release, and from my testing locally it works really well.
See individual commit diffs & messages for more details.
--- …
> Bug 1258700 - Update to WhiteNoise 3.0 and switch to its middleware-based approach

- .eslintrc
- ui/js/controllers/logviewer.js
- ui/js/controllers/perf/alerts.js
- ui/js/controllers/perf/compare.js
- ui/js/controllers/perf/graphs.js
- ui/js/directives/treeherder/main.js
- ui/js/models/perf/alerts.js
- ui/js/models/repository.js
- ui/js/perf.js
- ui/plugins/controller.js
Requires “===“  and “!==“ instead of just “==“ and “!=“ for equality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1380)
> Bug 1260901 - enable eqeqeq eslint directive for JavaScript

- ui/js/controllers/perf/graphs.js
Request to merge code for Bug 1253029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1386)
> Bug 1253029 - Use case-insensitive matching in performance test selector

- treeherder/etl/management/commands/ingest_push.py
- treeherder/etl/tasks/buildapi_tasks.py
- treeherder/etl/tasks/cleanup_tasks.py
need to add a check for ``active_status`` in a few places, because our fixtures have some "onhold" repos, which mess things up on ingestion loops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1389)
> Bug 1231361 - fixes for skipping onhold repos

- ui/partials/main/thPinboardPanel.html
* Add boolean check to 'Save bugs only' so that ng-click is fully disabled.
* Disable dropdown if no job was selected, and keep Save Bugs Only disabled until a bug has been selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1390)
> Bug 1261082 - Disable additional pinboard actions when they don't make sense

- tests/etl/test_buildbot.py
- treeherder/etl/buildbot.py
This supercedes PR 1361 and is rebased onto master and has my test fixes squashed into @kmoir's patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1391)
> Bug 1212177 - l10n repacks should be displayed in treeherder properly

- ui/js/controllers/perf/graphs.js
- ui/js/perf.js
- ui/partials/perf/comparechooserctrl.html
- ui/partials/perf/graphsctrl.html
- ui/partials/perf/revisiondescribe.html
There was a bunch of code in the compare chooser which still assumed
12 character revisions everywhere which needed to be updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1393)
> Bug 1262202 - More fixes related to revision length for perfherder

- treeherder/model/derived/artifacts.py
We weren't taking the repository into account when getting the reference data
signature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1395)
> Bug 1231361 - Fix performance artifact ingestion

- treeherder/etl/perf.py
There was one more case where we didn't handle multiple signatures correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1397)
> Bug 1260926 - Fix etl code for perf signatures to handle framework properly

- tests/webapp/api/test_jobs_api.py
- treeherder/model/derived/jobs.py
If our regexes give the same platform values for several different
buildernames, then we may find the wrong signature and buildername for
those jobs.  This means that we will send the wrong buildername when
attempting to backfill or retrigger jobs.
This change ensures that the reference_data_signature is unique for
every buildername we get from buildbot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1372)
> Bug 1242038 - Store unique job signatures for buildernames

- tests/settings.py
- tests/webapp/api/test_bugzilla.py
- treeherder/config/settings.py
- treeherder/config/settings_local.example.py
- treeherder/webapp/api/bugzilla.py
- treeherder/webapp/api/urls.py
This endpoint receives a http POST request from the UI containing information about the bug to be filed (product, component, summary, version, description), then formats it properly as a submission to Bugzilla's REST API, using a server-side Bugzilla API key, and adding a "treeherder" comment tag.
The API then passes back either the bug ID (if the submission was successful) or Bugzilla's failure response if something went wrong.
I'm unsure how to write a test for this since it involves pushing the received information into Bugzilla and returns either a bug number or an error.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1282)
> Bug 1117583 - Add an API endpoint that creates a new bug in Bugzilla.

- tests/conftest.py
- tests/etl/test_perf_data_adapters.py
- treeherder/etl/perf.py
- treeherder/model/fixtures/repository.json
- treeherder/model/migrations/0013_add_enable_perfalert_property_to_repository.py
- treeherder/model/models.py
Make a repository property on whether we should generate performance alerts,
default to false.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1403)
> Bug 1251845 - Only generate performance alerts on specific repositories

- requirements/common.txt
Workaround for something changing in pypi that causes pip to prefer
the .zip version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1417)
> Bug 1266426 - Download PyYAML from a direct URL

- requirements/common.txt
Workaround for recent changes in PyPI's API response:
https://bitbucket.org/pypa/pypi/issues/436/peep-hash-failures-due-to-being-served-zip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1420)
> Bug 1266607 - Accept .zip sha256 hash for functools32

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
- treeherder/model/management/commands/migrate_to_intermediate_jobs.py
- treeherder/model/migrations/0017_add_centralized_job_model.py
- treeherder/model/models.py
Not really useful in-and-of-itself, but should be helpful by acting
as a centralized place to relate and map job information from what
is stored in the main treeherder database to what's in the per-project
databases. Eventually, we can extend this into a full-fledged jobs model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1411)
> Bug 1265037 - Create an intermediate jobs model/table

- ui/js/services/jobfilters.js
The result state and classified state should not apply to runnable jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1426)
> Bug 1256519 - Show 'Add new jobs' when classified jobs are filtered out

- ui/js/controllers/logviewer.js
- ui/js/directives/treeherder/clonejobs.js
- ui/js/models/job.js
- ui/js/services/jobfilters.js
- ui/js/services/main.js
- ui/plugins/controller.js
Since we only need it when actually filtering the job list, just dynamically
calculate there instead of keeping a (potentially large amount) of redundant
data in memory constantly. It doesn't take long to recalculate this relative
to other expenses (such as recalculating the DOM).
Since we were storing about 200 characters per job, and that a typical push
has upwards of 2000 jobs, this can save up to 2 megabytes on the default
treeherder view of 5 pushes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1424)
> Bug 1267102 - Be more efficient about storing job title + search information

- schemas/performance-artifact.json
- tests/etl/test_perf_data_adapters.py
- treeherder/etl/perf.py
E.g. "e10s" if a test was run in e10s mode, "shell" if a JS test was run
using only the JavaScript shell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1430)
> Bug 1261922 - Allow specifying extra options for a perfherder test

- tests/log_parser/test_error_parser.py
- treeherder/log_parser/parsers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1423)
> Bug 1245773 - Highlighting mozmake.EXE errors as well.

- ui/partials/main/thActionButton.html
This hopefully fixes Bugzilla bug [1240857](https://bugzilla.mozilla.org/show_bug.cgi?id=1240857).
This keeps the job info panel up and the current job selected, when the user clicks or navigates the resultset action menu.
I tested it out and propose we keep the **Set as top of range** and **Set as bottom of range** entries clearing the selected job. Since you may have a job already selected in a different resultset which will lie outside the new range, and the entire page reloads anyway when either of those menus is invoked.
So this is what we can now do, with this fix:
I did not locally test these action menu entries if you guys wish to poke at them:
* Add new jobs
* Trigger Missing jobs
* Trigger All Talos jobs
But otherwise everything seems fine locally on Nightly and Chrome.
Tested …
> Bug 1240857 - Ignore job clear on majority of resultset action menu

- Vagrantfile
- puppet/manifests/classes/elasticsearch.pp
- puppet/manifests/classes/init.pp
- puppet/manifests/vagrant.pp
**1) Vagrant: Switch to a 64bit Ubuntu base image:**
Since no packages for Elasticsearch 2.x+ are available for 32bit.
This also makes Vagrant consistent with stage/prod/Heroku/Travis.
**2) Vagrant: Install/run an Elasticsearch instance:**
Since it's required for fuzzy auto-classification in bug 1268484. 
Follows the steps here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
Test using:
`curl -X GET localhost:9200`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1435)
> Bug 1268485 - Add elasticsearch to local Vagrant environment

- tests/conftest.py
- tests/model/test_classified_failure.py
- treeherder/model/derived/jobs.py
- treeherder/model/models.py
- treeherder/webapp/api/classifiedfailure.py
When setting the bug number for a classified failure, first check for an
classified failure that already has that bug number, and if one exists,
update all references to the classified failure being changed to instead
point at the existing classification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1438)
> Bug 1265188 - Make sure to check for existing identical classification when trying to update the bug number.

- ui/js/controllers/logviewer.js
This var ``jobStr`` no longer exists.  Should use the ``scope.logViewerTitle`` instead now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1432)
> Bug 1268705 - fix logviewer job details fields

- schemas/pulse-job.yml
- tests/sample_data/pulse_consumer/job_data.json
- treeherder/etl/job_loader.py
- treeherder/model/migrations/0020_update_job_name_length.py
- treeherder/model/models.py
These changes were discovered to be needed after direct testing
against a Task Cluster exchange from the ``taskcluster-treeherder`` project with Pulse.
-Made some schema changes to be more precise for several fields
-Modified to job_loader to be more resilient to optional data being
missing
-Change the ``name`` field for job types and job groups to allow 100
characters because some names were being truncated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1433)
> Bug 1266229 - Pulse ingestion fixes and updates

- newrelic.ini
It's been switched off via the New Relic web UI config page for some time, however it makes sense to explicitly turn it off via the agent config (which cannot then be overridden by the web UI).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1450)
> Bug 1250573 - Explicitly disable New Relic browser monitoring

- tests/etl/test_buildapi.py
- treeherder/etl/buildapi.py
The long-term aim is to make the fetch missing pushlogs tasks redundant, by fixing the causes of missing pushes (if they're not already fixed).
However currently it's hard to identify whether it's still required, since the standard pushlog task can race with job ingestion, causing us to fetch 'missing' pushes that would have been otherwise retrieved fine.
By stopping the retrieval of missing pushes for pending/running jobs, we give the standard pushlog retrieval time to run, prior to the job being completed. If the push is still missing once we ingest the completed job, we'll run the fetch missing pushes task as before - as a last resort fall-back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Bug 1234247 - Only fetch missing pushlogs for completed jobs

- ui/js/models/job.js
This lets us search for strings like `fxup-esr(` (and was the old
behaviour before we accidentally regressed in bug 1267102)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1448)
> Bug 1269747 - Group job/group info together as one token for job title

- bin/run_celery_worker
- bin/run_celery_worker_buildapi
- bin/run_celery_worker_hp
- bin/run_celery_worker_log_parser
- bin/run_celery_worker_pushlog
- bin/run_celerybeat
- bin/run_gunicorn
Previously if the `bin/` directory scripts were run in the Vagrant environment, the processes run would not have been started via the New Relic wrapper command, since the New Relic licence key is not set.
For greater consistency between Vagrant and production, the wrapper command is now always used. 
This works since `NEW_RELIC_DEVELOPER_MODE` is defined in the Vagrant environment (thanks to a previous commit in the same bug), which prevents the agent from trying to submit real data:
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-configuration#developer_mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1451)
> Bug 1169944 - Use the New Relic wrapper when running scripts locally too

- README.md
- docs/common_tasks.rst
- docs/installation.rst
- treeherder/etl/pushlog.py
- ui/partials/main/thHelpMenu.html
- ui/partials/perf/helpMenu.html
- ui/userguide.html
RTD has moved project docs from PROJECT.readthedocs.org to PROJECT.readthedocs.io for security reasons.
There is currently a redirect in place, however RTD's mass email requested people update links since it won't be there forever.
Also updates a few wiki page links for pages that have moved after the A-Team rename.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1457)
> Bug 1270236 - Update ReadtheDocs links to the new .io domain

- docs/conf.py
The workaround that allowed using sphinx_rtd_theme when building locally, is no longer required. See:
https://github.com/rtfd/readthedocs.org/pull/2115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1458)
> Bug 1270239 - Docs: Remove the redundant sphinx_rtd_theme workaround

- .travis.yml
Since it's now supported:
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone
This will reduce the job runtime by 60-80s.
Similar to the container job (job chunk 1), since we're now caching the virtualenv, we have to workaround the default virtualenv being polluted with existing packages (by creating a clean one in another directory), to avoid constant cache churn.
See individual commits for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1453)
> Bug 1270182 - Travis: Enabling caching for the Ubuntu trusty jobs

- ui/css/treeherder-resultsets.css
This apparently helps prevent selecting text outside of the current element, which incidentally is exactly what I want to do here.
The other options that seemed to work but were a lot bigger/weirder changes were to:
1. Try adding click event handlers to force the selection to get trimmed to just the revision text, but that seems overkill to just select a single word of text.
2. Mangle the HTML in index.html so that there were no spaces between the closing </a> tag, the closing </span> tag, and the opening of the following <span> tag. Besides being ugly HTML, I think it only worked for selecting just the revision text on a triple-click.
3. Switch out the <span> for a <div>. This also caused things to shift onto new lines, which I'd then have to counter with more CSS.
---
This change is …
> Bug 1270682 - Stop selecting the spaces around a revision when double-clicking a revision

- ui/partials/perf/alertsctrl.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1466)
> Bug 1270871 - Specify framework when generating compare URL in alerts

- ui/js/controllers/main.js
- ui/partials/main/thActionButton.html
Not totally happy with this, but it appears to do what I want it to do. 
It even seems to handle me changing the other query string parameters, preserving their new values. I guess that's some angular magic happening behind the scenes...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1464)
> Bug 1236067 - Make 'Set as top of range' and 'Set as bottom of range' links work when middle-clicked

- ui/css/treeherder-navbar-panels.css
- ui/partials/main/thSheriffPanel.html
This adds a pencil icon when you hover over a job exclusion in the sheriff
panel list. 
Also included are some spacing fixes for CSS around the
changes I made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1471)
> Bug 1201982 - Add fa-pencil on hover for sheriff panel job exclusion entries

- bin/pre_deploy
...by defining `SKIP_PREDEPLOY` in the environment.
This is useful in cases where we want to avoid potentially destructive actions (such as running migrations) from taking place, or know that the migration is just going to time out unless run by hand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1460)
> Bug 1270454 - Allow skipping the Heroku pre_deploy script entirely

- requirements/common.txt
- treeherder/config/settings.py
The last usage of it was removed in bug 1229203.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1473)
> Bug 1271334 - Remove drf-extensions since it's no longer used

- tests/webapp/api/test_throttling.py
The lack of the `assert` statement meant they would have always passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1472)
> Bug 1271256 - Fix always passing tests in test_throttling.py

- ui/partials/main/jobs.html
- ui/plugins/pluginpanel.html
This fixes Buzilla bug [1261424](https://bugzilla.mozilla.org/show_bug.cgi?id=1261424).
In this PR we add a unique id for the job details action bar pin button, and add a few other useful id's and classes at the same time for future [treeherder-tests](https://github.com/mozilla/treeherder-tests) selection.
Tested on OSX 10.11.4:
Nightly **49.0a1 (2016-05-09)**
Chrome Latest Release **50.0.2661.94 (64-bit)**
Adding @wlach for review and @rbillings for visibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1484)
> Bug 1261424 - Add btn ids and classes for treeherder-tests

- requirements/dev.txt
Since the celery auto-reload feature which it enables hasn't been working for some time regardless:
https://github.com/celery/celery/issues/1658
https://github.com/celery/celery/issues/1025
https://github.com/celery/celery/issues/1880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1479)
> Bug 1175757 - Remove unused pyinotify dependency from dev.txt

- treeherder/etl/buildapi.py
- treeherder/etl/common.py
Bug 1090289 added handling for the l10n jobs that had invalid revision-branch combinations. However these jobs are no longer running (see bug 1125433 / bug 1221391), so the workaround can now be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1478)
> Bug 1271571 - Remove workaround for broken l10n dep jobs

- treeherder/model/derived/jobs.py
We were updating every field for these unnecessarily in certain cases
(every time in the case of machine) which could be problematic if we
had a flood of updates, as we did today.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1483)
> Bug 1271723 - Optimize updating machine and job_group reference data

- docs/installation.rst
This fixes Bugzilla bug [1272049](https://bugzilla.mozilla.org/show_bug.cgi?id=1272049).
This updates the Vagrant and VirtualBox installation requirements. So we don't refer to specific versions and instead encourage users to generally run the latest available releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1486)
> Bug 1272049 - Generalize vagrant and vbox install requirements

- ui/js/directives/treeherder/bottom_nav_panel.js
This work hopefully fixes Bugzilla bug [1271420](https://bugzilla.mozilla.org/show_bug.cgi?id=1271420).
This makes any and all jobs in the pinboard draw the same way as they do in the main job table, so that:
- failures are no longer always solid
- classified jobs carry their corresponding star icon
This might mean sometimes the star is truncated on longer job names, but longer job names are being truncated anyway, which is a separate issue.
Here's the new appearance (autoclassified failure shown):
I created a separate pinboard scope variable for this property, rather than mucking with the existing job object properties. So when anyone changes thResultStatusInfo [here](https://github.com/mozilla/treeherder/blob/daf296dc30c030e8292b4915d5766b86c8b7dacf/ui/js/providers.js#L61-L148) we …
> Bug 1271420 - Make classified failures consistent in the pinboard

- ui/partials/main/thJobDetailsRetriggerMenu.html
Would these be better on the `li` elements instead of the `a` elements within them? Do we have better strings to use?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1470)
> Bug 1207598 - Add some tooltips for retrigger/backfill job buttons

- ui/css/treeherder-info-panel.css
- ui/partials/main/thJobDetailsRetriggerMenu.html
- ui/plugins/controller.js
This is the easiest option I saw for this. It does mean the menu's tooltip is not completely correct (since it will still mention backfilling, even if that option is not present.
I guess the other options would be:
1) Also fix the tooltip for try repos.
2) On try, hide the entire menu and only show the old retrigger button.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1102)
> Bug 1207398 - Disable the backfill button on try repos

- ui/css/treeherder-navbar.css
This buys 150px of space in the navbar when the window is really narrow.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1158)
> Bug 1227264 - Only expand the quickfilter bar if the window is at least 850px wide

- ui/js/controllers/perf/alerts.js
- ui/partials/perf/bugzilla_talos.tmpl
It's too hard/annoying to account for weekends and holidays when we specify
the day of the week. Business days are just easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1491)
> Bug 1272435 - Specify backout date in perf regression template in business days

- ui/css/perf.css
- ui/js/controllers/perf/graphs.js
- ui/partials/perf/graphsctrl.html
I have created a simple "X" at the top right of the popup body. Clicking on it closes the popup. Clicking on anywhere else on the graph still closes the popup like before. Please have a look @wlach @jmaher
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1493)
> Bug 1263173 - Popup close button

- ui/js/controllers/perf/graphs.js
Using the button as specified. Using the hideTooltip function in place of plotUnselected. Use of previous code would have resulted in unnecessary deselection of a sub-plot, when clicking on the close button. @wlach Have a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1497)
> Bug 1263173 - Outside click clears popup

- docs/ui/installation.rst
- npm-shrinkwrap.json
- package.json
- web-server.js
Remove the requirement of needing local.conf.js, to automatically setting thServiceDomain, and add ability to connect to stage/custom service via command line flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1505)
> Bug 1274054 - Add command line flags to ui server and update doc

- treeherder/webapp/api/jobs.py
- treeherder/webapp/api/resultset.py
For now permission decisions should be made in pulse_actions.
In the future Treeherder will use Taskcluster scopes (bug 1273092) or accessTokens (bug 1273096).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1508)
> Bug 1259494 - Allow non-sheriffs to backfill & retrigger missing jobs

- treeherder/model/migrations/0024_remove_failure_line_unique.py
- treeherder/model/models.py
This is causing errors. In the future it will be replaced by a
more correct constraint that makes failure lines unique per log
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1511)
> Bug 1233164 - Remove incorrect unique constraint on failure_line

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
This is an obscure case (that we should probably handle better), but I
believe this patch should at least fix the new relic exception in the
common cases (specifically when we get the same retry with a different
guid in the same batch of jobs). This patch also adds a bunch of unit
tests to test ingesting batches of jobs containing retries. There are
many cases which still fail (which would probably never occur in real
life), but I'm going to put off fixing those for now -- see comments
in the unit tests for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1507)
> Bug 1272532 - Handle case where we get two different retry guids for a job

- schemas/pulse-job.yml
- treeherder/config/settings.py
- treeherder/etl/management/commands/ingest_from_pulse.py
- treeherder/etl/pulse_consumer.py
- treeherder/etl/tasks/pulse_tasks.py
This contains several tweaks and fixes that allow us to ingest data from
a real Task Cluster owned exchange.
One of the main fixes is the way I was binding to the exchange and
routing keys with the same Queue.  Before, it was re-creating the Queue,
so would miss some of the bindings.
This PR stops just short of actually turning ingestion on.  I figured I'd do that in the next PR to add it to the ``procfile`` and the queue in ``settings.py``
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1431)
> Bug 1266229 - More fixes and tweaks prior to turning on Pulse ingestion

- .travis.yml
- docs/common_tasks.rst
- npm-shrinkwrap.json
- package.json
* Adds an extra Python test chunk to balance the test runtimes (reduces the long pole chunk from 9 mins to 5-6, once the cache is warmed).
* Makes some nodejs changes to avoid constant cache invalidation (due to npm-shrinkwrap quirks) which lengthens job runtime (and bloats the Travis cache).
* Makes us actually use Python 2.7.11 (rather than 2.7.3 and 2.7.6) since until now we weren't (!!). As well as making the tests more representative of Vagrant/stage/prod/Heroku, Python 2.7.11 is 10-15% faster in many cases, so should reduce runtimes slightly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1518)
> Bug 1272207 - Reduce the Travis end to end time

- treeherder/webapp/api/logslice.py
Taskcluster logs use the name 'builds-4h'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1520)
> Bug 1275796 - Fix logslice API with taskcluster logs

- ui/js/models/resultsets_store.js
The values for these two fields is almost ALWAYS identical.  But when it's not, then it matters.  We should always use the ``platform`` field to aggregate jobs by platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1522)
> Bug 1274610 - Use platform field to group jobs instead of build_platform

- treeherder/model/fixtures/repository.json
Disables the following repos:
b2g-inbound
mozilla-b2g37_v2_2
mozilla-b2g37_v2_2r
mozilla-b2g44_v2_5
b2g-ota
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1528)
> Bug 1276234 - Disable the now unused gecko-based B2G repositories

- tests/client/test_treeherder_client.py
- tests/conftest.py
- tests/e2e/conftest.py
- tests/etl/test_pushlog.py
- tests/sample_data_generator.py
- tests/sampledata.py
- tests/test_utils.py
- tests/webapp/api/test_bugscache.py
By using `json.load()` instead of `json.loads()` we can pass the file object directly, rather than having to `.read()` it first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1527)
> Bug 1276254 - Remove unnecessary usage of .read() when json decoding

- ui/css/treeherder-navbar.css
- ui/partials/main/thWatchedRepoNavPanel.html
I added a scope to display exclusion state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1530)
> Bug 1200692 - Display current exclusion and revision state in tooltip

- docs/rest_api.rst
- docs/retrieving_data.rst
Since several people have not had logging set up when trying to debug issues using the client/API, so instead of a helpful error message (eg reminding them to sync their clock for Hawk auth), they get:
`No handlers could be found for logger "thclient.client"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1535)
> Bug 1229025 - Document treeherder-client logging

- treeherder/config/settings.py
Since the docs say it should come before Django's `CommonMiddleware`:
https://github.com/ottoyiu/django-cors-headers#setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1538)
> Bug 1272335 - Correct the ordering of CorsMiddleware

- treeherder/model/fixtures/repository.json
Since bug 1276389 removed mozilla-esr38 and comm-esr38 and bug 1251285 disabled alder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1542)
> Bug 1276864 - Remove mozilla-esr38, comm-esr38 and alder repositories

- treeherder/autoclassify/tasks.py
- treeherder/etl/tasks/buildapi_tasks.py
- treeherder/etl/tasks/classification_mirroring_tasks.py
- treeherder/log_parser/tasks.py
- treeherder/model/tasks.py
- treeherder/perf/tasks.py
- treeherder/webapp/api/auth.py
Requests made to the Treeherder API have their URLs and other request metadata recorded by the New Relic agent, which helps when debugging. 
However background celery tasks have no such URL or request metadata, so really benefit from the addition of custom attributes. These are then shown in the New Relic errors dashboard, slow transaction traces and in the Insights analysis tool:
https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-metrics/collect-custom-attributes
https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-transaction-api#add_custom_parameter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1543)
> Bug 1124278 - Add New Relic custom attributes for more celery tasks

- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
If a buildbot job is cancelled whilst in the pending state, the resultant "no longer running" job does not appear in builds-4hr (due to buildbot limitations), which causes orphaned jobs in Treeherder.
To work around this, Treeherder pre-emptively updates the DB for jobs when a user cancels them using the Treeherder interface. This is not ideal, since the manual DB update can race with the job completing (if the job finished before buildapi had time to cancel it), or worse can show the job as cancelled even if the buildapi request failed to complete, leaving the job as running even though Treeherder's UI will show it as stopped.
We have to keep on performing this suboptimal workaround for pending jobs (until we stop using buildbot), but we can at least limit it to just the pending jobs …
> Bug 1163802 - For job cancellation only manually update pending jobs

- treeherder/model/derived/jobs.py
- treeherder/model/sql/jobs.json
Found this while testing the pulse ingestion from Task Cluster
When updating or inserting a resultset record, we need to check against
the revision_hash value because, while revision_hash is on its way out, we
do still use it as a fallback and there is a unique index for it.
This error can occur as a race condition when a job is being ingested that
does not yet have a resultset, but during ingestion, the resultset is
created in parallel.  So the process ingesting the job tries to insert
the resultset and gets the index violation.  This check will prevent that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1531)
> Bug 1276355 - Fix IntegrityError for idx_revision_hash on resultset creation

- treeherder/config/settings.py
At once per day, it can stay out of date too long
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1533)
> Bug 1275589 - Shorten refresh duration of runnable jobs list to 4 hours

- treeherder/etl/management/commands/ingest_from_pulse.py
- treeherder/etl/pulse_consumer.py
settings.PULSE_DATA_INGESTION_CONFIG will be read in from the env
variable as a url ParseResult, not a string.  So this adjusts to
that change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1546)
> Bug 1277080 - Pulse config fixes for env.url variable

- tests/log_parser/test_store_failure_lines.py
- treeherder/log_parser/failureline.py
Python can either be compiled in UCS2 mode or UCS4 mode, which differ in
how non-BMP characters are represented. In the former they are
represented by a (user-exposed) surrogate pair so that a single astral
codepoint is encoded in a string of length 2. In the latter all
characters are represented by a single 4 byte value and all characters
have a string length of 1 e.g. len(u"\U0010FFFF") is 2 in UCS2 python
and 1 in UCS4 python.
Several functions don't work identically between the two variants
e.g. ord() will only accept a single python character and
ord(u"\U0010FFFF") will either succeed or fail depending on the compile
time options. Similarly, regexps can't directly work with characters
outside the BMP in UCS2 Python, and one must instead match the
individual parts of the surrogate …
> Bug 1277300 - Fix astral plan character hack to work with UCS2 python

- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
When a log already exists with different state during job ingestion with
a non-default status, we should not change it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1549)
> Bug 1277345 - Fix log exception during job ingestion

- Procfile
- bin/run_celery_worker_buildapi
- bin/run_read_pulse_jobs
- docs/pulseload.rst
- treeherder/config/settings.py
- treeherder/etl/management/commands/read_pulse_jobs.py
This PR creates the ``store_pulse_jobs`` celery queues on Heroku and SCL3.  I also renamed the ``ingest_from_pulse`` mgmt command to be ``read_from_pulse`` to hopefully distinguish the reading from pulse queue from the actual storage of the jobs.  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1532)
> Bug 1266229 - Enable pulse reading queues prior to turning on ingestion of jobs

- treeherder/model/fields.py
Since `related_field` was renamed to `target_field` in:
https://github.com/django/django/pull/4241
Fixes:
AttributeError: 'FlexibleForeignKey' object has no attribute 'related_field'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1553)
> Bug 1277593 - Make FlexibleForeignKey compatible with Django 1.9

- tests/conftest.py
- tests/model/derived/test_jobs_model.py
- treeherder/model/derived/jobs.py
This wasn't a serious issue, it just meant that we would never infer a bug
number when a job was sheriffed using the non-autoclassification UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1564)
> Bug 1277936 - Fix indentation issue that made update_autoclassification_bug a no-op.

- Procfile
This ca be turned on or off based on the number of dynos assigned to it.  By default, it will get zero, so it'll be a no-op, till we flip the switch in the Heroku dashboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1566)
> Bug 1266229 - Allocate Heroku dynos for pulse queue reading

- treeherder/autoclassify/management/commands/autoclassify.py
Refactor the code slightly by forward-porting the changes from the
elasticsearch branch that cause us to optimise out further matching when
we find a match that is considered good enough. Also wrap the creation
of a FailureMatch in a try/except block so that we don't fail if there
is an existing FailureMatch for the same line/classification which could
happen if the task previously failed for an unrelated reason. This gives
higher granularity than just putting the entire task in a transaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1569)
> Bug 1277575 - Don't fail the task when autoclassification encounters a duplicate FailureMatch

- schemas/pulse-job.yml
- tests/etl/test_job_loader.py
- treeherder/etl/job_loader.py
Some repos are longer-lived and do not yet have the Task Cluster
code that allows them to submit tasks with a revision.  They only
have the older code to submit revision_hash.  This prevents the
jobs from being ingested via Pulse.  This commit adds support
for revision_hash until a time when it's no longer needed.
I created Bug 1277956 to remind me to remove this support when its no longer needed.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1559)
> Bug 1277955 - Add support for revision_hash to pulse jobs

- treeherder/config/settings_local.example.py
- ui/css/treeherder-bugfiler.css
- ui/index.html
- ui/js/controllers/bugfiler.js
- ui/js/controllers/main.js
- ui/js/values.js
- ui/partials/main/intermittent.html
- ui/plugins/controller.js
- ui/plugins/failure_summary/controller.js
- ui/plugins/failure_summary/main.html
- ui/plugins/pluginpanel.html
This is now rebased onto the now-landed server-side component to this.
This adds buttons to lines in the failure summary panel when a failed job is selected in the UI. When you click that line, a modal dialog pops up with the new bug filer form. 
At the top of the form, you can select a product/component pair for the bug. An attempt is first made to select the product/component based on the filename of the failure, but that's imperfect, so there's a product finder tool that searches bugzilla for the product/component pair for the soon-to-be-filed bug. 
The form pre-fills the summary line from the line that was clicked in the failure summary panel, stripping out extraneous things like "TEST-UNEXPECTED-FAIL". Off to the right of the Summary field is a '>' button, which shows the other lines …
> Bug 1117583 - Add UI to treeherder to use the new bug filing API

- treeherder/model/migrations/0027_jobdetail_unique_together_20160607_1447.py
- treeherder/model/models.py
During job ingestion, we can sometimes get an error of
MultipleObjectsReturned when creating a JobDetail record.  Adding
an index for uniqueness will prevent us from getting that while
using the get_or_create model function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1573)
> Bug 1278711 - Add unique together index to JobDetail model/table

- tests/autoclassify/test_classify_failures.py
- treeherder/autoclassify/matchers.py
- treeherder/model/migrations/0028_test_match_created_index.py
- treeherder/model/models.py
First try to select only failure lines from the last 7 days. If that
didn't find a good enough match, select from the 7 days before that, and
so on. If running the queries has taken more than a set time limit,
stop looking at further time ranges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1580)
> Bug 1279193 - Use a sliding time window, with a maximum execution time, for autoclassification.

- tests/conftest.py
- treeherder/model/management/commands/load_initial_data.py
- treeherder/perf/fixtures/performance_bug_templates.yaml
- treeherder/perf/migrations/0017_performancebugtemplate.py
- treeherder/perf/models.py
- treeherder/webapp/api/performance_data.py
- treeherder/webapp/api/performance_serializers.py
- treeherder/webapp/api/urls.py
- ui/js/controllers/perf/alerts.js
Do this by storing the content of each template in the database (currently
we have just one, for Talos) and adding an API endpoint for fetching it.
For now, we will store the data that should be in each template in a
pre-loaded fixture. Bonus new feature: automatic population of a "CC" list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1579)
> Bug 1260805 - Make performance bug template configurable per-project

- treeherder/log_parser/tasks.py
* Adds the name and url for each `JobLog`, to save having to look them up using the id.
* Renames the status attribute to make it clearer that it refers to the status that was set prior to the task starting (eg helps answer if the log was already successfully parsed or had previously failed).
* Switches the status to the human-readable status descriptions (such as "pending") rather than the status code, using `Model.get_FOO_display()`:
https://docs.djangoproject.com/en/1.8/ref/models/instances/#django.db.models.Model.get%5FFOO%5Fdisplay
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1583)
> Bug 1124278 - Adjust the New Relic custom attributes for the log parser

- ui/js/perf.js
This was intended to guard against Talos outputting 0 values in the case of
error, but I don't believe that happens anymore (if it ever did?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1585)
> Bug 1279591 - Include 0 / null values in Perfherder compare view

- ui/js/directives/treeherder/resultsets.js
When a DONTBUILD push is in "Add new Jobs" mode, Treeherder reports the percentComplete as NaN. Coercing that into undefined prevents the page title from displaying "NaN%"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1582)
> Bug 1279359 - Don't let percentComplete become NaN when the total number of jobs is 0

- tests/etl/test_runnable_jobs.py
- tests/model/derived/test_jobs_model.py
- treeherder/etl/allthethings.py
- treeherder/model/management/commands/cycle_data.py
- treeherder/webapp/api/runnable_jobs.py
The runnable jobs process used to add new buidlernames immediately, but wait till we cycle data to remove defunct ones.  This change will remove defunct ones at the same time we update for new ones.  
Added a test for this as well as removing the cycle data test for runnable jobs, since it's no longer done that way.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1587)
> Bug 1275589 - Prune runnable jobs

- tests/client/test_perfherder_client.py
- tests/client/test_treeherder_client.py
- tests/conftest.py
- treeherder/client/thclient/client.py
* Use responses instead of mock in the Python client tests
* Make Python client requests use connection pooling
* Send auth headers for Python client GETs too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1589)
> Bug 1245158 - Make Python client requests use connection pooling + enable auth for GETs

- treeherder/etl/pushlog.py
Since the `CollectionNotStoredException` exception raised later will contain a combination of all exceptions and is harder to follow in the New Relic UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1607)
> Bug 1281309 - Report individual pushlog exceptions to New Relic

- treeherder/log_parser/tasks.py
- treeherder/log_parser/utils.py
- treeherder/webapp/api/job_log_url.py
Removes the unnecessary second fetching of the JobLog object & some other cleanup.
See individual commit messages for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1611)
> Bug 1281463 - The log parser fetches the JobLog object twice for each log

- docs/rest_api.rst
- docs/retrieving_data.rst
- docs/submitting_data.rst
- tests/client/test_perfherder_client.py
- tests/client/test_treeherder_client.py
- tests/conftest.py
- tests/test_utils.py
- tests/webapp/api/test_artifact_api.py
- treeherder/client/thclient/client.py
- treeherder/client/thclient/perfherder.py
- treeherder/config/settings.py
- treeherder/etl/th_publisher.py
- treeherder/log_parser/utils.py
- treeherder/model/management/commands/import_reference_data.py
- treeherder/perf/management/commands/import_perf_data.py
- treeherder/perf/management/commands/test_analyze_perf.py
This combines the `protocol` and `host` parameters into a new `server_url` parameter to avoid the easily-made mistake of omitting `protocol` when submitting to a local Vagrant instance, as well as reducing the number of config variables users of the client have to keep track of.
In addition:
* The per-method `timeout` parameters have also been removed for simplicity (I couldn't find any consumers of them using GitHub code search)
* The default timeout has been lowered from 120s to 30s
* The Treeherder environment variables `TREEHERDER_REQUEST_PROTOCOL` and `TREEHERDER_REQUEST_HOST` are now no longer required
* General python client cleanup
See individual commit messages for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Bug 1279213 - Simplify the Python client's handling of server url & timeouts

- ui/js/services/jobfilters.js
So you can filter by "buildbot" or "taskcluster".  When other systems start using pulse ingestion, you'll be able to filter by whatever they put as their ``buildSystem``.  This is helpful for testing to see what jobs come from where.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1601)
> Bug 1280504 - add ability to filter by build system type

- treeherder/config/settings.py
In the past we've had infra incidents caused by excessive use of Treeherder's API. To make the accidental cases of these easier to diagnose, consumers of our API should set an appropriate user agent.
To enforce this, common default user agents are now blacklisted using the Django common middleware:
https://docs.djangoproject.com/en/1.8/ref/middleware/#module-django.middleware.common
https://docs.djangoproject.com/en/1.8/ref/settings/#disallowed-user-agents
Requests to the API that match one of the blacklisted user agents will received an HTTP 403 response with content `Forbidden user agent`.
Bug 1230222 has whittled down the number of undesired user agents - prior to this landing I'll double check any remaining and fix them/announce on the mailing lists etc.
Edit: The docs changes have …
> Bug 1267683 - Prevent default scripting user agents from interacting with Treeherder

- tests/sample_data/pulse_consumer/job_data.json
- treeherder/etl/job_loader.py
The pulse ingestion was throwing away the UTC timezone that came from Task Cluster and applying the local timezone.  That's how ``time.mktime`` works.  Now we parse the time, get the time tuple in UTC and create the timextamp with ``calendar.timegm`` which expects UTC times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1619)
> Bug 1281412 - Fix timezones with pulse ingestion

- treeherder/config/whitenoise_custom.py
The existing behaviour in `update_files_dictionary()` wasn't as obvious as it could be.
This is a no-op in terms of functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1622)
> Bug 1282839 - Make CustomWhiteNoise easier to understand

- tests/test_worker/test_task.py
- treeherder/workers/task.py
Make retryable_task retry the actual task object, rather than trying to
call .retry on the wrapped function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1623)
> Bug 1282872 - Fix exception retrying tasks.

- treeherder/workers/task.py
This prevents over-long retries or too mcuh variation (the distribution
is centred around 3 hours with thoretical minima and maxima at about 2
and 4 hours). That's not a very long time if we have infra issues, but
is longer than the old one hour limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1629)
> Bug 1283074 - Make exponent for task retry backoff close to 2

- schemas/pulse-job.yml
Several existing jobs are already out of compliance with these patterns
and there is no existing way to tell task definition developers how to
comply with our required patterns.
created bug 1283866 in Taskcluster for that tool/workflow
This removes the pattern requirements.  If we ever decide that we DO
need these patterns, we can create that tool and then fix old task
definitions to comply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1639)
> Bug 1283865 - remove pattern requirements for pulse job display fields

- ui/js/controllers/perf/compare.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1643)
> Bug 1283880 - Fix display of compare subtest performance when branches differ

- ui/plugins/pluginpanel.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1642)
> Bug 1229782 - Add an info icon for cases where the job name has a description hiding in a tooltip

- docs/rest_api.rst
To ease debugging and coordinating with credential owners in case of any later issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1647)
> Bug 1284460 - Docs: State bugs should be filed for credential changes

- docs/rest_api.rst
To make it clearer when submitters are hitting this case vs other authentication failure modes (like incorrect `client_id` or `secret`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1648)
> Bug 1284503 - Docs: List the error message shown for Hawk token expiry

- treeherder/perf/fixtures/performance_bug_templates.yaml
* We now have a keyword in bugzilla for talos-regression which we should use
instead of the whiteboard (it's faster)
* Add Robert and Allison to the default CC list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1651)
> Bug 1284626 - Update talos regression filing template

- tests/webapp/api/test_bugzilla.py
- treeherder/webapp/api/bugzilla.py
I originally used usernames so I wouldn't be printing full email addresses
into bugs. Apparently older users in Treeherder have a readable name as
the username field, but newer users have a random string of
letters/numbers, which is much less useful.
This change uses the user's email address instead, splitting it at the '@'
and using the first part. This should still be relatively unique per user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1654)
> Bug 1284990 - Use email address instead of username

- ui/js/controllers/perf/alerts.js
- ui/js/controllers/perf/e10s.js
- ui/js/models/perf/alerts.js
- ui/js/perf.js
Here are changes to 2 of the files which use _.map. 
In https://github.com/mozilla/treeherder/blob/master/ui/js/perf.js#L372
_.map is being operated on an array and not an object, whereas, $httpParamSerializer works only on objects.
Also do you want me to make changes to the file which you had changed as an example?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1658)
> Bug 1285004 - Use angular's httpParamSerializer in perf controllers

- schemas/pulse-job.yml
This sets the field lengths to what they will be in a later PR for
the job_details model.  But these are still within the constraints
of the current field lengths for that table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1665)
> Bug 1278711 - Set pulse schema jobdetails field lengths higher

- .travis.yml
The `manage.py check --deploy` command causes the Django models to be initialised, which requires Elasticsearch to be accessible, if `ELASTICSEARCH_URL` is set. The variable is set globally for the Travis runs, however for the linters job (which is where `check --deploy` was previously being run) Elasticsearch isn't actually installed.
Whilst we could have just unset `ELASTICSEARCH_URL` for the linters job, it's best to move the test to the main Python job chunk, since:
* The command doesn't only hit Elasticsearch, but also the DB, and the linters job is running the older mysql 5.5, rather than mysql 5.6. 
* Whilst Elasticsearch isn't currently enabled for anywhere other than the prototype Heroku instance, we'll soon be using it everywhere, so should get `check --deploy` to actually test …
> Bug 1285539 - Fix 'manage.py check --deploy' on Travis

- tests/conftest.py
- tests/log_parser/test_tasks.py
Bug 1280910 made the bug suggestions generation during log parsing no longer hit the bugscache Treeherder API, so we no longer need to mock the request to it.
Any future uses of `fetch_json()` during tests would be better mocked using the responses library instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1669)
> Bug 1285923 - Remove unused mock_fetch_json fixture

- tests/etl/test_buildapi.py
- tests/etl/test_pushlog.py
- tests/log_parser/test_tasks.py
- tests/model/derived/test_artifacts_model.py
All tests other than those testing the API no longer hit the API (as of bug 1211414), so don't need to use the `mock_post_json` fixture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1668)
> Bug 1285925 - Remove unnecessary usages of the mock_post_json fixture

- requirements/common.txt
Since the latter is actually being maintained, and is recommended by the Django docs:
https://docs.djangoproject.com/en/1.9/ref/databases/#mysql-db-api-drivers
mysqlclient has had several bug fixes as well as Python 3 support added since it forked from upstream 1.2.5:
https://github.com/PyMySQL/mysqlclient-python/blob/master/HISTORY
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1671)
> Bug 1277797 - Switch from the MySQLdb driver to mysqlclient

- requirements/common.txt
To pick up Datasource's switch to mysqlclient:
https://github.com/jeads/datasource/releases/tag/v0.11.0
(Otherwise we still try to install MySQL-python alongside mysqlclient)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1675)
> Bug 1277797 - Update to datasource 0.11.0

- ui/js/controllers/jobs.js
```
Error: [$interpolate:interr] Can't interpolate: {{getCancelJobsTitle()}}
ReferenceError: scope is not defined
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1677)
> Bug 1278800 - Fix 'scope is not defined' error from getCancelJobsTitle

- docs/common_tasks.rst
Since if the wheel package is not installed, it results in:
`error: invalid command 'bdist_wheel'`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1678)
> Bug 1286240 - Docs: Install 'wheel' at the same time as 'twine'

- treeherder/model/search.py
This is likely just deleting things that were not indexed in the first place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1681)
> Bug 1284429 - Ignore BulkIndexError when trying to bulk delete from ElasticSearch

- ui/css/treeherder-info-panel.css
- ui/js/directives/treeherder/bottom_nav_panel.js
- ui/plugins/pluginpanel.html
This work hopefully fixes Bugzilla bug [1281944](https://bugzilla.mozilla.org/show_bug.cgi?id=1281944).
This makes the job details classification star match the actual job result color for the selected job. Prior they were always orange (testfailed), which wasn't accurate for other result types.
**Before** (see orange classification star in lower left details panel):
**Proposed** (now purple here):
A big thanks to @camd for helping work through some of the angular stuff with me, to correctly access the job result property in the directive. I wasn't able to use the existing css color classes for the main jobs table because of their interdependence with before and after selectors, which messes up the star rendering in job details. So I replicated the color properties.
I have a few css …
> Bug 1281944 - Make job-panel classification star match job color

- treeherder/webapp/api/jobs.py
We were allowing filtering on any of the model's properties, which caused
djangorestframework to try and render some ridiculous things in the browsable
api renderer (including an option form with every single job in treeherder)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1694)
> Bug 1287140 - Restrict job detail filters to a small set

- requirements/common.txt
To pick up the XSS fix, plus:
https://github.com/marcgibbons/django-rest-swagger/blob/stable/0.3.x/CHANGELOG.md
https://github.com/marcgibbons/django-rest-swagger/compare/0.3.7...0.3.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1701)
> Bug 1286463 - Update django-rest-swagger to 0.3.9

- requirements/common.txt
Fixes Insights missing the HTTP status code amongst other things:
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-268050
https://github.com/edmorley/newrelic-python-agent/compare/v2.66.0.49...v2.68.0.50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1707)
> Bug 1287950 - Update New Relic Python agent to 2.68.0.50

- requirements/common.txt
To pick up the admin XSS fix:
https://docs.djangoproject.com/en/1.9/releases/1.8.14/
https://github.com/django/django/compare/1.8.13...1.8.14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1708)
> Bug 1287975 - Update Django to 1.8.14

- requirements/common.txt
To pick up the corrected XSS fix:
https://github.com/marcgibbons/django-rest-swagger/pull/491
https://github.com/marcgibbons/django-rest-swagger/compare/0.3.9...0.3.10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1709)
> Bug 1286463 - Update django-rest-swagger to 0.3.10

- treeherder/etl/tasks/classification_mirroring_tasks.py
- treeherder/log_parser/failureline.py
- treeherder/log_parser/tasks.py
- treeherder/log_parser/utils.py
- treeherder/workers/task.py
This improves task retrying, such that we now:
* no longer accidentally wrap several log related tasks in two nested retry cycles (for a total of 100 retries)
* reduce code duplication
* no longer retry `zlib.error` exceptions (seen when we hit bug 1284360)
* manually report the exceptions that caused tasks to retry, rather than relying on the messy automatic `celery.exceptions:Retry`, where everything is lumped into one group
This should reduce some of the log parser backlogs we've been seeing recently, as well as make it easier to interpret exceptions using the Error Analytics view in New Relic.
See individual commit messages for more information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Bug 1284289 - Improvements to celery task retrying & New Relic reporting

- ui/js/models/resultset.js
- ui/js/models/resultsets_store.js
* Validate that we're passing an actual date to the server (should always
be the case, but just in case...)
* Update the last updated interval even if nothing has been returned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1703)
> Bug 1287501 - Attempt to make sure polling for new jobs is reasonable

- tests/log_parser/test_performance_parser.py
- treeherder/log_parser/parsers.py
Sometimes a non-valid PERFHERDER string can be found in a log because
of debugging code or other reasons. There's no reason to not parse the rest
of the log for a job if we find one of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1714)
> Bug 1288202 - Ignore malformed PERFHERDER_DATA lines

- treeherder/etl/pushlog.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1717)
> Bug 1288181 - Handle empty changeset list from json-pushes

- treeherder/model/derived/base.py
This prevents failures during disconnect masking the underlying problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1722)
> Swallow exceptions raised during datasource disconnect when there is a preexisting exception

- Gruntfile.js
- contribute.json
* Make contribute.json valid json
* Make contribute.json available at site root (so web based tools can find it when eg automatically reporting bugs)
This boosts our HTTP Observatory score (with which all Mozilla sites are about to be analysed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1725)
> Bug 1289159 - Fix contribute.json so it parses and is available at site root

- ui/partials/main/jobs.html
This fixes bug [1288928](https://bugzilla.mozilla.org/show_bug.cgi?id=1288928).
This removes the now unused `isLoadingJobs` from the markup. Everything still seems fine in local testing on page load.
Nightly **50.0a1 (2016-07-23)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1726)
> Bug 1288928 - Remove obsolete isLoadingJobs from markup

- docs/rest_api.rst
This was my first stop in the docs and playing around with treeherder and just wasn't sure what the import was so had to go read some code. Thought it might be `treeherder`, or `treeherder_client`, I know its mentioned later on, but thought it would help anyone who didn't read the docs later on :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1720)
> make clear the name of the module

- treeherder/webapp/api/jobs.py
The count(*) query that limit/offset pagination requires is super slow with
InnoDB. Using a cursor-based approach makes the behaviour more reasonable if
no parameters are specified with this endpoint (arguably we should require
a parameter if none specified, but we can leave that for another time)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1695)
> Bug 1280039 - Use cursor pagination with /jobdetail/ endpoint

- requirements/common.txt
This fixes `MacMismatch` being raised when `MisComputedContentHash` should have been raised instead. In addition, a the hash of the payload is no longer generated a second time unnecessarily for all requests.
https://mohawk.readthedocs.io/en/latest/#changelog
https://github.com/kumar303/mohawk/compare/0.3.2.1...0.3.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1739)
> Bug 1289694 - Update mohawk to 0.3.3

- tests/webapp/api/test_auth.py
- treeherder/config/settings.py
- treeherder/webapp/api/auth.py
- treeherder/webapp/api/bug.py
- treeherder/webapp/api/bugzilla.py
- treeherder/webapp/api/classifiedfailure.py
- treeherder/webapp/api/failureline.py
- treeherder/webapp/api/note.py
- treeherder/webapp/api/permissions.py
- treeherder/webapp/api/text_log_summary.py
- treeherder/webapp/api/text_log_summary_line.py
* Refactors test_auth.py to increase test coverage and prepare for later changes.
* Clarifies the error message shown to clients when the specified Hawk `client_id` was not authorised/found.
* Merges the redundant `HasHawkPermissions` into `HasHawkPermissionsOrReadOnly`.
* Removes unnecessary checks inside `IsStaffOrReadOnly`.
* Sets an API-wide default of the `IsAuthenticatedOrReadOnly` permissions class (which accepts either Hawk or Django user authentication), which prevents us from adding new API endpoints that are writeable even by anyone, even in they are not logged in.
These changes also simplify my work in bug 1277304 / #1627, since there are now fewer places to adjust when trying to block all writes when down for maintenance.
As always, see individual commit messages for more …
> Bug 1275405 - Clean up the API permissions system

- docs/installation.rst
Now that Treeherder's data ingestion process doesn't hit it's own API:
* `./manage.py runserver` is less susceptible to memory issues.
* The runserver/gunicorn process doesn't need to be running whilst the data ingestion takes place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1745)
> Bug 1289709 - Docs: Simplify development data ingestion instructions

- treeherder/config/settings.py
urlparse's `netloc` attribute (which I'd copied from the `SITE_HOSTNAME` usage elsewhere in settings.py) includes the port number as well as the hostname, and so was causing the SCL3 hostname check to not match (since the environment variable there includes the default port, even though it doesn't need to), meaning TLS was enabled for celery on SCL3 when the rabbitmq instance there doesn't support it.
Also changes `SITE_HOSTNAME` to use what we really wanted, which was `hostname` not `netloc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1753)
> Bug 1286702 - Fix hostname extraction in server_supports_tls()

- treeherder/model/migrations/0034_add_unique_together_build_machine_platform.py
- treeherder/model/models.py
Also to the machine_platform table.
This is necessary because we use a get_or_create() on these
tables, but without the unique index, we can (and did) get
duplicates which then blocked data ingestion of jobs on try.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1759)
> Bug 1291882 - Add unique_together index on build_platform table

- tests/model/derived/test_artifacts_model.py
- treeherder/model/derived/artifacts.py
- treeherder/model/migrations/0035_job_detail_field_lengths_decrease.py
- treeherder/model/models.py
This is required in order to create a unique index on title,
value and job_id to prevent duplicates.  The index will be
created in a later PR.
This also uses update_or_create instead of get_or_create as
this will be the mechanism going forward to prevent duplicates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1666)
> Bug 1278711 - Lower field lengths in job_detail table

- ui/js/directives/treeherder/clonejobs.js
Edge case I apparently missed when testing Bug 1289651.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1763)
> Bug 1292708 - Scroll job into view if it is hidden behind the navbar/header

- treeherder/model/migrations/0036_job_details_unique_together.py
- treeherder/model/models.py
This one piggy-backs on the previous PR for bug 1278711, so it is in the same branch.  So please just compare using the latest commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1667)
> Bug 1278711 - Job detail unique together idx

- tests/ui/unit/controllers/autoclassify.tests.js
- ui/plugins/auto_classification/controller.js
Order is based on a token match with the error summary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1774)
> Bug 1293653 - Sort the unstructured bug suggestion in the autoclassify panel.

- ui/css/treeherder-pinboard.css
- ui/partials/main/thPinboardPanel.html
The only change in functionality from using the separate element is that this placeholder goes away immediately when the input has focus, while the old, separate placeholder stayed until you started typing into the input. Not sure we care, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1769)
> Bug 1293447 - Use a placeholder attribute instead of a separate element for placeholder text

- .travis.yml
- bin/pre_compile
- bin/vendor-libmysqlclient.sh
- puppet/manifests/classes/mysql.pp
- puppet/manifests/classes/python.pp
- puppet/manifests/vagrant.pp
- tests/test_checks.py
- tests/test_setup.py
- treeherder/__init__.py
- treeherder/checks.py
- treeherder/config/settings.py
**1) Vendor libmysqlclient 5.7 on Heroku, Travis and in the Vagrant environment**
The latest versions of libmysqlclient 5.5/5.6 (used by mysqlclient) are still vulnerable to TLS stripping, even after last year's backports of 5.7.x fixes:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3152
- http://bugs.mysql.com/bug.php?id=82383
Ideally we'd just use the standalone Connector/C library instead of the libmysqlclient packages, however the latest release is too old (http://bugs.mysql.com/bug.php?id=82448).
Heroku's cedar-14 stack comes with libmysqlclient 5.5.x, so until it is updated to 5.7.x (see heroku/stack-images#38) we must manually vendor 5.7.x ourselves, so that connections between the Heroku dynos and our public RDS instances are secure. We can do this and still remain on …
> Bug 1289156 - Vendor libmysqlclient 5.7 to protect against CVE-2015-3152

- bin/pre_compile
- bin/vendor-libmysqlclient.sh
The Heroku pre_compile script is currently run prior to the cache being restored (https://github.com/heroku/heroku-buildpack-python/pull/321), which means we have to tweak PATH so vendor-libmysqlclient.sh can find the binaries from the cache instead of the app directory.
However the workaround added in #1770 only added one of the two extra required PATHs, this adds the other.
Prior to this the buildpack compile would output:
> ./bin/vendor-libmysqlclient.sh: line 65: pip: command not found
...and so wouldn't purge the old mysqlclient package, which is needed to force recompilation against the newer libmysqlclient.
Once the PR against heroku-buildpack-python is merged, these workarounds can be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Bug 1289156 - Update the Heroku PATH workaround so pip can be found

- tests/model/derived/test_jobs_model.py
Previously test_new_job_in_exclusion_profile was attempting to download logs from ftp.mozilla.org, due to the log parser not being mocked, which caused intermittent test timeouts on Travis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1776)
> Bug 1294096 - Fix test that times out due to external HTTP requests

- bin/pre_compile
- treeherder/config/settings.py
There's a strange bug when creating relative symlinks on top of an already existing symlink, in that the target resolves to the wrong file. As such, we now explicitly check for an existing symlink first, to avoid overwriting.
The SCL3 system check disabling has also been tweaked since #1770, since the `HOSTNAME` environment variable doesn't appear to be set during deploy, even though it appears in `env` on the same machine.
Yey for deployment code that can only really be tested by deploying \o/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1779)
> Bug 1289156 - Final tweaks for libmysqlclient deploy on Heroku/SCL3

- tests/log_parser/test_error_parser.py
- treeherder/log_parser/parsers.py
Handle newlines after blacklisted strings and add unit tests for this case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/treeherder/1781)
> Bug 1268333 - Ignore pygtk import lines properly
