mozilla/treeherder

ui/helpers/url.js, ui/job-view/details/summary/ActionBar.jsx
This reverts commit f96bcb910ebb83b03c43cad7d1f92eabe05fca13, per:
https://github.com/mozilla/treeherder/pull/4077#issuecomment-425909898
=> Revert "Bug 1494665 - Open interactive tasks in a new tab after triggering (#4077)"

ui/test-view/ui/Test.jsx
The ``Link`` component presumes it's part of the same domain.  So we should just use the helper function to get the url.
=> Bug 1493881 - Fix test-view bug links

ui/job-view/JobView.jsx
I used to get the ``revision`` and ``selectedJob`` from angular as props.  When I made the ``SelectedJob`` context, I stopped doing so for both.  But I neglected to then get the ``revision`` from the URL.  This PR now does so.
=> Bug 1451492 - Fix wording awaiting a new revision

.travis.yml
1. **Switch Python 3 job to GCE infrastructure**
Since we need MySQL to be running, and it's no longer started by default in the non-GCE Docker images:
travis-ci/travis-cookbooks#988 (comment)
2. **Re-order job matrix/adjust naming**
The Python 3 sub-job runs more than just linters, so the old name was not correct. The comments have been removed since they mostly duplicate the name in `env`.
=> Bug 1495520 - Travis: Fix MySQL connection errors

tests/ui/unit/react/groups.tests.jsx, ui/helpers/job.js, ui/job-view/context/SelectedJob.jsx, ui/job-view/pushes/JobGroup.jsx
This solves the problem by ensuring that, if the job's group is expanded before we look for it.  It's possible the job is collapsed into a count like ``+5``.  Then we'll be able to find the job DOM element, and select it.
=> Bug 1494667 - Fix selecting job within count on page load

ui/job-view/details/summary/ActionBar.jsx
I was getting the status on page load.  But I should get it at the time the event is fired instead.
=> Bug 1495858 - Fix logviewer hotkey

treeherder/intermittents_commenter/commenter.py
Update max number of bugs that can be retrieved at a time via bugzilla (in fetch_all_bug_details). This seems to have changed from last Monday where we were able to fetch 1200 bugs at a time (and there were 1200+ comments). I'll be investigating further.
=> Bug 1497306 - fix intermittents commenter

ui/helpers/constants.js, ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx, ui/job-view/details/tabs/autoclassify/ErrorLine.jsx
These are several autoclassify events that were used only from keyboard shortcuts.  This removes the events and the handlers for them.  Either only ``$emit``ed, or only consumed.  So they're no no-ops.
There is one event left: ``autoclassifyIgnore`` which is both ``$emit``ed and consumed, so I'll address that in a separate PR.
=> Remove unused autoclassify events

ui/helpers/job.js, ui/job-view/context/Pushes.jsx, ui/job-view/context/SelectedJob.jsx, ui/job-view/pushes/Push.jsx
This also has a related fix when a job that's selected is within a job group count.  We won't be able to find the job element to scroll it into view.  So we look for the group instead.
=> Bug 1498139 - Fix when selected job is out of push range

ui/intermittent-failures/DropdownMenuItems.jsx, ui/intermittent-failures/Graph.jsx, ui/intermittent-failures/Navigation.jsx, ui/intermittent-failures/View.jsx
I didn't see a compelling use case for getDerivedStateFromProps. It didn't seem to improve performance in `View` compared to componentDidUpdate and added unnecessary complexity, so I didn't use it.
=> Bug 1483419 - remove componentWillReceiveProps in IFV

ui/job-view/pushes/JobGroup.jsx
This is another case where it we're not getting bound to ``this`` properly.  I've been blaming these on possible oddness with ``react2angular``.  I'm still of the opinion that that's the case.  When we move to a pure React app, then we can move these to the ``constructor``.  That's https://bugzilla.mozilla.org/show_bug.cgi?id=1480166.
=> Bug 1498275 - Fix expanding runnable job counts

ui/intermittent-failures/View.jsx
I accidentally left out the proper querystring param `page_size` during the redux removal. Tested it locally.
=> Change pageSize query param back to page_size

treeherder/webapp/api/serializers.py, ui/intermittent-failures/BugDetailsView.jsx
I've removed build type and platform from the test suite field string and refactored the regex. I've looked at a few different bugs to ensure this looked good. @jmaher could you also take a look and confirm this still captures the required info? If you want to test it, I'll probably have to push to prototype unless you're using a mirror of the prod db (so there's enough data in the BugJobMap model).
=> Bug 1496115 - Improve IFV bug details test suite field

neutrino-custom/base.js, package.json, ui/js/logviewer.js, ui/js/treeherder.js, ui/js/treeherder_app.js, yarn.lock
The ``ngRoute`` was messing with our browser history since we're no longer using ``$location`` to modify the URL.  So removing that fixed the bug.
But I also found several other angular components that are vestigial and can be removed.
=> Bug 1498076 - Fix browser back button

ui/job-view/JobView.jsx, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx, ui/job-view/details/tabs/autoclassify/ErrorLine.jsx
Sits on top of PR #4142
There were a few places where we were still looking to ``$rootScope`` for ``repoName``, ``filterModel`` and ``currentRepo``.  We don't need those anymore.  Though ``MainCtrl`` still needs a couple values from react for the window title.  So still need to set ``currentRepo`` and ``firstPush``.
=> Bug 1499141 - Convert repoName to react

ui/models/filter.js
I need to ``cloneDeep`` the defaults object, or we end up modifying it while making changes (like checking tier-3).  That results in setting the ``defaults`` to tier 1,2,3 and comparing our current state of tier=1,2,3 means, "oh, we should just remove that param, because we match defaults."  I could have made ``addFilter`` and ``removeFilter`` ensure they don't modify the current value, instead creating a new value.  But this seems like it removes the possibility of a foot-gun.  
Happy to go that route, if preferred.  But some of these ``lodash`` functions ARE pretty nice, imo.  :)
=> Bug 1498835 - Fix toggling tier-3

ui/helpers/autoclassify.jsx, ui/job-view/details/DetailsPanel.jsx, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/js/models/perf/alerts.js, ui/models/taskcluster.js
There were just a few files left that had global ``lodash`` imports.  We may still choose to convert them to native ES6, but at least this will allow tree-shaking until that time.
=> Bug 1466494 - Convert global lodash imports to specific imports

ui/css/treeherder-global.css, ui/index.html, ui/job-view/JobView.jsx
When I changed the ``index.html`` for the on-screen overlay of the shortcuts, I changed the hierarchy of elements.  This ended up with the ``CSS`` for ``height: calc()`` in the wrong place.
=> Fix window scroll-height

ui/job-view/context/Pushes.jsx, ui/job-view/pushes/Push.jsx
This appears to fix the memory leak issue in local testing.
I also, while trying to track this down, found a bug with the ``nojobs`` param.  So the second commit addresses that.
=> Bug 1499551 - Fix memory leak when loading new pushes

neutrino-custom/base.js, ui/entry-perf.js, ui/helpers/auth.js, ui/job-view/headerbars/PrimaryNavBar.jsx, ui/js/perf.js, ui/login-callback/LoginCallback.jsx, ui/login-callback/index.jsx, ui/shared/auth/AuthService.js, ui/shared/auth/Login.jsx
This moves the auth code out of the ``/js`` folder:
1. Moved ``auth-utils`` into the ``/helpers`` folder
2. Moved the ``LoginCallback`` to its own app folder like the other apps.  And followed the pattern of the other apps with an ``index.jsx``.
=> Move auth folder to shared folder

ui/intermittent-failures/DateOptions.jsx
Update `endday` with current date when selecting a date option (i.e. 'last 7 days'). Tested it locally.
=> Bug 1500056 - update endday in bugdetails view

ui/helpers/constants.js, ui/job-view/context/Pushes.jsx, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/Push.jsx
This PR switches polling for jobs from each ``Push`` to the ``Pushes`` context.  Then it sends an event with the new jobs, and each ``Push`` listens to that event.
I am experimenting with the idea of fetching the jobs in the ``Pushes`` context, or possibly ``PushList`` and passing that to each ``Push`` as a prop.  But there are issues with re-rendering too much.  So for now, this is a smaller change that simply updates the jobs each push already fetched.
I briefly looked into switching to GraphQL for fetching these jobs, but it will involve changing the way we parse the jobs data.  I think it is worth exploring in a separate PR.
=> Bug 1501682 - Poll for new jobs on all pushes at once

bin/pre_deploy
To work around the intermittent MySQL deadlocks encountered during a small percentage of deployments. This will ensure deployments don't cause email spam to app collaborators and Heroku admins, as well as saving us from having to manually retry the release each time it occurs.
The `IGNORE_PREDEPLOY_ERRORS` option has also been removed, since it's mostly redundant with `SKIP_PREDEPLOY`.
=> Bug 1428031 - Heroku: Retry load_initial_data up to 5 times

ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/PushHeader.jsx, ui/login-callback/LoginCallback.jsx, ui/test-view/ui/Groups.jsx
I didn't remove the ordering rules from ``lint.js`` for these functions.  Happy to do so, if that makes more sense.  But seems like it's correct to keep them until React 17?  :)
=> Bug 1451171 - Transition away from unsafe lifecycle functions

bin/pre_deploy
Since there was still a deploy failure after five attempts here:
https://dashboard.heroku.com/apps/treeherder-prototype/activity/releases/2847
=> Bug 1428031 - Heroku: Increase max load_initial_data retries to 10

requirements/dev.txt, setup.cfg, tests/settings.py, treeherder/intermittents_commenter/commenter.py, treeherder/webapp/graphql/schema.py
http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html
https://github.com/PyCQA/pycodestyle/blob/2.4.0/CHANGES.txt#L4
https://github.com/PyCQA/pyflakes/blob/2.0.0/NEWS.txt#L1
Also:
* Switches from the `ignore` setting to the new `extend_ignore`, which doesn't overwrite the default ignore list, meaning we no longer have to duplicate it ourselves.
* Remove the rarely used `[pycodestyle]` config section, since it's only used when using tools like autopep8, which should really learn to use the `[flake8]` section themselves.
* Enables the previously ignored F403 and F405 rules, adding `# noqa` entries to instances that we do not wish to fix.
* Adjust max line length down to 100, since we already disable the `E501: line too long` rule, making the length mostly redundant other than in IDEs, …
=> Bug 1502288 - Update flake8, pycodestyle and pyflakes

docs/backend_tasks.md, setup.cfg, tests/selenium/conftest.py
* Enables the display of skipped test/expected fail reasons, in the pytest summary.
* Skips the Selenium tests with a clear reason message, unless the built UI is found (preventing the annoying/confusing test timeouts).
* Removes the disabling of the `pytest-html` and `pytest-metadata` plugins, since they are required when passing the `--html` option to generate an HTML report.
* Updates the docs to mention `yarn build` and `--html`.
=> Bug 1502306 - Make it easier to run Selenium tests

ui/helpers/job.js, ui/helpers/url.js, ui/job-view/CustomJobActions.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/summary/SummaryPanel.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/models/jobLogUrl.js, ui/shared/JobDetails.jsx, ui/shared/JobInfo.jsx
This moves the bottom-left list of details to a shared ``JobInfo`` component that can be used in the ``LogViewer`` as that gets converted.
I also removed creating the ``buildUrl`` field in the ``JobLogUrlModel``.  It can get accessed by the task inspector better.  The url it generated was a 404 anyway...   :)
Along those lines, I removed the ``machineName`` field.  iirc, that machine name is auto-generated, so really doesn't provide value.  And the user can get to it through the task inspector anyway.  But if I've gone too far, I'll revert that.  :)
=> Bug 1450045 - Create a shared JobInfo component

newrelic.ini
Since we now run them as Django management commands (rather than scheduled Celery tasks), which New Relic only instruments if explicitly instructed.
=> Bug 1503576 - New Relic: Instrument cycle_data & update_bugscache

ui/job-view/context/Pushes.jsx, ui/job-view/context/SelectedJob.jsx, ui/job-view/details/DetailsPanel.jsx, ui/job-view/pushes/Push.jsx
If the ``selectedJob`` is in state ``running`` and we poll for new jobs and that job is now ``completed``, the ``DetailsPanel`` doesn't update to reflect that, even though the job field does.  This fixes that issue.
=> Fix updating details if selectedJob is updated

bin/travis-setup.sh
Since the service is no longer started by default in the base Travis image as of travis-ci/travis-cookbooks#999.
Fixes:
```
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
(eg https://travis-ci.org/mozilla/treeherder/jobs/450605269#L880)
=> Bug 1504617 - Travis: Explicitly start redis-server

.travis.yml
Since all jobs are now being run on the GCE infra now, regardless of what the option is set to:
https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
=> Travis: Remove deprecated `sudo` option

treeherder/model/fixtures/repository.json, treeherder/model/fixtures/repository_group.json, ui/job-view/headerbars/ReposMenu.jsx
For Servo CI we’re starting to move to Taskcluster. Treeherder seems like a nice way to visualize which tasks have succeeded or failed. https://treeherder.mozilla.org/#/jobs?repo=servo already exists, but as far as I can tell only shows commits in / pushes to the `master` branch. Testing happens in the `auto` (and `try`) branch, before merging into `master`.
=> Add more branches for the Servo repository

ui/intermittent-failures/BugDetailsView.jsx
Since the failuresbybug API changed to deliver all results with no pagination (and the
associated meta went away) for the table sorting in #4178, the bug count needed to be changed to tableData.length from tableData.count
=> Bug 1506856 - fix IFV bug details count

ui/perf.html
The Perfherder equivalent of #4262 since the changes there only affected auto-generated HTML, but Perfherder still uses its own custom HTML template (until the React conversion is finished).
=> Bug 1505417 - Remove viewport meta tag for Perfherder too

ui/logviewer/App.jsx, ui/logviewer/Navigation.jsx, ui/shared/JobInfo.jsx
As-per Ed's suggestion, this adds a navbar button to get to the original job and removes the link to filter by that job type from the ``JobInfo`` component.
So it now looks like this:
=> Bug 1506633 - Fix Logviewer links to original job in Treeherder

tests/ui/unit/react/revisions.tests.jsx, ui/job-view/App.jsx, ui/job-view/context/SelectedJob.jsx, ui/job-view/pushes/JobsAndGroups.jsx, ui/job-view/pushes/Platform.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx, ui/job-view/pushes/PushJobs.jsx, ui/job-view/pushes/PushList.jsx, ui/job-view/pushes/Revision.jsx, ui/job-view/pushes/RevisionList.jsx
The whole ``data-job-clear-on-click`` property is a cumbersome footgun.  This new logic should handle all the cases in a much simpler way.  I don't think I missed any use-cases, but since those are "famous last words" way too often, I'll deploy this branch to prototype and ask the sheriffs if they can give it a try.
=> Bug 1506424 - Fix logic to unselect job by clicking open areas

ui/job-view/KeyboardShortcuts.jsx, ui/job-view/headerbars/NotificationsMenu.jsx, ui/shared/NotificationList.jsx, ui/shared/context/Notifications.jsx
This makes the ``esc`` shortcut key clear any notifications, sticky or not.  If there is a ``selectedJob`` and notifications, then first ``esc`` will clear the notifications, and second will clear the selected job.
=> Bug 1505336 - Make notifications clear-able with esc

ui/helpers/url.js, ui/shared/JobDetails.jsx
The WPT viewer no longer seems to load correctly, so the link has been removed to prevent end-user confusion.
=> Bug 1507449 - Remove link to WPT viewer since it doesn't work

ui/intermittent-failures/DateRangePicker.jsx
The `timers` module is a Node.js built-in, which webpack will polyfill during the build. Using it adds `timers-browserify` to the bundle unnecessarily, given that browsers natively support `setTimeout`:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
(This import was presumably copied from a react-native code example.)
=> Bug 1472542 - Use native setTimeout rather than via a polyfill

.prettierignore
For:
* generated directories such as `build/`
* filetypes that are supported by Prettier, but that we haven't yet converted to its style (eg CSS, HTML, JSON, YAML)
These entries are not needed when running Prettier via ESLint, but help prevent the "format on save" feature of IDE prettier plugins from auto-formatting files when making unrelated changes to them.
As and when we use Prettier with more filetypes, these can be removed.
=> Bug 1507172 - Add additional .prettierignore entries

ui/helpers/http.js
Change response header to account for additional info such as the utf charset when checking for errors.
I've noticed that occasionally the IFV spinner would get stuck the first time loading the page for the day and found that the exact string match for the header content was insufficient since "text/html; charset=utf-8" is returned for the 503 instead of just "text/html".
=> Fix getData helper

.gitignore, .neutrinorc.js, .prettierignore, Makefile, bin/post_compile, docs/conf.py, setup.cfg, treeherder/config/settings.py
So that their purposes are clearer and it's easier to differentiate between generated content and files committed to the repository.
* Neutrino build: `build/` -> `.build/`
* Sphinx build: `_build/` -> `.build-docs/`
* Django collectstatic: `treeherder/static/` -> `.django-static/`
(The naming then aligns with `.pytest_cache/`, `.vagrant/`, `.vscode/` etc)
=> Clean up the location of generated output directories

ui/job-view/details/DetailsPanel.jsx
This was happening because the specific job in question was the newest job on that page.  And we poll for that >= the timestamp of the latest job.  So each poll, that job was always returned.  That's not a problem, except that in ``DetailsPanel`` we were checking if we should reload the details panel by object (``oldjob !== newjob``) instead of the values that we care about.  This fixes it so that we just check the things that would change in the job: ``state``, ``result``, ``failure_classification_id``.
So the details will reload if any of those fields change, which is the correct thing to do.
=> Bug 1507808 - Fix job details reloading for specific job

ui/job-view/App.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx
This adds the ability to collapse pushes.  The collapsed pushes are persisted on the URL so that the links can be shared.
This obviously isn't the whole solution to paging and memory usage, but I still feel like this is a worthwhile feature to help reduce noise in certain circumstances.
Expanded push:
Collapsed push:
=> Bug 1502147 - Add ability to collapse pushes

package.json, yarn.lock
The last usage was removed in #4107 ([bug 1485226](https://bugzilla.mozilla.org/show_bug.cgi?id=1485226)).
=> Remove unused redux-thunk dependency

.neutrinorc.js, package.json, yarn.lock
* React prop-types are now stripped from the bundle in production (since they are only used by React in development), reducing bundle size.
* react-hot-loader's Babel plugin is now enabled in production too, which is the first piece for fixing bug 1507906.
* `@neutrinojs/eslint` now configures `emitWarning` itself, so our customising is no longer required.
* `@neutrinojs/devServer` now enabled `overlay` itself, so we do not need to do so manually.
Full changelog:
https://github.com/neutrinojs/neutrino/compare/1c082ac...e9c21b8
=> Update Neutrino to 9.0.0-rc.0

ui/job-view/details/DetailsPanel.jsx
Embarrassing I missed this...  We were only updating ``DetailsPanel`` if the ``result``, ``state``, or ``failure_classification_id`` changed.  But that meant it didn't update if switching between jobs that had those values the same.  [facepalm...]  Now we also check the ``id``.  The other fields ARE important to check, in case the selected job got an update due to polling.
=> Bug 1510240 - Fix updating details panel when changing jobs

ui/job-view/context/PinnedJobs.jsx, ui/job-view/context/Pushes.jsx, ui/job-view/context/SelectedJob.jsx
Sits on top of the prior PR #4317.
This change seems to have a good impact on the memory leak when >50 pushes are loaded.
=> Bug 1480166 - Use class fields to avoid bind() calls in /context

ui/job-view/headerbars/WatchedRepo.jsx
This functionality is already covered by the outer ``ErrorBoundary``, so it's redundant.
=> Remove redundant error boundary in WatchedRepo

ui/job-view/pushes/PushLoadErrors.jsx
I discovered this when I was filtering on my own email.  I don't have any pushes, but it told me it was "a bad revision" which is clearly not right.  I HAD no revision specified.  So just needed to add that check.
=> Fix bad revision message when no revision filter in url

ui/job-view/headerbars/FiltersMenu.jsx, ui/job-view/headerbars/PrimaryNavBar.jsx
This came up in our brainstorm today and seemed trivial enough to just add it.
I'm not certain this is the right location.  It seemed right, but could possibly go under the ``Login`` menu when the user is logged in?  I'm open to suggestions.  This isn't terribly easy to discover, but adding another button to the navbar just adds that much more clutter.
=> Bug 1512262 - Add link to filter to pushes for current user

treeherder/etl/runnable_jobs.py
At the moment, Taskcluster is only publishing runnable-jobs.json.gz, but the plan at some point is to switch that to only publishing runnable-jobs.json, with no period of both artifacts being published.
Before the tc change can go through, then, consumers like Treeherder's "Add new jobs" feature need to be updated to try finding the new artifacts and fall back to the old one.
Once enough time has passed after everything changes over and all of the old gzipped artifacts expire, the fallback can be removed.
=> Bug 1494750 - (Part 1) Make Treeherder backend first attempt to find an uncompressed runnable-jobs.json

ui/job-view/App.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/headerbars/SecondaryNavBar.jsx, ui/job-view/headerbars/WatchedRepo.jsx, ui/job-view/pushes/Push.jsx
This is the rest of them in ``/job-view``.
And one cleanup, found a function named incorrectly.
=> Bug 1480166 - Use class fields to avoid bind() calls in App and /headerbars

treeherder/workers/task.py
Since it's unlikely to be a recoverable error.
=> Bug 1490741 - Don't retry tasks that fail with IndexError

.neutrinorc.js, jest.config.js
Since it's in `devDependencies` so is not installed during deploys.
Fixes:
`Error: Cannot find module '@neutrinojs/jest'`
https://dashboard.heroku.com/apps/treeherder-stage/activity/builds/8228fa8d-0209-43d3-8699-4e6c124b248f
=> Bug 1364045 - Don't load '@neutrinojs/jest' in production

ui/models/runnableJob.js
We needed to be returning ``JobModel`` instances which have this function, rather than raw objects.  I also changed this to use a ``reduce`` to make it a little more efficient.
This was broken by PR #4333.  So I'll revert to just before that commit on prod.
=> Bug 1513902 - Fix filtering with add new jobs

ui/helpers/filter.js, ui/job-view/App.jsx, ui/job-view/headerbars/PrimaryNavBar.jsx, ui/job-view/headerbars/SecondaryNavBar.jsx
This fixes when url changes are made that should not cause re-rendering in the ``App``.  It used to be you could add a url param of ``foo=bar`` and it would cause the page to re-render (the virtual DOM would catch most of it before actual paint, though).  This is pretty unlikely, but it meant that pertinent URL changes that should re-render SOME things are re-rendering ALL things.  ``selectedJob`` is an example.  Changing that param is still re-rendering too much, but we need this fix in before we can address it in the ``selectedJob`` context.
=> Bug 1501984 - Fix too much re-rendering in App for url changes

package.json, tests/ui/unit/context/pushes.tests.jsx, tests/ui/unit/models/jobs.tests.js, tests/ui/unit/react/groups.tests.jsx
Since it's unnecessary given that we now have the ability to import JSON directly, and the current usage is causing ESLint warnings like:
```
warning: Illegal usage of jasmine global (jest/no-jasmine-globals) at tests/ui/unit/context/pushes.tests.jsx:15:5:
13 |
14 |   beforeEach(() => {
> 15 |     jasmine.getJSONFixtures().fixturesPath = 'base/tests/ui/mock';
|     ^
16 |
17 |     fetchMock.get(
18 |       getProjectUrl('/resultset/?full=true&count=10', repoName),
```
This means the only `jasmine-jquery` feature we're now using is the `toHaveLength` matcher, so use of `jasmine-jquery` can be dropped entirely once the tests are migrated to Jest, which supports `toHaveLength` natively.
Since otherwise any rules marked as level `warning` do not cause ESLint to exit with a non-zero exit code.
=> Bug 1514720 - Fix ESLint 'Illegal usage of jasmine global' warnings

ui/perfherder/SelectorCard.jsx
After a user selects a new project from the dropdown,
disable revision button until new data returns
I've tested the change locally and it works nicely.
=> Perfherder comparechooser button change

ui/helpers/aggregateId.js, ui/job-view/context/SelectedJob.jsx
This logic in ``SelectedJob`` was primarily for page load job selection.  But the same code is used when clicking a job to select it.  So now we only expand the group if we can't find the job we're looking for.  It would of course always find the job if the user actually clicked it.
While testing, I hit a bug where it didn't expand the right group.  I realized we didn't have the right number of params in ``getGroupMapKey``.  All the callers had all 5 params, but since the func def only had 4, it was dropping the last item of ``plOpt``. and there were cases where only the ``opt`` was difference, so it picked the first group rather than the correct one.
=> Bug 1512656 - Fix unexpected group count expansion

.eslintrc.js, tests/ui/unit/react/groups.tests.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/job-view/details/tabs/autoclassify/AutoclassifyToolbar.jsx, ui/job-view/details/tabs/autoclassify/LineOption.jsx, ui/job-view/details/tabs/autoclassify/StaticLineOption.jsx, ui/job-view/details/tabs/failureSummary/BugListItem.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/headerbars/FiltersMenu.jsx, ui/job-view/headerbars/HelpMenu.jsx, ui/job-view/headerbars/InfraMenu.jsx, ui/job-view/headerbars/NotificationsMenu.jsx, ui/job-view/headerbars/ReposMenu.jsx, ui/job-view/headerbars/WatchedRepo.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobCount.jsx, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/PushHeader.jsx, ui/shared/NotificationList.jsx, ui/shared/auth/Login.jsx, ui/userguide/UserGuideBody.jsx
I'm not quite certain why the type of ``reset`` was flagged by the linter in ``ui/job-view/headerbars/ActiveFilters.jsx``.  But it's kind of irrelevant since this wasn't a real form that we're submitting.  So I just switched it to "button".
Also: The ``JobGroup`` tests were way too brittle.  They broke here, and I've had to update them several times when making html changes.  So this makes them test just what matters.
=> Bug 1513601 - Fix/enable ESLint 'react/button-has-type'

ui/perfherder/SelectorCard.jsx
During testing I found the `validateInput` wasn't working as expected. With the onBlur this function will only be called if you select "something". So if that something is the compare button, it means you have to select it twice to actually navigate (once to validate and reset disableButton, and the second to navigate). This only happens if you paste a valid revision directly into the input. Removing this entirely until I have more time to rework it (it will still show an error message if the New revision input is blank). I also might try to incorporate one of Cam's suggestion (in #4388).
=>  Perherder compareChooser - remove input validation

requirements/common.txt
Since it's not compatible with Django <2.1 - see:
https://github.com/mozilla/treeherder/pull/4342#issuecomment-444888366
Bug 1517253 is filed for updating it once we're using newer Django.
Closes #4342.
=> Add pyup ignore marker for mysqlclient 1.3.14+

tests/ui/unit/react/bugfiler.tests.jsx, ui/helpers/job.js
Wrench jobs are a job type for the standalone WebRender test suite, and
run reftests as part of the job. Having reftest-ish things like the
reftest analyzer links for these jobs is desirable.
=> Bug 1517264 - Treat wrench jobs as reftests.

.yarnrc
Since:
- most are not actually required
- they often don't work with --no-bin-links (the bin scripts called may not exist)
- they cause Yarn to "unplug" the package when using the "Plug and Play" feature
- it's more secure to not run arbitrary code during package installation
Fixes the failures seen in #4418.
=> Don't run preinstall/install/postinstall hooks during yarn install

requirements/docs.txt
There has finally been a new release of recommonmark, so we no longer need to install directly from its GitHub repository. This also solves the issue of constant cache churn seen on Travis (due to usage of pip editable mode).
=> Update to recommonmark 0.5.0

tests/selenium/pages/base.py, ui/intermittent-failures/Navigation.jsx, ui/intermittent-failures/index.jsx, ui/js/perf.js, ui/perf.html, ui/shared/LogoMenu.jsx
This ensures consistency between all the apps.  
We converted ``LogoMenu`` to Reactstrap, rather than generic Bootstrap and added its use to IFV.
I had to tweak the Selenium tests and ``LogoMenu`` itself a bit to get the tests working.
Closes #4380.
=> Bug 1514668 - Use shared LogoMenu across IFV and Perfherder

ui/perf.html
This fixes how the ``LogoMenu`` is laid out with the rest of the Perfherder navbar.  I didn't notice this before merge.  It may be that the branch wasn't up-to-date with the latest bootstrap or some other change.  So when it got rebased, they didn't play well together.  Anyway, here's the easy-fix.  :)
=> Bug 1514668 - Fix perfherder navbar layout with bootstrap

ui/job-view/pushes/PushHeader.jsx
I noticed a small bug with my earlier change.  If you log in or out, the menu availability on "add new jobs", etc does not update.  This fixes that.  I also added destructuring on ``prevProps``
=> Bug 1501984 - Fix menu availability on login/out

ui/job-view/pushes/PushHeader.jsx
I unfortunately hadn't tested this enough.
I'm working on adding a few Jest tests in a separate branch.  But I'm hitting an import error.  It MAY be due to the circular references in imports.  So I submitted a fix to the ``import/no-cycle`` eslint rule.  I'll continue with that branch in a separate PR, so that we can get this fix in.
=> Bug 1519508 - Fix PushHeader not updating for add new jobs

tests/ui/unit/context/pushes.tests.jsx, tests/ui/unit/models/jobs.tests.js, ui/helpers/job.js, ui/helpers/location.js, ui/helpers/url.js, ui/job-view/details/tabs/autoclassify/AutoclassifyTab.jsx, ui/job-view/headerbars/ReposMenu.jsx, ui/job-view/headerbars/WatchedRepo.jsx, ui/models/bugJobMap.js, ui/models/bugSuggestions.js, ui/models/classification.js, ui/models/job.js, ui/models/jobLogUrl.js, ui/models/perfSeries.js, ui/models/push.js, ui/models/runnableJob.js, ui/models/textLogStep.js, ui/perfherder/CompareSelectorView.jsx, ui/perfherder/SelectorCard.jsx, ui/shared/JobInfo.jsx, ui/test-view/redux/configureStore.js
This really only required moving a handful of functions from ``helpers/url`` to ``helpers/location`` and then one to ``helpers/job``.  But since they were imported in so many places, it makes for a lot of noise.
=> Bug 1493833 - Fix ESLint errors with import/no-cycle

ui/perfherder/CompareSelectorView.jsx, ui/perfherder/SelectorCard.jsx
Add improved input validation back to selectorCard component and move query param validation to selectorCard
Tested locally... tried as many different combinations of interactions as I could think of. Let me know if I've missed something.
- I had to remove the input validation in #4390 because the behavior was not right. This pr replaces the onBlur with onChange and adds validation back in.
- Other improvements to the validation include adding a 'validating...' message and using the new bootstrap `valid` prop to show when a revision has been validated (only occurs when a user pastes in a revision, pastes in a revision and then selects another project/repo, or uses the newRevision or originalRevision query params). The lack of this information has resulted in confusion for the user (@wlach …
=> Bug 1519573 - Add Perfherder compareChooser input validation

ui/partials/perf/graphsctrl.html, ui/perfherder/helpers.js
Fixing a bug caused by the change to using signature_id instead of signature_hash in the `comparesubtest` view in #4414. I had neglected to make changes to the `comparesubtests` urls used in the Alerts view and Graph view tooltip.
=> Perfherder - change comparesubtests url to use signature id

.neutrinorc.js, package.json, ui/css/treeherder-navbar.css, ui/push-health/App.jsx, ui/push-health/Health.jsx, ui/push-health/Metric.jsx, ui/push-health/Navigation.jsx, ui/push-health/NotFound.jsx, ui/push-health/helpers.js, ui/push-health/index.jsx, ui/shared/auth/Login.jsx, yarn.lock
Here is the beginning of the prototype for the Push Health View.  It only has dummy data for now.  I'm sure the format will evolve as we start creating the API to give us some real data.
The bar at the top may be a bit obnoxious.  :)  It display red/yellow/green, based on the worst ``result``.  Perhaps a badge on the left or right that says, "pass", "fail", "indeterminate" would also work.  Or perhaps just the color bars on the left for each metric is enough.
I'm considering adding markdown support for the details items.  I'd like to support links there, but we could have a "url" field in the details, too.  They're just strings at the moment.
=> Bug 1521157 - Create a prototype for the Push Health View

ui/css/treeherder-details-panel.css
It looks like bootstrap's default button class (now?) sets the
default button color to dark grey, which is really hard to see against
the background of the job details panel. Fix this by resetting
the color to the default of the containing class.
=> Make job details panel close button visible again

.neutrinorc.js, tests/ui/unit/react/revisions_test.jsx, tests/ui/unit/test-setup.js
This adds a little bit of wiring for using ``Jest``.  Some of the other ``Karma`` tests are hitting an error with the ``taskcluster-client-web`` package.  But the revisions ones go through OK.
=> Bug 1364045 - Convert the revisions unit tests to Jest

.neutrinorc.js
Rats, I somehow missed the deprecation warning in the output when I rebased...  This fixes it.
=> Fix deprecation warning in jest setup

tests/ui/unit/context/pushes.tests.jsx, ui/helpers/url.js, ui/test-view/redux/modules/groups.js
This somehow never got switched over.
=> Switch front-end to use /push/ endpoint

ui/helpers/url.js, ui/job-view/pushes/PushActionMenu.jsx, ui/push-health/Health.jsx, ui/push-health/Metric.jsx, ui/push-health/Navigation.jsx, ui/push-health/TestFailure.jsx, ui/push-health/helpers.js, ui/push-health/index.jsx, ui/push-health/pushhealth.css
Per a chat with Joel, here is the initial take on data we would display for failed "Tests" metric.  I'm sure this will continue to evolve.
This also adds a menu item to the push action menu to access this view.  I went back and forth on whether to include this.  Open to opinions if you think it's better NOT to have the menu item included at this time:
Here's the new look of the page:
=> Bug 1521157 - Update dataset for unit tests

ui/job-view/context/PinnedJobs.jsx, ui/job-view/details/PinBoard.jsx
This moves the data for ``failureClassificationId`` and ``failureClassificationComment`` into the context for the pinboard so that the hotkey has access to clear it at the right time.
=> Bug 1508422 - Fix ctrl+shift+u not clearing classification details

ui/push-health/Metric.jsx
This makes use of the nicer ``Collapse`` reactstrap component.  Also added use of ``CardBody`` and ``Card`` to give a little outline around the detail content.  I thought it looked a bit nicer and would add some distinction between the overall "Confidence" and the per-line "Confidence".  Open to opinions on that.  :)
=> Bug 1521157 - Push Health make use of reactstrap Collapse component

tests/webapp/api/test_push_api.py, treeherder/etl/job_loader.py, treeherder/etl/jobs.py, treeherder/webapp/api/push.py
Check ``revision`` length to see if we don't need the ``__startswith`` for finding it.  If we DO need that, then report to New Relic that we hit a revision <40 chars.
=> Bug 1306707 - Search for push without startswith when 40 chars

package.json, ui/css/treeherder-loading-overlay.css, ui/css/treeherder-test-view.css, ui/entry-perf.js, ui/intermittent-failures/BugDetailsView.jsx, ui/intermittent-failures/DropdownMenuItems.jsx, ui/intermittent-failures/Layout.jsx, ui/intermittent-failures/index.jsx, ui/js/components/loading.js, ui/js/controllers/perf/alerts.js, ui/login-callback/LoginCallback.jsx, ui/login-callback/index.jsx, ui/logviewer/Navigation.jsx, ui/logviewer/index.jsx, ui/partials/perf/alertsctrl.html, ui/partials/perf/comparerror.html, ui/partials/perf/comparetable.html, ui/partials/perf/graphsctrl.html, ui/partials/perf/helpMenu.html, ui/partials/perf/testdatachooser.html, ui/perf.html, ui/perfherder/SelectorCard.jsx, ui/shared/auth/Login.jsx, ui/test-view/index.jsx, ui/test-view/ui/Groups.jsx, ui/test-view/ui/StatusNavbar.jsx, ui/test-view/ui/Test.jsx, yarn.lock
This continues on the work in #4475 of switching to Font Awesome v5 and using the React version over the manual CSS classes approach, since we're currently using a mixture of 3 different Font Awesome packages which isn't ideal since their stylesheets are not compatible with each other.
Before:
* Login callback / Test view / Intermittent failures view:
- Legacy `react-fontawesome`
* Logviewer:
- Font Awesome v4 web fonts
* Perfherder:
- combination of Font Awesome v4 web fonts and legacy `react-fontawesome`
After:
* Login callback / Test view / Intermittent failures view / Logviewer / User guide:
- Modern `react-fontawesome` (`@fortawesome/react-fontawesome`)
* Perfherder:
- combination of Font Awesome v5 SVG+JS and modern `react-fontawesome`
Unchanged:
* Push health / shared login …
=> Bug 1506805 - Upgrade to modern Font Awesome (Part 1)

ui/job-view/CustomJobActions.jsx
Doing so shaves 156KB off the minified index entrypoint (job-view), which is >10%. The reason the browser version is not used automatically is that the js-yaml package is missing the `browser` field from it's `package.json`.
See:
https://github.com/nodeca/js-yaml/pull/462
(which looks like it might be wontfix, hence adding the workaround here)
=> Bug 1525239 - Use the browser version of js-yaml not the node version

.dependabot/config.yml
Since it turns out the `ignored_updates` setting refers to the versions that should be ignored, rather than the versions that are safe (which is the opposite of pyup).
=> Bug 1525923 - Fix version ranges for Dependabot ignored_updates

treeherder/model/fixtures/repository.json
This needs to be deployed after the move [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1525368) takes place.
=> Bug 1525368: Update ci-{admin,config} repository paths.

.neutrinorc.js, tests/ui/unit/react/groups_test.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/JobsAndGroups.jsx
--WIP:
Trying to get these tests working with Jest is hitting an error with ``taskcluster-client-web``.  Talked to Dustin, and it appears to be an issue with the version of ``hawk`` that's getting installed with their package.  
Filed upstream bug https://bugzilla.mozilla.org/show_bug.cgi?id=1523376 to hopefully address this.
=> Bug 1364045 - Convert the groups unit tests to Jest

renovate.json
Unfortunately Renovate doesn't currently support setting a team alias as the reviewer (see renovatebot/renovate/issues/1908), but does support listing one or more users.
We could list both Sarah and Cameron, however GitHub doesn't cancel the other person's review once the first person has reviewed, so it seems easiest to just say that one person reviews JS dep updates (Renovate) and the other reviews Python deps (Dependabot).
I've also set labels to match the style configured for Dependabot.
=> Update Renovate config to set reviewer and labels

treeherder/config/settings.py
These Golang related User Agents are accessing only the site root and robots.txt, so safe to block. The ActiveData UA block can be removed, since ActiveData no longer makes requests to our API.
=> Bug 1524941 - Update list of blocked User Agents

ui/js/controllers/perf/compare.js, ui/perfherder/CompareTable.jsx
There was a bug in the subtests controller that was breaking the view when 'test metric' was included in the data. I consolidated duplicate logic in the test metric (should have done this right away as per Cam's suggestion in #4538, rather than waiting till I start converting this file next week). I think that helper function will get folded into a component to be used by both views, so leaving it in the compare.js file for now.
While there, I removed the 'title' prop that wasn't being used by the subtests view and isn't necessary and removed the redundant variable `noiseMetricTestName`.
=> Bug 1526339 - fix noise metric for subtests view 

vagrant/setup.sh
Recent Ubuntu package updates mean that a clean Vagrant provision was failing due to dpkg wanting an answer to the "which version of the config file would you like to keep" question, which fails when apt-get is run non-interactively.
To avoid such prompts we have to force dpkg to always pick one of the config file conflict resolution options -- in this case I've chosen to always use the new version of the config file (via `--force-confnew`), since we don't customise any system config files, so overwriting any existing ones is fine.
Fixes:
```
default: Setting up ubuntu-release-upgrader-core (1:18.04.30) ...
default: Configuration file '/etc/update-manager/release-upgrades'
default:  ==> Modified (by you or by a script) since installation.
default:  ==> Package distributor has shipped an …
```
=> Vagrant: Fix error during dist-upgrade due to conf file prompt

vagrant/setup.sh
Since the version in Vagrant should stay in sync with the version pre-installed on Travis, and Travis have since updated to 0.6.0.
See:
https://github.com/travis-ci/travis-cookbooks/blob/9595f0a5316a2bc9b15f1e8a07e58cd07b97167c/cookbooks/travis_build_environment/attributes/default.rb#L267-L270
https://travis-ci.org/mozilla/treeherder/jobs/491551123#L57
https://github.com/koalaman/shellcheck/blob/master/CHANGELOG.md#v060---2018-12-02
=> Vagrant: Update to shellcheck 0.6.0

vagrant/setup.sh
Since the Travis pre-installed pip is already v19.x.
See:
https://pip.pypa.io/en/stable/news/
=> Vagrant: Update pip to 19.02

tests/webapp/api/test_performance_alerts_api.py
Python 3's `filter()` now return iterators rather than list/..., so must be cast back to a `list()` if used in contexts where an iterator is not supported. However in this case `first` fulfils the goal more cleanly.
Fixes:
`TypeError: 'filter' object is not subscriptable`
=> Bug 1526682 - Remove Python 3 incompatible usage of filter()

treeherder/webapp/api/urls.py
They are identical other than name, and we no longer use `/resultset/`.
=> Bug 1526223 - Remove /resultset/ endpoint in favour of /push/

tests/intermittents_commenter/test_commenter.py, treeherder/intermittents_commenter/comment.template
* Switches from `.iteritems()` to `.items()` in the Jinja template.
* Removes an assert from `test_intermittents_commenter` that is redundant (due to `match_querystring=True`) and non-deterministic across Python versions (due to the query string params being affected by dict order).
=> Bug 1526764 - Make test_intermittents_commenter pass under Python 3

treeherder/webapp/api/bug.py
Python 3's `map()` returns an iterator rather than a list/..., which delays any `ValueError` until point of use, which is after the try-catch. As such it must be explicitly cast to a list to force its evaluation.
Prevents the following exception in `test_bug_job_map_bad_job_id`:
`ValueError: invalid literal for int() with base 10: 'aaaa'`
=> Bug 1526766 - Fix bug-job-map job_id error handling under Python 3

tests/etl/test_load_artifacts.py
Since by design `.encode()` returns bytes, whereas the test should be using a string. The goal of the encode seems to have been to handle unicode correctly, however that's now achieved via the use of:
`from __future__ import unicode_literals`
Fixes the following exception under Python 3:
`TypeError: Object of type bytes is not JSON serializable`
=> Bug 1526763 - Remove `.encode()` from test_load_non_ascii_textlog_errors

treeherder/services/elasticsearch/utils.py
Since this usage was added after the others were converted in #3418.
Fixes:
`AttributeError: 'dict' object has no attribute 'iteritems'`
=> Bug 1526657 - Make remaining .iteritems() usage Python 3 compatible

treeherder/etl/job_loader.py
Since `slugid.encode()` internally uses `base64.b64encode()` which returns bytes under Python 3:
https://docs.python.org/3/library/base64.html#base64.b64encode
Fixes the following exception during `test_job_transformation`:
`TypeError: Object of type bytes is not JSON serializable`
=> Bug 1526763 - Explicitly convert encoded task IDs back to a string

tests/etl/test_job_ingestion.py, tests/etl/test_perf_data_adapters.py, treeherder/etl/jobs.py, treeherder/etl/perf.py, treeherder/model/models.py
Since Python 3's hashlib's `.update()` must be passed bytes not unicode:
https://docs.python.org/3/library/hashlib.html#hash-algorithms
https://docs.python.org/3/library/hashlib.html#hashlib.hash.update
Fixes:
`TypeError: Unicode-objects must be encoded before hashing`
Additional test assertions have also been added to ensure the generated hashes did not change as a result of this. ([travis run prior to the code change](https://travis-ci.org/mozilla/treeherder/jobs/490914050))
=> Bug 1453967 - Ensure arguments passed to hashlib update() are bytes

ui/css/perf.css, ui/partials/perf/alertsctrl.html
Add CSS for progress bar colors and gt and ls symbols that was erroneously removed in #4538
=> Bug 1526909 - Perf alerts missing color indicators

ui/perfherder/CompareTableControls.jsx
I made a mistake interpreting the filter logic, implementing it so that once a filter is selected it's out of the default 'all results' mode and then ALL result metrics need to match the filter settings whereas it should actually be if one or more filters are selected, only look at those filters to see if the metrics match. This fixes that logic and renames the filter state to match the button labels ( hopefully this makes the code clearer).
=> Bug 1526550 - fix perfherder compare table filters

ui/perfherder/CompareTable.jsx, ui/perfherder/TableAverage.jsx
Found a case where the array of data supplied to the table's tooltipgraphs isn't assigned a default value of [] in the getResultsMap helper if it is in fact undefined. Added a default prop in TableAverage to account for it and conditional in the CompareTable.
=> Bug 1526944 - add default prop in TableAverage component

.dependabot/config.yml
Since it requires Python 3:
https://github.com/erikrose/more-itertools/releases/tag/6.0.0
Bug 1527336 has been filed to update it once we're using Python 3.
Closes #4626.
=> Dependabot: Add ignored_updates entry for more-itertools

.travis.yml
Since Celery/kombu don't yet support Python 3.7:
https://github.com/celery/celery/issues/4500
This isn't seen in tests due to bug 1349362.
=> Bug 1527020 - Travis: Use Python 3.6.8 instead of 3.7.2

ui/logviewer/App.jsx
Ends up this was the wrong param to use.  This caused the ``LazyLog`` to appear to scroll through the log from the beginning.
https://mozilla-frontend-infra.github.io/react-lazylog/
=> Bug 1525122 - Fix so log viewer more quickly jumps to selected line

tests/e2e/test_job_ingestion.py, tests/log_parser/test_job_artifact_builder.py, tests/log_parser/test_log_view_artifact_builder.py, tests/log_parser/test_performance_artifact_builder.py, tests/log_parser/test_tasks.py, tests/test_utils.py, treeherder/log_parser/artifactbuildercollection.py
1. **Explicitly `.decode()` streamed log lines**
Since the `request` package's `iter_lines()` returns bytes by default:
http://docs.python-requests.org/en/master/user/advanced/#streaming-requests
We cannot pass `decode_unicode=True` to `iter_lines()` since it splits on Unicode newlines (which can exist in test message output), so instead we manually `.decode()` each line before parsing it.
Fixes the following exception under Python 3:
`TypeError: a bytes-like object is required, not 'str'`
The test utility `load_exp()` had to be modified to no longer use append mode when opening the expected output JSON files, in order to fix:
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
2. **Remove no longer required use of `contextlib.closing()`**
Since `requests` has native …
=> Bug 1526743 - Make log parsing Python 3 compatible

Vagrantfile, bin/travis-setup.sh, docs/backend_tasks.md, tests/autoclassify/test_classify_failures.py, tests/log_parser/test_store_failure_lines.py, tests/model/test_cycle_data.py, tests/model/test_search.py, tests/webapp/api/test_text_log_error.py, treeherder/autoclassify/matchers.py, treeherder/config/settings.py, treeherder/config/utils.py, vagrant/env.sh, vagrant/setup.sh
To ensure the CI and local environments match stage/production (where Elasticsearch is not configured) and don't run differing code-paths due to the various `ELASTICSEARCH_URL` conditionals used in auto-classify.
At such time when work on the fuzzy auto-classify matcher continues, this can be reverted.
Several tests had to be updated to make them correctly handle `ELASTICSEARCH_URL` being unset.
=> Bug 1527868 - Vagrant/Travis: Remove Elasticsearch server

.neutrinorc.js
The current perfherder entrypoint size is right on the threshold, which causes failures when something marginally increases the bundle size (such as the duplicate deps that occur after a React update PR prior to the lockfile maintenance PR cleaning them up).
=> Increase maxEntrypointSize to avoid failures from duplicate deps

treeherder/perf/management/commands/reassign_perf_data.py
In the [initial push](https://bugzilla.mozilla.org/show_bug.cgi?id=1520417#c8) I didn't realize the sheer amount of Raptor tp6 tests we have. The old version of the `reassign_perf_data.py` script was written with the idea of supplying all old/new ids by hand, at the command line.
IRL that would mean typing in somewhere around 3000 pairs, which is not at all practical.
This update should fetch all these pairs via a raw query and then reuse existing logic to do the reassignment.
The use case is very specific to that of [bug 1520417](https://bugzilla.mozilla.org/show_bug.cgi?id=1520417).
=> Bug 1520417 - Rename raptor-tp6 subtests to remove redundant test name prefix

manage.py
Prevents:
```
kombu/five.py:20: DeprecationWarning: the imp module is deprecated in favour of importlib ...
markdown/util.py:453: DeprecationWarning: Using the add method to register a processor or pattern is deprecated ...
newrelic/api/import_hook.py:166: DeprecationWarning: Use importlib.util.find_spec() instead
```
=> Bug 1528485 - Suppress manage.py DeprecationWarnings from dependencies

.travis.yml, runtests.sh
Invalid comparisons between bytes and strings will now cause the tests to fail, making it easier to spot bugs that would appear under Python 3.
If there are any false positives in the future, the errors can be suppressed using `filterwarnings` in `setup.cfg`.
See:
https://docs.python.org/3.6/using/cmdline.html#cmdoption-b
https://docs.python.org/3.6/library/exceptions.html#BytesWarning
=> Bug 1528601 - Surface 'BytesWarning's and make them fail the tests

tests/client/test_treeherder_client.py, treeherder/client/thclient/client.py
* `get_resultsets()` has been deprecated for some time
* the other methods being removed are for API endpoints that no longer exist after #3222 (bug 1437968)
=> Bug 1528833 - Remove obsolete TreeherderClient methods

treeherder/client/setup.py, treeherder/client/thclient/client.py
Changes:
* The deprecated `TreeherderClient.get_resultsets()` has been removed. Use the otherwise identical `TreeherderClient.get_pushes()` instead.
* Functionality related to submitting jobs has been removed, now that
Treeherder's REST API no longer supports it (bug 1349182):
- `TreeherderClient`'s constructor no longer accepts the `client_id` and `secret` arguments.
- `TreeherderClient.post_collection()` has been removed.
- The `TreeherderJobCollection`, `TreeherderCollection`, `TreeherderJob`, `TreeherderData` and `ValidatorMixin` classes have been removed.
- `treeherder-client` no longer depends on the `requests-hawk` package.
* The `TreeherderClient` methods `get_products()`, `get_job_groups()`, `get_build_platforms()`, `get_job_types()`, `get_machines()` and …
=> Bug 1529191 - treeherder-client: Bump version to 5.0.0

.dependabot/config.yml, requirements/common.txt
The backwards-incompatible change has since been fixed, so the latest version now works with Django 1.11 again, avoiding the test failures seen in #4342.
https://github.com/PyMySQL/mysqlclient-python/blob/master/HISTORY.rst#whats-new-in-142
=> Bug 1517253 - Update mysqlclient from 1.3.13 to 1.4.2.post1

ui/css/treeherder-global.css, ui/intermittent-failures/Layout.jsx, ui/perfherder/CompareSelectorView.jsx, ui/perfherder/CompareTable.jsx, ui/perfherder/SelectorCard.jsx
In preparation for implementation of [CSP policy](https://bugzilla.mozilla.org/show_bug.cgi?id=1270157), replace inline styles with bootstrap utility classes and custom classes.
Bootstrap doesn't appear to have width utility classes (only width controls as they pertain to the grid syntax and using a col-1 is too large for several of the compare table column contents, so I went with custom css classes).
=> Remove inline styles from new Perfherder/IFV components

tests/settings.py, tests/test_middleware.py, tests/webapp/api/test_csp_report.py, treeherder/middleware.py, treeherder/webapp/api/csp_report.py, treeherder/webapp/api/urls.py, ui/css/intermittent-failures.css, ui/entry-perf.js, ui/perf.html
This adds a `Content-Security-Policy-Report-Only` header for static assets served by WhiteNoise (such as our frontend), which includes a first pass at a possible policy that should work for Treeherder.
The header also includes a `report-uri` directive, which points at a newly added API for collecting CSP violation reports. Reports are logged as warnings (so will appear in Papertrail) and sent to New Relic as a custom event. This will allow us to see whether the policy would block valid requests, so we can refine it prior to converting to the real (ie blocks things) `Content-Security-Policy` header.
The addition of `ng-csp` to `perf.html` is to enable AngularJS's ngCSP feature, which turns off use of `eval()` and automatic stylesheet injection, so that the policy directives `unsafe-eval` …
=> Bug 1270157 - Add a report-only CSP header and report collection API

tests/test_middleware.py, treeherder/middleware.py, treeherder/webapp/api/csp_report.py, treeherder/webapp/api/urls.py
1) Makes the following changes to the initial report-only CSP header added in #4678:
* Adds a `frame-src` directive
Whilst the Auth0 domain is already whitelisted in `connect-src` allowing initial logins to work, Auth0.js renewals are performed in an iframe, so need both the auth0 domain and `'self'` (for the `/login.html` callback) to be permitted via `frame-src`.
* Adds https://taskcluster-artifacts.net to `connect-src`
Since some requests to `queue.taskcluster.net` redirect to it (eg for the "Add new jobs" feature), and for redirects both the original and new domain need whitelisting.
* Adds `'report-sample'` to `script-src` and `style-src`, which makes the browser send JS/CSS samples for any violations of the "inline" rules, making it easier to debug collected CSP violation reports. …
=> Bug 1270157 - Content-Security-Policy-Report-Only Adjustments

setup.cfg, tests/auth/test_backends.py, tests/webapp/api/test_auth.py, treeherder/auth/backends.py
The id token payload contains an `exp` property, which is an integer representing the number of seconds past the epoch at which the id token expires:
https://openid.net/specs/openid-connect-core-1_0.html#IDToken
However the mocked value in our authentication tests was the string `'500'`, which is neither the correct data type, nor a timestamp. This meant that during tests only, the `min(accesstoken_exp_in_ms, idtoken_exp_in_ms)` in `AuthBackend.authenticate()` was comparing an int and a string, which under Python 3 results in:
`TypeError: '<' not supported between instances of 'str' and 'int'`
A later bug/PR will refactor the auth backend to fix issues unrelated to Python 3 compatibility and add more test coverage.
=> Bug 1453837 - Use correct value for id token expiry in auth tests

package.json, tests/ui/unit/react/compare_table_test.jsx, tests/ui/unit/test-setup.js, ui/perfherder/CompareTableControls.jsx, ui/perfherder/InputFilter.jsx, ui/perfherder/constants.js, yarn.lock
This is only testing the filtering buttons and filter input logic and does not include a thorough set of test cases (I'm wondering if this should be done as some sort of separate unit test with just the filtering functions or if this is sufficient - thoughts?). More to come when I work on the compare view and compare subtest views. 
If you'd like these tests organized differently (broken out into additional tests), lmk.
FYI @ionutgoldan this is what testing components would look like using this library and jest utlities.
=> Add tests for Perfherder's compare table using react-testing-library

.dependabot/config.yml, requirements/dev.txt
The new version has dropped support for Python 2, so this was previously blocked on bug 1330474.
Changes:
https://github.com/erikrose/more-itertools/blob/6.0.0/docs/versions.rst#600
=> Bug 1527336 - Update more-itertools from 5.0.0 to 6.0.0

docs/installation.md, tests/test_middleware.py, treeherder/middleware.py, ui/helpers/url.js
The latest policy used in the report-only header has been working well on production (the violation reports [logged to New Relic](https://insights.newrelic.com/accounts/677903/explorer/events?eventType=CSP%20violation&duration=604800000) are only from scripts injected by browser addons), so we're ready to start enforcing the policy by using the real `Content-Security-Policy` header name.
NB: When features are added in the future, PR authors and reviewers will need to remember to update the policy if needed (for example to add domains to the `connect-src` directive). The CSP header is not enabled when using `webpack-dev-server` (it would break dev source maps and react-hot-loader) so if in doubt test locally (using `yarn build` and serving via Django runserver) or on prototype first.
See: …
=> Bug 1270157 - Convert the report-only CSP header to the real thing

tests/test_middleware.py, treeherder/middleware.py
Unfortunately the "Custom Actions" usage of `ajv.compile()` requires that the `script-src` CSP directive contain `'unsafe-eval'`, otherwise the whole feature breaks.
Using `'unsafe-eval'` defeats much of the point of CSP, so it should be removed as soon as possible. Bug 1530607 is filed to track.
CC @helfi92
=> Bug 1530602 - Adjust Content-Security-Policy to fix ajv.compile()

treeherder/webapp/api/performance_serializers.py
When using django-rest-framework's `ModelSerializer`, automatic validation rules are created for different types of API requests. Since `PUT` requests are meant to be for full updates of an object, these automatic validation rules for such requests are configured to enforce all non-optional fields.
The `is_regression` field doesn't have a `default`, and so would normally be treated as required for `PUT`s, except that in Django prior to 2.1 `BooleanField`s had an implicit `blank=True` set within Django, meaning django-rest-framework's validator treated them as optional.
As such, the current performance alert API implementation has been able to use `PUT`s for partial updates (updates where only some fields are specified), even though it really should have been using `PATCH` instead.
However …
=> Bug 1530502 - Force perf alert API to treat is_regression as optional

Procfile, treeherder/config/settings.py, treeherder/etl/tasks/pulse_tasks.py
In #4709 push ingestion was changed to use a new `store_pulse_pushes` queue (since we now prefer the term "push" instead of "resultset"), with the old queue left behind to ensure any tasks in it at the time of deployment would still be run.
Now that the old queue is empty it can be removed.
=> Bug 1530206 - Remove the now emptied store_pulse_resultsets queue

ui/helpers/http.js, ui/intermittent-failures/Layout.jsx, ui/job-view/context/Pushes.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/js/controllers/perf/alerts.js, ui/js/controllers/perf/compare.js, ui/js/controllers/perf/graphs.js, ui/models/push.js, ui/perfherder/CompareSelectorView.jsx, ui/perfherder/SelectorCard.jsx, ui/perfherder/helpers.js, ui/push-health/Health.jsx, ui/shared/ErrorMessages.jsx
This is kind of a combination of two bugs - Bug 1527834 to replace usage of `getData` in the Perfherder SelectorCard component with PushModel.getList and part of [Bug 147377](https://bugzilla.mozilla.org/show_bug.cgi?id=1473777) to replace usage of `Fetch`. Since I'm starting conversion on the compare view, I wanted to get this part of it out of the way rather than wait for one of us to convert all Fetch usage at once (which would probably result in a fairly large diff anyways). 
Cameron, there's some files of TH that I had to change so please let me know if you want some things implemented differently, or if there's some aspect of the `getData` wrapper that should be approached differently.
@ionutgoldan This will affect the subtest distribution controller.
=> Bug 1527824 - refactor and replace usage of PushModel.getList

tests/etl/test_perf_schema.py, treeherder/log_parser/parsers.py
Fixes:
```
ResourceWarning: unclosed file <_io.TextIOWrapper name=
'schemas/performance-artifact.json' mode='r' encoding='UTF-8'>
```
=> Bug 1526911 - Close performance-artifact.json after opening it

tests/webapp/api/test_auth.py, treeherder/auth/backends.py
This can be merged once enough time has passed since #4697 (bug 1529223) landed for people to refresh any existing Treeherder UI tabs (that will have still been using the old header names/values).
(Will wait at least a couple of days more)
=> Bug 1530586 - Auth: Remove legacy header support

requirements/dev.txt
isort published the wheel a few days after the sdist (see timothycrosley/isort/issues/855), meaning the wheel hash was missing from the update PR. This causes installs to fail, since now that there is a wheel, pip favours it over the sdist and complains since the hash doesn't match the expected value.
=> Add hash for isort wheel package

Procfile, treeherder/config/settings.py
The `store_failure_lines*` and `crossreference_error_lines*` queues have been unused since the log parsing tasks were combined in #2544.
=> Bug 1531271 - Remove unused Celery queues

.dependabot/config.yml, lints/queuelint.py, requirements/common.txt, runtests.sh, tests/conftest.py, tests/settings.py, treeherder/__init__.py, treeherder/celery.py, treeherder/config/settings.py, treeherder/etl/jobs.py, treeherder/etl/management/commands/ingest_push.py, treeherder/etl/perf.py, treeherder/etl/tasks/pushlog_tasks.py, treeherder/log_parser/tasks.py, treeherder/services/pulse/consumers.py
Updating in one go, since the Celery 4 release only supports the newer versions of its dependencies and vice versa.
Of note, this fixes the unhelpful connection error messages shown when in fact there was an authentication problem, and brings Celery/Kombu support for Python 3.7. It's also likely that this will fix the pulse listener hang seen in [bug 1529404](https://bugzilla.mozilla.org/show_bug.cgi?id=1529404).
The new Celery release has renamed a number of the settings. Most changes were performed by running:
```
celery upgrade settings treeherder/config/settings.py --django
celery upgrade settings tests/settings.py --django
```
The Django integration in celery.py has been cleaned up by following:
https://celery.readthedocs.io/en/latest/django/first-steps-with-django.html
The bug being …
=> Bug 1337717 - Update to newer Celery, Kombu, py-amqp and billiard

treeherder/config/settings.py
This makes Celery defer acknowledging a task until after the task has been completed, to prevent data loss in the case of a celery/infra issue which prevents Celery from returning any unfinished tasks back to RabbitMQ.
It effectively changes the task delivery guarantee from "at most once" to "at least once", which is fine since our tasks are now all idempotent.
See:
https://devcenter.heroku.com/articles/celery-heroku#using-acks_late
http://docs.celeryproject.org/en/latest/faq.html#should-i-use-retry-or-acks-late
http://docs.celeryproject.org/en/latest/userguide/tasks.html#Task.acks_late
http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-task_acks_late
=> Bug 1532255 - Enable Celery acks_late

newrelic.ini, treeherder/services/pulse/consumers.py
Since these Django management commands are infinite duration (they run continuously listening for Pulse messages), they cannot be added to the list of Django management commands in `newrelic.ini` that are automatically tracked by the New Relic Python agent.
Instead, we need to wrap the finite duration function within the Pulse listener command that represents a discrete unit of work that New Relic can report as an individual non-web transaction.
See:
https://docs.newrelic.com/docs/agents/python-agent/supported-features/python-background-tasks#wrapping
=> Bug 1340216 - Make pulse_listener_{pushes,jobs} report to New Relic

requirements/common.txt, requirements/dev.txt
This fixes the deploys on Heroku when we do not use the ``dev.txt`` requirement (it's only used on Prototype).
Thanks Ed!
=> Move attrs requirement to common.txt

Procfile
Since the memory leaks that made it necessary to restart the workers after they had processed 50 tasks appear to no longer occur.
=> Bug 1513506 - Stop using --maxtasksperchild with log parser tasks

.eslintrc.js, tests/selenium/pages/treeherder.py, ui/css/treeherder-test-view.css, ui/css/treeherder.css, ui/job-view/CustomJobActions.jsx, ui/job-view/details/BugFiler.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/summary/LogUrls.jsx, ui/job-view/details/summary/StatusPanel.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/job-view/details/tabs/autoclassify/ErrorLine.jsx, ui/job-view/details/tabs/autoclassify/LineOption.jsx, ui/job-view/details/tabs/autoclassify/StaticLineOption.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/headerbars/FiltersMenu.jsx, ui/job-view/headerbars/TiersMenu.jsx, ui/job-view/headerbars/WatchedRepo.jsx, ui/job-view/pushes/PushHeader.jsx, ui/shared/JobDetails.jsx, ui/shared/JobInfo.jsx, ui/shared/auth/Login.jsx, ui/test-view/ui/StatusNavbar.jsx, ui/userguide/UserGuideBody.jsx
This addresses [Bug 1531243](https://bugzilla.mozilla.org/show_bug.cgi?id=1531243)
Please see individual commits
=> Bug 1531243 - Fix some a11y issues with buttons and labels

.travis.yml, renovate.json
Ensure node versions for package.json and travis.yml are the same (enabled support for renovate per here: https://github.com/renovatebot/renovate/blob/aeeeff59e13a71b16864079609a37e14f3f29904/website/docs/node.md#file-support)
=> Make travis use same node version as package.json

tests/push_health/test_classification.py, treeherder/config/settings.py, treeherder/push_health/classification.py, treeherder/push_health/filter.py, treeherder/push_health/push_health.py, treeherder/push_health/utils.py, treeherder/webapp/api/push.py, ui/push-health/Metric.jsx, ui/push-health/Navigation.jsx, ui/push-health/TestFailure.jsx
This has some of the logic for detecting intermittents.  But it is
still a work in progress.  It only does some of the detection
so far.
I still have a ways to go on this to get all the logic in.  But this is a good place to get some of the basic concepts reviewed and merged before I start adding more of the rules.
As you can probably tell from the endpoint, the hub of the data collection is in ``push_health/push_health.py`` in the ``get_push_health_test_failures`` function.  From there it makes the rest of the calls.
I opted for raw ``SQL`` to get the history of intermittents.  This seemed to be the most efficient way to go.  But open to suggestions.  :)
The unit tests are a bit anemic, but I'll flesh those out in a later PR.
=> Bug 1521157 - Have Push Health prototype return live data

treeherder/push_health/push_health.py, treeherder/push_health/utils.py, ui/job-view/pushes/PushActionMenu.jsx, ui/push-health/TestFailure.jsx
After some conversations with @jmaher I changed directions here, slightly.  Instead of fetching the ``log_lines`` for each job of each test, I print out the ``FailureLine``s, grouped by test name.  I added a link to the log so you can easily inspect further.  And when there is an identical failure, it shows both jobs for the same test failure.
I did not yet address the idea of using Serializers.  Comments in-line.
=>  Bug 1521157 - Improve test matching and log lines

tests/push_health/test_classification.py, treeherder/push_health/classification.py, treeherder/push_health/push_health.py, treeherder/webapp/api/push.py, ui/push-health/ClassificationGroup.jsx, ui/push-health/Metric.jsx, ui/push-health/TestFailure.jsx, ui/push-health/TestFailures.jsx, ui/push-health/pushhealth.css
This PR will group test failures into the groups to which we have calculated they belong.  So, "intermittent", "previousRegression", or "needInvestigation".  It defaults to the first two being collapsed in the UI.
=> Bug 1521157 - Group by classifications

ui/push-health/TestFailure.jsx
I missed these key errors when I added more data in a previous PR. This fixes the key errors for ``map``ped ``array``s.
=> Bug 1521157 - Fix key errors in React with arrays of data

treeherder/push_health/classification.py, treeherder/push_health/push_health.py, treeherder/webapp/api/push.py, ui/job-view/pushes/PushActionMenu.jsx
Currently, we categorize failures into "intermittent".  This adds categorizing them into "fixedByCommit"
These queries are a bit slow still, so I will introduce caching in a follow-up PR.
=> Bug 1521157 - Check for fixed_by_commit classification

treeherder/push_health/push_health.py
When we do clean_test, the test name could come back "None".  In
this case, the test should be skipped.
=> Fix error when some test names get filtered out

treeherder/model/management/commands/cache_failure_history.py, treeherder/push_health/push_health.py
The normal request for history will now cache the results for that ``push_date``.  So if none is cached, it will save it for the next time it's requested.
This also adds a management command to warm the cache for the prior 5 days, by default.  This will be called daily in the heroku scheduler once this commit is pushed to each instance.
=> Bug 1521157 - Cache failure history with management command

ui/helpers/constants.js
The 'opt' build flavor is supposed to be shown on top for the group of platforms whose only difference is the build flavor:
https://github.com/mozilla/treeherder/blob/fa39de7925dc2dc398c22389d31fa7af79369ab5/ui/helpers/constants.js#L125
Because its value is 0, it evals to false in the if check at
https://github.com/mozilla/treeherder/blob/fa39de7925dc2dc398c22389d31fa7af79369ab5/ui/job-view/pushes/Push.jsx#L233
and 10 gets used as value instead which puts it at bottom.
Let's increase the value for each flavor so all are positive and the sort function doesn't have to become more complex.
=> Bug 1539580 - platform 'opt' should be on top of list for operating system

treeherder/model/management/commands/cache_failure_history.py, treeherder/push_health/push_health.py
When the management command to update the failure history is invoked, we want to force 
updating the cache.  This is in case we change the format of the data that is stored, we can easily update it to the latest version.
=> Bug 1521157 - Allow force-caching of failure history

treeherder/push_health/classification.py, treeherder/push_health/push_health.py, treeherder/push_health/similar_jobs.py, treeherder/webapp/api/push.py, ui/push-health/Job.jsx, ui/push-health/TestFailure.jsx, ui/push-health/TestFailures.jsx, ui/push-health/index.jsx
This correlates matching passing jobs to the failed jobs for a given test.  So this helps you see the frequency of pass/fail for a particular test to help with determining how intermittent it is.  
The second commit implements marking a test as intermittent if it has >50% pass/fail ratio.
This second commit also removes the bucket of "FixedByCommit" because those are ones that also need investigation, so even 100% confidence in FBC tests go into "Needs Investigation".
=> Bug 1521157 - Calculate intermittents for passing jobs

ui/job-view/context/SelectedJob.jsx
This was the result of me changing some items from links to ``button``s when I did some a11y fixes a while back.
=> Bug 1541726 - Fix pinboard closing on pin all

treeherder/webapp/api/push.py, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/models/job.js, ui/models/push.js
This is to help with enabling retriggers in Push Health.  The way this was done before was really convoluted.  This application can be applied to any function that is currently using ``getGeckoDecisionTaskId``.  I'm just starting here since this is what I need right now.
=> Bug 1496858 - Improve JobModel retrigger wrt decision task

treeherder/push_health/similar_jobs.py
If there were no structured log failures in the push, then ``failures`` here would be empty, so we should bail out of this function.
This was the bug you mentioned in the retrigger PR.  :)
=> Fix Push Health when there are no structured log failures

treeherder/webapp/api/push.py
I'm not 100% certain why, under the hood, this is so much faster, but it is.  It must have to do with doing a string lookup through a filter on a large table.
=> Bug 1542446 - Speed up Push API to get Decision Task

tests/webapp/api/test_performance_alertsummary_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py
Return revision, prev_push_revision and push_timestamp; doesn't appear to affect the overall query time.
Creating this pr separately so I can continue to work on the Perfherder Alerts conversion.
=> Perfherder - modify AlertSummary serializer

ui/models/job.js
Some jobs (notable release jobs) should not be retriggered, but instead rerun.
Use the new `retrigger-multiple` action to allow taskgraph to make that
determination.
=> Bug 1521032: Use retrigger-multiple action to retrigger jobs.

tests/webapp/api/test_bugzilla.py, treeherder/webapp/api/bugzilla.py, ui/job-view/details/BugFiler.jsx
This updates the bug filer to use markdown in the bugzilla bug
description. It adds bolded labels to the `Filed by` entry and any URLs
specified. Addtionally the comment is surrounded in a code fence so
that long lines aren't wrapped and lines that also happen to have
markdown formatting in them are ignored.
Example output:
**Filed by:** foo [@] bar.com
**Parsed log:** http://.../parsed.log.html
**Full log:** http://.../full.log.html
---
```
[task 2019-03-06T03:54:26.459Z] 03:54:26 INFO - TEST-FAIL...
[task 2019-03-06T03:54:26.460Z] 03:54:26 INFO - INFO | LeakSanitize
...
```
@sarah-clements Can you take a look this? I've tested the front-end locally and can confirm it doesn't seem to cause any errors, but I've neither confirmed that back-end tests pass nor that it properly files a bug.
=> Bug 1544149 - Use markdown in the bug filer

ui/css/treeherder-fuzzyfinder.css, ui/job-view/pushes/FuzzyJobFinder.jsx, ui/job-view/pushes/PushActionMenu.jsx
This commit changes a few pieces of the fuzzy job finder modal:
Change the name from 'Add New Jobs (Fuzzy)' to 'Add New Jobs (Search)'.
This distinguishes it a bit from 'mach try fuzzy' since we don't have
fzf's search syntax.
Allow the fuzzy finder to search by job symbol instead of just job
name/label. You can now just search for 'wpt' instead of
'web-platform-test'. There's something weird with the fuzzy search
library, so searching for both the job label and the job symbol (eg
'android wpt') doesn't give any results. But you can search for 'wpt'
and then look through the list for android jobs. There's an issue filed
against fuse.js about this, so hopefully it works better in the future.
Loosen the threshold on what qualifies as a match in the fuzzy search.
The old value made it …
=> Bug 1546463 - Tweak 'Add New Jobs (Fuzzy)' a bit

treeherder/push_health/classification.py, treeherder/push_health/push_health.py, ui/push-health/TestFailure.jsx
If a test fails in one job, it may pass in a retrigger, even in that new job failed
because of another test.  In this case, the job should count as a pass for this
test with regard to it being intermittent.
=> Bug 1548632 - Push Health - Use failed jobs for tests where they passed

ui/push-health/Health.jsx, ui/push-health/Metric.jsx, ui/push-health/TestFailure.jsx, ui/push-health/pushhealth.css
This is mainly aimed at fixing a ``subtest`` that had a really odd and long string:
http://localhost:5000/pushhealth.html?repo=mozilla-inbound&revision=fdff2d33f119d6ea14594af60846df80c76506d2
I think it was the 34th test.  So this formats the monospaced text and prevents the table from growing too large with a hard-to-wrap string.
It also makes the ``subtest`` shorter by default to remove clutter.  Then it can be viewed by clicking  "more..."
=> Fix minor Push Health layout

tests/push_health/test_classification.py, treeherder/push_health/classification.py
It occurred to me that, rather than being able to toggle these tests on and off based on whether all their failed jobs are classified, that it is appropriate to move them to "intermittent".  My reasoning is that if the job was classified intermittent by a sheriff or whomever, then that means it's been investigated already and judged to be intermittent.
@jmaher : What do you think?  Do you agree or am I off-base?  :)
=> Bug 1550273 - Remove tests from need investigation that are classified

treeherder/webapp/api/push.py, ui/job-view/App.jsx, ui/job-view/headerbars/HealthMenu.jsx, ui/job-view/headerbars/PrimaryNavBar.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx, ui/job-view/pushes/PushList.jsx, ui/models/push.js, ui/push-health/Navigation.jsx, ui/shared/PushHealthStatus.jsx
This adds an opt-in to add the Push Health Status badge to each push.  It stores your selection in ``localStorage`` so it persists.  Currently, the options are "All", "Try" or "None".  If there are other specific options I should add, please let me know.
I also added a Tooltip to Push Health on the "[--PROTOTYPE--]" text to help explain its state a bit.
In Treeherder, the badge will look like:
I left the PushActionMenu item so that you can still access Push Health without needing to activate the badge.
=> Bug 1549556 - Add Push Health badge to PushHeader

ui/helpers/url.js, ui/shared/JobDetails.jsx
- When a test job uploads a single profile, it's a json file, so relax the extension check
- perf.html has been renamed to 'Firefox Profiler' and 'perf-html.io' moved to 'profiler.firefox.com'
=> Show 'open in Firefox Profiler' links for profiles with a .json extension

ui/helpers/location.js, ui/helpers/object.js, ui/job-view/details/PinBoard.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/Platform.jsx, ui/job-view/pushes/PushJobs.jsx
Partially address [Bug 1510280](https://bugzilla.mozilla.org/show_bug.cgi?id=1510280)
This change reduces the rendering time of a 10 pushes of mozilla-inbound (unfiltered) from around 8 seconds to around 4 seconds.
The main gist of this change is to add ``shouldComponentUpdate`` and remove the ``getDerivedStateFromProps`` from ``PushJobs`` also means that we won't re-render every push when a single push has returned new jobs.  
This change also moves the filtering and re-rendering of platforms from ``PushJobs`` which holds all the platforms for a ``Push`` down to each ``Platform``, which then filters itself.  This has the advantage that if one platform needs to re-filter and render, the others don't need to.  Follow-up PRs will try to take more advantage of this.  But I didn't want to …
=> Bug 1510280 - Reduce repeated rendering of PushJobs

tests/ui/unit/react/bugfiler_test.jsx, ui/job-view/details/BugFiler.jsx
Bugfiler uses an apparently undocumented bugzilla api to search for
product/component pairs, and bugzilla recently moved the api endpoint,
breaking the bug filer. This patch points to the correct endpoint.
=> Bug 1555864 - Fix bugfiler's use of bugzilla's product/component search

treeherder/model/fixtures/repository.json, ui/intermittent-failures/constants.js
And disable the esr52 repositories at the same time.
This should land after the repositories have been [created](https://bugzilla.mozilla.org/show_bug.cgi?id=1555777).
=> Add support for mozilla-esr68 repository.

tests/ui/unit/context/pushes_test.jsx, ui/helpers/constants.js
Most landings these days are going to autoland rather than
mozilla-inbound, so lets default to showing autoland if no repo is
specified.
=> Bug 1552250 - Make autoland the default repo

tests/ui/unit/react/alerts_test.jsx, ui/perfherder/alerts/AlertTable.jsx, ui/perfherder/alerts/AlertTableRow.jsx
This patch solves a bug Ionut discovered where if an alert summary checkbox is selected (to select all alerts), and then one alert is deselected, any action performed will still update all alerts because the checkbox summary alert was also not deselected. I added another test to cover this scenario and cleaned up the `AlertTableRow` file a bit.
=> Bug 1558752 - Fix alert summary checkbox on Perfherder alerts view

ui/helpers/job.js, ui/job-view/details/summary/ActionBar.jsx
@camd: This is a combination of the original pull request with fixes for the lint errors and two additional changes to prevent test isolation from being available to jsreftests and to increase the maximum 'times' to 100.
=> Bug 1557038 - Add Test Isolation to Job Action, r=camd.

tests/ui/models/filter_test.js, tests/ui/unit/react/selected_job_test.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/JobsAndGroups.jsx, ui/job-view/pushes/Platform.jsx, ui/models/filter.js
This fixes when you are classifying a failure in the middle of a list of failures in "unclassified only" mode.  When you save the calssification, the job disappears, and hitting "N" for next takes you to the top failure, instead of the next one from where you were.
This change keeps the classified job visible while it's selected.  It then disappears when no longer selected and you go to the correct "next" failure.
The crux of this failure was that I was passing ``platform`` as the first param to the ``filterCb`` callback, when ``platform`` is no longer a param of that function.  It just takes ``selectedJobId``.  Consequently, the ``platform`` param isn't needed on several components going down the hierarchy.
There was a bit of churn in ``FilterModel`` because I fixed a couple other …
=> Bug 1438555 - Fix 'n' after classifying going to top failure

ui/css/perf.css, ui/perfherder/alerts/AlertsView.jsx
I realized in my last pr #5065 I didn't address the issue with the disappearing pagination, and the culprit was the use of Math.round. I also added active prop (and a CSS style to match the color) to easily denote active page to avoid confusion and remove unused styles.
=> Bug 1559146 - fix disappearing pagination in Perfherder alerts view

ui/perfherder/helpers.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1557235
The template forms we use for filing Bugzilla tickets approximate percentages without any decimals. This is nice most of the times, as the report is readable.
Still, there are cases when we need to leverage 2 decimals for extra precision.
More precisely, when we have alerts which end up approximated to 0%.
E.g.:
for Perfherder alerts like
6.8% Base Content JS linux64-shippable opt
5.45% Base Content JS windows10-64-shippable-qr opt
0.21% Base Content JS windows7-32-shippable opt
we would get a report like
7% Base Content JS linux64-shippable opt
5% Base Content JS windows10-64-shippable-qr opt
0.21% Base Content JS windows7-32-shippable opt
=> Bug 1557235 - Provide 2 decimals for 0% regressions

ui/job-view/details/DetailsPanel.jsx, ui/models/perfSeries.js
I broke the details panel with the pr #5053 I recently merged. My bad :) Since the `getSeriesList` now returns `failureStatus` due to that refactor, you can utilize the error handling.
FYI @KWierso
=> Fix bug caused by change made to PerfSeriesModel.getSeriesList

ui/job-view/details/PinBoard.jsx
I just needed to add a check before calling ``refilter``.  Because if another job in the same platform was classified, a race condition could cause this job to have already been removed from the DOM.
=> Bug 1554136 - Fix error when classifying many jobs on the same platform

ui/job-view/CustomJobActions.jsx, ui/job-view/context/Pushes.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushActionMenu.jsx, ui/job-view/pushes/PushHeader.jsx, ui/models/job.js, ui/models/push.js
I wanted to simplify the process of getting the decision task ID rather than searching in the existing/loaded jobs.  Since we have to do a round-trip to the server anyway.
=> Bug 1441938 - Use PushModel.getDecisionTask functions

treeherder/model/fixtures/repository.json, ui/intermittent-failures/constants.js
The mercurial repository is up and running now.
=> Bug 1561934 - Activate comm-esr68 repository.

ui/perfherder/alerts/AlertsView.jsx
Change navigatePage function to update state and params and fetch new alert summaries instead
of using angular state.go since that causes the page to re-mount on navigation (and to clear the text in the search input when navigating from page to page).
=> Bug 1562852 - fix Perherder Alerts search input

ui/models/user.js
Totally untested by me, but the default has been same-origin since Firefox 61 or 62, and similar timeline for Chrome.
=> Bug 1563884 - Stop sending 'credentials: same-origin' to /user requests

tests/webapp/api/test_bugzilla.py, treeherder/webapp/api/bugzilla.py, ui/job-view/details/BugFiler.jsx
Always use the “defect” bug type, or the bot will soon fail to file new bugs once the [Bugzilla API makes the type field mandatory](https://bugzilla.mozilla.org/show_bug.cgi?id=1562364).
[Bug 1531759 - Modify treeherder's bugfiler to set bug type as 'defect'](https://bugzilla.mozilla.org/show_bug.cgi?id=1531759)
=> Bug 1531759 - Modify treeherder's bugfiler to set bug type as 'defect'

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py
I've made a few changes to the `/performance/summary/` endpoint so that if a `all_data` param is passed the data is in the same structure as it would be with the `/performance/data/` endpoint (except it also eliminates the need to call `/performance/signature/` endpoint as the Perfherder graphs view is currently doing).
=> Perf summary api change

treeherder/webapp/api/push.py, ui/job-view/CustomJobActions.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx, ui/models/job.js, ui/models/push.js
I broke retriggers when I fixed add-new-jobs in commit 3b5665fa7144a1b7604c5bf1d0f5dc97f972264f.
These need tests and I will add them after Armen's pulse data ingestion changes land.  Otherwise, the test data to ingest would have to be re-written.  [Bug 1565667](https://bugzilla.mozilla.org/show_bug.cgi?id=1565667)
The second commit fixes the Treeherder side of having retriggers and add new jobs work on NSS repos.  Hopefully this is generic enough, but not too generic to work for any other repo.  Now NSS has to generate the required artifacts in their decision tasks.
=> Bug 1565364 - Fix Retriggers

docker/dev.Dockerfile
Per Armen's research, this should solve the issue with the failing tests in Travis due to a missing wheel SHA in our requirements file that pip was expecting. However the linting test has failed.. I've tried running `docker-compose run backend ./runtests.sh` but I don't see any issues except for the usual src/recommonmark/ errors. Do I need to change the graphql-core dependency? https://travis-ci.org/mozilla/treeherder/jobs/559102999
=> Fix bad release of graphql_relay

docker/dev.Dockerfile
This reverts commit 989626a007cb311e44e798338bd8800aea79cd52.
The wheel has been [deleted](https://github.com/graphql-python/graphql-relay-py/issues/23#issuecomment-511619701):
https://pypi.org/project/graphql-relay/0.4.5/#files
=> Revert "Fix incorrect version of graphql_relay being released"

docs/installation.md, docs/testing.md, mkdocs.yml
Having the ``test`` and ``installation`` info interleaved didn't feel ideal to me.  Hopefully this organization will make it easier to get to the info you want.  :)
Please feel free to offer suggestions for more info!
=> Split out the /docs automated test section and enhance it a bit

docs/infrastructure/troubleshooting.md, docs/pulseload.md, docs/submitting_data.md, misc/compare_pushes.py, requirements/common.txt, requirements/dev.txt, schemas/pulse-job.yml, schemas/task-treeherder-config.yml, tests/etl/test_job_loader.py, tests/etl/test_job_schema.py, tests/sample_data/pulse_consumer/job_data.json, tests/sample_data/pulse_consumer/taskcluster_pulse_messages.json, tests/sample_data/pulse_consumer/taskcluster_tasks.json, tests/sample_data/pulse_consumer/taskcluster_transformed_jobs.json, tests/sampledata.py, tests/services/pulse/test_consumers.py, tests/test_worker/test_pulse_tasks.py, treeherder/etl/job_loader.py, treeherder/etl/jobs.py, treeherder/etl/management/commands/ingest_push_and_tasks.py, treeherder/etl/management/commands/update_pulse_test_fixtures.py, treeherder/etl/schema.py, treeherder/etl/taskcluster_pulse/handler.py, treeherder/etl/taskcluster_pulse/parse_route.py, treeherder/etl/tasks/pulse_tasks.py, treeherder/services/pulse/__init__.py, treeherder/services/pulse/consumers.py, treeherder/services/pulse/sources.py
Currently, Treeherder consumes Pulse messages from an intermediary service called `taskcluster-treeherder`.
Such service needs to be shut down and its functionality imported into Treeherder.
In order to do this we need to switch to the standard Taskcluster exchanges as defined in here:
https://docs.taskcluster.net/docs/reference/platform/queue/exchanges
On a first pass we are only including the code from `taskcluster-treeherder` without changing
much of Treeherder's code. We will still have an intermediary data structure representing
what `taskcluster-treeherder` was emitting, however, we will stop consuming data directly
from it and be able to shut it down.
Following this work would be to get rid of the intermediary job representation which will
clean up a bunch of code and some old …
=> Bug 1395254 - Consume Taskcluster jobs from standard queue exchanges

yarn.lock
This removes the unsecure lodash being used.
I don't know why `snyk test` was not catching this.
I got notified via GitHub.
`yarn audit` would show the vulnerability.
Details:
https://www.npmjs.com/advisories/1065
=> Upgrade dependencies of enzyme

treeherder/webapp/api/refdata.py, treeherder/webapp/api/serializers.py, treeherder/webapp/api/urls.py, ui/models/job.js
The issue here was that, for canceling, you need the decision task ID for the job.  But that data does not come down with the greater list of jobs in the job-view.  It only comes when you get an individual job (the currently selected one).
So the most efficient way to get this info was to create an endpoint for the ``taskclustermetadata``.  I call this with the list of job ids when the attempt to cancel happens in the ``JobModel``.
I didn't create a JS model for ``taskclustermetadata`` as it seemed overkill.  But I'll do that if you feel like it's worth it for parity with the others.
=> Bug 1567868 - Fix canceling more than one job from the pinboard

renovate.json
Changing the reviewer to Armen (thank you!) since he'll be taking a turn at handling this. We can change this in the future to team reviewers - not sure exactly what that entails but it appears that's what Ed was originally going for and renovate has added that feature in quite recently: https://github.com/mozilla/treeherder/pull/4585
FYI @camd
=> Change renovate reviewer to armenzg

ui/job-view/details/tabs/SimilarJobsTab.jsx
I broke the ``SimilarJobsTab`` when I converted ``JobModel.getList`` to use ``getData``.  This fixes it.
=> Fix SimilarJobsTab fetching job list

tests/ui/job-view/groups_test.jsx, tests/ui/job-view/selected_job_test.jsx, tests/ui/job-view/stores/pushes_test.jsx, tests/ui/mock/platforms.json, ui/helpers/filter.js, ui/helpers/job.js, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/summary/StatusPanel.jsx, ui/job-view/details/summary/SummaryPanel.jsx, ui/job-view/details/tabs/AnnotationsTab.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/job-view/details/tabs/failureSummary/BugListItem.jsx, ui/job-view/details/tabs/failureSummary/FailureSummaryTab.jsx, ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/JobsAndGroups.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushJobs.jsx, ui/logviewer/App.jsx, ui/models/filter.js, ui/models/job.js, ui/models/runnableJob.js, ui/shared/JobInfo.jsx
This renames ``selectedJob`` as it's percolated through the details panel to ``selectedJobFull`` to distinguish the difference between the version we get in the normal ``PushList`` and the detailed version we have in the details panel (it has a few extra fields like ``job_logs`` and such.
This also adds some small optimizations like ``addAggregateFields`` for each job.  Before we were calling these functions over and over, every time the filtering changed and jobs were re-rendered.
=> Rename details selectedJob to selectedJobFull

ui/css/treeherder-resultsets.css, ui/job-view/pushes/Revision.jsx
The spacing was off after ionut's addition of the clipboard copy.  I had meant to fix this before we pushed to prod.  But here it is.  :)
=> Fix spacing around revision sha

ui/helpers/job.js, ui/job-view/details/PinBoard.jsx, ui/job-view/details/tabs/SimilarJobsTab.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobGroup.jsx
I had tried to optimize setting the ``btnClass`` on jobs and group counts, but it ended up not having the right updates when things changed.  So this goes back to how it was, getting the class on the fly.
=> Fix btnClass being applied incorrectly to jobs and counts

treeherder/perf/fixtures/performance_bug_templates.yaml
The old wiki links redirect so this isn't urgent, just a bit of cleanup.
=> Update wiki links and component in perf bug templates

package.json, tests/ui/test-setup.js, yarn.lock
`jest-dom` has moved to `@testing-library/jest-dom`. Please uninstall jest-dom and install `@testing-library/jest-dom` instead,
or use an older version of `jest-dom`. If you do upgrade to `@testing-library/jest-dom`, make sure to update your usage of `jest-dom`
to use `@testing-library/jest-dom/extend-expect` rather than simply `jest-dom/extend-expect`. Learn more about this change here:
https://github.com/testing-library/dom-testing-library/issues/260 Thanks!
=> Switch from `jest-dom` to `@testing-library/jest-dom`

tests/ui/job-view/PushList_test.jsx, tests/ui/job-view/stores/pushes_test.jsx, ui/job-view/pushes/PushActionMenu.jsx, ui/models/push.js
Just need to update on "get X more" pushes because we silently update the URL so as not to kick off a cascade of unwanted renders.
This also fixes the error where we only fetched up to 10 pushes, even if the ``fromchange`` param is set.  It should then get the max pushes allowed.
=> Bug 1572255 - Fix set top and bottom of range links

ui/shared/JobInfo.jsx
This fixes two bugs.  The ``job.searchStr`` is what is internally searched in the job, but it needs to be split in the ``JobInfo`` for each link.
The second bug is just cosmetic, but was in same file, so easy to fix at the same time.
=> Bug 1572283 - Fix filtering link by job data

ui/helpers/job.js
I should not have trimmed this field.  We need it for retriggers.
=> Bug 1573923 - Fix Custom actions and retriggers

ui/js/controllers/perf/graphs.js, ui/perfherder/graphs/TestCard.jsx
If more tests are added than colors are provided, show the excess as grey. More improvements to come in pr #5286
=> Bug 1573162 - Patch to prevent UI from breaking in Perfherder

.travis.yml
Up until now we were not testing the same code path that Heroku follows to
generate the front-end build.
Heroku runs the `yarn install` command under `NODE_ENV=production` which causes
only the production dependencies to be installed. In the case of
[PR 5283](#5283), we moved `neutrino`
from `dependencies` to `devDependencies` and went unnoticed until Heroku tried to deploy
the change. See output [1].
This change adds one more entry for Travis where we only install the production dependencies
before running `yarn build`.
[1]
```shell
2019-08-16 19:34:49 -----> Build
2019-08-16 19:34:49        Detected both "build" and "heroku-postbuild" scripts
2019-08-16 19:34:49        Running heroku-postbuild (yarn)
2019-08-16 19:34:50        yarn run v1.17.3
2019-08-16 19:34:50        $ yarn build …
```
=> Add test for generating production build

ui/job-view/App.jsx
This just ensures we don't try to render anything that requires ``currentRepo`` until we have a valid ``currentRepo``.
Before, we tried to kind of "fake it" with a dummy ``currentRepo`` till the real object was loaded.  But that was pretty useless and problematic in many ways.
=> Bug 1575334 - Fix errors when currentRepo is set incorrectly

.neutrinorc.js, requirements/common.txt, treeherder/webapp/api/push.py, ui/models/push.js
This adds some caching, so we don't have to fetch the Decision Task so often.  Both on the client/JS side as well as the back-end/Django side.  It also adds a bit of logging to give me more idea of what might be failing if this continues to fail.
=> Bug 1566077 - Fix retriggers throwing errors intermittently

tests/ui/job-view/Filtering_test.jsx, ui/helpers/job.js
I didn't need to make this lower case here.  The ``FilterModel`` makes everything lowercase while filtering anyway.
=> Bug 1573462 - Job and group name keeps capitalizations

treeherder/config/settings.py
Once we [switched to using Docker instead of Vagrant](https://github.com/mozilla/treeherder/pull/4901) we lost
the ability of using the Django debug toolbar when loading an API. This is a very important tool for Django development.
In Vagrant, we could specify which internal IPs to use, however, with Docker we can't predefine an IP before starting the container.
The toolbar allow us to provide options and specificall a function to determine to show or not the toolbar (via the `SHOW_TOOLBAR_CALLBACK` option).
=> Bug 1563014 - Enable the Django debug toolbar within Docker

ui/job-view/details/summary/ActionBar.jsx
It currently looks like this on stage: 
This sets the border and background to invisible.
=> Fix cancel button color on ActionBar

ui/perfherder/graphs/GraphTooltip.jsx
There's a missing condition for the tooltips for an alert (per certain scenarios) so adding it in.
=> Bug 1580207 - Fix for Tooltip on Perfherder graphs

codecov.yml
In order to not fail automatic tests when auto-deploying to master.
About:
https://docs.codecov.io/docs/commit-status#section-patch-status
=> Disable patch level checks

treeherder/model/management/commands/cycle_data.py, treeherder/model/models.py
This change will allow us to delete FailureLine records, even if they have an invalid continuation byte.
I also had it order deletion by ``id`` so it gets the oldest records first.
This removes part of a change that @ionutgoldan introduced to limit the logging to only ``CRITICAL`` for ``cycle_data``.  But I think we want to log the ``cycle_data`` activity so it is search-able in Papertrail.  But I value your input on this, @ionutgoldan, in case there was a strong argument to keep these lines.  :)
=> Bug 1581227 - Fix cycle_data failure due to invalid  continuation byte

tests/ui/models/jobs_test.js, tests/ui/models/push_test.js, treeherder/webapp/api/jobs.py, ui/job-view/CustomJobActions.jsx, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx, ui/job-view/redux/stores/pushes.js, ui/models/job.js, ui/models/push.js, ui/models/runnableJob.js, ui/models/taskcluster.js, ui/shared/JobInfo.jsx
This creates a ``decisionTaskMap`` which is used for all the actions interacting with Taskcluster.  Prior to this, you always needed to fetch it from the ``PushModel``.  This has proven to be slow and unreliable.  In Treeherder, we have all the decision jobs already, so this just uses what is already in memory.  
Formerly, we used to find this object from the in-memory list of jobs, but in a much more complex way.  This creates a small map of every decision task for every push that we can get wherever we need it.
I updated the ``JobModel`` so that it will use the decision task or map, if passed in.  If it wasn't, then it will try fetching it from the endpoint.  This will allow Perfherder and other apps to still get the decision task when they don't have the whole list of jobs.
Part of …
=> Bug 1566077 - Improve getting decision task ID

ui/job-view/redux/stores/pushes.js, ui/models/job.js
On central, there may be several decision tasks due to cron jobs, etc.  I neglected to add this check to be sure we get the right one.
=> Bug 1582737 - Fix error finding correct decision task

ui/perfherder/alerts/AlertTableRow.jsx
add a default value for when push timestamps exceed the max one year value
=> Bug 1582652 - perfherder graph links fix

ui/perfherder/graphs/GraphTooltip.jsx, ui/perfherder/graphs/GraphsView.jsx
Update the compare subtest link from the graph tooltip to use parent_signature if applicable (for a subtest) or signature if it's a test.
=> Bug 1583155 - Perfherder graph link fix

ui/perfherder/graphs/GraphsContainer.jsx
In my initial pr friday #5390 I switched to the Selection Zoom container but I hadn't noticed that this new container makes the datapoints overflow it's parent container due to something strange having to do with the `domain` prop. I've found a solution which creates a combined zoom and selection container, so the `zoomDomain` prop is updated but I can disable the mouse zoom features the sheriffs don't want.
tldr; fixed overflowing container due to zoom feature change.
=> Bug 1582731 - Perfherder graph change

ui/perfherder/graphs/LegendCard.jsx, ui/perfherder/graphs/TestDataModal.jsx
I had misunderstood Ionut's comments about how this logic should work on a previous pr so this now works so that:
- "Add related branches" text button returns results for same test and platform with the two related branches (autoland and mozilla-inbound) if applicable
- "Add related platforms" text button returns results for same test for the two above related branches and all platforms if applicable. This label has also been renamed to make it clearer its fetched related branches AND platforms.
I've combined two functions into one since they now do almost the same thing.
=>  Bug 1583488 - Perfherder legend links fix 

ui/job-view/details/BugFiler.jsx
Its developer wants to triage its intermittent bugs. A priority would hide
those bugs from the triaging queues.
=> Bug 1580287 - Don't set a priority for bugs in 'Firefox :: Messaging System'.

.eslintrc.js
We actually pass linting with this rule enabled.
=> Enable passing eslint rule: jsx-a11y/label-has-for

.eslintrc.js, ui/intermittent-failures/BugColumn.jsx, ui/job-view/App.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/tabs/AnnotationsTab.jsx, ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/headerbars/FiltersMenu.jsx, ui/job-view/headerbars/SecondaryNavBar.jsx, ui/job-view/pushes/PushActionMenu.jsx, ui/job-view/pushes/PushJobs.jsx, ui/job-view/pushes/PushList.jsx, ui/job-view/pushes/Revision.jsx, ui/perfherder/alerts/AlertTableRow.jsx, ui/perfherder/compare/CompareTable.jsx, ui/perfherder/graphs/GraphsContainer.jsx, ui/perfherder/graphs/LegendCard.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/Metric.jsx, ui/shared/TruncatedText.jsx, ui/test-view/ui/Test.jsx
Here are those rules disabled per-file, rather than globally.  I did them in separate commits so they could be easily reverted, if need be.
=> A11y eslint rules for outreachy

ui/css/intermittent-failures.css, ui/intermittent-failures/BugDetailsView.jsx, ui/intermittent-failures/helpers.js
* increase the size of the tooltip for longer failure messages when window is wide
* remove the path to the test in test name and show only the test name before the actual message
=> Bug 1555281 - Fix intermittent-failures.html truncated failure message

ui/perfherder/graphs/GraphsContainer.jsx
Hi @sarah-clements,
In Perfherder, lower horizontal labels from the Graph are being cut off the right side.
This inserts `setRightPadding()`, which calculates the `padding-right` of the chart, according to the last horizontal axis tick.
This probably need some refactoring and I can do that after the first review.
Since finding the occurrence of the issue may be difficult, I have used the page reported by the user to [test](http://localhost:5000/perf.html#/graphs?timerange=2592000&series=mozilla-central,1834678,1,10&series=mozilla-central,1955233,1,10&series=mozilla-central,2110541,1,10&series=mozilla-central,2117747,1,10&series=mozilla-central,1834673,1,10&series=mozilla-central,1955223,1,10&series=mozilla-central,2110530,1,10&series=mozilla-central,2117883,1,10&series=mozilla-central,1834 …
=> Bug 1584140 - Lower labels from Graphs view are being cut off

bin/pre_deploy
The New Relic python agent changed the parameter order for  the ``record-deploy`` command.  So our deployments were failing due to this.
https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-admin-script#record-deploy
This updates the params.  I had to add an env var on each Heroku deployment with the ``NEW_RELIC_APP_ID`` to make this work.
=> Fix New Relic record-deploy parameters

tests/ui/helpers/helpers_test.js, ui/css/perf.css, ui/perfherder/alerts/AlertTableRow.jsx, ui/perfherder/compare/TableAverage.jsx, ui/perfherder/graphs/GraphsContainer.jsx, ui/perfherder/helpers.js
"Removed text-align: center in perf.css so that numbers are left alligned by default and added thousands separator for numbers in helpers.js"
Hey @camd @sarah-clements. This is actually my first pull request for open source. Please tell me what I need to fix. Part of this bug was to fix the numbers not having a thousands separators so I changed the helper function "displayNumber" and because it returns a string now with thousands separators it does not pass the test provided for this function.
Is this a problem I need to fix and any directions for it?
All criticism is welcome.
=> Fixes Bug 1537890

ui/perfherder/index.jsx
I just realized the Perfherder HelpMenu and LoginMenu components aren't working properly (dropdowns aren't opening); I hadn't realized those were still using Bootstrap's jquery. Oops. I added that import. 
@camd Is removing jquery use for those two components on your to-do list or should I file a bug?
=> Perfherder nav menu - import bootstrap jquery package

treeherder/model/models.py, ui/helpers/job.js
We were sometimes returning ``0`` length duration.  Our UI code was interpreting that as no duration.  So it tried to calculate it.  In some circumstances (like the larger list of jobs) we return only duration, but not the start time, end time, etc.  So we get an error when trying to calculate it.
This fixes the back-end to always return a minimum duration of 1.  It also improves the calculation of duration on the front-end if we don't have one.
Lastly, it makes the grammar of the ``title`` on a job smarter, in case it's duration of 1.
=> Bug 1581739 - Fix when NaN duration is displayed

ui/job-view/details/BugFiler.jsx, ui/job-view/details/PinBoard.jsx
This was, in some cases, using a copy of the job used for the ``DetailsPanel``.  Since this is a separate instance than the one displayed in the main job field, it didn't update after using the ``BugFiler``.  The ``jobMap`` has a mapping of all jobs displayed in the job field, by id.
This was also attributed to a timing of display with the modal dialog being ``toggle``d off and the ``successCallback`` being called.  So just swapped them.
=> Bug 1577532 - Reflect new job classified status after using BugFiler

ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx
Hi @camd ,
In Treeherder's Jobs View, when `(+)` to expand groups, the URL is updated with `&group_state=expanded`. The push's links, however, are not immediately updated with these URL params.
Currently, the `groupCountsExpanded` props is not being passed from Push to PushHeader component.
The solution pass this props and checks it against the previous props, in the already created `shouldComponentUpdate()` method.
(Thanks @camd for the help!)
Two brief tests were done:
1. In the default Job View (all jobs), the `(+)` button was clicked and the push link was checked.
2. After clicking on the push link (single job), the `(+)` button was toggled to check if the groups were expanded.
=> Bug 1217058 - Preserve grouping state when clicking links

treeherder/model/fixtures/repository.json
This is part of https://bugzilla.mozilla.org/show_bug.cgi?id=1574648
=> Servo: set tc_root_url to community-tc instead of taskcluster.net

schemas/performance-artifact.json
The [same change](https://phabricator.services.mozilla.com/D52136) is landed on mozilla-central.
=> Bug 1595018 - Temporarily allow maxLength of 100 for extra options

docs/pulseload.md, docs/submitting_data.md, treeherder/etl/common.py, treeherder/etl/management/commands/ingest_push_and_tasks.py, treeherder/etl/runnable_jobs.py, treeherder/middleware.py, treeherder/model/fixtures/repository.json, treeherder/seta/update_job_priority.py, ui/job-view/headerbars/InfraMenu.jsx
This is the second part of pr #5604 that landed yesterday and Armen reverted today because he wanted only the UI changes to land on production without the changes to the repository fixture (for firefox-ci).
I'm going to merge it today so I can test out the third party login, but I won't promote it to production until tomorrow.
=> Tc migration prep part2

.neutrinorc.js, tests/ui/models/jobs_test.js, treeherder/middleware.py, ui/helpers/auth.js, ui/helpers/taskcluster.js, ui/helpers/url.js, ui/login-callback/LoginCallback.jsx, ui/login-callback/index.jsx, ui/models/job.js, ui/models/taskcluster.js, ui/shared/CallbackMessage.jsx, ui/shared/ErrorMessages.jsx, ui/shared/auth/AuthService.js, ui/shared/auth/Login.jsx, ui/taskcluster-auth-callback/TaskclusterCallback.jsx, ui/taskcluster-auth-callback/constants.js, ui/taskcluster-auth-callback/index.jsx
This pr decouples taskcluster credentials from Auth0, which is kept strictly for user login and session management. _For reasons mentioned below, please only review the new login and taskcluster credential flows._
How to test these changes:
1) Login in to Treeherder - you'll need to grant permission to treeherder.mozilla.org and login continues as usual.
2) Perform a taskcluster action that requires credentials, like triggering a job. A new window will open redirecting the user to the taskcluster staging instance, and requires a login with auth0 or github. This won't show every time and I think @helfi92 had mentioned that someone is working on streamlining this for firefox-ci. After credentials are saved the window will close. 
3) You'll also notice the TC action probably won't work …
=> Bug 1566190 - Implement Taskcluster login change

.travis.yml
I've seen a Travis build fail because it was trying to build 12.13.0 from scratch and it timed out.
The other two Python tests on Travis are already pinning the Node version and they have not had this issue anymore.
=> Fix Node version for Selenium tests

.eslintrc.js, tests/ui/models/jobs_test.js, tests/ui/perfherder/selector_card_test.jsx, tests/ui/push-health/TestFailure_test.jsx, ui/helpers/filter.js, ui/helpers/job.js, ui/helpers/url.js, ui/job-view/details/tabs/AnnotationsTab.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/redux/stores/pushes.js, ui/models/filter.js, ui/models/job.js, ui/models/runnableJob.js, ui/perfherder/compare/CompareSubtestsView.jsx, ui/perfherder/compare/CompareView.jsx, ui/perfherder/compare/ReplicatesGraph.jsx, ui/perfherder/graphs/GraphTooltip.jsx, ui/perfherder/graphs/GraphsView.jsx, ui/perfherder/graphs/TestDataModal.jsx, ui/perfherder/helpers.js, ui/push-health/Job.jsx, ui/shared/JobInfo.jsx
Reenabled camelCase rule and fixed all violations in the code base.
There's a failing test `tests/ui/job-view/Filtering_test.jsx`, but it also fail on the master branch, so probably not due to changes in this PR. Running a diff on the output from `yarn test` both on master and the new branch confirms that no new tests fail because of this PR.
Update: The failing test was due to an old `node` version I had on my machine, after upgrading to `v12.13.0` all tests pass.
Close #5457
=> Reenable camelCase eslint rule

treeherder/middleware.py
I added `https://*.taskcluster.net` in pr #5629 , but we also need `https://taskcluster-artifacts.net` for the redirect since the existing `*.taskcluster-artifacts.net` entry doesn't whitelist the domain (only sub domains).
=> Bug 1595639 - Update CSP connect-src

package.json, tests/ui/push-health/UnsupportedJob_test.jsx, treeherder/push_health/push_health.py, treeherder/push_health/similar_jobs.py, treeherder/webapp/api/push.py, ui/push-health/TestFailures.jsx, ui/push-health/UnsupportedGroup.jsx, ui/push-health/UnsupportedJob.jsx, yarn.lock
This will show all jobs that are ``testfailed`` in the push, but are not able to be analyzed by Push Health.  It will provide links to write a bug against the test, see the job in streeherder, and look at the ``_errorsummary.log``, if present, to help analyze why it's not creating ``FailureLine`` records.
It will look like:
=> Bug 1585483 - Find jobs with unsupported tests

ui/intermittent-failures/BugDetailsView.jsx
only show bug number in page title if summary is unavailable
=> Bug 1596515 - IFV bug details title fix

treeherder/webapp/api/performance_data.py, ui/perfherder/graphs/GraphTooltip.jsx, ui/perfherder/graphs/GraphsContainer.jsx, ui/perfherder/graphs/GraphsView.jsx, ui/perfherder/helpers.js
The id for PerformanceDatum was mistakenly not carried over during the conversion, so there wasn't an accurate way to show tooltip data for retriggers. This pr adds the id to the `PerformanceSummary` api and modifies the `selected` param to include this id (backwards-compatible so won't break old links).
=> Bug 1591076 - Fix tooltip popup to support retriggers

tests/model/test_cycle_data.py, treeherder/model/management/commands/cycle_data.py, treeherder/model/models.py
This removes the cycling on a per-repo basis.  Now that our DB isn't segragated by repo, it is unnecessary.  Cycling by repo is going to be slower and leave holes (fragments) in the table on each delete.
=> Bug 1597136 - Optimize cycle_data to fragment table less

ui/perfherder/compare/CompareSubtestsView.jsx
This patch only adds a condition to fix loading spinner if test results are returned without data. I need to investigate why the Perfherder alerts has generated a link to a tests for a specific revision that we don't have data for.
=> Bug 1598037 - Perfherder subtests view fix

schemas/performance-artifact.json
[Back to Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1597634)
=> Bug 1597634 - Mirror CI schema support for public suite & test names

treeherder/model/management/commands/cycle_data.py
Fix typo from pr #5669 that's causing papertrail alerts. Interesting that our python linting didn't catch it before it was merged.
=> Fix cycle_data logger typo

treeherder/perf/alerts.py, treeherder/webapp/api/performance_data.py
Removed order_by in generate_new_alerts_in_series and performance/datum list API. These both seemed to have a significant effect on execution time, however the performance datum API is still not as fast as it could be. More details in the bug.
FYI @klahnakoski and @ionutgoldan
=> Bug 1597476 - Optimize perf datum queries

treeherder/perf/fixtures/performance_bug_templates.yaml
Due to the recent expansion of the sheriffing team, I updated the regression template to avoid spamming all team members when a regression bug is open from an alert.
=> Bug 1600932 - Avoid CCing all Perf sheriffs

ui/intermittent-failures/MainView.jsx, ui/intermittent-failures/View.jsx
Makes it easier to find the worst offenders in a component.
=> Bug 1601725 - Add product/component column to intermittent-failures view.

tests/ui/perfherder/compare_table_test.jsx, ui/css/perf.css, ui/css/treeherder-navbar.css, ui/perfherder/Validation.jsx, ui/perfherder/compare/CompareSubtestsView.jsx, ui/perfherder/compare/CompareTable.jsx, ui/perfherder/compare/CompareTableControls.jsx, ui/perfherder/compare/CompareTableRow.jsx, ui/perfherder/compare/CompareTableView.jsx, ui/perfherder/compare/CompareView.jsx, ui/perfherder/helpers.js
The permalinks feature in the Perfherder compare and compare subtests view (click on the # symbol when hovering over a table header or row) that landed right before the switch to react router wasn't translated very nicely on my part. 
Two things were addressed in this pr:
1. Due to differences between how UI-router and react-router designate the parent container, `scrollIntoView` meant the element would always hide behind the top navbar. Using `scrollTo` with an offset was the solution.
2. The scroll function had a lag due to history being replaced with the new hash in `onPermalinkClick`. This is because any change to the history or location object will trigger a new render, so I added a condition at the top level `Validation` component with `shouldComponentUpdate`.
I also moved the …
=> Bug 1594416 - Fix perf permalinks

ui/css/treeherder-navbar.css, ui/job-view/headerbars/TiersMenu.jsx, ui/perfherder/alerts/AlertHeader.jsx, ui/perfherder/alerts/StatusDropdown.jsx, ui/perfherder/compare/SelectorCard.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/Metric.jsx, ui/shared/DropdownMenuItems.jsx
Hi @sarah-clements and @camd,
The **dropdown** components of Treeherder are not accessible to screen reader/keyboard users. 
According to [W3C's WAI](https://www.w3.org/TR/wai-aria-practices-1.1/#menubutton) (Web Accessibility Initiative), dropdowns are composed by a **menu button** that toggles a **menu**/**menu bar**. As a general rule:
- _space_ and _enter_ keys should open the menu and the _first item_ should be focused;
- the menu should be navigable by using the _arrow, home and end keys_.
- the menu should be closed by pressing the _esc key._
So far, these issues were detected:
**A**. It was noted that `LogoMenu` component worked properly, with both _space_ and _enter_ keys. It was also noted that in the [Reactstrap's Dropdown …
=> Bug 1600757 - Dropdown menu screen reader keyboard support

ui/push-health/ClassificationGroup.jsx, ui/push-health/Metric.jsx
The Push Health view has some +/- graphic elements that informs the user if the row is expanded or not. Although it is already using a good practice of setting a `<title>` of explaining the icon for SR users, the best practice would be to also insert the `aria-expanded` attribute.
- The `aria-expanded attribute` was introduced in the **clickable elements**.
- The `<title>` descriptions were changed to inform the SR user the look of the icon. [Reference link, 2. Inline SVG](https://css-tricks.com/accessible-svgs/#article-header-id-1).
The changes were tested via NVDA navigation. Since the SR reads 'collapsed' or 'expanded' depending on the button state, the text choice for the `<title>` was to describe the visual of the icon.
=> Bug 1603251 - Improve expand/collapse component for screen reader users

ui/css/perf.css, ui/perfherder/ProgressBar.jsx, ui/perfherder/alerts/AlertHeader.jsx, ui/perfherder/alerts/AlertTable.jsx, ui/perfherder/alerts/AlertTableRow.jsx, ui/perfherder/compare/CompareTable.jsx, ui/perfherder/compare/CompareTableRow.jsx, ui/shared/TruncatedText.jsx
There are a few suggested changes to improve accessibility in Perfherder's Compare and Alert Views:
As most of the tasks were straightforward, I'm going to point their location and some comments below:
- **1a**. `ProgressBar.jsx`: According to [Reactstrap Github](https://github.com/reactstrap/reactstrap/issues/1681), there are still some issues in ProgressBar element. In this element, the props are not spread, making it not possible to insert more `aria-` attributes. The proposed solution is to insert an `aria-label` on the wrapper ProgressBar, insert a `.sr-only` `<span>` element with the description and insert a Table Header in `CompareTable.jsx:127`.
- **1b**. `CompareTable.jsx`
- **1c**: `perf.css:272:303`: I tried to show the links only when the table was focused, but the `:focus` …
=> Bug 1600752 - Accessibility improvements Compare and Alert Views

treeherder/push_health/performance.py, treeherder/webapp/api/push.py, ui/push-health/Health.jsx
This is a very simplistic start to this metric.  It just checks if there are any failed tasks that are in a performance group and lists those.  We will make this better in the months to come, but it's a start.
=> Bug 1604324 - Push Health show failed performance tasks

tests/ui/push-health/TestFailure_test.jsx, treeherder/push_health/classification.py, treeherder/push_health/similar_jobs.py, treeherder/push_health/tests.py, ui/push-health/TestFailure.jsx
This fixes two bugs that were sort-of related, so I put them into this same PR.
The first introduces the concept of a Pass/Fail ratio to the user.  We were using it in the back-end calculation before, but now we're surfacing it to help the user understand the criteria for retriggered jobs and intermittents.
The second is just making sure a "Needs Investigation" test never has a confidence higher than 90% for being Intermittent or Fixed By Commit.  If we DID have 100% confidence, they wouldn't need investigation.  :)
=> Bug 1600625 - Add explanation for rules of an intermittent

treeherder/webapp/api/push.py, ui/job-view/pushes/PushHeader.jsx, ui/models/push.js, ui/shared/PushHealthStatus.jsx
This modifies the ``health_summary`` api to require a ``revision`` rather than a ``push_id``.  This will make it easier for outside tools to use it.
I also noticed that I was calling the endpoint too many times during page load.  So the second commit fixes that.
=> Bug 1605214 - Improve Push.health_summary API

ui/job-view/App.jsx
Uses a React Fragment to clear the below warning for `Filtering_test.jsx`, as discussed [here](https://github.com/mozilla/treeherder/issues/5721#issuecomment-565055568) - 
```js
% yarn test tests/ui/job-view/Filtering_test.jsx
yarn run v1.19.2
$ node ./node_modules/jest/bin/jest tests/ui/job-view/Filtering_test.jsx
PASS  tests/ui/job-view/Filtering_test.jsx (11.762s)
● Console
console.error node_modules/prop-types/checkPropTypes.js:20
Warning: Failed prop type: The prop `children` is marked as required in `Pane`, but its value is `undefined`.
in Pane (created by SplitPane)
in SplitPane (at App.jsx:340)
in div (created by FocusTrap)
in FocusTrap (created by HotKeys)
in HotKeys (at KeyboardShortcuts.jsx:239)
in KeyboardShortcuts (created by ConnectFunction)
in ConnectFunction (at …
```
=> Clear test warnings for Filtering_test.jsx

tests/ui/mock/push_health.json, treeherder/push_health/similar_jobs.py, treeherder/push_health/tests.py, ui/push-health/Job.jsx, ui/push-health/TestFailure.jsx
This just shows any in-progress jobs that are the same ``platform``, ``config`` and ``job_type`` as one of the failures being displayed.  This is so it shows them when they are retriggered.
=> Bug 1602969 - Show matching in-progress jobs for failures

ui/css/perf.css, ui/perfherder/compare/RevisionInformation.jsx
Fixes Bug 1487761.
The revision comments were supposed to be displayed,
but we were looking at the wrong place to do so.
This patch fixes this, so revision comments are displayed
under the revision number + author.
The layout is changed to flex to do this properly.
Colors are tweaked a bit in order to pass WCAG standard.
This is how it looks:
=> Display revision comments in RevisionInformation.

ui/css/intermittent-failures.css, ui/intermittent-failures/MainView.jsx, ui/intermittent-failures/helpers.js
For the attribute insertion, they needed to be passed down by ReactTable props, such as `getTableProps`. The passed function is declared in `ui/intermittent-failures/helpers.js`.
The other tasks were solved via CSS.
Simple NVDA navigation and visual test on the CSS related tasks. Other views were also tested - only one view has the same React Table component, Perfherder Health, but apparently they are not linked.
=> Bug 1603241 - Accessibility improvements in Intermittent Failures View

treeherder/config/settings.py
Setting the DEBUG variable enables Django in a debug mode and it requires
the package `django_extensions`.
Changing the logging level should not require more than that. This change decouples both
and it supports the previous behaviour if still needed.
=> Allow changing logging level with environment variable

docs/installation.md, treeherder/etl/management/commands/ingest.py
…ko decision task
I noticed that we can ingest all tasks for a push without having to parse all logs by not
enabling eager celery consumption. If the user would like to do so it is still possible.
You can now also specify `--gecko-decision-task` to specify the Gecko decision task
associated to a push/revision. In the future we can determine this for the user but for
now we can just require it to be inputted manually.
A sample command:
```
./manage.py ingest push --project mozilla-central --revision fc3002cb85dc4d2c44d8aec1246f0356097411e3 --ingest-all-tasks --gecko-decision-task YiQiigCNQl63Hm21DjxXlA
```
=> Manual ingestion improvements

tests/ui/perfherder/graphs_view_test.jsx, ui/css/perf.css, ui/job-view/details/DetailsPanel.jsx, ui/perfherder/graphs/GraphTooltip.jsx, ui/perfherder/graphs/GraphsContainer.jsx, ui/perfherder/graphs/GraphsView.jsx, ui/perfherder/helpers.js
This pr fixes the issue with the graphs tooltip becoming unaligned with its datapoint any time the viewport falls below the graph containers specified width. This only happens when the graphs are in responsive mode, which they are currently set to:
Rather than trying to attach event listeners to change the absolute positioning on window resize (or trying my media query suggestions in the bug, which didn't actually work), I took another stab at incorporating the custom tooltip into the Victory library. This means the tooltip is rendered as an svg within the graph, and will scale in tandem. Doing this is not clearly documented so it took a bit of digging and experimenting. The tool tip now scales appropriately.
The upside of making these changes is that the tooltip is now testable! This …
=> Bug 1581497 - Change Perfherder graph tooltips

ui/perfherder/alerts/AlertHeader.jsx
This PR fixes the following error:
Remove the additional `<a>` and keep only `<DropdownItem>`.
Compared the visual appearance and functionality of the element to the production version.
=> Anchor-Dropdown fix for AlertHeader

ui/push-health/ClassificationGroup.jsx, ui/push-health/Health.jsx, ui/push-health/JobListMetric.jsx, ui/push-health/Metric.jsx, ui/push-health/Navigation.jsx, ui/push-health/TestMetric.jsx, ui/push-health/helpers.js
This adds a navigation bar to the top of the screen to get a quick status of each metric.  They're click-able to show/hide each as well.
Also, when a metric is hidden, it hides it all the way.  Before, it would leave the header present.  The top row negates the usefulness of this header on each metric when hidden.
Before:
After:
=> Bug 1608260 - Reduce noise in Push Health UI and add concise status

app.json, treeherder/etl/management/commands/pulse_listener_pushes.py, treeherder/etl/management/commands/pulse_listener_tasks.py, treeherder/etl/tasks/pulse_tasks.py
…cluster instance
The Pulse sources are configured differently on Heroku Review Apps because `PULSE_PUSH_SOURCES`
and `PULSE_TASK_SOURCES` are defined as arrays rather than a string.
This is because `app.json` is a Json file and we cannot specify an array by mixing single & double
quotes.
=> Heroku Review Apps to default to the Firefox CI

ui/css/perf.css, ui/perfherder/graphs/GraphTooltip.jsx, ui/shared/Clipboard.jsx
There was a recent change to the tooltip to make it render as an SVG and what I didn't realize is that there wasn't a way to select text once the tooltip was locked. I added css to fix that and included the Clipboard component to make copying easier for the revision sha (since that's what Perf sheriffs need to copy).
=> Bug 1609140 - Perfherder tooltip fix

ui/perfherder/graphs/LegendCard.jsx
This patch fixes some weird behavior with the Perfherder graph legends, that only occurred in very specific circumstances. One circumstance is when the user deselects one test and selects another, the selected test would plot white data points (white is a library default) instead of the new color because the 'z' attribute on each data point hadn't been updated with the new color. 
Another circumstance is when a test is removed but its gray border color is incorrectly pushed into the colors list. So the next time a test is added, it gets that color instead of an actual color and the data points will also plot as white, per the screenshot below. There's logic to now check for that. I left a comment in that part of the code base, but let me know if its not clear.
FYI @yogmel This is the …
=> Bug 1583989 - Fix Perfherder graph colors

tests/ui/push-health/TestFailure_test.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/GroupedTests.jsx, ui/push-health/TestFailure.jsx
This addresses [Bug 1602833](https://bugzilla.mozilla.org/show_bug.cgi?id=1602833)
Before expanding:
After expanding:
The intent here is to add some better organizing/sorting and reduce noise, initially.  So this adds two buttons to the "Need Investigation" section to ``Group By`` and ``Order By``.  These default to ``path`` and ``count``.  This also collapses those groups by default.  If the tests are grouped by either ``platform`` or ``test path`` then we hide that value from each individual test (to reduce screen noise).
I will persist these settings in the URL in a follow-up PR.
=> Bug 1602833 - Group failures by platform and config

treeherder/push_health/similar_jobs.py, treeherder/push_health/tests.py, ui/push-health/TestFailure.jsx
This just shows the Job Group that jobs belong to.  But it also now uses it to ensure we don't lump jobs from different groups together.  Here is what it will look like visually Note the ``M-1proc``:
=> Bug 1602493 - Show Job Groups for test failures

treeherder/seta/settings.py
Currently SETA is restricted to only accept API calls for autoland and mozilla-inbound:
https://github.com/mozilla/treeherder/blob/ffaa2e4b2af200d3ae91e3e6ecdc2d4e4f093e84/treeherder/seta/settings.py#L2
To keep our options open with smart scheduling experiments and solutions, we should expand that list to have 'Try'. While we are at it remove 'mozilla-inbound'.
=> Bug 1609975 - SETA to be enabled for Try

tests/ui/mock/push_health.json, tests/ui/push-health/GroupedTests_test.jsx, tests/ui/push-health/TestFailure_test.jsx, ui/perfherder/FilterControls.jsx, ui/perfherder/graphs/TestDataModal.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/GroupedTests.jsx, ui/push-health/Health.jsx, ui/push-health/TestMetric.jsx, ui/push-health/helpers.js, ui/shared/InputFilter.jsx, yarn.lock
Addresses [Bug 1610705](https://bugzilla.mozilla.org/show_bug.cgi?id=1610705)
This enables filtering by Test Path, Platform and Config (opt, asan, debug, etc).  You can type in any number of space-separated terms and it will filter with AND for each term.  It does it on every keystroke, so it's super-responsive.  But if it ends up being clunky when there are lots of tests, then I may need to introduce a debounce to it.  For now, though, the list is short enough that it's super quick.  It's persisted in the URL, too.
The box is in the upper-right corner:
First commit
-------------
The first commit fixes the data format returned by the API.  It had actually become out of date a few commits ago, but I hadn't fixed it.  The code still worked because of how the test was written.  So I fixed …
=> Bug 1610705 - Add filtering by Test path

treeherder/config/settings.py, ui/shared/auth/AuthService.js, ui/shared/auth/Login.jsx
I figured out the crux of the issue: The x-frame-options default was changed from "sameorigin" to "deny" in [django 3 ](https://docs.djangoproject.com/en/3.0/ref/clickjacking/#setting-x-frame-options-for-all-responses) and this was preventing the auth0 silent renewal (happens every 15 minutes) from completing and causing a timeout.
I changed the try/catch block in the renewal function to log out a user if there is any error whatsoever, and to ensure that is reflected in the UI (change the display back to Login/Register, which it wasn't doing before).
I tested this out on prototype and I do see a script-src being blocked every 15 minutes, but not the error showing the renewal failed (also opening another tab showed the user is still logged in).
=> Bug 1444895 - Fix frequent logout issue with Treeherder

ui/job-view/App.jsx, ui/shared/PushHealthStatus.jsx
This enables the Push Health badge on the Push Header on Try by default.  If the user has already made a choice, it keeps that.
I also cleaned up some wording.
=> Bug 1611334 - Enable Push Health badge on Try by default

ui/shared/auth/AuthService.js
Minor change to only log out the user when the silent renewal fails AND the current access
token has expired
=> Bug 1444895 - Auth login fix follow up

ui/job-view/pushes/Push.jsx
During [review time](https://github.com/mozilla/treeherder/pull/5794#discussion_r369780355) we introduced a small bug in the test filtering feature.
Reading `jobList` at the begining of the function instead of just before calling `mapPushJobs` almost guaranteed to start with an empty list which makes the call useless since it needs a non-empty list to work.
I also changed the code to call `this.setState` with a callback to `mapPushJobs` to guarantee that `jobTypeNameToManifests` is set in the state and not get an empty object.
```diff
diff --git a/ui/job-view/pushes/Push.jsx b/ui/job-view/pushes/Push.jsx
index 8e0e96547..0a79c394a 100644
--- a/ui/job-view/pushes/Push.jsx
+++ b/ui/job-view/pushes/Push.jsx
@@ -163,15 +163,18 @@ class Push extends React.PureComponent {
fetchTestManifests = …
```
=> Solve race condition for test path filtering

treeherder/webapp/api/push.py, ui/shared/PushHealthStatus.jsx
This fixes several issue:
1. The `/health_summary` endpoint was not showing `unsupported` count, which made a push with unsupported jobs show as ``OK`` when it should call them out.
2. The overall `/health` endpoint was only showing `pass` or `fail`.  Now it also shows ``indeterminate`` if there are no failures, but include unsupported tasks.
3. The UI was also not taking `unsupported` jobs into consideration.  
This also adds an icon to the `PushHeader` badge and a loading spinner.
=> Bug 1611485 - Fix inconsistencies with Push Health badge

ui/job-view/pushes/Push.jsx
This is my fault.  I ASKED you to change it to the code that's there.  :)  I forgot that this particular area is a little brittle and the instances of the jobs matter, not just the contents.  I need to fix this.
=> Bug 1612000 - Fix classified jobs disappearing at right time

ui/css/intermittent-failures.css, ui/css/perf.css, ui/css/treeherder-global.css, ui/css/treeherder-job-buttons.css, ui/css/treeherder-navbar.css, ui/css/treeherder-resultsets.css, ui/css/treeherder-test-view.css, ui/css/treeherder-userguide.css, ui/intermittent-failures/helpers.js, ui/job-view/headerbars/SecondaryNavBar.jsx, ui/job-view/pushes/JobGroup.jsx, ui/perfherder/FilterControls.jsx, ui/perfherder/alerts/AlertHeader.jsx, ui/perfherder/alerts/AlertTable.jsx, ui/perfherder/alerts/AlertTableRow.jsx, ui/perfherder/alerts/AlertsView.jsx, ui/perfherder/alerts/Assignee.jsx, ui/perfherder/alerts/StatusDropdown.jsx, ui/perfherder/compare/CompareSelectorView.jsx, ui/perfherder/graphs/GraphTooltip.jsx, ui/perfherder/graphs/GraphsViewControls.jsx, ui/perfherder/graphs/TestDataModal.jsx
Some color combinations does not pass the [WCAG contrast](https://developer.mozilla.org/pt-BR/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast?utm_source=devtools&utm_medium=a11y-panel-checks-color-contrast) recommendation.
Also, for color blindness distinction, texts with red and green should be accompanied by an icon.
Using _Firefox Accessibility Inspector_'s beta "Check for issues", I've checked for "**_Contrast_**" issues. That was done for each view and a different commit was made. Then, it was a manual color tweaking of each issue. 
Some colors became harder to distinguish because of the contrast rate.  That was seem mostly in blue and green colors. Maybe propose a **different color hue**?
Those were mostly visual and using Accessibility and Inspector devtools …
=> 1600761 - Visual/Color improvements to Treeherder apps

tests/ui/perfherder/graphs_view_test.jsx, ui/css/perf.css, ui/perfherder/constants.js, ui/perfherder/graphs/GraphsContainer.jsx, ui/perfherder/graphs/GraphsView.jsx, ui/perfherder/graphs/LegendCard.jsx, ui/perfherder/helpers.js, ui/shared/GraphIcon.jsx
The Graph view in Perfherder is not very usable for color blind users, mainly when there are multiple types of data plotted.
To improve it, it was suggested to choose a friendlier **color palette** and also use auxiliary **symbols** to help distinguish between data.
- In order to change the graph symbols, the `VictoryScatter` prop [`symbol`](https://formidable.com/open-source/victory/docs/victory-scatter/#symbol) in VictoryChart's library was used. The symbol name is passed from `GraphView` to `GraphContainer`, based on the stored value from `constants.js`
- In `LegendCard`, the name of the symbols have been retrieved, but in order to insert the icon, some decisions must be made - the icons are `<svg>` and live in another file? Are they React Components? Maybe we could use the same svg …
=> Bug 1574628 - Improve graph colors and add symbols

docs/installation.md
This section was confusing for a contributor since it does not actually work (The MySql container is not ready) and the Django migrations are now automatically applied when running `docker-compose up`.
=> Remove section about applying migrations

.gitignore, .travis.yml, requirements/dev.txt, runtests.sh
This is based on #5860 
I need to test the branch using our codecov account rather than [shubhank-saxena](https://codecov.io/gh/shubhank-saxena/treeherder)'s set up.
=> Add Python test coverage to codecov

app.json
* From $24/mo to $39/mo
* Dedicated RAM instead of shared
* Single Tenant
* 66 connections instead of 30
* 5GB instead of 2.5GB of storage
=> Heroku Review Apps: Bump the plan for JawsDB

docker/entrypoint.sh
Since we do not want to execute it against live production databases.
This fixes a change introduced in #5851 
One reviewer is sufficient, however, I want both of you to be aware of it.
=> Bug 1611502 - Do not run initialize_data when using DATABASE_URL

ui/perfherder/constants.js, ui/shared/GraphIcon.jsx
The newly implemented triangle icon in Perfherder's graph can be misleading (it could be read as a trend).
Change the triangle icon to **diamond**.
Now, there are 3 icons: square, triangle, and diamond that could be either color filled or just with stroke.
=> Bug 1574628 - Change Perfherder's icon

ui/job-view/headerbars/WatchedRepo.jsx
BugZilla Link : https://bugzilla.mozilla.org/show_bug.cgi?id=1608148
Here the treestatus URL "/treestatus/show/${treeStatusName}" needs to be updated to"/static/ui/treestatus/show/${treeStatusName}" according to the Issue explained in the link above.
Please Review it and let me know
=> Bug 1608148 - Update Treestatus URL

ui/job-view/pushes/PushHeader.jsx, ui/shared/PushHealthStatus.jsx
The use of the word `tests` is not always accurate.  They could be linting or build tasks.  So changing this to the more generic `items` is better.  Also made it a bit shorter.  And added a space between this badge and the count of `fixed by commit` tasks.
=> Bug 1613302 - Better wording on Push Health Status wrt Need Investigation

tests/ui/push-health/PushParent_test.jsx, ui/job-view/pushes/PushHeader.jsx, ui/shared/PushHealthStatus.jsx
This reverts commit 7e39d90a85617384f7b1fb9eaba857c5db49aaac.
Better wording on Push Health summary badge.
Fixed test to look for new wording of Push Health Badge.
=> Bug 1613302 - Revert and fix for Revert of Better wording on Push Health Status

ui/css/intermittent-failures.css, ui/intermittent-failures/GraphAlternateView.jsx, ui/intermittent-failures/GraphsContainer.jsx, ui/intermittent-failures/helpers.js
It is noted that the Graph in Intermittent Failures View is not accessible via Screen Reader. There are two tables:
- Failures Count per Push
- Failures Count vs Push Count
As discussed, we decided to try on an alternate view as a table. The user can change the view from Graph to Table, via a toggle button. 
NVDA navigation to test if the table was SR accessible. Also compared with the graph and console log of data, to check if data in the table was being mirrored.
=> Bug 1603269 - Alt. View for Intermittent Failures View for Screen Reader

ui/css/treeherder-job-buttons.css, ui/css/treeherder-userguide.css
Running and pending jobs are not very discernable after the first 1600761 push.
On the jobs view, the border can either be seen by default or only by hovering the mouse:
**No border**
**Border**
=> Bug 1600761 - Color Adjustment for running and pending jobs

ui/job-view/pushes/PushActionMenu.jsx
I've wanted to look at the performance comparison of push to try a few times recently, and I got annoyed buy having to copy the tip revision of the push and then navigate to perfherder, so I added a link in the push menu (where I went looking for an option to do that).
It turns out that the performance tab of a job also has that info (which I discovered looking at the code).
=> Add a quick link to compare a given revision in perfherder.

app.json
This reverts commit 634d056e3d9cbeee4468a84a1683b25bfaba8c50.
This is due to the add-on taking longer to start up than the shared add-on
*and* the release step not executing as the last step, thus, the DB is not
avalaible for the release step.
I have filed a Heroku ticket to solve this.
=> Revert "Heroku Review Apps: Bump the plan for JawsDB (#5948)"

docs/accessibility.md, ui/css/treeherder-global.css
Related: #5920 
Add style specs in case `darker-secondary` and `darker-info` color props are used in other reactstrap components in the future.
E.g. `Button`, `Progress`, or in `className` in case of `.text-darker-*`
=> Add style for darker colors

ui/perfherder/helpers.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1614581
prior to my changes, the only possible values for `branches` were `['autoland']` or `['mozilla-inbound']`
after confirming with @ionutgoldan that this is unlikely to change, I have removed the mapping and filtering, and left only URLs for autoland
=> Bug 1614581 - Remove related mozilla-inbound series when clicking through from Alerts view

treeherder/config/settings.py
Unfortunately it was being cast down to False rather than "INFO" or "DEBUG".
There were no fallouts from it but it was preventing setting the right logging
level for the Docker container or the Heroku Review Apps.
=> Properly configure LOGGING_LEVEL

ui/perfherder/FilterControls.jsx, ui/perfherder/graphs/TestDataModal.jsx, ui/shared/DropdownMenuItems.jsx
replacing #5996 to fix branch name so it matches the correct bug number
fixed the autoland typo, filtered the `pinned` mapping to only display values also found in `options`
=> Bug 1614404 - Group common repositories

treeherder/seta/job_priorities.py, treeherder/seta/preseed.py, treeherder/seta/settings.py
Expiration dates are set for new jobs for a period of two weeks where
a job's priority is not allowed to change.
For preseed jobs it is expected to never change yet we should include
them.
=> Seta: Include job priorities that are set to expire in the future

.travis.yml
If any step on the Travis run fails (like formatting checks or a test) then
we don't report the code coverage for it.
Unfortunately, this can be distracting when we see status checks
reporting a failure or a big change.
This change makes code coverage to report even if there are minor
failures.
=> Make coverage reporting fluctuate less

ui/css/treeherder-global.css, ui/intermittent-failures/BugColumn.jsx, ui/job-view/App.jsx, ui/job-view/details/PinBoard.jsx, ui/job-view/details/tabs/AnnotationsTab.jsx, ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx, ui/job-view/headerbars/ActiveFilters.jsx, ui/job-view/headerbars/SecondaryNavBar.jsx, ui/job-view/pushes/PushJobs.jsx, ui/job-view/pushes/PushList.jsx, ui/perfherder/compare/CompareTable.jsx, ui/perfherder/graphs/LegendCard.jsx, ui/test-view/ui/Test.jsx
There are rules disabled in some components. This removes the exceptions for a11y ESlint rules and fix them.
Note: `ActionBar`, `FiltersMenu` and `PushActionMenu` were not changed, as they were fixed in another PR.
=> Bug 1513583 - Enable ESLint a11y rules

treeherder/middleware.py, ui/helpers/taskcluster.js, ui/job-view/headerbars/InfraMenu.jsx, ui/job-view/pushes/Push.jsx, ui/login-callback/LoginCallback.jsx, ui/taskcluster-auth-callback/constants.js
Some preliminary work for both bug 1616329 (add the clientId for authentication) and for the new treeherder-taskcluster-staging instance.
=> Bug 1613265 - Update rootUrls and clientIds for new deployments

ui/css/perf.css, ui/css/treeherder-custom-styles.css, ui/css/treeherder-details-panel.css, ui/css/treeherder-navbar-panels.css, ui/css/treeherder-pinboard.css
This PR fixes some styles caused by enabling a11y ESLint, as pointed out [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1618619).
**Active filters**
**Get Next buttons**
-----------------
**Show / Hide more button in Failure Summary**
**Pinboard Bug icon**
**Pinboard Add related bugs**
---------------
**Legend Cards**
=> Bug 1618619 - Fix font differences caused by ESLint

ui/job-view/headerbars/TierIndicator.jsx
This prevents React from complaining about the missing key attributes.
=> Bug 1618755 - Add unique key attributes for TierIndicator buttons

tests/ui/job-view/Filtering_test.jsx, ui/job-view/pushes/PushHeader.jsx
There is a little bit of GraphQL api activity.  So I want to remove this button first, without deleting the app.  Perhaps people are hitting it occasionally out of curiosity.  Otherwise I will have to track down who is linking to it.  :)
=> Bug 1611334 - Remove View Tests button from PushHeader

ui/shared/PushHealthStatus.jsx
This adds an `In progress` state when there are no failures, but also more running jobs.  We only show the "check OK" when all jobs are complete with no failures or unsupported jobs.
=> Bug 1619679 - Fix Push Health Status badge to be more accurate

ui/job-view/headerbars/WatchedRepo.jsx, ui/models/treeStatus.js
New trees are set up that are named the same as the repositories.
The getTreeStatusName is no longer needed.
The trees themselves are created, but the hooks on hg.mozilla.org are not updated yet. So please don't deploy this just yet.
I did test changes locally against stage and I got some funny errors with TierIndicator keys. I don't think I caused those?
=> Bug 1619017 - Remove exception code for Thunderbird treenames in TreeStatus

tests/push_health/test_compare.py, tests/ui/mock/push_health.json, tests/ui/push-health/CommitHistory_test.jsx, treeherder/push_health/compare.py, ui/push-health/CommitHistory.jsx
I used the wrong link for the Parent Push in my last PR.  So it would link back to the same Push as the one it's showing the health for, rather than its parent.  The word `revision` is too ambiguous.  So I added some docs and used a better name.
=> Bug 1616311 - Fix link for the Parent Push

ui/perfherder/alerts/AlertsView.jsx
This is a fix for [Bug 1565480](https://bugzilla.mozilla.org/show_bug.cgi?id=1565480) that didn't kept update param of fetchAlertSummaries to true used to update alert statuses.
Recordings: [before](https://mozilla.zoom.us/rec/share/wZ1KD-H7-39JXJHy6nHGRYQwH6n4aaa8g3Ac_vUKmEwTcAhHyDy5QB9behtM74g?startTime=1582186704000) | [after](https://mozilla.zoom.us/rec/share/wZ1KD-H7-39JXJHy6nHGRYQwH6n4aaa8g3Ac_vUKmEwTcAhHyDy5QB9behtM74g?startTime=1582186417000)
=> Bug 1615535 Changing alert's status/assignee changes page's content

ui/job-view/pushes/PushList.jsx
PushList component should not have `role=button`. It should be `list` and its child elements, `listitem` instead.
Because PushList is interactive (that is, it has a `onClick` handler), ESLint doesn't accept `list` role. For that reason, I used `grid` and `gridcells`, as it was suggested in [ESLint repository](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-interactions.md).
=> Bug 1619873 - Change push-list role

treeherder/extract/extract_perf.json
The chunk size of 4000 results in BigQuery uploads that are too big.
=> BigQuery extraction to use smaller chunks for performance data

tests/push_health/test_compare.py, tests/ui/mock/push_health.json, tests/ui/push-health/CommitHistory_test.jsx, treeherder/push_health/compare.py, ui/push-health/App.jsx, ui/push-health/CommitHistory.jsx, ui/push-health/Health.jsx, ui/shared/PushHealthStatus.jsx
This is a refactor to make these a few of these more test-able and improve the testing of them, therein.
The terms `revision` and `repository` were getting mixed up in my head with regard to which one was for the `parent` and which one for the `push` in question.  So for the parent ones, I made the name clearer.
In doing this, I realized that the `currentRepo` object getting created in `App` was bogus and never worked right.  Ends up `App` can be greatly simplified, and creating `currentRepo` in `Health.jsx` makes more sense.
I moved a few things around to give them `data-testid` so that they're more test-able.
=> Bug 1620667 - Refactor currentRepo property and CommitHistory layout

.travis.yml, bin/post_compile
This increases the chances of not having a Heroku build & release failure
after the code has been merged to master (since it is not currently executed).
=> Travis: Add Heroku's Python build execution path

treeherder/etl/seta.py, treeherder/seta/common.py, treeherder/seta/job_priorities.py, treeherder/seta/models.py, treeherder/seta/preseed.json, treeherder/seta/preseed.py, treeherder/seta/settings.py, treeherder/seta/update_job_priority.py
This adds a number of additional job types which we may not want to put into production but it is a fairly complete list. I will attach a diff of the job priorities to the bug. This is mostly to get your initial feedback and I expect to make changes depending on your feedback.
=> Bug 1608427 - SETA: Better differentiate different kinds of tasks

ui/perfherder/graphs/GraphTooltip.jsx
Fix the way `prevFlotDataPointIndex` is calculated as the tooltip generates wrong data when the data point indexes are no consecutive.
=> Bug 1618145 Tooltip revision link directs to empty pushlog

.pre-commit-config.yaml
`isort` as part of the pre-commit set up ends up under `$HOME/.cache/pre-commit`.
Due to that, it was unable to determine the path to the `setup.cfg` and was
unable to differentiate third party libraries from first party libraries.
Specifiying where the path to the default virtualenv is fixes it.
=> Fix pre-commit's isort

bin/pre_deploy, docker-compose.yml, tests/push_health/test_usage.py, tests/sample_data/push_usage_data.json, tests/settings.py, tests/ui/mock/health_usage.json, tests/ui/push-health/Usage_test.jsx, treeherder/config/settings.py, treeherder/middleware.py, treeherder/push_health/usage.py, treeherder/webapp/api/push.py, ui/push-health/App.jsx, ui/push-health/Usage.jsx, ui/shared/LogoMenu.jsx
This creates a simple dashboard to show usage in Push Health and whether the count of `needInvestigation` tests has gone down over time (presumably as a result of retriggers).
I'm still working on getting the env var part of the unit test to work.  But the rest of the code will stay the same.  I'll fix it Monday.
=> Bug 1612229 - Push Health Usage Dashboard

schemas/performance-artifact.json
This patch adds the `chrome-m` application to the list of acceptable applications in the perfherder data schema.
=> Add chrome-m application for Chrome Android browser.

treeherder/webapp/api/push.py, ui/push-health/CommitHistory.jsx, ui/push-health/Health.jsx
Disable the Performance metric area.  Leave the library in-place because we will be enhancing it later.
Move the `Commit History` metric closer to the top and expanded by default to improve discoverability.  I wanted to minimize the noise, though, so if there are more than 5 commits, I show the first 5 and add a "more..." type button.
=> Bug 1623165 - Push Health Perf and Commit History UI cleanup

tests/ui/helpers/gzip_test.js, tests/ui/job-view/Push_test.jsx, ui/helpers/gzip.js, ui/job-view/pushes/Push.jsx, ui/models/filter.js
I'm taking the original code to filter by test path and I have added a check to only fetching the artifacts if `test_paths` is included in the URL.
You can look at this commit to see the change from when you last reviewed the code:
https://github.com/mozilla/treeherder/commit/7148f76703c360db7609e89e39bd289edae4c799
You can test with:
http://localhost:5000/#/jobs?repo=mozilla-central&test_paths=browser%2Fcomponents%2Fpayments%2Ftest%2Fmochitest%2Fformautofill%2Ftest_editcreditcard.html
http://localhost:5000/#/jobs?repo=mozilla-central&test_paths=test_editcreditcard.html
=> Bug 1615330 - Support test filtering instead of manifest filtering

docker-compose.yml
`initialize_data.sh` calls exec in the last line, thus, it was trying to execute `&&`
```
backend     | /app/initialize_data.sh: line 11: exec: &&: not found
```
=> Fix failure to initialize docker-compose up

ui/helpers/filter.js, ui/helpers/location.js, ui/helpers/url.js, ui/models/filter.js
Doing a simple split and taking the `1`th element was a bit fragile.  We want the last element.  So this helps with the weird URL mentioned in the bug.  But it would be good to move away from the hashed URLs that we currently use (a holdover from AngularJS).  I opened [Bug 1623951](https://bugzilla.mozilla.org/show_bug.cgi?id=1623951)
I also updated the `push` function in `models/filter.js` to correct this weird case of having an extra `?` character before the hash.  I was not able to figure out a way that it got there in this case.  But can be sure we take it out.  :)
=> Bug 1623589 - Make filter URL handling more resilient

treeherder/perf/fixtures/performance_bug_templates.yaml, treeherder/perf/fixtures/performance_framework.json
Reverts mozilla/treeherder#6099
Per the convo in the bug, we're going to take a different approach and change the enabled field for this framework to false instead of deleting it. A filter should be added to the API to only retrieve enabled frameworks.
=> Revert "Bug 1615540 - Remove AWFY from Perfherder"

ui/job-view/pushes/Push.jsx
Currently, this only works when you load the page with that URL param.  This change will load them also when you add the filtering in the app.
=> Bug 1615330 - Load test paths on URL changes

treeherder/push_health/utils.py, ui/push-health/GroupedTests.jsx
It doesn't look like the `message` field will get that large.  And if it does, let's just text wrap in the button/heading.
=> Bug 1618521 - Push Health no test name ellipses

treeherder/push_health/utils.py
This is mostly for fixing `TEST-UNEXPECTED-FAIL` in test names preceding the actual path.  But handles a few other cases, too.
=> Bug 1626001 - Strip some text from test_names for Push Health

CODEOWNERS
CC @klahnakoski @sarah-clements for FYI
Sarah, I also tried creating a team for contributors but it requires first to make them org members. I've asked around and this is the cleanest solution.
Contributors even with 'Read' access cannot ask a reviewer on PRs.
Using CODEOWNERS enables automatic review request when the file paths match.
More info found in here:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> Automatically assign code reviewers for some code paths

app.json, bin/pre_deploy
In the beginning of the Heroku Review Apps it made sense to create a user/password that was shared accross apps and be publicly available (since each app would generate their own random queue names).
Unfortunately, last night, I saw a lot of alerts for queues that were overgrowing. We recently
landed some code that should be deleting queues once there are no consumers (which was not happening). This could be because we had a Review app from a long time ago create lots of queues that were not auto-deleted or someone locally is doing development with the shared credentials unknowingly creating many queues.
Either way, the new Heroku Review apps allow defining config variables (secrets) at the pipeline level and are injected in the Review apps upon creation.
I've reset the …
=> Bug 1626914 - Make Review Apps use Pulse credentials secret

tests/webapp/api/test_jobs_api.py, treeherder/webapp/api/jobs.py
Currently both `api/project/<project>/jobs/<jobId>/` and `api/jobs/` APIs returns taskcluster metadata but the latter requires users to piece together the data due to its special formatting. 
This change to `api/project/<project>/jobs` will give users more options for retrieving this data (and it doesn't appear to affect query time with local testing). 
Note about the use of retry_id: even though retry is legacy language for run, we use still use it in the other Job APIs so I kept it for consistency.
=> Add task_id and retry_id to project bound Jobs API

tests/ui/push-health/JobListMetric_test.jsx, ui/push-health/Health.jsx, ui/push-health/Job.jsx, ui/push-health/JobListMetric.jsx, ui/push-health/helpers.js
This will apply `failedInparent` filtering to `Linting` and `Builds` metric.
=> Bug 1625998 - Filter failed builds/linting for parent push

tests/ui/mock/push_health.json, tests/ui/push-health/Job_test.jsx, tests/ui/push-health/TestFailure_test.jsx, treeherder/push_health/classification.py, treeherder/push_health/tests.py, treeherder/push_health/usage.py, ui/push-health/TestMetric.jsx
This gives a better name to this section, because not all items will be 'intermittent'.  Some are now items that also fail in the parent push.
=> Bug 1627088 - Rename known intermittents to known issues

treeherder/webapp/api/jobs.py
The most common issue with failed tasks except intermittent failures are
check-in related issues. Until now, the tasks in 'Similar Jobs' were ordered by
the task's start time which was confusing if tasks had been requested to run
again ("retrigger") because the list jumped between pushes. With the new order
by pushes, issues can be more easily associated with a push/check-in.
The downside is that infrastructure related issues are harder to spot but in
general these don't affect only one kind of task (which the 'Similar Jobs' tab
focuses on).
=> Bug 1627271 - Order 'Similar Jobs' first by push id, then by task's sart time

.pre-commit-config.yaml, docs/installation.md, requirements/dev.in, requirements/dev.txt, setup.cfg, tests/selenium/test_expand_job_group.py, tests/selenium/test_info_panel.py, tests/selenium/test_log_viewer.py, tests/selenium/test_select_job.py, tests/selenium/test_select_unclassified_job.py
@armenzg identified the issue.
When we handle isort within from pre-commit hooks, it's understanding of third party applications import isn't ideal (in contrast to what we had when we run isort locally).
So for that, there is a suggest package ```seed-isort-config```, which basically creates ```.isort.cfg``` file which instructs and corrects the way ```isort pre-commit``` hook sees the packages, thus sorting them correctly.
=> Add seed-isort-config hook

docker-compose.yml
Closes #6179 
- Entries in the `docker-compose.yml` file for `pulse` and another one for the `celery worker`.
=> Add Celery and Pulse ingestion in docker-compose

treeherder/config/settings.py
It seems that Heroku Review apps have regressed and they are not being added to ALLOWED_HOSTS, thus,
making the web deployment have lost of errors (one of them below):
> ERROR [django.security.DisallowedHost:77] Invalid HTTP_HOST header: 'treeherder-pulse-lsiten-afvimm.herokuapp.com'. You may need to add 'treeherder-pulse-lsiten-afvimm.herokuapp.com' to ALLOWED_HOSTS.
This change can be manually tested like this:
```shell
% export HEROKU_REVIEW_APP=1
% export HEROKU_APP_NAME=treeherder-foo
% python -c "from treeherder.config import settings; print(settings.ALLOWED_HOSTS)"
['https://treeherder-foo.herokuapp.com']
```
=> Review apps: Adjust ALLOWED_HOSTS

docker-compose.yml, docs/installation.md, docs/pulseload.md, treeherder/etl/management/commands/pulse_listener_pushes.py, treeherder/etl/management/commands/pulse_listener_tasks.py
This does a few things:
1. Updates the Pulse docs to reflect how things work now for local development
2. Allow the user to set an env var to ingest more than just `autoland`
3. Allow the user to skip the data ingestion, especially if they're hooking up to a remote DB like `treeherder-stage`
=> Bug 1629139 - Update Pulse Docs and allow skip of ingestion

ui/job-view/CustomJobActions.jsx, ui/models/job.js, ui/models/push.js, ui/models/taskcluster.js
Before actions were generated by triggering hooks, treeherder generated action tasks directly. When doing this, the calling code generated the task id, and then used that to link to the task. Now that things are generated via hooks, refactor things so the calling code gets the task id from the code triggering the hook.
=> Show the correct task id for actions.

ui/job-view/headerbars/NotificationsMenu.jsx
This tag had been throwing an error on the console for a while.  I think the `tag="a"` was added here by mistake.  Mellina added it a while back for a11y.  But the item already has an `<a>` tag, so this shouldn't be needed.
=> Fix console error 'a' descendent of 'a'

treeherder/model/management/commands/cache_failure_history.py, treeherder/push_health/tests.py
Looks like `black` fixed up a bunch of formatting.  I'll comment on the sections that actually had code changes.
**Note**: Most of this code will go away once we migrate to `mozci`.  But fixing for now anyway.
=> Bug 1628070 - Fix cache_failure_history management command

docker/mysql.cnf
The recent addition of Celery workers consumption has increased the usage
of number of connections to the database.
In certain cases like loading a large number of pushes we can hit the maximum
limit of connections.
This change increases the default `max_connections` to 300 (about double).
=> Bug 1630293 - Increase max connections for Docker set up

treeherder/log_parser/crossreference.py
The 'test_groups' data got added in bug 1340551 to track which test manifests
contributed tests to the current task. It is not needed as part of the test
output and should be ignored.
=> Bug 1627993 - Ignore 'test_groups' data from errorsummary.log.

ui/job-view/CustomJobActions.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushActionMenu.jsx, ui/job-view/pushes/PushHeader.jsx, ui/job-view/pushes/PushList.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/GroupedTests.jsx, ui/push-health/Health.jsx, ui/push-health/TestFailure.jsx, ui/push-health/TestMetric.jsx
Per a chat in-channel, we probably don't really need to require a user to be logged in to retrigger jobs or to access other features (except for classifications, which I left as-is), since we retrieve taskcluster credentials separately and they are used/verified when calling any tc action.
=> Bug 1620160 - Relax login requirements for UI features

ui/job-view/pushes/Push.jsx
Some devs don't commonly look at a single `try` push, but filter by `author`.  This adds the Push Health summary for that case, too.
=> Bug 1630107 - Show Push Health Summary when try has author filter

treeherder/model/management/commands/cycle_data.py
Add an exception to the `days` restriction for prototype2. I thought about adding a `--force` option instead but it might be too dangerous since we only want to have less Perf data for this one deployment. (Prototype2 has a smaller database and Ionut said 30 days was probably sufficient).
=> Modify cycle_data for prototype2

ui/perfherder/alerts/AlertsViewControls.jsx, ui/perfherder/alerts/Pagination.jsx
I have the solution but I would wait until [Alerts view gets stuck on last page](https://bugzilla.mozilla.org/show_bug.cgi?id=1595111) is merged because this could cause many accidental clicks on last page (I just did quite a few while testing it) and provoke frustration to sheriffs.
=> Bug 1615227 - AlertsView: Add first last to pagination

tests/push_health/test_compare.py, tests/ui/mock/push_health.json, treeherder/push_health/compare.py, ui/job-view/pushes/Push.jsx, ui/job-view/pushes/PushHeader.jsx, ui/push-health/CommitHistory.jsx, ui/push-health/pushhealth.css, ui/shared/PushAuthor.jsx, ui/shared/Revision.jsx
This takes the commits area and borrows some prior art from Treeherder.  The intention is to make it a little more familiar to what folks are accustomed to seeing.
=> Bug 1634099 - Add push date and author to commits list

.travis.yml, package.json, tests/ui/job-view/App_test.jsx, tests/ui/job-view/Filtering_test.jsx, tests/ui/job-view/PushList_test.jsx, tests/ui/job-view/Push_test.jsx, tests/ui/job-view/SecondaryNavBar_test.jsx, tests/ui/job-view/details/PinBoard_test.jsx, tests/ui/job-view/revisions_test.jsx, tests/ui/job-view/selected_job_test.jsx, tests/ui/job-view/stores/selectedJob_test.jsx, tests/ui/perfherder/alerts_test.jsx, tests/ui/perfherder/compare_table_test.jsx, tests/ui/perfherder/graphs_view_test.jsx, tests/ui/perfherder/legend_card_test.jsx, tests/ui/perfherder/replicates_graph_test.jsx, tests/ui/perfherder/retrigger_modal_test.jsx, tests/ui/perfherder/selector_card_test.jsx, tests/ui/perfherder/tests_table_test.jsx, tests/ui/push-health/CommitHistory_test.jsx, tests/ui/push-health/GroupedTests_test.jsx, tests/ui/push-health/Health_test.jsx, tests/ui/push-health/JobListMetric_test.jsx, tests/ui/push-health/Job_test.jsx, tests/ui/push-health/TestFailure_test.jsx, tests/ui/push-health/UnsupportedJob_test.jsx, tests/ui/push-health/Usage_test.jsx, yarn.lock
This looks pretty huge, I know.  Mostly, this is changing the use of the deprecated`waitForElement` to the newer`waitFor`.  There is one case in `graphs_view_test.jsx` that fails when upgraded to `waitFor`.  So I left that as-is to let the test owners address it.  Filed [Bug 1635208](https://bugzilla.mozilla.org/show_bug.cgi?id=1635208)
The most notable changes were the tests in `Filtering_test.jsx`.  These ones were a little trickier because we actually render the entire app.  I had to massage the `fetchMock` calls and `before*` and `after*` calls a fair amount.  I still don't know for sure why the upgrade broke it.  But I think it's clearer now.
=> Upgrade React Testing Library and React

tests/extract/test_extract_job.py
So we can get Travis/Heroku deployments unblocked.
=> Temporarily disable test_extract_job

treeherder/etl/perf.py, treeherder/etl/pushlog.py, treeherder/etl/taskcluster_pulse/handler.py, treeherder/push_health/tests.py
These messages are producing too much noise in Papertrail.
These account for a big chunks of all of the logging.
=> Reduce logging

tests/ui/models/jobs_test.js, ui/helpers/taskcluster.js, ui/models/taskcluster.js
I changed `getCredentials` to return a Promise. What will happen now is that when a user is logged out and they attempt to retrigger a job a new window will open, following the authorization flow to retrieve the taskcluster credentials. After a specified time, credentials will be checked again and the original action (say, a retrigger) will be performed or an error will be thrown if the credentials weren't renewed.
=> Bug 1637423 - Fix taskcluster credential retrieval when not logged in

docs/accessing_data.md
Reworded docs to specify a `.env` file does not exist and must first be created
=> Bug 1637981 - Imprecise docs for setting up .env variables

tests/conftest.py, tests/perfalert/test_alerts/test_secretary_tool.py, tests/perfalert/test_perf_sheriff_bot.py, tests/sample_data/perf_sheriff_bot/recordContext.json, tests/services/test_taskcluster.py, treeherder/perf/alerts.py, treeherder/perf/management/commands/synthesize_backfill_report.py, treeherder/perf/models.py, treeherder/perf/perf_sheriff_bot.py, treeherder/perf/secretary_tool.py, treeherder/utils/__init__.py
This PR's main purpose is to simply integrate [Bug 1612547 - Define component for doing backfills using existing reports](https://bugzilla.mozilla.org/show_bug.cgi?id=1612547).
It's fully integrated, but hidden behind 2 feature flags. The feature flags are only allowing this PR to work during coverage tests.
*(Once the rest of PerfSheriffBot's dependencies are integrated in the PRs that follow, we'll simply remove the feature flags & fully enable this one.)*
=> Bug 1618836 - Integrate the backfill logic in the PerfSheriffBot

ui/perfherder/graphs/GraphTooltip.jsx
When there are no previous revisions or the jobs are older than 4 months, the job link is missing. This PR is showing the data properly when one of those links are [missing](https://treeherder.mozilla.org/perf.html#/graphs?highlightAlerts=1&series=autoland,1925871,1,1&timerange=31536000&zoom=1557598427458,1558233523623,14.807632501856,47.513514917235895).
Example:
**Datapoint is very first**
Before: [tool-tip showing hash, job nor compare links](https://treeherder.mozilla.org/perf.html#/graphs?highlightAlerts=1&selected=1925871,808954023&series=autoland,1925871,1,1&timerange=31536000&zoom=1557598427458,1558233523623,14.807632501856,47.513514917235895)
After: tool-tip showing hash and job links
=> Bug 1637526 Show tooltip information properly when some of them are missing

treeherder/log_parser/failureline.py
I'm wondering what you think about this policy to safeguard us from changes in those files.  Logging a `custom_event` would mean we'd have to actually look for them to notice them.  We could perhaps also log a warning to PaperTrail.
ahal confirmed this was an intentional recent change in the bug, fwiw.  :)
=> Bug 1640024 - Only create FailureLines for supported actions

CODEOWNERS
Since it can easily be missed and people can be waiting for a while.
CC @camd
=> Automatically set reviewer for constants.js changes

Procfile
Since they're not utilizing the worker enough.
I'm also lowering from concurrency of 7 to 3 since these are low memory workers.
We see barely some load.
=> Merge autoclassify workers

.pre-commit-config.yaml
Travis started failling because it was pointing to the original location.
=> Point shellcheck-py to new location

Procfile
It sometimes confuses me. Once we decide to switch over we can add it back.
That ingestion command is only used for the Docker set up.
=> Remove joint Pulse consumer from Procfile

ui/css/treeherder-details-panel.css, ui/job-view/details/tabs/failureSummary/SuggestionsListItem.jsx
Hey there!
First time contributor to this project. I've been helping folks in the Tulsa Mozilla co-working space to onboard with Mozilla Central. I work on the Firefox Profiler. I ran into confusion around what the suggested bugs mean for test failures. I took a stab at changing the UI to provide better hints for first time (and existing) users as to what is going on.
I don't see a `CONTRIBUTING.md` here, so I'm not sure the best approach here to talking about this work. I figured a good first approach would be to send in a PR with some changes. I'm happy to re-file this on Bugzilla if that's the proper channel, or continue here with my "drive-by PR".
Specifically my co-worker was confused over this test failure. He assumed that the issue was already on file. I had the exact some …
=> Restyle the failure summary's bug suggestions and add a label to hint at what they mean

ui/taskcluster-auth-callback/TaskclusterCallback.jsx, ui/taskcluster-auth-callback/constants.js
This will hopefully save time for when issues like what happened over a week ago occur again (see this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1643141)). Taskcluster seems to give pretty vague error messages but it will at least help us determine if its an issue on our end or theirs (or if a users credentials aren't set up correctly).
=> Improve error message handling when fetching taskcluster credentials

requirements/common.in, requirements/common.txt, requirements/dev.in, requirements/dev.txt
CVE-2020-13596
https://github.com/advisories/GHSA-2m34-jcjv-45xf
CVE-2020-13254
https://github.com/advisories/GHSA-wpjr-j57x-wxfw
Dependabot was failing to open the PR without giving a proper error report.
=> Security update for Django

ui/perfherder/graphs/GraphsContainer.jsx
This PR is setting explicitly the right limit of x axis to today.
**Before**
**After**
=> Bug 1642933 - Perfherder's graph doesn't show properly the interrupted jobs

package.json, yarn.lock
See details:
https://app.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7660
=> Update serialize-javascript to handle security issue

ui/job-view/details/DetailsPanel.jsx
Remove filter that only shows parent tests. Graph links for subtests work.
=> Bug 1646713 - Show subtests in Performance tab

tests/ui/job-view/fuzzy_test.jsx, tests/ui/mock/job_list/fuzzy_jobs/search_debug_results.json, ui/job-view/pushes/FuzzyJobFinder.jsx
Fuse.js 4.0 is adding support for search tokens, allowing us to do more precise searches. This commit upgrades to an unreleased version of Fuse.js with that support included, and switches to use it for Treeherder's Fuzzy Job Finder.
=> Bug 1648878 - Change fuzzy finder to accept Fuse.js 6's new enhanced search operators

tests/ui/perfherder/dropdown_menu_test.jsx
I have been trying to learn how to write tests for the pinned projects. I've been having some difficulty because most of the resources I've seen don't show tests written in the same way, and the mocking bit is confusing to me. 
I'm doing my best to follow existing tests, but I don't see any documentation on how to check for the order of items. How do I fetch all items in the dropdown and check they are in the order as expected? I have read about [snapshot testing](https://jestjs.io/docs/en/tutorial-react#snapshot-testing), would that be more appropriate here?
=> Bug 1616759 - Provide test coverage for grouping of common repositories

ui/shared/JobInfo.jsx
Adds a `copy to clipboard` button beside the job label.
=> Issue 6563 - add button to copy task label

tests/ui/mock/push_health.json, tests/ui/push-health/ClassificationGroup_test.jsx, tests/ui/push-health/GroupedTests_test.jsx, tests/ui/push-health/Health_test.jsx, tests/ui/push-health/TestFailure_test.jsx, tests/ui/push-health/details/DetailsPanel_test.jsx, ui/css/failure-summary.css, ui/css/treeherder-custom-styles.css, ui/helpers/job.js, ui/job-view/details/tabs/TabsPanel.jsx, ui/push-health/GroupedTests.jsx, ui/push-health/Health.jsx, ui/push-health/Metric.jsx, ui/push-health/TestFailure.jsx, ui/push-health/details/DetailsPanel.jsx, ui/push-health/pushhealth.css, ui/shared/tabs/failureSummary/BugListItem.jsx, ui/shared/tabs/failureSummary/FailureSummaryTab.jsx, ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
This has a few of the tweaks we talked about in the last PR for this bug:
* I added the `max-width` overall
* Added a `developerMode` for the `DetailsPanel`/`FailureSummaryTab`.  
* I removed the red bar along the left side
* Eliminated some of the specific `CSS` classes we've brought over from the AngularJS days.
* Increased the font size in the `FailureSummaryTab` when in `developerMode`
* Removed the "file bug", "clipboard" and "log viewer" icon buttons and just made the error text a link, as we discussed.
=> Bug 1647451 - Follow-up improvements to Push Health details panel

tests/ui/job-view/App_test.jsx, tests/ui/job-view/Filtering_test.jsx, tests/ui/job-view/PushList_test.jsx, tests/ui/job-view/revisions_test.jsx, tests/ui/job-view/stores/pushes_test.jsx, ui/css/treeherder-pushes.css, ui/job-view/pushes/Push.jsx, ui/job-view/redux/stores/pushes.js, ui/shared/Revision.jsx, ui/shared/RevisionList.jsx
Hi! I need help understanding BugLinkify.js 
In the scenario where there are multiple bugs that are linkified, I am unsure how to attach a bug summary tooltip for each bug. I already have retrieved the bug summaries from RevisionList.js and passed it as a prop into Revision.js.
In this image, there are different bugs that are linkified. The desired goal would be to hover over each hyperlinked bug and it would show the related bug summary.
=> Bug 1539792 -- Tooltip for "bug xxxxxx" shows the commit message rather than the bug summary

tests/ui/job-view/Filtering_test.jsx, ui/helpers/job.js
You can see a link filtering the tasks [here](https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&author=armenzg%40mozilla.com&searchStr=Linux%2C18.04%2Cx64%2Cdebug%2CMochitests%2Ctest-linux1804-64%2Fdebug-mochitest-browser-chrome-e10s%2Cbc4).
Manifest scheduled tasks when backfilled have their symbol changes and
potentially their label.
A manifest scheduled backfilled task (e.g. bc2) ends up being named bc2-<revision>-bk.
The label can also be different than the original task selected to be backfilled.
For instance 'test-linux1804-64/debug-mochitest-browser-chrome-e10s-4' can be
'test-linux1804-64/debug-mochitest-browser-chrome-e10s-1' yet the symbol be bc4
This changes the `searchStr` that helps filtering tasks from:
`Linux 18.04 x64 debug Mochitests …
=> Bug 1649229 - Filter backfilled manifest scheduled tasks

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
This fixes the Failure Summary Panel issues in the bug.  If the job is changed, it will re-scroll to the top and remove any text selection from the last job.
=> Bug 1644851 - Fix Failure Summary scroll and selection on job change

ui/helpers/job.js
In PR #6596 I made the link to filter from normally scheduled tasks to include backfilled tasks. This change makes the link on backfilled tasks match tasks for normally scheduled tasks.
=> Bug 1649229 - Also make backfill tasks match the same search string

.gitignore, tests/perf/test_sheriffing_criteria/test_criteria_tracker.py, tests/sample_data/criteria-records.csv, treeherder/perf/management/commands/compute_criteria_formulas.py, treeherder/perf/sheriffing_criteria/__init__.py, treeherder/perf/sheriffing_criteria/bugzilla_formulas.py, treeherder/perf/sheriffing_criteria/criteria_tracking.py, treeherder/utils/__init__.py
This PR extends `./manage.py compute_criteria_formulas` command to compute the perf sheriffing criteria formulas described [here](https://docs.google.com/document/d/11WPIPFeq-i1IAVOQhBR-SzIMOPSqBVjLepgOWCrz_S4/edit). Specifically, the engineer traction & fix ratio **for each** framework/suite combination.
Previously, it could compute these on the fly for a single combo. Nevertheless, the command kept that previous behavior also, in the form of a subcommand (`./manage.py compute_criteria_formulas individually <framework> <suite>`).
To be able to run the command locally, you'll need to copy/paste the [perf-sheriffing-criteria.csv](https://bugzilla.mozilla.org/attachment.cgi?id=9161800) file to your project's root. This CSV file mostly contains around 600 framework/suite rows (acting as …
=> Bug 1649387 - Provide enhanced management script for Bugzilla formulas

tests/ui/job-view/Filtering_test.jsx, tests/ui/job-view/details/PinBoard_test.jsx, tests/ui/mock/task_definition.json, ui/css/treeherder-details-panel.css, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/JobTestGroups.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/logviewer/App.jsx, ui/shared/JobArtifacts.jsx
Fixes #6630
When selecting a job that has MOZHARNESS_TEST_PATH specified we can fetch
what test groups[1] were executed.
This change adds a new tab named "Test Groups" and renames "Job Details" to "Artifacts".
[1] Some test jobs use manifests to group tests while wpt jobs don't use manifests.
=> Issue 6630 - Add Test Groups tab

package.json
Depending on how we write our tests I've noticed that it is not possible
to use `isRequired` as part of the `propTypes` without the tests calling
some unimportant component with all the required props.
In other words, this removes proptypes warnings in the output of our tests
while not preventing noticing test failures.
You can still test errors when they happen.
=> Travis/jest - Disable printing to console on JS tests

tests/ui/job-view/Push_test.jsx, ui/job-view/pushes/Push.jsx
Both paths work.
@ahal The paths are lower-cased in the UI.
@camd if you check out the branch you can use the links below
- [/indexeddb/key-generators/reading-autoincrement-indexes-cursors.any.worker.html](http://localhost:5000/#/jobs?repo=autoland&group_state=expanded&revision=5e566996d34e4d424750bf184a13e751a7e3b95f&test_paths=%2Findexeddb%2Fkey-generators%2Freading-autoincrement-indexes-cursors.any.worker.html)
- [testing/web-platform/tests/indexeddb/key-generators/reading-autoincrement-indexes-cursors.any.worker.html](http://localhost:5000/#/jobs?repo=autoland&group_state=expanded&revision=5e566996d34e4d424750bf184a13e751a7e3b95f&test_paths=testing%2Fweb-platform%2Ftests%2Findexeddb%2Fkey-generators%2Freading-autoincrement-indexes-cursors.any.worker.html)
- …
=> Bug 1638424 - Translate WPT paths in the test path filter

tests/ui/push-health/CommitHistory_test.jsx, ui/job-view/pushes/Push.jsx, ui/push-health/CommitHistory.jsx, ui/push-health/pushhealth.css, ui/shared/Revision.jsx, ui/shared/RevisionList.jsx, ui/shared/StatusProgress.jsx
I could not find where to find the bug number to be written in the heading if it is not present already 
Also, I have not removed the links to the parent push although they were removed in the recent figma UI
Also, that button showing 6 items at the end of parent revision has not been removed since there were tests written for them already and could not removed without ammending the tests
=> Bug 1647447 - Refactor the push information UI

tests/ui/perfherder/alerts-view/alerts_test.jsx, treeherder/perf/fixtures/performance_framework.json
This patch adds the "mozperftest" framework. We are going to produce metrics for xpcshell tests via `./mach perftest` and want them to be displayed in the Treeherder UI (performance tab) and also ingested by perherder
=> added the xpcshell framework

ui/shared/Revision.jsx
This PR increases clarity between commit message and bug summaries. A space is added in between the two as well as 'Commit: ' added before the commit message.
=> Bug 1651673 - Bug tooltips could be clearer about what is bug summary and what is commit message.

treeherder/etl/job_loader.py, treeherder/utils/taskcluster.py
There's various approaches in the repository on how to fetch information from Taskcluster
but there's no centralized module. This is the beginning of centralizing it.
This patch is used in following PRs.
=> Taskcluster utils module

treeherder/etl/management/commands/ingest.py, treeherder/etl/taskcluster_pulse/handler.py
Fixes #6696
In my impetus to reduce the number of tasks that get stuck in the
celery queues, I made some nightly tasks not being ingested.
You can test this change with:
```shell
./manage.py ingest task --task-id Gcw1BJ1wTTu69A9Uud8NqA
```
=> Fix: Ingest mobile nightly tasks

docker/dev.Dockerfile
It seems that Travis is failing because shellcheck cannot be downloaded.
We don't need anymore as we test for it [here](https://github.com/mozilla/treeherder/blob/master/tox.ini#L22-L23).
=> Docker: No need for shellcheck within the Docker container

tests/ui/job-view/Push_test.jsx, ui/job-view/pushes/Push.jsx
This removes fetching the tests-by-manifest.json.gz and merging it with the contents
of manifests-by-task.json.gz.
This speeds up filtering by tests path and reduces the memory footprint.
It is not perfect but it is a big improvement.
You can test this locally by loading this URL:
http://localhost:5000/#/jobs?repo=autoland&test_paths=toolkit%2Fcomponents%2Fpictureinpicture%2Ftests%2F
and comparing it with:
https://treeherder.mozilla.org//#/jobs?repo=autoland&test_paths=toolkit%2Fcomponents%2Fpictureinpicture%2Ftests%2F
=> Bug 1626623 - Faster test path filtering (drop filtering by test file)

ui/taskcluster-auth-callback/constants.js
I requested new clients be added in preparation for the hash-less routing per this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1654850) (the addition of the new clients will be included in the forthcoming routing pr). I also asked for both localhosts to be registered, so these need to be updated.
=> Update localhost clients for taskcluster authentication

docker-compose.yml, treeherder/config/settings.py, treeherder/etl/management/commands/pulse_listener_pushes.py, treeherder/etl/management/commands/pulse_listener_tasks.py
Reverts mozilla/treeherder#6476
I think this is out of sync with the TH pipeline since I merged this before realizing we needed to reconnect our repo to heroku (since Armen's no longer an admin).
=> Revert "Local dev: Skip ingesting if pointing to an RDS DB"

treeherder/log_parser/parsers.py
Per the request by Aryx here: https://github.com/mozilla/treeherder/pull/6724#issuecomment-679384520
=> Limit log parser regex for unsuccessful task run to code 137

.travis.yml, package.json, tox.ini
Some changes in here:
* Making tox a bit more the centralized point for configurying job execution
* Move Heroku code paths into tox from .travis.yml
* Move to more modern Travis image (xenial 16.04 -> bionic 18.04)
* Make Python tests outside of Docker to run slow tests (DB required)
* Cache tox packages to speed up following Travis runs
* Remove coverage data before gathering new data (to prevent using old data)
=> Improve Travis and Tox configuration

tests/ui/push-health/ClassificationGroup_test.jsx, tests/ui/push-health/PlatformConfig_test.jsx, tests/ui/push-health/TestMetric_test.jsx, ui/push-health/Action.jsx, ui/push-health/ClassificationGroup.jsx, ui/push-health/Health.jsx, ui/push-health/PlatformConfig.jsx, ui/push-health/Test.jsx, ui/push-health/TestMetric.jsx
=> Bug 1609211 - Persist settings in URL

tests/webapp/api/test_note_api.py, treeherder/webapp/api/note.py, treeherder/webapp/api/serializers.py
Marco and the `mozci` team need this API to support moving away from ActiveData.
=> Bug 1669548 - Add API to get classifications for a given push/revision

ui/css/treeherder-custom-styles.css, ui/css/treeherder-details-panel.css, ui/helpers/performance.js, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/tabs/PerformanceTab.jsx, ui/job-view/details/tabs/TabsPanel.jsx
This patch is part of the work identified by cross-project [Performance workflow improvements 2020 project](https://bugzilla.mozilla.org/show_bug.cgi?id=1665457) which is about collecting and prioritizing a smaller set of issues to improve performance workflow issues.
This individual issue is also being tracked on [Bug 1667193](https://bugzilla.mozilla.org/show_bug.cgi?id=1667193).
This link is the one I've been primarily testing against: http://localhost:5000/#/jobs?repo=try&selectedTaskRun=YPFqUsNFRaySxJzP3-hpeA.0&revision=b9afd492797dbe5456fd7a46d359bb4f00be2417
Each commit in this PR is broken out logically, and should be viewable independently.
A Talos run with no profile:
A Talos run with a profile artifact.
Please let me know if you have any questions about this PR.
=> Add more prominent buttons to the PerformanceTab

ui/css/perf.css
I have removed the hovering over `link to graph` and assigned the same colour to the the text "graph".
=> Bug 1671212  - Links to graphs from Perfherder alerts should be always visible

ui/shared/HelpMenu.jsx
To improve usability and accessibility, I have added  `"Help and Resources"` text in the dropdown menu.
=> Bug 1671209 -  Add text to "Help" dropdown in treeherder/perfherder

tests/model/test_cycle_data.py, treeherder/model/management/commands/cycle_data.py
This improves [PR 6786](https://github.com/mozilla/treeherder/pull/6786) (which was reverted) by explicitly increasing the expiring interval for empty alert summaries to a safer value.
That way, we further reduce the risk of unintentionally deleting data perf sheriffs still investigate.
**Bug link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1668511
=> Bug 1668511 - Remove empty alert summaries v2

ui/helpers/url.js, ui/job-view/pushes/PushHeader.jsx, ui/job-view/redux/stores/pushes.js
I had tried to fix a bug that was discovered [here](https://github.com/mozilla/treeherder/pull/6825#issuecomment-717601567) but went about it in the wrong way, and the result was that `selectedJob` and `selectedTaskRun` query params was stripped in all circumstances (so it affected urls from Perfherder and IFV). This fixes it and fixes the original bug by a different approach. 
FYI @camd merging and deploying this today since you're PTO and its affecting the code and perf sheriffs.
=> Bug 1674415 - selectedJob query param should show selected job

tests/log_parser/test_store_failure_lines.py, treeherder/log_parser/failureline.py
Making a tweak to the return value of this function and endpoint so that it matches the schema needs of the `mozci` function that uses it.
=> Bug 1640024 - Make group_results endpoint match mozci format

ui/App.jsx, ui/perfherder/alerts/AlertsView.jsx, ui/perfherder/alerts/AlertsViewControls.jsx, ui/perfherder/alerts/Pagination.jsx
I thought I had fixed the favicon path but I forgot that our assets are handled differently for deployments vs local development.
Also includes some additional fixes for the Perfherder alerts page (back navigation for pagination) that was flagged in #6825.
=> Routing change fixes

tests/ui/job-view/App_test.jsx, ui/App.jsx, ui/intermittent-failures/BugDetailsView.jsx
I missed a few things with the backwards-compatibility of the logviewer urls and needed to add the location origin to external logviewer links since the behavior has changed with the nested browser routing.
=> Bug 1674604 - Logviewer Url fixes

ui/perfherder/App.jsx, ui/perfherder/Navigation.jsx, ui/perfherder/alerts/Assignee.jsx
An interesting quirk of the routing changes is that hitting enter on an input element was causing a full page reload in Perfherder alerts view, whereas it wasn't before. Also found some Perfherder routes that didn't need to be there (and a added a default page value to prevent an unnecessary lifecyle update when filters are changed), so batched that cleanup in this pr.
=> Bug 1676140 - Perfherder alerts Assignee button fix

ui/job-view/details/JobTestGroups.jsx
Fixes a quirk where if `{ MOZHARNESS_TEST_PATHS: "{}" }`, the value is parsed as an empty object and the uncaught error breaks the UI. I think technically we don't need to actually parse this payload, but it's easier to catch this type of bug if we do otherwise we'll end up with `["{", "}"]`. Ahal is also fixing it on his end.
=> Bug 1675835 - add condition for JobTestGroups

ui/css/treeherder-base.css, ui/css/treeherder.css, ui/index.jsx, ui/job-view/App.jsx, ui/push-health/pushhealth.css
Seems like we might need a little audit on our `CSS` at some point.  Not sure all this stuff is necessary.  But due to the peculiarities of the navbars and the details panel in Treeherder itself, the snippet I moved to `treeherder.css` here **is** necessary.  I tried to get rid of it.  
But it shouldn't get applied to everything, so moved some of the `CSS` imports around.  
@sarah-clements : I tested this out a fair amount with TH, Push Health, Perfherder and IFV.  But would you give it a spin as well?  A second set of eyes on this would be great, since it changes such low-level elements.
=> Bug 1676186 - Fix scrolling in Push Health

ui/intermittent-failures/BugDetailsView.jsx
I have adjusted the `PushTime` column width as it autocrop the columns with default width without affecting the maxWidth of the specified columns and it would not have any impact on the text of the other columns (all are clearly visible).
=> Bug 1519784 - Drop seconds from datetime 'Push Time' column in list of classifications to prevent cropping

.pre-commit-config.yaml
Reverts mozilla/treeherder#6886
Seems to be an issue with this new version that is breaking the dependency tree and throwing errors locally (when precommit is installed).
=> Revert "Update precommit hook prettier/prettier to v2.1.2"

ui/css/treeherder-custom-styles.css, ui/css/treeherder-details-panel.css, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/tabs/PerformanceTab.jsx
This includes the unit and whether lower or higher is better. I felt a
bit confused looking at the results, and not knowing what the individual
values meant. This change also presents everything in a table format
which should make it easier to scan and understand.
I ran these changes by some users of this view, and handled some of
their early feedback. This included removing a graph that wasn't very
helpful. There might be some opportunities in the future to add more
details to the columns to help in making navigating the data easier.
However, this is not a replacement for the comparison view, but instead
the motivation is for making the individual test runs easier to
understand.
Useful link for testing:
* [Raptor](https://treeherder.mozilla.org/jobs?repo=autoland&revision=43e0f933ad51ba77 …
=> Add a table-based view for the performance data

tests/ui/shared/FailureSummaryTab_test.jsx, ui/css/treeherder-custom-styles.css, ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
This uses a `regexp` to find paths within the failure summary search string.  It omits the filename and the trailing slash.
I had to make `text-darker-secondary` have `!important` because it wasn't working when the link had been visited.
=> Bug 1673050 - Add filter by test path button to Failure Summary lines

schemas/performance-artifact.json
This patch adds a hyphen to the list of possible characters in the `tags` entries.
See this bug for more information: https://bugzilla.mozilla.org/show_bug.cgi?id=1676499
Try run for these changes: https://treeherder.mozilla.org/jobs?repo=try&tier=1%2C2%2C3&revision=40c831b4b9d0f1e2899d53dbe5bff8da229d6f35
=> Bug 1676499 - Add hyphen to possible perfherder-data tag entry characters.

ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
This fixes an edge case where this filter button for test paths should not show for Reftests.  Because Reftests don't have Test Groups to filter by.
=> Bug 1673050 - Exempt Reftest jobs from test path filter button

ui/helpers/constants.js
This platform is used for both x64 cross-compile and universal builds.
=> Bug 1683389 - revert platform name change for osx-shippable

tests/sample_data/pulse_consumer/transformed_job_data.json, treeherder/etl/job_loader.py, ui/job-view/pushes/Platform.jsx
I'd be shocked if this is an acceptable way to solve it, but I think this is _a_ way of fixing #6467. (But mostly it's a way to get my feet wet with Treeherder development.)
=> Hacky way to get rid of 'opt' from shippable platform labels

.circleci/config.yml, tox.ini
* Create new Tox environment for linting checks
* This decouples the need for setting up Docker for it
* Move production environment variables into Heroku's tox environment
* It makes it more atomic and less dependant on the CI being set up correctly
* Call `tox -e docker` instead of custom command
* Upload code coverage file
=> Some CI & tox changes

ui/perfherder/graphs/GraphsContainer.jsx
This bug was introduced when the improvement of showing the graph timeline up to current date instead of up to the date of last datapoint.
- by clicking to hide the series in the graph is shown `TypeError: e[0] is undefined`
=> Bug 1681880 TypeError: e[0] is undefined when hiding all data series

package.json, yarn.lock
Reverts #6814
V3 of webpack-dev-server isn't compatible with this version of webpack-cli so rather than trying to deal with the workaround mentioned in this bug, we can wait till webpack-dev-server V4 is released which will support this (in beta at the moment).
=> Revert Update dependency webpack-cli to v4 (#6814)

ui/helpers/job.js
We're missing the generate profile button in browsertime tests and it's because they aren't being taken into account in the `isPerfTest` function. This patch solves issue #6950.
=> Add "browsertime" as a possible performance test in `isPerfTest`.

tests/log_parser/test_error_parser.py, treeherder/log_parser/parsers.py
This is usually the root cause of other errors, like here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1686814#c8
And would be nice not having to scroll back a bunch to detect it.
=> Consider YOU ARE LEAKING THE WORLD an error.

tests/intermittents_commenter/expected_comment.text, tests/intermittents_commenter/test_commenter.py, treeherder/intermittents_commenter/comment.template, treeherder/intermittents_commenter/commenter.py
The IFV bot comments will include the build type, grouped by platform, to look like this:
Repository breakdown:
* autoland: 16
* mozilla-central: 5
* try: 2
Platform and build breakdown:
* macosx1014-64-qr: 18
* opt: 7
* debug: 11
* macosx1014-64-shippable-qr: 3
* opt: 3
* macosx1014-64-devedition-qr: 1
* opt: 1
* macosx1014-64: 1
* debug: 1
FYI @jmaher
=> Bug 1496319 - add build type to IFV bot comments

treeherder/changelog/collector.py, treeherder/etl/management/commands/ingest.py, treeherder/etl/push_loader.py, treeherder/utils/github.py
* remove use of client id and secret for github app in push_loader.py
* rename helper functions in github.py
I need to set up 2FA for the bot account and then test this on prototype, so I'll do that Thursday.
=> Bug 1620648 - Switch to github personal access token to avoid rate limiting

.circleci/config.yml
* It looks like the default image was changed to a different(?), older version of ubuntu
that was causing an error and the python-tests job to fail
=> Change circle-ci default machine image for python-tests

treeherder/webapp/api/push.py, ui/helpers/display.js, ui/job-view/pushes/Push.jsx, ui/push-health/Health.jsx, ui/push-health/MyPushes.jsx, ui/shared/PushHealthStatus.jsx
The status progress indicators percentage of failures (in the pie chart) now matches the possible regressions. I also addressed a few other things - comments in the second commit or see the bug for details.
=> Bug 1678760 - Push Health status progress fixes

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
This was included with #6998 by mistake.
=> Remove Push Health link from Failure Summary tab.

ui/intermittent-failures/BugDetailsView.jsx, ui/job-view/details/DetailsPanel.jsx, ui/job-view/pushes/PushJobs.jsx
#6998 changed the log viewer helper function to include the leading forward slash, but didn't remove it from other consumers who add their own. I went through and audited usage of this to make sure everything is updated, and made sure the specific case that bug 1691676 mentions worked again.
=> bug 1691676: Fix log viewer links not to have double forward slash

ui/shared/auth/Login.jsx
* To help guard against situations when a token is faulty and needs to be easily cleared so the user can retrieve a fresh taskcluster token
=> Bug 1692544 - Clear taskcluster credentials on logout

ui/job-view/App.jsx
The health summary query can be very slow sometimes and I'm concerned this is slowing page load, from some recent spikes in response time I'm seeing in New Relic.
=> Change push health visibility back to try

treeherder/config/urls.py
Move debug_toolbar path to first index in urlpatterns.
=> Fix Django Debug Toolbar

requirements/common.txt, requirements/dev.in, requirements/dev.txt, tox.ini
In my local tests, I was getting failures with xdist ~80% of the time. I haven't seen any failures with it removed. (I don't know why it only started happening after merging to master...but there's no point in debugging that now.)
=> Disable pytest-xdist because it seems to be increasing intermittent failures

.circleci/config.yml, .dockerignore, docker/Dockerfile, docker/entrypoint_prod.sh, requirements/common.in, requirements/common.txt, treeherder/config/settings.py, version.json
This probably needs a bit more work, but as far as I can tell it gets some sort of functioning treeherder instance up and running in the resulting container. It's probably best to iterate in the CloudOps environment, once that's available.
I added cron entrypoints as well, and added extra arguments for those that are run in multiple different ways. Specifically, `cycle_data` and `perf_sheriff` should support all the ways in which we currently use them.
=> Add CloudOps-ready Docker builds

bin/pre_deploy
* For some reason the django check warning is causing a release to fail for a recent schema change
so removing the check since its implicitly called as part of the migrate command that follows
=> Change pre_deploy to remove django checks

treeherder/perf/fixtures/performance_bug_templates.yaml
Currently rstewart and bc no longer work at Mozilla and their emails appear on cc_list of the regression bug templates.
=> Bug 1704761 Remove inactive people from regression cc list

tests/e2e/test_job_ingestion.py, tests/model/test_bugscache.py, treeherder/etl/artifact.py, treeherder/model/models.py
I did some research into whether we need the raw sql in the `search` method, but since Django still only supports full text search with postgres, this seems like a reasonable way to utilize mysql's boolean full text searches (if anyone knows better, please let me know). See the bug for more details on the what and why. Aside: I've talked to Jeremy about possibly migrating to postgres after the initial gcp migration, since Django is really designed to be used with postgres.
So, the changes I've made are re-enable caching of bug suggestions during ingestion (temporarily disabled on Saturday to give myself more time to look into this #7099 ) and to move search term sanitizing into its own function with a basic unit test.
=> Bug 1704311 - Bugscache changes

treeherder/config/settings.py
Each deployment in gcp will have its own cert that will need to be accessible
=> Add TLS cert path env variable

treeherder/perf/email.py
**Buy link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1706569
=> Bug 1706569 - Improperly built URLs for backfill report emails

treeherder/config/settings.py
Reverts mozilla/treeherder#7127
This wasn't actually needed; there was a change on the cloudOps side that caused the need for this change (but its been fixed).
=> Revert "Add port to allowed hosts for gcp staging"

treeherder/model/error_summary.py
Used [this task](https://treeherder.mozilla.org/jobs?repo=try&group_state=expanded&resultStatus=usercancel%2Ctestfailed%2Cbusted%2Cexception&revision=e411a85d1ee041a77718cbb0d785b92e105392e8&selectedTaskRun=GKyYLRj1QYSBHau-i8oc5g.0) to verify the fix.
=> Bug 1709356 - Don't use 'Last test finished' as search term but fall back to checks for crash signature and whole failure line

docker-compose.yml, docs/installation.md, docs/pulseload.md, tests/etl/test_job_loader.py
@Archaeopteryx and @gmierz have both had issues with our docs being a bit confusing for backend development (even I was confused!) and things not working quite right.
I took some time debug this and make changes:
1) The shared pulse user wasn't working and you needed to export the PULSE_URL in the shell before running `docker-compose up`. Turns out the password needed to be reset :) So there's no need to do that anymore.
2) It seems you need to have both PROJECTS_TO_INGEST in the docker backend container (with some defaults) or you need to export whatever projects you want to see before also running docker-compose **and** specify those projects in a second shell to run the celery workers. So I've updated the docs and added `PROJECTS_TO_INGEST=autoland,try` to the docker-compose file. …
=> Improvements to ingesting data locally - doc and docker changes

ui/perfherder/compare/CompareView.jsx
Reproduction of the bug: Go to http://localhost:5000/perfherder/compare?originalProject=mozilla-central&newProject=try&newRevision=570364e12beb104652bb1a7950064b25383522e1&framework=4&selectedTimeRange=172800
and then choose 'mozperftest' from the frameworks dropdown.
=> Bug 1711031 - Undefined measurement unit in Compare View

treeherder/perf/auto_perf_sheriffing/backfill_tool.py
Based on the newly added functionality from taskcluster (https://phabricator.services.mozilla.com/D115057), we can prevent Sherlock from retriggering jobs that already run
=> Bug 1712257 - Sherlock does not backfill if there are jobs

ui/helpers/constants.js
This is needed for this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1700763
We are working on implementing Fission and isolated process on Android, and want to start running tests in automation on builds with isolated process. So we need a Treeherder platform option for that.
=> Bug 1700763 - Add an isolated process option for Android treeherder platforms

tests/ui/perfherder/compare-view/compare_table_test.jsx, ui/perfherder/Validation.jsx, ui/perfherder/alerts/AlertsViewControls.jsx, ui/perfherder/compare/CompareTableControls.jsx, ui/shared/FilterControls.jsx, ui/shared/InputFilter.jsx
The filter buttons ('Hide uncomparable results', 'Show only important changes', 'Hide uncertain results', 'Show only noise' ) and the filter text from the Compare View Page are not reflected in the URL as they should.
This PR should fix this issue.
=> Bug 1717212 - Compare View query string parameters are not updated

tests/ui/perfherder/compare-view/compare_table_test.jsx, ui/perfherder/compare/CompareTableControls.jsx
Reproduction link for this bug: https://treeherder.mozilla.org/perfherder/compare?originalProject=try&originalRevision=080aa96854f418e43bf7830723b4b8349f2d60b4&newProject=try&newRevision=a0bddba56926720593c4639f75ee0e7e68792bea&framework=13&filter=ContentfulSpeedIndex&pageTitle=strict+mode+vs+normal+mode+recorded+sites&page=1
=> Bug 1720839 - Compare View Pagination links to pages are not shown when number of pages < 5

ui/css/treeherder-pinboard.css
Before the width was fixed and long labels would wrap or get cut off.
=> Bug 1525121 - use dynamic width for pinned tasks in pinboard to fit labels

ui/job-view/redux/stores/pushes.js
The object holding the mapping of job IDs to the jobs themselves got iteratively
regenerated - the script walked over all jobs currently shown (with
Array.prototype.reduce) and for each job of the push which shall be shown, a new
object got generated based on the old one + the new job id and data. Based on
testing with mozilla-central and the default 10 pushes shown, this translates
into ~90k jobs and slow page warnings (execution up to 46s measured). The new
code takes one object and sets the id and data pairs iteratively in 100-200ms.
=> Bug 1617835 - optimize time to switch to view showing single push

ui/helpers/filter.js
Bug 1450045 removed the machine_name data from the frontend cache and the
ability to filter by 'machine name' has been broken since.
Checking the results of tasks which have been run a specific machine should be
done with Taskcluster. Treeherder would also only show the runs for the
currently shown tree, to which machines are not bound.
=> Bug 1722731 - remove filtering by 'machine name'

ui/helpers/constants.js
This will make these job names more easily readable in the Treeherder UI.
=> Bug 1730527 - Give windows10-64-2004 mingw jobs a friendlier name

tests/webapp/api/test_bug_creation.py, treeherder/webapp/api/bug_creation.py, ui/shared/BugFiler.jsx
Bug 1429030 added automatic suggestions of the Bugzilla product and component
combination to use for new bugs created from the bug filer. Unrelated
product::component suggestions got suggested under certain conditions.
Examples:
* Android tests junit tests separate the path by . compared to / in the
database. If the search term starts with org.mozilla., the string between the
first potential # and the last . left of it should be used for the search
(should match the file name of the test). Example: bug 1732081
* Test framework files in the failure will suggest the component for that one.
The real failure might not be in the failure log. Set the Mochitest framework
as opt-in and do not automatically suggest it. Example: bug 1732236
* Crashes should be reported into the component of the …
=> Bug 1732359 - several improvements to Bugzilla products and components suggested by bug filer

ui/intermittent-failures/View.jsx
Both `updateData` (initiated by `didComponentUpdate`) and `updateState` took
care of changes to url parameters.
=> Bug 1733650 - Intermittent Failures View should request data only once

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Switching between different failed tasks and clicking "Show more bug
suggestions" for a failure line shows the additional bugs and still "Hide more
bug suggestions" after one switched directly to another failed task with bug
suggestions for a failure line at the same index (e.g. the first one).
This doesn't apply if one e.g. selected a failed task with no suggestions at the
same failure line index or one selected a task without failure lines inbetween.
React didn't update the element because the key was static (onyl index used).
=> Bug 1741227 - List of suggested bugs should not sometimes remember if further bugs got shown for different task

ui/css/perf.css, ui/perfherder/alerts/AlertsView.jsx, ui/perfherder/compare/CompareTableControls.jsx, ui/perfherder/shared/Pagination.jsx
This is a set of patches for [bug 1743523](https://bugzilla.mozilla.org/show_bug.cgi?id=1743523) and [bug 1743520](https://bugzilla.mozilla.org/show_bug.cgi?id=1743520) to make the size and position of pagination buttons consistent across navigation.
=> Make the pagination button size and position consistent

tests/ui/job-view/details/PinBoard_test.jsx, treeherder/webapp/api/classification.py, treeherder/webapp/api/urls.py, ui/helpers/http.js, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/PinBoard.jsx, ui/models/classificationTypeAndBugs.js
* Removing the bug-job associations prevents wrong updates to bugs about the
issue still being observed in CI or about its frequency.
* Deletion of the classification type instead of appending 'not classified'
makes the data more robust for analysis.
* This feature is only enabled for employees and members of the 'sheriff' LDAP
group to prevent broad undesired changes by random users.
The failure classification type ("intermittent", "infra", ...) is stored
independently from the bug used for classification (bug 1169720), hence no model
based view set gets used.
=> Bug 1253768 - bulk unclassification support including removal of association with bug

docker-compose.yml, docker/Dockerfile, package.json
Per https://nodejs.org/en/blog/vulnerability/jan-2022-security-releases/
Will work on the node upgrade to v17 separately.
=> Update to 16.13.2 for latest security release

treeherder/model/fixtures/repository.json
This will allow any pushes and tasks run on main branch of these staging repos to be reported to Treeherder
=> Bug 1746426 - Add mobile staging repos to Treeherder

treeherder/intermittents_commenter/commenter.py
=> Bug 1752137 - prevent stockwell 'needswork:owner' Bugzilla whiteboard tag from getting duplicated by intermittent commenter

ui/css/treeherder-job-buttons.css, ui/job-view/pushes/JobGroup.jsx, ui/job-view/pushes/JobsAndGroups.jsx, ui/job-view/pushes/Platform.jsx, ui/job-view/pushes/PushJobs.jsx
In "Add new jobs" mode, if a group is expanded,
Show "[All]" button is next to the group name, that flips selected state of all runnable jobs in the group
=> Bug 1743534 - Add [All] button next to the expanded group name, to select/deselect all jobs in this group, in "Add new jobs" view.

ui/job-view/CustomJobActions.jsx
yaml v4 made the `load` function safe and dropped the `safeLoad` one. The update
to yaml v4 had landed in
https://github.com/mozilla/treeherder/commit/933d8dfb69b7156b19f486fe853e6efd868f8fb0
=> Bug 1753211 - switch yaml v4 call from `safeLoad` to `load` to fix Custom Actions

ui/perfherder/alerts/AlertTableRow.jsx
The `untriaged` label was displayed in green with a checkmark before it, which doesn't really convey
the state of the alert (someone might think the work is done here).
This patch updates the element so it uses yellow instead (from the `text-warning` class).
Bug was filed in bugzilla: for https://bugzilla.mozilla.org/show_bug.cgi?id=1741449
=> Update untriaged item text color from green to yellow

treeherder/log_parser/tasks.py
Production only logs up to log level `info`.
=> Bug 1746176 - log progress of CI log parsing in production

tests/webapp/api/test_jobs_api.py, treeherder/webapp/api/serializers.py, ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
This improves the response time for tasks with many failure lines locally by a
factor of 5. In production these requests often timed out because they were
too slow to get a response.
=> Bug 1748445 - remove unused attributes from text_log_errors API endpoint

ui/taskcluster-auth-callback/constants.js
* Remove forward slash in tcClientIdMap const
I discovered this while trying to test out something unrelated and it breaks the login callback.
=> Taskcluster login fix on prototype and tc-staging

ui/css/treeherder-job-buttons.css
The current font weight makes it almost indistinguishable from black
=> Use bold font-weight for collapsed retry job groups

ui/logviewer/App.jsx
The button to transfer selected text from the log viewer into the bug filer in a
different tab got added in bug bug 1745936 but didn't trigger React's `onChange`
event.
=> Bug 1756488 - trigger update of react state for bug filer after log content got copied into it with button

treeherder/etl/taskcluster_pulse/handler.py
Add focus-android to the list of mobile repos where we ignore non-{main,master} pushes.
=> Ignore focus-android pushes on non-main branches

tests/webapp/api/test_bugzilla.py, treeherder/utils/bugzilla.py, treeherder/webapp/api/bugzilla.py, ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
The bug page opened after a bug got created with treeherder's bugfiler should
use the host specified by the BUGZILLA_API_URL environment variable. Until now,
the bug got created on httpst://bugzilla-dev.allizom.org but an unrelated bug
with same id on https://bugzilla.mozilla.org/ got opened on success.
=> Bug 17456842 - Use same host for opening new bugs like the one on which they got created

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Necessary change which hadn't been included in bug 1756842.
=> Bug 1758089 - use `data.id` instead of `data.success` for classification with created bug

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py
Fix for the case where the [performance tab for AWSY tests is missing](https://treeherder.mozilla.org/jobs?repo=autoland&searchStr=Linux%2C18.04%2Cx64%2CWebRender%2CShippable%2Copt%2CAre%2Cwe%2Cslim%2Cyet%2Ctests%2Cby%2CTaskCluster%2C%2Cfission%2Cenabled%2Ctest-linux1804-64-shippable-qr%2Fopt-awsy-base-fis-e10s%2Cab&revision=7c9a7ccd7e0742a1b4994cb60b4c35394e1a2ec5&selectedTaskRun=cA7Neo9LQLe_Tahb4TWz7A.0) due to the fact that results being filtered after `should_alert = True`. An empty value for the field `should_alert` in `PerformanceSignature` table is stored as `null` and results with the `null` value will be excluded without this change.
=> Bug 1755460 - Exclude the results where should_alert is False

treeherder/perf/fixtures/performance_bug_templates.yaml
Update regression templates text to let devs know that they can trigger profile jobs or ask the sheriffs for that.
“If you need the profiling jobs you can trigger them yourself from treeherder job view or ask a sheriff to do that for you.”
=> Bug 1764873 - Update regression templates about profiling

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
`bugSuggestionsLoading` was never set to `true`. If other requests for the selected task finished loading before the bug suggestions one, the suggestions for the previously selected task were shown.
=> Bug 1756406 - show loading indicator while bug suggestions load

docker-compose.yml, docker/dev.Dockerfile, docker/entrypoint.sh, docker/entrypoint_prod.sh, requirements/common.in, requirements/common.txt, tests/conftest.py, tests/test_worker/test_task.py, treeherder/etl/tasks/pushlog_tasks.py, treeherder/workers/task.py
- As mentionned in [release notes](https://docs.celeryq.dev/en/stable/history/whatsnew-5.0.html#step-1-adjust-your-command-line-invocation), the global CLI parameters (app name) must be placed before the subcommand
- Requirements update for celery 5.2.6 (current stable on pypi)
- `from celery import task` must be replaced by `from celery import shared_task`
- an environment variable for celery was misnamed
- added a check in dev entrypoint to wait for rabbitmq to be up (as we already wait for mysql to be up)
- this removes error messages present on `master` too
- configured the `$HOME` env variable to a folder writable by `nobody:nogroup`
- this prevents a crash from `mozci` imports that tries to read a configuration file
- setup the configuration level in dev docker-compose to `INFO` to …
=> Upgrade Celery to v5

webpack.config.js
Using `yarn build:dev` was leading to a blank HTML page
=> Restore webpack dev build

webpack.config.js
I also set the `open` configuration to open Firefox immediately on the right page.
=> Configure webpack dev server on all interfaces

webpack.config.js
The support for the `BACKEND` environment variable was dropped in the neutrino removal: the `treeherder.mozilla.org` was generated by `neutrino inspect` and finally hardcoded.
This will restore the view of the local backend by default when running `docker-compose up --build`
=> Bug 1772135 - Restore support for BACKEND environment variable

treeherder/perf/migrations/0043_drop_multicommitdatum.py, treeherder/perf/migrations/0044_perfdatum_bigint_fk.py, treeherder/perf/migrations/0045_restore_cascade_perf_datum_deletion.py, treeherder/perf/migrations/0045_restore_perf_multicommitdatum_and_schema.py, treeherder/perf/migrations/0046_restore_cascade_perf_datum_deletion.py, treeherder/perf/models.py
There are 3 migrations:
* perf.0043 drops the `perf_muulticommitdatum` table, allowing to do the `performance_datum` PK migration with an external tool. There is a check that requires the table to be empty for the migration to pass.
* perf.0044 update django's state schema. It requires `performance_datum` PK column to be of type `bigint(20)` to pass. This migration is not reversible and restore the `perf_multicommitdatum` table (handled by django, no error should occur there).
* perf.0045 restores a specific DB constraint. It is a copy of perf.0036 that updates  `perf_muulticommitdatum` FK constraint (to add a CASCADE behavior on delete).
There are checks to ensure migrations are not ran if the data is not ready on the tables at each step:
```sh
$ django-admin migrate perf 0043
$ #Perform …
```
=> Bug 1343328 - [DO NOT MERGE] PerfDatum bigint PK migration using pt-osc

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Bug 1757222 removed the error message from failure lines if they are supposed to
get classified with bugs which track all failures for a test (single tracking
bug). The error message contains valuable information (e.g. it can indicate if
the issue is a permanent failure) and should be shown.
=> Bug 1778202 - show error message in failure even if it is supposed to be classified with a single tracking bug

docker-compose.yml
This should fix the backend usage through docker-compose: the backend was not used at the correct address (using host `localhost` instead of goinf through the docker inner hostname).
=> Bug 1779242 - Fix the backend configuration for frontend through docker-compose

.circleci/config.yml, docs/installation.md, docs/pulseload.md, package.json, yarn.lock
This bumps markdownlint-cli to latest version available, and fixes a bunch of Markdown issues (extra useless references).
I also tried to update the node version used on CI to 18, then 16, and both versions failed later on for unit tests (missing mocks).
=> Update markdown lint to fix CI

requirements/common.in, requirements/common.txt, requirements/dev.in, requirements/dev.txt, treeherder/config/settings.py
Django update to 4.0.6 :
* `pytest-freezegun` dependency version has been fixed to https://github.com/ktosiek/pytest-freezegun/pull/38 (removes a distutils deprecation warning making tests fail).
* Remove USE_L10N django setting (defaults to True in 4.0).
* Set USE__TZ setting to False (defaults to True instead of false in 4.0, Treeherder only uses UTC times).
* Add `CSRF_TRUSTED_ORIGINS` setting, configurable with an environment variable. ⚠️ You'll have to define `CSRF_TRUSTED_ORIGINS` for deployments with origin URLs (e.g. frontend address) as defined in the [Django official documentation](https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS).
=> Update Django from 3.2 to 4.0

ui/job-view/redux/stores/selectedJob.js
The single push view gets deliberately opened. It's not a view which drops older
pushes and the selected task which they might contain.
=> Bug 1782174 - single push view opened: don't warn if previously selected task missing

ui/css/treeherder-job-buttons.css, ui/job-view/pushes/JobButton.jsx, ui/job-view/pushes/JobGroup.jsx
For https://bugzilla.mozilla.org/show_bug.cgi?id=1779188
Here's the current output, that adds a mitten icon at the top-right, the same place as the "classified" icon:
Things to consider:
* How to mark these jobs (the above is just an example)
* Use different color or style for the job button?
* Show symbol? If so, where?
* it would be better avoid confusion with "classified" icon
* Add separate filter for them?
=> Bug 1779188 - Mark failed jobs where other job with same name does not fail.

.eslintrc.js, package.json, ui/job-view/details/summary/LogUrls.jsx, ui/perfherder/alerts/AlertModal.jsx, ui/perfherder/alerts/FileBugModal.jsx, ui/perfherder/alerts/StatusDropdown.jsx, ui/perfherder/compare/CompareTable.jsx, ui/perfherder/compare/SelectorCard.jsx, ui/shared/InputFilter.jsx, yarn.lock
`yarn add @babel/eslint-parser eslint eslint-parser-import && yarn lint --fix`
then manually fixed a couple of issues.  If we turn react-comp back on to warn/error, there are ~35 issues to sort out, mostly just reordering functions, but I thought that would be too much to sort out with this patch.
=> upgrade eslint to latest (8.21.0)

ui/css/treeherder-job-buttons.css
Use `outline` instead of `border` to show rounded rectangles around the buttons.
This achieves almost same effect, and this doesn't require the negative `margin`.
With this patch the following actions don't change the layout:
* select jobs
* select runnable jobs
* pin jobs
especially the second one was troublesome because it changes the position of the button while selecting multiple jobs.
=> Bug 1765877 - Use outline for selected jobs and remove negative margins

setup.cfg
The django-extensions package sets 'default_app_config' wrapped in a 'try'
statement.
=> Ignore warning RemovedInDjango41Warning to let pytest run in local development environment

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx, ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
this allows us to use the data that is in the backend:
* original: https://github.com/mozilla/treeherder/commit/6b2e992aa2c8d1c6b7e221fb2a6115ee1ec468ff
* small tweak: https://github.com/mozilla/treeherder/commit/94284fd2588ee8e167f62398ad88b1a9b992663e
this displays the new button- as a signal for user/sheriff to investigate or file a new bug/reopen a bug.
once this is r+, I want to work on collecting some metrics so we can monitor this over time and if numbers shift further we can adjust rules.
=> display new button for failure lines we haven't seen [in 21 days].

treeherder/middleware.py
I switched Taskcluster's staging environment to use tcstage.taskcluster-artifacts.net so we no longer need the old staging artifact domain here.
=> remove old taskcluster staging artifacts domain from csp

schemas/performance-artifact.json
Required for [bug 1779588](https://bugzilla.mozilla.org/show_bug.cgi?id=1779588).
=> Bug 1779588 - Add safari application for Safari browser on macOS

package.json, yarn.lock
last update that I see this available this week- a lot of changes:
https://github.com/reduxjs/react-redux/releases
nothing is `breaking` in the changes, so the risk is lower, tests pass, so I am inclined to assume all is working well.
=> Update dependency react-redux to v8

ui/helpers/http.js
It looks like inside the `getData` function we are getting the `contentType` from the header. But while doing it, we have a weird `''.startsWith('text/html');` after an OR operator. I think this might be a forgotten artifact while refactoring that code. `''.startsWith('text/html');` always returns false, which was confusing to me while I was looking at this function. And below that line, we have a check for `contentType` to see if it's "application/json".
See:
https://github.com/mozilla/treeherder/blob/eccd74e32ea098bd5b57a1695bc1ff142ca49606/ui/helpers/http.js#L24
=> Remove the unnecessary OR operation while getting the content type in `getData`

tests/ui/models/browsertime_alerts_extra_data_test.js, ui/models/browsertimeAlertsExtraData.js
Currently we add the profile links to browsertime alerts unconditionally. This PR changes this logic to check if the profile exists before adding it. It refactors this function a bit to make it possible to run `Promise.all`. This allows us to run all the promises in parallel instead of doing them inside a for loop serially.
With this PR, we don't have to manually check if the platform is android or not. It will automatically not add the links for androids as well since it will fail to find them.
=> Add the profile urls to performance alerts only if the profile artifacts are available

ui/perfherder/graphs/GraphTooltip.jsx
This was encountered when trying to create two alerts from Speedometer subtests. The first was successful, but the second only showed the common alert notice and no way for me to create another alert (or to associate it with the common one).
=> Graph View - Show 'create alert' button on datapoints with common alerts

ui/perfherder/perf-helpers/textualSummary.js
Fixes [Bug 1815345](https://bugzilla.mozilla.org/show_bug.cgi?id=1815345).
Previously we were putting the zip file links directly to alert summaries. This wasn't great because users had to download the files first, and then open them inside the Firefox Profiler by dragging and dropping that file. This is still adding some friction between seeing the bug and analyzing the issue.
Now we are directly generating Firefox Profiler links. This way, users can directly click on these links to open them in Firefox Profiler instead of downloading the profiles. This reduces the friction even more.
Before we had urls like:
https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/PKkTETY8S9aDfCuLhivdLw/runs/0/artifacts/public/test_info/profile_espn.zip
Now generating urls like: …
=> Bug 1815345 - Generate profiler before/after links to open them directly in Firefox Profiler

treeherder/etl/taskcluster_pulse/handler.py
This way only commits to the main branch gets ingested by Treeherder. The latter ones got migrated to the monorepo.
=> Bug 1816432 - add firefox-android as mobile repository, drop android-components and focus-android

ui/shared/BugFiler.jsx
This enables to create Bugzilla queries for intermittent failures which exclude these bugs.
=> Bug 1594967 - add 'test-verify-fail' keyword to bug created for failures of test-verify tasks

tests/log_parser/test_error_parser.py, treeherder/log_parser/parsers.py
The text could be e.g. prefixed with a timestamp, see bug 1775522.
=> Bug 1819906 - search for 'non-fatal error' at any position in line to exclude it as failure

treeherder/model/fixtures/repository.json
This patch enables performance test alerting on the firefox-android branch.
=> Bug 1821054 - Enable performance alerting on the firefox-android branch.

tests/perfalert/test_alert_modification.py, treeherder/perf/models.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1824074
=> Bug 1824074 - When reassigning a regression to an acknowledged improvement, summary status goes unsynced with the items

schemas/performance-artifact.json
required for https://bugzilla.mozilla.org/show_bug.cgi?id=1818364
=> Bug 1818364 - Add custom chromium-as-release app

treeherder/etl/perf.py
This patch fixes an issue where the tests with a suite-level summary value don't have an application version set. See this query to see how the application version is not set in the tp6 tests: https://sql.telemetry.mozilla.org/queries/91180/source
If you change it to search for benchmark tests, they'll show an application version since they have no suite level value.
=> Bug 1742479 - Ingest application version for tests that have a suite value.

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Originally I used counter==1 to determine if this was the "First" instance of a failure.  It became obvious we needed to see the NEW flag on all failures on the same revision, so we switched to `failure_new_in_rev`.  This hack is a hack-
* we only increment `counter` if on autoland || mozilla-central, so a new failure would be `counter == 0`
* here I check for `try && counter == 0`.  This was less processing than computing in the python backend to adjust `failure_new_in_rev`.
* this will have the same effect because the counter will always be 0, so the experience will be the same.
once this lands and we verify it, I will post on dev-platform to discuss how it is used and how to surface errors (including the mittens icon as well as common edge cases).  I will also include a survey to …
=> show NEW flag on try

tests/ui/perfherder/compare-view/compare_table_test.jsx, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, ui/css/perf.css, ui/perfherder/compare/CompareTableControls.jsx, ui/perfherder/compare/CompareView.jsx
This patch adds a button to the Compare View that enables using replicates in the comparison. Note that this only works for try-branch pushes.
=> Bug 1831945 - Add a toggle for replicates to the CompareView.

ui/perfherder/compare/CompareSubtestsView.jsx
This patch is a follow-up to PR #7703. It enables the ability to use replicates on the subtest Compare View table. Currently, the `Use replicates` button is displayed, but doesn't do anything since the parameter isn't handled properly.
Before:
After:
=> Bug 1831945 - Handle replicates parameter in CompareSubtestsView.

docker-compose.yml
Running `docker-compose up --build` on macbook M1 gives this error `no matching manifest for linux/arm64/v8 in the manifest list entries`
The solution was to add `platform: linux/amd64` to each container
To test this I use the following commands in the terminal:
1.  `docker system prune --all --volumes --force`
2. `docker-compose up --build`
=> Add platform to docker-compose.yml

tests/webapp/api/test_perfcompare_api.py, treeherder/webapp/api/perfcompare_utils.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py
Backend part of https://mozilla-hub.atlassian.net/browse/PCF-272.
To test access: http://localhost:8000/api/perfcompare/results/?base_repository=mozilla-central&new_repository=mozilla-central&framework=1&interval=86400&no_subtests=true&base_revision=9d50665254899d8431813bdc04178e6006ce6d59&new_revision=a998c42399a8fcea623690bf65bef49de20535b4 with the staging credentials
=> Add base_rev and new_rev to the PerfCompare API + removed unnecessary fields

treeherder/config/settings.py
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1782215
`window.opener` is always set to `null` when the **Cross-Origin-Opener-Policy** header is present and set to `same-origin` in a request (see https://developer.mozilla.org/en-US/docs/Web/API/Window/opener).
Now, `window.opener` is used to determine whether the **LoginCallback** window should be closed or not, so we don't want it to be constantly `null`.
Since [Django 4.0](https://docs.djangoproject.com/en/4.2/releases/4.0/#requests-and-responses), this header is automatically added by Django's `SecurityMiddleware` and set to `same-origin`, which is unwanted.
=> Bug 1782215 - Properly close the tab opened by LoginCallback when needed

tests/ui/job-view/bugfiler_test.jsx, ui/shared/BugFiler.jsx
The new format got added in bug 1631828 and puts the crash signature in front of the test during whose execution the crash got recorded.
=> Bug 1844214 - detect crashes logged in the new format

tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, treeherder/webapp/api/urls.py
Hi there :)
I created the API to get the task data.
Please let me know if there is anything that needs to be modified :)
URL: `GET: /api/performance/alertsummary-tasks/?id=1` (`1` is the id of the alert summary)
result sample:
```
{
"id": 1,
"tasks": [
"test-windows10-64-shippable-qr/opt-talos-tp5o",
"test-linux1804-64-shippable-qr/opt-talos-tp5o",
"test-linux1804-64-shippable-qr/opt-talos-g5"
]
}
```
raw SQL: (I referred to the query in the bugzilla [0])
```
select distinct jt.name
from performance_alert_summary pas
, performance_alert pa
, performance_signature ps
, performance_datum pd
, job j
, job_type jt
where pas.id = 1
and (  pas.id = pa.summary_id 
or pas.id = pa.related_summary_id)
and pa.series_signature_id = ps.id
and ps.id 		 = pd.signature_id
and pd.job_id 	 = j.id
and …
```
=> Bug 1667866 - Add the GET API to get the tasks by the id of the alert summary

docker/Dockerfile, docker/dev.Dockerfile
Use Debian bullseye to be able to pull the packages, else error message 'NO_PUBKEY' shown for fetching from Debian Bookworm.
=> Update python Docker tag to v3.9.18

.eslintignore, package.json, yarn.lock
* webpack `5.76.3` → `5.88.2`
* webpack-cli `4.9.2` → `5.1.4`
* @mozilla/glean `1.3.0` → `2.0.1`
* @babel/eslint-parser `7.11.5` → `7.22.15`
I was able to build and serve the application with no major changes in the frontend
=> Update javascript dependencies

ui/job-view/details/tabs/TabsPanel.jsx
Potential fix for [Bug 1827920](https://bugzilla.mozilla.org/show_bug.cgi?id=1827920), the rare error/crash with `TypeError: s is not a function` when trying to load a push health page.
The import was being used instead of the prop tied to the store resulting in the `updatePinnedJob` prop sometimes having the value of `null` when it is attempted to be called later inside FailureSummaryTab.
Not sure this is the fix but I am reasonably confident as it seems straight forward - I can't repro/test the issue locally with just the UI.
=> Potential fix for Bug 1827920

tests/conftest.py, tests/webapp/api/test_performance_alerts_api.py, tests/webapp/api/test_performance_alertsummary_api.py, treeherder/webapp/api/performance_serializers.py
Add TaskclusterMetadata information for current push and prev push (basically the ends of the push range of the alert summary):
- taskcluster `task_id` - the one that's visible in the treeherder job view, under `Job` link [example](https://prototype.treeherder.nonprod.cloudops.mozgcp.net/jobs?repo=autoland&group_state=expanded&selectedTaskRun=QTrvdpaJT0WyQMBQlr3Byw.0&searchStr=Linux%2C18.04%2Cx64%2CWebRender%2CShippable%2Copt%2CBrowsertime%2Cperformance%2Ctests%2Con%2CFirefox%2Ctest-linux1804-64-shippable-qr%2Fopt-browsertime-tp6-essential-firefox-bing-search%2Cbing&tochange=3338e8c3aaad554ffc57245d3897865695657a62&fromchange=3338e8c3aaad554ffc57245d3897865695657a62)
- `retry_id` the index of the retrigger - zero is first run of the job, from 1 to higher is retrigger …
=> Add TaskclusterMetadata to the alert summary API endpoint

treeherder/webapp/api/groups.py, treeherder/webapp/api/serializers.py
Work on `groupsummary` endpoint performance:
* Base the query on the JobLog table
* Apply filters/transformation within the query when possible
* Avoid using a serializer to handle query output
* Clean some Python code
I got interesting performance improvements with different data size:
* `master`
* Small : 619 ms ± 12.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* Medium : 1.88 s ± 99.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* Large : 12.2 s ± 412 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* `61e2076`
* Small : 481 ms ± 38.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* Medium : 536 ms ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* Large : 4.32 s ± 396 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
The results were …
=> Optimize summarygroup endpoint

ui/push-health/Test.jsx
Previously, select all checkboxes in the tests tab would always stay on the same position on screen due to a missing positive relative.
=> Fix select all test checkboxes not scrolling properly

tests/push_health/test_compare.py, treeherder/push_health/usage.py, treeherder/webapp/api/push.py, treeherder/webapp/api/serializers.py
* Related commits (revisions in the serializer) are now prefetched, but not limited to 20 results as before (django does not supports slicing a prefetch, but it is possible in SQL)
* Avoids 1 SQL request per Push
* 35516 / 1260041 Push entries are linked to more than 20 commits. 8 are linked to ~10k commits.
* Small data (`/api/project/autoland/push/?full=true&count=100&fromchange=<rev_id>`)
* `master` : 569 ms ± 5.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* `e6109c95`: 520 ms ± 4.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* Approx 9% time reduction
* Large data (`/api/project/autoland/push/?full=true&count=100`)
* `master` : 5.69 s ± 63.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* `e6109c95`: 1.87 s ± 69.5 ms per loop (mean ± std. dev. of 7 runs, …
=> Optimize push-list endpoint

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Currently, if you try to view failed task details on push health (e.g. [here](https://treeherder.mozilla.org/push-health/push?repo=try&revision=0ed64f3af4ed16738fdcb7881bb0e7199d4d1d94&testGroup=pr&selectedTest=browserbasecontenttestperformancebrowserstartupcontentjs&selectedTaskId=)), the error `TypeError: updatePinnedJob is not a function` appears. Since this function doesn't seem to consistently be defined, I've used optional chaining to avoid this error, and now I'm able to load the tasks in the development environment.
=> Bug 1852185 - Fix error viewing push health tasks

initialize_data.sh, tests/test_setup.py, treeherder/config/settings.py, treeherder/model/error_summary.py, treeherder/webapp/api/note.py
Reverts mozilla/treeherder#7818 because the `bug_suggestions` API endpoint can return an internal server error.
=> Revert "Bug 1851253 - store new failure lines in database for persistent stor…"

treeherder/model/fixtures/repository.json
We are just enabling performance alerting on Firefox iOS
Let me know if there are any issues @gmierz
=> Bug 1855222 -  Enable alerting on firefox iOS

schemas/performance-artifact.json
required for https://bugzilla.mozilla.org/show_bug.cgi?id=1848419, (android follow up of #7669)
=> Bug 1848419 - Add custom chromium-as-release app for android

tests/webapp/api/test_perfcompare_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py
For testing please use the staging credentials locally using docker.
Here's a [testing link](http://localhost:8000/api/perfcompare/results/?base_repository=mozilla-central&new_repository=mozilla-central&framework=1&interval=172800&no_subtests=true&base_revision=ffe93e4e0835b70448d485c82e3900bc4f47f205&new_revision=4124eee4f58ca46e13cb937c757a2fe1875120f0). You can edit this link to contain other repositories and revisions.
=> Add field lower_is_better to the perfcompare endpoint

ui/perfherder/compare/CompareSubtestsView.jsx, ui/perfherder/compare/CompareView.jsx
This patch modified the CompareView graphs link to use the `signature_id` instead of the `signature_hash`. This fixes an issue where the graphs link for `custom-car` results would redirect to `chrome` or `chromium` results instead.
Locally, you can test this by going to here (note you'll need to change the domain to the localhost): `https://treeherder.mozilla.org/perfherder/compare?originalProject=mozilla-central&newProject=mozilla-central&newRevision=a0f7b9f56d1f3dd6b66ba0417bab9acccddc3ad9&framework=13&originalRevision=b94f3d418f54f964368486a65cd5d15e828867db&page=25`
Next, find a test with `custom-car`, and click the `graph` link. This should bring you to an incorrect page (either chrome or chromium). With this patch applied, the link correctly redirects to a `custom-car` graph.
=> Bug 1840394 - Use signature_id instead of signature_hash for graphs link.

ui/shared/Revision.jsx
I believe this should fix bug 1444986, where the initial "Á" of Emilio's last name is being ignored, so that treeherder displays the incorrect initials "EL" instead of "EÁ".
=> Make the AuthorInitials function more i18n-friendly

ui/helpers/revision.js
To fix bug 1865684: capitalize the first (Unicode) letter in each name component, not the first (ASCII) alphanumeric.
=> Make the parseAuthor function more i18n-friendly

treeherder/etl/perf.py
This patch enables replicate ingestion into the `performance_datum_replicate` table on mozilla-central for only speedometer3 tests.
=> Bug 1866550 - Ingest replicates for speedometer3 on mozilla-central.

tests/ui/job-view/PerformanceTab_test.jsx, ui/job-view/details/tabs/PerformanceTab.jsx
For https://bugzilla.mozilla.org/show_bug.cgi?id=1861899
This changes the following:
* If the job is perf test, ignore `profile_resource-usage.json` and `profile_build_resources.json`
* "Open in Firefox Profiler" is shown only when there's profile for perf test
* "Generate performance profile" button is shown if there's no profile for perf test
* If there are multiple profiles, use most relevant profile
* the order is "*.zip would go first, then profile_resource-usage.json / profile_build_resources.json, then *.json", as mentioned in the bug
=> Bug 1861899 - Ignore non-perf-test profiles in perf test job performance tab.

treeherder/etl/management/commands/ingest.py
This patch moves the setup for the `--enable-eager-celery` setting out of `ingest_hg_push`, and into the `handle` method for the ingest command. This enables us to use the flag with all the different `ingestion_type`s.
For example, this patch allows us to parse, and ingest logs for individual tasks (very useful for perf tasks), and the following command now parses and ingests the perf data for a single task, previously it would only ingest the task itself: `docker-compose exec backend ./manage.py ingest task -p autoland --task-id BKhBS3GbTKeIXvTMRI26vg --enable-eager-celery`
=> Move setup for enable_eager_celery so it's set for all ingestion types.

treeherder/perf/fixtures/performance_bug_templates.yaml, ui/perfherder/alerts/StatusDropdown.jsx
Hi there :)
This PR strengthens the message of the alert comment to let them know the `mach try perf` command.
https://bugzilla.mozilla.org/show_bug.cgi?id=1848885
=> Bug 1848885 - Add mention of ./mach try perf --alert to comment 0

.pre-commit-config.yaml, README.md, pyproject.toml, setup.cfg, tox.ini, treeherder/perf/sheriffing_criteria/criteria_tracking.py, treeherder/push_health/utils.py
I replaced the flake8 pre-commit hook with ruff's and migrated the configuration found in:
- [setup.cfg](https://github.com/mozilla/treeherder/blob/e91eb1cd66c13ee592da45185c718276433e4976/setup.cfg#L1-L8)
- [tox.ini](https://github.com/mozilla/treeherder/blob/e91eb1cd66c13ee592da45185c718276433e4976/tox.ini#L58-L59)
To Ruff's configuration in `pyproject.toml`.
I kept the default Flake8 rules, `pyflakes` (`"F"` rule) and `pycodestyle` (`"E"` and `"W"` rules).
=> Bug 1823654 - Switch to Ruff for linting

ui/css/treeherder.css
For https://bugzilla.mozilla.org/show_bug.cgi?id=1864319
=> Bug 1864319 - Always show the scrollbar to avoid the layout change depending on the content.

ui/css/treeherder-job-buttons.css
for https://bugzilla.mozilla.org/show_bug.cgi?id=1766520
This changes the text size of the group button (collapsed button) to the same size as regular job button,
in order to avoid making the line taller.
=> Bug 1766520 - Use the same font size for job button and group button.

treeherder/perf/alerts.py
This patch fixes an issue where the absolute alert threshold was negative on an improvement, and this was checked against the alert threshold. This meant that improvements would never have an alert generated for them since they were always negative. With this change, improvement alerts will now be produced for tests using the absolute threshold.
=> Bug 1879316 - Use the absolute value of the delta in the alert threshold check.

ui/helpers/constants.js
This patch adds some proper names for the win11 reference hardware platforms.
=> Bug 1886208 - Add proper names for the win11 ref hw platforms.

ui/shared/BugFiler.jsx
Until now, 'application crashed' had been expected as prefix of the crash signature. Other text can be logged in its place, e.g. 'not thread-safe'.
=> Bug 1890349 - only check for crash signature to identify failure line as crash

treeherder/etl/management/commands/ingest.py
I change the function name handleMessage to the `handle_message`.
It was left out when the committer was working on it before. The handleMessage function does not exist anymore.
=> Change the function name according to N802 of pep8

requirements/common.in, requirements/common.txt
The API documentation page was broken: https://github.com/encode/django-rest-framework/issues/9291
Revert "Bump djangorestframework from 3.15.0 to 3.15.1"
This reverts commit 995ce0322734bdec2c641b304a80b275549824f3.
Revert "Bump djangorestframework from 3.14.0 to 3.15.0"
This reverts commit 9b9a11f1e93bccdf7086f6fa6d6f07db9ed0643b.
=> Revert djangorestframework from 3.15.1 to 3.14.0

schemas/performance-artifact.json
For https://bugzilla.mozilla.org/show_bug.cgi?id=1840660
=> Add Safari Tech Preview to perf schema (Bug 1840660)

ui/perfherder/compare/TableAverage.jsx
This patch adds a `%` sign to the standard deviation shown in compare view. It also adds a bit of text to clarify what the percentage means.
=> Add percentage to compare view standard deviation.

treeherder/webapp/api/intermittents_view.py
Else bugzilla's intermittent graph shows failures for incorrect days.
=> Bug 1902276 - sort failurecount data returned by API by date

tests/log_parser/test_store_failure_lines.py, treeherder/log_parser/failureline.py, treeherder/webapp/api/push.py
Django filters the group status data on the push ID in the `job` table where it is a foreign key. Moving the condition to the `push` table reduces query time (from 17-27s to 4-5s in a local development setup with production db queried).
=> Bug 1901687 - Look up push ID in push table for faster query

treeherder/perf/fixtures/performance_bug_templates.yaml
Hi there :)
The reason why it's not working is because there is no framework data[0]
So, I added the template data.
I can't reproduce the same environment for the issue as the real server in my local. You should test it in the staging before deploying the prod.
Let me know If there is anything to change it.
[0] api
https://treeherder.mozilla.org/api/performance/bug-template/?framework=15
[1] bug link
https://bugzilla.mozilla.org/show_bug.cgi?id=1900454
=> Bug 1900454 - "File Regression Bug for" doesn't work for mozpreftest test framework

ui/job-view/CustomJobActions.jsx
This is a regression from the upgrade to React 18. 'setState' (to set it from triggering state to non-triggering state) is asynchronous and the method in which it gets set calls this.close() itself. Put that call as callback of these setState calls.
=> Bug 1908442 - call close method for Custom Job Action/Custom Push Action modal in callback of setState

docker-compose.yml
`docker-compose up --build` was failing on machines with Apple Silicon with this error:
`no matching manifest for linux/arm64/v8 in the manifest list entries`
It looks like we fixed it a year ago in #7728, but "statsd" was added after that PR and broke the docker-compose builds with M1 chips again.
Similar to the previous PR, to test it you can run these commands in your terminal:
1. `docker system prune --all --volumes --force`
2. `docker-compose up --build`
=> Add platform to `statsd` in docker-compose.yml

treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, treeherder/webapp/api/utils.py
This PR fixes both [Bug 1910864](https://bugzilla.mozilla.org/show_bug.cgi?id=1910864) and [Bug 1887138](https://bugzilla.mozilla.org/show_bug.cgi?id=1887138).
First commit fixes Bug 1910864 and second commit fixes Bug 1887138. Please look at their commit messages to get more information about what they are doing. But to give you a quick overview about them:
1. First commit fixes how we send `"N/A"` for profile urls. Changed it to `None` there so we can see null properly on the frontend and omit them/
2. Second commit fixes various issues in the function where we generate the profile urls. But the most important issue was how we return incorrect profile urls sometimes because the caching mechanism only caches the last alert metadata inside a single push, and uses that for all the alerts.
=> Bug 1910864/1887138 - Fix how we handle profiler urls on the perfherder backend

ui/job-view/KeyboardShortcuts.jsx
Fixes a regression from the upgrade to React 18 (bug 1901015).
=> Bug 1915992 - wait for job to be pinned (and therefore pinboard to beshown) before setting focus to bug number input

treeherder/perf/fixtures/performance_bug_templates.yaml
[FXP-3647](https://mozilla-hub.atlassian.net/browse/FXP-3647) - Adds a link to the Running Alert Tests section of the Mach Try Perf page from Perfdocs and clarifies that all of the tests in the mentioned alert summary id will be executed
=> Bug 1907897 Include documentation about mach try perf --alert in comment 0

ui/helpers/constants.js
Just noticed that the 14.0 tests are sorted above the 13.0 ones and wanted to clean that up.
=> Fix Android platform sorting

treeherder/etl/management/commands/ingest.py
I looked whether I could change some tests but wasn't sure where to do that. Happy to do it if you think it's useful!
Otherwise I manually tested the patch locally.
=> Fix --last-n-pushes by providing the retrieved fetch_push_id to ingest_hg_pushes

ui/helpers/constants.js
A follow up of https://bugzilla.mozilla.org/show_bug.cgi?id=1925531
to get the pretty names for s24/p6
=> Update pixel 6 and samsung s24 naming

schemas/performance-artifact.json
As per 1867837 removing all mentions of chromium
=>  Bug 1867837 - Remove chromium from performance-artifact.json

treeherder/etl/perf.py
This patch enables replicates for the applink-startup tests.
=> Bug 1932211 - Enable replicates for applink-startup tests.

tests/ui/job-view/PerformanceTab_test.jsx, ui/helpers/url.js, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/tabs/PerformanceTab.jsx, ui/job-view/pushes/PushActionMenu.jsx
https://mozilla-hub.atlassian.net/browse/PCF-509
The following links were modified to redirect to PerfCompare instead of  Perfherder's Compare View
=> PCF-509 Replace the target for comparison buttons to perfcompare

package.json
It had been added initially as dependency of JSON5 which is not used anymore.
=> drop dependency on tsconfig-paths

ui/perfherder/alerts/AlertHeader.jsx, ui/perfherder/alerts/AlertTable.jsx
How to Change the Revision of an Alert
Prerequisites:
You must be authenticated to perform this action.
The "Reset Revision" button is only visible if the alert's initial revision has been modified.
---
Steps
1. Open Browser Developer Tools
Open your browser's console (usually by pressing F12 or Ctrl+Shift+I).
Navigate to the Network tab.
2. Use the "Take" Button
Click the Take button to generate a request to the backend.
3. Copy the Request as cURL
Locate the request generated by the Take button in the Network tab.
Right-click the request and select Copy > Copy all as cURL.
4. Modify the cURL Request
Paste the copied cURL request into a text editor.
Find and remove the assignee_username key from the request.
Replace it with:
"revision": "hash_revision"
(Replace hash_revision with the …
=> Implement revert button for revision (change culprit)

bin/pre_deploy, initialize_data.sh, tests/test_setup.py, treeherder/config/settings.py, treeherder/model/error_summary.py, treeherder/webapp/api/note.py
Same patch as https://github.com/mozilla/treeherder/commit/1310f34128061954f511a0c61cee3f0529e7c009 and I added cache table creation to the pre_deploy script.
=> Bug 1851253 - store new failure lines in database for persistent storage across reboots.

ui/helpers/constants.js
NSS started using these in bug 1831552.
=> Add pretty names for windows2022-{32,64}

tests/ui/job-view/stores/selectedJob_test.jsx, ui/job-view/redux/stores/pushes.js, ui/job-view/redux/stores/selectedJob.js
Those arguments are ignored when calling the action.
=> Clean redux unused action parameters

treeherder/model/migrations/0036_bugjobmap_internal_bug_refs.py, treeherder/model/migrations/0036_bugscache_init_autoincrement.py, treeherder/model/migrations/0037_bugjobmap_internal_bug_refs.py
Refs. https://github.com/mozilla/treeherder/pull/8512#issuecomment-2671449773
* Sets the auto increment Postgres sequence to the greatest current PK (max bugzilla ID) to avoid future conflicts.
* Use real reference to Bugscache in the BugJobMap migration (we cannot assume internal ID == bugzilla ID).
=> Bug 1923923 - Fix Bugscache and BugJobMap migrations

tests/webapp/api/test_perfcompare_api.py, treeherder/webapp/api/perfcompare_utils.py, treeherder/webapp/api/performance_data.py
I added a fix based on Julien's suggestion from [Bug 1947155 - Custom-car browser is being compared to chrome browser in this comparison](https://bugzilla.mozilla.org/show_bug.cgi?id=1947155)). 
See also: [Bug 1942904 - Perfcompare comparing incorrect applications (e.g. chrome-m vs fenix as opposed to fenix vs fenix)](https://bugzilla.mozilla.org/show_bug.cgi?id=1942904)
=> Bug 1942904 - Perfcompare comparing incorrect applications (e.g. chrome-m vs fenix as opposed to fenix vs fenix)

tests/ui/perfherder/legend_card_test.jsx, tests/webapp/api/test_performance_data_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/performance_serializers.py, ui/perfherder/graphs/LegendCard.jsx, ui/perfherder/perf-helpers/helpers.js
For testing locally, either use the staging connection or ingest some alerts to look at the corresponding graphs. 
alert_change_type and alert_threshold can have a null value.
=> Display the should_alert field in Graphs Legend

treeherder/perf/fixtures/performance_bug_templates.yaml, ui/perfherder/alerts/StatusDropdown.jsx
This patch changes the alert comment #0 to make some information more accessible for developers. It moves the backout message to the top, and follows it with a link to some documentation. At the same time, some additional info is provided for where to reach out to people for help.
The wiki link to the sheriffing docs is also removed since it hasn't been useful for developers. The backout mention is also changed to mention that we're only looking for an acknowledgment, and an investigation to begin within 3 business days (instead of a plan).
=> Bug 1947517 - Rework the alert comment to make information more accessible.

tests/etl/test_load_artifacts.py, treeherder/model/error_summary.py, treeherder/webapp/api/note.py
I want to figure out how to test this.  Also some of this might be a little overkill.
=> use in memory cache in parallel with db cache, convert keys to be date specific

tests/ui/mock/alert_summaries.json, tests/webapp/api/test_performance_alertsummary_api.py, treeherder/webapp/api/performance_serializers.py, ui/perfherder/alerts/AlertHeader.jsx
=> Highlight duplicated alert summaries for the same revision

tests/webapp/api/test_hash_api.py, treeherder/webapp/api/hash.py, treeherder/webapp/api/serializers.py
The tocommit API currently searches for substrings across all commits and all repositories, this patch limits the search to commits in try and commits in the past 2 months. The search times went from 14-15 seconds to under 1 second now We do this by passing a date parameter for each hash and searching for +1 and -2 around the date(I assumed timezones may cause some issues so to be safe I expanded the range a bit)
=> Bug 1962486 - Improve Performance of tocommit API

ui/shared/Revision.jsx
The "Revert" commit messages are from the migration to Git VCS which has no `hg oops` equivalent as we speak.
=> Color commits which start with "Revert" red as backouts.

tests/ui/job-view/App_test.jsx, tests/ui/shared/FailureSummaryTab_test.jsx, ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
Regression from 74c6fdb9ca9307e66d0fd4896dd91920604d5c0f
=> Bug 1961788 - correctly set repoName for log link in failure line

treeherder/model/error_summary.py
fix some edge cases.  I see that we continue to have keys up to 3 months old.  Looking in the database I don't see that we are retriggering old jobs- this patch really does 2 things:
1) fix bug to actually check for existing date
2) key 21 day cache off of "today", not job submit time.
=> small tweaks to handle edge cases in new failures

ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
This is needed, e.g. for
* permanent failures of regular tasks which need to be tracked and don't require a backout like backlog tasks
* central-as-beta simulations failures or similar
=> Bug 1967629 - add button to force filing a bug with bugfiler, omitting internal issue

ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
Single tracking bugs have been filed by default for some time now. There are few non-single tracking bugs left where single tracking bugs would be filed.
=> Bug 1968693 - remove rules differentiating between 'single tracking bugs' and other bugs

treeherder/perf/auto_perf_sheriffing/sherlock.py
Currently, Sherlock runs at the 40 minute mark every hour. This patch ensures that telemetry will only run once per day instead of every hour.
=> Only run telemetry alerting once per day.

treeherder/perf/auto_perf_sheriffing/sherlock.py
This patch fixes an issue where the telemetry start time was always returning False because the checks consider the 0 hour as being less than the 23rd hour. Starting an hour earlier fixes this. The start/run time is arbitrary, and changing it won't affect anything.
=> Start telemetry earlier to fix a run time issue.

docker-compose.yml, treeherder/perf/auto_perf_sheriffing/sherlock.py
In prod, we can't use the mozdata project since our service account is defined in a separate one. This patch fixes the issue by using the setting from `GCLOUD_PROJECT` to specify which project we should be querying in.
=> Use GCLOUD_PROJECT for setting the BigQuery projcet to use.

treeherder/etl/perf.py
Perf team has requested to have:
- tab restore on central and autoland report replicates
- applink-startup report replicates on autoland
=> Bug 1977456 - Enable Replicates on applink startup tests. r?#perftest

tests/conftest.py, tests/webapp/api/test_performance_alertsummary_api.py, treeherder/webapp/api/performance_data.py
This patch resolves an issue that causes duplicate alert summaries to be returned from the API because of the OR filter on a query that contains a ManyToOne field. Specifically, for each alert that an alert summary had, a duplicate alert summary would be created.
=> Don't use OR with tables that contain many-to-many/one-to-many fields or associations.

ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/summary/SummaryPanel.jsx
The resource use profiles are very useful to figure out what took time in a job, but they are currently almost undiscoverable (you need to switch to the artifacts tab to find them). I think being able to open them with a single click would be useful (and I'm hoping to add more information in them in the future to make them even more useful).
=> Show a button to open resource use profiles in the Action Bar

ui/job-view/details/tabs/TabsPanel.jsx, ui/shared/JobArtifacts.jsx, ui/shared/tabs/failureSummary/FailureSummaryTab.jsx, ui/shared/tabs/failureSummary/SuggestionsListItem.jsx
For both mochitests and xpcshell tests, pushing to try with `./mach try fuzzy --env MOZ_PROFILER_STARTUP=1` will make the test harnesses upload as an artifact a profile of the failing test runs. It would be nice to make it possible to open these profiles with a single click from the Failure Summary.
Example for xpcshell tests: http://localhost:5000/jobs?repo=try&selectedTaskRun=aumhVXDvRm2gF0IfGBlfxg.0&revision=8981a5b1ae891370b62cfe0b4f236f94c2c0104d
Example for mochitests: http://localhost:5000/jobs?repo=try&selectedTaskRun=HKDJwSO_SSmp7ZxY0wd1nQ.0&revision=8981a5b1ae891370b62cfe0b4f236f94c2c0104d
=> Show 'open in Firefox Profiler' links in failure summary lines referencing profile artifacts

treeherder/etl/perf.py
Missed adding the homeview startup test in this bug where we intended to enable for all of the startup tests: https://bugzilla.mozilla.org/show_bug.cgi?id=1977456
=> Bug 1980506 - Enable replicates on for homeview startup test as well. r?#perftest

tests/ui/job-view/App_test.jsx, tests/ui/shared/FailureSummaryTab_test.jsx, ui/job-view/details/DetailsPanel.jsx, ui/job-view/details/tabs/TabsPanel.jsx, ui/push-health/details/DetailsPanel.jsx, ui/shared/tabs/failureSummary/FailureSummaryTab.jsx
This is done by ensuring network requests are done in parallel:
- if we are sure the failure summary tab will be selected, do not wait for the /api/project/try/performance/signatures/?id= request to finish before removing the loading throbber (setting jobDetailLoading to false)
- start fetching /api/project/try/performance/signatures/?id= immediately after the /api/project/try/performance/data/?job_id= request completes (instead of waiting for all the requests in jobPromise, jobLogUrlPromise and builtFromArtifactPromise promises to complete).
- do the /api/project/try/note/?job_id= and /api/project/try/bug-job-map/?job_id= requests in parallel with the other set of requests (ie call updateClassifications() in parallel rather than after the first set of promises has resolved).
- do the …
=> Bug 1967984 - show the Failure Summary faster when selecting a job

ui/job-view/App.jsx
I profiled loading the treeherder homepage. We wait for 2 pairs of requests before loading the list of jobs: https://share.firefox.dev/4liIF28
This PR trivially reduces this to waiting for one group of 4 requests. Profile of loading the same page with the PR applied: https://share.firefox.dev/3HeQY0D
=> Do not await the /api/performance/framework/ request when loading treeherder

.gitignore, .vscode/settings.json, docker-compose.yml, eslint.config.mjs, tests/ui/infra-compare/InfraCompare.test.jsx, tests/ui/job-view/headerbars/FiltersMenu.test.jsx, tests/ui/job-view/pushes/JobsAndGroups.test.jsx, tests/ui/shared/BugFiler.test.jsx, tests/ui/shared/RevisionList.test.jsx, ui/infra-compare/InfraCompare.jsx, ui/job-view/headerbars/FiltersMenu.jsx, ui/job-view/pushes/JobsAndGroups.jsx, ui/shared/BugFiler.jsx, ui/shared/RevisionList.jsx, yarn.lock
This fixes several web console errors that don't require large package changes.  Also added several new unit tests to cover the changed files.
This also includes a few config changes:
* VS Code settings to use the .eslint.config.mjs` and `.prettierrc`
* `.gitignore` Roo Code Plugin specific files
`reactstrap` is the culprit of several web console errors.  This will be handled in an upcoming PR.
=> fix: Web console errors that don't require package changes

ui/helpers/constants.js, ui/job-view/KeyboardShortcuts.jsx, ui/job-view/details/summary/ActionBar.jsx, ui/job-view/details/summary/LogItem.jsx, ui/shared/ShortcutTable.jsx
Also, document existing ActionBar shortcuts in the button tooltips. Someone suggested doing that when I told them an 'r' shortcut exists to retrigger. And I discovered today while working on this patch that the 'l' shortcut to open the log exists. And it is super useful so I wish I had discovered it earlier.
=> Add a keyboard shortcut to open resource usage profiles

tests/ui/job-view/PushList_test.jsx, ui/job-view/pushes/PushList.jsx, ui/job-view/redux/stores/pushes.js
When loading the treeherder jobs view with the "fromchange" parameter specified in the url, sometimes the parameter is respected, sometimes it isn't. That's due to a race between the fetchPushes() call made by App.jsx (since https://github.com/mozilla/treeherder/pull/8895/commits/9375945f941e278bd458378886fa025647c8d79b) and the fetchPushes call from PushList.jsx.
In that commit I tried to add a pre-fetch without removing the fetch that was triggered from the PushList component, but now I wonder why I made it so complicated. Unless I'm missing something, the PushList component will only exist once, so it shouldn't need to fetch again.
My confidence level in this PR isn't very high. It fixes the bug locally, but I'm not convinced yet it doesn't cause other regressions (and there's at least …
=> Bug 1982521 - Avoid calling fetchPushes from both App and PushList.

ui/css/intermittent-failures.css, ui/intermittent-failures/App.jsx, ui/intermittent-failures/BugDetailsView.jsx, ui/intermittent-failures/Layout.jsx, ui/intermittent-failures/MainView.jsx, ui/intermittent-failures/helpers.jsx
Before:
After:
Summary of the changes:
- Use the full available width;
- Adjust the width of columns to limit wasted space;
- Remove the "Revision" column and make the "Push Time" values link to the jobs;
- Merge the platform, build type and test suite columns into one "Job Name" column matching the job names we show in the log viewer;
- Hide the machine names for virtual machines. On hover show "virtual machine" in gray text to indicate why the cell was empty;
- Show the failure lines directly instead of hiding them in a tooltips;
- Fix the various filter boxes to have a placeholder text, a clear button, and filter by regexp rather than by prefix;
- Show the full cell content as a tooltip, so the values of cells cropped with an ellipsis can still be seen;
- Show 100 failures by default …
=> Cleanup bugdetails

treeherder/log_parser/failureline.py, treeherder/webapp/api/push.py
This reverts back to the legacy API, but takes advantage of the new DB indexes.  Testing on Staging environment showed this is the current fastest API.
=> fix: Use original group_results api with optimized indexes

tests/webapp/api/test_performance_alertsummary_api.py, treeherder/webapp/api/performance_data.py, treeherder/webapp/api/utils.py, ui/perfherder/alerts/AlertsView.jsx, ui/perfherder/alerts/AlertsViewControls.jsx
This PR adds functionality for filtering the list of available alert summaries to only show the sheriffed framework alerts and exclude the non-sheriffed ones (for example, the platform_microbench alerts). 
Selecting the "all sheriffed frameworks" option in the dropdown will only display the sheriffed framework alerts.
=> FXP-4047 Implement functionality to filter by all sheriffed frameworks in Alerts View

tests/log_parser/test_error_parser.py, treeherder/log_parser/parsers.py
`Assertion failure` without further context in the same log line is sometimes logged for marionette, mochitest and web platform tests. The ones checked were not fatal but e.g. failures related to asynchronous tab switching.
=> Bug 1991905 - do not use log line which contains 'Assertion failure' without further context as failure line
